### ISSUE TITLE
Investigate Rust backend exception? net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8819] opened 2021-05-13 16:31 UTC
@david-allison-1 

###### Reproduction Steps

```


  | --------- beginning of main
-- | --
1 | 05-13 10:27:48.639 I/AnkiDroid(20564): AnkiActivity::onStart - DeckPicker
2 | 05-13 10:27:48.664 I/AnkiDroid(20564): AnkiActivity::onResume - DeckPicker
3 | 05-13 10:27:48.860 I/AnkiDroid(20564): DeckPicker:: Selected deck with id 1492865350031
4 | 05-13 10:27:48.884 I/AnkiDroid(20564): Begin openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
5 | 05-13 10:27:48.892 I/AnkiDroid(20564): Opening rust backend. Server: false. Langs: 'en', path:
6 | 05-13 10:27:48.934 I/AnkiDroid(20564): Opening Collection: '/storage/emulated/0/AnkiDroid/collection.anki2' '' '' ''
7 | 05-13  10:27:48.971 W/AnkiDroid(20564): DeckPicker/  net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException:  Anki already open, or media currently syncing.
8 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at net.ankiweb.rsdroid.RustBackendImpl.validateMessage(RustBackendImpl.java:3)
9 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at net.ankiweb.rsdroid.BackendV1Impl.openAnkiDroidCollection(BackendV1Impl.java:6)
10 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at net.ankiweb.rsdroid.BackendMutex.openAnkiDroidCollection(BackendMutex.java:2)
11 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at net.ankiweb.rsdroid.BackendUtils.openAnkiDroidCollection(BackendUtils.java:1)
12 | 05-13  10:27:48.971 W/AnkiDroid(20564): 	at  net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.createRustSupportSQLiteDatabase(RustSupportSQLiteOpenHelper.java:4)
13 | 05-13  10:27:48.971 W/AnkiDroid(20564): 	at  net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.getWritableDatabase(RustSupportSQLiteOpenHelper.java:2)
14 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.libanki.DB.<init>(DB.java:9)
15 | 05-13  10:27:48.971 W/AnkiDroid(20564): 	at  com.ichi2.libanki.backend.RustDroidBackend.openCollectionDatabase(RustDroidBackend.java:1)
16 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.libanki.Storage.Collection(Storage.java:6)
17 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:8)
18 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
19 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:1)
20 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.DeckPicker.handleDeckSelection(DeckPicker.java:1)
21 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.DeckPicker.onDeckClick(DeckPicker.java:6)
22 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.DeckPicker.lambda$new$1(DeckPicker.java:1)
23 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.DeckPicker.l(Unknown Source:0)
24 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.n2.onClick(Unknown Source:2)
25 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.view.View.performClick(View.java:7448)
26 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.view.View.performClickInternal(View.java:7425)
27 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.view.View.access$3600(View.java:810)
28 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.view.View$PerformClick.run(View.java:28305)
29 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.os.Handler.handleCallback(Handler.java:938)
30 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.os.Handler.dispatchMessage(Handler.java:99)
31 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.os.Looper.loop(Looper.java:223)
32 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
33 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at java.lang.reflect.Method.invoke(Native Method)
34 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
35 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
36 | 05-13 10:27:48.971 W/AnkiDroid(20564):
37 | 05-13  10:27:48.971 W/AnkiDroid(20564):  net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException:  Anki already open, or media currently syncing.
38 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at net.ankiweb.rsdroid.RustBackendImpl.validateMessage(RustBackendImpl.java:3)
39 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at net.ankiweb.rsdroid.BackendV1Impl.openAnkiDroidCollection(BackendV1Impl.java:6)
40 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at net.ankiweb.rsdroid.BackendMutex.openAnkiDroidCollection(BackendMutex.java:2)
41 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at net.ankiweb.rsdroid.BackendUtils.openAnkiDroidCollection(BackendUtils.java:1)
42 | 05-13  10:27:48.971 W/AnkiDroid(20564): 	at  net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.createRustSupportSQLiteDatabase(RustSupportSQLiteOpenHelper.java:4)
43 | 05-13  10:27:48.971 W/AnkiDroid(20564): 	at  net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.getWritableDatabase(RustSupportSQLiteOpenHelper.java:2)
44 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.libanki.DB.<init>(DB.java:9)
45 | 05-13  10:27:48.971 W/AnkiDroid(20564): 	at  com.ichi2.libanki.backend.RustDroidBackend.openCollectionDatabase(RustDroidBackend.java:1)
46 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.libanki.Storage.Collection(Storage.java:6)
47 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:8)
48 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
49 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:1)
50 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.DeckPicker.handleDeckSelection(DeckPicker.java:1)
51 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.DeckPicker.onDeckClick(DeckPicker.java:6)
52 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.DeckPicker.lambda$new$1(DeckPicker.java:1)
53 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.DeckPicker.l(Unknown Source:0)
54 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.ichi2.anki.n2.onClick(Unknown Source:2)
55 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.view.View.performClick(View.java:7448)
56 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.view.View.performClickInternal(View.java:7425)
57 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.view.View.access$3600(View.java:810)
58 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.view.View$PerformClick.run(View.java:28305)
59 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.os.Handler.handleCallback(Handler.java:938)
60 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.os.Handler.dispatchMessage(Handler.java:99)
61 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.os.Looper.loop(Looper.java:223)
62 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
63 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at java.lang.reflect.Method.invoke(Native Method)
64 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
65 | 05-13 10:27:48.971 W/AnkiDroid(20564): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
66 |  


```

###### Actual Result

```
net.ankiweb.rsdroid.BackendException$BackendDbException$BackendDbLockedException: Anki already open, or media currently syncing.
at net.ankiweb.rsdroid.RustBackendImpl.validateMessage(RustBackendImpl.java:3)
at net.ankiweb.rsdroid.BackendV1Impl.openAnkiDroidCollection(BackendV1Impl.java:6)
at net.ankiweb.rsdroid.BackendMutex.openAnkiDroidCollection(BackendMutex.java:2)
at net.ankiweb.rsdroid.BackendUtils.openAnkiDroidCollection(BackendUtils.java:1)
at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.createRustSupportSQLiteDatabase(RustSupportSQLiteOpenHelper.java:4)
at net.ankiweb.rsdroid.database.RustSupportSQLiteOpenHelper.getWritableDatabase(RustSupportSQLiteOpenHelper.java:2)
at com.ichi2.libanki.DB.<init>(DB.java:9)
at com.ichi2.libanki.backend.RustDroidBackend.openCollectionDatabase(RustDroidBackend.java:1)
at com.ichi2.libanki.Storage.Collection(Storage.java:6)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:8)
at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
at com.ichi2.anki.AnkiActivity.getCol(AnkiActivity.java:1)
at com.ichi2.anki.DeckPicker.handleDeckSelection(DeckPicker.java:1)
at com.ichi2.anki.DeckPicker.onDeckClick(DeckPicker.java:6)
at com.ichi2.anki.DeckPicker.lambda$new$1(DeckPicker.java:1)
at com.ichi2.anki.DeckPicker.l(Unknown Source:0)
at com.ichi2.anki.n2.onClick(Unknown Source:2)
at android.view.View.performClick(View.java:7448)
at android.view.View.performClickInternal(View.java:7425)
at android.view.View.access$3600(View.java:810)
at android.view.View$PerformClick.run(View.java:28305)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7660)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

###### Debug info

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/a40dbaab-8619-4876-acb4-a44a4ec69df2

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment] 2021-05-13 17:13
Needs further investigation.

This is related to the fact that AnkiDroid now locks the database when it's open. 

I hope that this is going to be due to two AnkiDroid instances (parallel) open on the same collection. 

It could also be a race condition between clicking sync (closing the database in some cases), and then quickly tapping on a deck, but I don't feel this is the case given the logs

I don't understand how:

* AnkiDroid has been opened: a deck list is showing (`onStart` -> `onResume` -> `select deck`)
* But: the collection is not open after `onResume` is called

**Comment by david-allison-1** [comment] 2021-05-13 17:15
We can fix this: check that the collection is open onStart/onResume (if appropriate), then try to open it, and if not, display a `database locked` screeen.

But this doesn't explain /why/ it happens, it only patches the crash

**Comment by mikehardy** [comment] 2021-05-13 19:24
FWIW - the alpha test group has approximately 10,000 users and I'd guess we have had roughly 5000-10000 active installs over time of Rust backends. So this is necessarily infrequent, whatever it is. Patching the crash and asking for more information in a dialog somehow might be "sufficient" as a first cut at a real fix via understanding

**Comment by mikehardy** [comment] 2021-05-22 20:04
I'm not going to block 2.15 on this, we don't see it very often as far as I can tell.

**Comment by david-allison-1** [comment] 2021-09-29 02:46
Needs investigation on the next round. I've added a "database locked" screen, but haven't confirmed if this fixed the issue

**Comment by dae** [comment] 2022-07-18 07:08
Assuming this is rare, I guess it can be closed?

**Comment by BrayanDSO** [comment] 2023-01-06 19:02
> Assuming this is rare, I guess it can be closed?

I think the same

**Closed by BrayanDSO** 2023-01-06 19:02 UTC
Labels: Bug, Help Wanted, Keep Open
