### ISSUE TITLE
No Interface while learning cards

### ISSUE THREAD

**Issue by Mannes1988** [ankidroid/Anki-Android#7450] opened 2020-10-23 13:43 UTC
Hi,

When I'm learning cards the interface vanish after I clicked the answer button on the first card.
 
![Capture+_2020-10-23-14-24-55](https://user-images.githubusercontent.com/72976663/97009458-66b48c80-1544-11eb-908d-b9d27603ce47.png)

You can't see the interface but it is still there. I can do any action. Chose next learning interval, open card menu etc. Everywhere else everything is ok and the problem occur in every deck.
New installation didn't help.

Can you help me? It's annoying and I don't want to change the app.

Jannes

PS, it's my first post on GitHub so please be indulgent.

###### Debug info
AnkiDroid Version = 2.13.5

Android Version = 8.0.0

ACRA UUID = 0eac72c6-7c99-40f9-a763-302d120b99cb

Scheduler = std

###### Research

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment] 2020-10-23 15:23
Hi @Mannes1988, thanks for the report

This is a duplicate of #7369. I have added instructions to that issue ]on how to work around the issue, and how you can help us diagnose and solve it](https://github.com/ankidroid/Anki-Android/issues/7369#issuecomment-714875650).

All the best,

David

**Closed** 2020-10-23 15:23 UTC
Labels: Duplicate
