### ISSUE TITLE
Hello, may I contribute with this app? I will create a new logo for you.

### ISSUE THREAD

**Issue by ibnu-djamil** [ankidroid/Anki-Android#4837] opened 2018-05-03 10:41 UTC
of course a more interesting logo

**Comment by oldmud0** [comment] 2018-05-09 04:26
You don't have to wait for approval - just do it and show us!

**Comment by timrae** [comment] 2018-05-15 21:21
Closing as it's not a bug, please just open a pull request and/or post some screenshots to the user forum for feedback.

**Closed by timrae** 2018-05-15 21:21 UTC
