### ISSUE TITLE
   collection not opened

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3292] opened 2015-07-28 10:48 UTC
Originally reported on Google Code with ID 2396
```
What steps will reproduce the problem?
1.when i clicked the anki icon
2.error reporting page will be shown
3.cant get to my Deck it sats corrupted

What is the expected output? What do you see instead?
Error message says"Database could not be opened its either not a real Anki database
or its been corrupted"
Can't even use the options to fix the problem

Does it happen again every time you repeat the steps above? Or did it
happen only one time? It happens all the time whenever i click the icon i land in tge
feedback page..but can't access the decks


What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title)
On what version of Android? (Home screen > menu > About phone > Android
version)


If it is a crash or "Force close" and you can reproduce it, the following
would help immensely: 1) Install the "SendLog" app, 2) Reproduce the crash,
3) Immediately after, launch SendLog, 4) Attach the resulting file to this
report. That will make the bug much easier to fix.


Please provide any additional information below.

```

Reported by `fshabee` on 2014-11-10 14:52:20

**Comment by timrae** [comment] 2015-07-28 13:28
duplicate of #3576

**Closed by timrae** 2015-07-28 13:28 UTC
Labels: bug, Priority-Critical, waitingforfeedback
