### ISSUE TITLE
[BUG]: New Cards/Day limit for "Today only" is Incompatible with Custom Study Session's limit 

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16099] opened 2024-04-05 05:51 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Try increasing new card limit for today in Custom Study by any number y
2. Review those cards
3. Now in Deck Options, increase New Cards/Day for "Today" by any number x

### Expected behaviour

x amount of New Cards is shown this time

### Actual behaviour

x+y amount of New Cards are shown

### Debug info

```text
AnkiDroid Version = 2.18alpha8 (6fc26947fd31743bc83e68f17ae7fec64bfa8e62)

Backend Version = provider(?) (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = null

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by brishtibheja** [comment] 2024-04-05 06:04
I saw this just now while scrolling: #16017
Could this might be related?

**Comment by brishtibheja** [comment] 2024-04-11 11:24
@BrayanDSO I think this is fixed in the latest alpha.

**Comment by BrayanDSO** [comment] 2024-04-11 11:48
The report is also from the latest alpha. Are you sure that the issue exists or that is doesn't exist?

**Comment by brishtibheja** [comment] 2024-04-11 12:17
I can't reproduce it now so I thought I might have installed a newer version. (I am bad at recalling when I did what)
I am trying this right now and Today Only limit is working fine although it clearly didn't before.

**Comment by BrayanDSO** [comment] 2024-05-11 10:05
I'm going to close this as can't reproduce

**Closed by BrayanDSO** 2024-05-11 10:05 UTC
Labels: Bug, Needs Triage
