### ISSUE TITLE
[Bug] Cannot sync collection freshing downloaded (& checked) from AnkiWeb

### ISSUE THREAD

**Issue by twwn** [ankidroid/Anki-Android#12128] opened 2022-08-21 17:25 UTC
###### Reproduction Steps

1. Do some incompatible note type changes on Anki Desktop (git)
2. AnkiDroid (2.16a79) now demands a full sync
3. Pick AnkiWeb's state (download starts at ~243000 KB, for whatever reason)
4. Try sync again, AnkiDroid demands DB check
5. Do so (10 MB saved)
6. Try sync again, AnkiDroid again claims the states are incompatible

###### Expected Result

Sync

###### Actual Result

Stuck in that full sync loop

###### Debug info
AnkiDroid Version = 2.16alpha79

Android Version = 12

Manufacturer = OnePlus

Model = IN2023

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; IN2023 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.2 Mobile Safari/537.36

ACRA UUID = f5eb4f44-ef2c-405b-a4f6-12303f2ae0f9

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

(Entirely unrelated issue: The time the bars are shown when "Fullscreen mode" is set to "hide system bars" is far too little. The same gesture calls down Android's own bar, and by the time you've closed that again, you've got less than half a second to hit anything on AnkiDroid's bar before it hides again.)

**Comment by twwn** [comment] 2022-08-21 17:39
Alright, indirect fix:

* Call database check on Anki Desktop: "Deleted 2 cards with missing note." [Without telling me or writing in the relevant log which 2 I just lost. Neat.]
* Full sync that to AnkiWeb
* Download that to AnkiDroid – which now no longer wants a DB check & everything is fine again.

So seems there's a major & minor bug respectively:
* The "missing note" check is missing or bugged on AnkiDroid.
* The DB download form somehow starts counting at the DB size ("started" downloading "at" ~243000 KB, finished "at" ~486000 KB).

**Comment by mikehardy** [comment] 2022-08-21 20:46
Interesting :thinking: can I ask if you have enabled the "new backend schema" in the settings -> advanced section?

I ask because we have actually just completely replaced the sync and the database check with the exact same routines that Desktop uses (literally packaging the same Desktop code into a library and we use it in AnkiDroid now) but only if you've selected that brand new "new backend schema" preference.

If you weren't using that, then I'm afraid this may indeed be a bug, and may be reproducible, but won't really matter since we'll be using Desktop's code as the default shortly.

**Comment by twwn** [comment] 2022-08-22 07:51
I see. No, it's not enabled yet. Then I guess if this also covers the minor download issue, this can be closed.

**Comment by mikehardy** [comment] 2022-08-22 13:03
I *think* it will cover those cases, so I will close this. Although with adoption of any new system (and even though the code is in use / deployed already for all Anki Desktop users it will be new to us) we may discover new issues with the new system. If you notice anything with the final release of 2.16 (or if happen to update to an alpha where we turn the new stuff on by default) please do let us know, we're listening

Cheers

**Closed by mikehardy** 2022-08-22 13:03 UTC
