### ISSUE TITLE
[BUG]: Bottom statistics line is too long in some languages

### ISSUE THREAD

**Issue by Seagist** [ankidroid/Anki-Android#15031] opened 2023-12-19 13:43 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Set a language, in which the bottom statistics line has longer text than in English. For example, Japanese or Russian.
2. Do some reviews. Having more digits in numbers inside the line makes it worse.

Optional: Use a phone with rounded screen corners. But with a long enough study session even without them the text might not fit.

### Expected behaviour

Text fits well, like in English.

<details> 
  <summary>Screenshot in English</summary>
   
![Screenshot_2023-12-19-19-13-53-753_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/61379157/9712993c-8ebd-4f6d-a12a-e8ca7ddab193) 
</details>

### Actual behaviour

It barely fits on the screenshot, but consier that due rounded screen corners (which a lot of phones have these days) the text ends up being significantly truncated on both sides. If I remember correctly, time spent per card wasn't there in 2.16.

<details> 
  <summary>Screenshot in Japanese</summary>
   
![Screenshot_2023-12-19-19-13-33-666_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/61379157/5709dd8f-752b-49ac-96ec-789402b78861)
</details>
<details> 
  <summary>Screenshot in Russian</summary>
   
![Screenshot_2023-12-19-19-14-11-012_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/61379157/5a3f4a4e-3513-4e15-b63c-5a45622d0e77)
</details>

### Debug info

```text
AnkiDroid Version = 2.17alpha12 (3c81b124d2ca555d48e82e0f2d31d8ed13d3b662)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 12 (SDK 31)

ProductFlavor = full

Manufacturer = Xiaomi

Model = POCO F2 Pro

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; POCO F2 Pro Build/SKQ1.211006.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = e5707c1e-d95e-49d0-804d-d70217e92125

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2023-12-19 14:20
Thanks for the report!

Closing as duplicate of:

* https://github.com/ankidroid/Anki-Android/issues/14641

**Closed by david-allison** 2023-12-19 14:20 UTC
Labels: Bug, Needs Triage
