### ISSUE TITLE
Images not exhibited if there is the html global attribute "style" in the <img> tag

### ISSUE THREAD

**Issue by hugomarins** [ankidroid/Anki-Android#6118] opened 2020-05-07 13:43 UTC
###### Reproduction Steps

1. Sometimes I insert a "style" or "width" or "height" attribute in the <img> tag, in order to make its presentation better in the computer version of Anki. E.g.:
`<img src="paste-cc910fe1adb2784cbca44d53a3c11989dd7fb103.png" style="MAX-height:300px;">`
2. Strangely, in AnkiDroid *some* of this images with the attribute "style" or "width" or "height" are not exhibited in the reviewer mode.
3. If I open "Edit Note" and then press the clip icon, the image is shown properly in the edition field, but if I return to the reviewer mode, the image is not shown.
4. This happens to many of my notes, whatever note type is being used. This is making difficult to me to use AnkiDroid to review my cards, as the only solution is to bury the card to answer they another time when I'm using the computer version (Windows).

###### Expected Result

The images with attributes in its <img> tag should be shown regularly.

###### Actual Result

Some images with attributes in its <img> tag like "style" are not being shown.

###### Debug info
AnkiDroid Version = 2.9.7

Android Version = 10

ACRA UUID = a0d461aa-35d6-44e3-8d07-4c709fc07481

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

![1 Review mode - img not shown](https://user-images.githubusercontent.com/54500828/81301220-23766800-904f-11ea-8583-a58b280421e4.jpg)
![2 Edit Note](https://user-images.githubusercontent.com/54500828/81301254-2ec99380-904f-11ea-8f40-afafabd3e039.jpg)
![3 Edition field](https://user-images.githubusercontent.com/54500828/81301282-3a1cbf00-904f-11ea-9814-828d220c5f8f.jpg)

**Comment by mikehardy** [comment] 2020-05-07 13:53
Can you please sign up for beta testing so you receive 2.10beta3 from the play store and let us know if you can still reproduce? https://docs.ankidroid.org/#betaTesting

**Comment by hugomarins** [comment] 2020-05-07 15:28
Mike,

I upgraded to 2.10beta3 and that specific card worked properly. I'll keep testing and, if the problem still occur in any notes, I'll let you know!

Thanks a lot!

**Comment by mikehardy** [comment] 2020-05-07 15:43
Glad to hear that, there was work in that area so inability to reproduce was the hope and is not unexpected. I'm going to go ahead and close this but obviously we'll reopen if you have a reproduction scenario. In the meantime, thanks for testing the beta - I'm hoping to do a full release in a couple days because it's pretty quiet so far on issue reports for it, so if you see anything getting a solid report is gold. Cheers

**Closed by mikehardy** 2020-05-07 15:43 UTC
Labels: Waiting For Feedback
