### ISSUE TITLE
[Bug] Error when app is opened while being offline

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#12821] opened 2022-11-12 13:27 UTC
When I open the latest alpha version of the app while being offline, I get the following error message saying, "Please check your internet connection."
![Screenshot_20221112-071038](https://user-images.githubusercontent.com/92206575/201476242-3042e8a6-1eb5-4ba2-8485-5f381e8bb790.jpg)

Since I didn't request any kind of syncing, getting this message is unexpected. Also, the latest stable version (v2.15.6) doesn't show this error.

###### Debug info
AnkiDroid Version = 2.16alpha89

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.91 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2022-11-12 14:56
That's unexpected, are you certain you don't have auto sync set up on app startup? I can't think why AnkiDroid would try to access the internet on startup, and I can't think why that dialog would be displayed if there wasn't an attempt at internet access. So auto-sync is all I can think of :thinking:

**Comment by user1823** [comment] 2022-11-12 16:01
The auto sync is turned off. (Assuming the below one is the setting you are talking about.)

![Screenshot](https://user-images.githubusercontent.com/92206575/201482850-1ef9a533-9372-474f-b5e0-c7ea1efae6b7.jpg)

**Comment by mikehardy** [comment] 2022-11-12 18:30
That's exactly what I was talking about. Well, bummer. I was hoping it was that easy but of course it cannot be that easy.
Just know it's not intended - neither to use network when not actually syncing nor to auto-sync (if that is what is going on) without it being configured. Needs triage...

**Comment by dae** [comment] 2022-11-13 00:01
This can probably be fixed by catching exceptions in the call to syncStatusFromRequired() and swallowing them, returning NO_CHANGES. The network call only happens when there are no local changes.

**Comment by criticalAY** [comment] 2022-11-21 11:58
I am not able to reproduce this issue. @user1823  are you talking about fresh install of the alpha version?

**Comment by user1823** [comment] 2022-11-21 12:08
No, I am not using a fresh install. I only updated my existing installation with the latest apk.

Also, one thing I forgot to mention earlier is that the error doesn't show up every time I open AnkiDroid while being offline. I only see it when I first open the app on a particular day (with last sync the night before, if it matters).

**Comment by doozan** [comment] 2023-01-20 15:05
I can confirm and reproduce this. If my phone is in airplane when I open Anki for the first time of the day I get the same crash screen. I do not have auto sync enabled but I do have analytics turned on.

**Comment by user1823** [comment] 2023-04-20 16:40
Still searching for solutions...

**Comment by doozan** [comment] 2023-04-20 17:41
I'm still seeing this pretty regularly if I have my phone in airplane mode. If it helps with debugging, there should be a couple of fresh crash reports submitted from my phone over the last couple of days.

```

AnkiDroid Version = 2.16alpha92

Android Version = 12

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 0819f67d-4836-45b6-90c6-ecc700511215

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by david-allison** [comment] 2023-04-30 15:46
Added to the list of backend related issues to be addressed in 2.17

**Comment by Arthur-Milchior** [comment] 2023-05-16 03:17
Seems similar to https://ankidroid.org/acra/app/1/bug/49954/report/2b79cd5e-dd55-4c51-96c7-305b6ce3665b

**Comment by BrayanDSO** [comment] 2023-08-31 09:37
Fixed

**Closed by BrayanDSO** 2023-08-31 09:37 UTC
Labels: Bug, Help Wanted, Needs Triage, Keep Open, Backend Related
