### ISSUE TITLE
Add button (+) disappears on returning to card browser from search

### ISSUE THREAD

**Issue by mnmean** [ankidroid/Anki-Android#4698] opened 2017-09-05 17:48 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Main > Hamburger > Card Browser > Search (any item) > Back (top left anki arrow or left on device)

###### Expected Result
Card browser screen returns with add button. 

###### Actual Result
Add button is missing. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.2

Android Version = 7.0

ACRA UUID = 445e0197-bfda-4466-8ad2-e252b2386cee

**Comment by timrae** [comment] 2017-09-12 18:55
This should be fixed in the latest alpha version, it's a duplicate of Issue #4579

**Closed by timrae** 2017-09-12 18:55 UTC
