### ISSUE TITLE
Pressing <AGAIN> removes card from day's queue if within 10 minutes of next day

### ISSUE THREAD

**Issue by JeopardyTempest** [ankidroid/Anki-Android#4293] opened 2016-05-21 13:32 UTC
###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[X] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps
1. Press (<10 min) AGAIN on a card with less than 10 minutes remaining in the day 

###### Expected Result
Card remains in day's queue

###### Actual Result
Removes card from the day's queue

###### Debug info
AnkiDroid Version = 2.5.4
Android Version = 6.0
ACRA UUID = c5413d1d-758f-4254-849c-25fbfe72e3dd

Had seen this occasionally when up late working on cards and couldn't make sense of why.  Sometimes I'd start clicking again, and the cards would just disappear from the queue.  Think I've been able to identify (and test) that it's happening only inside the final 10 minutes of the day (my AGAIN repeat time is set to 10 min).  I'll be trying to finish the last few cards in a set just before the day change... hit AGAIN on a few... and suddenly I'm done.  It just drops them from the current day queue immediately upon clicking any button.

**Comment by hssm** [comment] 2016-05-21 14:15
This isn't an AnkiDroid bug but a consequence of how Anki's scheduling works. Since it follows per-day scheduling, all cards that populate the queues have to be due on *at least* the current day or before it. Since those cards are scheduled in the future it won't include them in the queues.

Closing as not a bug since the desktop client follows this behavior as well.

**Closed by hssm** 2016-05-21 14:15 UTC

**Comment by JeopardyTempest** [comment] 2016-05-21 15:07
Well then at least hopefully if another person comes across this same frustration, they'll see this and the need to lower the Steps (under deck options, it'd need to be changed under lapses for old cards and also in new cards) to get the cards done properly.
Rough that it's just considered natural, and so not an issue.  Makes the program fairly unusable in that time window.
Always wondered why there wasn't an option to randomly position cards within a day, or randomly select next card from today's cards... so that there'd not be a pattern to repeats, and also would just happen to solve this issue.  But oh well, I guess if enough people aren't troubled by it, so be it.

Thanks for your work with AnkiDroid, have a good day.
