### ISSUE TITLE
App crashes when clicked on CountButton

### ISSUE THREAD

**Issue by vinishhub** [ankidroid/Anki-Android#9063] opened 2021-06-03 18:23 UTC
###### Reproduction Steps

https://user-images.githubusercontent.com/76252038/120691892-ab35dc80-c4c4-11eb-81d8-7594cf616e97.mp4

###### Debug info
```
AnkiDroid Version = 2.16alpha00

Android Version = 11

Manufacturer = realme

Model = RMX3085

Hardware = mt6785

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX3085 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.141 Mobile Safari/537.36

ACRA UUID = 5edea3c8-99cc-4753-8ece-03d86a74ada5

Scheduler = std

Crash Reports Enabled = false

DatabaseV2 Enabled = true

```

###### crash report########

```
2021-06-03 23:47:49.789 19095-19095/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 19095
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.StudyOptionsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.drawerlayout.widget.DrawerLayout.setDrawerShadow(int, int)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3730)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3898)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2323)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:255)
        at android.app.ActivityThread.main(ActivityThread.java:8194)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.drawerlayout.widget.DrawerLayout.setDrawerShadow(int, int)' on a null object reference
        at com.ichi2.anki.NavigationDrawerActivity.initNavigationDrawer(NavigationDrawerActivity.java:114)
        at com.ichi2.anki.StudyOptionsActivity.onCreate(StudyOptionsActivity.java:51)
        at android.app.Activity.performCreate(Activity.java:8151)
        at android.app.Activity.performCreate(Activity.java:8135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3699)

```
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by sheodox** [comment] 2021-06-03 19:24
I'm also experiencing this. And I experienced it sometimes when clicking on the other part of the row with the deck name but that only seemed to only happen on decks that I still had upcoming reviews for today but it wasn't quite time to review yet.

**Comment by david-allison-1** [comment] 2021-06-03 19:41
See: https://github.com/ankidroid/Anki-Android/issues/9052 - fixed in 2.15.4 for stable. 

I think it's still unstable on the alpha channel, awaiting the next alpha is release,

**Comment by mikehardy** [comment] 2021-06-04 15:50
I did not actually release an alpha so the alpha and beta channels should both be getting "the highest version code" which is currently 2.15.4 as released to public channel

**Comment by vinishhub** [comment] 2021-06-04 16:10
so should i close this issue

**Comment by mikehardy** [comment] 2021-06-04 21:39
Yes as it's duplicate - we're tracking it in other areas.
Main branch still has no PR merged to fix it but there is one waiting (on me, really) to get it in.
Stable branch works because I reverted the root cause

**Closed** 2021-06-04 21:39 UTC
