### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Vsantarlas** [ankidroid/Anki-Android#11972] opened 2022-08-03 14:55 UTC
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = SM-G991U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-G991U1 Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36

ACRA UUID = a85e4d89-52b9-4328-a767-b7f53b5ad94d

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment] 2022-08-07 21:05
This bug has no information to indicate what the problem is, thus from a maintainer perspective is a waste of time to even have to look at in order to close it. Please be kind to software maintainers, and value our time. Thank you

**Closed by mikehardy** 2022-08-07 21:05 UTC
