### ISSUE TITLE
Option "Place in review queue interval between"

### ISSUE THREAD

**Issue by LeProgramming** [ankidroid/Anki-Android#15291] opened 2024-01-21 13:19 UTC
I get frustrated when I have a deck and I've left it for a long time without reviewing it and when I want to review it again it loses the entire interval.

**Describe the solution you'd like**
The option to reschedule cards from the deck so that they are reviewed in a certain period of time. Automatically rescheduled ( and correctly) the cards.

**Describe alternatives you've considered**
Add the option "place in review Queue interval between" x~y days

**Additional context**

This is a good solution to deal with card accumulations and when it is necessary to review a few days of a test, for example.

![Screenshot_20240121-090907~2](https://github.com/ankidroid/Anki-Android/assets/71198157/fce7ac9d-eb25-4dce-b3ea-660a1e384287)

As in video:

 https://youtu.be/kxi52hun1AA?si=n3EKcaJLRZf9BHHq

*** please enable automatic subtitle and translated

Thank you.

**Comment by BrayanDSO** [comment] 2024-01-21 13:41
Duplicate of #14729

**Closed by BrayanDSO** 2024-01-21 13:41 UTC
