### ISSUE TITLE
[BUG]: cannot preview image occlusion cards in note editor

### ISSUE THREAD

**Issue by 11Milkyway11** [ankidroid/Anki-Android#15542] opened 2024-02-16 23:08 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Make an Image occlusion (If I add three square blocks on the image and press "add" it shows me "3 cards added"
2. Go to main and then go to card browser
3. Press the card that I made right before (if hard to find, use search `added:1` to see only recently added items)
4. Press an eye shaped icon on the top
5. Toast appears indicating AnkiDroid could not generate a preview card

### Expected behaviour

It should be possible to view the Image Occlusion card in the Previewer

### Actual behaviour

Cannot see the image occlusion card that I made

### Debug info

```text
AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-F731N

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-F731N Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.164 Mobile Safari/537.36

ACRA UUID = dcea78b1-e17e-4574-a71c-ea49ffca3bcd

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2024-02-16 23:29
I believe I answered your comment on the Play Store in the review comments section @11Milkyway11 ? It has to be the problem report is so similar. I see you tried the currently available beta and that still didn't work. Hopefully we can figure it out here - thank you for logging the issue

(note for other maintainers here: 2.17beta3 never made it out of review to beta channel and 2.17beta4 is still in review by google, not released to alpha or beta channel yet)

**Comment by mikehardy** [comment] 2024-02-26 12:27
I just reproduced this - I updated the title and description to more closely match my findings after reading the bug report.
It still needs triage at the code level, but the basic problem appears to be that the Note Editor does not connect correctly with the Card Previewer for the new Image Occlusion cards

**Comment by david-allison** [comment] 2024-02-26 16:03
* Closing as duplicate of #15359

**Closed by david-allison** 2024-02-26 16:03 UTC
Labels: Bug, Note Editor, Needs Triage, Reproduced, Previewer, 2.17
