### ISSUE TITLE
Allow adding drawing to card during reveal on mobile with stylus support

### ISSUE THREAD

**Issue by pascalwhoop** [ankidroid/Anki-Android#4067] opened 2016-01-27 07:40 UTC
Hi. You have the great whiteboard feature. Once you click show answer, give the option to add the drawn graphics to the answer section of the card. This helps visually supported learning and increases efficiency. Instead of visualising the answer during creation, we reuse the drawing one creates when using the whiteboard.

**Comment by hssm** [comment] 2016-01-27 08:41
I can imagine a feature where you can edit a card and use the whiteboard as the source of the field content.

Ultimately a dupe of https://github.com/ankidroid/Anki-Android/issues/3471 and https://github.com/ankidroid/Anki-Android/issues/1633.

**Closed by hssm** 2016-01-27 08:41 UTC

**Comment by pascalwhoop** [comment] 2016-01-27 09:38
ah sorry, was on mobile and didnt searching previous issues wasnt effective.. I'll watch the others and see what happens. I'm no good android java dev otherwise i'd pull request this
