### ISSUE TITLE
Migrate the deprecated onBackPressed

### ISSUE THREAD

**Issue by Prachi-Jamdade** [ankidroid/Anki-Android#13323] opened 2023-02-21 17:16 UTC
**OnBackPressed Override Function is deprecated in Android 13**
Android 13 has a new feature called **Predictive Back Gesture** which shows users that they are about to navigate back to the launcher from the application with back action.

Here is the warning that android studio will give on using onBackPressed on Android API level 33+

![image](https://user-images.githubusercontent.com/94190717/220414065-377f7c7f-8f76-45a9-8c0f-a8722022e1c8.png)

Here is how you can replace onBackPressed in the code -

```import androidx.activity.addCallback

onBackPressedDispatcher.addCallback(this /* lifecycle owner */, object : OnBackPressedCallback(true) {
    override fun handleOnBackPressed() {
        // Back is pressed... Finishing the activity
        finish()
    }
})

// ====================================================
/* Or for lambda simplicity: */
// ====================================================
onBackPressedDispatcher.addCallback(this /* lifecycle owner */) {
    // Back is pressed... Finishing the activity
    finish()
}```

**Comment by david-allison** [comment] 2023-02-21 17:30
Thanks!

Part of https://github.com/ankidroid/Anki-Android/issues/12364 : happy for you to take this on if you'd like.

Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/12364

**Closed** 2023-02-21 17:32 UTC
Labels: Duplicate

**Comment by Prachi-Jamdade** [comment] 2023-02-21 17:43
You can assign #12364 to me. Would be happy to contribute :)

**Comment by david-allison** [comment] 2023-02-21 17:57
> You can assign #12364 to me. Would be happy to contribute :)

There's multiple sub-issues within it, not assigned, but do comment to say you're working on `onBackPressed` :)
