### ISSUE TITLE
After editing the field text with html tags and line breaks, the field text is rendered incorrectly.

### ISSUE THREAD

**Issue by L-M-Sherlock** [ankidroid/Anki-Android#5651] opened 2019-12-08 10:00 UTC
###### Reproduction Steps

1. edit a field text in card which includes html tags and line breaks. For example:

```html

 <style>
                div.dis {font-weight: bold;margin-bottom:3px;padding:0;}
                span.grammar,
                span.informal   {margin: 0 2px;color: #0d47a1;}
                span.complement {margin: 0 2px;font-weight: bold;}
                div.idmphrase {font-weight: bold;margin: 0;padding: 0;}
                span.eng_dis  {margin-right: 5px;}
                span.chn_dis  {margin: 0;padding: 0;}
                span.pos  {text-transform:lowercase; font-size:0.9em; margin-right:5px; padding:2px 4px; color:white; background-color:#0d47a1; border-radius:3px;}
                span.tran {margin:0; padding:0;}
                span.eng_tran {margin-right:3px; padding:0;}
                span.chn_tran {color:#0d47a1;}
                ul.sents {font-size:0.9em; list-style:square inside; margin:3px 0;padding:5px;background:rgba(13,71,161,0.1); border-radius:5px;}
                li.sent  {margin:0; padding:0;}
                span.eng_sent {margin-right:5px;}
                span.chn_sent {color:#0d47a1;}
            </style><span class="pos">verb</span><span class="tran"><span class="eng_tran">to try hard to find out more information about sth</span><span class="chn_tran">探索；探究；查考</span></span><ul class="sents"><li class="sent"><span class="eng_sent">She had started to <b>delve</b> into her father's distant past.</span><span class="chn_sent">她开始探究她父亲久已逝去的岁月。</span></li></ul>
```

2. save
3. browse

###### Expected Result

The field text is rendered with its **all** html tags.

###### Actual Result

The field text is rendered with its **partial** html tags.

And the line breaks are transformed to `<br>`.

```html
<br> <style><br>                div.dis {font-weight: bold;margin-bottom:3px;padding:0;}<br>                span.grammar,<br>                span.informal   {margin: 0 2px;color: #0d47a1;}<br>                span.complement {margin: 0 2px;font-weight: bold;}<br>                div.idmphrase {font-weight: bold;margin: 0;padding: 0;}<br>                span.eng_dis  {margin-right: 5px;}<br>                span.chn_dis  {margin: 0;padding: 0;}<br>                span.pos  {text-transform:lowercase; font-size:0.9em; margin-right:5px; padding:2px 4px; color:white; background-color:#0d47a1; border-radius:3px;}<br>                span.tran {margin:0; padding:0;}<br>                span.eng_tran {margin-right:3px; padding:0;}<br>                span.chn_tran {color:#0d47a1;}<br>                ul.sents {font-size:0.9em; list-style:square inside; margin:3px 0;padding:5px;background:rgba(13,71,161,0.1); border-radius:5px;}<br>                li.sent  {margin:0; padding:0;}<br>                span.eng_sent {margin-right:5px;}<br>                span.chn_sent {color:#0d47a1;}<br>            </style><span class="pos">verb</span><span class="tran"><span class="eng_tran">to try hard to find out more information about sth</span><span class="chn_tran">探索；探究；查考</span></span><ul class="sents"><li class="sent"><span class="eng_sent">She had started to <b>delve</b> into her father's distant past.</span><span class="chn_sent">她开始探究她父亲久已逝去的岁月。</span></li></ul>
```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by L-M-Sherlock** [comment] 2019-12-08 10:05
# Before:

![Screenshot_20191208-175703](https://user-images.githubusercontent.com/32575846/70387814-a8981b00-19e4-11ea-8983-2afbebe0bcaf.jpg)

![Screenshot_20191208-180420](https://user-images.githubusercontent.com/32575846/70387860-383dc980-19e5-11ea-9d44-ae1537fd7436.jpg)


# After:

![Screenshot_20191208-175721](https://user-images.githubusercontent.com/32575846/70387816-b8affa80-19e4-11ea-8b95-33b85d4e9d27.jpg)

![Screenshot_20191208-175811](https://user-images.githubusercontent.com/32575846/70387819-c2d1f900-19e4-11ea-9f4f-1d5e3514968a.jpg)

**Comment by mikehardy** [comment] 2019-12-08 13:30
I believe this is a dupe of #3304

**Comment by mikehardy** [comment] 2019-12-08 13:30
closing preliminarily - please

**Closed by mikehardy** 2019-12-08 13:30 UTC
