### ISSUE TITLE
[BUG]: can not connect to a gamepad to work with javascript

### ISSUE THREAD

**Issue by zye9312** [ankidroid/Anki-Android#14974] opened 2023-12-14 20:26 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Connect a gamepad to Android and then connect that device to Chrome via USB
2. add <embed src="https://hardwaretester.com/gamepad" style="width=100px, height=1000px"> to the front card;
3. or type "navigator.getGamepads()" in the console of the PC Chrome.

### Expected behaviour

It should be able to detect the gamepad device and respond correctly.

### Actual behaviour

The gamepad can be detected by "https://hardwaretester.com/gamepad" via a browser on an Android device. However, it could not be seen inside the Anki app.

### Debug info

```text
None
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2023-12-15 05:16
Whoops, missed this! Thanks again for the report!

* Duplicate of https://github.com/ankidroid/Anki-Android/issues/14975
* Fixed in https://github.com/ankidroid/Anki-Android/pull/14983

**Closed by david-allison** 2023-12-15 05:16 UTC
Labels: Bug, Needs Triage
