### ISSUE TITLE
When "Show answer" is tapped, the auto-scrolling to the top of the answer area won't work

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4663] opened 2017-07-08 13:51 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Show a card
![image](https://user-images.githubusercontent.com/10436072/27985775-073d66f8-642d-11e7-8de6-cf799fe15465.png)

2. Tap "Show answer" 

###### Expected Result
The top of the answer area is displayed.
![image](https://user-images.githubusercontent.com/10436072/27985826-123dc65a-642e-11e7-8250-a3379cedc89e.png)

###### Actual Result
The displayed area won't change. Users need to scroll down manually to read the answer.
![image](https://user-images.githubusercontent.com/10436072/27985781-262f175a-642d-11e7-8dd4-7627af13d30b.png)

###### Debug info
AnkiDroid Version = 2.8.2
Android Version = 5.0
ACRA UUID = 59e2f4d3-276c-47cc-a713-a5df28348710.

and,

AnkiDroid Version = 2.5beta16
Android Version = 5.0
ACRA UUID = 3afc3806-b1e8-422c-ae7f-ca493e16d1b3

(Recently I started using a Android 5.0 device. This problem happens on it.)

**Comment by timrae** [comment] 2017-07-17 10:36
Isn't this a duplicate of #4624?

**Closed by timrae** 2017-07-17 10:36 UTC

**Comment by snowtimeglass** [comment] 2017-07-17 13:19
You're right. 
The new title of #4624 is less misleading. Thank you.

**Comment by timrae** [comment] 2017-07-17 13:24
The problems are occurring with chrome 58.x?

**Comment by snowtimeglass** [comment] 2017-07-17 13:39
Chrome 59.0.3071.125, which ferrouswheel referred to on #4624 
![image](https://user-images.githubusercontent.com/10436072/28270293-e0eab8e2-6b3f-11e7-9f3c-698c90c2e427.png)

![image](https://user-images.githubusercontent.com/10436072/28270281-d5fb3b3c-6b3f-11e7-84d6-947400d50c29.png)

**Comment by timrae** [comment] 2017-07-17 13:40
Yes, he's saying it's working with that version though.

**Comment by snowtimeglass** [comment] 2017-07-17 13:57
#4624 ![image](https://user-images.githubusercontent.com/10436072/28270573-eb0f10d8-6b40-11e7-9866-6c3bfffcf1c9.png)

It seems that the action has (almost) fixed this problem on my device, too.
Just uninstalling Android System WebView seems to (almost) have fixed this problem, too.
(Incidentally, as you know, the uninstalling process only uninstalls the updates of the program, not uninstall the program itself.)

**Comment by snowtimeglass** [comment] 2017-07-17 14:03
>Yes, he's saying it's working with that version though.

Yes, I understand the discord. 
On my device, the problem wasn't fixed just with that version of Chrome.
