### ISSUE TITLE
AnkiDroid crashes when I'm trying to import the following apkg-file (which works fine in Anki for Desktops)

### ISSUE THREAD

**Issue by tomkahn** [ankidroid/Anki-Android#4822] opened 2018-04-11 07:03 UTC
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open [this apkg-file](http://www.thomaskahn.de/jura-vorlagen/download.php?action=download&file=Jura-Vorlagen8.apkg) or synchronize a collection that includes it.

###### Expected Result
Imports cards, doesn't crash.

###### Actual Result
Doesn't import cards, crashes.

###### Debug info
AnkiDroid Version = 2.8.3
Android Version = 7.1.1
ACRA UUID = 8314e674-5f2c-4884-835e-d6e3fd657dcf
Affects AnkiDroid on other Android devices as well!

**Comment by tomkahn** [comment] 2018-04-11 08:32
The deck I uploaded above contains several cards with different note types. After experimenting a little I found out that the problem is associated with one note type in particular, namely "Fragenfolge 1.11". *Some* decks that only contain this note type will crash as well, for example [this one](http://thomaskahn.de/JV8-ankidroid5_nur_FF.apkg), while decks with other note types won't crash.

The content of the cards also seems to be a relevant factor. For example [this deck](http://thomaskahn.de/JV8-ankidroid13_FF_pausiert_only.apkg) (wich also only contains cards of the type "Fragenfolge 1.11" will not crash when importing:

**Comment by mikehardy** [comment] 2018-04-11 18:03
Crash bugs are always serious! This looks like a great report though, thanks especially for uploading a test deck that should trigger it. I'm traveling hope to look at this shortly if no one beats me to it

**Comment by tomkahn** [comment] 2018-04-11 18:06
Haha, thanks, but your template made it easy!

Mike Hardy <notifications@github.com> schrieb am Mi., 11. Apr. 2018, 20:03:

**Comment by mikehardy** [comment] 2018-04-12 13:45
Very strange, I'm unable to reproduce this with any of the 3 decks you linked, in current AnkiDroid (2.9alpha19) on Android 8.1 or 6.0. This testing isn't great since I'm missing your versions on both AnkiDroid and Android, but it's what I have just now.

Have you tried one of the latest AnkiDroid builds? The designation "alpha" is normally a little off-putting but the latest builds are very stable and I use them for my normal daily reviews, not just development. Whatever the issue is may be fixed there? https://github.com/ankidroid/Anki-Android/releases is where to find them

If you are still able to reproduce the problem in the current builds, I'll work with you (and maybe Tim, looking for the stack trace related to that ACRA UUID) to dig deeper

**Comment by tomkahn** [comment] 2018-04-12 17:35
Just tried it with the latest alpha as well, no problems here either. I'm glad it'll be fixed soon! Is there a date for the next release yet? I'm asking because the first deck I posted is a deck for German law students that gets downloaded somewhat frequently and I'm pretty sure most of my colleagues are rather skeptical of manually downloading and installing apkgs. ^_^

In any case thanks for your fast help, Mike!

**Comment by mikehardy** [comment] 2018-04-12 20:15
Glad it appears to be fixed in recent cose. Releases are up to @timrae but at present I think the code is stable whereas there are a couple of pending merges that are potentially destabilizing. So maybe sooner rather than later before those merges are attempted. Fingers crossed and even if skeptical there is at least a workaround

**Closed** 2018-04-13 05:45 UTC

**Comment by timrae** [comment] 2018-05-11 04:33
Does this work in 2.8.4? I suspect it must have been 572ecf4465b5541d727e5363f9795d182b5b9c8d which was making it work in the alphas

**Comment by tomkahn** [comment] 2018-05-11 17:36
Just tried with 2.8.4. Doesn't crash anymore with this version!
