### ISSUE TITLE
[Bug] Disappearing buttons on main screen (sometimes)

### ISSUE THREAD

**Issue by aTr00per** [ankidroid/Anki-Android#9081] opened 2021-06-06 16:51 UTC
###### Reproduction Steps

1. Open AnkiDroid
2. Sync by pushing the button in the top right corner or swiping down
3. Open the menu on the left side by clicking the hamburger button or swiping right

###### Expected Result
Everything should be normal/as usual. 
In the top right corner of the main screen should a search button, sync button and the kebab menu button.

###### Actual Result
The search button, sync button and the kebab menu button disappear everytime. Sync by swiping down is still possible.

###### Debug info
AnkiDroid Version = 2.15.2

Android Version = 10

Manufacturer = OnePlus

Model = OnePlus Nord

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; OnePlus Nord Build/QQ3A.200805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 43a01fb7-27f7-4c80-af40-d07913915574

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by aTr00per** [comment] 2021-06-06 16:57
I had some problems uploading a screenshot on my Smartphone.
![Screenshot](https://user-images.githubusercontent.com/24195028/120933137-fb958000-c6f8-11eb-8db6-7ae1d71dc2e0.png)

**Comment by prateek-singh-3212** [comment] 2021-06-06 17:27
Thanks @aTr00per for reporting this issue. In your debug info I saw that you are using older version on AnkiDroid i.e 2.15.2 the current AnkiDroid version is 2.15.4 so please update to the newer version. If this issue is still reproducable then please let us know.

**Comment by aTr00per** [comment] 2021-06-06 17:42
Oh, sorry. My bad. It is the up-to-date version of the F-Droid store.

I tried it on my other phone with the 2.15.4 version from the play store. Same problem.


The debug info:
AnkiDroid Version = 2.15.4

Android Version = 9

Manufacturer = OnePlus

Model = ONEPLUS A3003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; ONEPLUS A3003 Build/PKQ1.181203.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.88 Mobile Safari/537.36

ACRA UUID = 65169ea2-3d07-4768-860a-3e8a9a425d0a

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by prateek-singh-3212** [comment] 2021-06-06 17:51
Thanks for update. I got that it is reproducable in my device too. We fix that soon.

**Comment by aTr00per** [comment] 2021-06-07 20:25
Same problem appears when
1. Open Anki
2. Sync
3. Turn Screen off
4. Turn Screen on


Tested on 2.15.4

**Comment by prateek-singh-3212** [comment] 2021-06-08 07:51
@mikehardy @david-allison-1 This issue is duplicate of #8934 so can we close this? and shift to that issue. I will take this issue.

**Comment by mikehardy** [comment] 2021-06-08 13:43
@prateek-singh-3212 sure! as mentioned on #8934 this issue is duplicate and came in second but it has slightly more information so I resolved the other as a dupe of this one and we can keep this open to focus discussion. Good luck :-)

**Closed** 2021-07-19 14:12 UTC
