### ISSUE TITLE
Images from Android clipboard do not paste correctly.

### ISSUE THREAD

**Issue by McSpooder** [ankidroid/Anki-Android#7626] opened 2020-11-08 13:10 UTC
You can copy an image from Android, say by holding it down and tapping copy.

However you cannot paste it from the clipboard like you would on a desktop machine.

Instead you get something like: content://com.android.chrome.FileProvider/images/screenshot/16048407172167286279025733221228.png

**Comment by david-allison-1** [comment] 2020-11-08 14:19
Hi @McSpooder 

Which version of AnkiDroid are you using?
Which phone are you using?

This might be fixed in the latest alpha: https://github.com/ankidroid/Anki-Android/releases/download/v2.14alpha27/AnkiDroid-2.14alpha27.parallel.A.apk

**Comment by McSpooder** [comment] 2020-11-08 14:21
2.13.5, I will try the alpha thanks!

**Comment by McSpooder** [comment] 2020-11-08 14:27
Just tried the alpha, unfortunately no luck

![Screenshot_20201108-142709_AnkiDroidA.jpg](https://user-images.githubusercontent.com/21046724/98467693-9616fa80-21ce-11eb-951d-6389bd63286d.jpg)

**Comment by McSpooder** [comment] 2020-11-08 14:31
Update:

Pasting by holding down the field and pressing clipboard (which opens up the native Android clipboard) just pastes the relative path on the device.

However, pasting using the Google keyboard displays an anki error saying that pasting is not supported here.

**Comment by McSpooder** [comment] 2020-11-08 14:37
Tried hard coding the html like so:
<img src="content://com.android.chrome.FileProvider/images/screenshot/16048455604811721105034031108145.jpg"/>

But that didn't work either. Anki just says failed to load image.

**Comment by david-allison-1** [comment] 2020-11-08 15:05
Thanks for the repro - will improve this in the next alpha

**Comment by david-allison-1** [comment] 2020-11-08 16:53
I'm going to close this as a duplicate of #7566 to consolidate discussion.

**Closed by david-allison-1** 2020-11-08 16:53 UTC

**Comment by david-allison-1** [comment] 2020-11-08 23:59
@McSpooder Could you try alpha28: https://github.com/ankidroid/Anki-Android/releases/download/v2.14alpha28/AnkiDroid-2.14alpha28.parallel.A.apk

**Comment by McSpooder** [comment] 2020-11-09 19:36
@david-allison-1 
Can confirm pasting images now works with the alpha when using the Google keyboard!

**Comment by mikehardy** [comment] 2020-11-09 19:38
@david-allison-1 -> 🏆

**Comment by david-allison-1** [comment] 2020-11-09 19:44
<img src="https://media.giphy.com/media/120jXUxrHF5QJ2/giphy.gif"/>
