### ISSUE TITLE
Reset Deck

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2076] opened 2015-07-28 08:55 UTC
Originally reported on Google Code with ID 1174

```
I read all the reasons why you shouldn't reset a deck but it's simply the decision of
the student if he wants to waste his time learning stuff he might not have forgotten
yet.

That said let me state my situation:
I studied Japanese 2 years ago and my deck had 400 in it. I recently decided to get
back to it, but now have all the cards for review while I know almost none of them
anymore PLUS if I DO know one it schedules the next review for 1 year into the future,
even if it was a lucky guess.

This is discouraging and the reason why I've been wasting my time looking for a solution
instead of learning.

Please add this feature; people will appreciate and those who don't just won't use
it.
```

Reported by `Hashishin` on 2012-06-16 10:34:49

**Comment by mikehardy** [comment] 2018-06-17 22:12
@timrae Duplicate of #2746 and that issue has a useful discussion with workarounds - this should be closed

**Closed** 2018-06-17 23:49 UTC
Labels: Priority-Medium, accepted, enhancement

**Comment by mikehardy** [comment] 2018-12-02 01:56
Follow instructions at the link below to tell google play you want betas and join the alpha google group and this will be present in 2.9alpha53 (the next alpha) and higher
https://docs.ankidroid.org/manual.html#betaTesting
