### ISSUE TITLE
AnkiDroid gesture error

### ISSUE THREAD

**Issue by sibilek** [ankidroid/Anki-Android#4340] opened 2016-06-23 10:14 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps
When I am using gestures I have a problem. If I want to listen audio again and press audio button it shows answer. But I am not ready for answer I just want to listen audio one more time to be sure about pronunciation and then I will check the answer.

You can see details in YouTube video. https://youtu.be/wfQ1Atp7E38

I already know there is a replay button in drop-down menu and I can assign that as a app bar button also. But it replays all sounds on front face of cards. And if I only want to listen one of the sounds and click on play button it shows the answer.

If I am being picky sorry for that. I am just trying to do beta testing and trying to make AnkiDroid work better...

Thanks for your efforts and patience...

###### Debug info
AnkiDroid Version = 2.6

Android Version = 5.0

ACRA UUID = bff7e18d-3056-4ce7-b037-e3fa06fb7462

**Comment by hssm** [comment] 2016-06-28 11:00
Dupe of https://github.com/ankidroid/Anki-Android/issues/2610

There really isn't an easy way around this problem.

**Closed by hssm** 2016-06-28 11:00 UTC
