### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by payam088** [ankidroid/Anki-Android#9051] opened 2021-06-02 17:29 UTC
Hello anki support. 
1. Add new notes and creating new deck in ankidroid is disabled. It doesn't work ! 

Please fix it.

**Comment by david-allison-1** [comment] 2021-06-02 17:33
Hi, thanks for the report. This is a likely a duplicate of: https://github.com/ankidroid/Anki-Android/issues/8993

Could you 

* close AnkiDroid
* Open AnkiDroid
* Click the menu
* Help - Get Help - Send Troubleshooting Report
* Settings - Advanced - About AnkiDroid - Copy Debug Info and paste it in the thread above
* Provide a video of the issue

If you have development experience, it'd be great to know as that would make diagnosing this much easier

**Closed** 2021-06-02 17:34 UTC
Labels: Duplicate

**Comment by prateek-singh-3212** [comment] 2021-06-02 17:37
Thanks, @payam088 for reporting this issue. Can you provide us the screenshot of the issue and debug info.

For debug info :- Go to Settings > Advanced > About Ankidroid > copy debug info.

**Comment by payam088** [comment] 2021-06-02 18:17
AnkiDroid Version = 2.15.3

Android Version = 10

Manufacturer = HUAWEI

Model = YAL-L21

Hardware = kirin980

Webview User Agent = Mozilla/5.0 (Linux; Android 10; YAL-L21 Build/HUAWEIYAL-L61; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = c2f3b04b-567b-4bbf-9e3d-f89773f38e88

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by payam088** [comment] 2021-06-02 18:28
https://user-images.githubusercontent.com/85249888/120533076-9a6a6580-c3f5-11eb-9210-1fcf56026260.mp4

**Comment by david-allison-1** [comment] 2021-06-02 18:52
Click the buttons, not the text. I'll get this sorted
