### ISSUE TITLE
Increase number of failed cards in filtered decks

### ISSUE THREAD

**Issue by voidplayer** [ankidroid/Anki-Android#7285] opened 2020-09-26 19:48 UTC
Edit by Arthur:

# How to reproduce:
1. add a note
1. create filtered deck
1. Uncheck "resschedule" button. (This transform it into a preview deck)
1. search anything that lead to your card to be selected
1. open this filtered deck
1. press again (as many time as you want)
1. Press undo

# Initial bug report

From outside
![Screenshot_20200926-003047_AnkiDroid](https://user-images.githubusercontent.com/4019910/94349083-8fc72780-0041-11eb-8fa7-29d8325bcfca.png)
After failing one card
![Screenshot_20200926-003103_AnkiDroid](https://user-images.githubusercontent.com/4019910/94349085-90f85480-0041-11eb-8c47-b720bb4d96ec.png)
After failing another card
![Screenshot_20200926-003417_AnkiDroid](https://user-images.githubusercontent.com/4019910/94349086-9190eb00-0041-11eb-8a88-e7412711c563.png)

Every time i tap on fail, this number increases forever

If i try to undo after failing, it crashes

**Comment by david-allison-1** [comment] 2020-09-26 21:14
@voidplayer Thanks! Could you provide your Debug Information: `Settings - Advanced - About AnkiDroid - Copy Debug Info`

**Comment by voidplayer** [comment] 2020-09-26 22:37
AnkiDroid Version = 2.13.2

Android Version = 10

ACRA UUID = 3ab3e7d9-3f01-4b07-9a98-94244270ed93

Scheduler = std2

**Comment by david-allison-1** [comment] 2020-09-26 22:55
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/3268ec2b-5ef1-4554-b5cc-09c591b45867

```
java.lang.ArrayIndexOutOfBoundsException: length=3; index=4at com.ichi2.libanki.sched.SchedV2.undoReview(SchedV2.java:12)at com.ichi2.libanki.Collection$1.undo(Collection.java:1)at com.ichi2.libanki.Collection.undo(Collection.java:3)at com.ichi2.async.CollectionTask.nonTaskUndo(CollectionTask.java:2)at com.ichi2.async.CollectionTask.doInBackgroundUndo(CollectionTask.java:4)at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:46)at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)at android.os.AsyncTask$3.call(AsyncTask.java:378)at java.util.concurrent.FutureTask.run(FutureTask.java:266)at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)at java.lang.Thread.run(Thread.java:919)
--
```

**Comment by Arthur-Milchior** [comment] 2020-09-27 05:28
"fail" ? Do you mean "again" or do you mean something different ?

Do you know whether the card was new or was a due card before moving to learning mode ? Can you please share the steps you use for the new card or for the lapsed cards please ?

Is it always the same card you see again and again and again ?

If you use anki desktop, you can share the few cards that create the problems, so that we can look at them directly

I currently can't reproduced, but I would expect that I don't have the correct settings here

**Comment by Arthur-Milchior** [comment] 2020-09-27 05:39
> java.lang.ArrayIndexOutOfBoundsException: length=3; index=4

should means that the card is in the preview queue, which should probably not be possible.

Have you started the review of those cards on any other system ? Desktop, ios ?

Have you used the preview mode on the same cards ? 

I actually never used the previewer and don't even know how to use it. So @david-allison-1 any guidance would be appreciated to figure out how to put a card in the preview queue, and then review/undo it

**Comment by david-allison-1** [comment] 2020-09-27 05:48
@Arthur-Milchior There's no such thing as a 'preview' queue in the previewer. It avoids the scheduler entirely and contains a collection of cardIds to obtain and render.

**Comment by Arthur-Milchior** [comment] 2020-09-27 05:58
I edited the initial bug report to add reproduction steps

**Comment by Arthur-Milchior** [comment] 2020-09-27 06:00
Tried to reproduce it upstream. You can't undo a card in preview mode. That'll save one part of the problem.
I'll look at numbers later,

**Comment by voidplayer** [comment] 2020-09-27 08:53
The crash while undoing in a filtered deck has been going on for a very long time. The increasing number when tapping again has only been happening for a couple of versions, although it seems related :)

Thanks for researching the reproduction steps and fixing it!

**Comment by Arthur-Milchior** [comment] 2020-09-27 10:23
Were we told the crashed occurred ? I've never heard of it. It would have been corrected quite a long time ago otherwise. Nothing complex here

**Comment by voidplayer** [comment] 2020-09-27 11:36
I didnt report it because anki crashed a lot and you guys were already fixing lots of crashes very recently. This was just one of them

It barely crashes now, so its easier to aisle problems. I waited until i could reproduce it on the latest version

Also, Its not very critical. And the deck didnt seem to broke either

Thanks again! I will report if this happens again!

**Comment by Arthur-Milchior** [comment] 2020-09-27 11:38
Makes sens I guess. I mostly corrected bugs I created so I didn't realize there were so many corrections that users would remark it.

**Comment by mikehardy** [comment] 2020-09-27 13:36
@Arthur-Milchior By my rough estimation I fixed maybe 10 crash bugs and David went berserk and fixed like 40 or 50, starting around Feb/March with a crescendo in April/May. Stats indicate there are around 99% fewer crashes :-)

**Closed** 2020-09-27 13:38 UTC
