### ISSUE TITLE
[BUG]: Editing cards in a Filtered Deck will cause the cards to return to the original Deck.

### ISSUE THREAD

**Issue by ChuckieChen945** [ankidroid/Anki-Android#16551] opened 2024-06-05 03:47 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Create a filtered deck.
2. Edit a card in the filtered deck and save.

https://github.com/ankidroid/Anki-Android/assets/29732324/440547bc-e6b1-4531-a970-d889a44e274e

### Expected behaviour

the card won't return to the original Deck

### Actual behaviour

the card will return to the original Deck

### Debug info

```text
AnkiDroid Version = 2.19alpha4 (a2a109caa87ccfd84d9f49ae3294749712961ac2)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 10 (SDK 29)

ProductFlavor = full

Manufacturer = HUAWEI

Model = MXW-AN00

Hardware = mt6873

Webview User Agent = Mozilla/5.0 (Linux; Android 10; MXW-AN00 Build/HONORMXW-AN00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 9daaa97f-8375-4c53-b49d-ff939ff2a6a3

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-06-05 06:18
Thanks

Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/16522

* https://github.com/ankidroid/Anki-Android/issues/16522

**Closed by david-allison** 2024-06-05 06:18 UTC
Labels: Bug, Needs Triage
