### ISSUE TITLE
Short alarm when there are available cards to study.

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2129] opened 2015-07-28 08:59 UTC
Originally reported on Google Code with ID 1227
```
Right now the widget can give an alarm but only when at least 10 cards have lined up.
I think there should be no such limitation. What if, for example, there are only 9
cards left to study? 

So in the options there should be an option with the following settings:

1, Turn on / off alarms
2, Every how many cards should an alarm be raised? (01-...)
For example, 1 would mean that with every additional card arriving in the waiting queue,
there is an alarm raised. Or every second, third, ect.
3, Should the program pop up automatically?
4, Or should it just indicate on the notification bar?
5, Costum sound option where you can choose your specific mp3 to play as anki warning
sign.
 
```

Reported by `rekeakos` on 2012-07-17 12:57:47

**Comment by eginhard** [comment] 2016-01-23 01:51
Duplicate of #4006

**Closed by eginhard** 2016-01-23 01:51 UTC
Labels: enhancement, Priority-Medium

**Comment by federvieh** [comment] 2016-01-23 07:21
Is this really the same as #4006? I'd assume, that the notification
described here is probably far easier to implement then the one mentioned
in #4006.

>

**Comment by eginhard** [comment] 2016-01-23 09:12
It's the same general issue of providing "more advanced notification
options" and it's easier to group it under the same issue to discuss it in
one place.
