### ISSUE TITLE
Anki Crash on Launch after Sync

### ISSUE THREAD

**Issue by benbassist** [ankidroid/Anki-Android#4585] opened 2017-02-15 12:16 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Launch Anki and sync decks.
2. Anki Crash's after sync.
3. Attempting to launch Anki again results in crash on opening.

###### Expected Result

Sync and be able to review by decks.

###### Actual Result

Sync results in Anki crashing and no longer be able to open it.

###### Debug info

‎AnkiDroid Version = 2.8.2beta2

Android Version = 4.3

ACRA UUID = c6867d4d-a37f-43a1-a98a-fc91817aca6b

###### Notes

I have attempted re-installing Anki and tested it with one of my simplest decks and still experience the same result.

**Comment by timrae** [comment] 2017-02-15 12:56
I can't seem to see any crashes from you, but could you please try to install the latest beta and see if it fixes your issue?

https://github.com/ankidroid/Anki-Android/releases

**Comment by benbassist** [comment] 2017-02-15 15:55
I have installed the latest beta and I am unfortunately still experiencing the same problem.

**Comment by timrae** [comment] 2017-02-15 15:58
Can you make a video of what happens? It might be more fruitful at this
point to contact ankiweb support site, but ankidroid should definitely not
be crashing.

**Comment by hssm** [comment] 2017-02-15 18:32
This seems to be a native crash in SQLite.

If you could send/attach a copy of your collection in the crashing state, I'd like to take a look at it.

**Comment by benbassist** [comment] 2017-02-15 20:21
I have attached a copy of my collection.
[collection.anki2.zip](https://github.com/ankidroid/Anki-Android/files/778287/collection.anki2.zip)

**Comment by hssm** [comment] 2017-02-17 07:30
Thanks. I've managed to reproduce some crashes and I'm [investigating the cause](https://github.com/requery/sqlite-android/issues/35). The crashes occur outside of AnkiDroid code and I'm trying to understand how exactly we are triggering them, and why specifically your collection crashes and not others.

It might take some time before I isolate the exact issue. I can't get the crashes to occur in a separate project. I'm strongly suspecting a threading issue (in the native libraries).

If I understand the nature of the crash correctly, then:
1 - The sync completes successfully and there is no data loss
2 - The crash only occurs after sync (when reopening the database)
3 - After this crash, subsequent uses of AnkiDroid operate normally without issue.

If that is the case, then you might just have to live with the problem until we can figure it out. Otherwise, if you were not encountering an issue in the 2.7 release of AnkiDroid then it might be best for you to roll back to that release.

**Comment by benbassist** [comment] 2017-02-17 11:13
Thanks for looking into this for me.

I will try AnkiDroid 2.7 and see how I get on.

**Comment by natemiller82** [comment] 2017-04-22 17:16
I have this same problem -- sync completes successfully, but then it crashes, only occurs after sync on version 2.8.2; downgrading to 2.7 resolved the problem.

I tried clearing cache/data/reinstalling; even tried all this after deleting the ankidroid folder. Same problem. Recently clean upgrade to Nougat, problem persists.

**Comment by Plagioclase** [comment] 2017-05-16 22:07
I have the exact same problem. I think it appeared after I deleted a deck on my phone, there was a conflict between the cloud and my phone which I then overwrote from my phone, and the issue has been happening since then.

**Comment by Vaanen** [comment] 2017-08-30 11:04
I'm having the same issue, happenned after i downloaded my collection from the cloud, but now nothing solves it

**Comment by mikehardy** [comment] 2018-10-08 03:37
I'm closing this for lack of a specific trace, but I watch crashes closely and will open a new ticket if I see one, or if anyone can post the debug info UUID of their ankidroid after sending feedback through the crash dialog, I'll take a look

**Closed by mikehardy** 2018-10-08 03:37 UTC
