### ISSUE TITLE
[BUG]: On deck screen Total new cards and Total cards are being shown from the first deck in the collection, not the selected deck.

### ISSUE THREAD

**Issue by szalejot** [ankidroid/Anki-Android#14643] opened 2023-11-02 07:12 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Click on the number of reviews for the deck, so the deck view shows.

### Expected behaviour

Show Total new cards and Total cards for the selected deck.

### Actual behaviour

Total new cards and Total cards values are for the first deck in the collection, regarding which deck was actually selected.
Please see the screenshots below.

![Screenshot_2023-11-02-06-48-56-001_com ichi2 anki-edit](https://github.com/ankidroid/Anki-Android/assets/3840404/51cf1119-69bd-4ec7-96c7-f49af138c655)
![Screenshot_2023-11-02-06-49-29-671_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/3840404/751bf9af-b551-4623-bbd2-73d4f37febb0)

### Debug info

```text
AnkiDroid Version = 2.17alpha3 (42a8c8c55c200f372b0bd0b462e4b58554b72fe5)

Android Version = 13

ProductFlavor = full

Manufacturer = Xiaomi

Model = 21081111RG

Hardware = mt6893

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 21081111RG Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = 32cd7308-64af-439f-aa74-37ffb8dd0ae1

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2023-11-03 15:53
Thanks so much for the report!

Duplicate of #14608. Fixed in #14637

Should be fixed in alpha4, if it's not, please ping and I'll reopen the issue

**Closed by david-allison** 2023-11-03 15:53 UTC
Labels: Bug, Needs Triage
