### ISSUE TITLE
Enhanced Deck Selection for Viewing Statistics

### ISSUE THREAD

**Issue by valeriad0l** [ankidroid/Anki-Android#16187] opened 2024-04-15 23:34 UTC
**Is your feature request related to a problem? Please describe.**
When clicking Statistics, you should have the option to select which deck you want your statistics for, instead of having to enter the name of the desired deck in the search bar. It shouldn't have to be those of the most recently studied deck. This issue is related to functionality and user experience. 

**Describe the solution you'd like**
I would like the Statistics section of the AnkiDroid app to include a feature where users can select which deck they want to view statistics for, perhaps from a dropdown menu. After opening the Statistics page, users should be presented with a list of all their decks, allowing them to choose one or multiple decks for which the statistics will be displayed. This selection should persist even when the app is closed and reopened.

**Describe alternatives you've considered**
As an alternative to a direct selection from a dropdown menu, another solution could be to implement a settings option within the app where users can set their preferred deck for statistics as a default option. This would allow users who frequently review statistics for the same deck to save time. Additionally, adding a toggle feature on the main statistics screen to switch between 'Current Deck' and 'All Decks' could provide users with flexible viewing options without complicating the user interface.

**Additional context**
This issue is related to functionality and UI/UX.

**Comment by david-allison** [comment] 2024-04-15 23:43
Thanks for the suggestion! Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/15197

* https://github.com/ankidroid/Anki-Android/issues/15197

**Closed by david-allison** 2024-04-15 23:43 UTC
Labels: Duplicate
