### ISSUE TITLE
[BUG]: Tags dialog & deck selection dialog have a grey background in Black theme

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16474] opened 2024-05-25 02:05 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

0. Enable Black theme
1. Select a card in the browser 
2. Choose Edit tags
3. Close the dialog.
4. Choose Change deck.

### Expected behaviour

The dialogs have a black background.

### Actual behaviour

The dialogs have a grey background.

### Debug info

```text
2.19 alpha2
```

### (Optional) Anything else you want to share?

This issue was not present in 2.19 alpha 1.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2024-05-25 21:56
Duplicate of #15241

**Closed by BrayanDSO** 2024-05-25 21:56 UTC
Labels: Bug, Needs Triage
