### ISSUE TITLE
Deprecation - convert to Preference fragments to avoid old API

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5019] opened 2018-10-06 18:44 UTC
De-linting the codebase and this looks involved - we're using [APIs that say this on the warning](https://developer.android.com/reference/android/preference/PreferenceActivity#addPreferencesFromResource%28int%29):

```
This function is not relevant for a modern fragment-based PreferenceActivity.

```

And the recommendation is to change how preferences are displayed completely, to fragments.

**Comment by timrae** [comment] 2018-10-06 21:07
We already use preference fragments in the main preferences, or are you talking about deck options? If so, good luck with that rats nest lol.

**Comment by mikehardy** [comment] 2020-06-04 23:14
This now affects the ability to move to API29 as a target as there is a fresh batch of deprecation prompting a move to https://developer.android.com/jetpack/androidx/releases/preference - #6365

**Comment by MarioRomanDono** [comment] 2021-03-25 17:37
Hey, I'm taking a look at this. I'm not sure if I'm missing something, but, in order to move to the new API, should I just change the import to `androidx.preference` and remove the old API uses in every affected file? I saw in the `gradle.properties` file that `android.useAndroidX` and `android.enableJetifier` flags are already set to true, which is a requisite pointed [here](https://developer.android.com/jetpack/androidx/migrate#migrate_an_existing_project_using_android_studio).

**Comment by mikehardy** [comment] 2021-03-25 18:35
@MarioRomanDono more or less correct yes? The problem is that I think one or more of the preferences might not be converted to fragments which *may* imply a structural change

Either way it's a wide-ranging change, that's for sure, I just checked to see how many files were affected:

```
mike@isabela:~/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src/main/java (master) % grep -r 5019 
com/ichi2/ui/AppCompatPreferenceActivity.java:@SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/ui/AutoSizeCheckBoxPreference.java:@SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/ui/ConfirmationPreference.java:@SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/ui/SeekBarPreference.java:@SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/anki/AnkiDroidApp.java:    @SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/anki/FilteredDeckOptions.java:    @SuppressWarnings("deprecation") // Tracked as #5019 on github
com/ichi2/anki/FilteredDeckOptions.java:    @SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/anki/FilteredDeckOptions.java:    @SuppressWarnings("deprecation") // conversion to fragments tracked in github as #5019
com/ichi2/anki/FilteredDeckOptions.java:    @SuppressWarnings("deprecation") // Tracked as #5019 on github
com/ichi2/anki/Preferences.java:@SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/anki/Preferences.java:@SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/anki/Preferences.java:    @SuppressWarnings("deprecation") // Tracked as #5019 on github - convert to fragments
com/ichi2/anki/Preferences.java:    @SuppressWarnings("deprecation") // Tracked as #5019 on github
com/ichi2/anki/DeckOptions.java:    @SuppressWarnings("deprecation") // conversion to fragments tracked as #5019 in github
com/ichi2/anki/DeckOptions.java:    @SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/anki/DeckOptions.java:    @SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/anki/DeckOptions.java:    @SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/anki/DeckOptions.java:    @SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/anki/DeckOptions.java:    @SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/preferences/StepsPreference.java:@SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/preferences/TimePreference.java:@SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/preferences/NumberRangePreference.java:@SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/preferences/IncrementerNumberRangePreference.java:@SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019
com/ichi2/preferences/CustomDialogPreference.java:@SuppressWarnings("deprecation") // TODO Tracked in https://github.com/ankidroid/Anki-Android/issues/5019

```

!

**Comment by david-allison-1** [comment] 2021-03-27 19:30
This isn't going to be a good issue for someone due to the magnitude of the change required. Some initial research into the changes which will be made would be useful

**Comment by david-allison-1** [comment] 2021-07-18 23:00
The first step to me would be to remove `onBuildHeaders/loadHeadersFromResource` and move these to fragments.

**Comment by david-allison-1** [comment] 2021-08-11 01:48
The custom preferences require a lot more code to get working: https://stackoverflow.com/a/34398747/13121290

**Comment by david-allison-1** [comment] 2021-08-11 05:01
I'm going to see this through for `Preferences.java`, which will take a large dent out of the work required for `DeckOptions.java`

**Comment by BrayanDSO** [comment] 2022-09-12 22:45
For anyone's information, DeckOptions will be replaced entirely by the new HTML page (#12175) when the new backend is the default. So there is only FilteredDeckOptions to fix (which gives me a headache just by looking at it)

**Comment by dae** [comment] 2023-08-31 06:54
@BrayanDSO is this ok to close?

**Comment by BrayanDSO** [comment] 2023-08-31 07:58
Honestly, I think that it's easier to migrate the desktop filtered Deck options screen to Svelte than migrating our screen to AndroidX prefs. That would benefit AnkiMobile as well, since I haven't found how to create a filtered decks there

**Comment by dae** [comment] 2023-08-31 08:03
AnkiMobile does have a screen (Filter/Cram option in cog menu), but would welcome this being ported to Svelte.

**Comment by BrayanDSO** [comment] 2023-08-31 10:40
Closing this as duplicate of #3625

**Closed by BrayanDSO** 2023-08-31 10:40 UTC
Labels: Priority-Low, Help Wanted, Keep Open, Deprecation
