### ISSUE TITLE
[Bug] footer and header missing

### ISSUE THREAD

**Issue by yeeping1** [ankidroid/Anki-Android#8139] opened 2021-03-03 13:40 UTC
I already reinstalled the app but the problem still exists.
footer and header button disappear but those button still work.

![problem](https://user-images.githubusercontent.com/50470520/109813962-f7c11000-7c68-11eb-8721-35b515f1c5dd.jpg)

Other details
AnkiDroid Version = 2.14.3

Android Version = 8.1.0

ACRA UUID = b14fcaf6-c5cc-4b21-bacd-a09b349a28ca

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2021-03-03 14:15
I believe this may duplicate #7369  ? Have you tried clearing the cache to see if it resolves (temporarily - it is still a bug, that is a workaround)

**Comment by yeeping1** [comment] 2021-03-03 14:28
> I believe this may duplicate #7369 ? Have you tried clearing the cache to see if it resolves (temporarily - it is still a bug, that is a workaround)

clear cache already but problem still exist.  thanks to tell me #7369

**Comment by mikehardy** [comment] 2021-03-07 19:02
This is definitely a duplicate of #7369 - still exists, clearing cache/data is a valid *workaround* but is of course terrible in the long run. We're working on it...

**Closed by mikehardy** 2021-03-07 19:02 UTC
Labels: Waiting For Feedback
