### ISSUE TITLE
Review session returns to deck screen after every card with "No cards are due" message

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#3745] opened 2015-10-18 16:36 UTC
I have been having a strange problem since recently. I will explain it using an example from today:
- I have 19 cards to review, and I press 'study'
- I press '10 minutes/again' for the first card -> the review session stops and gets me back to the deck screen with a toast saying 'no cards are due yet.'
- I press 'study' again, and go to the next card
- I press '10 minutes/again' -> the review session stops again and gets me back to the deck screen with the same toast
- repeat until the review list is exhausted

This is very annoying on the long run. I tested it with the desktop version, starting from the same deck state, and it's behavior is correct.

Has a similar issue been created yet? If necessary, I can make my collection available to reproduce the issue. I guess I could also record a video from my session, just tell me where to put it.

**Comment by hssm** [comment] 2015-10-19 00:50
It's a duplicate of https://github.com/ankidroid/Anki-Android/issues/3640 so I'll close this one.

A copy of your collection would help. I haven't been able to reproduce this on my end yet.

Do you have the widget enabled? Do you have notifications turned on?

**Comment by wujek-srujek** [comment] 2015-10-19 17:51
In the last week, I made the following changes:
- added an extra step for new cards on the desktop client
- started using notifications (to inform me when > 10 cards are due)
- started using the widget

Your comments made me try revert the various settings, and it turns out, removing the widget from the home screen seems to be fixing the issue for me! Re-adding the widget again introduces the feature again.
Seems the widget is the culprit, at least in my case. I haven't read the other issue yet, let's see what  it says about it.

**Comment by wujek-srujek** [comment] 2015-10-19 18:38
Here is a link to my collection (doesn't github support attachments??):
https://file.io/g8dxq2

How I imported it and was able to reproduce the issue:
- Go to your AnkiDroid folder (for me it was /storage/emulated/0/AnkiDroid) and delete everything.
- Copy the attached file into this folder.
- Go to you system settings and set the time to 18. Oct 2015 (yesterday, as of this writing), 22:00:00. As Anki scheduling is time sensitive, you might need to set 'GMT+02:00 Central European Summer Time' to reproduce my timing. Note: you will need to disable 'Automatic date & time' and 'Automatic time zone' to be able to set date/time/zone info.
- Add the Anki widget to your home screen. You should see 19 due cards.
- Start Anki and pick the 'Español' deck, which has 19 cards due (red color, I guess this is learning?)
- Press 'Study' - you should see the question 'porywczy; gwałtowny; porywisty', pick 'Show answer', press '10 minutes/again'.
At this point, you will be moved back to the deck information screen with a toast saying no cards are due.
- Press 'Study' - you will see the second question.
- 'Press 'Show' and then '10 minutes/again' - you are moved to the deck info screen again.
- Repeat until the deck is exhausted.

I have been able to reproduce the issue 100% of the time with the above steps, I hope it will also work for you.

- Now, go to the deck again and press 'undo' as many times as necessary to revert the deck to the 'original' state (with 19 due cards).
- Go to the home screen, remove the widget.
- Start Anki, start the review seesion and enjoy correct behavior.

**Comment by wujek-srujek** [comment] 2015-10-19 18:52
It turns out, without the widget, but with the notifications set to '> 10 due cards', the issue also manifests itself. So it seems to be an issue when anything else except for the Anki reviewer proper reads the scheduler data.

**Comment by hssm** [comment] 2015-10-21 07:04
This is like the perfect bug report, thanks! I've been able to reproduce it following your steps. Hopefully I'll have a fix for it soon.

**Comment by hssm** [comment] 2015-10-25 07:16
I originally marked this as a duplicate but the other issue *might* be something else, so I will use this issue for the main "no cards are due" bug. There's a fix on the way for that.

**Closed** 2015-10-25 16:52 UTC
