### ISSUE TITLE
Complicated code in BeolingusParser

### ISSUE THREAD

**Issue by rillig** [ankidroid/Anki-Android#4685] opened 2017-08-12 13:39 UTC
###### Research

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Look at the `BeolingusParser`. 

###### Expected Result

The parser code is simple.

###### Actual Result

The parser code is complicated.

###### Suggested Code

    private static final Pattern PATTERN = Pattern.compile("" +
            "<a href=\"([^\"]+)\"[^>]*>" +
            "<img src=\"/pics/s1[.]png\"[^>]*title=\"([^\"]+)\"[^>]*>");

    /**
     * @param html HTML page from beolingus, with translation of the word we search
     * @return {@code "no"} or the pronunciation URL
     */
    public static String getPronunciationAddressFromTranslation(String html, String wordToSearchFor) {
        Matcher m = PATTERN.matcher(html);
        while (m.find()) {
            if (m.group(2).equals(wordToSearchFor)) {
                return "http://dict.tu-chemnitz.de" + m.group(1);
            }
        }
        return "no";
    }

    @Test
    public void test() {
        String html = ""
                + "<a href=\"/dings.cgi?speak=de/0/7/52qA5FttGIU;text=Wasser\" "
                + "onclick=\"return s(this)\" onmouseover=\"return u('Wasser')\">"
                + "<img src=\"/pics/s1.png\" width=\"16\" height=\"16\" "
                + "alt=\"[anhören]\" title=\"Wasser\" border=\"0\" align=\"top\" /></a>";

        String pronunciationUrl = BeolingusParser.getPronunciationAddressFromTranslation(html, "Wasser");
        assertEquals(pronunciationUrl, "http://dict.tu-chemnitz.de/dings.cgi?speak=de/0/7/52qA5FttGIU;text=Wasser");
    }

**Comment by timrae** [comment] 2017-08-12 13:48
Can you make a merge request please? I'm closing this as it's not a bug or a feature request.

**Closed by timrae** 2017-08-12 13:48 UTC
