### ISSUE TITLE
New typed answer dialog doesn't provide same hints to keyboard application

### ISSUE THREAD

**Issue by flimzy** [ankidroid/Anki-Android#3913] opened 2015-12-01 13:03 UTC
The new version of the app looks great to me, but typing in the answer now produces a different behavior which I think is objectively wrong (in contrast to issue #3912, which seems to be full of subjective issues).

With the old app, my keyboard app new not to upper-case the first letter of input.  With the new version, my keyboard thinks it should be upper-case, which means I must use several extra keystrokes (exact number is keyboard dependent), or enter an answer which AnkiDroid thinks is "wrong", because the first character of my answer is upper case, while it was expecting lower case.

I'm not entirely sure what mechanism controls this behavior, but I suspect there's a simple input hint/class that ought to be set that no longer is.

**Comment by eginhard** [comment] 2015-12-01 13:33
Duplicate of #3910

**Closed by eginhard** 2015-12-01 13:33 UTC
