### ISSUE TITLE
Feature request: Import flashcards from CSV (or any other delimiter)

### ISSUE THREAD

**Issue by dkateiva** [ankidroid/Anki-Android#4749] opened 2017-12-12 17:40 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Feature request
Would be nice to have a feature similar to the one in Anki desktop - importing flashcards from a CSV file or from file with a custom delimiter (of course with UTF-8 and HTML support).

**Comment by timrae** [comment] 2017-12-18 05:18
Duplicate of #3517

**Closed by timrae** 2017-12-18 05:18 UTC
