### ISSUE TITLE
AnkiDroid 2.13alpha14 crashes with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mawis** [ankidroid/Anki-Android#6906] opened 2020-08-17 06:36 UTC
###### Reproduction Steps

This is what I do:

1. Update to 2.13alpha14 from the beta channel
2. keep studying some cards

###### Expected Result

AnkiDroid keeps running instead of crashing.

###### Actual Result

After studying some cards, AnkiDroid crashes at the moment I'm pressing one of the answer buttons.

###### Debug info
In the Android log I see the following message:

```
08-17 08:26:03.590  1705  2178 W InputTransport: Slow Input: 261ms so far, channel '6ee75ba GestureStub (server)' publisher ~ publishMotionEvent: seq=14850928, deviceId=7, source=0x1002, action=0x0, actionButton=0x00000000, flags=0x10000, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=-2365.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=1050677364000000, eventTime=1050677364104000, pointerCount=1
08-17 08:26:03.590  1705  2178 W InputTransport: Slow Input: 262ms so far, channel 'gesture_input_monitor (server)' publisher ~ publishMotionEvent: seq=14850929, deviceId=7, source=0x1002, action=0x0, actionButton=0x00000000, flags=0x10000, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=0.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=1050677364000000, eventTime=1050677364104000, pointerCount=1
08-17 08:26:03.590  1705  2178 W InputTransport: Slow Input: 262ms so far, channel 'PointerEventDispatcher0 (server)' publisher ~ publishMotionEvent: seq=14850930, deviceId=7, source=0x1002, action=0x0, actionButton=0x00000000, flags=0x10000, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=0.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=1050677364000000, eventTime=1050677364104000, pointerCount=1
08-17 08:26:03.591  1705  2178 W InputTransport: Slow Input: 263ms so far, channel '9df6915 StatusBar (server)' publisher ~ publishMotionEvent: seq=14850934, deviceId=7, source=0x1002, action=0x4, actionButton=0x00000000, flags=0x10000, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=0.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=1050677364000000, eventTime=1050677364104000, pointerCount=1
08-17 08:26:03.591  1705  2178 W InputTransport: Slow Input: 263ms so far, channel 'e263a73 com.ichi2.anki/com.ichi2.anki.Reviewer (server)' publisher ~ publishMotionEvent: seq=14850935, deviceId=7, source=0x1002, action=0x0, actionButton=0x00000000, flags=0x10000, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=0.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=1050677364000000, eventTime=1050677364104000, pointerCount=1
08-17 08:26:03.591  1705  2178 W InputTransport: Slow Input: 263ms so far, channel 'gesture_input_monitor (server)' publisher ~ publishMotionEvent: seq=14850936, deviceId=7, source=0x1002, action=0x0, actionButton=0x00000000, flags=0x10000, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=0.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=1050677364000000, eventTime=1050677364104000, pointerCount=1
08-17 08:26:03.591  1705  2178 W InputTransport: Slow Input: 263ms so far, channel 'PointerEventDispatcher0 (server)' publisher ~ publishMotionEvent: seq=14850937, deviceId=7, source=0x1002, action=0x0, actionButton=0x00000000, flags=0x10000, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=0.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=1050677364000000, eventTime=1050677364104000, pointerCount=1
08-17 08:26:03.591  1705  2397 I MiuiGesture: status: Unknown -> Detected
08-17 08:26:03.591  1705  2178 W InputTransport: Slow Input: 170ms so far, channel 'e263a73 com.ichi2.anki/com.ichi2.anki.Reviewer (server)' publisher ~ publishMotionEvent: seq=14850938, deviceId=7, source=0x1002, action=0x1, actionButton=0x00000000, flags=0x100000, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=0.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=1050677364000000, eventTime=1050677457842000, pointerCount=1
08-17 08:26:03.591  1705  2178 W InputTransport: Slow Input: 170ms so far, channel 'gesture_input_monitor (server)' publisher ~ publishMotionEvent: seq=14850939, deviceId=7, source=0x1002, action=0x1, actionButton=0x00000000, flags=0x100000, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=0.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=1050677364000000, eventTime=1050677457842000, pointerCount=1
08-17 08:26:03.592  1705  2178 W InputTransport: Slow Input: 170ms so far, channel 'PointerEventDispatcher0 (server)' publisher ~ publishMotionEvent: seq=14850940, deviceId=7, source=0x1002, action=0x1, actionButton=0x00000000, flags=0x100000, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=0.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=1050677364000000, eventTime=1050677457842000, pointerCount=1
08-17 08:26:03.593  1705  2397 I MiuiGesture: status: Detected -> Unknown
08-17 08:26:03.594  1705  2397 I MiuiGesture: status: Unknown -> Detected
08-17 08:26:03.594  1705  2397 I MiuiGesture: status: Detected -> Unknown
08-17 08:26:03.594  2560  2560 D NavStubView: distouch : true
08-17 08:26:03.603 30121 30121 I AnkiDroid: AbstractFlashcardViewer:: EASE_4 pressed
08-17 08:26:03.604 30121 30895 I AnkiDroid: Answering card
08-17 08:26:03.604 30121 30895 I AnkiDroid: Answering card 1502057080674
08-17 08:26:03.626 30121 30121 D AndroidRuntime: Shutting down VM
08-17 08:26:03.627 30121 30121 E AndroidRuntime: FATAL EXCEPTION: main
08-17 08:26:03.627 30121 30121 E AndroidRuntime: Process: com.ichi2.anki, PID: 30121
08-17 08:26:03.627 30121 30121 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=3; index=-2
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:6)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.anki.AbstractFlashcardViewer.updateScreenCounts(AbstractFlashcardViewer.java:3)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:11)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:1)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:34)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:16)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:775)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:227)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7582)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
08-17 08:26:03.627 30121 30121 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
08-17 08:26:03.628   568   568 E SELinux : avc:  denied  { find } for service=miui.mqsas.MQSService pid=30121 uid=10252 scontext=u:r:untrusted_app_27:s0:c252,c256,c512,c768 tcontext=u:object_r:mqs_service:s0 tclass=service_manager permissive=0
08-17 08:26:03.629 30121 30121 E MQSEventManagerDelegate: failed to get MQSService.
08-17 08:26:03.638 30121 30121 E ACRA    : ACRA caught a ArrayIndexOutOfBoundsException for com.ichi2.anki
08-17 08:26:03.638 30121 30121 E ACRA    : java.lang.ArrayIndexOutOfBoundsException: length=3; index=-2
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.libanki.sched.SchedV2.counts(SchedV2.java:6)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.anki.AbstractFlashcardViewer.updateScreenCounts(AbstractFlashcardViewer.java:3)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.anki.AbstractFlashcardViewer.updateForNewCard(AbstractFlashcardViewer.java:1)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.anki.AbstractFlashcardViewer.fillFlashcard(AbstractFlashcardViewer.java:11)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.anki.Reviewer.fillFlashcard(Reviewer.java:1)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:34)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:16)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:775)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at android.os.Looper.loop(Looper.java:227)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:7582)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
08-17 08:26:03.638 30121 30121 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X ] I have searched for similar existing issues here and on the user forum
- [X ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment] 2020-08-17 09:00
Hi @mawis, thanks for the report! This is a duplicate of #6903 and will be fixed in the next alpha.

Any further discussion would be best consolidated in the above issue.

Sorry for the inconvenience & thanks again for the feedback!

David

**Closed by david-allison-1** 2020-08-17 09:00 UTC

**Comment by mikehardy** [comment] 2020-08-17 15:49
We'll have a new alpha out shortly @mawis - sorry for the hassle but we really really appreciate the alpha testing and hope you'll stay on the alpha track. In the meantime you can install the old alpha "parallel" build and it will allow you to continue reviewing: https://github.com/ankidroid/Anki-Android/releases/tag/v2.13alpha13 - specifically https://github.com/ankidroid/Anki-Android/releases/download/v2.13alpha13/AnkiDroid-2.13alpha13.parallel.A.apk

**Comment by mawis** [comment] 2020-08-18 06:52
Thanks … I couldn't identify this as the same bug.

**Comment by mikehardy** [comment] 2020-08-18 14:11
@mawis the new alpha should be out now (as of about 14hrs ago actually...) so should be fixed for you. Sorry again about the hassle but thank you very much for trying alphas and taking the time to report, it's how we make progress
