### ISSUE TITLE
Add ability to insert clozes in note editor

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2520] opened 2015-07-28 09:43 UTC
Originally reported on Google Code with ID 1618

```
What steps will reproduce the problem?
1. Press plus symbol to insert new card
2. Change note type from basic to cloze  
3. Insert text in to fields to have 

What is the expected output? What do you see instead?
I don't understand how to input the clozes on my android phone, It's easy on the mac
app and ankiwed but there are no option under the menus to insert the clozes and if
i double press any words the get the android clipboard options: cut paste etc.

Does it happen again every time you repeat the steps above? Or did it
happen only one time?
yes always


What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title)

Ankidroid 2.0

On what version of Android? (Home screen > menu > About phone > Android
version)

Android version 2.3.5


If it is a crash or "Force close" and you can reproduce it, the following
would help immensely: 1) Install the "SendLog" app, 2) Reproduce the crash,
3) Immediately after, launch SendLog, 4) Attach the resulting file to this
report. That will make the bug much easier to fix.


Please provide any additional information below.

The answer to this could simply be that it's not possible to insert clozes within Ankidroid,
I'm hoping it's other wise.

```

Reported by `talktoianobrien` on 2013-01-19 17:36:19

**Comment by x1704e** [comment] 2015-10-28 09:35
Are there any updates on the progress of implementing this feature?

**Comment by timrae** [comment] 2015-10-28 09:39
@x1704e 
There has been no progress unfortunately. I've added the HelpWanted label to make this issue easier to find for new developers.

**Comment by kabutar111** [comment] 2015-11-23 14:19
It will greatly make ankidroid, more independent.

**Comment by Ruckamongus** [comment] 2016-03-13 20:38
In the desktop version of Anki you can use the keyboard shortcut control+shift+c to insert a new "{{c1::}}" around selected text (or just by itself if no text is selected). Is this possible on Android devices with a keyboard?

**Comment by Tj20** [comment] 2017-05-12 22:25
I downloaded AnkiDroid and this was the first problem I found with the app within half an hour... it's strange that this problem persists since two years now.

I'm no dev, but highlighting text and modifying it with some {{c1::}}" should definitely be possible. I have an app where you can select text, press a button named "bold", "italic" etc. and the selected part of the text gets the appropriate markup... but I guess nearly every app where you can input text and change its markup does that.

I think you can also change the context menu ("select all, copy, cut") that pops up when you select some text like this:

> I think what you're looking for is TextView.setCustomSelectionActionModeCallback. This will allow you to create your own ActionMode.Callback for when the text is selected.
[stackoverflow](http://stackoverflow.com/questions/22832123/get-selected-text-from-textview)

**Comment by eginhard** [comment] 2017-05-12 22:54
@Tj20 The issue is not that this is necessarily difficult, but that there are currently no developers who have time to work on this.

**Comment by MatMoore** [comment] 2017-05-13 09:19
@eginhard does this need a core developer to look at it first or could anyone new the project pick it up?

I'm not an android dev, but if I would be happy to spend some time looking at this if you can give me some pointers on where to start.

**Comment by timrae** [comment] 2017-05-13 10:03
Isn't this already fixed by #4606?

**Comment by timrae** [comment] 2017-05-13 10:46
I don't have time to check right now, but it's probably in the alpha
version... Can you try?

**Comment by Tj20** [comment] 2017-05-14 19:56
Thanks, I've downloaded the latest alpha (2.9alpha3, 16 Mar) from [here](https://github.com/ankidroid/Anki-Android/tags) and gave it a try.

The changes by @mooingcat look like a very good early implementation of this feature. Making new clozes on Android is a thing now, yay!

I've noticed a couple of things (but this version is already very usable):

- it only works when adding a new note, but not when you want to edit an existing note
- the context menu (cut/copy/paste) sometimes overlaps the paperclip menu and so you can't click on it, depending on the length of your text and what you want to select
- after inserting a cloze, the cursor does what it wants, as mooingcat already pointed out. On my Android 6.0.1 phone the cursor jumps to the beginning of the text field. IMO it would be nice if the cursor would jump to the beginning or end of the second `}}` so it would be easy to move on or to put a cloze hint into the brackets, like `{{c1::l'eau::french word for water}}`. But as mooingcat said, it might be complicated to implement and it's not that annoying.
- all clozes are marked "c1", as mooingcat said. In the desktop version you can decide if they're all the same or if you want "c1, c2, c3..." with each new selection.

**Closed** 2017-05-15 00:00 UTC
Labels: accepted, enhancement, HelpWanted, Priority-Medium
