### ISSUE TITLE
ETA uses hours instead of minutes since 2.10alpha50

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5829] opened 2020-03-17 20:12 UTC
###### Reproduction Steps

1. Go to deck list
2. Look at the estimated time

###### Expected Result

It's in minutes, like in the statistics for "Review Time" and the widget.

###### Actual Result

It's hours instead of minutes. That makes the ETA quite imprecise. Any reason for this? 

The only workaround is to use the widget which still shows the exact minutes.

###### Debug info
AnkiDroid Version = 2.10alpha50

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment] 2020-03-17 20:27
Thanks for the report! 
Caused by #5626. @Arthur-Milchior @mikehardy

**Comment by Anthropos888** [comment] 2020-03-17 20:36
Personally I prefer just minutes so that the "Review Time" in the statistics matches the ETA. 

"1h 20min" for example would also be fine. But at the moment I just see "1 h" even though the widget says 80min. That "1 h" is too imprecise.

**Comment by Arthur-Milchior** [comment] 2020-03-17 20:45
It can easily be changed if the maintener want me to change it.
I don't have strong opinion about whether to display minutes.

**Comment by david-allison-1** [comment] 2020-03-17 20:51
[I have no strong feelings one way or the other](https://www.youtube.com/watch?v=CxK_nA2iVXw), but a preference under "Appearance" sounds like a good compromise to me.

**Comment by mikehardy** [comment] 2020-03-17 23:03
I agree 1h is too imprecise, and I'm trying to avoid expansion in preferences unless it is really changing behavior - we get lots of complaints on how difficult the app is to use and too many options leads to those complaints.

I do agree with the point of the original PR though, 8245 minutes (for example) is also sort of useless. How long is that?

Perhaps we do minutes until it is a large quantity of minutes, then convert to hours. A reasonable breakpoint might be 999 minutes. 999 and below we say minutes, 999 and above we say hours. I can basically picture that, but after that I don't relate it well to a real duration.

A quick vote

It should change the widget too, I think

**Comment by Arthur-Milchior** [comment] 2020-03-17 23:12
999 seems already a lot to me. 1 don't see what would be the problem with "1h20". Doesn't take much space, seems clear. 
As always, I'm not at ease with the fact that only github user vote. We are not a representative group of users

**Comment by Anthropos888** [comment] 2020-03-17 23:16
I agree, "1h 20min" would be nice.

**Comment by mikehardy** [comment] 2020-03-17 23:18
We get to vote because we do the work, it's sort of a convenience / velocity tradeoff. Opening a public vote takes forever and at a certain point if we're doing the work we make our best effort then move on :man_shrugging: - I'm okay with 1h 20m format then, works for me

**Comment by david-allison-1** [comment] 2020-03-17 23:26
An alternate perspective: minutes.

I'm never going to get my collection to 0, so the delta motivates me.

I'm currently seeing "1d", which is much less useful than minutes. 1d 16h 37m is probably too long, and thinking about it as a time rather than a number makes me (rightfully) feel bad.

It'd be demotivating to do a study session and not have the number change if we chose the second two most significant

**Comment by Anthropos888** [comment] 2020-03-18 07:33
> 1d 16h 37m is probably too long

Yeah, definitely too long for the widget which can only show 4 digits.

Probably it's the best to just leave it plain minutes as it was before alpha50 and don't change anything.

**Comment by david-allison-1** [comment] 2020-03-18 11:59
Tangent:

>  I'm trying to avoid expansion in preferences unless it is really changing behavior - we get lots of complaints on how difficult the app is to use and too many options leads to those complaints.

I agree with the premise, but disagree with the result. IMO, users struggle with the application because we don't explain Anki's state model/internals well. Even mid to advanced users will struggle with "What is the first step?". Appearance settings should be obvious, even to new users.

We should work on this (#4334), but I don't feel appearance settings will make Anki more difficult to use (although there is a minor discoverability issue).

**Comment by mikehardy** [comment] 2020-03-18 14:19
reasonable points @david-allison-1 - I'd love to see #4334 brought home, the rank of play store reviews saying effectively "I installed the app and it's empty, now what?" puts that issue as maybe second item (behind I want a WYSIWYG editor) as enhancements users want. I have a tendency to go with "implementor's choice" as a policy for implementors that demonstrate a commitment to follow-up work when there are problems. Specifically I mean: if someone is willing to implement something and support it, even if it's a little counter to my preference, I'm likely to go with it.

**Comment by mikehardy** [comment] 2020-03-18 14:21
So concretely for this: @Arthur-Milchior maybe the feature is re-shaped to have a pref for "Human-readable review ETA display" and if toggled on it has current behavior, if toggled off it's just raw minutes (previous behavior)? If not, then we need to have a threshold where we convert to just hours, so we don't lose so much precision, and the widget will just need to have raw minutes for space reasons

**Comment by Arthur-Milchior** [comment] 2020-06-10 00:29
Both are easy to implement it seems. I have no preference. As it's mostly a GUI question, and not a technical one, I don't believe I've anything specially relevant to say here

**Comment by mikehardy** [comment] 2020-06-18 19:47
Altered as well as possible we think in #6495

**Comment by david-allison-1** [comment] 2020-06-19 03:14
"Easy" in the reviewer now shows the hours component, rather than just the number of days.

**Comment by Arthur-Milchior** [comment] 2020-06-19 13:12
Strange, I would have expected to see such an error. I'll look later

**Comment by mikehardy** [comment] 2020-06-28 17:25
This was fixed by #6509

**Closed by mikehardy** 2020-06-28 17:25 UTC
Labels: Bug

**Comment by p4nix** [comment] 2020-09-26 20:35
Possibly related discussion (@Arthur-Milchior recommended putting this here, so it doesn't get lost in the Discord abyss):

Currently, if "Show ETA" is enabled for the reviewer, it will show the time left in a strange "N hours NN left" message. Recently, there has been some discussion in the Discord started by a user with many top bar buttons who could only read "1 hour..." because of the text being cut off. He wanted an option to show the time left in a shorter minute-only time format. Obviously, adding an extra-option for that will bloat the Settings.

Why not rather use the same format as on the Deck screen, "N h NN m", or even without the whitespace ("NhNNm")? The currently displayed message is a bit long, inconsistent with the Deck screen and even misses the unit for the minutes.

![Untitled](https://user-images.githubusercontent.com/7038116/94349815-81303e80-0048-11eb-8caa-d75e8f46f0d7.png)
