### ISSUE TITLE
Investigate performance issues

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3979] opened 2015-12-09 02:00 UTC
Some users have reported performance issues with the 2.5 release. This issue will be used for tracking down the cause of the problem.

Some questions:
- 1. Is your AnkiDroid data on an SD card?
- 2. What is the path to your AnkiDroid directory (Settings -> Advanced -> Collection path)
- 3. In which functions of the application do you encounter slow-downs? Please test things like searching in the card browser and emptying/rebuilding filtered decks. (Mainly, is it happening when reading data, saving data, or both?).
- 4. Approximately how many decks and cards are in your collection? Use the card browser see the number of cards (select All decks).
- 5. Does your collection have lots of sub-decks? Are they deeply nested (3 or more parents)?

The main concern is whether our recent switch to a different database journaling mode is the cause of the issues. To accurately test for this as the cause we need you to test an older version where this change was an optional setting.

Just to be safe, **please sync your collection and ensure you have recent backups**. Then, install [this apk](https://github.com/ankidroid/Anki-Android/releases/download/v2.5beta16/AnkiDroid-2.5beta16.apk) of a previous release. Note that you may need to uninstall your existing version of AnkiDroid which will clear your preferences.

In this apk there is a setting that switches between database modes: `Settings -> Advanced -> Enable write-ahead-logging`. Please test out AnkiDroid with this setting enabled and disabled and let us know how the performance of each compares.

**Comment by lovasoa** [comment] 2015-12-17 06:49
I'm also having performance issues with the latest release. Using the "back" button to switch to the previous card can take up to several seconds.

**Comment by spookylukey** [comment] 2016-06-16 13:04
I'm experiencing bad performance on my device. Here are symptoms and answers to questions:

1) My AnkiDroid data is on an SD card

2) The path is /storage/17F7-802D/AnkiDroid

I had to set this up manually, because I want it to save to my SD card, not internal storage. On my device, since an Android upgrade where I chose to have removable SD card, the path /sdcard/ actually goes to internal storage, and /storage/17F7-802D goes to the real SD card.

3) I get a pause after certain actions, usually when I would expect AnkiDroid to be saving data. The time I notice it for sure is after a card is shown and I select a button (or do a gesture) to indicate "Again" or "Good". At this point, with AnkiDroid 2.5 I sometimes saw a delay of up to 3 seconds before the next card was shown. After upgrading to AnkiDroid 2.6 just the other day it got worse, up to 8 seconds before the next card is shown. The gesture/button is definitely recognised immediately, because the coloured dots are shown immediately, but the next card is not.

Sometimes it does not happen, I think with some decks. On others, I get the pause about every 5 to 10 cards (I think - it might be less but long pauses makes you feel like it is very often).

Also, the 'writing changes to DB' phase of syncing seems to be slower than I expect, but it's difficult to be sure.

4+5) I have about 3000 cards in my collection, roughly split into about 20 decks, none of which are 'sub' decks.

I tried the APK you linked to. With it, I am getting the same 2-3 second pauses I was getting before with 2.5. When I enabled the 'write ahead logging' option, it seems that the frequency of the pauses goes down, but they don't go away entirely (something like once every 20 cards), and can be 4 to 5 seconds. I'll keep this on and see if I have more observations after a while.

I can supply my entire DB if you want, it is not private. I have SDK tools and could get the files off the device from my Linux laptop. I could also run some tests using SDK tools if you want, but my knowledge of Android dev is extremely limited, you'll have to tell me the exactly the commands to run.

**Comment by hssm** [comment] 2016-06-17 19:18
I don't recall there being any changes between 2.5 and 2.6 that impacts database transactions so I'm surprised (and somewhat confused) to hear about your experience.

The best thing you could provide would be a log file from a debug session that we can walk through and see exactly where the pauses are occurring. Hopefully the [guide on the wiki](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide) is clear enough to help you figure out how to do that if you are interested. From the way you've described it, there is also a possibility that some of your cards (or templates) are triggering some condition that takes a really long time to render.

At this stage we are almost certainly not going to re-introduce the WAL journal mode and I had planned on closing this issue after the release went out.

**Comment by spookylukey** [comment] 2016-06-20 18:32
OK, thanks for the pointers, I will hopefully look into that and provide a debug log, in a new issue if necessary, but I won't have time to do it soon, it might be a month or so.

**Comment by zaz** [comment] 2016-10-06 19:30
I'm experiencing very similar problems to @spookylukey: I have normal decks but experience occasional long pauses, especially when using the back button. Syncing takes ~15s.

**Comment by spookylukey** [comment] 2016-10-07 05:29
I've found that for me, *sometimes* the issue can be resolved by creating a "fresh" database:

1) Sync to Ankiweb
2) In advanced settings, change the location to a new place, effectively creating a new DB
3) Sync from Ankiweb again, downloading all my data into the new DB.

Sometimes this doesn't work however.

I now have a collection of DBs! One is terrible - every 2 or 3 cards, it pauses for about 8 seconds. It also seems to depend on which deck I'm using. I'm happy to send the devs the DB files, but I'm afraid I won't be able to do any more debugging.

**Comment by hssm** [comment] 2016-10-07 06:29
I can take a look if you send me your collection but I doubt there will be anything interesting to learn from it. It seems like your SD card is struggling with small and frequent IO.

@zaz 
Tapping back to close an Activity triggers a database save. 15s sync time is normal.

**Comment by lovasoa** [comment] 2016-10-07 06:48
And couldn't the next 10 or so cards be buffered in order to get rid of most of this slow io?

7 октября 2016 г. 9:29:07 GMT+03:00, Houssam Salem <notifications@github.com> пишет:

**Comment by hssm** [comment] 2016-10-07 07:00
Potentially, but it would complicate things quite a bit.

**Comment by mikehardy** [comment] 2018-10-08 03:54
I'm closing this but it's not because I am not interested in performance - #4864 - we are implementing analytics where we could put timing monitors in, and there are features in current development tools that allow pinpointing things as well. We just don't have good reproduction scenarios here at the moment. If anyone has a collection that is performing badly and the scenario to make it do so, by all means post it up

**Closed by mikehardy** 2018-10-08 03:54 UTC
Labels: Priority-High

**Comment by spookylukey** [comment] 2018-10-08 09:50
FWIW, my performance problems were fixed by buying a faster SD card.
