### ISSUE TITLE
Add picture to note: allow picture cropping / editing

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3085] opened 2015-07-28 10:31 UTC
Originally reported on Google Code with ID 2188
```
I am likely to use the Add picture to card feature from e.g. magazines or books and
the keyword is often near/in the picture which should be taken out.

It would be good to facilitate basic editing capability before saving the photo, or
even better, just allow invoking one of the phone's editors by adding a button to deal
with this.
```

Reported by `tilusnet` on 2014-07-20 17:15:45

**Comment by eginhard** [comment] 2015-10-29 09:33
Duplicate of #2554

**Closed by eginhard** 2015-10-29 09:33 UTC
Labels: enhancement
