### ISSUE TITLE
[Bug] Review top-bar button spacing

### ISSUE THREAD

**Issue by joshakaw** [ankidroid/Anki-Android#8970] opened 2021-05-26 21:34 UTC
###### Reproduction Steps

1. Settings
2. Reviewing
3. App bar buttons
4. 2+ actions set to "Always show"
5. Review any deck

###### Expected Result

Evenly spaced icons no matter the amount of action buttons. 

Not part of the issue but if space was a concern of viewing the deck name, maybe have a tooltip.

###### Actual Result

Varied spacing:
- 2 pairs of different spacing "groups" with 4 buttons (including ... button)
- 1 pair spaced in a "group", this group is spaced differently from the ... button

![Screenshot_20210526-170641.png](https://user-images.githubusercontent.com/84877484/119734123-80a2ae80-be48-11eb-9194-02de8c7299e2.png)
![Screenshot_20210526-170437.png](https://user-images.githubusercontent.com/84877484/119734138-85676280-be48-11eb-993d-d558d5ad5997.png)

###### Debug info

AnkiDroid Version = 2.15.0

Android Version = 11

Manufacturer = Google

Model = Pixel 3

Hardware = blueline

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3 Build/RQ1A.201205.003.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 0dad175e-a323-4043-b6d3-cfb5e999ad28

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2021-05-26 21:53
Hi there! Thanks for pointing this out. If you're a designer that's probably maddening, just like when kerning is off ;-)

This may be related to some of the accessibility work that went on for 2.15. Accessibility guidelines prescribe a certain amount of space around tappable elements and we made some changes to adhere to them, but the application may be uneven

Marking for triage

**Comment by vinishhub** [comment] 2021-05-27 07:25
I would like to work on it

**Comment by david-allison-1** [comment] 2021-05-27 10:25
sounds good to me

**Comment by vinishhub** [comment] 2021-05-31 17:22
how can i solve this issue?

**Comment by david-allison-1** [comment] 2021-05-31 17:30
> how can i solve this issue?

I don't know - needs investigating, likely with the layout inspector

**Comment by vinishhub** [comment] 2021-06-02 11:25
https://user-images.githubusercontent.com/76252038/120472040-126b6800-c3c3-11eb-8f13-981768b6cded.mp4

this was my investigation🕵🏼‍♂️.

**Comment by david-allison-1** [comment] 2021-06-02 12:53
Awesome! What does it look like in 2.14.6

**Comment by vinishhub** [comment] 2021-06-02 14:33
https://user-images.githubusercontent.com/76252038/120498933-418ed300-c3dd-11eb-84b2-aba13fb6b055.mp4

here's the look of 2.14 @david-allison-1

**Comment by david-allison-1** [comment] 2021-06-02 14:58
Ok, now we need to know the parameters to change to fix this

**Comment by vinishhub** [comment] 2021-06-02 15:17
can we change left and right padding ??
in [reviewer_toolbar.xml](https://github.com/ankidroid/Anki-Android/blob/658653ad28d45c0ee25ecd7f61699621f1373b36/AnkiDroid/src/main/res/layout/reviewer_topbar.xml#L7)

**Comment by david-allison-1** [comment] 2021-06-02 15:32
> can we change left and right padding ??
> in [reviewer_toolbar.xml](https://github.com/ankidroid/Anki-Android/blob/658653ad28d45c0ee25ecd7f61699621f1373b36/AnkiDroid/src/main/res/layout/reviewer_topbar.xml#L7)👈🏼

I'd expect that it's due to the image sizes since different images now have different widths

**Comment by vinishhub** [comment] 2021-06-02 17:43
> I'd expect that it's due to the image sizes since different images now have different widths

what should be the width of image ? 
currebtly the size is 24 dp

**Comment by david-allison-1** [comment] 2021-06-02 17:56
What gives you the correct result?

**Comment by vinishhub** [comment] 2021-06-02 19:55
> What gives you the correct result? Some of them seem to work already
`<dimen name="side_margin">30dp</dimen>` this works

**Comment by vinishhub** [comment] 2021-06-03 16:19
![WhatsApp Image 2021-06-03 at 21 48 13](https://user-images.githubusercontent.com/76252038/120678204-7cfcd080-c4b5-11eb-81c7-e297190daaba.jpeg)

**Comment by david-allison-1** [comment] 2021-06-03 17:14
That doesn't look like it matches 2.14.6, can you compare the two. Our main goal is to ensure that there isn't a regression

**Comment by vinishhub** [comment] 2021-06-03 19:00
> That doesn't look like it matches 2.14.6, can you compare the two. Our main goal is to ensure that there isn't a regression

I have changed the width of image here so this was the result. Here changing width doesn't work.
@david-allison-1 what if change space of tappable  area.

**Comment by david-allison-1** [comment] 2021-06-03 19:01
I don't have experience with this, try it and see!

**Comment by david-allison-1** [comment] 2021-06-09 01:11
Just to note: I expect the fix will mean that we can revert https://github.com/ankidroid/Anki-Android/pull/9038

**Comment by david-allison-1** [comment] 2021-06-09 02:18
I've had a longer look into this, it appears that the underlying issue is related to #9038 : `RtlCompliantActionProvider` wasn't mirroring the Android System. It wasn't an SVG-related issue

Needs confirmation, but I believe this can be fixed by replacing: https://github.com/ankidroid/Anki-Android/blob/7351e8481615bb2edd181153a6d9db8c429cf776/AnkiDroid/src/main/res/layout/rtl_menu_item.xml

with 

https://android.googlesource.com/platform/frameworks/base/+/f966ed949c4aa14de5b070cc36039493f98848f1/core/res/res/layout/action_menu_item_layout.xml 

specifying the copyright correctly and then removing the manual padding from 

https://github.com/ankidroid/Anki-Android/blob/8ed613568efef958e1c69e5c974614c073a571bd/AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java#L92-L94

**Comment by vinishhub** [comment] 2021-06-09 05:39
> I've had a longer look into this, it appears that the underlying issue is related to #9038 : `RtlCompliantActionProvider` wasn't mirroring the Android System. It wasn't an SVG-related issue
> 
> Needs confirmation, but I believe this can be fixed by replacing: https://github.com/ankidroid/Anki-Android/blob/7351e8481615bb2edd181153a6d9db8c429cf776/AnkiDroid/src/main/res/layout/rtl_menu_item.xml
> 
> with
> 
> https://android.googlesource.com/platform/frameworks/base/+/f966ed949c4aa14de5b070cc36039493f98848f1/core/res/res/layout/action_menu_item_layout.xml
> 
> using an ImageButton, specifying the copyright correctly and then removing the manual padding from
> 
> https://github.com/ankidroid/Anki-Android/blob/8ed613568efef958e1c69e5c974614c073a571bd/AnkiDroid/src/main/java/com/ichi2/ui/RtlCompliantActionProvider.java#L92-L94
After applying these changes this was the result 

https://user-images.githubusercontent.com/76252038/121299448-117e8d00-c913-11eb-8ec4-80945c576303.mp4

**Comment by david-allison-1** [comment] 2021-06-09 10:41
I'm stumped then. Appeared to work for me

**Comment by vinishhub** [comment] 2021-06-09 11:23
![image](https://user-images.githubusercontent.com/76252038/121345860-004d7480-c943-11eb-9fe8-93e4e83d2303.png)
@david-allison-1  i think now its better, what say??

**Comment by david-allison-1** [comment] 2021-06-09 11:37
> ![image](https://user-images.githubusercontent.com/76252038/121345860-004d7480-c943-11eb-9fe8-93e4e83d2303.png)
> @david-allison-1 i think now its better, what say??
> the width of all the buttons are `48dp` now except menu button

The goal is to match how it looked in 2.14.6. If we do this in a sustainable manner, I'm happy

**Comment by vinishhub** [comment] 2021-06-09 14:51
i have compared the layout with 2.14 there also the `more option` button is of same width i.e 40 dp

**Closed** 2021-08-22 23:03 UTC
Labels: Bug, UI, Help Wanted, Needs Triage, Keep Open, 2.15
