### ISSUE TITLE
Bluetooth keyboard with type-in answers not focused automatically

### ISSUE THREAD

**Issue by mmbradle** [ankidroid/Anki-Android#4003] opened 2015-12-15 12:53 UTC
This is new after the last couple of updates.

When I reviewing with a bluetooth keyboard and typing in answers, when a new card comes up I have to hit tab a couple of times to get focus in the type-in section. This is a bit annoying, especially if I hit a "space" key while typing before I realize I don't have focus, then the answer shows up before I'm ready.

**Comment by eginhard** [comment] 2015-12-15 13:20
Duplicate of #3912

**Closed by eginhard** 2015-12-15 13:20 UTC
