### ISSUE TITLE
Soft crash to decklist during reviews.

### ISSUE THREAD

**Issue by JHerseth** [ankidroid/Anki-Android#5780] opened 2020-02-29 12:24 UTC
Every day when I review my deck, I get a "soft crash" where I get dumped back to the deck list. When this happens, the "new cards" also resets, so I get 5 more new cards for that day, even if I went through my 5 for the day.

This happens every day, so I should be able to capture this behaviour while logging or something, if neeed.

###### Reproduction Steps

1. Review cards
2. Until crash
3. The end

###### Expected Result

Complete reviews as normal

###### Actual Result

As noted above, I crash back to the deck list.

###### Debug info
AnkiDroid Version = 2.10alpha41

Android Version = 10

ACRA UUID = e2ba917d-92ec-4989-9467-4b211c9f2952

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

Edit: This bug was present at the latest version on Play Store as well.

**Comment by mikehardy** [comment] 2020-02-29 13:10
I suspect heavy fonts crashing the webview. Are you using any custom fonts or a customized card template? There's a closed issue in the repo focusing on this with workarounds 

Even then, the new cards should not reset. Are you on v1 scheduler or v2?

**Comment by JHerseth** [comment] 2020-02-29 15:15
Yes, I'm using a couple of custom fonts that are a bit heavy and a Bootstrap4 based template with anki-canvas (js script) for writing input. One kanji stroke-order font thats 17mb and a handwritten kanji font at 30mb.

I'm on the v1 scheduler.

If I didn't get new cards, I wouldn't be much bothered by this, but getting 5 new cards after a crash is kinda inconvenient. If there is anything I can do to help (logs etc) let me know.

**Comment by Anthropos888** [comment] 2020-03-06 20:22
@JHerseth I'm curious about the loading times for each of your cards. I'm using 10 different Japanese fonts between 2MB and 7MB each which are loading randomly for every card. I'm using Chrome Canary 76 as webview because all newer versions are significantly slower with fonts, css and js. Still it takes up to 1 second for the fonts to load, and since Chrome doesn't cache fonts anymore since version ~55, the fonts need to be loaded on every single card.

How long does each card need to fully load with your giant 30MB fonts?

**Comment by JHerseth** [comment] 2020-03-07 20:39
> How long does each card need to fully load with your giant 30MB fonts?
Maybe around .3 seconds give or take? Never felt the load time was slow.

**Comment by Anthropos888** [comment] 2020-03-08 11:53
Would you mind uploading a test deck that uses your fonts and scripts? Sounds like you found a way to make fonts load faster. Which webview are you using?

**Comment by mikehardy** [comment] 2020-03-09 12:09
@JHerseth there is no crash by that UUID, I have no crash trace to work with :-(

**Comment by JHerseth** [comment] 2020-03-09 12:35
@Anthropos888 Webview is 80.0.3987.132. I can't share the biggest font since it's not free. This is my CSS for loading the fonts:

`@font-face { font-family: Quicksand; src: url('_Quicksand-Light.ttf'); }
@font-face { font-family: Roboto; src: url('_robotoslab.ttf'); }
@font-face { font-family: gPencil; src: url('_g_pencilkaisho_JISlimit_R.ttf'); }
@font-face { font-family: KanjiStrokeOrders; src: url('_KanjiStrokeOrders.ttf'); }
@font-face { font-family: TakaoMincho; src: url('_TakaoMincho.ttf'); }


@font-face {
  font-family: 'Roboto';
  src: local('TakaoMincho');
  unicode-range: U+2F00-9FFF;
}`

The nonfree(30mb) as well as a limited free version can be downloaded here: https://zarasu.booth.pm/items/389721
Kanji stroke order font is another big one (17mb) is from here: https://www.nihilist.org.uk/

I could share a deck without media files though, if you want.

@mikehardy Ok, guess it's not a normal crash then? My workaround now is just exiting the deck after 10-15 cards and reopening it.  Give me a heads up if theres anything I can help with, but if the problem is upstream I understand that it could be hard (or impossible).

**Comment by mikehardy** [comment] 2020-03-09 13:05
Yeah, the WebView actually runs in a separate process with isolation. 
I had to handle something similar in a different app, but I think the solution will be to listen for and correctly handle WebView termination events. 

https://developer.android.com/guide/webapps/managing-webview#termination-handle

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1415

@JHerseth you are already on alpha builds right? If so I can at least try to put some instrumentation here (via the termination handler) to see if we are on the right track

**Comment by Anthropos888** [comment] 2020-03-09 13:18
> I could share a deck without media files though, if you want.

That would be great. I can use it with my own fonts and see how fast it is.

**Comment by JHerseth** [comment] 2020-03-09 17:36
@mikehardy  yeah, I'm on alpha41

@Anthropos888 here is my full deck with media, minus the nonfree font. I'm probably in breach of some EULAs here, but atleast the stuff that's still in there is free (beer) - I'll unshare the file in a day or two. https://mega.nz/#!4pxTETxB!lqR1pRqFJFTHE7z2frvd0sAGSQz7etx76ihsLqeqk34

**Comment by Anthropos888** [comment] 2020-03-10 10:28
@JHerseth thanks for the deck. I tested it with the 18MB kanji strokeorder font and as expected it took around 1,5sec to load each card and each side on my phone (Nokia 6, Android 9, Canary 76). Then I tested it with my very old Samsung Galaxy S3 with Android 4.3, Chrome 35 and its own Webview - and each card is loading very quickly in around 0.3sec.

Sorry for using this thread, but may I ask which phone you are using? It seems that the lags described in this issue https://github.com/ankidroid/Anki-Android/issues/5213 might also be a matter of the Android manufacturer.

**Comment by JHerseth** [comment] 2020-03-10 13:27
@Anthropos888 Samsung S10 Plus

**Comment by mikehardy** [comment] 2020-03-14 12:34
@david-allison-1 if you're playing around with the WebView already, this one has a nasty user experience effect but (if the termination handler solves it) is actually an almost trivial fix...notes in comment above https://github.com/ankidroid/Anki-Android/issues/5780#issuecomment-596512163

**Comment by david-allison-1** [comment] 2020-03-14 12:52
@mikehardy I'll look into reproducing it

**Comment by david-allison-1** [comment] 2020-03-14 13:02
Reproduced. Added: `mCard.loadUrl("chrome://crash");` at the start of `displayCardAnswer()`.

**Comment by mikehardy** [comment] 2020-03-14 13:10
Fantastic - reproduction is always the first step. I think adding a termination handler will fix it but I must admit I was surprised that the reviews weren't correctly persisted (resulting in it appearing to be a new day for new reviews) after the crash. I think there are likely two things at play and termination handling will at least make it appear everything is fine, but the new reviews thing sure was odd. Thanks for looking at this, I should make a graph of the issue count going down + the PR rate :-)

**Comment by mikehardy** [comment] 2020-03-16 22:07
2.10alpha50 is out with this! available as soon as google play finishes processing and starts serving it up :rocket:

**Comment by david-allison-1** [comment] 2020-03-31 08:35
@mikehardy Requesting a reopen of this. I'm still occasionally getting a killed by the WebView if I trigger this immediately after app load.

Had a long debug session for this yesterday. It takes a long time to occur, but once it does, it happens with regularity.

I could only get it to crash on the first instance. After that, it seemed stable. 

```HEAD is now at 9c12b9aac Gracefully handle WebView Crashes```

Steps (repeat 2-6 until crash): 

1. Modify `displayCardAnswer()` to crash chrome
2. Open Android "Current App" screen and swipe Anki away to kill it
3. Open Anki
4. Open a deck with cards
5. Display Answer
6. Anki Crashes

```
2020-03-31 09:28:27.989 6955-6955/com.ichi2.anki A/chromium: [FATAL:crashpad_client_linux.cc(552)] Render process (7023)'s crash wasn't handled by all associated  webviews, triggering application crash.
2020-03-31 09:28:27.989 6955-6955/com.ichi2.anki A/libc: Fatal signal 5 (SIGTRAP), code -6 (SI_TKILL) in tid 6955 (com.ichi2.anki), pid 6955 (com.ichi2.anki)
```

**Comment by david-allison-1** [comment] 2020-03-31 10:47
No clue about the cause.

Fix: 

1. Open Anki
2. While on the deck screen, switch to Chrome
3. Press 'Back' in Chrome
4. See Log Line: `
2020-03-31 11:45:10.978 24674-24674/com.ichi2.anki E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (24741) crash detected (code -1).`
5. Back to Anki
6. Review as normal, crashes occur and are fixed by `onRenderProcessGone`
6. Review as usual

**Comment by mikehardy** [comment] 2020-03-31 13:12
🤷‍♂  truly bizarre.

**Comment by mikehardy** [comment] 2020-03-31 19:59
Closing this for now - it'll be where we leave this for the 2.9.x branch - @david-allison-1 apart from fixing the issues :trophy: in most all cases also opened #5883  to track a remnant issue

**Closed by mikehardy** 2020-03-31 19:59 UTC
Labels: 2.9.x, Bug, Priority-Medium, Rendering
