### ISSUE TITLE
[Bug] "Type Answer" box not appearing

### ISSUE THREAD

**Issue by Firewater21** [ankidroid/Anki-Android#15466] opened 2024-02-09 21:25 UTC
###### Reproduction Steps

1. N/A
2. N/A
3. N/A

###### Expected Result

There would be a type in box above show answer

###### Actual Result

There was none

###### Debug info
AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2102J20SG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; M2102J20SG Build/TKQ1.221013.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.164 Mobile Safari/537.36

ACRA UUID = 59dab852-30af-4114-8e82-bb304c5ede34

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))
https://github.com/ankidroid/Anki-Android/assets/149249012/8d77de68-31db-4476-b88d-5958a4d24a1e

**Comment by mikehardy** [comment] 2024-02-09 21:30
Hi there! Can you paste the card template code in here ? It is likely either the wrong card type (make sure it is the type answer type) or the card type doesn't have the correct stuff in the template --> https://docs.ankiweb.net/templates/fields.html?highlight=type%20answer#checking-your-answer

**Comment by Firewater21** [comment] 2024-02-09 22:02
> Hi there! Can you paste the card template code in here ? It is likely either the wrong card type (make sure it is the type answer type) or the card type doesn't have the correct stuff in the template --> https://docs.ankiweb.net/templates/fields.html?highlight=type%20answer#checking-your-answer

Hello! Thank you for the response

Front
{{cloze:Text}}
{{type:cloze:Text}}

Back
{{cloze:Text}}<br>
{{type:cloze:Text}}
{{Back Extra}}

I actually captured it on video
Here: https://github.com/ankidroid/Anki-Android/assets/149249012/e6eb5113-4b24-4e2b-99b3-90096a5debd7

And it does fix itself when I enter the edit portion and save

**Comment by david-allison** [comment] 2024-02-09 22:24
@Firewater21 Could you export, zip up a deck and post it here?

The video recording is great, but I can't reproduce this (I didn't modify `Cloze`, I made `Type-Cloze`, but that should have been enough to display the issue

**Comment by Firewater21** [comment] 2024-02-09 22:29
> @Firewater21 Could you export, zip up a deck and post it here?
> 
> The video recording is great, but I can't reproduce this (I didn't modify `Cloze`, I made `Type-Cloze`, but that should have been enough to display the issue

Sure!

![Intro to Psych-20240210062817.zip](https://github.com/ankidroid/Anki-Android/files/14226821/Intro.to.Psych-20240210062817.zip)

**Comment by david-allison** [comment] 2024-02-09 23:07
I still can't reproduce or see how this could happen

https://github.com/ankidroid/Anki-Android/blob/96d4604a03e76bc44ebbb103396af5dbdc4b4b35/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt#L1883-L1891

https://github.com/ankidroid/Anki-Android/blob/65c9f9197ef31e223e5ced4950c366883c94205b/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt#L72-L78

https://github.com/ankidroid/Anki-Android/blob/65c9f9197ef31e223e5ced4950c366883c94205b/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt#L84-L134

* tested invalid JS on the card

**Comment by david-allison** [comment] 2024-02-09 23:25
@Firewater21 The most useful thing that can be done to move this along would be to determine which beta/alpha introduced the issue.

Could you download `Parallel.B` from: https://github.com/ankidroid/Anki-Android/releases, import the deck you provided and determine the release which introduces the issue

**Comment by Firewater21** [comment] 2024-02-09 23:51
> @Firewater21 The most useful thing that can be done to move this along would be to determine which beta/alpha introduced the issue.
> 
> Could you download `Parallel.B` from: https://github.com/ankidroid/Anki-Android/releases, import the deck you provided and determine the release which introduces the issue
> 
> More information which you could provide (such as the frequency of the issue) would be useful

Yes, I tried doing the same reviews in B variant from 2.17beta2 and this issue wasn't in it.

I just actually encountered this issue today and it only happened twice to me in the v8a one. 

Additional info: I do make my cards in the PC version.

I'll try to record all of my review session to see if this happens again.

**Comment by david-allison** [comment] 2024-02-10 00:05
Thanks, do you have any apps which use the AnkiDroid API?

**Comment by Firewater21** [comment] 2024-02-10 00:09
> Thanks, do you have any apps which use the AnkiDroid API?

Nope.

**Comment by david-allison** [comment] 2024-02-10 00:11
Could you post debug information from the `B` variant, just to be sure nothing's changed

**Comment by Firewater21** [comment] 2024-02-10 00:14
> Could you post debug information from the `B` variant, just to be sure nothing's changed


AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2102J20SG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; M2102J20SG Build/TKQ1.221013.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.164 Mobile Safari/537.36

ACRA UUID = 1d7d1978-787b-4da1-82c9-1b53b6909dcc

Crash Reports Enabled = true

**Comment by david-allison** [comment] 2024-02-10 06:20
On us: check the above ACRA UUIDS

If we can't get reproduction steps within a couple of days, defer to 2.18

Final step:
* @Firewater21 After the bug occurs: `Help - Get Help - Send Troubleshooting report`, then let us know

If `Parallel.B` works: I'm thoroughly confused as the two apps should be equivalent. Very slight possibility of a note type caching/syncing issue.

**Comment by david-allison** [comment] 2024-02-10 06:46
Reproduced randomly on 2.17alpha16 with the provided deck

**Comment by Firewater21** [comment] 2024-02-10 07:04
> I believe I reproduced randomly on 2.17alpha16 with the provided deck

Oh nice!, Does something really triggers it? Or it just happens randomly?

**Comment by david-allison** [comment] 2024-02-10 15:23
I haven't been able to reproduce it again. If you find steps, it would be appreciated

**Comment by BrayanDSO** [comment] 2024-05-11 10:42
I'll close it as can't reproduce

**Closed by BrayanDSO** 2024-05-11 10:42 UTC
Labels: Bug, Needs Triage
