### ISSUE TITLE
[BUG]: Table tag

### ISSUE THREAD

**Issue by NoobSam777** [ankidroid/Anki-Android#17214] opened 2024-10-08 14:03 UTC
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Create a card
2. Add _table_ tag, and it, add some _td/tr_ tags
3. Review it

### Expected behaviour

It should be normal like on desktop

https://github.com/user-attachments/assets/51b97b54-b40f-4e47-aa45-67c6b84807cf

### Debug info

AnkiDroid Version = 2.19beta4 (11e1a6044124219994d1684cd725c4c9e6a69289)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 12 (SDK 32)

ProductFlavor = full

Manufacturer = Xiaomi

Model = Redmi Note 8

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; Redmi Note 8 Build/SKQ1.220714.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.27 Mobile Safari/537.36

ACRA UUID = e43df5bb-f3f3-4160-8965-d1cf3a258e99

FSRS Enabled = true

Crash Reports Enabled = true

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by NoobSam777** [comment] 2024-10-09 22:25
![Image](https://github.com/user-attachments/assets/dad4cc8e-653c-4475-b345-00cfa5ae0473)

That seems to be it. It creates several `<br>` tags

**Comment by david-allison** [comment] 2024-10-10 00:50
Thanks! Closing as a duplicate of https://github.com/ankidroid/Anki-Android/issues/3304

* https://github.com/ankidroid/Anki-Android/issues/3304

----

I think we all want a new unified Note Editor which will resolve this issue

**Closed by david-allison** 2024-10-10 00:50 UTC
Labels: Bug, Needs Triage
