### ISSUE TITLE
suggestions and bugs

### ISSUE THREAD

**Issue by lahootian313** [ankidroid/Anki-Android#4069] opened 2016-01-27 17:47 UTC
Hi

1. You know when decks are ample we need searching but the search's button isn't available in main page  I mean in very first versions of this app it was at top of the main page

2.unfortunately when I  search  I always have to change the field to all decks

Please make '' all decks '' as default 

3.most of the time after synchronization I'm sure that some of my media aren't synchronized but app notifies that synchronization is completed

4.and I have a problem with exporting decks
U know when I export them without media it works properly but with media it says importing failed
5.
When I check media it says there are 6 media in media folder that aren't used by any card while when I check my cards all media are played  properly  

So how can I solve this problem?

**Comment by eginhard** [comment] 2016-01-27 19:57
1. There's already a lot of actions in the main screen, so we can only add things there that are really necessary. I think it's not too much trouble to go to the browser first and most people probably don't need to search every time they use the app.
2. I find that quit irritating as well because it's usually not what I intended. What do others think about defaulting to "All decks" when coming from the deck picker.
3. The notification is only displayed when the sync (including media) is fully completed (but make sure you have "Fetch media on sync" enabled in Settings -> AnkiDroid).
4. Can you provide an example deck where the import fails?
5. It's exactly what is says - the media on your cards are fine, but there are some more media files that aren't used. You can delete them by running "Check media" in Anki Desktop.

PS: I'm closing this as it's not about any specific issue. You can continue the discussion in the [group](https://groups.google.com/forum/#!forum/anki-android), which is better suited for discussing several small questions.

**Closed by eginhard** 2016-01-27 19:57 UTC

**Comment by hssm** [comment] 2016-01-27 21:07
For 4, there is https://github.com/ankidroid/Anki-Android/issues/3636.

**Comment by lahootian313** [comment] 2016-01-28 09:30
Hi
Sir

As I told after synchronization there are some media that aren't synchronized and in later synchronization they will be synchronized I don't know why it can't do that 
Actually I have to go to check media and after that the app can recognize new media so after that it begins to synch

And u said delete them if I delete them I can't  listen to them so why did u say that?

It's clear after deleting the button of play is shown but there is no sound


Besides I'm learning English and there are lots of synonyms in this language so most of the time I live to have these synonyms in one place so I have to search and then combine them

That's why I told that search's button is more useful if it is in the main page as it used to be

**Comment by snowtimeglass** [comment] 2016-01-29 01:00
@lahootian313
>2.unfortunately when I search I always have to change the field to all decks
>Please make '' all decks '' as default
 
@eginhard
>I find that quit irritating as well because it's usually not what I intended. What do others think about defaulting to "All decks" when coming from the deck picker?

I agree with you. 
I use the browser frequently,
and then, I almost always have to change the field to "All decks" as well.
I feel it's inconvenient way, in contrast to that of Anki Desktop.

How about making "All decks" as default, and making the item, "Current deck", under the "All decks" like Anki Desktop?

**Comment by timrae** [comment] 2016-01-29 01:12
> How about making "All decks" as default, and making the item, "Current deck", under the "All decks" like Anki Desktop?

Currently it's supposed to remember your last choice, which is a feature I find pretty useful. It's not really working as intended though because the choice gets reset anytime you open the browser from a location other than the DeckPicker. This should be easy to fix so let's try that first and see how it goes before removing the feature entirely.

**Comment by snowtimeglass** [comment] 2016-01-29 03:14
It's a good idea.
It will practically enable users to set a default deck of the browser. 
For example, if an user always select "All decks" on the browser, it will be a default setting of the browser.
