### ISSUE TITLE
[Bug] cards are blank when I review them on my android phone

### ISSUE THREAD

**Issue by KarishmaDixit** [ankidroid/Anki-Android#8967] opened 2021-05-26 18:24 UTC
###### Reproduction Steps

1. review cards on my android phone (pixel 5)
2. 
3.

###### Expected Result

Cards display like normal

###### Actual Result

Cards are showing as blank:
![image](https://user-images.githubusercontent.com/17726476/119711032-f44bb800-be56-11eb-9d85-849d67514e6a.png)

But cards display like normal when I review them on my PC.

Extra info which may be helpful: 
1. some of my cards have LaTex on them
2. some of my cards use the "image occlusion enhanced for Anki 21 alpha" plugin

###### Debug info

AnkiDroid Version = 2.15.1

Android Version = 11

Manufacturer = Google

Model = Pixel 5

Hardware = redfin

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 5 Build/RQ1A.210205.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = d41352ad-fd5d-4e81-a11f-1f3048fe9c9d

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2021-05-26 18:31
Hello! I believe this will be a duplicate of #8944 and will be fixed by #8965  as soon as I get it working well
Can you confirm whether or not your templates have conditionals with spaces in between the conditional start and the conditional name? That would help me have confidence this really was duplicate

**Comment by KarishmaDixit** [comment] 2021-05-26 19:06
Hello! Thanks very much for the help. All my cards have the following template, which I think I edited a while ago to hack in MathJax support:

![image](https://user-images.githubusercontent.com/17726476/119716829-7808a300-be5d-11eb-8f34-9c2be59f3cf0.png)

**Comment by mikehardy** [comment] 2021-05-26 19:23
Well....that's not a duplicate :-), that's different. Thanks for the details on the template. I don't see why this would not be working except I also don't think you'll need to hack in Mathjax support - we not only support Mathjax we have a current version (I think) in form of Mathjax 3 - embedded in the app so it will work offline even

I wonder if you removed all the mathjax stuff if it would work? Also note that our card template editor has gotten a lot better so it is not quite as painful to try doing this in the app itself. Do be careful and make sure you have a valid backup / sync with ankiweb first, I would hate for you to mess up your template while trying things that should fix it instead

**Comment by mikehardy** [comment] 2021-05-26 19:32
I will be that 2.15.0 works for you, you may install a parallel build to check really quickly:
https://github.com/ankidroid/Anki-Android/releases/tag/v2.15.0

And I think #8946 (which just went in for 2.15.1) is causing things to be blank - with mathjax just not loading at all somehow. I could be wrong, but the parallel build test is pretty easy

I continue to think you can remove all the mathjax stuff and just use mathjax in the supported / built-in way though? 

https://docs.ankidroid.org/manual.html#mathjax (note "Previous workarounds are no longer necessary...")

**Comment by KarishmaDixit** [comment] 2021-05-26 23:36
Hi, thanks for the advice, I tried removing the mathjax stuff, and it now works!

**Comment by mikehardy** [comment] 2021-05-27 14:16
Excellent! Thanks for reporting back, and I'm really glad it's all working for you now. Should actually be faster *and* work offline as well (previously the workaround only worked by pulling Mathjax in over the network...)

**Closed by mikehardy** 2021-05-27 14:16 UTC
Labels: Waiting For Feedback
