### ISSUE TITLE
Collection not opened - custom study

### ISSUE THREAD

**Issue by MuhamHS** [ankidroid/Anki-Android#5708] opened 2020-01-10 13:28 UTC
I can't use custom study. Every time I open the deck and click on a card (to see the answer) I get the following message:

"Collection not opened - An error occurred, while accessing your collection. It may have been caused by a harmless bug, or there might be a problem with it.

Try running check database, or restoring from backup by pressing "options" button. If you continue to see this message, please file a bug report."

I did the abovementioned steps, but it didn't help. What else can I try to be able to enter custom study again?

My bug report is this:

AnkiDroid Version = 2.9.1

Android Version = 8.0.0

ACRA UUID = 5d6e2fc5-d664-46b2-b69f-cbb0be3fa9e8

###### Reproduction Steps

1. Running check data base
2. Restoring all decks from backup
3. Deleting custom study deck and tried again

###### Expected Result

I hoped to be able to access custom study.

###### Actual Result

I receive the following message: 
"Collection not opened - An error occurred, while accessing your collection. It may have been caused by a harmless bug, or there might be a problem with it..."

###### Debug info

AnkiDroid Version = 2.9.1

Android Version = 8.0.0

ACRA UUID = 5d6e2fc5-d664-46b2-b69f-cbb0be3fa9e8

###### Research
*Enter an [ x ] character to confirm the points below:*

x

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2020-01-10 14:28
Hi @MuhamHS ! Can you move to the latest alphas? There have been quite a few fixes and I think this may have been one of them. Until we know you're testing on the latest code we might be duplicating effort with scarce volunteer resources https://docs.ankidroid.org/manual.html#betaTesting

**Comment by MuhamHS** [comment] 2020-01-10 14:33
Thank you for your response. 
I don't understand what you mean though.. What is an alpha?

**Comment by mikehardy** [comment] 2020-01-10 14:49
I'm sorry MuhamHS I can't provide support at that level - the link contains the necessary information and I am confident google will define the necessary terms from the link if you aren't aware of them yet

**Comment by MuhamHS** [comment] 2020-01-10 15:20
Unfortunately I couldn't find any information considering my problem on that link. And I did try to google my problem, before registering on this website, but couldn't find any solution. English is my third language and most resources on Anki are English, that makes it a little harder to understand for me.

Thank you anyway. I appreciate every effort to helping me. 

If anyone had the same problem and knows what to do, please let me know.

**Comment by mikehardy** [comment] 2020-01-10 15:40
I do understand language issues, I'm living in a country now where english (my mother tongue) is essentially not spoken.

Stable: the main release version (2.9.1 right now)
beta: testing version that should be stable, (2.9.2beta5 now I think?)
alpha: a version that has the very latest bugfixes. It should be stable but the newest features might still have problems (2.10alphaXX - I think like 40 right now I forget)

So the alpha has all the latest bugfixes. If you sign up for betas in the google play app for AnkiDroid, then join the google group we link to in the link I provided above, then check for updates in the google play app on the beta tab, you should see an AnkiDroid alpha available. You should install that and retest

**Comment by MuhamHS** [comment] 2020-01-10 17:29
Thank you for your understanding and for explaining it more in detailed. 

I did follow all the steps now.
1. I have the beta version now (last update 4.1.2020) 
2. I entered the google alpha group on your link. 
3. I looked for updates in google play, but there aren't any (exept for the update to beta, which I did). 
I also could't find Alpha Ankidroid, even though I entered the google alpha group.

The App is called now "Ankidroid (Beta)", but when I check the app-info, it says "2.10alpha30" (maybe that's Alpha Ankidroid nevertheless?)

But even in updated version the problem still occures. 

I also send a bug report, but I did that several times before and nothing happened.

Am I out of options?

**Comment by mikehardy** [comment] 2020-01-10 20:04
If it says 2.10alpha30 then you are on the latest alpha, great

I'm sorry it is still happening. Using the UUID you posted I was able to find the bug report in our crash database:

```
java.lang.RuntimeException: org.json.JSONException: No value for resched
at com.ichi2.libanki.Sched._lapseConf(Sched.java:14)
at com.ichi2.libanki.Sched._lrnConf(Sched.java:2)
at com.ichi2.libanki.Sched.answerButtons(Sched.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.showEaseButtons(AbstractFlashcardViewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardAnswer(AbstractFlashcardViewer.java:20)
at com.ichi2.anki.AbstractFlashcardViewer$4.onClick(AbstractFlashcardViewer.java:5)
at android.view.View.performClick(View.java:6897)
at android.view.View$PerformClick.run(View.java:26104)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: org.json.JSONException: No value for resched
at org.json.JSONObject.get(JSONObject.java:392)
at org.json.JSONObject.getBoolean(JSONObject.java:413)
at com.ichi2.libanki.Sched._lapseConf(Sched.java:13)
... 14 more
```

it looks like somehow your collection has empty values for things that should not be empty.

Is it possible for you to rebuild that custom study deck? The value that is unexpectedly empty seems like it has to do with the learning intervals, which I think are stored in the deck or the deck options group

**Comment by MuhamHS** [comment] 2020-01-10 20:33
I deleted the study deck several times and started new, but unfortunately the problem has not solved.

I did have empty decks though (I wanted to add the cards later). Maybe thats where the problem started? Because I had decks, that have no cards? I now deleted all the empty decks. But the problem is still occurring. 

I worry that I may have to delete all my cards and start from zero (I don't use premade decks, I made every card myself from novels and textbooks).

**Comment by mikehardy** [comment] 2020-01-10 20:38
You might try long-pressing on the deck with the problem, and going into the options there to see if you can (it might crash right there) and if you can, change the intervals? Also, if you could export your collection (it would be a .colpkg file, which is really just a fancy .zip file) and put it on google drive or similar I might be able to investigate what happened. If you can't (because of sensitive information or whatever) I understand, but that might be the only way to truly pinpoint the problem.

**Comment by MuhamHS** [comment] 2020-01-10 20:59
Long-pressing the deck I got into the options, and changed the option for the interval. The app didn't crash, but the original problem is still there. 

I will gladly try to export my collection and put it on google drive, if you can investigate the problem this way. But I will have to figure out first what that all means and how to do and then I will get back to you. 

For now thank you for your time. Talk to you later !

**Comment by MuhamHS** [comment] 2020-01-12 19:33
Hi there. 
I wasn't successful exporting my decks. Whenever I want to export my collection, I receive a message, that is not UTF-8 format. I don't know what that is, but many resources say if this problem occurres, I have to use libre office to change the format. I have downloaded libre office now, but this is where I am stuck. The next steps explained don't match what's happening with my files or I understand something wrong.. What can I do?

Or is it possible to investigate my problem, if I give you access to my ankiweb?

**Comment by mikehardy** [comment] 2020-01-12 21:59
Hmm that's unexpected. Nothing about the export process should involve LibreOffice (though I personally use LibreOffice and I like it, it is just unrelated to Anki).

I'm just looking for the file that results from this: https://docs.ankidroid.org/#_exporting_collection_package

**Comment by MuhamHS** [comment] 2020-01-12 22:33
One of the resources considering the UFT-8 problem and libre office was this (second last answer): https://bit.ly/2taBwNb

But never mind, if we have another way now. I have the file on my desktop following the steps from your link. I hope it's the right format now. 

Is this what you mean by google drive? > https://drive.google.com/drive/u/0/recent
Can you see my deck?

**Comment by MuhamHS** [comment] 2020-01-12 22:45
What I have noticed though. The custom study deck is not visible when I open this file on my computer :/ Where did it go? That's the deck, that is broken

**Comment by MuhamHS** [comment] 2020-01-27 00:12
Hello community,
I still can't use custom study deck :/ Did any other user have this problem and knows how to solve?

**Comment by mikehardy** [comment] 2020-02-10 18:44
I've done everything I can think of there. Your custom study deck is broken, no idea why or how that can even happen but definitely broken

I'm leaving that issue open because it's the kind of database corruption we might be able to fix as part of "check database" but to me it looks like creating a different sort of custom study deck would be the solution

You mention you have tried re-creating the custom study deck. Perhaps the way you are creating it is leading to a bug? Are you able to create any type of custom study deck (maybe one with different rules would work?) Are you able to create a custom study deck on AnkiDesktop?

**Comment by MuhamHS** [comment] 2020-02-10 19:55
Hello MikeHardy. Thank you for coming back to this issue.

You wrote: "(..)to me it looks like creating a different sort of custom study deck would be the solution"
> The translation for custom study deck is "Benutzerdefinierte Sitzung". Right know I am not sure if "custom study deck" is the correct translation, as you ask me to make a new one (which I can do whithin seconds). I try to explain it differently, to make sure I used the right term: 

The deck I am talking about is normally empty.
Usually I study the decks/cards, that Anki "wants" me to study. But sometimes I want to study a very specific deck, because I am repeating a old lesson. But the Anki App doesn't "want" me to study this deck (don't know how to explain better), because it's not the time for these cards. 
When I click on this specific deck I want to study, it says "no cards" on the left > meaning I finished studying this deck. On the right it says "Benutzerdefiniertes Lernen" (the translation I found was "custom study", but you may have a different term for this). When I click "Benutzerdefiniertes Lernen" then I have six options, one of them being "studying in advance" - Then I take this option and enter I want to study 333 days in advance (because I want to make sure I study the whole deck).
That's when the deck "Benutzerdefinierte Sitzung" (custom study?) is filled with cards. (> The cards are usually from another deck and don't "belong" to the "Benutzerdefinierte Sitzung"-deck)
After I finished studying these cards, this deck is empty again, until I fill it with another deck I want to study in advance.

Sorry for this long explanation, I just want to make sure, we are talking about the same deck.


Now to answer your questions: 

"You mention you have tried re-creating the custom study deck. Perhaps the way you are creating it is leading to a bug?"
> I always used the same method to create this deck. The way I explaind above (by clicking "studying in advance" and entering "333" days in advance). The way I created this deck was never a problem before.

"Are you able to create any type of custom study deck (maybe one with different rules would work?)"
> I did experiment with the rules. Even though I wasn't sure how this could help, I did change a few things (like the Intervals for example)

"Are you able to create a custom study deck on AnkiDesktop?"
> Yes. I have downloaded Anki on my computer to try to study there instead of my smartphone (and also on my Ipad, but online).
The first card appears, but the moment I click (to see the answer), I receive the same message about a problem with this deck. Whether I study on my phone (Samsung), on my desktop (Windows) or online (on my Ipad or other devices), I receive the same message everywhere. 
I even deleted Anki and then created all the decks from an older backup. 
The thing is: The other decks work fine. It's just a very limited learning, as it doesn't fit my learning schedule (when I prepare for a specific lesson or novel) and it's not useful that way.

Thank you for leaving this issue open. 

I really hope my problem can be fixed with the next "check database", as you say it. But I wonder how long it will take, like months or years? Am I better off buying a new sellphone and building all decks from zero? (I am not rich or something, I just think this tool is that great and helpful) But then again, how are the chances that the problem appears again in the new sellphone? 
What would you do? 

Thanks for reading this. If you don't find the time to respond, it's ok, you already said, you have done everything you can, and for that, thank you for your time. 
Maybe someone else reads this and knows how to solve or has any suggestions, in that case, it's good the issue is staying open.

Good evening to everyone.

**Comment by mikehardy** [comment] 2020-02-10 20:28
I don't think we are having a language / translation issue. Your English seems excellent and I believe we're talking about the same thing. I want to focus on this though:

>  Then I take this option and enter I want to study 333 days in advance (because I want to make sure I study the whole deck).

This is the first time you have specified exactly how you are creating the custom study deck, it's very useful to know.

What if you said only 1 day in advance? 10 days? 100 days? I am curious if it is because it is so far in advance or something similar

**Comment by MuhamHS** [comment] 2020-02-10 21:14
(Haha ok thanks, I worried because computer stuff is already hard to express/understand in my native tongue, so I wanted to be very clear. Sorry for the long explanation, then :)

Let's take for example the deck „A Little Life“ with 345 cards.
Right now it shows „0 0 0“, because I finished studying this deck.

If I use „study in advance“ and choose only „1 day in advance“, it says „congratulations, you are finished for today.“, and I don't get to study this deck. Same for 10 days, 50 days, 100 days, 150 days.. (I tried them out)

Until I choose 200 days in advance, then it says, I have to study 3 cards.
If I choose 250 days, it says, I have to study 5 cards.
If I choose 300 days, it says, I have to study 19 cards.
If I choose 333 days, it says, I have to study 52 cards.

And so on.. Now for this specific deck, the „333 days in advance“ doesn't work to study the whole deck. I have to choose „555 days in advance“, in order to study the whole deck.

No matter which option I take (250 days or 300 days..), the moment the first card appears and I click to see the answer, I receive the message „Sammlung nicht geöffnet“ („collection not opened“) and that something is wrong with the deck or there might be a bug etc..

**Comment by mikehardy** [comment] 2020-02-10 21:26
Now we are on to something. I can try to reproduce that. Your deck link above to google drive was not an actual shareable link to your collection. If you could export your collection you can actually attach it here as long as you change the extension from 'colpkg' to 'zip'

**Comment by MuhamHS** [comment] 2020-02-10 21:59
Would it also work, if I give you access to my ankiweb (email and password)?
Or do you need it explicitly the way you described?

**Comment by MuhamHS** [comment] 2020-02-10 22:14
Would it also work, if I give you access to my ankiweb (email and password)?

Or do you need it explicitly the way you described? (If so, I will find out how to do this and get back to you tomorrow. It's getting too late here for me to focus)

**Comment by mikehardy** [comment] 2020-02-10 22:44
I definitely do not want any access credentials, just sharing the exported collection is the way

**Comment by MuhamHS** [comment] 2020-02-11 15:24
Ok noted ! I will do that and come back

**Comment by mikehardy** [comment] 2020-02-12 15:13
I'm not sure what exactly is going wrong but in CustomStudyDialog in our code, there is a line that is supposed to put the 'resched' value into the dynamic deck, where it will be correctly referenced later. That does not seem to be working for some reason, and I it could be days or weeks before I have time to get to the bottom of it, but this is the line that is confusing to me - if this works, the crash shouldn't happen (but the crash is happening, so :thinking: ) https://github.com/ankidroid/Anki-Android/blob/014e6951988d37b7166bc63edca8c4e91ed34771/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java#L470

**Comment by mikehardy** [comment] 2020-03-02 17:13
#5757 was an improvement but actually fixed #5758 I think. This one remains a problem.

**Comment by david-allison-1** [comment] 2020-03-14 18:42
Hi @MuhamHS, I'd like to try solving this, if you're still here. 

Could you let me know when you get this message?

Thanks

**Comment by MuhamHS** [comment] 2020-03-14 19:48
Hi @david-allison-1 

Yes I am here :D

**Comment by david-allison-1** [comment] 2020-03-14 20:21
Wonderful!

I have a few ideas about the problem, but to fix it, I'd like to see your Anki collection.

The collection is a file ending in either: `.akpkg`, `.anki2`, or `.colpkg`.

Could you follow these steps to provide the file.

Please let me know if the translations don't match and you don't know what to do, or if my instructions don't make sense.

I believe that you previously uploaded a file to Google Drive. If you did this, could you start at Step 6.

----

1. Could you open the main screen of AnkiDroid (Deck Browser).
2. Could you open the options on the top right and select the bottom option: (`Export Collection`/`Sammlung exportieren`).
3. Untick both options. I do not need media, or scheduling information.
4. Wait a while
5. Share to Google Drive
6. Find the file in Google Drive: https://drive.google.com/drive/u/0/my-drive
7. Right click the file, and select "Get Shareable Link"
8. Reply with the link

----

Feel free to disable the link after I let you know I've downloaded it. You can do this by selecting "Share" on the file.

**Comment by MuhamHS** [comment] 2020-03-14 21:57
Hello David, 
Thanks for your support! Since it is already late here in Germany, I will do that tomorrow :)
(However, I believe MikeHardy reproduced the deck from scratch)

I will come back tomorrow afternoon. Until then have a nice night ! :D

**Comment by MuhamHS** [comment] 2020-03-15 19:38
I am back :D

**Comment by MuhamHS** [comment] 2020-03-15 19:42
The file was gone, I had to reproduce. But I hope it works now

**Comment by MuhamHS** [comment] 2020-03-15 19:42
https://drive.google.com/open?id=1xSBw50Xx9miEekyXkeDswrATJ1dnm_96

**Comment by MuhamHS** [comment] 2020-03-15 19:45
Does it work ?

**Comment by david-allison-1** [comment] 2020-03-15 19:57
@MuhamHS Just got back. Works, thanks! Feel free to unshare

**Comment by david-allison-1** [comment] 2020-03-15 20:06
Awesome, thanks! @MuhamHS 

Can you confirm:
* The issue listed in the thread is still a problem

**Comment by MuhamHS** [comment] 2020-03-15 20:06
Yes it is still a problem.

**Comment by david-allison-1** [comment] 2020-03-16 01:30
Cause: Invalid Dynamic Deck Definition:

Snipped JSON for the dynamic custom study deck.
```json
"1540823220108": {
        "dyn": 1,
        "conf": 1
    }
```
`conf` defines the deck with the options group to use.

Per [Database Structure](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure) `conf: "id of option group from dconf in `col` table. Or absent if the deck is dynamic. `

Some code uses has(`conf`) to check whether it's dynamic, others use `dyn==1`. We fail as we return settings for conf (Default) where a dynamic deck is expected.

Specific error: 

https://github.com/ankidroid/Anki-Android/blob/623f51a7a697f5b4c67b6f7de44f4d23fcd2bcde/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java#L654-L668

**Comment by david-allison-1** [comment] 2020-03-16 10:44
Hi @MuhamHS,

Just to keep you in the loop: a fix has been written, I've tested it personally and it's going through our review process.

We'll make our best efforts to notify you when it goes into the AnkiDroid beta.

It requires that you run "Check Database" after you upgrade to fix the custom study deck.

All the best,
David

**Comment by MuhamHS** [comment] 2020-03-16 16:30
Ok got it! Thanks a lot :D

**Comment by david-allison-1** [comment] 2020-03-18 19:58
Notified downstream of issue: https://anki.tenderapp.com/discussions/ankidesktop/39763-bug-report-filtered-deck-corruption?unresolve=true

I'd rather not fix this first and get libAnki out of sync with downstream.

**Closed** 2020-03-18 20:37 UTC
Labels: 2.9.x, Accepted, Needs Triage, Reproduced

**Comment by david-allison-1** [comment] 2020-03-19 20:06
Root cause: #5253
