### ISSUE TITLE
[Crowdin]: Unnecessary space characters 🟨 

### ISSUE THREAD

**Issue by NameLessGO** [ankidroid/Anki-Android#15582] opened 2024-02-19 04:18 UTC
###### Reproduction Steps
https://crowdin.com/project/ankidroid -> pt-BR -> Translated all

###### Expected Result
🚫 🟨 

###### Actual Result
🟨 !!!

###### Debug info
Brave browser: Versão 1.65.6 Chromium: 122.0.6261.43 (Versão oficial) nightly (arm64)

![image](https://github.com/ankidroid/Anki-Android/assets/66227691/c893dcef-5f4b-4775-b725-6faaf2602160)

Strings affected
- Voice should be installed before use
- Tap a voice to listen
- Use anyway
- Internet
- Install
- Failed to open text to speech settings
- Android backup in progress. Please try again
...

**Comment by david-allison** [comment] 2024-02-19 04:27
Added in: e854c9a599bef00d45a27255011b6ddad3d7220c
* https://github.com/ankidroid/Anki-Android/pull/14628

Discussion: https://github.com/ankidroid/Anki-Android/pull/14628#discussion_r1419858389 -> https://github.com/ankidroid/Anki-Android/issues/14903

Sorry for asking about the writeup, closing as a duplicate of https://github.com/ankidroid/Anki-Android/issues/14903

* https://github.com/ankidroid/Anki-Android/issues/14903

**Closed by david-allison** 2024-02-19 04:27 UTC
