### ISSUE TITLE
Number of cards due across all decks and a time estimate

### ISSUE THREAD

**Issue by Xenonicus** [ankidroid/Anki-Android#15696] opened 2024-02-27 17:26 UTC
In the previous version of AnkiDroid, the top left of the main menu would list the number of cards due across all decks and give a time estimate, e.g. "877 cards due (122 min)". In the new release it only lists the number of cards due, without the estimated time. Is there a way to get it to display the estimated time again?

**Comment by david-allison** [comment] 2024-02-27 18:28
Thanks!

* Duplicate of https://github.com/ankidroid/Anki-Android/issues/15688, please give it a 👍

**Closed** 2024-02-27 18:29 UTC
Labels: Duplicate
