### ISSUE TITLE
Support for Retaining JavaScript Global Variables Between Card Front and Back in AnkiDroid

### ISSUE THREAD

**Issue by tategotoazarasi** [ankidroid/Anki-Android#14326] opened 2023-08-28 06:43 UTC
**Is your feature request related to a problem? Please describe.**
I've developed a card template for Anki that uses JavaScript to randomize the order of choice questions on the front side. To ensure the back side reflects the same randomized order, I use the `window` object to store global data between the front and back of the card. This approach works seamlessly on Anki desktop and AnkiWeb. However, I've found that AnkiDroid does not support this feature, leading to inconsistencies when reviewing cards on the mobile platform.

**Describe the solution you'd like**
I would like AnkiDroid to support the ability to retain JavaScript global variables (specifically those attached to the `window` object) between the front and back of a card, similar to how Anki desktop and AnkiWeb operate. This would ensure that the randomized order of choice questions remains consistent across both sides of the card on all platforms.

**Describe alternatives you've considered**
One alternative would be to redesign my card templates to avoid relying on global JavaScript variables. However, given the need to maintain a consistent randomized order between the front and back, this approach might not provide the same level of flexibility and functionality. It would be more efficient and user-friendly if AnkiDroid could support the same JavaScript features as the other platforms.

**Additional context**
Here's a brief overview of my card setup:

- **Front:**
  - I initialize a global variable (`selectionGlobalData`) on the `window` object if it doesn't exist.
  - I store the content of the card's front side and any selected options in this global variable.

```html
<script type="text/javascript">
    if (!window.selectionGlobalData) {
        window.selectionGlobalData = {
            front          : "",
            selectedOptions: [],
        };
    }
    var selectionGlobalData = window.selectionGlobalData;
</script>

<div id="frontContent">
    <!-- ... -->
</div>
<script type="text/javascript">
    //...
    selectionGlobalData.front           = $("#frontContent").html();
    selectionGlobalData.selectedOptions = ""
    $("input:checked").each(function (element, index, array) {
        selectionGlobalData.selectedOptions += element.attr("id");
    });
</script>
```

- **Back:**
  - I retrieve the stored front content from the global variable and display it on the back side of the card.

```html
<div id="frontSide">
    <!-- Front content will be inserted here -->
</div>

<hr id=answer>

<div id="remark">{{Remark}}</div>
<script type="text/javascript">
    (function () {
        $("#frontSide").html(selectionGlobalData.front);
        //...
    })();
</script>
```

This setup allows me to maintain consistency between the front and back of the card, ensuring a synchronized study experience. Supporting this feature in AnkiDroid would be beneficial for advanced users who rely on JavaScript for custom card behaviors.

**Comment by david-allison** [comment] 2023-08-28 07:02
Thanks for the detailed report!

Closing as a duplicate of #2868

It's in the backlog of reviewer work

**Closed** 2023-08-28 07:03 UTC
Labels: Duplicate
