### ISSUE TITLE
Editing a note turns insignificant HTML newlines to br tags

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15365] opened 2024-01-30 19:13 UTC
#### Example:

Desktop:
<img width="235" src="https://github.com/ankidroid/Anki-Android/assets/92206575/fd8fdb1e-d138-44c9-a97d-6bde0fc6300c">

AnkiDroid: (displays incorrectly)
<img width="235" src="https://github.com/ankidroid/Anki-Android/assets/92206575/8f3e5e80-8058-4721-a54f-b36035c0c9ce">

After syncing to Desktop without making any edit to the note on AnkiDroid, no change happens in the HTML.

But after making a small edit
<img width="235" src="https://github.com/ankidroid/Anki-Android/assets/92206575/0df0f93c-d9eb-4025-a684-432c39337552">

The linebreak in the HTML gets replaced by a &lt;br&gt; tag.
<img width="182" alt="image" src="https://github.com/ankidroid/Anki-Android/assets/92206575/5a961bbe-e989-4028-a62a-1c454394579d">

Turning off the option added in https://github.com/ankidroid/Anki-Android/pull/7692 solves the issue in the sense that the HTML is no longer altered after editing the card in AnkiDroid. However, the card still displays incorrectly on AnkiDroid (same as the second image above).

Also, this is a suboptimal solution because it takes the note editor one step away from a WYSIWYG editor (because all the &lt;br&gt; tags become visible).

Also, I think that the title of the preference is misleading. I think that it should be "Replace HTML with newlines" because it replaces &lt;br&gt; tags with newlines when enabled.

_Originally posted by @user1823 in https://github.com/ankidroid/Anki-Android/issues/3304#issuecomment-1913483423_

Debug Info:
```
AnkiDroid 2.17 alpha 17
```

**Comment by david-allison** [comment] 2024-02-10 03:26
Let's move this back to #3304, thanks!

Duplicate of #3304

**Closed by david-allison** 2024-02-10 03:26 UTC
