### ISSUE TITLE
AnkiDroid doesn't show LaTeX svg images

### ISSUE THREAD

**Issue by ImCruel** [ankidroid/Anki-Android#5332] opened 2019-06-18 06:21 UTC
###### Reproduction Steps

1. 
Create a LaTeX card in Anki (while avoiding common boogie traps, like putting the latex delimiter `latex` in the card template.
2. 
Set LaTeX rendering to svg (in Anki)
3. 
Sync Anki

###### Expected Result

The LaTeX equation shows up in AnkiDroid

###### Actual Result

While the equation shows up in AnkiWeb and other svg images (written in html) show up on AnkiDroid, instead of the equation there is a '?' sign.

I can open the svg files synced to my Android device with svg viewers.

This is how the card looks on my phone:

![WhatsApp Image 2019-06-18 at 08 19 11](https://user-images.githubusercontent.com/39959991/59657734-e50b5c80-91a1-11e9-9d99-77530aa820d3.jpeg)

###### Debug info

https://ankidroid.org/docs/help.html

###### Research

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2019-06-18 07:14
Hmm - if I recall correctly you have to view the card correctly on Anki Desktop to render it into your media collection, then sync that down for it to render on AnkiDroid? But I could be off.

I'm mostly replying to say that AnkiDroid just got Mathjax support to match Anki Desktop and the rest of the ecosystem. So if you're looking at equations, maybe switching to mathjax is possible? They are available in the alphas (which are about to beta - they're plenty stable) - https://github.com/ankidroid/Anki-Android/wiki/Installation#beta--alpha-releases

**Comment by timrae** [comment] 2019-06-18 07:31
See the Anki Desktop manual for how to use LaTeX:
https://apps.ankiweb.net/docs/manual.html#latex-on-web/mobile

or, just switch to Mathjax to save yourself the headache

**Comment by ImCruel** [comment] 2019-06-18 19:33
> 
> 
> See the Anki Desktop manual for how to use LaTeX correctly:
> https://apps.ankiweb.net/docs/manual.html#latex-on-web/mobile
> 
> or, just switch to Mathjax to save yourself the headache

I read the Anki Desktop manuals section on LaTeX on mobile, but it doesn't help me. 
The images show on AnkiWeb, but not on AnkiDroid.
This issue shouldn't be closed yet, because the problem still persists.

**Comment by timrae** [comment] 2019-06-18 20:19
Do the images show up when you review on AnkiWeb in Google Chrome *on your Android device*?

**Comment by ImCruel** [comment] 2019-06-19 08:26
Yes, they do show up on AnkiWeb when reviewing on my Android device.

However, this is quite impractical because I have to be online to do so.

**Comment by timrae** [comment] 2019-06-19 12:18
Hmm that's pretty unexpected. What version of Android are you using? Usually (at least on Android 4.4+), if it works in Chrome then it should work in AnkiDroid as well. Do you have any special characters in the filename or something slightly abnormal?

I would recommend you just switch over to using mathjax, rather than investing a lot of time into debugging this to be honest.

**Comment by timrae** [comment] 2019-06-20 00:00
Can you please upload a small test deck apkg that we can use to reproduce the issue?

**Comment by ImCruel** [comment] 2019-06-20 06:03
My phone is running on Android 7.0.

I created a test deck (which is zipped, because GitHub doesn't allow apkg files):

[Anki_LaTeX_error.zip](https://github.com/ankidroid/Anki-Android/files/3308981/Anki_LaTeX_error.zip)

**Comment by Eido95** [comment] 2019-07-15 09:06
This issue also appears to me.

> Do the images show up when you review on AnkiWeb in Google Chrome _on your Android device_?

Yes, for both PNG and SVG images.

When I remove the V from "Create scalable images with dvisvgm" under LaTeX tab (which falls back to create images with `dvipng`), AnkiDroid shows LaTeX PNG images fine.

Following @timrae recommendation, I've setup MathJax support according to wiki [Enabling MathJax rendering in AnkiDroid](https://github.com/ankidroid/Anki-Android/wiki/Anki-desktop-compatibility#enabling-mathjax-rendering-in-ankidroid) section.
After this setup, AnkiWeb (both mobile and desktop), Anki desktop and AnkiDroid display successfully SVG images of mathematical equations.

This solution seems to work fine, but it feels too manual instead of support SVG display of LaTeX.

**Comment by timrae** [comment] 2019-07-15 10:14
That mathjax workaround from the wiki is no longer needed in the latest alpha versions, it should just work. Going forwards, mathjax will most likely be the only way that we support LaTeX equations

**Comment by milyukhin** [comment] 2019-07-15 13:24
I tested the attached deck and it worked fine:
![Anki-screenshot](https://user-images.githubusercontent.com/6668375/61219202-d3e54980-a767-11e9-99af-89b80accfd69.png)

Although, I was able to reproduce on my phone (anki 2.8.4) before I upgraded it to 2.9alpha80, where the issued disappeared.
I'm not sure what exactly fixed this, but it seems this has been fixed in the latest pre-releases.

**Comment by timrae** [comment] 2019-07-16 02:42
Thank you, it's possible svg support is v2.9  only, I don't remember exactly when it was merged

**Closed by timrae** 2019-07-16 02:42 UTC

**Comment by Eido95** [comment] 2019-07-16 08:41
I see that you added `MathJax.js` library under your project assets - so it will work offline :)

Additionally, I recommend you to include library version in file name in case that you don't automatically manage its versions.

After this discussion, in the context of Anki database storage - I think it is essential for all Anki projects to work with MathJax, instead of LaTeX, because the former storage short text, while the latter stores concrete image files.

**Comment by adamwolf** [comment] 2019-07-16 11:44
Does desktop Anki do it differently than how we did it here?  We pulled in
exactly the same version of Mathjax that desktop Anki uses, and pulled it
in the same way, as far as I can tell.

**Comment by ImCruel** [comment] 2019-07-18 06:42
Following a suggestion from timrae, I switched my cards to MathJax. They work fine now, although it was a hassle to port them all.

Thank you all for your help!
