### ISSUE TITLE
Enhancement request - Auto-next marks as 'good'.

### ISSUE THREAD

**Issue by Emailnickjohn** [ankidroid/Anki-Android#4720] opened 2017-10-31 22:43 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

Currently, when I set 'auto next card' or 'timer' to e.g. 10 seconds, after 10 seconds it moves onto the next card but it marks the card which I didn't respond to as 'again'. Not sure if this is intended. But please add the option to have it mark as 'good'. As most of the time I get cards correct within that 10 seconds, and would like to reduce the necessary interaction with the app as much as possible when using audiocards.

**Comment by timrae** [comment] 2017-12-11 06:18
Duplicate of #2609

**Closed by timrae** 2017-12-11 06:18 UTC
