### ISSUE TITLE
[BUG]:  自定义学习，比如 "复习忘记的卡片" ，    不支持  自动展示答案   功能

### ISSUE THREAD

**Issue by snnhqm** [ankidroid/Anki-Android#15829] opened 2024-03-10 01:50 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

WINDOWS版ANKI学习页面的   “更多”  菜单中，有 “自动展示” 菜单项， 可以启动   自动展示答案   功能

### Expected behaviour

手机版学习页面的  “更多菜单   ⋮   ” ，     有 “自动展示” 菜单项 ，   可以启动   自动展示答案   功能

### Actual behaviour

手机版学习页面的   “更多菜单   ⋮   ”   ，     缺少 “自动展示” 菜单项 ，    无法启动    自动展示答案   功能， 

### Debug info

```text
2.17
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-03-10 11:18
Resolution would be to add 'Auto Advance' to the Reviewer menu, as seen in Anki Desktop

<img width="189" alt="Screenshot 2024-03-10 at 11 18 47" src="https://github.com/ankidroid/Anki-Android/assets/62114487/cb5907b1-1b8f-43ce-870a-b11f9107b000">

**Comment by david-allison** [comment] 2024-03-10 19:11
Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/15519

* https://github.com/ankidroid/Anki-Android/issues/15519

**Closed** 2024-03-10 19:11 UTC
Labels: Enhancement, Anki Ecosystem Compatibility
