### ISSUE TITLE
Interesting. Yes now they are just CardN where N is some number, and you can't move them. This would be an interesting feature but it must wait for #5151 to land as that changes everything in the area. I'm hoping for that in the next day or three but it's open source so I can't promise sorry

### ISSUE THREAD

**Issue by Volmarx** [ankidroid/Anki-Android#15286] opened 2024-01-20 19:46 UTC
Interesting. Yes now they are just CardN where N is some number, and you can't move them. This would be an interesting feature but it must wait for #5151 to land as that changes everything in the area. I'm hoping for that in the next day or three but it's open source so I can't promise sorry

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/6017#issuecomment-614204535_
----
The issue was requested in 2020 but has not yet implemented.  There are some people still requesting this feature.  More and more people are using AnkiDroid instead of the desktop version of Anki, so there are many reasons to equalize the functionality.

**Comment by Volmarx** [comment] 2024-01-20 19:48
The issue was requested in 2020 but has not yet implemented.  There are some people still requesting this feature.  More and more people are using AnkiDroid instead of the desktop version of Anki, so there are many reasons to equalize the functionality.

**Comment by david-allison** [comment] 2024-01-20 19:57
The issue is still open, closing this as a duplicate of 

https://github.com/ankidroid/Anki-Android/issues/6017

**Closed by david-allison** 2024-01-20 19:57 UTC
Labels: Duplicate
