### ISSUE TITLE
[Bug] "java.io.IOException: I/O error" when attempting sign in to AnkiWeb account

### ISSUE THREAD

**Issue by bsnodin** [ankidroid/Anki-Android#9154] opened 2021-06-27 10:49 UTC
###### Reproduction Steps

1. Sign out of my AnkiWeb account on AnkiDroid
2. Attempt to sync collection -- prompts me to log in to AnkiWeb
3. Enter AnkiWeb credentials and press "LOG IN"

Other misc info:
- On the same mobile device, I am able to log into ankiweb.net in my browser app (chrome)
- In AnkiDroid, I originally signed out of AnkiWeb because I was having an issue with sync. When I tried to sync, I'd get an error saying something like: "sync error type -1 arbitrarystring"

###### Expected Result

Successful login to AnkiWeb so I can sync collection (etc)

###### Actual Result

I get the following message:

"A network error has occurred

java.io.IOException: I/O error"

I remain logged out of AnkiWeb

###### Debug info

AnkiDroid Version = 2.15.4

Android Version = 10

Manufacturer = Xiaomi

Model = MI 9

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; MI 9 Build/QKQ1.190825.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.120 Mobile Safari/537.36

ACRA UUID = 8b06829a-c014-4383-a8f0-2af02602c9db

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by bsnodin** [comment] 2021-07-14 09:26
Update: I had to do a ~factory reset on my phone and I now seem to be able to sign in to AnkiWeb and sync as usual.

It's not obvious to me whether or not some underlying issue with my phone was causing the AnkiDroid/AnkiWeb issue and the issue that caused me to need to do a factory reset.

I'm happy for this issue to be closed but I'll leave it open since I'm not sure what the proper procedure is.

**Comment by mikehardy** [comment] 2021-07-14 14:23
I had saved this one for inspection but without a reproduction I did not have any leads on it.
I'm really glad you're working again!
Since we can't reproduce and you're moving forward I think the best is to close it yes.
Cheers

**Closed by mikehardy** 2021-07-14 14:23 UTC

**Comment by dobefore** [comment] 2021-09-06 11:13
I encounter the same issue though using Anki custom server.
Ankidroid 2.15.6
how to reproduce:

1.prepare an new account and login
2.import 2 decks or more (in my case,a deck including 4 subdecks) from Ankidroid,Do not sync!!!
3.delete one of decks 
4. sync

this will cause sync error ,and two alterlatives (Ankiweb or Local) are provided to keep .
When I choose keep local,messagebox like this `sync error type -1 arbitrarystring` pop out
On my server screen,error message seems like graves count not equal 
```
sanity check failed with server: [[0, 0, 0], 32, 32, 6, 127, 7, 4, 1] client: [[0, 0, 0], 32, 32, 6, 185, 7, 4, 1]
```
I want to know wether it's my server problem or not,or something else?

**Comment by david-allison-1** [comment] 2021-09-06 12:00
> I encounter the same issue though using Anki custom server.
> Android 8
> Ankidroid 2.15.6
> how to reproduce:
> 
> 1.prepare a new account(without data and media) and login
> 2.import 2 decks or more (in my case,a deck including 4 subdecks) from Ankidroid,Do not sync!!!
> 3.delete one of decks
> 4. sync
> 
> this will cause sync error ,and two alterlatives (Ankiweb or Local) are provided to keep .
> When I choose keep local,messagebox like this `sync error type -1 arbitrarystring` pop out
> On my server screen,error message seems like graves count not equal
> 
> ```
> sanity check failed with server: [[0, 0, 0], 32, 32, 6, 127, 7, 4, 1] client: [[0, 0, 0], 32, 32, 6, 185, 7, 4, 1]
> ```
> 
> I want to know wether it's my server problem or not,or something else?

That's not the same bug. This is saying that after a sync, your sync server and AnkiDroid are displaying different information.

I would first check to see if 'reviewing - new timezone code' fixes the issue: https://github.com/ankidroid/Anki-Android/issues/9368

If not, then it may be a bug in either AnkiDroid or the sync server. Given that we sync with AnkiWeb with no issues, the implication is that it's the custom sync server, but that's not guaranteed.

**Comment by dobefore** [comment] 2021-09-06 12:10
Thanks for so constrctive advice! I will try to work out.Thanks again
