### ISSUE TITLE
[Feature] Switch Profile In AnkiDroid

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#8650] opened 2021-04-20 04:36 UTC
## Problem 

- If the user wants to maintain many profiles in one device, then there is no option for that in AnkiDroid 
- AnkiDesktop have switch profile feature for adding, removing, opening user.

## Data 

  We will store a list of profiles in shared preferences 

## Design 
- new user opens app then user will login through normal login page , and that user details will store in default profile option.
- if user want to create another profile ,then he have to navigate Settings->AnkiDroid ->SwtichUser ,then user can perform operation like add user ,select user ,delete user.
- after adding new profile in list and selecting profile then login page will open for user to login and that info will save to selected profile option (so that in  future if user again select this profile option then it will directly login without asking for all process again).
- If user select already login profile then It will directly take user to HomePage
<img src="https://user-images.githubusercontent.com/52353967/115337800-48f87500-a1bf-11eb-9bc2-bf170541a5ed.jpg" width="500" height="600" />

**Comment by TarekkMA** [comment] 2021-04-20 16:54
I like the following design, the same one used in Gmail.

![image](https://user-images.githubusercontent.com/6633545/115435042-b8935200-a209-11eb-9c8e-3ff62de943d9.png)

**Comment by Akshay0701** [comment] 2021-04-20 16:55
Thanks😊

**Comment by Akshay0701** [comment] 2021-04-20 17:04
but still i worry at many parts like in this solution I propose saving users profile in list form in shared preferences, we cant directly save List of object In it ,in order to do this we might need to parse Gson and in retriveing part we need to convert gson string in form of object  using `Type type = new TypeToken<ArrayList<Profile>>() {}.getType();`

the worrying part is  it seem to much conversion to save list and i am not aware of more optional way then this .

**Comment by TarekkMA** [comment] 2021-04-20 17:41
BTW, this change would require a change in the storage structure to support multi-profile.

Right now multi-profile support in ankidroid is done via installing multiple 
https://github.com/ankidroid/Anki-Android/wiki/FAQ#how-to-use-different-anki-profiles

**Comment by eginhard** [comment] 2021-04-21 09:07
Thanks for the ideas! This is a duplicate of #2545, I'd suggest to keep the discussion there.

**Closed by eginhard** 2021-04-21 09:07 UTC
