### ISSUE TITLE
Anki API: Add option to trigger sync

### ISSUE THREAD

**Issue by matejdro** [ankidroid/Anki-Android#3714] opened 2015-10-07 13:45 UTC
Allow 3rd party apps to trigger sync, so all flashcard changes made by said apps can automatically be synced after app finishes making changes.

**Comment by Glutanimate** [comment] 2015-10-10 11:50
I would love to see this implemented, if only to trigger sync via automation apps like Tasker. There are lots of ways I could see a sync intent being useful, for instance: Automatically performing a sync from AnkiWeb every morning to ensure you've got the latest additions and changes to your decks with you before leaving the house.

This feature request might be a duplicate of #2918, though.

**Comment by timrae** [comment] 2015-10-10 12:40
It's a good idea to have an intent. This isn't as high priority anymore
since we implemented auto sync though

**Comment by Glutanimate** [comment] 2015-10-10 14:30
Auto sync has certainly been a great addition to Ankidroid, but I think it fulfills a different purpose altogether, making the app more convenient to use when directly interacted with. 

A sync intent, OTOH, would not only greatly improve integration with other apps, but also make it possible to sync in the background/without user interaction.

**Comment by matejdro** [comment] 2015-10-10 18:06
Does auto sync work with 3rd party apps using the API? AFAIK it only works when opening/closing main app.

**Comment by Glutanimate** [comment] 2015-10-15 20:39
Just to make a stronger case for this feature request as far as the automation end is concerned, here is what I would use a sync intent for:

- **trigger a background sync in the morning before leaving the house**. I work with a lot of media files in my Anki decks, image occlusions, sound bytes, etc. That's why I usually sync Ankidroid right after completing a desktop Anki session, lest I'd have to use my mobile data plan to fetch the latest changes when I'm on the go. Unfortunately I still forget to do this sometimes and end up wasting my measly monthly data on syncing. Having a way to automate syncs would completely solve this.
- **"push" latest changes right after Anki exits**. Mostly throwing out some random ideas here, but I think it would be pretty easy to set up a system that would automatically trigger an AnkiDroid sync when Anki exits. A bash script with a call to Pushbullet on the one end, and a Tasker profile linked to the Pushbullet trigger on the other - something like this. Wouldn't that be neat?

Just two examples of the plethora of use-cases for a sync intent.

**Closed** 2015-10-16 16:07 UTC

**Comment by timrae** [comment] 2015-10-16 16:47
Done
https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API#sync-intent

**Comment by Glutanimate** [comment] 2015-10-16 17:27
Hey Tim,

thanks so much for addressing this so quickly.

I've just given the new Alpha a test run after setting up the intent with Tasker. It works for the most part, but the intent's behaviour seems to be somewhat erratic. It will sometimes:

- launch Ankidroid without triggering a sync (seems to mostly happen when an Ankidroid instance is in memory / the Recent Apps screen or cached)
- launch Ankidroid for a split second, then perform a sync (seems to mostly happen when Ankidroid hasn't been launched before in that session)
- do nothing at all (seems to only happen when the screen is off)

Changing the intent target to "Service" fixes the last point - syncing works reliably when the screen is off - but the behavior when the screen is on remains unpredictable.

If it's any help, I tested the latest alpha on Android KitKat 4.4.4.

**Comment by timrae** [comment] 2015-10-16 19:22
Thanks for the feedback. I've changed the documentation to use Service for the target, and made a couple of changes in alpha74 which should reduce the probability of that first bug happening. 

There's a 1minute minimum interval between syncs now to prevent server overloading, and if you exceed that or try to sync while offline then you'll need to manually close AnkiDroid with the hardware back button in order for subsequent sync to work correctly.

**Comment by timrae** [comment] 2015-10-16 19:44
I've fixed the bug I mentioned in my last post by using notifications instead of snackbars, I won't bother building a new alpha just for that though

**Comment by Glutanimate** [comment] 2015-10-18 11:44
Awesome. thanks for the fixes. I've just given Alpha 76 a try and it's working almost perfectly now. The only remaining issue is that triggering the sync will still briefly launch Ankidroid before returning to the previous screen. As this only happens when the screen is on and even then only lasts for the fraction of a second it's not that big of a deal, but can still be distracting.
