### ISSUE TITLE
[Bug] Auto Advance doesn't work

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#15544] opened 2024-02-17 08:09 UTC
###### Reproduction Steps

1. Set Seconds to show answer in Deck Settings

###### Expected Result

The setting was working in 2.17beta2

###### Actual Result

The setting isn't working in 2.17beta3 and beta4

###### Debug info
AnkiDroid Version = 2.17beta4 (b6ed71fdc2bfceeed3d96e8d249f9fa53aefed12)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.164 Mobile Safari/537.36

ACRA UUID = 7ed5121d-d5f6-484c-a729-72c1f012dc72

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment] 2024-02-17 08:27
Reproduced
I'll look which commit introduced this

**Comment by SanjaySargam** [comment] 2024-02-17 09:05
Can't reproduce

**Comment by SanjaySargam** [comment] 2024-02-17 09:10
@pavreh set seconds to 2 and try once

**Comment by pavreh** [comment] 2024-02-17 11:45
Well, I need to set Seconds to show question. Then, answer in a cloze deletion is shown.

**Comment by SanjaySargam** [comment] 2024-02-17 11:50
I set Seconds to show question to 3.0
and Seconfs to show answer to 2.0

It still working

**Comment by pavreh** [comment] 2024-02-17 12:21
Try Seconds to show question to 0.0
and Seconds to show answer to 2.0.
Answer is not shown while
if you set Seconds to show question to 2.0
and Seconds to show answer to 0.0,
answer is shown.

**Comment by SanjaySargam** [comment] 2024-02-17 12:25
You need to understand one thing 
Here Seconds to show question for x seconds means it will show question x secs and then it will show answer
and Seconds to show answer for x seconds means it will show answer x secs and then it will show next question

And if we set value to 0 then it means auto advance is disabled

**Comment by pavreh** [comment] 2024-02-17 12:34
Thanks for your time. I changed the settings of my deck so it is working again for me.
I am just saying the logic was opposite in 2.17beta2. If I set Seconds to answer then the answer was shown. If I set Seconds to questions then the next question was shown.

**Comment by SanjaySargam** [comment] 2024-02-17 12:50
You can close this issue. Thank You

**Closed** 2024-02-17 15:20 UTC

**Comment by mikehardy** [comment] 2024-02-17 18:54
@pavreh maybe of interest, there was a logic error in the auto-advance in the betas before beta4 #15516 - that may explain it

**Comment by pavreh** [comment] 2024-02-17 23:26
@mikehardy I see, thanks. I just noticed Anki works in the same way.
