### ISSUE TITLE
Review Card scheduling seems to have issues: version 2.12.1

### ISSUE THREAD

**Issue by turbowine** [ankidroid/Anki-Android#6898] opened 2020-08-16 00:00 UTC
I'm using Ankidriod 2.12.1 and I noticed that after this upgrade the card scheduler when reviewing **missed** cards is not working the way it used to.

For example, say I have a bunch of cards I'm reviewing, 700+ is common for me.  When I answer incorrectly, the card  should come back in 1 minute, and then 5 min and then 10 minutes, etc.  as I see the card again and then each time I answer correctly the time interval grows according to my custom settings.  However,  as I review, say I accidentally hit the 'good' button when I meant to hit "again" because I got it wrong, but was too fast with my fingers.  So then I hit the back button, to fix my answer. Sometimes, after doing this, it won't leave this card until this card is finished.   As in, I'll hit good at 1 min, the same card comes up again, then I hit good again, at 5 minutes, then the same card comes back immediately, and I hit good again for 10 minutes, and then once again the same card comes back immediately for 20 minutes, until it is all done and I hit the last "good" and the card is then finished.  However, it obviously didn't intersperse the card with the other cards in the deck, waiting out the time delays.  Even though there are other cards that either have not been seen yet, or have lower time delays (that should be mixed in to the review order).  It is running out the current card without intermixing with the other cards.  This is new, I've not seen this in prior versions.  (This happens both in the main and filtered decks.)

Additionally, I've seen cards get ignored.   For my 700 cards, it takes me 90+ min or so to review all of them.  Sometimes when I'll  hit again on a card (and the delay is low, like 1 or 5 or 10 min)  I don't see that card again for 45, 60 minutes. So it is also ignoring some cards that should be mixed in and reviewed giving greater intervals than intended.

**Comment by turbowine** [comment] 2020-08-16 00:07
I found the  forum, and I see someone else posted about this

https://groups.google.com/forum/#!topic/anki-android/FDqqbj9rn_U


I am NOT using   Scheduler V 2

Android version 10

**Comment by mikehardy** [comment] 2020-08-16 00:08
@turbowine thank you for reporting this! @Arthur-Milchior has been hard at work on the scheduler with a massive pile of performance improvements that have caused a few issues, it may be that this is already fixed - he might have more information

**Comment by Arthur-Milchior** [comment] 2020-08-16 00:18
# First Error
It's the first time I've seen this error described. Clearly something is really wrong here. Would you mind sharing your collection with us (or with me) when you see a new card without waiting for 5 minutes ? I'll also need you to tell me which card you were reviewing (id if possible. Otherwise the field content and the card type, so I can find it myself)

Do you use filtered deck ? 
If you go back to the deck picker and start reviewing again, do you still have the same problem ?
Are those problem created by new cards, review cards, or by both kinds of card ?


# Second error

the second error seems to be a duplicate of https://github.com/ankidroid/Anki-Android/issues/6768 and of the email you gave. Could you go to https://github.com/ankidroid/Anki-Android/issues/6768 and answer all question I've asked ? It may help me find how to reproduce the bug.

In particular, i've got the same question, i'd love to see a copy of your collection when the bug occurs. It should be easier to understand what is going on if I can take a look at your collection.

Do you know whether those problem arrive with new cards ? with cards which are due today ? Both ?
Do you see new cards before seeing due cards ?

**Comment by turbowine** [comment] 2020-08-16 00:31
First Error
I do think you've seen First error before, sounds like this to me:

https://groups.google.com/forum/#!topic/anki-android/FDqqbj9rn_U

As I said, the problem starts when you hit "undo" (back?) button  on a card you reviewed.


First & Second Error
I have a filtered deck that I use mostly, that is just the review cards that are due today.  No new cards.  I see both in this.
(I study new cards separately from review cards.)

**Comment by Arthur-Milchior** [comment] 2020-08-16 00:41
You're right. Thanks for insisting. I don't know why I thought the email was similar to the github bug.

Interesting

**Comment by Arthur-Milchior** [comment] 2020-08-20 21:12
Do you think you could go to alpha https://docs.ankidroid.org/#betaTesting and let us know if the problem still exists ? A lot of change occurred since 2.12 and I'd be curious to know whether it was solved.

**Comment by Arthur-Milchior** [comment] 2020-08-25 22:41
I believe I've found the cause of the bug. If I'm right, I assume that it was corrected on alpha.

Can you please state whether:
* when you undo a card C, put it in learning, and see it again and again, do you have new/review cards, or are all of you cards in learning ?
* If some cards are not seen until the end of the session, is it possible that you undo, and then press "again". I believe that if, just after Undo, you put a card in the learning queue, it forbids the queue to be filled again until this card is seen properly.

**Comment by turbowine** [comment] 2020-08-27 02:59
Using these definitions from the Anki Guide:

  *

    *New* refers to cards that you have downloaded or entered in, but
    have never been studied before.

  *

    *Learning* refers to cards that were seen for the first time
    recently, and are still being learnt.

  *

    *To Review* refers to cards that were previously learnt, and now
    need to be reviewed so you don’t forget them.


First your item one, I usually study in filtered decks, so there are no  
"new" cards in these decks.    So these are all a mixture of 
learning/review cards, some of which will be mature

(interval of greater than 21 days).

To be honest, I don't know that this happens when I study new words. The 
way I do it is a move all learning/review to a filter deck and study 
them there each day, and then only study the new words for the day in 
the main deck.


For your item two, since this issue appears to be new to this version, I 
don't think it is expected behavior.


Side question: When does a card transition from "learning" to "review"?

**Comment by Arthur-Milchior** [comment] 2020-08-27 08:21
>  First your item one, I usually study in filtered decks, so there are no  "new" cards in these decks.    So these are all a mixture of learning/review cards, some of which will be mature (interval of greater than 21 days).

I do not feel like I got an answer to my question. I'll try to ask differently.


When you have a card in learning that you keep seeing again and again until it graduate, do you still have cards in review to see that day ? I would expect that it is is not the case and that your card gets priority over other cards in learning but that you can still see review cards.

> For your item two, since this issue appears to be new to this version, I don't think it is expected behavior. 

Indeed, it is not expected, and I thank you very much for this bug report. I even think we already corrected the bug in the alpha version that I invited you to try. 

I do not see how it answer my second question however.

> Side question: When does a card transition from "learning" to "review"?

You have a number of steps in the deck configuration. By default I believe it is 1. 5, 10. It means that if you press "again" you'll see the card again in 1 minute. Otherwise, if the card is new and you press good, you'll go to step 2 and see the card in 5 minutes. Then if you press good again you'll go to step 3 and see the card in 10 minutes. If you press good again there is no more step and the card graduate - that is transformed into a review card.

**Comment by turbowine** [comment] 2020-08-27 16:49
Your questions were:

  * when you undo a card C, put it in learning, and see it again and
    again, do you have new/review cards, or are all of you cards in
    learning ?
  * If some cards are not seen until the end of the session, is it
    possible that you undo, and then press "again". I believe that if,
    just after Undo, you put a card in the learning queue, it forbids
    the queue to be filled again until this card is seen properly.

Follow-up Question to #1:

When you have a card in learning that you keep seeing again and again 
until it graduate, do you still have cards in review to see that day ? I 
would expect that it is is not the case and that your card gets priority 
over other cards in learning but that you can still see review cards.

Answer:  Yes, I do, both that I've started reviewing and some that have 
not been reviewed at all yet.  If I'm at step 1 and go to Step 2,  
wouldn't expect to see the card for 5 minutes, I'd expect to see some 
other cards first, either for the first time that day, or other review 
cards at  Step 2 or Step 3.  But instead I see the same card again 
immediately.  And then the same thing when it goes to Step 3.  It does 
not interleave other cards, as it should.

For Question 2, you said I didn't answer it, but I don't understand the 
question. I think you are referring to cards where I'm on step two and 
expect to see them in 5 minutes, but I don't see them for 30 minutes (or 
whatever).

**Comment by turbowine** [comment] 2020-10-05 06:03
I've been using the newest version and I just wanted to let you know it 
looks like this bug is fixed.

Thank you very much!!

**Comment by david-allison-1** [comment] 2020-10-05 09:12
@turbowine Thanks for the feedback!

**Closed by david-allison-1** 2020-10-05 09:12 UTC
Labels: 2.12.x, Needs Triage, Reviewer
