### ISSUE TITLE
[Bug] 2.16.0beta1: MissingDirectoryException: /storage/emulated/0/AnkiDroid

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13806] opened 2023-05-05 22:13 UTC
* https://ankidroid.org/acra/app/1/bug/47388/report/db387581-d2e9-423a-a381-aeb95fb83d58

```
com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$MissingDirectoryException: Directories [MissingFile(source=source, file=/storage/emulated/0/AnkiDroid)] are missing.
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$DirectoryValidator.getExceptionOnNullResult(MigrateUserData.kt:5)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Companion.createInstance(MigrateUserData.kt:9)
	at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Companion.createInstance(MigrateUserData.kt:3)
	at com.ichi2.anki.services.MigrationService$onStartCommand$1.invokeSuspend(MigrationService.kt:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

```
getDataDirectory: /data
getDataSystemDirectory: /data/system
getDownloadCacheDirectory: /data/cache
getExternalStorageDirectory: /storage/emulated/0
getExternalStorageState: mounted
getInternalMediaDirectories: [/system/media, /oem/media, /product/media]
getLegacyExternalStorageDirectory: /sdcard
getOdmDirectory: /odm
getOemDirectory: /oem
getProductDirectory: /product
getProductServicesDirectory: /product_services
getRootDirectory: /system
getStorageDirectory: /storage
getSystemExtDirectory: /system_ext
getVendorDirectory: /vendor
isExternalStorageEmulated: true
isExternalStorageLegacy: true
isExternalStorageManager: false
isExternalStorageRemovable: false
```

```
deckPath: `/storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid1`
migrationDestinationPath `/storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid1`
migrationSourcePath `/storage/emulated/0/AnkiDroid`
```

**Comment by david-allison** [comment] 2023-05-05 22:15
We need an error message + actions if this case occurs. Handling the below cases:

* If a user deleted the AnkiDroid folder
* If a user renamed the AnkiDroid folder 
* If a user ejected the AnkiDroid folder

**Comment by BrayanDSO** [comment] 2023-06-06 20:39
If the AnkIDroid directory is deleted, the migration needs to be considered finished. 

I wouldn't spend time on renaming (why someone would do that? if they do something crazy like that, they can feel the consequences) and on SD cards removal (in some cases it may not because the used wanted to, but too hard and rare case to deal with it

Can we lock the directory to avoid deleting it or renaming it? Like when a "you can't do this. that app is using this folder" message appears. If so, that's a good fix

**Comment by oakkitten** [comment] 2023-06-23 19:00
This comes from `MigrateUserData` so this happens when migrating *media files*, which is launched after migrating essential files, which must have succeeded. CMIIW but at this point `/storage/emulated/0/AnkiDroid` should exist?

**Comment by BrayanDSO** [comment] 2023-06-23 21:29
I could reproduce it by deleting the folder. User's fault, but still possible

**Comment by BrayanDSO** [comment] 2023-08-31 10:17
I don't think this will be addressed in the future

**Closed by BrayanDSO** 2023-08-31 10:17 UTC
Labels: Priority-High, Bug
