### ISSUE TITLE
[BUG]: Numeric Keys Don't Work

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16998] opened 2024-08-29 14:38 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

* Connect a physical keyboard.
* Go to **Settings > Controls** and bind numeric keys to control options. Flag options already use them with <kbd>Ctrl</kbd>.
* Press bound keys in reviewer. Try <kbd>Ctrl</kbd>+<kbd>1</kbd>, for example. This should toggle the red flag.

### Expected behaviour

Control options don't work. 

### Debug info

```text
AnkiDroid Version = 2.19beta1 (6630ff411d643bf03206e106c4d940dc7076e738)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by brishtibheja** [comment] 2024-08-29 14:55
I never used keyboard until recently (that's why you never saw me talking about them before).

**Comment by BrayanDSO** [comment] 2024-09-01 10:36
I'll close this as `Can't reproduce`. It may be an issue with your keyboard

**Closed by BrayanDSO** 2024-09-01 10:36 UTC
Labels: Bug, Can't reproduce

**Comment by brishtibheja** [comment] 2024-09-01 17:15
I wouldn't say so, the keypresses work when assigning control options.
