### ISSUE TITLE
Requesting Anki Mobile for Scheduler V2

### ISSUE THREAD

**Issue by averywjohnson** [ankidroid/Anki-Android#4926] opened 2018-09-03 21:33 UTC
Please provide me access to Anki Mobile Beta Android so I can use scheduler V2

*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by timrae** [comment] 2018-09-03 22:05
Hi, it's not implemented on AnkiDroid. There is already an issue open so I'm closing this. In the future please search before opening a new issue.

**Closed by timrae** 2018-09-03 22:05 UTC

**Comment by timrae** [comment] 2018-09-03 22:06
Duplicate of #4905
