### ISSUE TITLE
Parallel builds A and B can't be installed

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#6510] opened 2020-06-19 21:09 UTC
###### Reproduction Steps

1. Download one of the newly included parallel builds A or B from the releases page (in my case 2.12alpha15 A)
2. Install

###### Expected Result

Successful installation

###### Actual Result

A message is shown: "Do you want to install an update to this existing application? Your existing data will not be lost. It does not require any special access."

(That's strange because only used Build E before, so why it says "existing application"?)

After pressing "install" button, the setup tries to install but finishes unsuccessfully with message "app not installed"

I never had problems installing previous parallel builds (on my Android 9 phone) that were released manually.

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2020-06-19 22:23
That is...unexpected! Indeed, something is going wrong with the generation of parallel builds and then their copying / uploading but it is not immediately obvious.

I can see that the parallel builds are still internally using the main application name, they are not self-identifying to the system as  Ankidroid.A etc. You can see it in 'package' line below.

Let me check it out - thanks for reporting

```
(base) mike@kunashir:~/Downloads % apkanalyzer  manifest print AnkiDroid-2.12alpha15.parallel.A.apk 
<?xml version="1.0" encoding="utf-8"?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:versionCode="21200115"
    android:versionName="2.12alpha15"
    android:installLocation="0"
    android:compileSdkVersion="28"
    android:compileSdkVersionCodename="9"
    package="com.ichi2.anki"
    platformBuildVersionCode="28"
    platformBuildVersionName="9">

```

**Comment by mikehardy** [comment] 2020-06-19 22:43
Fixed in https://github.com/ankidroid/Anki-Android/commit/f7cf613c6e126941396c1a6fc8d18e9a99f8eb80

I uploaded new parallel packages to the release tag, can you try them? should work: https://github.com/ankidroid/Anki-Android/releases/tag/v2.12alpha15

**Closed by mikehardy** 2020-06-19 22:43 UTC

**Comment by Anthropos888** [comment] 2020-06-20 19:09
@mikehardy Works fine now, thank you!

**Comment by mikehardy** [comment] 2020-06-20 19:49
Root cause was the law that "no good deed goes unpunished", when I added Amazon App Store publishing it messed up the package renamer. One step forward, one step to the side, repeat

**Comment by Anthropos888** [comment] 2020-06-20 20:02
Haha, all developers seem to hate Amazon ;-) 
Hopefully this will be a solution soon:
https://www.xda-developers.com/amazon-fire-toolbox-helps-install-google-apps-change-launchers-and-more-on-amazon-fire-tablets/

**Comment by mikehardy** [comment] 2020-06-20 21:17
That's a neat idea, but my friends with Fire tablets (and I have a few) are never doing that, no way. They generally have multiple small children running around and need to deal with life, honestly it was easy enough to implement the amazon auto upload, I'm just endlessly surprised by the ripple effects of altering anything in software, no matter how tiny
