### ISSUE TITLE
Samsung: Cannot add new cards (plus button doesn't work)

### ISSUE THREAD

**Issue by mikeingerman** [ankidroid/Anki-Android#8993] opened 2021-05-28 10:06 UTC
Edit by David: I haven't been able to reproduce this and I'm seeking a device on the [Samsung test lab](https://developer.samsung.com/remotetestlab/rtlDeviceList.action), and/or a device where we can install alphas with additional diagnostic logging via logcat or a source which details a workaround for this issue

Bug reported on:

* Samsung Galaxy A51 - Android 11 - English - ❌
* Samsung Galaxy A31 - Android 11 - English - ❌ https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser/user/ab45dc86-566f-47a1-ba6e-5dd1fa78db0a
* Samsung Galaxy Tab A 10.5 (SM-T590) - Android 10 - ❌

Getting a user to perform a "send exception report" from the help menu will allow us to obtain better device configuration to see if we can pinpoint if it's a firmware version, or other factors

**test lab notes**
* Download and run applet from: https://developer.samsung.com/remotetestlab/rtlDeviceList.action
* press the power button
* swipe to open the device
* ⚠️⚠️ **DO NOT LOG IN TO YOUR GOOGLE ACCOUNT**
* in the browser, enter: https://github.com/ankidroid/Anki-Android/releases
* Select 2.15.2 or later 2.15
* Go through prompts to install
* Try and break the "Plus" button (also called a FAB)

**test lab progress**

- Galaxy Tab S7 (Android 10) - ✔️
- Galaxy Note10 (Android 10) - ✔️
- Galaxy S9+ (Android 10) - ✔
- Samsung A51 on Android 10 (Vietnam)
- Galaxy A51 Phone (Android 10) ❓ Couldn't access devices in Moscow
- Galaxy s10e (Android 10) - ❓
- Galaxy S9 (Android 10) - ❓

**thoughts**

Another avenue to test is to see whether using the Software Renderer setting in "Advanced" fixes this

## Original Report

have used Anki happily for months and suddenly I cannot add new cards. The screen is
Grey when I press the Plus button. 

Version is 2.15.2 
Have tried a database check and reinstalling the app.

I can't work out how to attach the debug report from clip board - is this what you need?
 AnkiDroid Version = 2.15.2

Android Version = 10

Manufacturer = samsung

Model = SM-T590

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-T590 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Safari/537.36

ACRA UUID = 1ce8b704-36a6-410b-b23e-d4b3f5c1bcd6

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

Help please!

**Comment by prateek-singh-3212** [comment] 2021-05-28 10:14
@mikeingerman Thanks, for reporting this issue. can you please share the screenshot? 
For debug info please read this guide: https://docs.ankidroid.org/help.html

**Comment by mikeingerman** [comment] 2021-05-28 10:33
OK will do - have never taken a screen shot from a tablet before and am
trying to work out how to send it to you.

A steep learning curve, worse than mastering German!

Mike

**Comment by david-allison-1** [comment] 2021-05-28 10:35
The debug report is good!

First off: please download 2.14.6 parallel.A so you can add cards: https://github.com/ankidroid/Anki-Android/releases/tag/v2.14.6 ensure that you close ankidroid before opening it

Now, could you close AnkiDroid.A, open ankidroid and send a video of what's happening. I'm very confused, and a video should help show what's going on

**Comment by david-allison-1** [comment] 2021-05-28 10:39
@Akshay0701 what's the Android video recorder that you use? I'll need to add a section to the dev guide for it

**Comment by mikeingerman** [comment] 2021-05-28 10:43
All this is making me think you are IT gurus - and I am not!

Am away from desk for rest of the day - may have time and determination? to
deal tomorrow.

Regards

Mike

**Comment by Akshay0701** [comment] 2021-05-28 10:46
@david-allison-1 I used [AZ Recorder App](https://play.google.com/store/apps/details?id=com.hecorat.screenrecorder.free&hl=en_IN&gl=US)

>

**Comment by david-allison-1** [comment] 2021-05-28 10:48
Understood Mike.

For now: click here and install the app to get the previous version of AnkiDroid: https://github.com/ankidroid/Anki-Android/releases/download/v2.14.6/AnkiDroid-2.14.6.parallel.A.apk

**Comment by mikeingerman** [comment] 2021-05-28 16:15
Will do, thanks!

**Comment by david-allison-1** [comment] 2021-05-28 16:38
@mikeingerman Could you try `Settings - Advanced - Safe Display Mode` and see if this fixes the issue

**Comment by david-allison-1** [comment] 2021-05-28 16:39
This seems to be confined to Samsung devices (also had a report on the forums, pointed them here).

I've tried on:

* Galaxy Tab S7 (Android 10) - ✔️ 
* Galaxy A51 Phone (Android 10) ⛔ Couldn't access devices in Moscow
*Galaxy Note10 (Android 10) - ✔️

**Comment by mikeingerman** [comment] 2021-05-28 16:48
David

Have installed and the problem has gone - thanks.

Any idea why?!!

Mike

**Comment by david-allison-1** [comment] 2021-05-28 16:52
The app that you installed is an old version of AnkiDroid. It won't be updated, but it lets you use the app without this problem while we diagnose the issue

It'd be great to get your help in trying a few things to get this fixed. 

The bug likely impacts users that we haven't heard from, and we can't yet reproduce the issue ourselves, which makes it hard to deal with

**Comment by david-allison-1** [comment] 2021-05-31 12:23
@mikeingerman A video of this issue would be fantastic if you have the time

**Comment by david-allison-1** [comment] 2021-05-31 19:54
Can't repro on a Samsung A51 on Android 10 (Vietnam)

**Comment by david-allison-1** [comment] 2021-06-02 13:08
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser/user/ab45dc86-566f-47a1-ba6e-5dd1fa78db0a - from https://www.reddit.com/r/Anki/comments/nqhbme/anki_doesnt_allow_new_deck_and_note/h0artmb/?context=3

**Comment by AbdelrahmanHamdy1998** [comment] 2021-06-03 14:47
No problem here, S10e android 11. ankidroid version playstore 2.15.4

**Comment by david-allison-1** [comment] 2021-06-03 15:13
I'm not hopeful, but this is possibly caused by the text labels not being clickable, which is fixed in https://github.com/ankidroid/Anki-Android/pull/9055 and will be in 2.15.5

**Comment by mikehardy** [comment] 2021-07-03 23:17
No feedback on this one, I think it was fixed by #9055

**Closed by mikehardy** 2021-07-03 23:17 UTC
Labels: Bug, Can't reproduce, Help Wanted, Home Screen, Nondeveloper, Priority-High

**Comment by Sarahirl7** [comment] 2021-08-12 17:08
Hola quiero saber porque No me aparecen todas mis tarjetas en el mazo pero si al explorar
![Screenshot_20210812-115952](https://user-images.githubusercontent.com/88849415/129238845-1d2a9e24-efec-4c4c-b79d-57cc11123c39.png)
![Screenshot_20210812-115959](https://user-images.githubusercontent.com/88849415/129238861-0a6b165d-7944-4935-9af3-2f1e3dabff05.png)
