### ISSUE TITLE
Add User Profile Feature

### ISSUE THREAD

**Issue by CreatorZZY** [ankidroid/Anki-Android#8748] opened 2021-05-01 15:53 UTC
**Is your feature request related to a problem? Please describe.**
Add User Profile Feature Just like What the feature in Anki of IOS do.

**Describe the solution you'd like**
Emmm, It is useful for me to manage the desk.

**Describe alternatives you've considered**
Change The profile in the Left（or Right） Side drawer.

**Additional context**
Nope.

**Comment by david-allison-1** [comment] 2021-05-01 16:02
Thanks for the feature request!

I believe this is a duplicate of https://github.com/ankidroid/Anki-Android/issues/2545

**Closed by david-allison-1** 2021-05-01 16:02 UTC
Labels: Duplicate
