### ISSUE TITLE
Constant AnkiDroid Bug

### ISSUE THREAD

**Issue by PBAnkiSandwich** [ankidroid/Anki-Android#5681] opened 2020-01-02 14:19 UTC
###### Reproduction Steps

1. Enter the ankidroid app (start the app)

###### Expected Result

Start the app with no problems

###### Actual Result

App starts correctly, but banner appears below that reads 
"AnkiDroid has encountered a problem; a report is being sent to the developers..."
The banner does not disappear and stays on the screen when I exit the app or start a new one, only dissappears when I stop the app. I have deleted the app and its files, reinstalled it and downloaded my files, and the banner persists.
![Capture+_2020-01-02-10-58-37](https://user-images.githubusercontent.com/59444222/71671367-aad66680-2d51-11ea-9f47-a87e2120b310.png)
![Capture+_2020-01-02-10-59-02](https://user-images.githubusercontent.com/59444222/71671368-aad66680-2d51-11ea-8328-bcaae8bdc20d.png)

###### Debug info
AnkiDroid Version = 2.9.1

Android Version = 7.0

ACRA UUID = 

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2020-01-02 14:24
Hi there! Without that ACRA UUID I won't be able to isolate the crash report and find the root cause

You might try a database check from the deck list

I will say that you should try the current alpha versions, as any problem if not yet fixed, will be fixed there first so you can test it, and it may have already been fixed meaning the alphas might just work for you: https://docs.ankidroid.org/manual.html#betaTesting

**Comment by PBAnkiSandwich** [comment] 2020-01-02 14:45
I tried the database check and it all seems to be working properly. I also tried the media check and it seems that all my media files are missing now for some reason. 
Sadly I don't know how to get the ACRA UUID because it doesn't appear when I press"copy debug"
What can I do?

**Comment by mikehardy** [comment] 2020-01-02 14:46
If you did the database check and that fixed it, I wouldn't worry, it must have been one of the forms of known corruption that the check can fix. For missing media - you might try this ?thttps://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

**Comment by PBAnkiSandwich** [comment] 2020-01-02 14:51
I'm going to try using the link on missing media, thanks!
And, no, the database check didn't do anything

**Comment by mikehardy** [comment] 2020-01-02 14:54
Oh - sorry, I understand that you did the database check and "all seems to be working properly", meaning "it does not crash all the time now". If it is still crashing, then I would join the beta program via google Play, then add yourself to the alpha list and check for updates on the google play beta tab to get the most up to date build, and re-try

**Closed** 2020-01-06 15:13 UTC
Labels: Waiting For Feedback

**Comment by PBAnkiSandwich** [comment] 2020-01-06 15:15
Hello! Just wanted to say the issue has been resolved. A few days after enabling beta testing, anki stopped working entirely. The app would glow when I picked it (Like apps do whem they're about to open) but nothing happened. So I deleted the app and downloaded what seems to be the beta version, plus downloading many missing media files. And now it seems to be working perfectly. Thanks!
