### ISSUE TITLE
Can't directly use android studio with this github

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#5461] opened 2019-10-10 13:17 UTC
###### Reproduction Steps

1. I forked this repo
2. I cloned it into my computer
3. I installed android studio on my computer
4. I opened the git project
5. I allowed android studio to install everything it tells me it needs to install

###### Expected Result
Being able to compile ankidroid

###### Actual Result
The following error messages:
ERROR: Failed to resolve: com.android.support:customtabs:25.1.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: AnkiDroid

ERROR: Failed to resolve: com.android.support:appcompat-v7:25.1.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: AnkiDroid

ERROR: Failed to resolve: com.android.support:design:25.1.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: AnkiDroid

ERROR: Failed to resolve: com.android.support:recyclerview-v7:25.1.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: AnkiDroid

ERROR: Failed to resolve: com.android.support:support-annotations:24.1.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: AnkiDroid

ERROR: Failed to resolve: com.android.support:support-v4:24.2.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: AnkiDroid

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
None here

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2019-10-10 13:44
We haven't been on the support libraries in forever, I'm not sure what version you forked? If it was the 2.8 branch, that one is dead - no further updates may be published to the app store so maintenance has been done and I wouldn't expect it to compile.

master works fine with Android Studio 3.5.x (current stable), I was just using it yesterday - also it's important to note that our CI system also does a clone in order to the builds, which succeeded for me about 10 times yesterday. So I'm going to close this as "can't reproduce" but we can reopen if there's more to it

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide

**Closed by mikehardy** 2019-10-10 13:44 UTC

**Comment by Arthur-Milchior** [comment] 2019-10-10 13:58
I'm quite sorry, it's enterily my fault. I didn't realize I already cloned ankidroid years ago; and so that when I cloned my repo, it was not up to date.
Corrected
