### ISSUE TITLE
[Bug] Answer time is not measured with V16 schema

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12024] opened 2022-08-14 04:50 UTC
###### Reproduction Steps
1. use V16 backend, V3 scheduler
2. long tap on a deck - Deck options - General - Maximum answer time is 60 s
3. review a card in 1 s
4. open Card info of the reviewed card 

###### Expected Result
Time (of the answer) is about 1 s.

###### Actual Result
Time is 60 s. Time is maximum answer time set in Deck options.
![Screenshot_20220814-064244_AnkiDroidA](https://user-images.githubusercontent.com/10192661/184522937-379eb3a1-e28a-485e-9ea4-f6323aa49128.png)

###### Debug info
AnkiDroid Version = 2.16alpha77 

Android Version = 12 

Manufacturer = samsung 

Model = SM-A225F 

Hardware = mt6769t 

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36 

ACRA UUID = 5d64dc12-4f5a-41a5-9aef-b68c18794aaf 

Scheduler = std3 

Crash Reports Enabled = true 

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment] 2022-08-14 05:06
I was not able to reproduce it when building with https://github.com/ankidroid/Anki-Android/pull/11849. If the issue still exists for you after it is merged, please let us know.

**Comment by pavreh** [comment] 2022-08-16 19:33
Unfortunatelly, still reproducible in 2.16alpha78, v3 scheduler. I started a new collection, made some cards and learned them.

**Comment by dae** [comment] 2022-08-16 19:50
Thanks for letting us know pavreh. I can reproduce it now :-( I must have made a mistake when I tested last time. A fix for this will hopefully be in the next alpha.

**Closed** 2022-08-16 20:59 UTC
