### ISSUE TITLE
Unnecessary Step When Adding Audio/Video

### ISSUE THREAD

**Issue by E0697** [ankidroid/Anki-Android#14146] opened 2023-07-21 14:02 UTC
###### Reproduction Steps

1. Create or edit a card
2. Tap on attachment symbol in any field
3. Tap on add audio or video
4. Another choice is presented between video and audio, when there's already a seperate option for each earlier.

###### Expected Result

After tapping on add audio it should go to file selection immediately

###### Actual Result

Another choice between audio and video is presented.

###### Debug info

AnkiDroid Version = 2.16.0beta5

Android Version = 12

ProductFlavor = full

Manufacturer = realme

Model = RMX2170

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; RMX2170 Build/SKQ1.210216.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36

ACRA UUID = 2faedfa9-8c35-433f-be34-c02a5473aea9

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by n1snt** [comment] 2023-07-23 07:00
If this gets approved, I would love to work on this.

**Comment by lukstbit** [comment] 2023-08-02 09:18
The usability is not great around this part of the app and it will be improved most likely for the 2.17 release.

@n1snt I plan to refactor NoteEditor so it wouldn't be wise to spend time working on this.

**Comment by E0697** [comment] 2023-08-03 06:45
Looking forward to this!

**Comment by BrayanDSO** [comment] 2023-08-31 10:20
Duplicate of #13064

**Closed by BrayanDSO** 2023-08-31 10:20 UTC
Labels: Accepted
