### ISSUE TITLE
Ankidroid app Import CSV feature

### ISSUE THREAD

**Issue by nathgilson** [ankidroid/Anki-Android#5257] opened 2019-03-04 09:34 UTC
That would be great to be able to import .cvs files directly to the app with no need to pass by the PC version

**Comment by mikehardy** [comment] 2019-03-04 14:09
Duplicate of #3517 - please head over there and give it a thumbs-up as it otherwise doesn't get a lot of traffic. There is already some infrastructure in the code to do similar things so maybe someone will pick it up...

**Closed by mikehardy** 2019-03-04 14:09 UTC
