### ISSUE TITLE
To allow fliping over into next card in interface of preview

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#4344] opened 2016-06-24 14:19 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

I don't sure I can expressed clearly what I want to say.Sorry my English and if you have any query to my suggestion I will response you as soon as possible.

###### Expected Result

I hope to allow fliping over into next card in interface of preview

###### Actual Result

Current solution
**Card browser**>**long-click the cards**>**Preview**>**Show answer**
Then you can see the card's content.If you want see the next card,I have to
**Return**>**long-click the next cards**>**Preview**>**Show answer**...
Oh kill me please.I just want to browse my notes.T_T

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment] 2016-06-29 04:26
Duplicate of #1381

**Closed by eginhard** 2016-06-29 04:26 UTC

**Comment by Juddd** [comment] 2016-06-29 06:50
I don't know what's meaning about you close this topic.Since the #1381 have already metioned this but it don't be implemented up to now.So can any information to give?

**Comment by eginhard** [comment] 2016-06-29 07:11
It just means that you should look at that issue for updates, there is no need to track the same thing in multiple places. That issue is "accepted", which means that if somebody implements such a feature, it would be merged into AnkiDroid - it's no guarantee of somebody working on it and so far nobody has volunteered to do so.
