### ISSUE TITLE
[Bug] Error if answering too fast 

### ISSUE THREAD

**Issue by 69asgard** [ankidroid/Anki-Android#14813] opened 2023-11-25 09:15 UTC
Anki performed a card check on November 25th, 2023 at 3:58 PM. The new version has a problem where if you review cards too quickly, there is a high probability of the following error message:

"card was modified: Normal (Review (ReviewState { scheduled _ days :28, elapsed _ days :28, ease _ factor :1.3, lapses :0, leeched : false , memory _ state : None ,) Normal (Review (ReviewState { scheduled _ days :21, elapsed _ days :23, ease _ factor :1.3, lapses :0, leeched : false , memory _ state : None , )"

This is followed by a several-second long freeze-up.

**Comment by david-allison** [comment] 2023-11-25 09:28
Hi, thanks for the report, please edit the main post to include your AnkiDroid debug info

**Comment by mikehardy** [comment] 2023-11-25 12:48
Also - this may already be fixed in the 2.17alphas - you might try a parallel release to see if it is reproducible there (assuming you are not already on the 2.17alpha6 version - our current - alpha - if you are already on that, then we've got an issue...) 

https://github.com/ankidroid/Anki-Android/releases

**Comment by 69asgard** [comment] 2023-11-25 15:43
> 另外-这可能已经在2.17αs中修复-您可以尝试并行发布，看看它是否可以重现（假设您还没有使用2.17alpha6版本-我们当前的alpha版本-如果您已经使用了，那么我们有一个问题...）
> 
> https://github.com/ankidroid/Anki-Android/releases

**Comment by 69asgard** [comment] 2023-11-25 15:45
AnkiDroid-2.17alpha6-arm64-v8a.apk

The version I used is this one.

**Comment by 69asgard** [comment] 2023-11-25 15:47
Sorry, I am not very skilled in this operation for github. If there is something wrong with the operation, please remind me.

**Comment by david-allison** [comment] 2023-11-25 16:24
Could you edit the first post to include debug information?

Settings - about - copy debug info

**Comment by 69asgard** [comment] 2023-11-25 16:26
AnkiDroid Version = 2.17alpha6 (393f61b229a26ec97eb13c83f0d1f09652f776c2)

Android Version = 10

ProductFlavor = full

Manufacturer = HUAWEI

Model = GLK-AL00

Hardware = kirin710

Webview User Agent = Mozilla/5.0 (Linux; Android 10; GLK-AL00 Build/HUAWEIGLK-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.105 Mobile Safari/537.36

ACRA UUID = 2f8fbb48-5d9e-4bbb-8aca-6b321ee60a00

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by david-allison** [comment] 2023-11-25 16:31
Thanks, is the issue still occurring?

**Comment by 69asgard** [comment] 2023-11-25 16:37
是的，报错问题在三分钟内发生了不下十五次。

Yes, the error occurred no less than fifteen times in three minutes.

![Screenshot_20231126_003337_com ichi2 anki_edit_1180877293076061](https://github.com/ankidroid/Anki-Android/assets/76214617/d863450f-ffa3-472b-8b7c-314781e0b6d7)

**Comment by 69asgard** [comment] 2023-11-25 16:41
如果查看卡片的频率不超过，两秒钟每一张，就很少报错。相反，如果几乎没有停歇的进入下一张卡片，极大概率会报错。

If you view cards at a frequency of no more than one card per two seconds, you will rarely encounter errors. On the other hand, if you enter the next card without stopping, there is a high probability of errors.

I should go to bed in this city. If there are any problems in the follow-up, I may recover later.

**Comment by 69asgard** [comment] 2023-11-25 16:42
In the first three months before the version, I can not remember exactly which version, but there is no such problem, I am very sure that the problem is caused by the version update.But I'm not sure exactly what caused it.

**Comment by david-allison** [comment] 2023-11-25 19:48
I can't reproduce this on my S21 yet.

**Comment by david-allison** [comment] 2023-12-09 23:40
Reproduced using the deck listed in: https://github.com/ankidroid/Anki-Android/issues/14920

**Comment by mikehardy** [comment] 2023-12-11 01:04
I believe this is a duplicate of #12946 and we have more information there, closing this so we can focus in one spot

**Closed** 2023-12-11 01:47 UTC
Labels: Reproduced, 2.17-alpha
