### ISSUE TITLE
Accurate new and review count

### ISSUE THREAD

**Issue by awes12** [ankidroid/Anki-Android#15303] opened 2024-01-22 09:13 UTC
(This may already be solved in the beta).

Currently, future buried cards are not included in the new and review count. It would be nice to have an accurate count of new and review cards for that day, taking buried cards into account (especially in the learning page).  
Ankiweb does this by showing the buried cards in gray (but only the modified count on the actual card page), which may be a good solution.

**Comment by user1823** [comment] 2024-01-22 11:17
- Duplicate of https://github.com/ankidroid/Anki-Android/issues/15186

**Comment by awes12** [comment] 2024-01-22 13:34
Not the same exact issue (I see the same when I click study), but a solution should fix my problem

**Comment by BrayanDSO** [comment] 2024-02-20 23:09
I'll be joining the issues

**Closed by BrayanDSO** 2024-02-20 23:09 UTC
