### ISSUE TITLE
MathJax displays differently in newest version

### ISSUE THREAD

**Issue by AlexApps99** [ankidroid/Anki-Android#9002] opened 2021-05-28 23:26 UTC
<details><summary>Screenshots</summary><br>

###### AnkiDroid:
![AnkiDroid](https://user-images.githubusercontent.com/30854646/120050212-b5914a00-c070-11eb-801b-0b6fb89577d2.jpg)
###### Anki Desktop (2.1.44):
![Anki Desktop](https://user-images.githubusercontent.com/30854646/120091254-886e9580-c15d-11eb-87bc-37d688ff8664.png)

</details>

###### Reproduction Steps

1. Create a card with LaTeX in this format: `\(\ce{Al^3+}\)`
2. Compare the difference between the old version of AnkiDroid/Desktop, and current version of AnkiDroid

###### Expected Result
Same appearance

###### Actual Result
New version looks all weird and spaced out

**Comment by mikehardy** [comment] 2021-05-29 02:41
Hi there! If you have some example card contents that would help. Mathjax is the preferred solution at this point, and we did move from mathjax2 to 3 with the new release, in case that's important

**Comment by AlexApps99** [comment] 2021-05-29 02:47
Example card content is the latex formula I included in the issue
description, on its own it should reproduce the issue

**Comment by david-allison-1** [comment] 2021-05-29 03:15
I did notice that moving from MathJax 2 to 3 has changed the spacing of some cards (when I was looking into the MathJax 3 slowdown issue), I didn't realise that this didn't match Anki Desktop.

I'm not at all familiar with MathJax, but I'll look into it if nobody else does in a reasonable time period. @AlexApps99 ping me here if nothing moves within 5 days and I'll have a deep dive.

----
**Diagnostics**

Firstly, could you provide sample images of the same formula from:

* Anki Desktop (latest)
* AnkiDroid (latest)
* AnkiDroid (2.14.6) download: https://github.com/ankidroid/Anki-Android/releases/download/v2.14.6/AnkiDroid-2.14.6.parallel.A.apk

If possible, use a formula where the differences are easily visible

It would also be ideal to obtain `card.html` for the two AnkiDroid instances, so we can compare. See: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by SpikyClip** [comment] 2021-05-29 03:45
Can confirm that this alignment issue is a problem with ankidroid 2.15.6 compared to anki desktop 2.1.22 (yea I know its outdated). In addition, the \color command bleeds through one character to the right (i.e. if you color a word in brackets, the right bracket will also be coloured. This is not an issue on desktop anki 2.1.22 and ankidroid 2.14.6.parallel. Attached are the screenshots, and the `card.html` files as txt.

[ankidroid_2.14.6.txt](https://github.com/ankidroid/Anki-Android/files/6564000/ankidroid_2.14.6.txt)
<img width="403" alt="anki_2 1 22" src="https://user-images.githubusercontent.com/74215773/120057140-2ee66800-c084-11eb-9607-4f956b384810.png">
![ankidroid_2 15 6](https://user-images.githubusercontent.com/74215773/120057141-2f7efe80-c084-11eb-892e-baea9df45e9a.jpg)
[ankidroid_2.15.6.txt](https://github.com/ankidroid/Anki-Android/files/6564001/ankidroid_2.15.6.txt)

**Comment by ShridharGoel** [comment] 2021-05-29 09:56
@SpikyClip The MathJax documentation mentions the change regarding `\color`. Here is the link: https://docs.mathjax.org/en/latest/input/tex/extensions/color.html

![image](https://user-images.githubusercontent.com/35566748/120065992-e6ce4200-c091-11eb-856d-294f42f03864.png)

**Comment by ShridharGoel** [comment] 2021-05-29 15:34
The MathJax documentation mentions the change regarding `\color`. Here is the link: https://docs.mathjax.org/en/latest/input/tex/extensions/color.html

![image](https://user-images.githubusercontent.com/35566748/120076054-6e7f7500-c0c1-11eb-9085-fbb38ac0a232.png)

**Comment by Arthur-Milchior** [comment] 2021-05-29 17:05
With 
```mathjax
\[lift(\color{red}{A} \Rightarrow \color{darkorange}{B}) = \frac{supp(\color{red}{A} \cup \color{darkorange}{B})}{supp(\color{red}{A}) \cdot supp(\color{darkorange}{B})}\]
```
current anki desktop shows:

![2021-05-29-185423_385x87_scrot](https://user-images.githubusercontent.com/357361/120078341-5bfc4000-c0af-11eb-93b5-03e16e5021d7.png)

I don't even understand what you means about alignment so I don't know whether there is an alignment problem.

It would help a lot if you could make screenshot that are actually identical as far as possible. That is, showing the same content, and with the same size, , because right now, even on your two ankidroid screenshot, I don't know what to compare, what changed because of the screen size and what changed because of the mathjax problem.

However, about coloring, it is now clear that it is not an ankidroid specific issues. I'd like to note that 2.1.22 used MathJax 2.  I don't think that comparing to old version of anki is very informative. In this case, this means I don't think we should touch it unless upstream does so (sorry @ShridharGoel as it seems your PR may be rejected). I understand that it's a pain for you, @SpikyClip and I hope that we can find other way to make things work. At least for coloring, we can uses the code provided by @ShridharGoel in #9006 in a card type. It may also be a pain for other users so we should document it. 

Also, you can export cards directly from the browser, it may be easier for us to debug if you exported a card and not its code, as there is no straightforward way to reimport the .txt file you sent us into anki

**Comment by mikehardy** [comment] 2021-05-29 21:08
not sure if @hgiesel is looking or has time but he was the mathjax master for our move to mathjax3

**Comment by david-allison-1** [comment] 2021-05-29 22:01
I don't think there's a problem in our implementation here. We match Anki Desktop, and MathJax has changed from v2 to v3. 

We should have informed users, and given them an upgrade path (as should have Anki), but I don't think this is a "bug/ecosystem compatibility issue".

**Comment by mikehardy** [comment] 2021-05-29 22:17
Agreed on all fronts, not great notice so the progress is messy but staying on old mathjax versions is also not an option. So it goes

**Comment by SpikyClip** [comment] 2021-05-30 01:29
> 
> 
> With
> 
> ```
> \[lift(\color{red}{A} \Rightarrow \color{darkorange}{B}) = \frac{supp(\color{red}{A} \cup \color{darkorange}{B})}{supp(\color{red}{A}) \cdot supp(\color{darkorange}{B})}\]
> ```
> 
> current anki desktop shows:
> 
> ![2021-05-29-185423_385x87_scrot](https://user-images.githubusercontent.com/357361/120078341-5bfc4000-c0af-11eb-93b5-03e16e5021d7.png)
> 
> I don't even understand what you means about alignment so I don't know whether there is an alignment problem.
> 
> It would help a lot if you could make screenshot that are actually identical as far as possible. That is, showing the same content, and with the same size, , because right now, even on your two ankidroid screenshot, I don't know what to compare, what changed because of the screen size and what changed because of the mathjax problem.
> 
> However, about coloring, it is now clear that it is not an ankidroid specific issues. I'd like to note that 2.1.22 used MathJax 2. I don't think that comparing to old version of anki is very informative. In this case, this means I don't think we should touch it unless upstream does so (sorry @ShridharGoel as it seems your PR may be rejected). I understand that it's a pain for you, @SpikyClip and I hope that we can find other way to make things work. At least for coloring, we can uses the code provided by @ShridharGoel in #9006 in a card type. It may also be a pain for other users so we should document it.
> 
> Also, you can export cards directly from the browser, it may be easier for us to debug if you exported a card and not its code, as there is no straightforward way to reimport the .txt file you sent us into anki

No problem, after looking at the two images it seems like the alignment is the same, its just a weird optical illusion to me that the coloured brackets appear closer to the words they are next to. As for the mathjax, I'll update the lines to the new mathjax 3 implementation. I don't have much reason to remain on the old anki versions anymore. Thanks for everyone's help!

**Comment by AlexApps99** [comment] 2021-05-30 03:09
Why was the issue closed?

**Comment by AlexApps99** [comment] 2021-05-30 03:13
I have already provided screenshots and example LaTeX (using default stylesheet and latex setup)
It is certainly not what the previous version of AnkiDroid or what Anki Desktop look like

**Comment by AlexApps99** [comment] 2021-05-30 03:14
I tried to install AnkiDroid.A from the link you gave me but it crashes every time I open it

**Comment by mikehardy** [comment] 2021-05-30 03:33
It was closed because of this assertion:

> I don't think there's a problem in our implementation here. We match Anki Desktop, and MathJax has changed from v2 to v3.

That implies there is no action item. I close issues when there is nothing actionable

**Comment by AlexApps99** [comment] 2021-05-30 03:35
It doesn't look the same on the latest Anki Desktop though?

**Comment by AlexApps99** [comment] 2021-05-30 03:41
Ok, I got the latest version of Anki, and the results still don't match with mobile
![image](https://user-images.githubusercontent.com/30854646/120091254-886e9580-c15d-11eb-87bc-37d688ff8664.png)

**Comment by Arthur-Milchior** [comment] 2021-05-30 09:52
Thank you for letting us know there is a difference between current version of anki desktop and ankidroid. That is indeed something that we can consider. If I understand correctly, the trouble is the differenc between the A and the g, right?

I insist, please, share your cards. Screenshots are nice. The field content is nice. But I REALLY want to have you card to be able to import them and see the difference - if any - myself. 

For example, if I don't have your card but only 
> \(\ce{Al^3+}\)

then I can't see for myself whether it depends on some css you added to your card, that would be activated only on condition of a small screen by example. Worst, it won't even reproduce your screenshot since there is an extra number.

**Comment by AlexApps99** [comment] 2021-05-30 10:01
Apologies, here it is:
https://filebin.net/w6b3ynktejznkfsg/CHE_Ions-20210530220027.apkg

**Comment by david-allison-1** [comment] 2021-05-31 05:09
What's the process for upgrading to a later version of MathJax? 

I've had a look: our font-size is slightly different, but fixing that doesn't fix the issues.

It appears that `em` causes different relative spacing between the two clients. 

We're on 3.1.2 on AnkiDroid/AnkiDesktop. Latest is 3.1.4, with 3.1.3 having 70 bugfixes, one of which may be relevant. 

https://github.com/mathjax/MathJax-src/releases/tag/3.1.4

**Comment by AlexApps99** [comment] 2021-05-31 05:12
Correct me if I'm wrong, but doesn't Anki use LaTeX, and not MathJax?

By that, I mean it converts to DVI, then to PNG, then displays it as a PNG (rather than displaying it directly as SVG or HTML)

**Comment by david-allison-1** [comment] 2021-05-31 05:21
`\( \)` is MathJax syntax. 

AnkiDroid doesn't natively support LaTeX, but if images are rendered on Anki Desktop, then they're synced and displayed.

**Comment by david-allison-1** [comment] 2021-05-31 14:32
Narrowed it down to the `chtml` renderer:

Change:

https://github.com/ankidroid/Anki-Android/blob/8eb2127a6f75fa738a85ccf356f5adae1ad8594f/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L2312

to:

`<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>  `  - fails

`<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>  ` - passes

**Comment by hgiesel** [comment] 2021-05-31 14:58
@david-allison-1 
However with `tex-svg.js` we had a whole other slew of issues, which is why it was [reverted](https://github.com/ankidroid/Anki-Android/pull/8147). Anki Desktop also uses `tex-chtml.js`.

**Comment by david-allison-1** [comment] 2021-05-31 15:04
@hgiesel 

Using `<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>` seems to work for the example listed in https://github.com/ankidroid/Anki-Android/issues/7915 

I'm not at all familiar with MathJax (although I'm getting better now). Is getting SVG rendering something that you'd have time to look at.

**Comment by david-allison-1** [comment] 2021-05-31 15:18
Likely related: https://github.com/mathjax/MathJax/issues/2583

**Comment by SpikyClip** [comment] 2021-06-03 05:32
> 
> 
> The MathJax documentation mentions the change regarding `\color`. Here is the link: https://docs.mathjax.org/en/latest/input/tex/extensions/color.html
> 
> ![image](https://user-images.githubusercontent.com/35566748/120076054-6e7f7500-c0c1-11eb-9085-fbb38ac0a232.png)

Just leaving this here in case others have similar issues. I got around to switching to the latex implementation of \color and realised there in fact is an alignment issue when you use two \color arguments next to each other, causing them to appear close when they should be spaced. The solution is to use \textcolor instead, which uses the \textcolor{color}{text} syntax, which makes it easy to convert using find and replace (same syntax as mathjax 2). This problem is documented [here](https://tex.stackexchange.com/questions/86039/what-is-the-difference-between-textcolor-and-color).

**Comment by david-allison-1** [comment] 2021-06-25 13:26
@hgiesel Were there other issues with the SVG MathJax renderer aside from the deprecation of `\color`?

From the linked issue, getting the HTML renderer working perfectly seems unlikely without serious effort, and moving to the SVG renderer should fix these issues.

**Comment by hgiesel** [comment] 2021-06-25 14:27
IIRC, the issue was not specifically the `\color` macro, but all [MathJax extensions](https://github.com/ankidroid/Anki-Android/tree/master/AnkiDroid/src/main/assets/mathjax/input/tex/extensions). Trying to use `\color` showed an error, that implied it couldn't find the extension file.

**Closed** 2024-10-11 22:42 UTC
Labels: Priority-High, Help Wanted, Keep Open, 2.15
