### ISSUE TITLE
The newer two strings from backend, `Discard current input?` and `Keep editing` have not yet been translated in the most languages

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15625] opened 2024-02-23 09:15 UTC
The newer two strings reused from backend by https://github.com/ankidroid/Anki-Android/pull/15597, `Discard current input?` and `Keep editing`, seem to be shown in English when `Language` settings of App is set to (maybe) any languages except for the following 5 languages:
   - Arabic
   - Greek
   - Hebrew
   - Simplified Chinese
   - Traditional Chinese

###### Samples
English (original)| Greek _(exception)_|Traditional Chinese _(exception)_
---|---|---|
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/edcd069a-7557-47c9-a283-76071681fd48" width="250px">|<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/a1703bd3-d051-4cf6-874b-5a1ed45052f1" width="250px">|<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/c72a833e-936e-4d1d-9ea0-aaec371c5b6c" width="250px">

Brazilian Portuguese | German | France
---|---|---|
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/b9837cb6-3576-4dbe-b592-ee4fb7c8d2f8" width="250px">|<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/54040f8b-eaf1-4c86-8302-e9c0b04c1d45" width="250px">|<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/f381c2d4-07e9-4c69-a9bb-e4d3feac77ab" width="250px">

###### Anything else you want to share?
Seemingly, the two strings have not yet been translated in the most languages even in the latest Anki Desktop (23.12.1).

- **Dec 25, 2023** 

	- The strings were added in Pontoon
	  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/10cb015f-bc3d-4a7b-bf01-e2d32219fda6" width="600px">https://i18n.ankiweb.net/ar/all-projects/all-resources/?string=25432
	  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/f4b04afc-b643-4734-bd7c-573c2dc71ce4" width="600px">https://i18n.ankiweb.net/ar/all-projects/all-resources/?string=25431

  - [Anki 23.12](https://github.com/ankitects/anki/releases/tag/23.12) was released, including the two strings created in https://github.com/ankitects/anki/pull/2903

- **Dec 28, 2023**

	- [Anki 23.12.1](https://github.com/ankitects/anki/releases/tag/23.12.1) was released, including the translations for the two strings in `adding.ftl` of 5 languages (ar, el, he, zh-CN, zh-TW) respectively: https://github.com/ankitects/anki/commit/08da442497765cf696f1493fbacf59bf53c58e5e

(The times above are probably the local time in Japan.)

###### Debug info

```
AnkiDroid Version = 2.17beta6 (c17fed63b97a464484f7ee465057ff251f54007f)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.165 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true
```

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment] 2024-02-23 12:25
The following is not directly related but I felt that it is not worth creating a separate issue:

In https://github.com/ankidroid/Anki-Android/pull/15597, an AnkiDroid-specific string was added for "Discard". It was noted that the backend doesn't export that string. But it actually does export that string, just not in the version currently used by AnkiDroid. You can refer to https://github.com/ankitects/anki/commit/dbfb46e6c89a43e3119644415ad6de314cdd7fc9.

**Comment by snowtimeglass** [comment] 2024-02-23 13:39
@user1823 Thanks you for letting me know. I didn't know them.

**Comment by mikehardy** [comment] 2024-02-23 13:44
In general:

1) we should use Anki Desktop strings whenever possible
2) where Anki Desktop does not have a translation, that should not be considered a bug in AnkiDroid, that should be considered a call to action to translate it upstream in Anki Desktop

Stated more generally: Anki Desktop should be the authoritative first source for translations whenever possible and we should increase our effort + focus our effort on improving translations there so whole ecosystem benefits

As such, this issue is a "won't fix" / "upstream issue" in my opinion

**Closed** 2024-02-23 19:00 UTC

**Comment by dae** [comment] 2024-02-25 01:03
It should be fairly rare that the desktop lacks a translation. The standard Qt dialog box buttons are already translated, so ok/cancel/discard/abort/etc may not all have translations, but pretty much everything else does (with the exception of strings that were either deemed to rare/obscure to be worth translating, and strings where we forgot to).

**Comment by user1823** [comment] 2024-02-25 02:24
I guess the issue is that there wasn't enough time for the translators to translate the new strings before the release (according to the timeline shared above).
