### ISSUE TITLE
[Issue] 2.15 reviewing is significantly slower 

### ISSUE THREAD

**Issue by AlexeyMalafeev** [ankidroid/Anki-Android#8948] opened 2021-05-25 21:04 UTC
Reviewing cards in 2.15 is significantly slower than in the previous release. When I tap show answer (I use a gesture for that - tap on screen center), there is an approximately half a second delay before the answer is actually shown. There was no such delay in the previous version. Moreover, when I want to see the answer, the answer buttons are shown first, then (after the delay) the answer. There is no point in seeing the answer buttons before the answer. 

AnkiDroid Version = 2.15.0

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi Note 8 Pro

Hardware = mt6785

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi Note 8 Pro Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = e950621d-9c03-4e0c-ab0d-bdc7221268fd

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment] 2021-05-25 21:13
*Probably* a duplicate of #8927, *maybe* fixed by #8946 - @AlexeyMalafeev I'm going to close this based on that idea but please understand we can re-open with the click of a button for more triage - I'm wrapping up a 2.15.1 release to fix all the things people noticed with the big 2.15.0. Can you wait for that and re-test when it comes out please? Should be just a couple more hours

**Closed by mikehardy** 2021-05-25 21:13 UTC
