### ISSUE TITLE
Keyboard Shortcut for Mark Note Does Not Work, Please revert to "*"

### ISSUE THREAD

**Issue by ji-zh** [ankidroid/Anki-Android#7954] opened 2020-12-25 23:09 UTC
Either it does not work or it is hard to understand.

The "Mark Note" Keyboard Shortcut stopped working for me. 
It was just "*" until maybe a few months back. According to the documentation
https://docs.ankidroid.org/

the hot key for Mark Note is now "\*".

What does "\*" mean? I tried the sequential combination of "\" and "*", it still did not work. 

Could you revert it back to "*" ?

**Comment by david-allison-1** [comment] 2020-12-26 02:57
Hi, thanks for the bug report. This is a duplicate of #7840

It's on my "very soon" TODO list (probably Sunday) and should be fixed in an alpha

**Closed by david-allison-1** 2020-12-26 02:57 UTC
