### ISSUE TITLE
[BUG]: Anki 2.16 [full] freezes when saving to the db and sometimes crashes when using a path like "/storage/emulated/0/Ankidroid"

### ISSUE THREAD

**Issue by MagTun** [ankidroid/Anki-Android#14314] opened 2023-08-26 20:14 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Install any arm64-v8a 2.16 apk from github (cf the one I tried below)
Set the Anki path to "/storage/emulated/0/Ankidroid" 
Review several cards, edit them, and create new ones... 

### Expected behaviour

There should be no delay when the changes are saved to the DB (ex when pressing the answer buttons, when saving the edit of a new card, when saving a new card). 

### Actual behaviour

Random delays (from a couple of seconds to 20 or 30 secondes) and sometimes the app crashes. 

### Debug info

```text
AnkiDroid Version = 2.16.3

Android Version = 13

ProductFlavor = full

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Redmi 7A Build/TQ3A.230705.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36

ACRA UUID = 0066c12e-dc67-4a9b-a157-d75c60fde9a9

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

I have had the same problem with AnkiDroid-2.16.0beta1-arm64-v8a.apk, AnkiDroid-2.16.1-arm64-v8a.apk, AnkiDroid-2.16.2-arm64-v8a.apk, AnkiDroid-2.16.3-arm64-v8a.apk.
I have these random delays with a "dummy" deck (50 card of only 2 word using the basic note type) (to eliminate any possible delay coming from custom .js)
I have tried the app [Android System WebView Beta](https://play.google.com/store/apps/details?id=com.google.android.webview.beta&hl=en&gl=US) but still got the delays.

When I installed AnkiDroid-2.16.3-arm64-v8a.apk I did have the delays for the first 2 days and then they came back.

Cleaning the db doesn't solve the bug (I have cleaned the db more then 10 times per day)

Closing the review, and even Anki (and the other apps) and restarting the deck/Anki doesn't solve the delays. 

The only thing that fixes this bug is to set Anki path to  /storage/emulated/0/Android/data/com.ichi2.anki (not delay at all for more than a week now)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by MagTun** [comment] 2023-08-30 12:37
I have tried again with 2.16.4 and the latest alpha version (2.17alpha1) : same problem (Anki still freezes) and same "solution" (using "/storage/emulated/0/Android/data/com.ichi2.anki " instead of  "/storage/emulated/0/Ankidroid")



**The new debug:**

AnkiDroid Version = 2.17alpha1 (e817d891c70a05b86aa10690f5a5d5e2b1c7ad2d)

Android Version = 13

ProductFlavor = full

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Redmi 7A Build/TQ3A.230705.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36

ACRA UUID = 0066c12e-dc67-4a9b-a157-d75c60fde9a9

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by voidplayer** [comment] 2023-08-31 07:13
I think im having the same issue and started happening on the same hardwarde in android version 12

Same version of ankidroid didnt freeze in version 11

Its not a big deal, i just close it and reopen it and nothing is lost, i thought id share my thoughts on when it started happening

**Comment by BrayanDSO** [comment] 2024-05-11 10:59
I'm going to close this as can't reproduce

**Closed by BrayanDSO** 2024-05-11 10:59 UTC
Labels: Bug, Needs Triage, 2.16
