### ISSUE TITLE
moving the deck operation from floating button to topbar, and keep floating button only to create cards. 

### ISSUE THREAD

**Issue by jainishrpandya** [ankidroid/Anki-Android#16103] opened 2024-04-05 09:27 UTC
**Is your feature request related to a problem? Please describe.**
I have been using Ankidroid for many years and one thing that always caught my eye is when I press the floating add button on the deck picker home screen. it shows me 4 options.

* get shared deck
* create filtered deck
* create deck
* create card

and then I have to press add to create the card. 
that makes the friction to two clicks. and over 90% of the time I use this button to just create the card.

**Describe the solution you'd like**
So my suggestion would be to reserve the floating button only to create the card. That would reduce the friction to one click and move the deck-related operations to the topbar with the spinner menu plus button beside the search button on the top bar.
so it will be easily accessible and friction will be the same as before. 2 clicks. and the main operation of the application's friction would be reduced.

**Additional context**
<img src="https://github.com/ankidroid/Anki-Android/assets/69842037/c405be7a-2211-4afb-8f04-2e4953fcca1d" alt="image" width="400px" />

**Comment by BrayanDSO** [comment] 2024-04-05 13:30
This is a literal duplicate of an issue that *you* created *only two days ago* (#16082), so this shouldn't be a mistake.

If you disagree about it being closed, say it there. DON'T create a duplicate just for the sake of it.

**Closed by BrayanDSO** 2024-04-05 13:30 UTC

**Comment by jainishrpandya** [comment] 2024-04-05 13:39
@BrayanDSO. Sincere apologies from my side. Unknowingly i just forgot that have created an issue before. It would not happen again. Thanks you. Pardon me.
