### ISSUE TITLE
[Bug] Answer buttons flash and dissappear

### ISSUE THREAD

**Issue by clay53** [ankidroid/Anki-Android#8032] opened 2021-01-21 04:36 UTC
###### Reproduction Steps

1. Start study
2. Hit show answer

###### Expected Result
Answer buttons show up and are there to tap. 

###### Actual Result
Answer buttons flash and dissappear but are still clickable.
![Screenshot_20210120-232911_AnkiDroid.jpg](https://user-images.githubusercontent.com/16981283/105280501-eb309e80-5b77-11eb-89de-0b4183b54429.jpg)[]()

###### Debug info
AnkiDroid Version = 2.14.3

Android Version = 8.0.0

ACRA UUID = ee4c502e-010b-4b90-8362-79f5c0f27e51

Scheduler = std2

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment] 2021-01-21 05:00
Duplicate of #7369.

If you could do anything to help us pinpoint the alpha where the bug started occurring (see linked issue), please let us know.

**Closed by david-allison-1** 2021-01-21 05:00 UTC
