### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by kami-leo** [ankidroid/Anki-Android#12402] opened 2022-09-14 23:07 UTC
Hello i am facing syncing problem and i am unable to login in ankidroid
ankidroid reports "you are currently offline" even though mkbile is connected to the mobile data is turned on.
Actually only the version of anki present in Play store can be installed. And all the versions are not being installed, and a message"app is not installed appears" in my Android phone having android version 11.
Plz help me fixing this problem. My whole week has been wasted away in fixing this problem.

**Comment by david-allison** [comment] 2022-09-15 01:19
Duplicate of #12402

**Closed by david-allison** 2022-09-15 01:19 UTC
Labels: Duplicate
