### ISSUE TITLE
[BUG]: Can't select deck in statistics screen

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16459] opened 2024-05-23 06:57 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Open stats screen
2. Select `collection`
3. Try switching back to `deck`

### Expected behaviour

switches back to `deck`

### Actual behaviour

Clicking there doesn't work most of the times. To switch back to `deck` it sometimes take 3-4 clicks. This doesn't happen anywhere else in the same screen.

### Debug info

```text
AnkiDroid Version = 2.18.0 (464cf290cc77c3f2c562cb03b408b78a13be261b)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.180 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-08-04 00:58
Could you post a video?

**Comment by brishtibheja** [comment] 2024-08-04 03:46
Here is:
https://github.com/user-attachments/assets/995e5e06-6921-4581-b698-04fd7500ca70

**Comment by snowtimeglass** [comment] 2024-08-07 12:08
Reproduced in 2.19alpha10 and in 2.16.1 (with the new backend enabled) on my device.

```
AnkiDroid Version = 2.19alpha10 (4afa7ec41ecc3efe7dd719db46c51cb09560292f)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36

ACRA UUID = 5e59349c-ede4-4942-91b7-199dcf1342c0

FSRS Enabled = false

Crash Reports Enabled = true
```
It doesn't seem to occur when the screen is in landscape mode.

![image](https://github.com/user-attachments/assets/e2525fc7-7a77-4d7e-b3ab-014bb415f4fe)

**Comment by brishtibheja** [comment] 2024-11-05 12:49
Keep open. The radio button is actually less responsive in the latest 2.19.1 ver. Instead of a few taps now it requires a few dozen taps to make it work.

**Comment by SttApollo** [comment] 2024-11-23 22:55
Can you assign this to me?

**Comment by BrayanDSO** [comment] 2024-11-23 23:12
Can't reproduce. Probably an issue with the position and size of the radio button. If this was serious and widespread, more people would have complained. 

As that screen comes from the desktop version, please create a report in their repo or in the forums so someone can make something minimally good

**Closed by BrayanDSO** 2024-11-23 23:12 UTC
Labels: Priority-High, Bug, Statistics, Help Wanted, Needs Triage
