### ISSUE TITLE
Since Update - "Collection not opened" error

### ISSUE THREAD

**Issue by ayokev** [ankidroid/Anki-Android#3908] opened 2015-11-30 23:15 UTC
Since the last update of Ankidroid, I can't open any collections I've had previously. I can't even do anything besides stare at the screen since the error interface takes up the whole screen. I tried the several options that it suggests like checking the database, restoring from backup, full sync from server, and delete collection and create new one. The only thing that kind of "works" is the last option, which is to delete the current collection (which I actually don't have) and to start a new one. With this option the error interface goes away and I can get shared decks. The problem arises again when I try to sync. This is a problem for me since some of the decks I have in my collection are no longer available via shared decks and I'd like to be able to have them on my phone. Anyway, the gist of it is that I can't access my personal collection.

**Comment by timrae** [comment] 2015-11-30 23:29
Probably a duplicate of #3905, you can either downgrade to version 2.4.4 or wait a day or two for a fix.

https://github.com/ankidroid/Anki-Android/releases/tag/v2.4.4

**Closed by timrae** 2015-11-30 23:29 UTC
