### ISSUE TITLE
"app bar buttons" setting is unresponsive

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#5827] opened 2020-03-17 16:15 UTC
###### Reproduction Steps

1. Tap Settings -> Reviewing -> App bar buttons
2.  No response

###### Expected Result
I remember this used to open a menu to select which buttons are shown in the app bar (and app bar menu) while reviewing. Examples of the buttons were toggle mark, suspend, whiteboard, etc. There were settings to always show certain buttons or to show them if space was available, or not show them at all 

###### Actual Result
No response when tapping that setting

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.10alpha50

Android Version = 7.0

ACRA UUID = fd9d9e7c-9e17-4df3-810e-43af4dc764e2

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by sudomain** [comment] 2020-03-17 16:28
Also, I didn't know if these small things about the settings menu warrented separate issues:
1.  the "settings" button opens a menu called "preferences" (minor ui quirk)
2. pressing the Back button while in the "settings"/"preferences" menu will exit the app. This is different from if the user presses Back while in one of the other screens (e.g. decks, card browser, statistics, and reviewing) they will be returned to the decks screen.

**Comment by david-allison-1** [comment] 2020-03-17 16:47
Confirmed. Regression in 2.10alpha50

**Comment by david-allison-1** [comment] 2020-03-17 17:10
Cause: 

https://github.com/ankidroid/Anki-Android/blob/e0ee33cb6a1f69fd125e086b61573dc2a11fa1ac/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java#L181 - reverting fixes the screen.

Added in https://github.com/ankidroid/Anki-Android/commit/e0ee33cb6a1f69fd125e086b61573dc2a11fa1ac fixing #5599

Pinging: @Arthur-Milchior 

Could this commit also be the cause of 

> pressing the Back button while in the "settings"/"preferences" menu will exit the app. This is different from if the user presses Back while in one of the other screens (e.g. decks, card browser, statistics, and reviewing) they will be returned to the decks screen.

Or should I keep looking?

**Comment by mikehardy** [comment] 2020-03-17 22:18
They are likely the same root cause - interestingly (?) that PR was intended to give us a few Intent objects that were *more* expressive (and ideally less error prone). Perhaps IntentTop either has the wrong intent flags in general, or the wrong IntentNNN object was chosen for that particular spot? 🤔

**Comment by sudomain** [comment] 2020-03-18 17:21
Maybe this is known already, but also affected are the custom sync server and advanced statistics setting.

**Comment by mikehardy** [comment] 2020-03-18 18:08
Yeah, it was a global change of style, so if it's got a problem in one spot, probably all spots. Big thanks for being on alphas and diligently reporting this stuff - it really helps. I imagine we'll have it fixed pretty quickly until then alpha49 might be the ticket for you

**Comment by mikehardy** [comment] 2020-03-20 00:32
@Arthur-Milchior do you have any time to look at this? I'm just curious for timing, I can potentially revert if it will be a while, or if you have a fix brewing I can wait

**Comment by Arthur-Milchior** [comment] 2020-03-20 14:42
I'd assume you'll just revert as indicated by @david-allison-1. I'll look about how to fix the original problem at some future point in time.

**Comment by mikehardy** [comment] 2020-03-20 14:46
Okay - I love progress (even if it requires follow-on work) so reverting pains me :-), but is the best path sometimes. I still like the original idea, and I'm still working through the rest of the stack of PRs as I get time - we're averaging 1.5/day right now (!) so it's still a matter of time but not through any lack of effort. Cheers @Arthur-Milchior

**Comment by mikehardy** [comment] 2020-03-20 20:10
This was reverted just now, released with revert as 2.10alpha53

**Closed by mikehardy** 2020-03-20 20:10 UTC
