### ISSUE TITLE
Does the header of navigation drawer keep pace with the new icon and the splash screen?

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4255] opened 2016-04-29 13:11 UTC
The header of navigation drawer reminds me of the old icon of AnkiDroid.
Does it keep pace with the new icon and the splash screen?

**Comment by timrae** [comment] 2016-04-29 13:16
Personally I like it and think they work well together. As always though, you or anyone else are welcome to submit an alternative design. 

Closing as not a bug report or enhancement request. General discussions like this are better suited to the forum.

**Closed by timrae** 2016-04-29 13:16 UTC

**Comment by snowtimeglass** [comment] 2016-04-29 13:27
I understand. Thank you.
