### ISSUE TITLE
Merging cards from card types

### ISSUE THREAD

**Issue by Mornon** [ankidroid/Anki-Android#4747] opened 2017-12-12 14:02 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

Not sure why, maybe due do reinstallation(s), I have three different "Basic (and reversed card)" card types, each with some (but different among each other) cards.

I was trying to find a way to merge them all, so to have just one "Basic (and reversed card)", but up till now I was unable to find a way; is it possible?

![20171212 145923](https://user-images.githubusercontent.com/21358808/33888431-55cba99c-df4d-11e7-8c0a-e5b5468f2b60.png)

**Comment by mikehardy** [comment] 2017-12-14 21:04
This is possible on the desktop at least, someone posted a step by step for how to do it there, and another user reported success with the method.  https://www.reddit.com/r/Anki/comments/3ydz67/is_there_a_way_to_merge_two_card_types_togeter/

In AnkiDroid you could use the Card Browser to pick each card and one by one change their type but that would of course be incredibly tedious. There does not appear to be support for filter by card type in the Card Browser, or multi-select + change-all-at-once, so this looks like a desktop task

**Comment by timrae** [comment] 2017-12-14 22:59
@mikehardy 
Yes, it's on our list of "help wanted" issues ;)

So I'll close this as: Duplicate of #2339

**Closed by timrae** 2017-12-14 22:59 UTC
