### ISSUE TITLE
[Bug] After the language is switched from Simplified Chinese to English, the pending review time on the main page is still in Simplified Chinese.

### ISSUE THREAD

**Issue by zkl-ai** [ankidroid/Anki-Android#10019] opened 2021-12-23 08:02 UTC
###### Reproduction Steps

1. Click setting
2. Click AnkiDroid General settings
3. Change language from Chinese to English

###### original 
![image](https://user-images.githubusercontent.com/72965042/147207699-7ef3ef6b-143b-484f-aeb5-ed8fd79322fb.png)

###### Expected Result
After the language is switched from Simplified Chinese to English, the pending review time on the main page should be in English.
###### Actual Result

![image](https://user-images.githubusercontent.com/72965042/147207591-a91de2a8-2b64-4762-879f-2291286c6100.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment] 2021-12-23 12:49
Hi, thanks for the report, I believe this is a duplicate of https://github.com/ankidroid/Anki-Android/issues/8865

If I'm mistaken, please let me know and I'll reopen it.

**Closed by david-allison-1** 2021-12-23 12:49 UTC
