### ISSUE TITLE
since update anki no longer works

### ISSUE THREAD

**Issue by Poppyt** [ankidroid/Anki-Android#3907] opened 2015-11-30 22:42 UTC
Collection not opened error. I went through ALL the options, even deleting, uninstalling and reinstalling. Never going to auto update again

Android latest update is used. Cannot access ankidroid interface since error takes up entire screen

**Comment by ayokev** [comment] 2015-11-30 23:10
This is happening to me too. I can't even sync with Anki's desktop program. Furthermore I tried manually exporting a deck from my desktop, which can still open my collections, as an .apkg but that didn't work either.

**Comment by timrae** [comment] 2015-11-30 23:29
Probably a duplicate of #3905, you can either downgrade to version 2.4.4 or wait a day or two for a fix.

https://github.com/ankidroid/Anki-Android/releases/tag/v2.4.4

**Comment by timrae** [comment] 2015-12-01 05:45
Should be fixed in 2.5.1, thanks for reporting

**Closed by timrae** 2015-12-01 05:45 UTC
Labels: duplicate
