### ISSUE TITLE
Feature request: reviewing with turned off screen

### ISSUE THREAD

**Issue by p4nix** [ankidroid/Anki-Android#6353] opened 2020-06-04 09:41 UTC
A lot of people have cards that do not actually require you to see the screen. This especially applies to basic q&a cards, cloze cards and audio language learning cards.
<hr>

It would be a nice option to be able to review those cards and grade them via:

- a bluetooth controller
- bluetooth audio volume controls
- volume controls of the device

while the screen is turned off and get the questions and answers read through the TTS engine (without the requirement of using tags).
<hr>

I'm not myself a developer, but here are some thoughts about the additional requirements this may have:
- ideally, be able to turn on and off this mode via the settings. Some people might not like this option as they don't want to accidentally review cards when they turned off their screen without exiting AnkiDroid.
 -> also, this could automatically turn off the auto-answer mode and vice versa, as they might lead to interesting and dangerous combinations ;)
- define an option to either white list or black list cards which can be reviewed in this mode, probably based on a tag. Those tags should ideally be defined by the user rather than hardcoded.
- add an option to ignore cards with MathJax/images/other content not suitable for turned off screens, which can be overwritten by the whitelist tag.
- for cards including sounds, add an option to not pass the question text through the TTS engine as only the audio might be needed.

**Comment by david-allison-1** [comment] 2020-06-04 09:57
Duplicate of #5112, could you copy the comment over? It'd be really useful as a spec.

**Closed by david-allison-1** 2020-06-04 09:57 UTC

**Comment by mikehardy** [comment] 2020-06-04 14:55
Getting mobile devices to consistently do things while the screen is off is not easy, power management is fragmented in the ecosystem
I closed the other one and have commented negatively on "screen off" functionality before
I'd encourage someone to use the API if they want to do this, but not put it in core
