### ISSUE TITLE
[BUG]: Despite Black Night Theme, New Finished Deck Screen is Dark, not Black

### ISSUE THREAD

**Issue by tdnzr** [ankidroid/Anki-Android#15674] opened 2024-02-26 11:46 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

In AnkiDroid 2.17, after finishing a deck, the "deck finished" screen has a Dark background even though my AnkiDroid appearance is set to Black.

### Expected behaviour

Before AnkiDroid 2.17, after finishing a deck, the "deck finished" screen used to be Black.

### Actual behaviour

Now it's Dark.

### Debug info

```text
Unnecessary.
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment] 2024-02-26 14:49
May be a duplicate of https://github.com/ankidroid/Anki-Android/issues/15322

**Comment by tdnzr** [comment] 2024-02-26 15:32
> May be a duplicate of #15322

Yup, looks like a duplicate. I unfortunately didn't find it when searching Github issues for "Black" and "Dark".

One bit of info I can contribute is that this problem is new in v2.17 and presumably stems from the introduction of Anki desktop code into AnkiDroid. As in, the incorrect background color coincides with AnkiDroid's congrats screen changing from how it looked like in v2.16, to the new congrats screen which borrows from the desktop version (incl. wrong background color and more verbose text).

**Closed** 2024-02-26 16:04 UTC
Labels: Bug, Needs Triage
