### ISSUE TITLE
[BUG]: ANKIDROID CRASHES WHEN USING TAGS

### ISSUE THREAD

**Issue by ZucuPro** [ankidroid/Anki-Android#16509] opened 2024-05-30 18:57 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Since last update I cant filter any card by tags or even clic on them, the app just keep crashing
Help please

https://github.com/ankidroid/Anki-Android/assets/171284652/34c4991c-4a8d-4ce8-afa4-d46fbaae181a

### Expected behaviour

.

### Actual behaviour

.

### Debug info

```text
AnkiDroid Version = 2.18.2 (f624ca684f2bee10203c67ed4f801aa4c5423b95)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-S918B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S918B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36

ACRA UUID = bfc01bcd-11aa-4474-aac9-75febd7a2a9b

FSRS Enabled = false

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by NameLessGO** [comment] 2024-05-30 21:17
Debug info is a necessary information for developers, please add it

> Open the navigation drawer by tapping the button on the top left of the screen

> Tap "Settings"

> Tap "About"

> Tap the "Copy debug info" button at the bottom (which copies "debug info" to the clipboard)

> If filling out the bug report on your mobile device, paste the contents of the clipboard directly to the issue. Alternatively, you can paste the contents of the clipboard into a new email, send it to yourself, then copy and paste that into the bug report from your computer.

-----

Try  Options (3 vertical dots) > Check > Check Database to clean unused tags and see if that helps

**Comment by Abhishekcmd** [comment] 2024-05-31 03:48
Yes even I faced a similar issue

**Comment by E0697** [comment] 2024-06-01 09:12
ADB Logcat:
'''
06-01 12:08:34.261  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{c8f6497 #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-3m28s357ms READY}
06-01 12:08:34.353  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{c8f6497 #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-3m28s449ms READY}
06-01 12:08:35.005  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{c8f6497 #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-3m29s101ms READY}
06-01 12:08:35.022  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{c8f6497 #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-3m29s117ms READY}
06-01 12:08:35.824 26109 26109 E com.ichi2.anki: Not starting debugger since process cannot load the jdwp agent.
06-01 12:08:35.867  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{c8f6497 #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-3m29s963ms READY}
06-01 12:08:35.872  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{c8f6497 #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-3m29s968ms READY}
06-01 12:08:36.466  1794  5439 E JobScheduler.Concurrency: Error executing JobStatus{c06d758 #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-7ms READY}
06-01 12:08:36.473  1794  1842 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-5ms READY}
06-01 12:08:37.315  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-848ms READY}
06-01 12:08:39.538 26109 26109 E AndroidRuntime: Process: com.ichi2.anki, PID: 26109
06-01 12:08:39.538 26109 26109 E AndroidRuntime: 	at com.ichi2.anki.dialogs.tags.TagsFile.<init>(SourceFile:7)
06-01 12:08:39.538 26109 26109 E AndroidRuntime: 	at com.ichi2.anki.dialogs.tags.TagsDialog.withArguments(SourceFile:3)
06-01 12:08:39.538 26109 26109 E AndroidRuntime: 	at com.ichi2.anki.dialogs.tags.TagsDialog.withArguments(SourceFile:1)
06-01 12:08:39.538 26109 26109 E AndroidRuntime: 	at com.ichi2.anki.AbstractFlashcardViewer.showTagsDialog$AnkiDroid_fullRelease(SourceFile:56)
06-01 12:08:39.538 26109 26109 E AndroidRuntime: 	at com.ichi2.anki.Reviewer.onOptionsItemSelected(SourceFile:28)
06-01 12:08:39.540 26109 26109 E ACRA    : ACRA caught a RuntimeException for com.ichi2.anki
06-01 12:08:39.540 26109 26109 E ACRA    : 	at com.ichi2.anki.dialogs.tags.TagsFile.<init>(SourceFile:7)
06-01 12:08:39.540 26109 26109 E ACRA    : 	at com.ichi2.anki.dialogs.tags.TagsDialog.withArguments(SourceFile:3)
06-01 12:08:39.540 26109 26109 E ACRA    : 	at com.ichi2.anki.dialogs.tags.TagsDialog.withArguments(SourceFile:1)
06-01 12:08:39.540 26109 26109 E ACRA    : 	at com.ichi2.anki.AbstractFlashcardViewer.showTagsDialog$AnkiDroid_fullRelease(SourceFile:56)
06-01 12:08:39.540 26109 26109 E ACRA    : 	at com.ichi2.anki.Reviewer.onOptionsItemSelected(SourceFile:28)
06-01 12:08:39.819  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-3s352ms READY}
06-01 12:08:39.833  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-3s366ms READY}
06-01 12:08:39.837  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-3s370ms READY}
06-01 12:08:40.674  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-4s207ms READY}
06-01 12:08:41.218  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-4s751ms READY}
06-01 12:08:42.024  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-5s556ms READY}
06-01 12:08:42.433  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-5s966ms READY}
06-01 12:10:08.979  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m32s512ms READY}
06-01 12:10:09.077  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m32s610ms READY}
06-01 12:10:09.757  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m33s289ms READY}
06-01 12:10:09.770  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m33s302ms READY}
06-01 12:10:11.288  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m34s821ms READY}
06-01 12:10:11.924  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m35s456ms READY}
06-01 12:10:30.776  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m54s308ms READY}
06-01 12:10:31.118  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m54s650ms READY}
06-01 12:10:31.621  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m55s153ms READY}
06-01 12:10:32.276  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m55s808ms READY}
06-01 12:10:34.304  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m57s836ms READY}
06-01 12:10:34.698  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-1m58s231ms READY}
06-01 12:10:40.219  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m3s752ms READY}
06-01 12:10:40.635  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m4s168ms READY}
06-01 12:10:40.799  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m4s332ms READY}
06-01 12:10:40.816  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m4s348ms READY}
06-01 12:10:41.244  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m4s776ms READY}
06-01 12:10:41.794  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m5s326ms READY}
06-01 12:10:41.927  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m5s460ms READY}
06-01 12:10:42.960  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m6s492ms READY}
06-01 12:10:43.358  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m6s891ms READY}
06-01 12:10:43.501  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m7s33ms READY}
06-01 12:10:43.511  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m7s43ms READY}
06-01 12:10:43.972  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m7s505ms READY}
06-01 12:10:44.372  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m7s905ms READY}
06-01 12:10:44.487  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m8s20ms READY}
06-01 12:10:44.514  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m8s46ms READY}
06-01 12:10:56.318  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m19s850ms READY}
06-01 12:10:56.787  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m20s320ms READY}
06-01 12:10:56.975  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m20s508ms READY}
06-01 12:10:56.994  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m20s527ms READY}
06-01 12:10:57.184  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m20s717ms READY}
06-01 12:10:57.680  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m21s213ms READY}
06-01 12:10:57.814  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m21s347ms READY}
06-01 12:10:57.823  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m21s356ms READY}
06-01 12:11:00.968  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m24s501ms READY}
06-01 12:11:01.355  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m24s888ms READY}
06-01 12:11:01.496  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m25s29ms READY}
06-01 12:11:01.516  1794  2113 E JobScheduler.Concurrency: Error executing JobStatus{e34a6ed #u0a486/0 com.ichi2.anki/org.acra.sender.JobSenderService u=0 s=10486 TIME=none:-2m25s48ms READY}
'''

**Comment by david-allison** [comment] 2024-06-01 09:35
Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/16490

* https://github.com/ankidroid/Anki-Android/issues/16490

**Closed** 2024-06-01 09:35 UTC
Labels: Bug, Needs Triage
