### ISSUE TITLE
Bug error

### ISSUE THREAD

**Issue by william301** [ankidroid/Anki-Android#4440] opened 2016-09-30 05:30 UTC
Hello, I have a problem when I start a Custom study session.

All my decks are fine, but when I open a custom study session and press for the answer the following error appears:

'An error ocurred while accessing your collection. It may have been caused by a harmless bug, or there may be a problem with it.

Try running check database, or restoring from backup by pressing the 'options' button. If you continue to see this message, please file a bug report. '

I already tried the 2 first options but it makes no difference. The bug message appears again and again!

Please someone help me with this issue. I need my custom study session working as usual. Thanks in advance!

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by timrae** [comment] 2016-09-30 05:34
Hi please fill in the form template above. Especially the "debug info"

**Comment by william301** [comment] 2016-09-30 06:13
Research

Enter an [ x ] character to confirm the points below:

[ x] I have read the support page and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the manual and the FAQ and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

Reproduction Steps

1. I open custom study session
Expected Result
I want it working normally, but when I press answer the bug error appears.

Actual Result
I press for the answer on a custom study session and a bug message appears.

Debug info
AnkiDroid Version = 2.4.3

Android Version = 5.1.1

ACRA UUID = 884619d7-c992-4bb3-b04e-15d32f22502b

**Comment by william301** [comment] 2016-09-30 06:16
Thanks Tim :) hope you can give me a hand with this. Really need my custom study working

**Comment by timrae** [comment] 2016-09-30 06:32
java.lang.RuntimeException: org.json.JSONException: No value for separate
at com.ichi2.libanki.Sched._newConf(Sched.java:1774)
at com.ichi2.libanki.Sched._lrnConf(Sched.java:1005)
at com.ichi2.libanki.Sched.answerButtons(Sched.java:240)
at com.ichi2.anki.AbstractFlashcardViewer.showEaseButtons(AbstractFlashcardViewer.java:1613)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardAnswer(AbstractFlashcardViewer.java:2146)
at com.ichi2.anki.AbstractFlashcardViewer$5.onClick(AbstractFlashcardViewer.java:414)
at android.view.View.performClick(View.java:5246)
at android.view.View$PerformClick.run(View.java:21256)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6963)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: org.json.JSONException: No value for separate
at org.json.JSONObject.get(JSONObject.java:389)
at org.json.JSONObject.getBoolean(JSONObject.java:410)
at com.ichi2.libanki.Sched._newConf(Sched.java:1769)
... 15 more
org.json.JSONException: No value for separate
at org.json.JSONObject.get(JSONObject.java:389)
at org.json.JSONObject.getBoolean(JSONObject.java:410)
at com.ichi2.libanki.Sched._newConf(Sched.java:1769)
at com.ichi2.libanki.Sched._lrnConf(Sched.java:1005)
at com.ichi2.libanki.Sched.answerButtons(Sched.java:240)
at com.ichi2.anki.AbstractFlashcardViewer.showEaseButtons(AbstractFlashcardViewer.java:1613)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardAnswer(AbstractFlashcardViewer.java:2146)
at com.ichi2.anki.AbstractFlashcardViewer$5.onClick(AbstractFlashcardViewer.java:414)
at android.view.View.performClick(View.java:5246)
at android.view.View$PerformClick.run(View.java:21256)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6963)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by timrae** [comment] 2016-09-30 06:32
You can try deleting the options group for that deck and recreating it. The options group is corrupt as it's missing the 'separate' field

**Comment by hssm** [comment] 2016-09-30 06:34
This is another case of https://github.com/ankidroid/Anki-Android/issues/3447

Do you use Anki on anything other than AnkiDroid? I have myself convinced that it's impossible to trigger this state from within AnkiDroid and it's coming from somewhere else.

**Comment by william301** [comment] 2016-09-30 06:50
@timrae: how can I delete the options group for the custom study deck?

All of my other decks are fine. It only happens when I start a custom study session. 

@hssm: I use AnkiDroid. Any suggestion?

**Comment by hssm** [comment] 2016-09-30 06:57
Custom study decks pull options from parent decks as each card shows up. The issue would reside in the options group used by the original deck of the first card that appears.

Can you export your collection and send it to me so I can try to reproduce it?

**Comment by william301** [comment] 2016-09-30 07:12
@hssm: sure, many thanks. How can I export it to you? Email?

**Comment by hssm** [comment] 2016-09-30 07:25
Yes. The AnkiDroid menu has an option to `Export collection`. Do include scheduling but don't include media. Click on my name to find my email.

**Comment by william301** [comment] 2016-09-30 07:47
@hssm: email sent :) hope we can fix it without much trouble

**Comment by hssm** [comment] 2016-09-30 07:58
Thanks.

If you delete the custom study deck and then remake it you will no longer have the problem (the cards are returned automatically so you don't lose anything).

I am more interested in how it ended up that way, though. How did you initially create the custom study deck? Did it work correctly before? Anki reuses the deck if it already exists when you pick a custom study option, so you would have to think back to the very first time you did that.

**Comment by william301** [comment] 2016-09-30 08:20
Yeah is working now! Great, many thanks man.

Well I recently created a new deck and started a custom study session for that deck as I normally do. Then this bug message appeared. Not sure how it happened though.. is the 1st time I have a problem with Anki.

However now is solved and I am so happy. My life would not be the same without Anki!

**Comment by hssm** [comment] 2016-09-30 10:04
I'm glad the problem is resolved. I am going to close this issue in favor of https://github.com/ankidroid/Anki-Android/issues/3447.

I can't understand how this bug can happen, even after looking at the code that creates it. I'd like to believe it was something we fixed along the way (your version of AnkiDroid is somewhat ancient) but our crash reporting tool suggests that it may not be the case.

If it happens again, try to recall the steps you take to lead up to it.

**Closed by hssm** 2016-09-30 10:04 UTC
