### ISSUE TITLE
[Bug] Feedback Dialog is showing while entering invalid details in LoginActivity

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#13966] opened 2023-06-09 09:30 UTC
###### Reproduction Steps

1. Go to LoginActivity
2. Enter invalid details

###### Expected Result
Feedback Dialog is not showing

###### Actual Result
Feedback Dialog is showing

https://github.com/ankidroid/Anki-Android/assets/65113071/26ca245b-0a7d-4edb-830f-717e46be018d

###### Debug info
AnkiDroid Version = 2.16.0beta2

Android Version = 13

ProductFlavor = full

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Mobile Safari/537.36

ACRA UUID = 056773a8-ba11-466b-90cf-cfa8c611eda1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by n1snt** [comment] 2023-07-27 17:39
I have tried replicating this issue but I am unable to reproduce it.

**Comment by dae** [comment] 2023-09-01 07:28
Closing until we hear back from people who can replicate it.

**Closed by dae** 2023-09-01 07:28 UTC
