### ISSUE TITLE
Implement Desktop's congrats screen bottom buttons and text link commands

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14955] opened 2023-12-12 14:50 UTC
https://github.com/ankidroid/Anki-Android/pull/14916 was aimed at reusing Anki's congrats screen in AnkiDroid. However, the screen is not exactly identical.

* https://github.com/ankidroid/Anki-Android/pull/14916

###### Desktop

<img width="476" alt="image" src="https://github.com/ankidroid/Anki-Android/assets/92206575/b73d44ca-5651-478c-9ae7-5f0609fce8f9">

###### AnkiDroid

<img width="200" alt="image" src="https://github.com/ankidroid/Anki-Android/assets/92206575/8d9d6956-2c48-4594-8923-dc4740dfadfc">

Note that two paragraphs are missing. The bottom buttons are missing too, but this was already noted in the PR.

> Also, the screen should have some buttons like the Desktop version do.
> AnkiMobile doesn't have them explicitly as well, only under the gear with 300+ options in the reviewer, so moving the buttons to Svelte and reusing them in all platforms is the least resistance path IMO

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/issues/14916#issuecomment-1848393386_

**Comment by david-allison** [comment] 2023-12-13 06:17
[Posted this in Discord, in case it helps others](https://github.com/ankitects/anki/blob/edd38ca06730d7fc16804f52ce10f6bc54c3d145/qt/aqt/overview.py#L209)

**Comment by BrayanDSO** [comment] 2023-12-28 17:38
This is a FR, not a regression, so Im removing from the 2.17 milestone

**Comment by user1823** [comment] 2023-12-28 18:58
To be fair, it is partially a regression. Before the change, there were some controls at the top (as shown in the below screenshot). Now, there are no controls.

<img width="300" src="https://user-images.githubusercontent.com/92206575/230805537-701b7ce7-b826-4ded-b359-8c3deea40203.png">

**Comment by david-allison** [comment] 2024-01-02 14:25
We need 'Deck Description' back, as of 2.17 this can't be edited.

**Comment by BrayanDSO** [comment] 2024-01-22 19:43
Besides `Description`, all of these were implemented and we decided that description doesn't fit well in a `Congratulations` page, so I'm going to close the issue since that was what OP asked

**Closed by BrayanDSO** 2024-01-22 19:43 UTC
Labels: Accepted, Anki Ecosystem Compatibility

**Comment by david-allison** [comment] 2024-01-22 19:58
Do we have an issue for 'description'? I feel that's a blocker for 2.17

**Comment by BrayanDSO** [comment] 2024-01-22 21:14
Nope. I suggest creating one
