### ISSUE TITLE
[Bug] Full sync button don't work properly on Incompatible Database dialog

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10394] opened 2022-02-24 19:02 UTC
###### Reproduction Steps

1. Have a newer scheme `collection.anki2`
2. Tap `Full sync from server` without being logged

Demo:
https://user-images.githubusercontent.com/69634269/155589058-7fc833e3-6cb7-4a3e-86cb-fb51639d8797.mp4

###### Expected Result

A message saying something like `You aren't logged, thus you can't sync`

###### Actual Result

It stays in a eternal loading, as shown in the demo video

###### Debug info
```
AnkiDroid Version = 2.16alpha45

Android Version = 11

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-N770F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36

ACRA UUID = 7b43f97d-f42d-432b-808c-dcee88875a39

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2022-02-24 19:04
As you can see, for a very brief moment it shows a log-in screen, but without tapping anything it vanishes and the eternal loading begins

**Comment by david-allison** [comment] 2022-02-24 19:07
Duplicate of https://github.com/ankidroid/Anki-Android/issues/7326 I believe

**Comment by BrayanDSO** [comment] 2022-02-24 19:15
Haven't found that. Thanks. I'll close this issue.

**Comment by BrayanDSO** [comment] 2022-03-01 00:11
Looked it further, they aren't the same problem

**Closed** 2022-03-01 18:26 UTC
