### ISSUE TITLE
Link to an anchor inside an iframe returns 404 on __viewer_.html

### ISSUE THREAD

**Issue by jsalatiel** [ankidroid/Anki-Android#3734] opened 2015-10-15 10:29 UTC
Hello, i am having a very odd behaviour when trying to link to an anchor inside a iframe.

The back card content has (basically):

```<a href="#Art_5" target="'iframe_theory'">Art 5</a>```
```<iframe src="_theory.html" name="'iframe_theory'" style="border:none" width="100%" height="700"></iframe>```

The html iframe renders correctly , but when i click in the link "Art 5" that should point me directly to the anchor `#Art_5` inside the iframe i got a 404 in the iframe section

I have no idea where it is getting this `__viewer__.html`  file from,  instead of the _theory.html

Webpage not available

The webpage atfile:///storage/emulated/0/AnkiDroid/collection.media/__viewer__.html#Art_5could not be loaded because:

net::ERR_FILE_NOT_FOUND

**Comment by hssm** [comment] 2015-10-17 08:58
I guess this is caused by https://github.com/ankidroid/Anki-Android/pull/631. Not sure what the behaviour would be for this without it.

**Comment by jsalatiel** [comment] 2015-10-18 02:26
I found the solution/workaroung
Just changed the ```<a href="#Art_5" target="'iframe_theory'">Art 5</a>``` to ```<a href="_theory.html#Art_5" target="'iframe_theory'">Art 5</a>```

It works great !!! Thanks for your hard work. Ankidroid is far better than anki desktop =)

**Comment by hssm** [comment] 2015-10-18 10:44
Good to see you found a solution. Since this is a very particular use case I don't think it's worth leaving an issue open for it, so I'm going to close this.

**Closed by hssm** 2015-10-18 10:44 UTC
