### ISSUE TITLE
[Bug] The deck is shown as empty in the browser after opening and closing the settings 

### ISSUE THREAD

**Issue by Andrej-Adamenko** [ankidroid/Anki-Android#9013] opened 2021-05-30 06:00 UTC
###### Reproduction Steps
1. Open a deck in `Card browser` 
![Screenshot_20210530-062514_AnkiDroid](https://user-images.githubusercontent.com/70955223/120093575-ec746800-c123-11eb-9908-e4177bda6e8d.jpg)

2. Go to `Settings` 
![Screenshot_20210530-062646_AnkiDroid](https://user-images.githubusercontent.com/70955223/120093610-1b8ad980-c124-11eb-9642-4865c001ad2d.jpg)

3. Change nothing in `Settings` and go back.
4. The deck is shown as empty now. 
![Screenshot_20210530-062924_AnkiDroid](https://user-images.githubusercontent.com/70955223/120093658-63a9fc00-c124-11eb-8ecc-2dd075a7f714.jpg)

5. As a workaround, re-select the current deck in the browser's deck list
6. Now it is shown correctly. 

###### Debug info
AnkiDroid Version = 2.15.2

Android Version = 10

Manufacturer = samsung

Model = SM-A920F

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-A920F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.77 Mobile Safari/537.36

ACRA UUID = 1b392f85-2b0c-4491-b153-fdb7fb7b8d34

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by ShridharGoel** [comment] 2021-05-30 07:39
Duplicate of https://github.com/ankidroid/Anki-Android/issues/8533 which seemed to have got fixed.

**Comment by ShridharGoel** [comment] 2021-05-30 16:26
@david-allison-1 Are you that this should be closed? Since the previous one was closed because it did not seem to happen anymore but seems like the issue might be intermittently happening on some devices as we can see in the screenshots in the issue description.

**Comment by david-allison-1** [comment] 2021-05-30 16:41
I saw that and couldn't repro. If it's still an issue, then it's still an issue and needs triage

**Comment by Andrej-Adamenko** [comment] 2021-05-30 16:59
I tried many times and the issue always reproduced. However, when I tried to make a screenshot video, the issue did not reproduce. I tried 3 times to reproduce the issue while a screenshot video was recording and it worked fine. When I switched from the settings back to the card browser, first it showed 0 cards in the deck, but after half a second the number changed to the correct one. 
I think this can help to fix it.
See the screenshot video [here](https://youtu.be/lKPcyVz1DvI).

**Comment by mikehardy** [comment] 2021-05-31 02:59
@Andrej-Adamenko thanks for this and your previous report, we're getting close to having all the 2.15 issues figured out, and it's reports like these that get us there!

**Comment by AbdelrahmanHamdy1998** [comment] 2021-06-05 22:34
Uploading Screen_Recording_20210606-003140_AnkiDroid_1.mp4…

**Comment by AbdelrahmanHamdy1998** [comment] 2021-06-05 22:35
https://user-images.githubusercontent.com/79529298/120907079-04397800-c65f-11eb-8b75-1be1fa8106f8.mp4

**Comment by mikehardy** [comment] 2021-06-06 15:46
@AbdelrahmanHamdy1998 unfortunately that video did not seem to upload correctly. Perhaps you could put it on youtube or similar and share the link?

**Comment by david-allison-1** [comment] 2021-06-06 20:59
Video works for me. @AbdelrahmanHamdy1998  What version of AnkiDroid is this?

**Comment by AbdelrahmanHamdy1998** [comment] 2021-06-06 21:05
playstore 2.15.4 @david-allison-1

**Comment by mikehardy** [comment] 2021-07-04 05:40
Even stranger for me - I can't reproduce this but if I select a large deck (10,000 cards) in card browser, then select a small deck (1000 cards), then go to settings, then go back with no change the deck browser switches itself back to the large deck?

Something is not right with the card browser...

**Comment by mikehardy** [comment] 2021-07-16 14:36
Fix this going out in the next alpha @Andrej-Adamenko today :rocket:

**Closed** 2021-07-16 14:37 UTC
Labels: Help Wanted, Needs Triage
