### ISSUE TITLE
[Bug] FDroid: "Error installing package" for multiple versions of AnkiDroid if app data already exists

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#14356] opened 2023-08-30 17:25 UTC
###### Reproduction Steps

1. Attempt to update to 2.16.3 via FDroid from 2.16.2 (I think this was my previous version)
2. FDroid displayed a warning along the lines of the signing key is different and inorder to upgrade, the app must be uninstalled then reinstalled.
3. Proceed to uninstall via the popup but keep AnkiDroid app settings. Below is a screenshot of this popup for another app.
![Screenshot_20230830-125202](https://github.com/ankidroid/Anki-Android/assets/30786326/fb3c2ba0-26a1-4813-bb9e-ba96ac1b2cc7)
I had to use another app as an example because I can't currently install AnkiDroid via FDroid due to this bug.
4. Install AnkiDroid using the install button
5. Get the following error (sometimes preceded by "error parsing package"):
![Screenshot_20230830-125302](https://github.com/ankidroid/Anki-Android/assets/30786326/4f087c0c-430e-4ebd-a4be-20f2910f363e)

This now occurs for me when trying to install 2.16.3, 2.16.2, and 2.15.6. I've upgraded in the past, but I don't think I've had the signing key popup or the option to keep app data before. I realize this sounds like a FDroid error, but since I can install other apps fine, my gut feeling is that in the process of installing, AnkiDroid does not enjoy the previous version of AnkiDroid's saved app data.

###### Expected Result
Install without error

###### Actual Result
Error installing the 3 most recent version of AnkiDroid, even versions I've previously had installed.

Luckily the parallel builds still work, probably because they have their own app data.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

-  [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2023-08-30 18:59
Thanks!

Duplicate of #14216, I'll update the title to match

**Closed by david-allison** 2023-08-30 19:00 UTC

**Comment by sudomain** [comment] 2023-08-30 19:08
I'm sorry. I did search existing issues, but didn't see that one.
Thank you

**Comment by david-allison** [comment] 2023-08-30 19:09
Our fault for not tagging it well enough, thanks for the writeup as always!
