### ISSUE TITLE
request to enhace the ui of the appliation. since the current ui looks so pro\imitive

### ISSUE THREAD

**Issue by CodeXstalker** [ankidroid/Anki-Android#14324] opened 2023-08-27 17:06 UTC
**Is your feature request related to a problem? Please describe.**
no]

**Describe the solution you'd like**
I will use the material design to enhnace the ui.

**Comment by BrayanDSO** [comment] 2023-08-27 17:10
Not a new issue. Duplicate of #13878 and similars. Feel free to improve it yourself so it is less "primitive" or otherwise just be patient. We are all volunteers here

**Closed by BrayanDSO** 2023-08-27 17:10 UTC
