### ISSUE TITLE
[BUG]: AnkiDroid installed through F-Droid shows up in play store as having an update available; update fails if attempted

### ISSUE THREAD

**Issue by cumber** [ankidroid/Anki-Android#15563] opened 2024-02-18 02:39 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

For me it seems to reproducible simply by having F-Droid. I'm not sure what other factors might be involved.

I believe it started several months ago, after years of never observing this AnkiDroid updates being offered by the play store when I have

### Expected behaviour

If AnkiDroid is installed through F-Droid, it should not appear as an update through the Play store.

Other apps I have installed through F-Droid don't even show up as installed apps when going to "Manage apps and device" in the Play store; this is how I expect AnkiDroid to work.

### Actual behaviour

AnkiDroid is installed through F-Droid.

The Google Play store, for the past several months, has been telling me that there is an update available for AnkiDroid (to version 2.16.5, which is the same version I have installed through F-Droid).

If I actually attempt to install the update, it always fails with the rather generic error message "Can't install AnkiDroid Flashcards".

Whenever the Play store notifies me about updates for apps, AnkiDroid is always in the list, and I have to individually update every other app (rather than pressing update all) if I don't want to trigger the failing update to AnkiDroid.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 14

ProductFlavor = full

Manufacturer = Google

Model = Pixel 8

Hardware = shiba

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 8 Build/AP21.240119.009; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.164 Mobile Safari/537.36

ACRA UUID = 435bc978-6836-47a0-8753-fa47d11bbaf9

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

I've had AnkiDroid installed through F-Droid for years, across several different phones. I cannot recall ever seeing the Play store offer an update for it before this started happening a few months ago.

Completely uninstalling the app and then reinstalling it didn't help.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-02-18 02:44
Similar to, if not a duplicate of:

* https://github.com/ankidroid/Anki-Android/issues/14216

Specifically: https://github.com/ankidroid/Anki-Android/issues/14216#issuecomment-1678167774

**Comment by david-allison** [comment] 2024-02-18 02:45
@mikehardy one for the queue, possibly needs a change on F-Droid so the version codes match

**Comment by david-allison** [comment] 2024-02-18 02:51
closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/14216

This can be worked on in: https://gitlab.com/fdroid/fdroiddata/-/issues/3047

**Closed by david-allison** 2024-02-18 02:51 UTC
Labels: Bug, Needs Triage

**Comment by cumber** [comment] 2024-02-18 04:30
@david-allison That one did turn up when I was searching to see if something like this was already reported, but I didn't see that it was a duplicate.

My issue is about the F-Droid-installed app being recognised by the Play store as "the same app" and trying to upgrade it. While that other issue appears to be that *after* installing from the Play store and then uninstalling, trying to install it from F-Droid fails.

I don't see the connection between the two. Most likely that's my lack of understanding, but would you mind explaining the link?

#14216 is reporting a failure to install *from F-Droid*, which I'm not experiencing. I do get a failure to install *from the Play store*, but that's not the problem I want resolved; I'm not trying to migrate to the Play store version, so I don't want the Play store to offer me upgrades for AnkiDroid in the first place.

That seemed to be how it worked for many years now, and seems to still be how it works for other apps I have installed through F-Droid that are also available through the Play store. What changed?

**Comment by cumber** [comment] 2024-02-18 04:30
In fact if the install error were fixed it would make the real problem significantly worse for me, as every time the Play store updates apps it would force my AnkiDroid to switch over to being Play-store-managed, which I don't want to happen. So if https://gitlab.com/fdroid/fdroiddata/-/issues/3047 is going to fix the install error then I urgently need to figure out the crossover between the app stores before that is completed and released!

**Comment by david-allison** [comment] 2024-02-18 04:40
The underlying problem in both cases is that F-Droid isn't producing the same version number as Google Play.

Google Play correctly reflects 2.16.5 for `arm64-v8a` as `321602300`. F-Droid displays `21602300`

See:

https://github.com/ankidroid/Anki-Android/blob/a06d445bfcea3139accc30faa1b24c0fe214d2b0/AnkiDroid/build.gradle#L195-L219

and 

https://gitlab.com/fdroid/fdroiddata/-/blob/edbed4979e54bec878135ed928edb481d2cfd1a7/metadata/com.ichi2.anki.yml#L797

**Comment by david-allison** [comment] 2024-02-18 04:42
While you're waiting for a fix:

https://github.com/ankidroid/Anki-Android/releases/latest

and https://github.com/ankidroid/Anki-Android/releases/ both provide `Parallel.A`, which the Play Store will not manage, but these will not automatically update
