### ISSUE TITLE
Ankidroid I need to have complete control over text-to-speech.

### ISSUE THREAD

**Issue by porfirio1830** [ankidroid/Anki-Android#4494] opened 2016-11-18 04:07 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[X  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Ankidroid, i need to control  text-to-speech as i do in anki, but this doesn't work completely with ankidroid.
2.  I have tried with the following code:

<script type="text/javascript">
var w=new SpeechSynthesisUtterance();
w.text={{EnglishWord}};
speechSynthesis.speak(w);
</script>

3. And with the following code:

`<p id="msg">{{EnglishWord}}</p> `
 ` <input type=" text" name="speech-msg" id="speech-msg" x-webkit-speech> `
`speechSynthesis.speak(document.getElementById('speech-msg'));`

###### Expected Result

I only need to listen the información choosen by the función speak (english-word)

###### Actual Result
Ankidroid speaks all (completely) the información shown in the flash card, that's it, hints, translations, examples and notes, i just want to listen the english-word and one-example. I don't have complete control over tts in ankidroid.

###### Debug info

It simply does not recognize valid html and javascripts commands.
The above code works well with the google chrome browser but not with ankidroid.

Please help, comments are welcomed.
Thanks.

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment] 2016-11-18 14:07
Duplicate of #1463. See that issue for possible solutions, but ultimately this depends on the TTS system you have on your phone.

**Closed by eginhard** 2016-11-18 14:07 UTC
