### ISSUE TITLE
adding colour change option in toolbar

### ISSUE THREAD

**Issue by sakshi-1604** [ankidroid/Anki-Android#8198] opened 2021-03-14 06:13 UTC
The android version lacks the colour changing option for font in the toolbar. It will be great if this feature is added

**Comment by david-allison-1** [comment] 2021-03-14 06:18
Thanks! Duplicate of https://github.com/ankidroid/Anki-Android/issues/7766. 

Pull requests very welcome. We had a really nice UI design proposed for this

**Closed** 2021-03-14 06:18 UTC
Labels: Duplicate
