### ISSUE TITLE
missing from the google play store

### ISSUE THREAD

**Issue by ijgnd** [ankidroid/Anki-Android#5785] opened 2020-03-02 12:48 UTC
The [link to the playstore from this repo](https://play.google.com/store/apps/details?id=com.ichi2.anki&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1) doesn't work anymore and I can't find it with my smartphone with Android 10. There's a [similar report on reddit](https://www.reddit.com/r/Anki/comments/fcb6of/ankidroid_is_gone_from_google_play/).

**Comment by midse** [comment] 2020-03-02 13:12
The link is working for me now!

**Comment by mikehardy** [comment] 2020-03-02 13:14
Yeah, not sure what is going on there but I just checked in a private/clean browser session and I see it just fine? I'll mention on reddit as well. I have an account there but don't follow it at all, just go over when referenced. Please let me know if it happens again, that's our main distribution channel and there's no reason it shouldn't be there

**Closed by mikehardy** 2020-03-02 13:14 UTC

**Comment by eginhard** [comment] 2020-03-02 13:21
I was able to reproduce shortly after the issue was opened, but it seems to be working fine again. Not sure what happened there.

**Comment by mikehardy** [comment] 2020-03-02 16:28
So odd. Google blip I suppose. I definitely appreciate the heads up and everyone should know we work hard to make sure that fdroid has the releases as well. Cheers
