### ISSUE TITLE
Possible bug with new card number indication

### ISSUE THREAD

**Issue by terrywallwork** [ankidroid/Anki-Android#5737] opened 2020-02-04 12:14 UTC
Im not certain if the following is a bug or not but I noticed that the New Card number amount on two decks shows the value 2 but when clicked to study it says study complete.  See attatched screenshot.

AnkiDroid Version = 2.9.2

Android Version = 8.0.0

ACRA UUID = 8c4ae41a-d8ac-41bd-ba77-8ac55aec197c

![Screenshot_20200204-120057](https://user-images.githubusercontent.com/19387982/73744033-d5984e00-4747-11ea-9378-ed01e933cd78.png)

**Comment by Anthropos888** [comment] 2020-02-08 08:01
Probably you're using scheduler V2 and the new card limit of your parent deck is already reached. You need to increase the new card limit for the parent deck in order to be able to learn those 2 remaining new cards because the sub decks stick to the limits of the parent deck

**Comment by terrywallwork** [comment] 2020-02-08 08:40
Thankyou for letting me know. 😃

**Comment by woj-tek** [comment] 2020-02-13 12:27
I just faced the same issue but for me it's not a "feature". I intentionally set parent's new items to "0" (to disable new items) and in AnkiDesktop I see that works well: neither parent nor sub-decks have new items != 0, neither in deck list nor in deck summary screen. In AnkiDroid however I can see new items with new value non-zero, but only in deck list - it's displayed correctly in deck summary.

I'd say it's deck-list display bug.

**Comment by mikehardy** [comment] 2020-02-13 15:24
PRs happily accepted :-)

**Comment by woj-tek** [comment] 2020-02-13 15:25
At first I would like to establish whether it's intended or actual bug :-)

**Comment by Anthropos888** [comment] 2020-02-13 19:37
I can confirm that the new card number is displayed differently in Anki Desktop and AnkiDroid when using V2 scheduler and the "new card limit" of the parent deck is set to 0:

AnkiDroid shows 4 new cards:
![Screenshot_20200213-202450](https://user-images.githubusercontent.com/45192213/74471152-02fb9f00-4ea0-11ea-8bd1-000ae1856330.png)

Anki Desktop shows 0 new cards:
![Anki](https://user-images.githubusercontent.com/45192213/74471205-1eff4080-4ea0-11ea-9795-fc31d7c58add.jpg)

The AnkiDroid deck summary shows correctly 0 new cards:
![Screenshot_20200213-202502](https://user-images.githubusercontent.com/45192213/74471258-363e2e00-4ea0-11ea-9842-8e17c6a254b4.png)

Actually I never realized the difference in Anki and AnkiDroid because I quite like to see the number of new cards per sub deck, even if the parent deck limit is set to 0 ;-)

But this should be tagged with the Anki Ecosystem label anyway.

**Comment by mikehardy** [comment] 2020-02-13 20:35
thanks for confirming! I tagged it up

**Comment by Anthropos888** [comment] 2020-02-15 15:56
I just tested it with stable AnkiDroid 2.9 and the bug doesn't exist there, neither with scheduler v1 nor v2. Another user reported it works for him on 2.9.1 but not on the latest Playstore version. So the bug might be introduced in 2.9.2 (version of the thread starter)

**Comment by mikehardy** [comment] 2020-02-15 16:06
Any commit listed here that is not 'Skipped', until you get to the 2.9.1 release (which is apparently okay) is suspect then https://github.com/ankidroid/Anki-Android/commits/hotfix-2.9.2

There aren't that many thankfully

**Comment by mikehardy** [comment] 2020-02-15 16:08
There is typically an alpha release every few commits, so installing the relevant alpha before / after the commit can finalize locating the issue. Each commit will contain a list of the releases it is in so you can find the ones with or without a specific commit.

 For instance this was in the list and might be it (I have not tested) https://github.com/ankidroid/Anki-Android/commit/7235a5bc667a6c9def934d85764cedc6594814b3 and when I expand the version list it appears to be in 2.10alpha10, so 2.10alpha9 won't have it but alpha10 will and can be used as a check

**Comment by Anthropos888** [comment] 2020-02-16 15:59
@mikehardy you were almost right ;-) alpha10 doesn't have the bug, but alpha11 has it. That's the culprit.

**Comment by mikehardy** [comment] 2020-02-16 16:21
@Anthropos888 thank you! If we bisected correctly @Arthur-Milchior #5579 is the only likely commit for this bug

**Comment by mikehardy** [comment] 2020-02-16 16:23
(edited to point to the correct PR 5582, apologies)

**Comment by Arthur-Milchior** [comment] 2020-02-16 23:32
We already new that this PR contained an error. And it was corrected in #5607
it does not mean that this PR contains no other error. But I believe that it would be worthwhile to test whether the bug still occur in alpha 17, which incorporated this correction, or not. 

I'm going to check again the two commits between alpha 10 and 11 to see whether I find anything of interest here

**Comment by mikehardy** [comment] 2020-02-16 23:33
release 2.9.3 contained the correction as well 🤔  (I merged it into the hotfix branch: https://github.com/ankidroid/Anki-Android/commits/hotfix-2.9.3)

**Comment by Arthur-Milchior** [comment] 2020-02-16 23:35
Got it. I'll make a PR today

**Comment by Arthur-Milchior** [comment] 2020-02-16 23:45
And by "today" I meant: in ten minutes
https://github.com/ankidroid/Anki-Android/pull/5759

**Comment by mikehardy** [comment] 2020-02-17 22:52
I just merged that PR and released 2.10alpha40 - hopefully that does the trick?

If it does I'll merge it in for release on 2.9.4 which is just about to release

Thank you @Arthur-Milchior !

**Comment by Arthur-Milchior** [comment] 2020-02-18 00:44
You're welcome. It's the least I can do, cleaning the mess I did

**Comment by Anthropos888** [comment] 2020-02-18 18:59
Problem is solved in alpha40, thanks @Arthur-Milchior

**Closed** 2020-02-18 23:50 UTC
Labels: Anki Ecosystem Compatibility, Bug, Help Wanted
