### ISSUE TITLE
about audio play

### ISSUE THREAD

**Issue by mayixb** [ankidroid/Anki-Android#16159] opened 2024-04-11 11:43 UTC
Hello,

I encountered an issue with the app where the audio playback pauses when the phone screen turns off. I would like the audio playback to continue uninterrupted even when the screen is off. Could you please look into this matter and provide a solution?

Thank you.

**Comment by BrayanDSO** [comment] 2024-04-12 18:51
Try Settings > Reviewing > Keep screen on

**Comment by stasimon1** [comment] 2024-04-14 09:01
> Try Settings > Reviewing > Keep screen on

"Screen off" mode would consume less battery. This is why "screen off" tool would be useful.

**Comment by mayixb** [comment] 2024-04-16 13:34
> and if you still think there is any problem related to this feature that can affect users. please let me know.

Similar to a music player, when the screen is turned off, the music continues to play and does not pause, because I am studying English, there are many pieces of audio

**Comment by BrayanDSO** [comment] 2024-04-16 19:20
Does the screen turn off automatically when an audio is played? Or the issue is because you want to turn it off yourself?

**Comment by mayixb** [comment] 2024-04-17 04:17
> Does the screen turn off automatically when an audio is played? Or the issue is because you want to turn it off yourself?

In order to save power, the phone screen will automatically turn off when the screen is not touched for a period of time. Apps like the audio player will keep playing after the screen turns off and not stop, but Anki will stop playing the current audio after the screen turns off. Turning the screen to always-on seems a bit wasteful just to solve this problem.

**Comment by david-allison** [comment] 2024-04-17 05:53
How are you using Anki with the screen off?

**Comment by mayixb** [comment] 2024-04-17 10:16
> How are you using Anki with the screen off?

I use it to practice English listening and use gestures to operate the card while wearing Bluetooth headphones; I basically don't look at the phone screen.

**Comment by david-allison** [comment] 2024-04-17 12:49
Gestures work while the screen is off?

**Comment by mayixb** [comment] 2024-04-18 04:01
> Gestures work while the screen is off?

I can just flip my wrist, then the mobile phone screen is opened, and the gesture can operate the screen

**Comment by BrayanDSO** [comment] 2024-04-18 19:20
From me, it's a "Won't fix"

**Comment by david-allison** [comment] 2024-04-18 19:32
Likewise. Thanks for the report. Closing as https://github.com/ankidroid/Anki-Android/labels/Won%27t-fix

**Closed by david-allison** 2024-04-18 19:32 UTC
Labels: Won't-fix
