### ISSUE TITLE
Return immediately to deck list after finishing a single deck

### ISSUE THREAD

**Issue by guemax** [ankidroid/Anki-Android#15832] opened 2024-03-10 06:54 UTC
**Is your feature request related to a problem? Please describe.**
In an older version of AnkiDroid, after finishing a single deck I was redirected immediately to the deck list. I rarely need the custom study feature, so I was very happy for not having to press another button for returning to the deck list like I have to do in  Anki Desktop.

**Describe the solution you'd like**
It would be great if AnkiDroid returned immediately to the deck list after finishing a deck. When a user tries to review cards from a deck without any cards to be reviewed, the deck overview with the custom study feature is shown. (This might be better than hiding the custom study feature behind an option or something similar.)

I am looking forward to your answer!

Edit: AnkiDroid specific terms.

**Comment by david-allison** [comment] 2024-03-10 11:10
Hi, thanks for the report!

Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/15349

* https://github.com/ankidroid/Anki-Android/issues/15349
* Fixed in https://github.com/ankidroid/Anki-Android/pull/15818

**Closed by david-allison** 2024-03-10 11:10 UTC
