### ISSUE TITLE
[BUG]: Filtered Deck doesn't include scheduling

### ISSUE THREAD

**Issue by jbealle** [ankidroid/Anki-Android#16360] opened 2024-05-07 09:11 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

I created a Filtered Deck from an Existing Deck using the "+" dialog. I confirmed that I had checked "Reschedule cards based on my answers in this deck".  I used the Search Filter ("tag:ch13" or "tag:ch14") which I had copied from a Card Browser search -- this worked fine.  I changed Limit To from 100 to 200 because there were actually 109 matching records.

### Expected behaviour

I don't know the program real well but I expected "Reschedule based on" to inherit the scheduling algorithm of the parent deck. I also expect to be able to access these settings in the Deck Options. The fact that there seemed to be no algorithm at all rendered the Filtered Deck unusable.

### Actual behaviour

The filtered records that matched the tags were successfully imported. But there was no scheduling algorithm imported and the settings panel in Deck Options was greyed out. When began studying, the Deck Count (Blue-Red-Green) was 0-1-109. Each card studied, no matter if I responded Hard or Good, would reduce Green by one.

### Debug info

```text
AnkiDroid Version = 2.18beta2 (dc5348852b15e0f27521acd3c5457595f4676f54)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = OnePlus

Model = LE2125

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; LE2125 Build/UKQ1.230924.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.26 Mobile Safari/537.36

ACRA UUID = dc16b5ae-5a3b-41d3-82f0-bf0a0c834586

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by jbealle** [comment] 2024-05-07 09:14
This same issue (no scheduling info) happens with Custom Study Session: Limit to Particular Tags. I assume these are related so I won't create a separate report.

**Comment by jbealle** [comment] 2024-05-07 09:36
I am not sure if you mean the behavior I described is "as intended" or if you can't duplicate the issue. I don't remember this happening even a few weeks ago, so I assumed it appeared in my current Beta and may have been fixed in Alpha. I was using Custom Study which was inheriting the parent deck algorithm fine until maybe a week ago. I don't use the desktop version at all.

**Comment by BrayanDSO** [comment] 2024-05-09 21:39
I'm going to close this as intended behavior. Feel free to ask for any help in Discord.

**Closed by BrayanDSO** 2024-05-09 21:39 UTC
Labels: Bug, Needs Triage
