### ISSUE TITLE
"Start of next day" not used by SchedV2

### ISSUE THREAD

**Issue by Arthus** [ankidroid/Anki-Android#6203] opened 2020-05-17 12:52 UTC
###### Reproduction Steps

1. Set the daily rollover time to something different from the default, like 6 hours after midnight
2. Learn into the night/morning
3. Check the decks/notes before and after 4am

###### Expected Result
The decks/cards should reset at 6am

###### Actual Result
The decks/cards still reset at 4am

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by Arthus** [comment] 2020-05-17 12:52
I'm already looking into it...

**Comment by mikehardy** [comment] 2020-05-17 15:03
There are some other things in that area - it's a bit of a bugfest in the start-of-day / collection configuration area I think #5831  #5637

**Comment by Arthus** [comment] 2020-05-18 00:08
I think, I have already narrowed down the reason... at least I hope so. I will have to check upstream libanki and will need to do some testing, so it will take some time (and #6138 is my priority right now) but all those issues might get solved in the near future :)

**Comment by mikehardy** [comment] 2020-05-18 00:11
:heart: !

**Comment by david-allison-1** [comment] 2020-05-18 00:11
Also linking: #5805

**Comment by Arthus** [comment] 2020-06-01 19:22
I started working on this today, but it's going to take some time.
 - Rollover time for SchedV2 is bugged (propably never worked), but it's not worth fixing alone with the other changes that were done to Anki's handlng of 
 - Anki changed the handling of rollover time in general to support timezones (thanks @david-allison-1 for linking the issue)
 - Anki also ported the whole rollover code to Rust, so I have to read through it and not only understand Rust, but also how Rust and Python communicate with each other.
So I'm currently going from some C++ experience to understanding Java, Python and Rust all at the same time.

As soon as I've figured out my open questions (communication between Anki's Rust backend and the python code), I will try to post an initial patch. But for today, I just started by deduplicating code between SchedV1 and SchedV2, so the following works are going to be easier.

**Comment by jparta** [comment] 2021-02-12 11:27
Having the same problem. Likely compounding with the DST issue for me. Start of day is set to 6 am, but I got new cards at 3 am.

**Comment by mikehardy** [comment] 2021-02-12 13:01
@jparta have you tried the current alpha builds? I believe they might fix it https://docs.ankidroid.org/manual.html#betaTesting / or a parallel build here from releases page

**Comment by jparta** [comment] 2021-02-14 01:15
@mikehardy I am not sure how to check that my app is the alpha version. Play store says it is beta. I reinstalled the app to be safe. What I can say for sure is that I still have the new cards for the new day.

**Comment by mikehardy** [comment] 2021-02-14 01:20
@jparta  If you follow the instructions in https://docs.ankidroid.org/help.html I believe it tells you how to get the version, also it will be in the info screen for the app in system preferences I think?

**Comment by jparta** [comment] 2021-02-14 02:13
@mikehardy From 'About Ankidroid', debug info and OS app info I get the version number 2.14.3, but I don't see build numbers or beta/alpha status anywhere.

When it hit 4am, the statistics caught up and started a new day. The statistics' new day is also unaffected by the 'start of new day' preference.

**Comment by mikehardy** [comment] 2021-02-14 02:21
2.14.3 means you are not on the alpha. You may wish to manually install it as a parallel version to make absolutely sure: https://github.com/ankidroid/Anki-Android/releases/tag/v2.15alpha26

**Comment by jparta** [comment] 2021-02-14 03:30
I get alpha in the parallel. It doesn't seem to fix the problem, though. No difference in number of cards to review or statistics with 0 vs 23 hours after midnight.

Btw, do the parallel apps share the DB?

**Comment by dae** [comment] 2021-02-14 03:38
There is a timezone setting in the computer version's preferences that says AnkiDroid doesn't support it. With the alpha, you should be able to use it, and it may resolve your issue.

**Comment by jparta** [comment] 2021-02-14 11:44
@dae I turned on 'New timezone handling' in the parallel app, but it didn't seem to make the system respond to the start-of-day preference. 

It also caused a sync error in the main app, 'Your Anki client does not support the new timezone code yet'. Would restoring from backup help? Switching off the handling doesn't help with the error.

**Comment by mikehardy** [comment] 2021-02-14 14:09
I believe you have to turn on new timezone handling on computer, turn it on in AnkiDroid, then sync from computer to AnkiDroid? Apologies this is all a bit fussy, it's literally brand new, you are perhaps our first non-developer tester (which is really appreciated, by the way, thank you).

The parallel version does use the same database in it's default configuration, but apart from allowing testing "on the side" like this the parallel builds may also be used to support (...in a way) multiple "profiles" like Anki Desktop / Mobile does if you change the storage to for example 'AnkiDroid.A' or something. That's how I keep collections separate between me and my child for instance (I use AnkiDroid.A for my child, AnkiDroid.B for me and the "main" AnkiDroid for testing since it gets auto-updates to new alphas from google)

**Comment by jparta** [comment] 2021-02-14 16:31
@mikehardy 
I am able to sync on the parallel version, but the main version is still complaining about the incompatibility of the timezone setting when I try to sync. 

I'm studying CS, but I haven't done Android development before. I might be able to do some digging and get more comfortable with the codebase, but not right now.

The parallel version seems useful, indeed. But now it modified the DB in a way that the main app doesn't agree with.

**Comment by mikehardy** [comment] 2021-02-14 17:55
A shame that the alpha doesn't seem to have worked 🤔 and yes while they can be configured to share a database (they default to that) this version jump is probably backward incompatible. If you switch the database path to a .A suffix and resync then the parallel will be separate and if you full sync down your main install (which will clobber it! Careful) then they will be fully separate and both working

**Comment by jparta** [comment] 2021-02-14 19:56
I implore anyone who is having this problem to try the alpha and confirm this. I followed the instructions and separated the installations. But it seems that the collection carries with it the preferences, so I can't use my collection and the timezone fix together if I want to keep syncing and using my main installation. I guess I can stop syncing the parallel app, though.

**Comment by dae** [comment] 2021-02-15 11:38
I suggest you make sure you're on the latest computer version, and confirm if the issue exists in it when the new timezone code is enabled. If it does, then the computer version needs fixing; if you've confirmed it works there and the issue is only in AnkiDroid, then it likely means the new code hasn't been hooked up somewhere in the alpha.

**Comment by jparta** [comment] 2021-02-28 01:26
I tried this on the desktop version. The scheduling obeys the start-of-day whether the new timezone handling is used or not. It does not make a difference whether it's before or after the start-of-day. Current playstore version or alpha26 indeed don't work. There seems to be some difference in how these preferences are handled in droid vs desktop.

**Comment by david-allison-1** [comment] 2021-04-07 21:13
@jparta Are you still around to help with diagnosis? Sorry I missed this.

**Comment by david-allison-1** [comment] 2021-04-08 06:02
Wish I'd caught this earlier - was on V1 for far too long as I didn't want to take the hit of switching

We're not setting `rollover` from Anki commit: https://github.com/ankitects/anki/commit/b17a0552d061af360e35e1cda48b2d228c94b66e

https://github.com/ankidroid/Anki-Android/blob/837a3b3fcee7dd9ecdebf500d5183a9f36f9f230/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java#L657-L664

https://github.com/ankidroid/Anki-Android/blob/837a3b3fcee7dd9ecdebf500d5183a9f36f9f230/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java#L569-L572

**Comment by jparta** [comment] 2021-04-10 18:58
@david-allison-1
That's great. I can test on my end if needed.

**Comment by david-allison-1** [comment] 2021-04-10 19:20
That's fantastic, thanks!

I've put in a fix which is awaiting code Review. This should be fixed in one or two alpha's time. 

@Arthur-Milchior PR is pending your thoughts

**Closed** 2021-04-12 05:02 UTC
Labels: Anki Ecosystem Compatibility, Keep Open, V2 Scheduler
