### ISSUE TITLE
[Bug] Ankidroid is requesting all files permission since version 2.16.4

### ISSUE THREAD

**Issue by hyperstown** [ankidroid/Anki-Android#14381] opened 2023-09-03 07:05 UTC
###### Reproduction Steps

1. Upgrade from 2.16.3 to 2.16.4
2. Open app

###### Expected Result

Do not request all files permission.

###### Actual Result

When app opens it redirects to Access all files permission setting.

###### Debug info
<details>
<summary>
Expand debug info
</summary>

```log
AnkiDroid Version = 2.16.4 (67fd45a351c44c46c844aa35a402b98a2a487f68)

Android Version = 13

ProductFlavor = full

Manufacturer = Sony

Model = Xperia XZ3

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Xperia XZ3 Build/TQ3A.230605.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.131 Mobile Safari/537.36

ACRA UUID = 87ee21e2-e3eb-41ee-9948-613eddc093ee

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```
</details>

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2023-09-03 12:48
In a nutshell, this only applies to GitHub/F-Droid releases, not ones from the Play store. The reason is to keep your collection safe in a directory that won't be removed if the app is uninstalled.

Duplicate of #13574

**Closed by BrayanDSO** 2023-09-03 12:48 UTC
