### ISSUE TITLE
Crash when adding image using camera- in galaxy note2

### ISSUE THREAD

**Issue by fidiG** [ankidroid/Anki-Android#4799] opened 2018-03-01 05:27 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by mikehardy** [comment] 2018-03-02 18:43
Hi there! Crash issues are always serious and I'd like to look at this, but the information here is very sparse. What version of AnkiDroid? What version of Android? That along with exact steps to reproduce and/or debug info are vital to figure out what's going on. Without those there isn't much I can do to help unfortunately

**Comment by fidiG** [comment] 2018-03-04 05:28
Hello again


Galaxy note 2 -  GT-N7100

Android:  4.4.2

Ankidroid: 2.8.3


If there is something else you need to know please reply


Thank you so much for responding. I really need this feature. Hope you can help





Sent with SolMail App<https://play.google.com/store/apps/details?id=net.daum.android.solmail>


--------- Original Message ---------
From: Mike Hardy
To: ankidroid/Anki-Android
Date: Fri Mar 02 19:43:22 CET 2018
Subject: Re: [ankidroid/Anki-Android] Crash when adding image using camera- in galaxy note2 (#4799)

Hi there! Crash issues are always serious and I'd like to look at this, but the information here is very sparse. What version of AnkiDroid? What version of Android? That along with exact steps to reproduce and/or debug info are vital to figure out what's going on. Without those there isn't much I can do to help unfortunately

**Comment by fidiG** [comment] 2018-03-06 19:40
Debug info:

AnkiDroid Version = 2.8.3


Android Version = 4.4.2


ACRA UUID = 933bab1d-c1e1-434a-ae2c-8c935a364731



I want to that this camera crash is started after the last update


Anyway even if you cannot solve the problem thank you for your time





Sent with SolMail App<https://play.google.com/store/apps/details?id=net.daum.android.solmail>


--------- Original Message ---------
From: Mike Hardy
To: ankidroid/Anki-Android
Date: Sun Mar 04 14:25:47 CET 2018
Subject: Re: [ankidroid/Anki-Android] Crash when adding image using camera- in galaxy note2 (#4799)

Hello!

That does help - but for crash bugs in particular it will help to have the contents of the “debug info” mentioned in the bug report template with this link explaining how to get them: https://docs.ankidroid.org/help.html <https://docs.ankidroid.org/help.html>

If there was a crash-reporting dialog (and there should have been?), that may allow us to cross-reference your ankidroid installation id with the otherwise-anonymous crash report so we can hopefully find the stacktrace telling us where in AnkiDroid the crash happened.

Just to set expectations, I’m not familiar with how AnkiDroid uses the camera exactly, but camera issues in Android in general may be problems close enough to the hardware layer that we may be able to prevent the crash in response to an issue but we may not be able to actually get the feature to work. I will say that Android 4.4.2 is pretty old and while an unofficial port of the custom ROM lineageos isn’t something I’d normally recommend it looks like your device has been orphaned by Samsung. I’ve had the same issue with a Samsung phone before (the J5) and I had good luck even with an unofficial LineageOS, and there is one available for your device as well - info here https://forum.xda-developers.com/galaxy-note-2/orig-development/rom-cyanogenmod-14-0-n7100-t3487568 <https://forum.xda-developers.com/galaxy-note-2/orig-development/rom-cyanogenmod-14-0-n7100-t3487568>

If the feature is really vital and it’s a problem we can’t work around after we’ve seen the stack trace, it may be that moving from Android 4.4 to Android 7.1 could do the trick...

-Mike

**Comment by mikehardy** [comment] 2018-03-11 16:01
@timrae  I think you're the ACRA cross-referencing jefe - anything for ID 933bab1d-c1e1-434a-ae2c-8c935a364731 ?

**Comment by timrae** [comment] 2018-05-11 05:14
No crash reports for that ID unfortunately... 
@fidiG are you still having the same issue? If so could you please un-install + re-install AnkiDroid, then reproduce the crash again, and finally upload your new debug info?

**Comment by mikehardy** [comment] 2018-09-14 03:11
I'm going to close this as I know I fixed a camera crash bug recently related to permissions, and I can't reproduce this otherwise. Please feel free to re-open if this is still a problem

**Closed by mikehardy** 2018-09-14 03:11 UTC
Labels: waitingforfeedback

**Comment by mikehardy** [comment] 2020-03-02 03:55
I think this was maybe a different root cause and #5782 might resolve it
