### ISSUE TITLE
Color of status bar doesn't match that of toolbar in night mode

### ISSUE THREAD

**Issue by street62** [ankidroid/Anki-Android#3805] opened 2015-11-02 14:46 UTC
(Sorry, I'm not a English speaker, so my English is probably awkward.)

In night mode, the color of status bar doesn't match that of toolbar. 
Color matching in default daytime mode

**Comment by street62** [comment] 2015-11-02 14:54
(Oh, my touch was wrong.)

Color matching in default daytime mode is good. But in night mode, the color of status bar is just 'black', so it looks little bit weird, and doesn't seem  to be applying material design look. I hope you fix this.

**Comment by eginhard** [comment] 2015-11-03 00:57
This is quite a subjective issue with some people preferring (in general, not just for the status bar) a dark-grey mode and others a mode with mainly fully black elements. In a later version, there'll hopefully be the possibility to customise colours to your individual preferences.

Duplicate of #3757

**Closed by eginhard** 2015-11-03 00:57 UTC
