### ISSUE TITLE
Share to AnkiDroid card puts 'Share via' to the front

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#6673] opened 2020-07-13 22:16 UTC
###### Reproduction Steps

1. Select a word (**Enterprise** in the screenshot)
2. Tap Share
3. Tap AnkiDroid card

###### Expected Result
Selected word in the Front field

###### Actual Result
'Share via' in the Front field, selected word in the Back field
Sharing to other apps shares only the word.

![2020-07-14 01 05 15](https://user-images.githubusercontent.com/7422433/87358974-750f0780-c556-11ea-9d7b-73d299d96e01.jpg)

###### Debug info
```
AnkiDroid Version = 2.12.0beta5
Android Version = 9
ACRA UUID = 56339d73-9c19-4c5f-babf-90831b5a8cef
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Probably, somehow relevant to #6323 and #5023

**Comment by Arthur-Milchior** [comment] 2020-07-14 23:15
I can't reproduce.
Does the problem appear if you select the text in a specific app, or with all app?
Can you test to select text in official google app, or app from your phone creator, and see if it does the same thing ?

**Comment by homocomputeris** [comment] 2020-07-15 09:03
Ok, it seems to happen only with Firefox Beta. But 'share via' isn't added when I share to other apps

**Comment by Arthur-Milchior** [comment] 2020-07-15 20:42
Are you okay if I close this report then ? It seems we can't deal with it ourself, sorr
y.

**Closed** 2020-07-16 20:15 UTC
