### ISSUE TITLE
Convert uses of startActivityForResult to new Activity APIs

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8602] opened 2021-04-14 11:49 UTC
The old method of passing information to / starting / receiving results from one Activity to/from another Activity is deprecated in general, and there is a new way that we have tested in #8356 by converting just the Fragment Activities.

The rest of the codebase should be converted using the same general conversion style you may see in #8356 such that all uses of startActivityForResult/onActivityResult use the new androidx.activity APIs

Not the highest priority item, but consistent style in the whole codebase is a good thing, so this would be nice to have

**Comment by nicdard** [comment] 2021-04-14 13:38
I would be happy to help with this :)

**Comment by nicdard** [comment] 2021-04-14 18:02
Can I start work on this, and in case, what would you prefer: one only PR with the whole change, or to split it per activities involved in the exchange?

**Comment by mikehardy** [comment] 2021-04-14 19:29
Fantastic - I think just one PR per Activity, they should be separate - and please start with just one prior to posting all the others - to make really sure the style looks good and (hopefully) save time for everyone in case there is something that needs tuning before implementing it in all activities

**Comment by divyansh-dxn** [comment] 2022-03-12 20:34
Hey! Can I work on it?

**Comment by david-allison** [comment] 2022-03-12 20:39
Sure. One class as a time - don't do them all at once

**Comment by divyansh-dxn** [comment] 2022-03-12 20:42
I'm on it.

**Comment by vikashprajapati** [comment] 2022-10-15 05:05
Hey, this issue is still open. Is there anything that I can help in, Please let me know.

**Comment by divyansh-dxn** [comment] 2022-10-15 05:48
Yeah @vikashprajapati this issue is still open and if you want you can get it assigned. I had been working on it earlier.

**Comment by rishujam** [comment] 2022-12-29 18:01
Hey @divyanshdxn, I want to work on this issue

**Comment by Prachi-Jamdade** [comment] 2023-02-18 01:31
@david-allison, I see that the issue is still open. I can take this up.

**Comment by deekshatw** [comment] 2023-02-22 09:24
If the issue's still open, can I work on it? @david-allison

**Comment by david-allison** [comment] 2023-02-22 10:04
Absolutely. Thanks!

**Comment by Prachi-Jamdade** [comment] 2023-02-22 10:05
It is assigned to me. You can take this up If I'm no longer working on it @deekshatw

**Comment by vibhu7005** [comment] 2023-08-15 07:48
Hi @david-allison Let me know if the issue is still open.

**Comment by mikehardy** [comment] 2023-08-31 15:49
@dae likely still a task - this issue is kind of an umbrella. Criteria to close would be codebase audit for string startActivityForResult - shouldn't appear anywhere (I haven't checked) and if it does, each instance needs a checkbox in the description here and a PR to convert

**Comment by vibhu7005** [comment] 2023-08-31 17:30
Let me know if I can help here

**Comment by nfragiskatos** [comment] 2023-10-26 03:19
@mikehardy, @david-allison 

This issue hasn't had an update in a bit, so I just had a question about it. I noticed that there doesn't seem to by any direct calls to `startActivityForResult` outside of `AnkiActivity`, but there are still many calls to 

- `AnkiActivity.startActivityForResultWithAnimation`, and 
- `AnkiActivity.startActivityForResultWithoutAnimation`. 
 
Should we be transitioning those calls over to

- `AnkiActivity.launchActivityForResultWithAnimation`
- There doesn't seem to be an analogous *`WithoutAnimation` helper for this one. Is it unnecessary?

**Comment by mikehardy** [comment] 2023-10-27 02:42
Interesting...

Question 1, probably
Question 2 - there is an intersection here with an issue I just logged for an api34 deprecation about predictive back support where animation override now needs to specific in and out animation style

Perhaps the change is to change the launch API to take an in and out style, make one of the styles "none" and alter callers to launch with the animations they need (... possibly "none") ?

**Comment by Aditya8840** [comment] 2023-11-23 20:21
Hi, could you please assign me if the issue is still open?

**Comment by mikehardy** [comment] 2023-11-23 20:27
This one has an intersection with predictive back at this point, I *think*, which means @lukstbit may have more wisdom on what's left to do here than I do ?

**Comment by lukstbit** [comment] 2023-11-24 10:19
These issues can be handled independently, the predictive back needs to be handled in the classes that get started for result and the startActivityForResult deprecation will be handled in the classes that start an activity for result. There might be activities which both handle back and call startActivity* but these issues should be handle separately. 

@Aditya8840 There's no need to be assigned. If you want to work on this, look at what you want to fix for this issue and then leave a comment here mentioning it so other can see who's working on what.

@nfragiskatos 

> Should we be transitioning those calls over to
> 
>   AnkiActivity.launchActivityForResultWithAnimation

Yes.

> There doesn't seem to be an analogous *WithoutAnimation helper for this one. Is it unnecessary?

There isn't one but it should be added as the connected method, startActivityForResultWithoutAnimation, has usages and we should replicate the current behavior. Seems pretty simple to add based on the source code of startActivityForResultWithoutAnimation.

**Comment by nfragiskatos** [comment] 2023-11-26 18:49
@lukstbit, 

The `AnkiActivity` class does have the following private function

```
private fun launchActivityForResult(
  intent: Intent?,
  launcher: ActivityResultLauncher<Intent?>,
  animation: Direction?
)
```

What's your opinion on forgoing the `launchActivityForResultWith/WithoutAnimation` functions and instead just exposing the private `launchActivityForResult` function? 

I'm not sure the the calls to `enableIntentAnimation` and `enableActivityAnimation` that the other functions do are necessary with the `ActivityResultLauncher` approach.

Just messing around with calling `launchActivityForResult` directly with `Direction` values (including NONE) seem to work as expected.

**Comment by lukstbit** [comment] 2023-11-29 14:57
@nfragiskatos Until we use only the new API I don't want to drop the current code. This issue has a lower priority.

**Closed** 2023-12-15 16:05 UTC
Labels: Help Wanted, Good First Issue!, Keep Open, Deprecation, Dev
