### ISSUE TITLE
deprecation: compileSdk 33 issues

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#12364] opened 2022-09-10 00:06 UTC
Hi there! Thanks for picking up a deprecation task - we think these are good first issues because:

1- typically you can just search the codebase for a relevant string and find *where* the work is quickly
2- typically there is documentation upstream in the Google Android Developer docs that explain how the old API worked, why it is deprecated, and then there is documentation for the new API
3- the functionality is already working, switching to a new implementation has a clear standard to meet, it should be obvious the change was good (because the feature was working, and should just still be working

These are the collection of interfaces deprecated as we switched compileSdkVersion from 32 to 33:

- [ ] Activity.onBackPressed
- [x] Intent.getParcelableExtra
- [x] Bundle.getSerializable
- [x] Intent.getSerializable
- [x] Parcel.readSparseArray
- [x] Parcel.readSerializable
- [x] Parcel.readList
- [x] Bundle.getParcelableArrayList
- [x] Bundle.get (array access: `b["key"]``)
- [x] Bundle.getParcelable
- [x] PackageManager.resolveActivity
- [x] PackageManager.getPackageInfo
- [x] PackageManager.queryIntentActivities
- [x] PackageManager.resolveService

The task is to:

-  pick one no one else has commented on here, write a comment here that you are working on that one
- search for the second part of the string (for example "onBackPressed")
- verify that it has a `@Suppress("deprecation")` near it signaling that you found the spot!
- Add a Timber.d in the area to make sure you can exercise the feature on the emulator before changing it (you should see your log message)
- read the docs on the deprecated API and the new API, and convert the code to the new API
- make sure `./gradlew jacocoTestReport ktlintCheck` passes on your work locally, and that the feature still works
- open a PR with your changes

Ask if you have any questions!

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/12359#issuecomment-1241571435_

**Comment by priyanshuborole** [comment] 2022-09-11 07:21
@david-allison I would like to work on Activity.onBackPressed deprecation.

**Comment by mikehardy** [comment] 2022-09-11 12:44
@priyanshuborole great - unless someone has said they are working on something - no need to ask permission, just state (with authority! go for it!) that you are working on such and such. Good luck, and thanks

**Comment by criticalAY** [comment] 2022-09-14 17:53
@david-allison  I was working on Intent.getParcelableExtra but when I am trying to update the method it gives an error and not recognizing the API level 33 intent removing the @supress also throws an error while building up the application.

**Comment by david-allison** [comment] 2022-09-14 18:03
> read the docs on the deprecated API and the new API, and convert the code to the new API

Look up the method: `getParcelableExtra`: https://developer.android.com/reference/android/content/Intent#getParcelableExtra(java.lang.String,%20java.lang.Class%3CT%3E)

https://developer.android.com/reference/android/content/Intent#getParcelableExtra(java.lang.String,%20java.lang.Class%3CT%3E) is recommended instead.

* Look into our `Compat` mechanism and see if we can use this here: https://github.com/ankidroid/Anki-Android/blob/57958d263252e9914b2c25ef68bffedc1abc292e/AnkiDroid/src/main/java/com/ichi2/compat/

**Comment by criticalAY** [comment] 2022-09-14 19:02
> > read the docs on the deprecated API and the new API, and convert the code to the new API
> 
> Look up the method: `getParcelableExtra`: https://developer.android.com/reference/android/content/Intent#getParcelableExtra(java.lang.String)
> 
> https://developer.android.com/reference/android/content/Intent#getParcelableExtra(java.lang.String,%20java.lang.Class%3CT%3E) is recommended instead.
> 
> * Look into our `Compat` mechanism and see if we can use this here: https://github.com/ankidroid/Anki-Android/blob/57958d263252e9914b2c25ef68bffedc1abc292e/AnkiDroid/src/main/java/com/ichi2/compat/

I found https://stackoverflow.com/questions/73019160/android-getparcelableextra-deprecated/73311814#73311814 which explains the usability of getPracelableExtra in API >=33

**Comment by SvitlanaShumilova** [comment] 2022-09-14 21:38
@david-allison Working on Parcel.readSparseArray

**Comment by sumanarlert** [comment] 2022-09-15 16:05
Hey, I was working on Bundle.getParcelable.
The method in API level 33 is
`public T getParcelable (String key, Class<T> clazz)`

I'm not sure which class should be mentioned here 
`mPreviousImageUri = savedInstanceState.getParcelable("mPreviousImageUri")`
Is it Uri::class.java ?

Also if I add a class, it says Call requires API level 33, should I surround it with `if (Build.VERSION.SDK_INT >= 33)` ?

**Comment by david-allison** [comment] 2022-09-15 20:23
> Hey, I was working on Bundle.getParcelable. The method in API level 33 is `public T getParcelable (String key, Class<T> clazz)`
> 
> I'm not sure which class should be mentioned here `mPreviousImageUri = savedInstanceState.getParcelable("mPreviousImageUri")` Is it Uri::class.java ?
> 
> Also if I add a class, it says Call requires API level 33, should I surround it with `if (Build.VERSION.SDK_INT >= 33)` ?

It's a Uri:

See: https://github.com/ankidroid/Anki-Android/blob/3f464f6f4cdc35a8b62e9ad9f93a2bb6efbe3306/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt#L85

See our [compat infrastructure](https://github.com/ankidroid/Anki-Android/tree/main/AnkiDroid/src/main/java/com/ichi2/compat) for how to handle this. There's already a thread on [Discord](https://discord.gg/qjzcRTx) where I've walked someone through this

**Comment by david-allison** [comment] 2022-09-16 02:21
#12410 adds this infra, and should be a good starting point

**Comment by criticalAY** [comment] 2022-09-16 19:29
> @david-allison I would like to work on Activity.onBackPressed deprecation.

are you still working on it?

**Comment by priyanshuborole** [comment] 2022-09-16 19:31
> > @david-allison I would like to work on Activity.onBackPressed deprecation.
> 
> Hey! are you still working on it?

Yes I am working on it, give me 1-2 days if not possible I will update you

**Comment by criticalAY** [comment] 2022-09-17 12:16
> Hey, I was working on Bundle.getParcelable. The method in API level 33 is `public T getParcelable (String key, Class<T> clazz)`
> 
> I'm not sure which class should be mentioned here `mPreviousImageUri = savedInstanceState.getParcelable("mPreviousImageUri")` Is it Uri::class.java ?
> 
> Also if I add a class, it says Call requires API level 33, should I surround it with `if (Build.VERSION.SDK_INT >= 33)` ?

Hey! Are you working on it? coz if not then I would like to overtake it.

**Comment by SvitlanaShumilova** [comment] 2022-09-17 17:07
I'm working on Parcel.readSparseArray and there is only one place it occurs, which is com/ichi2/anki/FieldEditLine.kt:249
But it looks like it's never used in the project and I can't find a way to test it. What am I supposed to do?

**Comment by n1snt** [comment] 2022-09-18 08:28
Is anyone working on PackageManager depreciated interfaces?
If not I would love to work on it.

**Comment by criticalAY** [comment] 2022-09-18 08:32
> Is anyone working on PackageManager depreciated interfaces? If not I would love to work on it.

I don't think anyone is

**Comment by sumanarlert** [comment] 2022-09-18 09:51
> Hey! Are you working on it? coz if not then I would like to overtake it.

I'm not able to figure out a few things. So sure go ahead. I'll just watch and learn 😂

**Comment by priyanshuborole** [comment] 2022-09-19 04:07
> > Hey, I was working on Bundle.getParcelable. The method in API level 33 is `public T getParcelable (String key, Class<T> clazz)`
> > I'm not sure which class should be mentioned here `mPreviousImageUri = savedInstanceState.getParcelable("mPreviousImageUri")` Is it Uri::class.java ?
> > Also if I add a class, it says Call requires API level 33, should I surround it with `if (Build.VERSION.SDK_INT >= 33)` ?
> 
> Hey! Are you working on it? coz if not then I would like to overtake it.

yes, you can start working on it.

**Comment by criticalAY** [comment] 2022-09-19 18:57
Could you please review the last PR so that I can move on to the other one?

**Comment by mikehardy** [comment] 2022-09-19 19:14
@criticalAY if you examine the volume of work in flight at any time (https://github.com/ankidroid/Anki-Android/pulse) you'll see you have to have some patience, especially since we are essentially all volunteers. Sometimes things are very very fast, sometimes they sit, it is not predictable. However, if you feel you have that PR under control, you can take on another one - that's fine. I would only caution against having *too* many PRs in flight at once, but that would be like 5-6 - at that point it is usually a sign that things are not really being answered satisfactorily for some reason or they would be getting merged. In this case I think we're close, go ahead on something new if you like, while reviewers catch up. Cheers!

**Comment by mikehardy** [comment] 2022-09-19 19:31
I believe the various SDK33 deprecations will not conflict with each other, each of them should be in different chunks of text which git should ideally be able to handle just fine on merge. Even if not, handling conflicts via git rebase / fixing conflicts / force push to your branch is one of the most powerful things you can learn as a modern software developer (where "modern" is defined as "we are all using git now"). Once you've got git rebase-merge/de-conflict/force-push down, there is almost nothing out of reach with regards to managing a source code repository and that's a powerful professional skill. So don't fear conflicts, in my opinion

**Comment by criticalAY** [comment] 2022-09-21 16:21
API 33 serializable bundle deprecation update #12463

**Comment by criticalAY** [comment] 2022-09-23 11:51
We are still working on it, right?

**Comment by mikehardy** [comment] 2022-09-23 12:04
@criticalAY - if you are looking for status updates, as mentioned before directly to you, with explanation, basically don't unless it really has been a while and then do so on the PR directly. But please note 2 days is not a while, and that's the timestamp on your last comment.

There will be periods of time, sometimes long periods, when no one is working on anything. It is a volunteer project and you cannot expect volunteers time, that is just a reality.

If this is a legitimate question about this issue specifically, unless it is closed it is still being worked on. It is not closed. We close issues not being worked on. I see 13 unchecked boxes above, so it is certainly an area of ongoing work.

**Comment by criticalAY** [comment] 2022-09-23 12:38
> will be periods of time, sometimes long periods,

Yes, I am aware of that fact as I already asked that on DC here just the issue of whether it's still up or dumped.

**Comment by mikehardy** [comment] 2022-09-23 13:16
If any decisions are made, they will be communicated, so no communication means no decision + no progress --> have patience please.

**Comment by n1snt** [comment] 2022-09-26 14:16
I'm currently working on `PackageManager.resolveActivity` deprecation.
There is one instance of it in `AdaptionUtil` which is used for checking if the device is running MIUI.
Can anyone please help me out in testing it? (Testing it using Timber)
I'm unable to get that part of the code to execute.

**Comment by criticalAY** [comment] 2022-09-30 09:01
Can we please review the last two PRs?

**Comment by siju-s** [comment] 2022-10-01 07:19
I will work on `PackageManager.getPackageInfo`.

**Comment by n1snt** [comment] 2022-10-01 17:12
I'm actually already working on PackageManager interfaces.

**Comment by SanjaySargam** [comment] 2022-11-12 20:09
@criticalAY 
Is there anyone working on `Bundle interface` ?

**Comment by criticalAY** [comment] 2022-11-12 20:15
> @criticalAY Is there anyone working on `Bundle interface` ?

Nope there were two bundle PRs made from my side but I recloned the repo which resulted in those PRs getting closed, so pick any bundle interface you like except those

**Comment by n1snt** [comment] 2022-11-12 20:15
I think @sumanarlert is working on Bundle.getParcelable except that I don't think anyone is working on any other Bundle interfaces.

**Comment by criticalAY** [comment] 2022-11-12 20:17
> I think @sumanarlert is working on Bundle.getParcelable except that I don't think anyone is working on any other Bundle interfaces.

He said he wants to watch and learn so I over took that (closed PR)

**Comment by SanjaySargam** [comment] 2022-11-12 20:26
So, I think no one is working on  `Bundle.getSerializable` .

**Comment by criticalAY** [comment] 2022-11-12 20:31
> So, I think no one is working on `Bundle.getSerializable` .
Ahmm I worked on it but sure if you want to fix it then go ahead. You can refer to the PR above(which is certainly closed now but it is of relevance you will get a clear idea of what you have to do) Those PRs are closed because of my stupidity but nvm

**Comment by SanjaySargam** [comment] 2022-11-12 20:33
> > So, I think no one is working on `Bundle.getSerializable` .
> > Ahmm I worked on it but sure if you want to fix it then go ahead. You can refer to the PR above(which is certainly closed now but it is of relevance you will get a clear idea of what you have to do) Those PRs are closed because of my stupidity but nvm

Ok Cool no worries

**Comment by HeadlessAngel** [comment] 2022-11-16 18:29
Is anyone working on  Activity.onBackPressed deprecation? If not I would like to try it

**Comment by criticalAY** [comment] 2022-11-16 20:28
> Is anyone working on Activity.onBackPressed deprecation? If not I would like to try it

Go ahead

**Comment by n1snt** [comment] 2022-11-21 20:46
@david-allison can I please get a review on these 2 deprecation PRs:
https://github.com/ankidroid/Anki-Android/pull/12550
https://github.com/ankidroid/Anki-Android/pull/12548

**Comment by sakxshi** [comment] 2023-02-21 09:10
Hey there, I am working on Parcel.readList .

**Comment by david-allison** [comment] 2023-02-21 13:25
> Hey there, I am working on Parcel.readList .

Should already be fixed: #13307

**Comment by sakxshi** [comment] 2023-02-21 14:24
> > Hey there, I am working on Parcel.readList .
> 
> Should already be fixed: #13307

Cool, no worries.

**Comment by david-allison** [comment] 2023-02-21 17:31
Additional info on `onBackPressed` from #13323

> **OnBackPressed Override Function is deprecated in Android 13** Android 13 has a new feature called **Predictive Back Gesture** which shows users that they are about to navigate back to the launcher from the application with back action.
> 
> Here is the warning that android studio will give on using onBackPressed on Android API level 33+
> 
> ![image](https://user-images.githubusercontent.com/94190717/220414065-377f7c7f-8f76-45a9-8c0f-a8722022e1c8.png)
> 
> Here is how you can replace onBackPressed in the code -
> 
> ```
> 
> onBackPressedDispatcher.addCallback(this /* lifecycle owner */, object : OnBackPressedCallback(true) {
>     override fun handleOnBackPressed() {
>         // Back is pressed... Finishing the activity
>         finish()
>     }
> })
> 
> // ====================================================
> /* Or for lambda simplicity: */
> // ====================================================
> onBackPressedDispatcher.addCallback(this /* lifecycle owner */) {
>     // Back is pressed... Finishing the activity
>     finish()
> }```
> ```

**Comment by mikehardy** [comment] 2023-03-29 23:03
@niryline that sounds great! Good luck

**Comment by MudssirAhmed** [comment] 2023-04-08 17:18
Hey @mikehardy, I migrated the deprecated code, But I'm getting some errors when I'm going to push the code and make a PR.
Can you help me to figure it out?

Here is the error code
`PS D:\Development\Open-Source\Anki-Android> git add .                                         
PS D:\Development\Open-Source\Anki-Android> git commit -m "Deprication OnBackPressed handled"
Running ktlint over these files:
AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateBrowserAppearanceEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
AnkiDroid/src/main/java/com/ichi2/anki/Info.kt
AnkiDroid/src/main/java/com/ichi2/anki/ModelBrowser.kt
AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.kt
AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsActivity.kt
AnkiDroid/src/main/java/com/ichi2/anki/preferences/Preferences.kt
AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/8.0.2/userguide/gradle_daemon.html
Process command line: C:\Program Files (x86)\Java\jre1.8.0_361\bin\java.exe -Xmx2560M -Dfile.encoding=UTF-8 -Duser.country=GB -Duser.language=en -Duser.variant -cp C:\Users\mudss\.gradle\wrapper\dists\gradle-8.0.2-bin\25jlreiuz6u3xu2phlpa2vv4m\gradle-8.0.2\lib\gradle-launcher-8.0.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.0.2
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2621440KB object heap


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

**Comment by mikehardy** [comment] 2023-04-09 01:46
@MudssirAhmed we use JDK11 normally for development. I would make sure that's the JDK in use. Looks like you attempted to use 8.

**Comment by MudssirAhmed** [comment] 2023-04-09 19:15
@mikehardy thanks for the comment, I created a PR for onBackPress depreciation handle. [PR](https://github.com/ankidroid/Anki-Android/pull/13586l)
Kindly review this PR.

**Comment by niryline** [comment] 2023-04-10 06:56
Oh @MudssirAhmed I was working on this... I guess I was too slow.

**Comment by dae** [comment] 2023-09-01 06:02
@david-allison there's a pending PR for the last remaining issue - should we ask them to update it?

**Comment by mikehardy** [comment] 2023-11-03 15:03
onBackPressed is the only remaining one, and we're going to track it in #14558

**Closed by mikehardy** 2023-11-03 15:03 UTC
Labels: Help Wanted, Good First Issue!, Keep Open, Deprecation
