### ISSUE TITLE
[Bug] Front of card not shown when returning to AnkiDroid from the background

### ISSUE THREAD

**Issue by fatbringer** [ankidroid/Anki-Android#14480] opened 2023-09-26 01:20 UTC
###### Reproduction Steps

1.  Launch ankidroid app, open a card with audio. 
2. Change to another app, or push ankidroid to the background by going back to the home screen 
3. The audio file with the card will keep on replaying. Sometimes it repeats itself without finishing the previous time
4. When returning to the ankidroid app, the words on the front of the card is gone from the view. 

###### Expected Result
The audio file should not play in the background. 

The front of the card should be displayed. 

###### Actual Result
Audio file plays repeatedly in the background, and the card view is bugged 

The front of the card is also not displayed when returning to the app

![Screenshot_2023-09-26-09-18-23-629_com.ichi2.anki.jpg](https://github.com/ankidroid/Anki-Android/assets/93758179/8e0e5732-ce41-40d7-9d27-81abdd8ef762)

![Screenshot_2023-09-26-09-18-49-344_com.ichi2.anki.jpg](https://github.com/ankidroid/Anki-Android/assets/93758179/ae1de5c7-4aee-487a-9f96-d5d7e19c067c)

###### Debug info

AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)
Android Version = 11
ProductFlavor = play
Manufacturer = Xiaomi
Model = Redmi Note 8
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Build/RKQ1.201004.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36
ACRA UUID 842fe7cf-0e14-44a4-abc6-3e5ddbe8d583
New schema = false
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by eginhard** [comment] 2023-09-27 16:02
Duplicate of #14414

**Comment by fatbringer** [comment] 2023-09-28 00:35
@eginhard Hey there. I noticed that the issue has been closed.

I saw the other issue that was raised and I want to say my issue is slightly different.

The audio replays itself in the background.

But my issue has the front of the card not showing as well. These are 2 different problems. Could you please look into that too?

**Comment by eginhard** [comment] 2023-09-28 06:35
Ok, I've updated the title to clarify. If you already know a similar issue exists, please mention it and clearly describe how your issue is related/different.

@traycerb Do you have the same behaviour of the front of the card not showing when returning to the app?

I don't see either issue on 2.17alpha1/Android 13.

**Comment by traycerb** [comment] 2023-10-01 07:27
> Ok, I've updated the title to clarify. If you already know a similar issue exists, please mention it and clearly describe how your issue is related/different.
> 
> @traycerb Do you have the same behaviour of the front of the card not showing when returning to the app?
> 
> I don't see either issue on 2.17alpha1/Android 13.

I can't recall the front of the card behavior in my cases, in part because the behavior described here is slightly different than mine.  

what's described here sounds immediate, but in mine, there was a delay of many minutes,  possibly even more than an hour, so I didn't typically remember where I left off.

I don't have the issue described here.  If I switch away, the audio stops immediately, and when I return, the card is where it left off.

**Comment by david-allison** [comment] 2023-11-27 00:05
I've prepared a fix for the audio.

AnkiDroid should scroll to the back of the card once the images are loaded:

https://github.com/ankitects/anki/blob/3713c86373bd57ba15aefd40a0c35b6378f63948/ts/reviewer/index.ts#L190-L192

This looks like what has occurred here

**Closed** 2023-11-28 19:04 UTC
Labels: 2.17-alpha
