### ISSUE TITLE
[Bug] Chemical Equations not supported in MathJax

### ISSUE THREAD

**Issue by Michael35699** [ankidroid/Anki-Android#8016] opened 2021-01-14 02:30 UTC
###### Reproduction Steps

1.  Create a card with a MathJax equation.
2.  Include a chemical equation in the MathJax using the LaTeX command `\ce`

###### Expected Result

Like in the desktop app, it should render a chemical equation.

###### Actual Result

It shows an error that shows that `\ce` is not a recognized LaTeX command.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid.
-  [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2021-01-14 12:12
Hi there! I think this may be fixed in the 2.15 version currently in development
Can you either switch to the alpha google play track https://docs.ankidroid.org/#betaTesting or try a parallel alpha build to check? https://github.com/ankidroid/Anki-Android/releases/tag/v2.15alpha22

**Comment by Michael35699** [comment] 2021-01-14 13:53
I am currently on 2.15alpha22, and the problem still seems to exist.

**Comment by mikehardy** [comment] 2021-01-14 13:56
Darn - that's unfortunate. I thought we had addressed this as I have a memory of some discussion on it, but perhaps not

https://github.com/ankidroid/Anki-Android/blob/8e73956efc03b8ef97317e28cac38664569a270c/AnkiDroid/src/main/assets/mathjax/conf.js#L25

https://github.com/ankidroid/Anki-Android/tree/master/AnkiDroid/src/main/assets/mathjax/input/tex/extensions

mhchem is in there, what are we missing? Perhaps @hgiesel knows :thinking:

**Comment by hgiesel** [comment] 2021-01-15 14:28
I already noticed that issue here: #7915. It looks like no package-specific features work right now.

**Comment by mikehardy** [comment] 2021-01-15 14:29
Okay - going back over to the regression issue for discussion - if I understand correctly this is duplicate then and I'll close. Discussion should continue on #7915

**Closed by mikehardy** 2021-01-15 14:29 UTC
Labels: Waiting For Feedback
