### ISSUE TITLE
Double-tap zooming not working in the reviewer

### ISSUE THREAD

**Issue by glutanimate** [ankidroid/Anki-Android#4292] opened 2016-05-20 13:25 UTC
###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. Create a new note using the basic note model (to have a clean slate without any custom CSS or JS interfering)
2. Open the note in the reviewer or preview window
3. Try to zoom in by double-tapping and sliding your finger up and down (like you would in a web browser like Chrome)
###### Expected Result

Card zooming in/out following the gesture.
###### Actual Result

~~The zoom gesture only seems to work sporadically. It seems to be most reliable when invoking it on the top-most area of the card (right below the header with the new/due counts).~~
Actually, it looks like it's only working when invoked on the margin of the card, be it top, bottom or on the sides.
###### Further remarks

Some settings that might be relevant:
- Gestures: off (is there any chance this might have something to do with the custom double-tap gesture?)
- text and image zoom levels: all set to the defaults
- whiteboard: disabled
###### Debug info

AnkiDroid version = 2.6alpha33 (but I've been experiencing this issue at least since the upgrade to material design)

Android version = 4.4.4

**Comment by Glutanimate** [comment] 2016-06-14 09:37
Looks like with #4310 double-tap to zoom has now stopped working completely. I guess it's because the margins that were removed in this PR were the last regions that were responsive to that gesture. I think it would be quite important to reimplement another way to zoom with one finger, be it as the classical double-tap to zoom gesture or toggleable zoom buttons. One-handed use of Ankidroid has now become far more difficult than before.

**Comment by johtso** [comment] 2018-04-10 10:41
Would be great to be able to zoom when using ankidroid one-handed. I'm studying image heavy cards where I need to do quite a bit of zooming in to see detail and this is a bit of an issue..

**Comment by tanmayChakrawarty** [comment] 2021-03-15 16:28
Hello Sir @david-allison-1 can I work on this issue?

**Comment by david-allison-1** [comment] 2021-03-15 20:52
> Hello Sir @david-allison-1 can I work on this issue?

Sure! And no need to call me sir :)

**Comment by tanmayChakrawarty** [comment] 2021-03-17 12:58
Hello, @david-allison-1 I want to know whether it will be good to add zoom-in, zoom-out buttons at the bottom right corner in the reviewer.

**Comment by david-allison-1** [comment] 2021-03-17 13:21
> Hello, @david-allison-1 I want to know whether it will be good to add zoom-in, zoom-out buttons at the bottom right corner in the reviewer.

I don't feel that would go down well with our userbase. I personally feel they'd get in the way of content.

**Comment by tanmayChakrawarty** [comment] 2021-03-17 13:29
> > Hello, @david-allison-1 I want to know whether it will be good to add zoom-in, zoom-out buttons at the bottom right corner in the reviewer.
> 
> I don't feel that would go down well with our userbase. I personally feel they'd get in the way of content.

Can you tell me where can I find the pinch to zoom-in and zoom-out feature code in the codebase?

**Comment by david-allison-1** [comment] 2021-03-17 13:37
It should be part of the WebView by default. Our code will be in `AbstractFlashcardViewer`/`Reviewer`.

The first stage would be to confirm if the issue is still relevant. It appears from a first glance that zooming works as expected.

**Comment by tanmayChakrawarty** [comment] 2021-03-17 16:42
> It should be part of the WebView by default. Our code will be in `AbstractFlashcardViewer`/`Reviewer`.
> 
> The first stage would be to confirm if the issue is still relevant. It appears from a first glance that zooming works as expected.

Double-tap to zoom is not working but the pinch to zoom is working perfectly.

**Comment by tanmayChakrawarty** [comment] 2021-03-31 12:57
@david-allison-1 I am working on this issue for quite a few days almost 2 weeks and I come up with the conclusion that double touch is working perfectly there is no issue with this gesture but as this issue mentioned double touch to zoom there is no option like that in the preference when I enabled the double touch gesture so I think we have to implement a new function for this.

**Comment by david-allison-1** [comment] 2021-04-01 15:22
@tanmayChakrawarty If you can't reproduce this issue, is there a problem, or can we close this?

**Comment by tanmayChakrawarty** [comment] 2021-04-01 16:12
@david-allison-1 there is no issue with the double touch gesture it is working perfectly, there is no zoom feature in the double touch. So if this has low priority then we can close it otherwise we have to implement it.

https://user-images.githubusercontent.com/75254780/113322803-c3f20c80-9332-11eb-88af-2aad92a3c7dd.mp4

**Comment by david-allison-1** [comment] 2021-04-01 16:17
I think we should raise a new issue for a new gesture.

Closing this as "can't replicate".

**Closed by david-allison-1** 2021-04-01 16:17 UTC
Labels: Accepted, Enhancement, Good First Issue!, Help Wanted, Keep Open, Priority-Low
