### ISSUE TITLE
Notifications for specific deck

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ankidroid/Anki-Android#6589] opened 2020-06-30 11:50 UTC
Hi,

I use anki for school but also for other stuff. I'd like for the notifications to be only about some specific deck. For example : I'd like to have a notification if one of my filtered deck  fills up to more than a certain point.

Do you think it's interesting?

Thanks!

version : 2.11.3

**Comment by david-allison-1** [comment] 2020-06-30 14:56
Hi @thiswillbeyourgithub,

Thanks for the suggestion!

I /think/ this enhancement request is a duplicate of #4944 (if it is, feel free to close this and we'll move the discussion to a centralised issue).

Improving reminders and notifications is something that we all want to work towards. If you have any suggestions for the design of our new Reminder system, your input would be much appreciated.

We've made some massive improvements to the performance of notifications for AnkiDroid 2.12, but the entire system is still in need of redesign and an overhaul. I don't think anyone is actively looking at this right now, so designs and suggestions are more than welcome.

A list of issues that we have with the system is visible here: https://github.com/ankidroid/Anki-Android/labels/Advanced%20Reminders

Thanks,

David

**Closed** 2020-06-30 16:01 UTC
Labels: Advanced Reminders, Enhancement
