### ISSUE TITLE
Preserve JS window (global) object in same card

### ISSUE THREAD

**Issue by reinert** [ankidroid/Anki-Android#4896] opened 2018-07-03 12:52 UTC
When making advanced cards, using JS, I need to transfer some state from the Front to the Back of a card. I'm successfully using the `window` object in Anki Desktop. But in AnkiDroid, I noticed that the `window` object is not preserved in the same card.

Any idea on how to solve it?

**Comment by timrae** [comment] 2018-07-03 13:19
See #4868

There are some tips there. Maybe we should add something to the wiki...

Closing as not a bug report or feature request (questions go on the forum)

**Closed by timrae** 2018-07-03 13:19 UTC
