### ISSUE TITLE
[Enhancement] Make Preferences Searchable

### ISSUE THREAD

**Issue by haran2248** [ankidroid/Anki-Android#8342] opened 2021-03-25 21:34 UTC
**Is your feature request related to a problem? Please describe.**
The settings is very large,It will be useful to have a seachView attached to the toolbar

**Describe the solution you'd like**
The SearchView attached will be able to redirect the user the required setting

**Describe alternatives you've considered**
Open to discussion from members

**Additional context**

**Comment by prince02765** [comment] 2021-03-26 03:54
It's very useful to add Searchbar on the toolbar.

When we added Searchbar we can also show tags the relevant search or most frequently search in Searchbar. something like this.

so, user can easily find.

![Settings_Suggestions](https://user-images.githubusercontent.com/69643676/112574752-f8d30080-8e14-11eb-97c2-6210cc28d88b.jpg)

**Comment by david-allison-1** [comment] 2021-03-26 06:59
Seems useful. Would you like to work on this?

**Comment by prince02765** [comment] 2021-03-26 07:09
I definitely try from my side, if I can make exactly something like this then sure I made it.

I'm working on it.

**Comment by david-allison-1** [comment] 2021-03-26 07:15
It'd be fair to give @haran2248 a chance to request the issue, as he raised it. Let's give it 24 hours

**Comment by prince02765** [comment] 2021-03-26 07:18
Okay, No Problem

**Comment by haran2248** [comment] 2021-03-26 08:53
> It'd be fair to give @haran2248 a chance to request the issue, as he raised it. Let's give it 24 hours

Yeah I have started working on this

**Comment by iamvs-2002** [comment] 2021-04-03 08:14
This is a great issue. Probably this might help you: https://developer.android.com/reference/android/widget/AutoCompleteTextView
Because there is dictionary support in the app, the dictionary words can be stored in a string array and hence used to show the nearest suggestions to the user. Do let me know if you need any help with the same.

**Comment by iamvs-2002** [comment] 2021-04-03 08:36
You can also use this wonderful library: https://github.com/mancj/MaterialSearchBar

**Comment by david-allison-1** [comment] 2021-06-02 10:08
@haran2248 do you plan to work on this, or have a partial PR to save effort for the next person?

**Comment by iamvs-2002** [comment] 2021-06-02 13:25
Please assign me this issue if no one else is working on it. I want to try this one.

**Comment by david-allison-1** [comment] 2021-06-02 13:32
Sounds good to me, thanks!

**Comment by iamvs-2002** [comment] 2021-06-02 14:00
> Sounds good to me, thanks!

Thanks a lot for assigning it to me. I'll report to you soon about my progress.

**Comment by david-allison-1** [comment] 2021-08-01 17:51
Hi @iamvs-2002, are you still working on this?

**Comment by david-allison-1** [comment] 2021-08-01 17:51
Added "Keep Open" as it's been something on my mind for a while

**Comment by iamvs-2002** [comment] 2021-08-02 10:18
> Hi @iamvs-2002, are you still working on this?

Hey @david-allison-1 
Yeah, I have been working on the issue. I have made up the settings menu, but I am not sure how to show the suggestions or the search entries there, as I am not able to find the menu for the Settings.

**Comment by david-allison-1** [comment] 2021-08-02 14:14
> > Hi @iamvs-2002, are you still working on this?
> 
> Hey @david-allison-1
> Yeah, I have been working on the issue. I have made up the settings menu, but I am not sure how to show the suggestions or the search entries there, as I am not able to find the menu for the Settings.

I'm not sure I understand this. Could you explain in more detail, or push your work to a local branch so I could see what the problem is

**Comment by iamvs-2002** [comment] 2021-08-02 15:06
> > > Hi @iamvs-2002, are you still working on this?
> > 
> > 
> > Hey @david-allison-1
> > Yeah, I have been working on the issue. I have made up the settings menu, but I am not sure how to show the suggestions or the search entries there, as I am not able to find the menu for the Settings.
> 
> I'm not sure I understand this. Could you explain in more detail, or push your work to a local branch so I could see what the problem is

Sure, let me post it on Discord.

**Comment by david-allison-1** [comment] 2021-08-02 15:08
It's best to keep a copy of the discussion here so we have a record of what's happened

**Comment by iamvs-2002** [comment] 2021-08-02 16:19
> It's best to keep a copy of the discussion here so we have a record of what's happened

Alright. 
So I am confused on how to fetch the items to be put on the search result.
Like there must be some list for everything in the setting, or should I do it manually for every setting available in the Setting menu?

**Comment by david-allison-1** [comment] 2021-08-02 17:15
Look for how other apps do it to see if there's a good design

If that doesn't come up with anything, expand each of our XML files, convert the `@StringRes int` into a string, and search on those

**Comment by iamvs-2002** [comment] 2021-08-03 04:34
> Look for how other apps do it to see if there's a good design
> 
> If that doesn't come up with anything, expand each of our XML files, convert the `@StringRes int` into a string, and search on those. We can't have more than 100 settings

Alright David, I am on it. I will report to you about the same in 2 days.

**Comment by iamvs-2002** [comment] 2021-08-03 15:01
> > Look for how other apps do it to see if there's a good design
> > If that doesn't come up with anything, expand each of our XML files, convert the `@StringRes int` into a string, and search on those. We can't have more than 100 settings
> 
> Alright David, I am on it. I will report to you about the same in 2 days.

@david-allison-1 I am really sorry to inform you that, I am no longer able to work on this issue for a couple of days. My system got crashed just now, and it will need some time. You may give the same to someone else. Thank you.

**Comment by david-allison-1** [comment] 2021-08-04 02:26
Sorry to hear that, good luck with getting things sorted!

**Comment by zihanxu3** [comment] 2021-11-19 03:33
Hi can I take the issue? Thanks!

**Comment by david-allison-1** [comment] 2021-11-19 14:07
Sure! Thanks

**Comment by zihanxu3** [comment] 2021-11-30 03:39
@david-allison-1 Hi David I think I am having the same issue as the previous person working on this issue - is there a way to extract all the settings as a list or some sort? Thanks!

**Comment by david-allison-1** [comment] 2021-11-30 21:58
> @david-allison-1 Hi David I think I am having the same issue as the previous person working on this issue - is there a way to extract all the settings as a list or some sort? Thanks!

Nope, you'll need to do so manually:

* Go through each of the preference XML files
* Build an abstraction to extract the necessary text (title/summary). This can either be the Android class, or design an XML reader yourself

For an extension, some preferences will have their title/summary changed in `Preferences.java`

It's a design decision as to:

* Use the screen classes that we already have
  * This will be more accurate, but will set all preferences when the screen is opened
* Allow each preference to be extended manually with additional strings

**Closed** 2022-08-15 11:54 UTC
Labels: Enhancement, Accepted, Keep Open
