### ISSUE TITLE
Regression Test: Search for decks with wildcard

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7394] opened 2020-10-16 06:10 UTC
It'd be nice to have a regression test to ensure that there's no regressions for this issue. 

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/7392#issuecomment-709631885_

**Comment by david-allison-1** [comment] 2020-10-16 06:44
@anadi198 

To bring you through the process: a regression test is a piece of code that we automatically run, to ensure that 

* A bug was correctly identified
* The bug was fixed
* A future developer who knows less about the context won't re-introduce the same bug

----

Since you've already written code which fixes the problem, the process would be:

* Check out an old revision of the code before your fix was applied
* Write an automated test which demonstrates the problem (it should fail on the assertion that you make), but don't commit it
* Check out the current master
* Copy the same test into a branch off `master`
* Ensure that the test now passes
* Commit and send off a pull request.

----

For the Finder, we have a class `FinderTest`

A sample test:

https://github.com/ankidroid/Anki-Android/blob/0d906acee26c5337ce8b35de48aadc061d0813e4/AnkiDroid/src/test/java/com/ichi2/libanki/FinderTest.java#L339-L372

For this test:

* Add the method below the first test in the file - the linked test was an automated conversion of Anki Desktop's test
* Create a deck with a star in the name
* Make a note, and insert it into this deck (or make the note, and change the deck of the cards).
* Perform a search on the deck name
* Ensure that the card that was created is returned (count is 1).

`long deckId = addDeck("deck name")` will also be a useful code snippet. `did` is short for deckId and is used in the code.

----

As a final note, it's generally best to test one thing per test to ensure we can pinpoint exactly what fails if we have a problem. In this sense, the above test is bad. But I felt it was a good example which shows most functionality required to complete this.

Please don't hesitate to reach out if you need more guidance (likewise, let me know if you think this post was excessive)

**Comment by anadi198** [comment] 2020-10-16 07:40
@david-allison-1 Thanks a lot for taking the time to explain in such great detail, I'll dive right into it and hopefully get it done :)

**Comment by anadi198** [comment] 2020-10-16 09:20
```
long currentDid = addDeck("Basic::Test");
getCol().getConf().put("curDeck", currentDid);
Note n = super.addNoteUsingBasicModel("Test", "Note");
n.model().put("did", currentDid);
```
The example you shared had everything except for adding a new deck and selecting it so I've looked for it and found this piece of code. Am I correct to assume that `getCol().getConf().put("curDeck", currentDid);` is the way to select a Deck?

Once I've selected my test deck, I think I can simply use this from your example from above: 
```
Note note = col.newNote(); 
note.setItem("Front", "foo"); 
note.setItem("Back", "bar"); 
col.addNote(note); 
```
Also, there is no findDeck() in Collection, only findDupes(), findReplace(), etc. Can I directly call the method from Finder.java?

Thank you for your time! @david-allison-1

**Comment by anadi198** [comment] 2020-10-16 14:07
There was an error from RoboElectric since it requires Java 9 for SDK 29, so I added @Config.

Here's the code I wrote after looking at various places, it doesn't work though(always fails).
```
    @Config(sdk = 28)
    @Test
    public void test_findDeck() {
        String val = "*Yr1::Med2::CAS4::F4: Renal::BRS (zanki)::HY";
        Collection col = getCol();
        long currentDid = col.getDecks().id(val, true);
        getCol().getConf().put("curDeck", currentDid);
        Note note = col.newNote();
        note.setItem("Front", "foo");
        note.setItem("Back", "bar");
        col.addNote(note);
//        long cid = note.cards().get(0).getId();
        ensureCollectionLoadIsSynchronous();
        ActivityController<CardBrowser> multimediaController = Robolectric.buildActivity(CardBrowser.class, new Intent())
                .create().start();
        multimediaController.resume().visible();
        saveControllerForCleanup(multimediaController);
        advanceRobolectricLooperWithSleep();
        CardBrowser cb = multimediaController.get();
        int pos = cb.getChangeDeckPositionFromId(currentDid);
        cb.selectDropDownItem(pos+1);    //Adjusting for All Decks option at position 0
        assertEquals(1L, cb.getCardCount());
    }
```
I don't understand the CardBrowser part, I just took it off of `CardBrowserTest`.

**Comment by mikehardy** [comment] 2020-10-16 14:29
🤔  the Robolectric thing should have been solved with this: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/test/resources/robolectric.properties / https://github.com/ankidroid/Anki-Android/commit/8748835f1ee5f606bb86a962e1fa477d38858a24 - strange that didn't work, perhaps there is a test execution mode we are missing? We should handle that though, the intention is that new contributors don't have to worry about unrelated things (that can be really frustrating to research + fix!) and can just focus on adding a test if that's the goal

**Comment by anadi198** [comment] 2020-10-16 15:41
> 🤔 the Robolectric thing should have been solved with this: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/test/resources/robolectric.properties / [8748835](https://github.com/ankidroid/Anki-Android/commit/8748835f1ee5f606bb86a962e1fa477d38858a24) - strange that didn't work, perhaps there is a test execution mode we are missing? We should handle that though, the intention is that new contributors don't have to worry about unrelated things (that can be really frustrating to research + fix!) and can just focus on adding a test if that's the goal

I was just clicking on the green play button next to the test method. For testing I added @Config but I'll remove that before a commit. I'm okay with using @Config if it's just my dev environment(macOS Catalina 10.15, have faced tonnes of macOS only issues before :D).

**Comment by mikehardy** [comment] 2020-10-16 16:01
I have two main dev rigs and one is macOS, I/we definitely intend to support it. Thanks for the use case for reproduction in the future, we should be able to fix that (although really, we need to move on to the next Java LTS versions anyway, that might be the real solution)

**Comment by anadi198** [comment] 2020-10-16 18:03
> ```
> long currentDid = addDeck("Basic::Test");
> getCol().getConf().put("curDeck", currentDid);
> Note n = super.addNoteUsingBasicModel("Test", "Note");
> n.model().put("did", currentDid);
> ```
> 
> The example you shared had everything except for adding a new deck and selecting it so I've looked for it and found this piece of code. Am I correct to assume that `getCol().getConf().put("curDeck", currentDid);` is the way to select a Deck?

I just realised you had provided an example to add a deck, so thank you! But I'm still wondering if I'm doing it right for the selection of the deck I just created.

**Comment by david-allison-1** [comment] 2020-10-16 18:10
> 
> > The example you shared had everything except for adding a new deck and selecting it so I've looked for it and found this piece of code. Am I correct to assume that `getCol().getConf().put("curDeck", currentDid);` is the way to select a Deck?
> 
> @david-allison-1 I just realised you had provided an example to add a deck, so thank you! But I'm still wondering if I'm doing it right for the selection of the deck I just created.

That looks good!

To confirm: You can add an assertion on the following:

`note.firstCard().getDid()` and ensure that the deck ID of the card is correct (not 1) before you continue to perform a search using the finder.

In the file that I linked, there should also be an example using the Finder to search.

**Comment by anadi198** [comment] 2020-10-16 19:05
> `note.firstCard().getDid()` and ensure that the deck ID of the card is correct (not 1) before you continue to perform a search using the finder.

```
        long did = note.firstCard().getDid();
        assertEquals(currentDid, did);
```
The `did` is indeed 1 and not equal to the deckID i was getting after creation at the start. I don't know why.

> In the file that I linked, there should also be an example using the Finder to search.

I tried to understand the flow of using deckID to searchCards() inside `CardBrowser.java` but it wasn't clear so I decided to just simulate going to the Card Browser and selecting my deck from the deckList hoping that the cards will be updated and then I'd check after that.

**Comment by anadi198** [comment] 2020-10-17 09:19
Okay I got it to work finally:
```
@Test
    public void test_findDeck() {
        String val = "*Yr1::Med2::CAS4::F4: Renal::BRS (zanki)::HY";
        Collection col = getCol();
        long currentDid = col.getDecks().id(val);
        col.getDecks().select(currentDid);
        Note note = col.newNote();
        note.setItem("Front", "foo");
        note.setItem("Back", "bar");
        note.model().put("did", currentDid);
        col.addNote(note);
        long did = note.firstCard().getDid();
        assertEquals(currentDid, did);
        ensureCollectionLoadIsSynchronous();
        ActivityController<CardBrowser> multimediaController = Robolectric.buildActivity(CardBrowser.class, new Intent())
                .create().start();
        multimediaController.resume().visible();
        saveControllerForCleanup(multimediaController);
        advanceRobolectricLooperWithSleep();
        CardBrowser cb = multimediaController.get();
        int pos = cb.getChangeDeckPositionFromId(currentDid);
        cb.selectDropDownItem(pos + 1);    //Adjusting for All Decks option at position 0
        advanceRobolectricLooperWithSleep();
        assertEquals(1L, cb.getCardCount());
    }
```

The second-last line was not there before(`advanceRoboelectricLooperWithSleep()`) and I decided to try it out.
As for the first assert statement failing, I did two things to fix it:
`col.getDecks().select(currentDid);` for selecting deck and
`note.model().put("did", currentDid);` must be **before** `col.addNote()`

I've tested both with and without my PR changes from before and it fails without the changes made with my PR. 

Now I think the master must have my PR from before merged before I open this PR(or the test will keep failing). 

@david-allison-1 Please tell me if the test I wrote is correct or needs changes, or let me know if I should open PR and you will give suggestions there.

**Comment by david-allison-1** [comment] 2020-10-17 12:47
That looks good!

You may be able to use `CardBrowser cb = RobolectricTest.startActivityNormallyOpenCollectionWithIntent(CardBrowser.class, new Intent())`

which should be able to reduce some of the code.

You'll want to name the test more clearly: `deckNameContainingWildcardCanBeSearched`

**Comment by anadi198** [comment] 2020-10-17 13:03
Thank you for the suggestions, it did reduce the code size so that's good! I'm waiting for my previous PR to be merged before I open a PR for this issue.

**Closed** 2020-10-23 18:26 UTC
