### ISSUE TITLE
Updating WebView on Lollipop breaks images in AnkiDroid

### ISSUE THREAD

**Issue by cameel** [ankidroid/Anki-Android#4297] opened 2016-05-23 17:51 UTC
###### Research

_Enter an [ x ] character to confirm the points below:_

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. Launch AnkiDroid and do some reviews. Cards with images are displayed correctly.
2. Close AnkiDroid
3. Update `Android system WebView` to the latest version (v4.3) from the Play Store. All other apps are already in the latest versions.
4. Launch AnkiDroid again and do some reviews. Images no longer show up.
###### Expected Result

I expect to see the images on cards that have them.
###### Actual Result

Every image that would normally show up on a card is  not displayed. A "broken image" icon is displayed instead.

The image files are still present and you can even view them with AnkiDroid using the Card Browser (by clicking the paperclip icon beside the field that contains the image).

The problem persists after device restart. Reinstalling AnkiDroid, clearing its cache and even removing application data and settings (via `Apps` in system settings) does not help. Removing the whole AnkiDroid directory (including the database and all media) and resyncing from scratch doesn't either. The collection itself does not change so it's clearly not an issue with settings or the data.

Only removing the WebView update fixes the problem.
###### Debug info

```
AnkiDroid Version = 2.5.4
Android Version = 5.1.1
ACRA UUID = 29be4aeb-644e-4b8a-9fd8-d2b2263f3c6a
```

**Comment by eginhard** [comment] 2016-05-23 23:18
Can you clarify the Android and WebView versions before and after the update? You first say Marshmallow, but then 5.1.1 (Lollipop) and 4.3 looks like the WebView app's rating, not its version number (the current stable version is 50.0.2661.86).

**Comment by cameel** [comment] 2016-05-24 12:10
> Marshmallow, but then 5.1.1 (Lollipop)

Sorry, for some reason I was convinced that Marshmallow was version 5. I should have just said version 5.1.1.

> 4.3 looks like the WebView app's rating

Oh, that explains a lot :-) I so rarely see ratings with decimal points that I naturally assumed that it must be the version number and it's not labeled in any way. I was only wondering why the release of all the Google stuff is not all coordinated so that it's at the same 4.x ;-)

Anyway, the new version is `50.0.2661.86`. When I uninstall the update it goes down to `39 (2237560- arm)`.

**Comment by mikehardy** [comment] 2018-06-11 14:44
With no offense intended to any of the discussion participants here @timrae I saw [the stale bot](https://github.com/probot/stale) in use in another project and issues like this make me think it would be a helpful thing here. Incidentally they also make the the Work in Progress bot (which you have mentioned), and No Response bot - the three of which might fit in here https://probot.github.io/apps/

**Comment by cameel** [comment] 2018-06-11 20:10
This issue is still relevant though. At least for me :) I hope it gets fixed eventually. But I guess it's pretty low priority since no other people are reporting this. Am I really the only one experiencing this?

I have to keep `WebView` at the factory version because with newer ones images are not displayed. I have encountered this issue also on my friend's nVidia Shield tablet when I recommended Anki to him so it's not just my Nexus.

**Comment by mikehardy** [comment] 2018-06-11 20:19
I do have a lollipop emulator laying around and I can see if I can reproduce it with that. I'm not sure if this is an option or not but at least higher Android API levels if you install Chrome you may select that as the webview implementation in the settings.

Either way I definitely understand it's relevant to you, but we haven't seen many reports of it no, and it's definitely working in the higher API levels. I like fixing everything but I'm not sure I can fix this...

**Comment by cameel** [comment] 2018-06-11 21:11
Well, if you feel it's going to be hard to fix then maybe it's indeed not worth the effort. I should update to Android 6 anyway. I would be okay with it being closed as `wontfix` if it's not worth fixing. I just did not get a real response either way until now and wanted to let you know that it still does happen so the issue is not really stale :)

Actually, the only thing holding me back with the upgrade is that I'm afraid of AnkiDroid being broken there too and not having an easy workaround like I have now. Seriously, Anki accounts for like 95% of my usage of the tablet so so far it made more sense for me to just downgrade WebView than risk losing a day of practice. Would be nice if you could look at it but if it's going to impact more important features or bugfixes then don't hesitate to close it. AnkiDroid is awesome anyway. Thanks for working on it :)

**Comment by mikehardy** [comment] 2018-06-11 21:23
I mostly work on it because I'm a heavy user as well :-), have you tried the Chrome idea, with Chrome replacing the builtin WebView? That really might be an option. As for Android 6, I'm not aware of any show-stopper type issues there but you can always search the issues list to see if you see something.

**Comment by cameel** [comment] 2018-06-11 21:56
I looked for it just now and I've found articles mentioning that there should be a switch available in developer options ([Google Chrome to Replace WebView in Android 7.0 Nougat](https://gadgets.ndtv.com/apps/news/google-chrome-to-replace-webview-in-android-70-nougat-863667)) but I can't see it on my tablet so I think it must have been introduced later.

I'll update to Android 6 eventually. Even if there are showstopper bugs, I know I can downgrade. It's just that the upgrade is just a few clicks to accept the OTA update and it'll probably even keep my apps and settings. But a downgrade will involve flashing the older version and a device reset so I just have to set aside some time to be able to get the tablet to a usable state if it turns out there are problems.

But anyway, thanks for suggestions. I think I can live with older WebView for a while more and wait for a moment when I can spare some time to tinker with the tablet. There are some other things I've been meaning to try doing with the device so that'll be a good opportunity to get down to it.

**Comment by mikehardy** [comment] 2018-06-11 22:40
I'll still see what I can see on lollipop just to see if it is a general problem or a trivial fix, but after looking into webview switching on lollipop it doesn't look promising. There's an opportunity to become a webview beta tester and maybe that would get you a release that worked but I imagine they've stopped making new releases that far back too. Upgrading Android is the likely successful solution. Good luck with the upgrade if you do it

**Comment by mikehardy** [comment] 2018-09-14 03:45
I will sadly resolve this as a won't fix - I can't reproduce it on any of my emulators going all the way back to API15 (Ice Cream Sandwich) so I'm not sure what's happening. Hopefully you can get a configuration going that works for you

**Closed by mikehardy** 2018-09-14 03:45 UTC

**Comment by cameel** [comment] 2018-09-17 20:05
Well, that's strange. Big thanks for looking into it anyway. I don't mind if closing it means that you can focus on making other parts of the app better for everyone :)
