### ISSUE TITLE
edit a image, tag list

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3323] opened 2015-07-28 10:51 UTC
Originally reported on Google Code with ID 2427
```
Please explain your idea here.

1. Please add the function that i can cut or edit image by in this app.
If I have a whole page image and I want put only a part of the page on a card, I have
to go out Ankid, cut it in the Phone gallary app, come in Ankid again. It's so cumbersome.

2. Please add some basic tag list. For example, font color, size, bold, underline...
etc. 


I am a Korean user. I am making the best use of this app and always thank. Have a good
day!

```

Reported by `cek8988@naver.com` on 2014-12-02 00:36:07

**Comment by eginhard** [comment] 2015-10-29 09:36
Duplicate of #2554 and #1377

**Closed by eginhard** 2015-10-29 09:36 UTC
Labels: enhancement
