### ISSUE TITLE
[Bug] Clicking outside of sync window cancels sync without cleanly disconnecting from sync service

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#12613] opened 2022-10-09 20:00 UTC
###### Reproduction Steps

1. Using beta86, review some cards and then click the sync button 
2. Wait for syncing dialog to appear
3. Click anywhere outside of syncing progress window

###### Expected Result

I wouldn't expect clicking on the screen to have any immediate action on the syncing. Maybe it could ask me if I wanted to cancel syncing, or instead of showing the detailed syncing progress by default it could animate the sync icon and create a notification instead of a window and I could interact with the notification to review/cancel progress of the sync.

Also, when double checking this before submitting the bug report, I got a crash after doing the above steps (not reproducible)

###### Actual Result

A snackbar immediately pops up saying "Interrupted" and further attempts to sync give an error saying "only one copy of anki can sync at a time, try again later"

###### Debug info

```
AnkiDroid Version = 2.16alpha86

Android Version = 12

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = f9d003f3-ae34-4529-8cd5-ed8aff42fa30

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2022-10-09 20:23
This is indeed a poor user interface at the moment - I believe the future state is to have the collection sync (which is by definition blocking) be non-cancelable except via explicit action (it may already be?) but once that phase is over and it's in media sync, it should be a sticky progress notification and unblock the UI

The fact it is even a dialog, much less one with poor UX is all a problem in my opinion.

We've got a progress notification coming up shortly as part of highest-priority scoped storage work, I'll leave this open and we can hook into that with media sync once it exists

**Comment by user1823** [comment] 2022-12-13 13:36
Still searching for solutions...

**Comment by david-allison** [comment] 2023-02-14 00:04
Was this regression introduced when the MaterialDialogs were modified, or is it present in 2.15?

**Comment by doozan** [comment] 2023-02-14 01:16
This is a change with the alphas. With 2.15, nothing happens if you accidentally touch outside of the sync window and pressing back brings up a dialog asking if you want to cancel or continue syncing.

**Comment by user1823** [comment] 2023-05-15 11:08
Still searching for solutions...

**Comment by user1823** [comment] 2023-08-13 16:27
Still searching for solutions...

**Comment by dae** [comment] 2023-09-01 06:22
The original report talks about not cleanly disconnecting. Are you getting an error when you attempt to sync immediately after cancelling?

**Comment by user1823** [comment] 2023-09-01 13:22
> Are you getting an error when you attempt to sync immediately after cancelling?

No. But, I am annoyed by the fact that accidental clicks outside the sync window interrupt the sync.

In my opinion, the best solution would be to replicate the behaviour of v2.15.

> With 2.15, nothing happens if you accidentally touch outside of the sync window and pressing back brings up a dialog asking if you want to cancel or continue syncing.

**Comment by user1823** [comment] 2023-12-11 15:17
Since no one else has reported about getting an error on attempting to sync immediately after cancelling, I think that the "unclean disconnection" part might be a one-time event or fixed in subsequent releases.

But, the cancellation of sync on accidental clicks is still an issue and I am quite annoyed by it. Probably, it would be better to address this part first (and I don't think that it would be too difficult to do this).

**Comment by david-allison** [comment] 2023-12-11 15:36
Agreed, I'd like this done before a 2.17 release

**Comment by david-allison** [comment] 2024-01-21 01:17
Removed in:

* https://github.com/ankidroid/Anki-Android/pull/14171/commits/e7f1807896783f1f585d9c7370bb89112e74f915
* https://github.com/ankidroid/Anki-Android/pull/14171/commits/712c11963b8bfe9935dce048184c220f3ea69e36

Specifically, I'll revive 

```xml
<string name="cancel_sync_confirm">Do you want to cancel the sync?</string>
```

**Comment by david-allison** [comment] 2024-01-21 01:38
This is more complicated than it appears.

Legacy code:

https://github.com/ankidroid/Anki-Android/blob/766a002e86801797a29aa946fa83a2f64526a8d0/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L1775-L1806

It explicitly overrides the back button so we can show the dialog.

In our newer code, if `onCancel` is called, the dialog has already been dismissed, so 'continue' would not restore the Progress Dialog

https://github.com/ankidroid/Anki-Android/blob/5f2cc77db6ab1f08a9e642b8f9846d792d475ced/AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt#L203-L213

**Closed** 2024-01-24 15:14 UTC
Labels: Sync, 2.16
