### ISSUE TITLE
Tapping the notification takes you to the deck list instead of to your open deck

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3593] opened 2015-08-03 14:59 UTC
*Steps to reproduce:
1. Turn on Anki notifications
2. Open a deck and start reviewing
3. Lock the device or navigate to home screen or another app
4. Tap the "Cards due" notification
5. Ankidroid opens and displays the deck list, kicking you out of whatever deck you were previously studying. This would also kick you out of any note you were editing, losing your changes in the process. 

Can it be changed so that tapping the notification brings you back to the current Anki session, rather than relaunching from the deck list?

**Comment by tobrie** [comment] 2020-06-25 18:50
I've wondered, when I've used it the first time, why the notification doesn't take me to the deck that it notifies me about. I'll make a PR if you agree that that's how it should work.

**Comment by mikehardy** [comment] 2020-06-25 20:47
There are two types of notifications generated - one that is for general work and one is per deck if I recall correctly
For the per deck one, sure it would be more useful to go right to the deck

**Comment by Ekagra** [comment] 2021-03-12 07:14
I am working on it

**Comment by IAmJaishree** [comment] 2021-03-14 12:30
Hi @mikehardy, can I work on this one? :)

**Comment by david-allison-1** [comment] 2021-03-14 17:49
> Hi @mikehardy, can I work on this one? :)

Thanks!! Lots of really useful (and not too difficult) work can be done with the notifications. We get a fair amount of feedback and it needs some care, but nobody's had the time to get around to it

**Comment by mikehardy** [comment] 2021-03-14 20:35
Indeed, would be great to see notifications improved a lot. In general google summer of code has not started in case that is a concern for you, but otherwise any issue is open game and no need to ask really - just post a PR, although it is a good practice to say "I am looking into this now" so people see that there is activity and we don't have multiple people working on the same thing without knowing it. Then in PRs make sure you put `Fixes #issuenumber` in there so github cross-links the PR and the issue for reference

**Comment by IAmJaishree** [comment] 2021-03-15 08:12
Hi @mikehardy, thanks for the info will keep this in mind now, I am very new to open source and still exploring the decorum of it :)

**Comment by IAmJaishree** [comment] 2021-03-15 12:30
@david-allison-1 @mikehardy I am able to see in many places we are using hard coded values for invoking sharedPreference code.

**I would like to create a SessionManager class which will internally use SharedPreference and will expose functions to store different kind of key values.**

For example 

instead of calling:
`preferences.getBoolean("widgetVibrate");`
we can call:
`sessionManager.getWidgetVibrate()`

I would like to refactor the code base and make such changes in places where SharedPreference is getting called directly from the business logic.

I think this will makes code more reader friendly and also less prone to errors.

Would like to hear your thoughts on it. :)

**Comment by mikehardy** [comment] 2021-03-15 12:32
I don't think that really has value here, for this issue. Solve things with focused solutions I think

**Comment by IAmJaishree** [comment] 2021-03-15 12:39
I do agree it is not related to this issue, but I still feel we should add this later(if not now).

**Comment by david-allison-1** [comment] 2021-03-16 02:33
> I don't think that really has value here, for this issue. Solve things with focused solutions I think

It's already been completed: https://github.com/ankidroid/Anki-Android/pull/8066 and is waiting for review, no need to duplicate the effort.

----

Agreed, focus on one issue at the time - for the most part bug fixes + automated tests will take priority over large scale refactorings because they're easier to complete, provide much more value to our millions of users, rather than a few developers, and are much less likely to lead to lava layers (layers of partially completed refactorings which reduce code consistency).

It's a balancing act - we need to keep code quality to an acceptable level to ensure that we can consistently move the project forward, but we shouldn't do that at the expense of shipping enhancements and bugfixes to our users. 

Small, localised refactors with fixes are good (especially if they add tests). Larger ones which affect the codebase should be discussed to ensure they're the best means of fixing an issue, rather than using the bug as a rider to bring along a partial refactoring.

**Comment by david-allison** [comment] 2022-10-22 17:05
The PR had feedback, and the feedback wasn't addressed for over 2 months, so the PR was automatically closed.

The issue is still open, and either the above PR can be used as a base (with some rebasing to fix conflicts), or the issue can be resolved working from first principles

**Comment by BrayanDSO** [comment] 2024-05-10 20:58
Closing this in favor of #1377

**Closed by BrayanDSO** 2024-05-10 20:58 UTC
Labels: Bug, Priority-Medium, Help Wanted, Good First Issue!, Reproduced, Keep Open
