### ISSUE TITLE
After adding a new card, Swipe Refresh synchronization do not remove badge from Sync Button.

### ISSUE THREAD

**Issue by Subhadiptech** [ankidroid/Anki-Android#12923] opened 2022-12-03 19:45 UTC
###### Expected Result
The badge should get removed on synchronising through refresh swipe as happens with Sync button.

###### Actual Result
The badge doesn't get removed on synchronising through refresh swipe as happens with Sync button.

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by criticalAY** [comment] 2022-12-04 05:54
It's a duplicate of #12873 please close this

**Comment by pratyaksh1610** [comment] 2022-12-04 09:21
@Subhadiptech Thankyou for filing an issue, but it seems to be in queue already.

**Closed** 2022-12-04 09:46 UTC
