### ISSUE TITLE
Screen flickers/refreshes when a card changes

### ISSUE THREAD

**Issue by mjuzikfrik** [ankidroid/Anki-Android#5384] opened 2019-07-17 12:29 UTC
Hello,

I have a problem with flickering/refreshing every time new card shows. It doesn't happen on the desktop version of Anki. I don't know really why. Could it be due to the card template? I'm attaching gifs to show what I'm talking about.
Ankidroid 2.9.80a

edit. Stable version 2.8.4 has no such problem.
![1](https://user-images.githubusercontent.com/16630872/61375459-40169900-a89f-11e9-8608-6e0ad0e4ffd5.gif)
![2](https://user-images.githubusercontent.com/16630872/61375460-40169900-a89f-11e9-9f01-890339fe2d47.gif)

**Comment by Anthropos888** [comment] 2019-07-20 09:09
Same here. It happend after the update to 2.9beta2. 
Beta1 didn't have that problem. 
Beta3 still has it.

Related question: if I want to downgrade to a previous version, do I need to uninstall AnkiDroid first? Will I lose all app settings like gestures and so on?

**Comment by timrae** [comment] 2019-07-20 09:16
@adamwolf 
Could this be caused by #5382?

**Comment by adamwolf** [comment] 2019-07-20 21:53
Maybe!  I don't think that change was in beta2 though!  Can we check?  I do
suspect it is related to MathJax in general, if not that particular change.

Does it do this on Anki Desktop?

Fixing this so that it doesn't blip and doesn't visually rerender MathJax
may be a chunk of work.

I wonder if we could detect MathJax cards and only load the MathJax
renderer for those cards... It would be different than what Anki Desktop
does, but it might be a quicker intermediate fix for most cards.

Do we currently show the whole card with a hidden answer and then reveal
the answer, or do we reload the webview for the answer?

**Comment by timrae** [comment] 2019-07-20 22:46
Yes, you can check the log here:
https://github.com/ankidroid/Anki-Android/commits/release-2.9

The latest mathjax patch was indeed introduced in beta2, and I can also reproduce the issue, so I will revert that for now. I don't notice any flicker in beta1, though the very first card does take much longer to load.

@mjuzikfrik Does it happen for you on simpler cards as well? If not, can you please attach a sample deck that reproduces the issue?

**Comment by mikehardy** [comment] 2019-07-20 22:48
That change was beta2 - https://github.com/ankidroid/Anki-Android/commits/release-2.9

Well, my prediction of flicker-sensitive users was accurate at least, but it's not a celebration ;-)

We currently go back to Java on card interaction and for answers we then fetch the answer, generate new HTML and push that back into the existing WebView (whole page load, but re-used WebView) based on my last investigation

It does seem like a viable deviation from Desktop to check for MathJax on a card (should be easy? famous last words) and only pull in all that machinery if needed.

**Comment by adamwolf** [comment] 2019-07-20 23:36
I can take a look at this this week. It may be good to see how Anki Desktop
does it.   I think they get away with all of this by having a 200 ms fade,
but I am not 100% sure.

Would we want to do that?

I think detecting MathJax and only waiting for MathJax to render will be
less work than the initial MathJax work and is something I can likely
tackle by the end of this week.

The fade would be pretty easy too.  I'm not sure I'm in love with either
one of these options, but I don't hate them either.

**Comment by timrae** [comment] 2019-07-21 00:14
@dae

Did you do anything particular on Anki mobile to prevent mathjax slowing down rendering?

**Comment by dae** [comment] 2019-07-21 00:38
I suspect the issues lie in the fact that AnkiDroid loads a new webpage on each card transition, instead of just dynamically updating part of it, so external fonts and Javascript have to be loaded each time.

**Comment by timrae** [comment] 2019-07-21 00:48
Fonts and js should be cached by most webviews after the first card is loaded on most webviews. Changing the way we populate the html would be too big of a change for 2.9, but I agree in the long term that would be a better solution.

**Comment by mjuzikfrik** [comment] 2019-07-21 05:53
I doesn't seem to happen to basic template. Maybe it's due to animations I have in my cards. I think that I had the problem in all betas. I can check it. Here's the deck.

https://drive.google.com/file/d/1v5vQC8QP7BbAGJyzvK25fz4HttNhuv8W/view?usp=sharing

**Comment by timrae** [comment] 2019-07-21 06:48
If you can tell us the exact version where the problem was introduced, we can see what would be involved to fix it. For example if it's caused by loading the Mathjax library then most likely the problem will not exist in 2.9alpha69, but it will exist in 2.9alpha 70. Can you please test it and let us know exactly which version the problem was introduced?

**Comment by Anthropos888** [comment] 2019-07-21 08:17
The flickering affects all of my decks and was introduced with Beta2. Depending on the template, this can be a very annoying bug and it reminds me of the credits in Python's Knights of the round table: https://youtu.be/SII-jhEd-a0 (3:10)

Anyway, it's fixed now with beta4, thank you!

I can install all the previous betas to check exactly which one introduced the flickering. But again: do I need to uninstall the current version first and will I lose the app settings?

**Comment by mjuzikfrik** [comment] 2019-07-21 09:54
@timrae 
It's exactly as you said. 2.9 alpha 69 is free of that flicker and it's introduced with alpha 70.

**Comment by timrae** [comment] 2019-07-21 09:59
Thank you for confirming that. 

@adamwolf
If we were to only include the mathjax CSS when mathjax is detected on a card, how would we detect the presence or absence of mathjax?

**Comment by mikehardy** [comment] 2019-07-21 11:55
I think a dynamic load would be a javascript thing, so perhaps in AbstractFlashcardViewer.java - where we have knowledge of card contents via inspection if we want - we could emit some javascript variable that indicates presence of mathjax in the card question or answer, then in the card html the mathjax load could be keyed on that?

**Comment by timrae** [comment] 2019-07-21 11:59
I don't think it would necessarily have to be a js thing, we could probably handle it in a similar way to night mode if that were advantageous for some reason (like simplicity). The question is how do we detect mathjax

**Comment by mikehardy** [comment] 2019-07-21 12:03
it's a regex - and I think @adamwolf already has that part nailed with unit testing https://apps.ankiweb.net/docs/manual.html#mathjax-support - should be (famous last words, as ever) easy to apply in java and then emit whatever (CSS or javascript variable or ? )

**Comment by timrae** [comment] 2019-07-21 12:13
Ok, yeah there are probably several different ways to do implement it, most likely one or more winners will emerge during testing ;)

**Comment by adamwolf** [comment] 2019-07-21 16:20
I think the blink is happening in card.js, where we're render MathJax in
onload.

Let's add a class to the card in AbstractFlashcardViewer, and only render
in card.js if that class is detected.  We can also be smart about adding
the mathjax-hasnt-rendeted-yet only to cards with MathJax, to prevent that
other blink on non MathJax cards.

I think it makes sense to revisit how the card/answers are loaded after 2.9
to fix this in a deeper way.

I apologize if some of my references are incorrect, I am writing this from
a mobile device.

**Comment by adamwolf** [comment] 2019-07-25 14:07
I have made progress on this.  It looks pretty good but I need to test it more.

**Closed** 2019-07-27 13:16 UTC

**Comment by timrae** [comment] 2019-07-27 18:37
@mjuzikfrik 

How is it in the latest beta?

**Comment by mjuzikfrik** [comment] 2019-07-27 20:42
Working fine! :) Thank you.

**Comment by adamwolf** [comment] 2019-07-27 21:26
Great!
