### ISSUE TITLE
Hide the top bar in the reviewer when "Show remaining" is turned off

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#13919] opened 2023-05-27 10:49 UTC
###### Reproduction Steps

1. Set the app theme to any one except the Black theme (the issue is there too, but it is not easily visible)
2. In the Reviewer section of the Appearance page in Settings, enable "Show top bar" and disable "Show remaining".
3. Go to the reviewer and see the issue.

Screenshot of the settings:
![Screenshot_20230527-160128~2](https://github.com/ankidroid/Anki-Android/assets/92206575/4c6bf977-7b99-4d94-9bf6-d54c824efc12)

###### Expected Result
The top bar should not be shown because it doesn't contain any information. It should look like the following:
![Screenshot_20230527-161044~2](https://github.com/ankidroid/Anki-Android/assets/92206575/85b522d4-7b8c-49bf-a514-e758fbd19736)

###### Actual Result
The top bar is shown unnecessarily.
![Screenshot_20230527-155555~2](https://github.com/ankidroid/Anki-Android/assets/92206575/68ac385b-c81b-4459-825e-1859d90bbb90)

I don't know why these are two separate settings. I think that they should be merged into one setting.

Another issue that the current implementation leads to is that when "Show top bar" is disabled and "Show remaining" is enabled, the remaining count is not shown because the top bar is not shown.

###### Debug info
AnkiDroid Version = 2.16.0beta2

Android Version = 12

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; moto g62 5G Build/S2SSIS32.18-12-4-8; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.163 Mobile Safari/537.36

ACRA UUID = d808c2e4-92ce-40db-9491-1fdcb75b1f50

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by snowtimeglass** [comment] 2023-05-27 12:28
>The top bar should not be shown because it doesn't contain any information. 

The top bar may contain other information depending on the setting of "App bar buttons"

![image](https://github.com/ankidroid/Anki-Android/assets/10436072/e4ded85f-2a3f-4e7e-b504-657f5bda0034)

![image](https://github.com/ankidroid/Anki-Android/assets/10436072/f172d0f3-203a-4723-a781-047875d48d0a)

>Another issue that the current implementation leads to is that when "Show top bar" is disabled and "Show remaining" is enabled, the remaining count is not shown because the top bar is not shown.

 I agree. It seems to be desirable to gray out it.

**Comment by user1823** [comment] 2023-05-27 12:46
> The top bar may contain other information depending on the setting of "App bar buttons"
> 
> ![image](https://user-images.githubusercontent.com/10436072/241389545-e4ded85f-2a3f-4e7e-b504-657f5bda0034.png)

In my app, the flag is shown just adjacent to the menu and not in the top bar. Probably, it has something to do with the other settings.

![Screenshot_20230527-181351~3](https://github.com/ankidroid/Anki-Android/assets/92206575/4cbd9f09-67ac-441b-bf44-1f36b62e6088)

So, if the card counts option is disabled, the only purpose of the top bar is to show the mark. I don't think that it is worth showing the top bar just to display the mark. Should we also shift the mark adjacent to the flag?

By the way, in https://github.com/ankidroid/Anki-Android/issues/12385, the current consensus is to remove the deck name from the reviewer (or atleast provide an option to hide it). So, we would have much room to add items there.

**Comment by david-allison** [comment] 2024-02-16 03:25
Closing as duplicate of #14374

**Closed by david-allison** 2024-02-16 03:25 UTC
