### ISSUE TITLE
[BUG]: Some titles and labels are in the System Language after language change in settings

### ISSUE THREAD

**Issue by valeriad0l** [ankidroid/Anki-Android#16186] opened 2024-04-15 23:07 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Open AnkiDroid
2. Go to Settings
3. Go to General
4. Select a different language other than System Language 

### Expected behaviour

All labels, titles and text should be in the newly selected language.

### Actual behaviour

![Screenshot_20240415-185549_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/91857937/0fad3ec3-e7b3-46fa-8ee2-4910f66c8958)
![Screenshot_20240415-185719_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/91857937/fb1d9b67-e53a-466b-884c-b3da2a0b3c51)
![Screenshot_20240415-185737_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/91857937/6fb81ea4-9ce1-4456-a40c-0aea7b4103b3)

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A205W

Hardware = exynos7884B

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-A205W Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = b2f555fc-671c-4986-83aa-7295f04a0e6c

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-04-15 23:43
Thanks for the report!

Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/12448

* https://github.com/ankidroid/Anki-Android/issues/12448

**Closed by david-allison** 2024-04-15 23:43 UTC
Labels: Bug, Needs Triage
