### ISSUE TITLE
tapping on an deck done for the day, ankidroid should offer options 

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#15172] opened 2024-01-07 18:58 UTC
When one taps on a deck that is done, that has no new card for today, the behavior should be more similar to anki, and offer options to do custom study, unbury, open the options and see the deck descriptions (I admit I don't see the point of the last one, but no reason to be different either)

Indeed, it's slightly frustrating to have to go on the previous screen to be able to add one extra card for the day

**Comment by BrayanDSO** [comment] 2024-01-07 19:11
Duplicate of #14955

**Closed by BrayanDSO** 2024-01-07 19:11 UTC
