### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Kayminet** [ankidroid/Anki-Android#8120] opened 2021-02-20 11:41 UTC
###### Reproduction Steps

1. Click on the "paquets" (french version)
2. 
3. 

###### Expected Result
Everything is working like usual

###### Actual Result
Everything is disapearing on the screen and I can'r write

###### Debug info
AnkiDroid Version = 2.14.3

Android Version = 8.0.0

ACRA UUID = 9690f7f0-abde-4de9-8b24-6e1957131ce8

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment] 2021-02-23 12:29
thanks for the bug report.

Can you take a screenshot of the "disappearing" screen, so that I see what actually is shown. I don't know why you'd expect to write in a deck (la traduction de paquet en VO)
Did you try to close it and open it again ? Does the bug stay here ? Can you reproduce each time ? With each decks ?

**Comment by Kayminet** [comment] 2021-02-23 14:35
Yes, I tried everything. I even checked all the "affichage" options

Le mar. 23 févr. 2021 à 13:30, Arthur Milchior <notifications@github.com> a
écrit :

**Comment by Kayminet** [comment] 2021-02-23 14:36
Sometimes its like this. I can write with my screen phone usualy

Le mar. 23 févr. 2021 à 13:30, Arthur Milchior <notifications@github.com> a
écrit :

**Comment by Ekagra** [comment] 2021-03-11 12:08
I'm unable to reproduce this error

**Comment by mikehardy** [comment] 2021-03-11 16:00
This was a bug in Android 8 hardware render that we finally fixed #8154 in 2.14.6

**Closed by mikehardy** 2021-03-11 16:00 UTC
