### ISSUE TITLE
Subdecks review not possible with new scheduler.

### ISSUE THREAD

**Issue by jaworekmichal** [ankidroid/Anki-Android#5640] opened 2019-11-26 21:06 UTC
I have a problem working with new scheduler and decks/subdecks hierarchy. AnkiDroid enables me to start review session only if I click top level deck (not subdeck).
If I click one of subdeck I'm informed that there is nothing to be reviewed today (even if numbers next to subdeck name clearly says that there are "due" cards)

Problem occurs only when new scheduler is enabled.

Behavior of Anki Desktop 2.1 with new scheduler is correct, so I conclude there nothing wrong with my decks settings. 

Real example screenshot: https://imgur.com/a/lRa5eCi
![Screenshot_20191126-153600_AnkiDroid](https://user-images.githubusercontent.com/2247048/69672537-9c34c980-1098-11ea-936c-fce42955a3a8.jpg)

###### Reproduction Steps

1. Enable new scheduler. 
2. Create deck and subdecks. "Root", "Root::Subdeck", "Root::Subdeck::DeeperSubdeck"
3. Add cards to all three decks, and make sure cards are ready to review (not "new", not "learning", due).  
4. In main view click subdeck "Root::Subdeck" to start review session.

###### Expected Result
- Review session should start
- Review session should contain cards from both "Root::Subdeck" and "Root::Subdeck::DeeperSubdeck" decks.
- Review session should NOT contain cards from "Root" deck

(This is how Desktop Anki 2.1 with new scheduler behaves)

###### Actual Result
Review session does not start. Message is displayed with information that there is not cards to be reviewed. ("Congratulations....")
(The same message is displayed when  "Root::Subdeck::DeeperSubdeck" is clicked)
(Review session starts only if "Root" deck is clicked.)

###### Debug info
AnkiDroid Version = 2.9.1

Android Version = 8.0.0

ACRA UUID = a61020a3-a597-42ee-9eca-fb1d2ebcf0dd

###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2019-11-26 21:19
Hi @jaworekmichal :wave: - can I ask you to update to the latest alpha? There has been a *lot* of anki -> ankidroid porting work happening and it may have already fixed your issue, or it will confirm there is still something going on. Either way we will only know for sure if you are running the latest alpha: https://docs.ankidroid.org/manual.html#betaTesting - note that there is nothing wrong with installing the alpha via those instructions, then leaving the alpha (and even beta, if you like) programs doing an uninstall/reinstall to get 2.9.1 stable again. It will all be compatible.

**Comment by jaworekmichal** [comment] 2019-11-27 12:16
Hi @mikehardy,

thanks for quick response.

I've tried both:
- 2.9.2beta4
- 2.10alpha17

Unfortunately on both version I can see the same problem. 

Let me know if there is any additional information which I can provide.

**Comment by mikehardy** [comment] 2019-11-27 13:28
@jaworekmichal thank you very much for trying the lastest alpha - any fixes we may land for this will of course be on our most current release so unless the alpha has problems for you (it might, you never know) I'd stay on it if possible and as you see updates come in you can retry your scenario to see if it was fixed and report here (plus updates will come through this issue on status as we investigate and work on it in time available)

Hey @hssm and @Arthur-Milchior - you two have done basically all the v2 scheduler / libanki work recently so the relevant code might be top of mind for you - can you think of why subdeck reviews wouldn't be possible in v2 scheduler?

**Comment by hssm** [comment] 2019-11-27 13:52
Looks like a bug.

I've not had any issues with subdecks myself, and I couldn't reproduce it using your example on my own collection (not a fresh one). It's possible that the option groups of the decks in the tree are involved.

Would you be able to export that deck (with scheduling enabled) or your collection and attach it here? Is the issue always present or does it need to enter a certain state to activate it? (E.g., do you need to review a certain amount from parent or sub deck to trigger limits?).

**Comment by jaworekmichal** [comment] 2019-11-30 21:23
Hi @hssm,

sorry for delay, I needed some time to investigate issue deeper.  

You are right, my first reproduction steps were not complete. I didn't realize that issue is cause by interaction of different decks/option groups. 

I'm attaching example collection. With it, reproduction should be easy.

**Collection description:**

There are three deck with option group "default" (keep in mind that this is not out-of-the-box default settings)
- Root
- Root::Subdeck
- Root::Subdeck::Deeper

Additionally there are 4 decks with option group "suspended" (limit 0 for all reviews). 
- Suspended
- Suspended::Old
- Suspended::Old::ENG
- Suspended::Old::Python

**Issue description**

I cannot start review of

- Root::Subdeck 
- Root::Subdeck::Deeper

when any of decks 

- Suspended
- Suspended::Old

is assigned to option group "suspended". 

If I assign both deck `Suspended` AND `Suspended::Old` to "default" option group --> I can start review of `Root::Subdeck` and `Root::Subdeck::Deeper`

Additionally, If I modify property "Maximum reviews/day" for option group "suspended" --> I can start review of `Root::Subdeck` and` Root::Subdeck::Deeper` and the limit from "suspended" option group is applied (even though  decks `Root::Subdeck` and `Root::Subdeck::Deeper` are assigned to "default" option group)

Let me know if I should clarify something. 




[5640_to_share_no_media.zip](https://github.com/ankidroid/Anki-Android/files/3907563/5640_to_share_no_media.zip)

**Comment by hssm** [comment] 2019-12-01 07:09
Thanks for the reproducible test case. I've put in a fix for this issue.

**Comment by mikehardy** [comment] 2019-12-02 13:26
@jaworekmichal this will be visible on the alpha track for verification of fix when #5645 is merged and @timrae releases the next alpha after that merge

**Comment by jaworekmichal** [comment] 2019-12-02 13:34
Thanks @mikehardy  and @hssm. I'm astonished how quickly it was solved. 👏

**Closed** 2019-12-27 00:50 UTC
Labels: 2.9.x, Priority-Medium, accepted, needs-triage

**Comment by thiswillbeyourgithub** [comment] 2020-05-11 08:32
Hi, I am having this problem in ankidroid 2.9.7. Isn't it supposed to be fixed?

**Comment by mikehardy** [comment] 2020-05-11 12:51
Yes it is supposed to be fixed, if you can reproduce something can you please open a new ticket with as much info and clear reproduction steps as possible (either starting from scratch or with a sample collection we can download). You should definitely try reproduction on the 2.10betas or 2.11alphas (which are largely the same at the moment, but well past the 2.9.x release tree at this point to make sure we're not chasing closed issue phantoms on old code https://docs.ankidroid.org/#betaTesting

**Comment by thiswillbeyourgithub** [comment] 2020-05-11 13:15
I am short on time and a quick test showed a was not able to reproduce with a fresh deck.

So I won't be bringing any more information but am reporting the following :

I have several decks and subdecks. I can't access any of the subdecks containing reviews (no new cards) but can access the ones containing only news as well as filtered decks that are insided (so they are subdecks too). Those filtered decks contain the "review" of the "new only" decks but not from the ones containing only reviews.

I can indeed review cards if I rename the subdeck to an upper level deck.

I can access the reviews no problem on the linux app, even with no addons.

I double checked every settings and nothing seems to explain this. All my subdecks are in a single deck with permissive settings (9k news and 9k review per day) to avoid sub limitations.

I am indeed using the V2 scheduler.

I am getting the message "Congratulations! You have finished for now" and not daily study limit reached.

If I find any more info I'll be sure to tell you, in the mean time probably won't investigate further for the time being.

Thanks a lot for giving YOUR time for ankidroid though, it is much apperciated :)

**Comment by thiswillbeyourgithub** [comment] 2020-05-11 13:21
Sorry for the second message : the issue is indeed fixed in ankidroid2.10-b4. I will be staying on this one for a bit until the next stable release. Thanks a lot!

**Comment by mikehardy** [comment] 2020-05-11 14:24
Fantastic! I *think* 2.10beta5 (which is a tiny bugfix I just issued vs beta4 in template processing) will be the 2.10 official release, so you should be rock stable here. Thanks for reporting back
