### ISSUE TITLE
Support adding multiple audio files to a single field

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3537] opened 2015-07-28 11:06 UTC
Originally reported on Google Code with ID 2665
```
What steps will reproduce the problem?
1. open a deck
2. add a note. 
3. write something on the front page
4. add an audio: record it speaking something into the mobile phone
5. tick OK


What is the expected output? What do you see instead?
I want to have the spoken word recorded _and_ the previously written word.
 but after recording the word, the wriiten entry is gone/deleted.

Does it happen again every time you repeat the steps above? Or did it
happen only one time? Every time


Paste the "debug info" from the AnkiDroid "About" dialog below (see the
above help webpage for detailed instructions).

AnkiDroid Version = 2.4.3

Android Version = 4.3

ACRA UUID = d4aa20fc-010f-432e-a43d-6f490778581b

Please provide any additional information below.

```

Reported by `luebbers231` on 2015-06-28 21:24:46

**Comment by eginhard** [comment] 2015-12-05 17:28
Basically a duplicate of #3669

**Closed by eginhard** 2015-12-05 17:28 UTC
Labels: accepted, enhancement, Priority-Low
