### ISSUE TITLE
No longer support {{=<% %>=}} in 2.10beta1

### ISSUE THREAD

**Issue by C-Y-Liu** [ankidroid/Anki-Android#6103] opened 2020-05-04 14:05 UTC
I have been using `{{=<% %>=}}` in my template, but the new version doesn't support this method even if I put it at the beginning of the template according to Anki Manual, I wonder this is a bug or this feature is completely removed.
![Screenshot_2020-05-04-21-56-02-458_com.ichi2.anki.jpg](https://i.loli.net/2020/05/04/g8FmBVYZA7IXysC.jpg)
 ![IMG_20200504_220220.jpg](https://i.loli.net/2020/05/04/Eqgy49VRDOLvHxs.jpg)

**Comment by mikehardy** [comment] 2020-05-04 14:11
@C-Y-Liu thank you so much for reporting this! I'm sorry there's a change from 2.9 to 2.10 that's affecting you, but getting a report of some incompatibility within a day of releasing the first 2.10 beta is really valuable to us, thanks.

@david-allison-1 do you have any time to look at this 🙏  I can't imagine what changed there?

**Comment by david-allison-1** [comment] 2020-05-04 14:34
> @C-Y-Liu thank you so much for reporting this! I'm sorry there's a change from 2.9 to 2.10 that's affecting you, but getting a report of some incompatibility within a day of releasing the first 2.10 beta is really valuable to us, thanks.
> 
> @david-allison-1 do you have any time to look at this 🙏 I can't imagine what changed there?

Did we ever support this? What does the syntax mean? I recall #5865, but I didn't look into it too much.

 Feel free to assign it to me and I'll get to it in a day or two. But, I don't think it's a regression.

**Comment by mikehardy** [comment] 2020-05-04 14:40
No pressure on time - @C-Y-Liu you can opt out of the beta program and revert to 2.9.7 to restore functionality. @david-allison-1 I'm inclined to say it must be a regression based on user report and knowledge that this is the first time anything directly from master made it to the beta channel since October as I just branched release-2.10 and shipped it - I don't believe in coincidence like that

**Comment by david-allison-1** [comment] 2020-05-04 14:47
Touché, I'm on it.

**Comment by dae** [comment] 2020-05-04 22:01
@Arthur-Milchior does #6073 prevent the rendering of {{Field}} inside note fields?

If so, the render_delimeter() functionality could be removed, and the code could just rewrite the alternate syntax to the standard one:

https://github.com/ankitects/anki/blob/master/rslib/src/template.rs#L254

**Comment by Arthur-Milchior** [comment] 2020-05-04 22:25
Unless I got things wrong, #6073 does not change any feature. I do hope that, appart from the increase in speed for complex card template, there was no difference for users.
I'm double checking it to see whether I misunderstood something.

**Comment by Arthur-Milchior** [comment] 2020-05-04 22:39
@C-Y-Liu Would you please be kind enough to copy paste your card type/template.
I've never used <% and must admit it's hard to check whether I made a mistake without an example showing what was expected to occur

**Comment by dae** [comment] 2020-05-04 22:57
@Arthur-Milchior I wasn't suggesting you broke something - I was saying that if {{Field}} inside other fields is now returned as {{Field}} instead of rendering recursively, then AnkiDroid can take the same approach as the computer version when handling this.

**Comment by Arthur-Milchior** [comment] 2020-05-04 23:06
If I got your code right (I don't speak rust), you construct a tree to represent the structures of strings and conditionals and then use the tree to build the string, by deciding which branches to prune and which to keep, and doing the replacements of fields by their values in leaves.
I could do something similar if I knew how to do a parser in java.
I must admit that, when you create the whole tree for a single template, I don't see the point of creating the complex data structure instead of just using regexps. I assume that it will be useful for more complex processing; e.g. batch rendering a lot of cards of the same type (which would be useful to actually test empty cards instead of using `reqs`)

Indeed, now that you mention it, I do realize that the infinite while loop ensured that if "{{foo}}" occured in the field "foo", then an infinite loop would occur. This would not have been the case on computer because you put a break after 100 iteration. (I discovered it when I created a card type with 200 fields; this limit ensured that it could only be reviewed on ankidroid or with an add-on)

**Comment by Arthur-Milchior** [comment] 2020-05-04 23:13
I must admit, I did break the feature of replacing {{ and }} by other values.
This was done in https://github.com/ankidroid/Anki-Android/pull/6073/commits/9307c34c9b667288d440b0f7f8934d8fdc9063c7

The problem is that I assumed that `sTag_re` never changed.  For context, this is the regexp which looks for the field opener (usually "{{") potentially followed by one of # = & ! > or {
Since I assumed this never changed, I assumed that calling the matcher multiple time with this regexp was useless. Doing a single run through the template would have been sufficient.

I was wrong, "{{=" change the field opener, and so at the point where it is found, I should have just halt the search/replace and do the loop all over again. A PR will arrive in a few minutes hopefully

Note that I can't really test it immediately, since I'm still note sure what would be a real test

**Comment by C-Y-Liu** [comment] 2020-05-05 00:19
> @C-Y-Liu Would you please be kind enough to copy paste your card type/template.
> I've never used <% and must admit it's hard to check whether I made a mistake without an example showing what was expected to occur

This is my template code. I hope it will help you.

```
{{=<% %>=}}
<div class="h1 xcolor xleft">
	<span class="ximg">🔖
	{{#《》}}	<%《》%>&nbsp;  <%Page%>{{/《》}}
 {{^《》}} Question {{/《》}}</span>
		<span id="time">
	</span>
</div>

	<div class="h2 xleft" id="div0" style="display:none; "><%Question%></div>
	<div class="h2 xleft" id="div1" style="display:block;"><%Question%></div>

{{#Answer}}
	<div class="h2 xleft slide" id='div0' style="display:block;"><hr><%Answer%></div>
	<div class="h2 xleft slide" id='div1' style="display:none; "><hr><%Answer%></div>
{{/Answer}}

{{#Notes}}
<br><div class="slide">
	<div class="h1 ycolor yleft">
	<span class="yimg">🖊
		Notes</span>
	</div>
	<div class="h2  yleft"><%Notes%></div></div>
{{/Notes}}

{{#Extensions}}
<br><div class="slide">
	<div class="h1 zcolor zleft">
	<span class="zimg">📚
		Extensions</span>
	</div>
	<div class="h2 zleft"><%hint:Extensions%></div></div>
{{/Extensions}}
```

**Comment by Arthur-Milchior** [comment] 2020-05-05 00:23
> @Arthur-Milchior does #6073 prevent the rendering of {{Field}} inside note fields?

Yes. Now that I've read again my PR I can answer. Indeed, my code make all change in a single pass; so if {{Field}} appear in a field, it won't be replaced again.

I should note that if https://github.com/ankidroid/Anki-Android/pull/6107 gets accepted, it won't be the case anymore, since the whole replacement process may restart. So if a user uses `{{={{ }}=}}` at the end of the template, the process will be executed a second time. Worse, if `{{={{ }}=}}` appears in a field content, then the process gets executed infinitely often (I should note that this problem already existed before all of my changes.)

**Comment by Arthur-Milchior** [comment] 2020-05-05 00:35
There is one thing I don't get. It seems anki only consider `{{=<% %>=}}` while AnkiDroid consider `{{=foo bar=}}` with foo and bar having no space and no "}}". I don't know why there is this difference

**Comment by Arthur-Milchior** [comment] 2020-05-05 00:54
I submitted a second PR which should be correcting this problem: https://github.com/ankidroid/Anki-Android/pull/6108
I explain the difference between both PR in the new PR. Depending on how we want to implement the retro compatibility, you may prefer one PR or another one

**Comment by Arthur-Milchior** [comment] 2020-05-05 00:55
As a side note, I'm going to correct the mistake I made and PR I opened, but I don't expect to contribute as much anymore. You may be interested in taking a look at a thank you note I left for you all https://www.reddit.com/r/Anki/comments/gdbuas/thanks_ankis_community/

**Comment by dae** [comment] 2020-05-05 01:51
The difference is that <% %> was documented in the manual and is used by some users. If anyone out there is using a different syntax, I have not come across them yet, so I don't think it's unreasonable to expect such users to update their templates.

I'm guessing your job application/process has moved along - congrats again :-)

**Closed** 2020-05-05 03:40 UTC
Labels: 2.10.x

**Comment by mikehardy** [comment] 2020-05-05 04:17
@C-Y-Liu I just released 2.10beta2 with what we *think* is a fix for this along the lines of Damien's comments above. As soon as Google is done processing it (sometimes takes an hour, sometimes takes 4 or so) it should be available on your phone as an update and hopefully it works. Please let us know how it goes! Thanks

**Comment by C-Y-Liu** [comment] 2020-05-05 04:41
> @C-Y-Liu I just released 2.10beta2 with what we *think* is a fix for this along the lines of Damien's comments above. As soon as Google is done processing it (sometimes takes an hour, sometimes takes 4 or so) it should be available on your phone as an update and hopefully it works. Please let us know how it goes! Thanks

It works well on my phone. Thanks!

**Comment by Arthur-Milchior** [comment] 2020-05-05 08:31
Great. Sorry again for breaking this feature

**Comment by mikehardy** [comment] 2020-05-05 13:43
Progress is very rarely linear, but usually worth attempting anyway. So far this is our only 2.10 beta bug report, that's frankly amazing.
