### ISSUE TITLE
Feature request: select card and export them

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8045] opened 2021-01-23 16:42 UTC
Following upstream, I believe it would be nice to be able to select card(s) in the deck browser and have an option to export them. It would be especially useful to share buggy card for debugging or to share a card type with an example without needing to share a whole deck or create it

**Comment by TarekkMA** [comment] 2021-03-10 00:48
I'm going to try to implement this feature

**Comment by TarekkMA** [comment] 2021-03-10 01:35
I have ported the feature from the pylib library, and added a menu item to export selected cards from the ``CardBrowser`` activity.
<img src="https://user-images.githubusercontent.com/6633545/110561577-9a3d2f80-8150-11eb-9415-160136c31cbe.png" width="25%"><img src="https://user-images.githubusercontent.com/6633545/110561582-9c06f300-8150-11eb-825c-1c79d09947f0.png" width="25%">


But the issue is the exporting methods is tightly coupled to ``DeckPicker`` activity. 

I'm thinking about creating a helper class named ``ExportHelper`` and both ``CardBrowser`` and ``DeckPicker`` will delegate the exporting functionally to it. And only handle ``onActivityResult()``

``ExportHelper`` will control the prograssbar and other dialogs, the listener, and ``exportToProvider`` function

Interested to hear your thoughts about this

**Comment by mohaned-hassan** [comment] 2021-03-27 20:13
can I work on this if this issue is still open?

**Comment by david-allison-1** [comment] 2021-03-27 20:23
Thanks for the interest! There's an open pull request which will close this, so it'd be best to work on something else.

**Comment by mohaned-hassan** [comment] 2021-03-27 20:33
ok

**Comment by simranBhamra** [comment] 2021-11-03 00:25
@Arthur-Milchior Hi Arthur, 
I am going to try to work on this for a school project. Can you explain what is meant by "share buggy card for debugging". 

Thanks in advance!

**Comment by simranBhamra** [comment] 2021-11-03 00:55
@Arthur-Milchior  Is this issue still open? I see there was a pull request that went stale and you mentioned in a comment that it was better to pick a different issue. However,  since this is still open is would I be able to work on this for a school project?

**Comment by Arthur-Milchior** [comment] 2021-11-03 02:52
Since Tarekk leaved us, it would be great to have someone taking the issue over and closing it. You can probably either use the commits from the existing PR, rebase them onto master and resolve the conflicts. You can also read them to inspire you and create your own PR. Or you can create a PR from scratch (but I doubt it's the best idea)

**Comment by dae** [comment] 2022-07-18 18:45
See https://github.com/ankidroid/Anki-Android/pull/8159#issuecomment-1186151840

**Closed** 2022-10-13 19:59 UTC
Labels: Good First Issue!, Anki Ecosystem Compatibility, Keep Open
