### ISSUE TITLE
Crash on switching app while edit tags dialog is open

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16351] opened 2024-05-04 11:36 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- In the Browser, select a card and choose Edit tags from the menu.
- Switch to another app

### Expected behaviour

No crash

### Actual behaviour

The "AnkiDroid has encountered a problem. A report is being sent ..." message appears. On switching back to AnkiDroid, the main screen of the app is displayed, not the edit notes dialog.

### Debug info

```text
AnkiDroid Version = 2.18beta2 (dc5348852b15e0f27521acd3c5457595f4676f54)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-5; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.123 Mobile Safari/537.36

ACRA UUID = 70fd8e4a-1bcf-4f20-8bac-43ba9946410f

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-05-04 11:58
Can't reproduce immediately

**Comment by david-allison** [comment] 2024-05-04 12:02
This appears to be a duplicate of your previous report of trying to edit the tags for a large amount of cards

**Comment by user1823** [comment] 2024-05-04 12:04
That was not my report, but someone else's. More importantly, here I am trying to edit the tag of a single note, not multiple notes.

**Comment by david-allison** [comment] 2024-05-04 13:31
Oh, I checked using ACRA which went to your reports. Could I get their debug info?

**Comment by user1823** [comment] 2024-05-04 13:36
I am not sure what I am supposed to provide you. I have already shared the debug info in the first post.

**Comment by david-allison** [comment] 2024-05-04 14:16
If that's their debug info, then it's likely the same issue: 

Do they have a huge amount of tags on the card?

**Comment by user1823** [comment] 2024-05-04 14:29
> If that's their debug info

It looks like there is some confusion. 

When I said "That was not my report", I was replying to your comment where you said that this issue seems to be a duplicate of another report posted by me (and I assumed that you were talking about https://github.com/ankidroid/Anki-Android/issues/16226). 

Anyway, the current issue is being experienced by me and the debug info is also mine.

> Do they have a huge amount of tags on the card?

The card has only a single tag. However, in my whole collection, I have thousands of tags.

**Closed** 2024-05-21 23:31 UTC
Labels: Bug, 2.18
