### ISSUE TITLE
Language setting does not work in 2.9.2beta4

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#5636] opened 2019-11-22 23:47 UTC
###### Reproduction Steps

1. Change language in Settings 
2. Restart, clean cache

###### Expected Result
Interface in selected language

###### Actual Result
Interface in system language

###### Debug info
AnkiDroid Version = 2.9.2beta4
Android Version = 9
ACRA UUID = 1e82c68a-fdc6-4201-ace5-5f2d2d4c6039

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2019-11-23 02:05
with apologies, this is a dupe of #4729 and has some partial work that is unfortunately stalled #5339 but the existing developer time has focused on other things for now. I'd like to see this fixed eventually but it'll need someone to finish it up

**Closed by mikehardy** 2019-11-23 02:05 UTC

**Comment by homocomputeris** [comment] 2019-11-23 13:15
OK, thanks. When I created the issue, that one wasn't shown in suggestions but only those from 2015.
