### ISSUE TITLE
Audio stops prematurely when "Automatically play audio" option enabled

### ISSUE THREAD

**Issue by mighty-cthulhu** [ankidroid/Anki-Android#5142] opened 2018-12-01 06:58 UTC
This is a reincarnation of https://github.com/ankidroid/Anki-Android/issues/1729

###### Reproduction Steps

1. Enable option to automatically play audio
2. Study a bunch of cards with audio

###### Expected Result

Audio always plays to the end

###### Actual Result

A small portion of audio at the end is sometimes cut off. Audio always plays completely when started manually. 

###### Debug info
AnkiDroid Version = 2.8.4
Android Version = 9
ACRA UUID = 52d6fd21-45ad-4229-834b-b16c62882197

Collection with a bunch of cards for which I've seen this bug: [Ankidroid_sound_bug.zip](https://github.com/ankidroid/Anki-Android/files/2661131/Ankidroid_sound_bug.zip)

###### Devices
Sony Xperia XZ2 Compact 2018 (Android 9) - **reproducible**
Moto X 2013 (Android 5.1) - could not reproduce
Nexus 7 tablet 2013 (Android 6.0.1) - could not reproduce
Moto G6 2018 (Android 8.0.0) - **reproducible**

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mighty-cthulhu** [comment] 2018-12-02 02:45
Results for a few other devices:

Moto X 2013 (Android 5.1) - could not reproduce
Nexus 7 tablet 2013 (Android 6.0.1) - could not reproduce
Moto G6 2018 (Android 8.0.0) - **reproducible**

Will make a collection with some media files tomorrow.

**Comment by mikehardy** [comment] 2018-12-02 02:50
Thanks @mighty-cthulhu - you can see why these are hard to nail down :-). Ideally it's then an Android 8.0.0 thing and the problem shows up on the emulator - if it's a Motorola + Android 8.0.0 thing, it's going to be really hard because I don't have that handset

**Comment by mighty-cthulhu** [comment] 2018-12-02 02:59
Not just Motorola, also Sony Xperia XZ2 with Android 9 (mentioned in the first message of this thread)

**Comment by mikehardy** [comment] 2018-12-02 03:07
Ah yes - sorry! That gives me more hope. Maybe it's Android >= 8.0.0 - as soon as you post a collection I'll check it real quick to see

and note that github won't take an '.anki2' file, but they're actually just zip files and if you just rename it collection.zip or whatever and it works fine for me

**Comment by mikehardy** [comment] 2018-12-10 17:00
I was not able to reproduce this in either an API27 (8.1) or API28 (9) emulator :-(

I haven't tried on my handset (OnePlus 5, API27) or tablet (Samsung S2, API27) yet.

**Comment by robjweiss** [comment] 2019-02-08 13:38
Also having this issue on a Pixel 2 XL running Android 9, AnkiDroid 2.8.4.

I can also create a zip of a few notes with the issue if that would be helpful.

**Comment by mikehardy** [comment] 2019-02-08 14:43
Sure - we are having trouble reproducing so more examoles can help

**Comment by robjweiss** [comment] 2019-02-08 19:08
Here you go, hope it helps. Also I tend to notice that this happens more often with my shortest audio files.
[ankidroid sound issue.zip](https://github.com/ankidroid/Anki-Android/files/2846501/ankidroid.sound.issue.zip)

**Comment by SvenskNavi** [comment] 2019-08-06 12:52
I also have this issue, Pixel 2 (non XL), AnkiDroid 2.8.4.

**Comment by mattdeckard** [comment] 2019-08-06 17:50
I have definitely seen this happen on my Pixel 2 (non XL) before but it has been a while and it was _very_ infrequent. I'm on 2.8.4 now but I doubt I've ever run into this while I've been on that version. Seems like it's been weeks/months.

**Comment by mattdeckard** [comment] 2019-08-06 17:54
This may be a long shot but.. it was a few months ago that I started a new deck that I did _not_ want to play audio automatically so I had to create a new option group for it which has that option disabled, while my main deck still has it enabled under the Default option group. It's possible I haven't seen the problem since then.

Might be worth a try for someone who can reliably reproduce this to:
1. Create or download a new deck
2. Create a new option group and put the new deck in the New option group
3. Go into the New option group settings and disable "Automatically play audio"

Would be weird if that fixed it but I've seen stranger things and it might help provide a lead as to the root cause.

**Comment by SvenskNavi** [comment] 2019-08-07 13:02
Tried this, no different. First card I opened after unchecking autoplay in the new deck cut short again. As another commenter noted, it seems to happen only with shorter audio files.

**Comment by ak-il** [comment] 2020-01-30 16:27
I'm also having this issue on One Plus 6 (ankidroid) and on the desktop using the `Japanese 2k/6k core` deck.

**Comment by ovilers** [comment] 2020-05-23 19:39
I have this issue with AnkiDroid on One Plus 6T. I am also using the Japanese 2k/6k core deck, specifically [this one](https://mega.nz/#!QIQywAAZ!g6wRM6KvDVmLxq7X5xLrvaw7HZGyYULUkT_YDtQdgfU)
I am unable to reproduce the issue on dekstop. The issue began to appear after a system update in late december last year. Before this, the app worked as expected with no issues.
The issue seems to be more prominent when using bluetooth headphones, however it also appears when using the internal speaker, although not as often. The issue also seems to only trigger on certain cards, and the audio cuts off at the same point every time.
I am also unable to reproduce the issue on my Honor 7 Lite (Model number NEM-L21, android version 7.0).
 I am willing to do more testing in order to aid in resolving this issue.

**Comment by david-allison-1** [comment] 2020-05-23 22:11
@ovilers

Adding a few more debug log statements (`Timber.d`) around the area would probably be my first port of call, as then we'll be able to compare the differences between a known good, and a problematic implementation.

My first guess would be that you should try setting `OnErrorListener` and see if any errors are caught which stop playback early: https://stackoverflow.com/a/38474407

Our getting started guide may be useful: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide

**Comment by ovilers** [comment] 2020-05-23 22:23
Thanks for replying @david-allison-1

**Comment by ovilers** [comment] 2020-05-23 22:26
Thanks for replying @david-allison-1 
Unfortunately my knowledge on writing code is very poor, and i'm not quite certain i understand what exactly you want me to do. I'm guessing you're suggesting i compile a version of the app with added debug functions around the audio?

**Comment by david-allison-1** [comment] 2020-05-23 22:33
@ovilers Okay, understood. It'd be best if you could come to discord (https://discord.gg/EUcWp9) and we can work out the best way to move forwards. Feel free to email me via gmail: davidallisongithub if you'd prefer to find an alternate method of communication.

**Comment by david-allison-1** [comment] 2020-07-22 22:42
It'd be great if we could get a repro on the Samsing test lab: https://developer.samsung.com/remote-test-lab

**Comment by david-allison-1** [comment] 2020-08-05 06:12
Interesting thought: does this occur over bluetooth? Does adding silence fix the problem: https://github.com/anars/blank-audio

**Comment by mikehardy** [comment] 2020-08-05 17:16
I think most of these are bluetooth because until very very very recently (read as: all modern hardware) bluetooth sound was terrible about stopping and starting and timing, in personal experience

**Comment by Rupestris** [comment] 2020-09-21 15:55
AnkiDroid Version = 2.12.1
Android Version = 10
ACRA UUID = b914fef6-716a-4f97-949a-bf5632484f1a

I want to listen to the same audio file repeatedly. For this reason I copied the audio button 19 times ('{{Audio}}{{Audio}}{{Audio}}'). Sometimes this error occurs. Then any subsequent repitition stops prematurely at the same time.
Stopping the repeating audio and pressong 'Replay audio' may fix the issue locally though it may happen again. 

I already suspected the issue to occur more often if bluetooth is activated, though it definetely also occurs if it is not activated.

**Comment by mikehardy** [comment] 2020-09-21 16:51
@Rupestris I'm not sure this will have the same root cause, either way could you reproduce with 2.13.2 (current stable?) - there have been lots of changes since 2.12.1

**Comment by Rupestris** [comment] 2020-09-21 17:33
@mikehardy Thank you. I updated and could reproduce it.

AnkiDroid Version = 2.13.2
Android Version = 10
ACRA UUID = b914fef6-716a-4f97-949a-bf5632484f1a
Scheduler = std

**Comment by LemmusLemmus** [comment] 2021-08-10 16:34
I'm having almost the same issue. The audio more often than not cuts off prematurely. This does however only occur when there are more than one audio files being automatically played. The audio is only cut-off when using Bluetooth and it is always cut off at the same place.

When using the same pair of Bluetooth earphones on Anki desktop the issue still persists, although it manifests itself slightly differently. In Anki desktop the audio is cut off at a slightly different place and all autoplayed audio files are cut off, not only the succeeding ones as is the case in Ankidroid.

**Comment by mikehardy** [comment] 2021-08-10 16:42
This may make it possible to solve this by adding something like "extra time padding" to audio files in sequence perhaps. Bluetooth audio normally has a bit of a delay before the audio starts (in my experience, at least, though this is a vague assertion), so perhaps the timers are just out of sync somehow and the system thinks the file is done but bluetooth is behind the system's model of timing, so the system says stop too soon? ...and adding some sort of padding may help? I'm not sure there is an API to do that in the system, or if we just put a pause in place before we send the next sound through if that would work.

Easy to test at least, by going in to the code in the Sound area and if there are multiple files just crudely hacking in a Thread.sleep in there to see if there is any effect at all, then the idea may be refined if that has an effect

**Comment by LemmusLemmus** [comment] 2021-08-10 16:47
@mikehardy Even aside from this bug some customizable extra time padding would be highly appreciated, as audio files are sometimes played too quickly in succession for me to distinguish them as two separate audio files.

**Comment by LemmusLemmus** [comment] 2021-08-10 16:53
I should probably also mention that the audio is cut off at the end of the audio file and not the beginning.

**Closed** 2024-03-20 18:16 UTC
Labels: Audio, Needs Triage, Keep Open
