### ISSUE TITLE
Ankidroid : images from google are not displayed

### ISSUE THREAD

**Issue by Pat32k** [ankidroid/Anki-Android#6198] opened 2020-05-16 11:14 UTC
Hello, images from google are no longer displayed on Ankidroid. This problem only concerns Ankidroid (the same images are displayed correctly on Ankiweb and on Anki on my computer).

I've checked the manual, and have tried to resolve the problem myself but it doesn't work.

###### Reproduction Steps

1. 
2. 
3. 

> Sorry, I don't unterstand what it means... :-(

###### Expected Result

see a picture 

###### Actual Result
no picture

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.10.2

Android Version = 10

ACRA UUID = ff24c429-68a8-42c1-b791-0095e664101c

**Comment by david-allison-1** [comment] 2020-05-16 11:20
Hi @Pat32k,

We can't reproduce the issue given the above steps.

Could you either: 

* Provide the HTML content of a note which no longer displays
* Export your collection, including media, and provide it to us (either publicly, via a link to Google Drive/DropBox here, or privately in an email to me (gmail: davidallisongithub) if your data is sensitive).

All the best,

David

**Comment by mikehardy** [comment] 2020-05-16 17:10
External images that are not served over https will likely not load in 2.10.
You could 
- stay on 2.9.x (it will be available forever)
- alter the cards to use HTTPS or (better) 
- not reference remote material in your flash cards, that is discouraged in general as it breaks your ability to work offline and stresses the internet for flash card reviews. There is an AnkiDesktop plugin you can use to "internalize" your images automatically and then this should work as well https://ankiweb.net/shared/info/221033553

I'm going to close this though, our supported methods for loading media do work

**Closed by mikehardy** 2020-05-16 17:10 UTC
Labels: Waiting For Feedback
