### ISSUE TITLE
Bug: Reminder minute can't be changed in a particular but major operation 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4530] opened 2017-01-06 13:27 UTC
###### Reproduction Steps

1. [Deck options] on a deck >[Reminders]>[Enable reminder notifications for this deck]>Enable 
![image](https://cloud.githubusercontent.com/assets/10436072/21718883/b23da618-d45d-11e6-8289-c0c466a4c051.png)

2. Tap [Remind at].
![image](https://cloud.githubusercontent.com/assets/10436072/21718456/fdc999a0-d45a-11e6-8908-a8702c527158.png)

3. Tap the the hour or the minute, then the number keyboard is displayed.  
![image](https://cloud.githubusercontent.com/assets/10436072/21718568/a7426d5e-d45b-11e6-93ee-684f47f06edc.png)

4. Change both the hour and the minute with the number keyboard (not using the drum roll)
![image](https://cloud.githubusercontent.com/assets/10436072/21718642/19b49b00-d45c-11e6-8c6a-38857a0267c1.png)

5. Tap [OK] in the "Remind at" popup  
![image](https://cloud.githubusercontent.com/assets/10436072/21718662/3ea1c280-d45c-11e6-9844-3c167e03798a.png)

###### Expected Result

Both the hour and the minute are changed to new ones, in this case, "21:00" is changed to "22:30".

###### Actual Result
The minute isn't changed. 
![image](https://cloud.githubusercontent.com/assets/10436072/21718706/841f7302-d45c-11e6-951a-b16683797c0b.png)

###### 
2.8beta3

**Comment by madhead** [comment] 2017-01-18 13:32
What is the android version here? I can try to reproduce on an emulator...

**Comment by snowtimeglass** [comment] 2017-01-18 14:31
The version is 4.3

**Comment by snowtimeglass** [comment] 2017-01-18 15:13
The behavior can be reproduced on Android 4.4.2 on an emulator (Nox App Player). 
AnkiDroid: 2.8beta3

**Comment by timrae** [comment] 2017-01-26 04:19
@madhead 
Any idea on this? I don't really want to delay the release much further.

**Comment by timrae** [comment] 2017-01-26 04:50
FYI I can't reproduce on Android 7.

@snowtimeglass 
Are you able to check with the [official Android emulator](https://developer.android.com/studio/run/emulator.html)? I'm not familiar with this "Nox App Player", but it doesn't really look reputable to me.

**Comment by madhead** [comment] 2017-01-26 09:36
No, no ideas. Maybe a bug with a native component. I was not able to reproduce on Genymotion.

**Comment by snowtimeglass** [comment] 2017-01-26 13:00
@timrae, @madhead 
The bug can be reproduced on the official Android emulator.

- Android 4.4
- AnkiDroid 2.8

![image](https://cloud.githubusercontent.com/assets/10436072/22331231/b4d96564-e40d-11e6-8d75-f52ed8cf412e.png)

![image](https://cloud.githubusercontent.com/assets/10436072/22331256/d73bbfb2-e40d-11e6-8e91-2deeadc065ca.png)

Click the the hour.
![image](https://cloud.githubusercontent.com/assets/10436072/22331266/e3a814e4-e40d-11e6-9849-8b78d248b341.png)

Change both the hour and the minute with your computer's physical keyboard (not using the drum roll on the screen) (Please **don't push [Enter] key** after inputting the minute, i.e. "30".)
![image](https://cloud.githubusercontent.com/assets/10436072/22331271/e772dd7a-e40d-11e6-8cb5-c2fba244ad65.png)

Click [OK] in the "Remind at" popup on the screen.

###### Expected Result

Both the hour and the minute are changed to new ones, in this case, "21:00" is changed to "22:30".

###### Actual Result
The minute isn't changed. 
![image](https://cloud.githubusercontent.com/assets/10436072/22331276/ec4f1afc-e40d-11e6-835d-a5d4d58ec4b6.png)

**Comment by snowtimeglass** [comment] 2017-02-16 13:05
@timrae 
Would you add the `advanced-reminders` label to this issue, too?

**Comment by snowtimeglass** [comment] 2017-02-16 13:22
Thank you!

**Comment by timrae** [comment] 2017-09-11 22:04
@snowtimeglass 
Is this still reproducible in the 2.9 alphas?

**Comment by snowtimeglass** [comment] 2017-09-12 09:56
Hi, it is still reproducible in 2.9alpha7 on my device (Android4.3).

**Comment by mikehardy** [comment] 2018-10-08 03:34
Reproduced still with 2.9alpha42 on API19, but not API21. API20 did not go into wide release and there is no emulator. The time picking widget changed between API19 and API21

I really hate doing this, but the APIs with the problem represent 20,000 or so of our 930,000 or so users checked in play console just now. 

I'm going to close this as a won't fix, with apologies to those affected

**Closed by mikehardy** 2018-10-08 03:34 UTC
Labels: Priority-Medium, accepted, advanced-reminders
