### ISSUE TITLE
[BUG]: No Way to Flip Card in Editing Preview When Answer Buttons Position Is Set to ‘None'

### ISSUE THREAD

**Issue by MarvNC** [ankidroid/Anki-Android#13569] opened 2023-04-07 21:43 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Settings -> Appearance -> Answer buttons position as `none`
- Have swipe gestures for flipping cards enabled
- Go to Card browser, tap on a card, tap the :eye: icon for preview
- Attempt to flip the card

### Expected behaviour

Either the answer button should be visible anyway, or gestures should work to flip the card.

### Actual behaviour

Nothing happens.

### Debug info

```text
AnkiDroid Version = 2.16alpha94

Android Version = 13

Manufacturer = Google

Model = Pixel 6

Hardware = oriole

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6 Build/TQ2A.230305.008.E1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.48 Mobile Safari/537.36

ACRA UUID = 1e650f01-412b-4de7-8d5e-f94f0a14f062

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by MarvNC** [comment] 2023-04-08 02:56
Frustratingly tried to look into the code and try fixing it myself, but I ran into issues as [this URL](https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.9/org.jacoco.agent-0.8.9-runtime.jar) 404s in the US for some reason causing the build to fail. Using a VPN allowed me to download the jar but I wasn't able to build still nor do I know where to put the jar to fix it manually. Here's a commit I want to test that I think could solve the issue? Will try again tomorrow to test. https://github.com/ankidroid/Anki-Android/commit/31d1ebc14f35658419b45c8a67429049d2bac196

**Comment by mikehardy** [comment] 2023-04-08 13:45
Until the maven central repo has geographical coherency in its distribution of jacoco 0.8.9 you can also imply try *locally* altering that version (but not committing...) to 0.8.8

**Comment by BrayanDSO** [comment] 2023-04-08 15:21
Duplicate of #12045

**Closed by BrayanDSO** 2023-04-08 15:21 UTC
Labels: Bug, Needs Triage
