### ISSUE TITLE
Add support for the new Scheduler v2 from Anki 2.1

### ISSUE THREAD

**Issue by Alphyn-gunner** [ankidroid/Anki-Android#4905] opened 2018-07-24 07:03 UTC
###### Research

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum
***
~~I'm posting this issue because Anki 2.1 RC1 is released and I'm worried about the compatibility between the desktop version and Ankidroid once the stable 2.1 is out. I'm sorry if it is still too early to post this issue.~~

Anki 2.1 stable is now released. 

The 2 most notable changes in the new scheduler are:
- The improved behavior of the filtered decks. The progress of the Learning cards is no longer reset when they are moved between the original deck and a filtered deck.
- The improved behavior of the subdecks. When studying a master deck, the cards from the subdecks within are taken in the proper SRS order, rather than in alphabetical order, how it was in the old scheduler. In other words, now the subdecks are properly mixed and not just stacked on top of one another.

Switching to the new scheduler in the desktop version breaks the compatibility of the collection with Ankidroid. Damien added the support of the new scheduler to Ankiweb and Ankimobile after he introduced it to the desktop beta.

From my (layman) point of view, the following steps need to be taken:

1. Basic support for the synced collections with the new scheduler enabled in the desktop version.
2. Ability to switch between the versions of the sheduler right in Ankidroid.

The changes the new scheduler introduces create a lot of opportunities for the more creative and efficient use of the filtered decks and subdecks. I think many Anki users will agree with me that it would be great to see those new features supported in Ankidroid as well.

Edit: [here's the article](https://anki.tenderapp.com/kb/anki-ecosystem/experiment-scheduling-changes-in-anki-21) with a more in-depth description of the new scheduler.

Thank you!

**Comment by mikehardy** [comment] 2018-08-28 23:16
Some notes as I look through the code:
- the [SYNC_VER goes to 9](https://github.com/dae/anki/commit/bbccc4fd6be1d13eea515cb809b2050966aefccb#diff-be58d55ab11f38bc77a9e44496f1d2a8) to use it
- the database schema version is still 11, so there doesn't seem to be a schema update needed
- v2 schedule packages [have the .anki21 extension](https://github.com/dae/anki/commit/0cce540d83b7e8179be410db62487acef0472e1c#diff-8accc4ce103267d07b06628f36f5b0a1R394) in place of .anki2
- scheduler version is stored as ["schedVer" in the JSON object persisted into the "conf" column of the collection table](https://github.com/dae/anki/blob/master/anki/collection.py#L90) in the database, and [is synchronized](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java#L264) 

Not sure what kind of implementation plan would fly here (and I'm certainly not saying I have time to do it) but the original scheduler port was pretty straight between from Python to Java, perhaps this one can be as well. The ability to go back and forth between the two (even though it is difficult and involves all sorts of gates on package import/export and synchronization) seems like a good idea given Anki is a distributed system.

**Comment by mikehardy** [comment] 2018-10-08 03:02
This is obviously popular - I just want to note that even the primary Anki developer has mentioned that it is involved and we should tackle the other 2.1 items first.

Other than that, the original scheduler port was as straightforward as it could be made from Python to Java, if someone wanted to look at schedv2.py and start the process, PRs would be welcome!

**Comment by mnhende2** [comment] 2018-10-08 08:43
Mike,
Thanks for all you, Tim and any others do in developing AnkiDroid.  Always much appreciated!  While many of us look forward to the new scheduler being incorporated, we know that the AnkiDroid team is constantly working on a number of other important upgrades or bug fixes also.  So, just a note of thanks for all the great work done and a future note of thanks for when the new scheduler and other features are incorporated as possible.
Best,
mnhende2

**Comment by Moosehorse123** [comment] 2018-11-15 22:39
Has anyone found a workaround for this which allows for offline studying on Android? I have not touched AnkiDroid since using v2 scheduler for fear of messing up card schedules. The anki online website is an option but the interface leaves something to be desired...

**Comment by mikehardy** [comment] 2018-11-15 22:41
AnkiDroid is the only Anki client on Android I know of, and it doesn't support v2 scheduler yet, so if you want offline study, you either need to stick to (or convert back to - it's possible) v1 scheduler, or make a PR here for V2 scheduler support (which would be awesome, by the way ;-) )

**Comment by Moosehorse123** [comment] 2018-11-15 22:59
Aw thanks for the reply @mikehardy, I have rudimentary python training and your notes above go over my head, so I fear my PR would just be worthless 🙈

**Comment by mikehardy** [comment] 2018-11-25 14:38
I will mention I have looked at the code for transitioning between v1 and v2 scheduler in AnkiDesktop and it looks sane to me. If someone wanted to try going from v2 scheduler to v1 and report here how it works, at least people that see this issue will know what they need to do in order to use AnkiDroid until this is solved

**Comment by abdusamed91** [comment] 2018-11-27 06:56
> This is obviously popular - I just want to note that even the primary Anki developer has mentioned that it is involved and we should tackle the other 2.1 items first.
> 
> Other than that, the original scheduler port was as straightforward as it could be made from Python to Java, if someone wanted to look at schedv2.py and start the process, PRs would be welcome!

For confirmation sake to see if I am looking at this problem correctly, is the Java port of [sched.py](https://github.com/dae/anki/blob/master/anki/sched.py) to be this [Sched.java](https://github.com/ankidroid/Anki-Android/blob/33b71df023772381bb6df64b8ffa55c48367d221/AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java)

Any 'difference' pointer will be appreciated. My approach is to smply compare the two files sched.py & schedv2.py, side by side for differences/improvements.

**Comment by mikehardy** [comment] 2018-11-27 11:44
That is correct and it is the first step to implementing the feature, also looking at the v1 differences (maybe with github history) to see the original two python and Java files to see how it was done the first time

**Comment by ChrisPWill** [comment] 2018-12-15 03:58
Hi guys, I've gone through scheduler v2 in the Python codebase and replicated each difference in a new `SchedV2` class in #5164. I've had exposure to Java in the past but haven't done Android development much in the past so I'm open to any feedback. All in all, I'm prepared to assist with testing and integration of the new scheduler into the rest of the app if needed.

**Comment by Alphyn-gunner** [comment] 2019-01-30 16:50
A heads up for anyone who stumbled upon this issue looking for a temporary workaround. 

There's a family of add-ons that make it possible to enjoy some benefits of the new scheduler on PC, while you continue to use the legacy scheduler in order to retain the compatibility with AnkiDroid.

[HoochieMama: Randomize Rev Queue](https://ankiweb.net/shared/info/1460733408)
[HoochiePapa: Randomize New Queue](https://ankiweb.net/shared/info/1173108619)
[HoochieBaby: Queue Controller & Day-Learning Queue](https://ankiweb.net/shared/info/1847358755)

Of course, those add-ons will only work while you do your reviews on the desktop version of Anki. On your android device, you will have to do the reviews the old way, on a deck per deck basis. But, at least you’ll be able to sync your collection.

**Comment by Alphyn-gunner** [comment] 2019-02-02 15:19
Thank you, Mike, @hssm and everyone else who is working on this! What is a better place for feedback, this thread or #5214? 

I haven't been able to install the apk, though. I tested it on a Android 8 AOSP phone and an Anroid 6 MIUI 9.5 phone. I get the "Application is not installed" error. I deleted any previous installations of Anki and removed the Ankidroid folder.

**Comment by timrae** [comment] 2019-02-02 20:45
Is there anyone who would be willing to port over the unit tests from python to Java for us? This would be the best way to ensure that this feature gets released quickly.

**Comment by hssm** [comment] 2019-02-04 05:45
Please use this thread to report any issues you find. I don't receive notifications so I won't look at PRs after they are merged.

I've made progress on adding a version toggle in AnkiDroid, so the only task remaining is the exporting changes. I will get to that next weekend, hopefully.

**Comment by slesniak** [comment] 2019-02-07 01:03
I am using Anki 2.9alpha61 and when doing reviews on mobile, good and easy show the same interval every time (for reviews, non-lapsed).  This is different than the behavior I see on Anki 2.1.8 desktop.

My max interval is the default (36,500 days) and much longer than any of my cards (max 2.8 years) so that's not the issue.

If this comment should be made somewhere else, let me know

**Comment by Alphyn-gunner** [comment] 2019-02-07 03:41
Can confirm, I have the same issue with alpha 61. Ankidroid.E build also has this.

**Comment by hssm** [comment] 2019-02-09 14:05
Thanks for reporting the issue. I've pushed a fix for it to https://github.com/ankidroid/Anki-Android/pull/5219

**Comment by timrae** [comment] 2019-02-09 15:32
Did you see #5229?

**Comment by hssm** [comment] 2019-02-09 16:48
I did not. I've just pushed a fix for that too.

**Comment by rathsky** [comment] 2019-02-09 17:49
Are you sure you pushed? There seem no new commits/pull requests.

**Comment by hssm** [comment] 2019-02-10 18:20
The PR was already merged by that point so it didn't show up. I've just opened a new PR that completes the rest of the work and brings it in line with the desktop client (including the stats issue mentioned above).

**A very important note to anyone who is already using the v2 scheduler:** the [official instructions](https://apps.ankiweb.net/docs/beta.html) for these changes (2.1.9beta1) advise you to switch back to the v1 scheduler, update, then switch back to v2. **From this point on, switching between v1 and v2 and back will have irreversible side-effects to your revision history**. I'm not sure if this behavior will remain in the final version, but that's how it works now so be mindful of it before testing on your day-to-day collection.

Another side-note: I encountered a bug which I haven't been able to reproduce yet when burying a large number of cards where I got reviews of really easy cards with massive negative intervals (like -18 years). I'm not yet sure if this is a scheduler or AnkiDroid bug, but be aware of this potentially affecting you as well.

**Comment by Alphyn-gunner** [comment] 2019-02-10 19:14
> switch back to the v1 scheduler, update, then switch back to v2

Does this include updating Ankidroid?

**Comment by mikehardy** [comment] 2019-02-10 22:17
> **From this point on, switching between v1 and v2 and back will have irreversible side-effects to your revision history**

Am I correct in my read of the diff that the revision history is to switch the ease assigned to certain revisions? I ask because it seemed like it moved them in a very predictable way, and rather than the drastic-but-vague "irreversible side-effects to your revision history", we could specify exactly what happens as a result of these: 

2->1 https://github.com/ankidroid/Anki-Android/pull/5232/files#diff-7f010620d726ffe711b87a36f86ae4fbR2578

1->2 https://github.com/ankidroid/Anki-Android/pull/5232/files#diff-7f010620d726ffe711b87a36f86ae4fbR2585

**Comment by hssm** [comment] 2019-02-11 07:25
Sorry I should have been more clear. 

@dae You might want to be aware of this. Re: scheduler switching and revlog rewriting, I believe it needs to be restricted to queue type 0 (and 2?).

Right now going to V1 erases ("conflates") your 4's and back to V2 erases your 2's for every queue type
```
v2 -> v1 -> v2
1  -> 1  -> 1
2  -> 2  -> 3
3  -> 2  -> 3
4  -> 3  -> 4
```
V2->V1
![image](https://user-images.githubusercontent.com/789082/52549727-c2022200-2e28-11e9-8a5e-70ebd4d7d836.png)
V1->v2
![image](https://user-images.githubusercontent.com/789082/52549732-cb8b8a00-2e28-11e9-8c4c-6d4c7d1c592f.png)

**Comment by dae** [comment] 2019-02-11 08:21
Thanks for letting me know, I'm not sure how I missed that. I've pulled the beta, rushed out an update to git, and posted a warning on the beta page that people will need to restore from backup. I should have beta2 out tomorrow with the fix:

https://anki.tenderapp.com/discussions/beta-testing/1381-anki-219-beta

Are you able to confirm the current git code behaves as expected when changing the scheduler on your collection?

**Comment by hssm** [comment] 2019-02-11 09:00
Yes it looks like it's fine now.

**Comment by slesniak** [comment] 2019-02-12 19:20
Just for clarification, do I need to do the steps in https://github.com/ankidroid/Anki-Android/issues/4905#issuecomment-462157839 if I'm using the stable desktop release (2.1.8)?  Is the latest alpha release of Ankidroid compatible with 2.1.8?

I've held off doing any studying on my phone pending clarification.

**Comment by dae** [comment] 2019-02-12 23:41
2.1.8 doesn't make such a change when switching schedulers. If you don't plan on testing the desktop betas, once 2.1.9 is released I'd suggest turning the v2 scheduler off in 2.1.8, then turning it back on using 2.1.9.

**Comment by mikehardy** [comment] 2019-02-13 01:50
#5235 appears to show a v2 related review count hierarchy error

**Comment by mikehardy** [comment] 2019-03-14 21:29
Is this closable? I think it is...

**Comment by mikehardy** [comment] 2019-03-16 15:00
People that want to use this should follow the procedure to have Google Play start installing the latest alphas: https://github.com/ankidroid/Anki-Android/wiki/Installation#beta--alpha-releases

**Comment by AustinHasten** [comment] 2019-03-21 14:12
Seems to be playing nicely with the latest alpha, at least as far as I can tell. I did notice, however, that it is not possible to see (or therefore edit) the second search on a filtered deck (as 2 are supported under the new scheduler rather than 1). I intend to test whether the second search does still apply when rebuilding filtered decks via the app. Does this fall under "Add support for the new Scheduler v2 from Anki 2.1" or would another issue be raised after this is closed?

**Comment by mikehardy** [comment] 2019-03-21 14:19
@AustinHasten nice to hear it seems like it's working for you, modulo the 2nd search issue you mention. My preference is always separate issues for new things but in this specific case I believe @hssm (who did all the heavy lifting here) is careful with notifications and was only listening in on one thread, so I'm tagging him specifically and it's up to him. If he doesn't have time though, new issue is my pref

**Comment by hssm** [comment] 2019-04-06 06:50
I won't have time to look into it anytime soon, so I think close this one and open a new issue.

**Comment by mikehardy** [comment] 2019-04-17 16:38
I'm going to close this so I can maintain this as the last comment. It seems to be working for everyone. Please open new issues if something goes wrong, or if there is something remaining here that is unaddressed.

For people that land here because "your anki client is not compatible with the v2 scheduler", you need to install the latest alphas of AnkiDroid, and you'll be set:
https://github.com/ankidroid/Anki-Android/wiki/Installation#beta--alpha-releases

**Closed by mikehardy** 2019-04-17 16:38 UTC
Labels: HelpWanted, Priority-Medium, accepted, enhancement
