### ISSUE TITLE
[BUG]: All decks show the same number of total cards and total new cards

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14608] opened 2023-10-28 15:33 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Have multiple decks with different number of cards in each
- Click any deck to open the following page:
<img src="https://user-images.githubusercontent.com/92206575/278809505-3c4057b7-3b64-4276-a17b-8f38b4419883.png">

### Expected behaviour

The page for each deck shows the number of cards and new cards in that particular deck.

### Actual behaviour

All decks show the same number of cards and new cards, possibly the number of such cards in the whole collection.

### Debug info

```text
AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 13

ProductFlavor = full

Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = d808c2e4-92ce-40db-9491-1fdcb75b1f50

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2023-10-28 15:58
Can't reproduce

**Comment by pavreh** [comment] 2023-10-29 12:42
After I finished today study limit, the info screen tells me the deck is empty while there are four cards to repeat.
![Screenshot_20231029_133426_AnkiDroidA.png](https://github.com/ankidroid/Anki-Android/assets/10192661/b7f44c5c-f1ed-49f4-866e-f9bb0ff11265)

**Comment by lukstbit** [comment] 2023-10-30 11:07
@pavreh That bug is being followed in #14538

**Comment by david-allison** [comment] 2023-11-01 19:18
Issue is fixed with a `launchCatchingTask { withCol { decks.select(did)  } }` here:

https://github.com/ankidroid/Anki-Android/blob/7d15caaa4acc16a2ace7adcfb54d0158eef20c0b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L1692-L1710

**Closed** 2023-11-01 23:42 UTC
Labels: Bug, Needs Triage, Reproduced, 2.17-alpha
