### ISSUE TITLE
[Bug] java.lang.IllegalArgumentException: While trying to show a snackbar

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#15740] opened 2024-03-01 17:11 UTC
###### Reproduction Steps

1. Install app on Emulator ( with no playstore app )
2. Go to Settings
3. Click on About
4. Click Rate Ankidroid

###### Expected Result
Should show `No suitable app found` snackbar

###### Actual Result
It throws an error:
```
ACRA caught a IllegalArgumentException for com.ichi2.anki.debug
java.lang.IllegalArgumentException: While trying to show a snackbar, could not find a view with id root_layout in com.ichi2.anki.preferences.Preferences@fd1759
at com.ichi2.anki.snackbar.SnackbarsKt.showSnackbar(Snackbars.kt:122)
at com.ichi2.anki.snackbar.SnackbarsKt.showSnackbar$default(Snackbars.kt:104)
at com.ichi2.utils.IntentUtil.tryOpenIntent(IntentUtil.kt:43)
at com.ichi2.anki.preferences.AboutFragment.onViewCreated$lambda$3(AboutFragment.kt:88)
at com.ichi2.anki.preferences.AboutFragment.$r8$lambda$gjOjG3i5r4YTsTNOWsu7EfSAxM8(Unknown Source:0)
at com.ichi2.anki.preferences.AboutFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
at android.view.View.performClick(View.java:6597)
at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
at android.view.View.performClickInternal(View.java:6574)
at android.view.View.access$3100(View.java:778)
at android.view.View$PerformClick.run(View.java:25885)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 2024
```

###### Debug info
AnkiDroid Version = 2.18alpha2-debug (6bb0ea54f7e3f6f998e28c8de9c99893896260f1)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 9 (SDK 28)

ProductFlavor = amazon

Manufacturer = Google

Model = AOSP on IA Emulator

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 9; AOSP on IA Emulator Build/PSR1.180720.122; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Safari/537.36

ACRA UUID = 63de06e9-9a3d-4ee5-8c5a-ce71ab411306

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by neeldoshii** [comment] 2024-03-01 17:23
Taking it up.

**Comment by mikehardy** [comment] 2024-03-05 02:51
re-read this one while scanning milestone issues, realized if this was debug-only the priority doesn't need to be high, we can defer this to 2.18 even

**Comment by neeldoshii** [comment] 2024-03-31 17:58
I am not able to reproduce this tested on ```amazonDebug,fulldebug```. Does this issue still exists?

**Comment by david-allison** [comment] 2024-03-31 18:55
Can you show a snackbar on the fragment, or is it just that there's no crash?

**Comment by neeldoshii** [comment] 2024-03-31 19:10
https://github.com/ankidroid/Anki-Android/assets/60827173/3859c22d-cee2-4acd-a788-e8edbadcad38

I have tested it on tablet not yet tested on mobile device. But on tablet I don't see crash or snackbar.

**Comment by david-allison** [comment] 2024-03-31 21:36
> Install app on Emulator ( with no playstore app )

**Comment by david-allison** [comment] 2024-03-31 21:46
The first step would be to reproduce on 2.18alpha2-debug (https://github.com/ankidroid/Anki-Android/commit/6bb0ea54f7e3f6f998e28c8de9c99893896260f1)

I can't:

![Screenshot 2024-03-31 at 22 45 22](https://github.com/ankidroid/Anki-Android/assets/62114487/bf22ed9c-8440-4db0-8b63-f68839378a26)

And there are no `Timber.e`s logged

**Comment by david-allison** [comment] 2024-03-31 22:03
This is reproducible on an API 28 Tablet

**Comment by david-allison** [comment] 2024-03-31 22:05
Introduced in 4aaeeb3008133a8490a23f13132aa011587f4b84 - issue with the tablet layout

**Comment by RobozinhoD** [comment] 2024-04-01 18:07
Assign it to me

**Closed** 2024-04-01 19:22 UTC
Labels: Bug, Priority-Low, Reproduced, 2.17
