### ISSUE TITLE
[Bug] prop:due behaviour changed in anki desktop

### ISSUE THREAD

**Issue by voidplayer** [ankidroid/Anki-Android#8307] opened 2021-03-21 20:13 UTC
###### Reproduction Steps

1. have a few cards due yesterday 
2. search ```"prop:due<=0" AND "prop:due>=-1"```
3. Different results in desktop and in ankidroid. Ankidroid had less results to be exact

###### Expected Result
Same results

###### Tested in:
    desktop version: 2.1.42
    ankidroid version: 2.14.6

###### Aditional notes

Desktop previous to ~2.1.42~ 2.1.41 return same as ankidroid. Theres something that changed in ~2.1.42~ 2.1.41

I cant really tell what old version is doing to be honest, because all results in desktop are cards in review that were due today or yesterday as expected in the search

I searched in issues about some other bug related to searching and didnt find anything, so sorry if you are already aware of this

**Comment by david-allison-1** [comment] 2021-03-22 04:18
Could you check to see if this is an intentional change in 2.1.42 (if you're comparing to 2.1.41). It's not in the changelog

Could very likely be one of the many changes in 2.1.41: https://changes.ankiweb.net/#/?id=changes-in-2141

**Comment by voidplayer** [comment] 2021-03-22 06:50
Yes, i said 2.1.42, but its part of the changes of 2.1.41

I believe 2.1.42 was mainly a fast bug fixing release because synchting was failing

Whether is intentional im still trying to figure out the details of why the results are different. It does list some changes on how ```due``` works in the changelog

**Comment by voidplayer** [comment] 2021-03-22 07:09
```"prop:due<=0" AND "prop:due>=-1"``` returns the same results as ```is:due``` before ```2.1.41``` and in ankidroid and only cards due yesterday and today (as the result i would expect as correct) from ```2.1.41``` onwards

**Comment by abdnh** [comment] 2021-03-22 23:49
This may be relevant:
https://github.com/ankitects/anki/pull/904

My understanding is that learning and "preview repeat" (failed non-rescheduled cards in filtered decks, if my understanding is correct) cards are now included. The change also affects `is:due` apparently.

The 2.1.41 changelog also mentions something about suspended cards in this context.

**Comment by abdnh** [comment] 2021-03-22 23:52
By the way, there is also a small change affecting `is:learn`. See https://github.com/ankitects/anki/pull/895

**Comment by voidplayer** [comment] 2021-03-23 08:20
Nice finding @abdnh 

Im still trying to understand what this "preview repeat" is

I have now the search ```"deck:one" AND "is:due" AND "prop:due>-1"``` in ankidroid and desktop. No filtered decks involved yet. Desktop return 1 card more in results

I cant see anything that makes this card different. They are all in deck:one and they are all due today. Why is anki not returning this card in results?






To be honest ive always had troubles understanding how this due works. This search comes directly from clicking on a column on the stats page. I would had never come. Also, my old is:due prop:due<-1

**Comment by abdnh** [comment] 2021-03-24 21:48
Could you post screenshots of the review logs of some of these cards (the additional card at least)?
Click Cards > Info in the desktop to see the review log.

**Comment by voidplayer** [comment] 2021-03-25 08:23
Are you having problems reproducing this?

Any way, here is some screenshot. Cards 1, 3, and 5 are not showing in ankidroid. Details are from card 1

![image](https://user-images.githubusercontent.com/4019910/112441022-42571900-8d4b-11eb-8d1d-8f45d82cb7ff.png)

**Comment by abdnh** [comment] 2021-03-25 12:49
I thought of multiple potential causes for this, but all of them turned to be wrong after consulting the code.

If those were all relearning cards, could this be caused by differences between how the two clients handle them?
Maybe someone more familiar with AnkiDroid's codebase can answer this.

**Comment by voidplayer** [comment] 2021-03-25 13:36
None of those cards has been touched today (it was relearn yesterday, but not today)

Of those, only the card 1 was relearn yesterday, card 3 and 5 are not (intervals 3.1 and 2 months)

**Comment by abdnh** [comment] 2021-03-27 01:51
If my understanding of the terminology is correct, should not relearn cards stay relearn if you don't review them?

(Not sure what is actually happening with these cards.)

**Comment by voidplayer** [comment] 2021-03-27 07:50
Yes, you can see it was in relearn (i failed it with rating: 1) and then i reviewed it (with rating:3). So its no longer in relearn

None of these cards where on relearn :)

I cant see anything obvious that separate this cards either

**Comment by voidplayer** [comment] 2021-05-26 08:33
still searching for solutions

**Comment by dae** [comment] 2023-08-31 00:38
Closed by #14171.

**Closed by dae** 2023-08-31 00:38 UTC
Labels: Needs Triage, Anki Ecosystem Compatibility, Keep Open
