### ISSUE TITLE
[Bug] deck option should be closable directly

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#15652] opened 2024-02-25 00:08 UTC
When you open it, and immediately close, you get asked to confirm you want to discard the changes. As they are no changes, it shouldn't be asked

AnkiDroid Version = 2.17beta6 (c17fed63b97a464484f7ee465057ff251f54007f)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 8 Pro

Hardware = husky

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro Build/UQ1A.240205.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.178 Mobile Safari/537.36

ACRA UUID = 47035a3d-ff8b-4423-8485-1d6d82d48957

Crash Reports Enabled = true

**Comment by BrayanDSO** [comment] 2024-02-25 00:40
Duplicate of #14438

**Closed** 2024-02-25 00:40 UTC
