### ISSUE TITLE
[Bug]  Slow media downloads (F-droid version 2.15.4) from AnkiWeb or even from self hosted server

### ISSUE THREAD

**Issue by jacktheripper19** [ankidroid/Anki-Android#9196] opened 2021-07-03 20:42 UTC
###### Reproduction Steps

1. On desktop, upload a large deck (contains about 106k media files/3.5 GB in my case) to AnkiWeb or even a personal server "anki-sync-server"
2.  try to sync on Ankidroid

###### Expected Result

downloads the deck in a couple of minutes

###### Actual Result

takes forever to download with a rate of 8 media files per second while desktop anki has a rate of 300 media files per second

###### Debug info
- I'm using version 2.15.4 available on F-droid. I tried also 2.15.2 and 2.14.6 but had the same results.
- I uploaded the deck to both AnkiWeb and my self hosted server "anki-sync-server". 
https://github.com/ankicommunity/anki-devops-services
- I created new users on anki desktop and downloaded the whole deck from both AnkiWeb and my server. It took 5 minutes to download.
- On the same network, I tried doing the same using Ankidroid but it's slow in both cases 
- My internet connection is good enough (700Mbps in download)
- I'm using a Oneplus 8 pro running Android 11

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2021-07-06 13:48
I'm going to resolve this as a duplicate of #8925 - we know this is happening, we're not sure why yet. We'll need help profiling I think, to see where the time is going

**Closed by mikehardy** 2021-07-06 13:48 UTC
