### ISSUE TITLE
Add doodle feature (draw with finger to create a new note)

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3296] opened 2015-07-28 10:49 UTC
Originally reported on Google Code with ID 2400
```
Hi
It's so good to use doodle method to writing formula and draw figures. Now u can't
write engineering formula and figures.

This feature are available now in viber.

We counting the moments to use doodle in next update.

Thanks 
Mehdi & Jamshid 

```

Reported by `mjavaheran` on 2014-11-12 11:41:30

<hr>
 * *Attachment: 2014-11-12-14-52-47.png<br>![2014-11-12-14-52-47.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2400/comment-0/2014-11-12-14-52-47.png)*

**Comment by eginhard** [comment] 2015-10-31 02:26
Duplicate of #1633

**Closed by eginhard** 2015-10-31 02:26 UTC
Labels: accepted, enhancement, Priority-High
