### ISSUE TITLE
[BUG]: beta94: Some dialogs use the system language instead of the configured language

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#13369] opened 2023-03-01 00:43 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

System language is Spanish but anki is configured to use English. Sync progress dialogs are in Spanish.

### Expected behaviour

Dialog in English

### Actual behaviour

Dialog in Spanish

![Screenshot_20230228-181556_AnkiDroidA](https://user-images.githubusercontent.com/409080/222015752-dd81769d-726f-44fb-8409-52be8ded3723.jpg)
![Screenshot_20230228-181544_AnkiDroidA](https://user-images.githubusercontent.com/409080/222015754-e12bc5d8-4192-4623-a2de-3d752fa8870d.jpg)

### Debug info

```
AnkiDroid Version = 2.16alpha94

Android Version = 12

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 0819f67d-4836-45b6-90c6-ecc700511215

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2023-03-01 00:45
Both are new backend dialogs and 99% probably be cause I forgot to do something or did some mistake on my recent languages PR. Shouldn't be hard to fix

**Comment by BrayanDSO** [comment] 2023-03-01 00:49
Actually, I can't reproduce it on my phone (Samsung, Android 13)

**Comment by david-allison** [comment] 2023-03-01 00:52
PR Ref: https://github.com/ankidroid/Anki-Android/pull/12991

**Comment by doozan** [comment] 2023-03-01 01:01
I just changed Anki settings from English to Spanish and then back to English. Now the dialogs show up in English.

**Comment by BrayanDSO** [comment] 2023-03-01 01:03
So most likely it's because I forgot to upgrade the backend language in the preference upgrade. Should be easy to fix

**Comment by BrayanDSO** [comment] 2023-04-25 20:00
> This specifically only happens if you were using an alpha version with the new backend enabled then upgraded to a newer alpha with the new language configuration code. As this would only affect a very few number of people and it has a workaround, I considered that is wasn't worth to fix it.

now closing this

**Closed by BrayanDSO** 2023-04-25 20:00 UTC
Labels: Bug
