### ISSUE TITLE
Audio playback would be cut off when the answer is shown

### ISSUE THREAD

**Issue by x-ji** [ankidroid/Anki-Android#4771] opened 2018-01-12 18:48 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

Note that there was an issue on Google Groups but it doesn't seem to have been resolved: https://groups.google.com/forum/#!topic/anki-android/p1I74wU-Gdg

###### Reproduction Steps

1. Review a card with audio
2. Click on the screen to show the answer, when the audio is still playing
3. The audio gets cut off and doesn't play in full

###### Expected Result
The audio should be played in full. This is also the behavior of the desktop software.

###### Actual Result
The audio gets cut off

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by mikehardy** [comment] 2019-01-01 21:14
duplicate of #2870

**Closed by mikehardy** 2019-01-01 21:14 UTC
