### ISSUE TITLE
Show progress bar during reviews

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5186] opened 2018-12-28 09:48 UTC
Above the Ankidroid information bar (with the numbers of upcoming cards) could be placed a thin progress bar to give a visual hint about how many reviews I have already done (proportional) and how many reviews are still to come. 

I find this visual feed back VERY useful in other apps since the human eye obviously can process this visual information faster than a row of numbers.

Also, the AnkiDroid numbers (top left) are very small, so one really need to focus on them. With a progress bar one can see and assess immediately the review progress, no need to take a close look.

Also, the AnkiDroid numbers are not really correct since they show the TOTAL number of reviews due on that day but not the ACTUAL number of due cards right now during the review session (the actual number of due reviews is shown in the deck overview screen. When clicking on that numbers it shows another screen with all reviews on that day, these are the same numbers as during reviews).

So most of the time my review session ends with the red number (wrong/learning cards) being 10 or more. The progress bar would use the ACTUAL due cards as a base so that users get a correct feedback about their current review session.

Pics here: https://groups.google.com/forum/m/#!topic/anki-android/JtodgZb8ueM

**Comment by mikehardy** [comment] 2018-12-28 14:13
This is a duplicate of #4679 but I like the idea. Could you head to that bug and give it a thumbs-up as a "vote" for the feature?

**Closed by mikehardy** 2018-12-28 14:13 UTC
