### ISSUE TITLE
"A network error has occurred" AnkiDroid Version 2.7

### ISSUE THREAD

**Issue by benbassist** [ankidroid/Anki-Android#4533] opened 2017-01-07 15:16 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Try to log in on Ankidroid
2. A network error has occurred 
3. Back to step 1

###### Expected Result

Succesful log in.

###### Actual Result

Can not log in.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.7

Android Version = 4.3

ACRA UUID = 1b051e4f-820d-470a-8980-db012f889a55

Note: I could log in and sync yesterday this is a new issue.

**Comment by eginhard** [comment] 2017-01-16 13:53
Duplicate of #4536

**Closed by eginhard** 2017-01-16 13:53 UTC

**Comment by pheochromocytoma** [comment] 2017-01-21 17:36
Hi, I am experiencing the same sync error on BlackBerry Passport (10.3.0.675) using AnkiDroid v2.8, please help!

**Comment by wouterstevens** [comment] 2017-01-23 12:00
Same problem here (Samsung SM-T813, Android 6.0.1, Ankidroid 2.7).
If I type in a wrong password, it's recognized as a wrong password. When entering the right password, the network error appears.

**Comment by eginhard** [comment] 2017-01-23 13:33
See #4536  for details.

**Comment by dae** [comment] 2017-01-24 12:16
@wouterstevens that does not sound related, as you'd get the same error regardless of your password. can you still reproduce the problem?
