### ISSUE TITLE
[Bug] The new import .csv feature is sporadic and occurs on a variety of Android machines

### ISSUE THREAD

**Issue by CurranLewin** [ankidroid/Anki-Android#14170] opened 2023-07-29 11:42 UTC
###### Reproduction Steps

1. The new import .csv feature is sporadic and occurs on a variety of Android machines
2. Import window sometimes appears, sometimes not
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by CurranLewin** [comment] 2023-08-19 00:45
> Possibly a duplicate of #13683

That's true. Thank you for your help.

**Comment by david-allison** [comment] 2023-08-19 13:11
Closing as a duplicate of https://github.com/ankidroid/Anki-Android/issues/13683

**Closed by david-allison** 2023-08-19 13:11 UTC
Labels: Duplicate
