### ISSUE TITLE
copy&paste menu

### ISSUE THREAD

**Issue by rg-software** [ankidroid/Anki-Android#5532] opened 2019-10-16 15:19 UTC
I am sorry for bringing this trivial issue, but it looks like in the last update the conext menu inside card edit interface was redesigned. Now when I do a long press, I see a button to insert a "{{c1::}}" snippet. Why so? I use copy&paste functionality in Anki every day, and now it is buried in a separate burger menu, while this snippet is always under our fingertips...
And it seems there is no way to change it back :(

**Comment by mikehardy** [comment] 2019-10-16 15:39
Hi there! This is related to all the work done to make the cloze functionality in AnkiDroid more usable, but it seems like an unintended side effect. 

I just tried to reproduce it and can't though. On 2.9.1 I do this:

1. open note in reviewer
1. select edit note from reviewer option menu
1. long press anywhere with nothing selected (I get options 'Paste' then 'Cloze deletion' in that order, then others...)
1. select a word with long-press (I get 'Cut' 'Copy' 'Paste' 'Cloze deletion' in that order)

So it seems fine on my phone? (Android 9 + AnkiDroid 2.9.1)

**Comment by snoyes** [comment] 2019-10-16 16:10
https://github.com/ankidroid/Anki-Android/blob/c71c2fe04dabaff09346202ce8aaeadd745785f4/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1716

https://developer.android.com/reference/android/view/Menu#add(int,%20int,%20int,%20java.lang.CharSequence)
> Use NONE if you do not care about the order.

**Comment by mikehardy** [comment] 2019-10-16 16:13
Nice digging! Any suggestion how to untangle this and #5533 based on your findings? Might be an easy PR and - don't tell anyone - but we award *tons* of internet points to anyone that gets a PR merged :wink:  :pray:

**Comment by adamwolf** [comment] 2019-10-16 16:21
Not just internet points, but fame! I had one or two PRs merged and people
stop me on the street now and ask for photographs! :)

**Comment by snoyes** [comment] 2019-10-16 18:05
I imagine that setting the third parameter to Menu.Size() instead of Menu.NONE would fix it.

**Comment by snoyes** [comment] 2019-10-16 22:26
I've confirmed that changing that line to:
`menu.add(Menu.NONE, mMenuId, menu.size(), R.string.multimedia_editor_popup_cloze);`
will move the Cloze deletion menu item to the right.

However, it moves it so far to the right that it moves into the overflow menu on my device. I don't like that - if I'm editing a Cloze note, there are good odds that I want the Cloze deletion.

@rg-software - would you be happy leaving the Cloze deletion menu option where it is, but it ONLY appears if the note type being edited is a Cloze type? That way Basic and other non-Cloze types wouldn't show it at all, which makes more sense anyway.

**Comment by timrae** [comment] 2019-10-16 23:18
Oh nice idea

**Comment by rg-software** [comment] 2019-10-16 23:24
@snoyes, yes, I think so. I fact, I just wanted the copy&paste items back :)

And I can confirm that it is actually back after Anki update to 2.9.1 -- it seems I was still using the 2.9 version. Thanks!

**Comment by timrae** [comment] 2019-10-16 23:25
That's unexpected about 2.9.1. All that changed was the support library version.

**Comment by rg-software** [comment] 2019-10-16 23:37
There were other strange things before the update... I'll keep an eye on them. For example, I didn't know the menu item was called "Cloze deletion", because it didn't respect language settings in Anki menu, and was always displayed in the device's system language! This was true for some other parts of the UI, too, but now everything looks allright to me.

**Comment by mikehardy** [comment] 2019-10-17 12:43
Okay, so the preferred solution appears to be to have cloze deletion first still but only if it's a cloze deletion note type.

**Comment by rg-software** [comment] 2019-10-20 02:01
Oh, I think I am onto something after all.
When I switch Anki's UI language to English, everything works fine: there is a "Cloze deletion" and "paste" options side by side.
However, if I switch it to "system default" (Russian in my case), "paste" disappears!

**Closed** 2019-10-21 05:51 UTC
Labels: 2.9.x, Good First Issue!, HelpWanted, UI

**Comment by timrae** [comment] 2019-10-21 22:19
Released in 2.9.2beta2, please test

**Comment by Manupedro** [comment] 2019-12-01 02:27
> Released in 2.9.2beta2, please test

I tested and CLOZE DELETION is not more a problem!
Thanks! Thanks! Thanks!
