### ISSUE TITLE
Graduating Interval is not synced with Anki Desktop

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7567] opened 2020-10-29 22:05 UTC
Reported on reddit. Anki 2.1.35

* Edit Deck Options: New - Graduating Interval (set to 2 days)
* Sync
* Open Anki Desktop
* Interval is 1 day

**Comment by thiswillbeyourgithub** [comment] 2020-12-30 11:24
Affected by this. I just realized this a few days before my exams and it is extremely problematic. I don't know when the graduating interval changed but it went from 7 days to 1.

**Comment by dougkrahmer** [comment] 2021-04-16 06:29
This issue also occurs if you force a full sync and re-download from AnkiWeb, so there is definitely a problem in how AnkiDroid writes this data.

**Comment by Arnold2381** [comment] 2021-04-28 06:48
@david-allison-1 I checked this issue and this is not only for Graduating Interval but for all the items in Options like New Cards, reviews, Lapses, General
Description is working fine.
And the opposite is not true if I changing some setting in the desktop and syncing it, it's getting updated in Droid too. 

Screencast of the AnkiDroid

https://user-images.githubusercontent.com/46752548/116357564-39f67000-a81a-11eb-8fe9-82ebfdf153b7.mp4

Screenshot of Anki Desktop after syncing

![image](https://user-images.githubusercontent.com/46752548/116357944-b8eba880-a81a-11eb-9f22-cea0b2fcab08.png)

**Comment by thiswillbeyourgithub** [comment] 2021-06-21 08:22
I don't know if it helps but the issue is still happening in the latest release (2.15.4)

**Comment by mikehardy** [comment] 2021-06-30 14:37
Either #8889 should remain open or this should remain open but this is reported a lot and we have a few duplicates in the system we need to conslidate

Going to close this in favor of #8889 for now

**Closed by mikehardy** 2021-06-30 14:37 UTC
Labels: Anki Ecosystem Compatibility, Bug, Help Wanted, Keep Open, Priority-High, Reproduced
