### ISSUE TITLE
Auto capitalization should be on when adding cards

### ISSUE THREAD

**Issue by mila6452** [ankidroid/Anki-Android#3758] opened 2015-10-24 16:18 UTC
Android test version.
Please make the input fields sensitive (e.g. entering a new card)
- The first letter is always capital
- The letter after a sentence (after a '.' character) Shoud be automatically capital

The same behavior that works using the browser. (When you add a new card)

**Comment by ospalh** [comment] 2015-10-24 16:31
Hmm.
There was another issue, #3754, that *complained* about the keyboard switching to capitals for the first letter.
There seems to be no agreement about what the Right Thing is here.

**Comment by x1704e** [comment] 2015-10-28 09:30
Then perhaps an option in the settings allowing us to choose would do the trick.

**Comment by timrae** [comment] 2015-10-28 09:35
As far as I understood #3574, the behavior in AnkiDroid v2.4.4 was to *not* auto-capitalize the first letter, whereas now it *is* auto-capitalizing. Is that not the case? Nobody was complaining about it before we changed the version, so if we just set it back to what it used to be there should be no objection right...?

**Comment by timrae** [comment] 2015-10-28 09:41
By the way, you can install v2.4.4 from [here](https://github.com/ankidroid/Anki-Android/releases/tag/v2.4.4) if you need to check the old behavior. You'll need to uninstall the beta first, which will *not* delete any of your existing cards.

**Comment by mila6452** [comment] 2020-06-09 20:13
Still looking for the solution..... I agree that an option should be introduced in case some one would use in this way and someone would use on another way.

**Comment by mikehardy** [comment] 2020-06-09 20:32
This changes per keyboard installed on the device. The easiest workaround might be to use SwiftKey when you want auto-capitalization (it doesn't allow you to turn it off!) and use GBoard when you don't (it starts lower-case I believe).

Note that in volunteer projects "an option should be introduced" should be read as "if I want this I should think about implementing the change..." - and I don't mean to be snarky at all, just that it really is all of us building the app together and we rely on users to make feature contributions

**Comment by mikehardy** [comment] 2020-07-08 19:07
Reported that GBoard auto-capitalizes "in all other apps" but not AnkiDroid. I'll reopen this in case someone wants to investigate, if we are doing something that alters GBoard behavior from it's default at least, we can look into that

**Comment by GoldenSnitch9** [comment] 2020-07-15 20:24
Any progress?

**Comment by mikehardy** [comment] 2020-07-15 20:33
@GoldenSnitch9 I have not seen a PR from you? There will be no progress without it being visible here, and likely no progress until an interested party proposes a fix.

**Comment by GoldenSnitch9** [comment] 2020-07-15 20:40
I'm sorry, what's a PR?
You suggested making an account and giving a thumbs up...that's what I did

**Comment by mikehardy** [comment] 2020-07-15 20:47
@GoldenSnitch9 no worries :-), A PR is a "Pull Request" it's when someone checks out our source code (we're open source, it's all available / all our development is in the open), figures out a fix for the problem that's bugging them, or implements a new feature they want, then they propose that fix here. We review it and if it works, we merge it in and it goes out in the next release

No one has proposed a fix for this, so the issue is just sitting idle. You will get email notifications if there is any activity though

**Comment by GoldenSnitch9** [comment] 2020-07-15 20:54
@mikehardy Oh, I see. Well I have recently started using Anki for my med school prep. I just now downloaded the SwiftKey keyboard as per your suggestion. Hope someone finds a solution soon :) Thank you

**Comment by mila6452** [comment] 2020-09-15 22:13
Still looking for the solution..... Hoping someone could do it, and this topic could be closed as resolved.

**Comment by mila6452** [comment] 2020-11-16 19:24
Still looking for the solution ... do not give up!

**Comment by david-allison-1** [comment] 2020-11-23 19:51
@mila6452 Thanks for the boundless patience, will get this in tonight or tomorrow for AnkiDroid 2.15

**Closed** 2020-12-08 14:21 UTC
Labels: Enhancement, Note Editor
