### ISSUE TITLE
[Bug] In alpha 92, collection synchronised message occurs before media sync 

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#13023] opened 2022-12-22 01:46 UTC
###### Reproduction Steps

1. Sync collection with AnkiWeb 

###### Expected Result
Collection synchronised message appears after the whole process of synchronisation (including media sync) is complete.

###### Actual Result
The message appears after the completion of main sync and before the beginning of media sync.

The alpha 91 had the correct behaviour.

###### Debug info
AnkiDroid Version = 2.16alpha92

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pratyaksh1610** [comment] 2022-12-22 05:48
@user1823 I am unable to reproduce the issue, can you share a mockup (i.e video) of the issue, Thanks !

**Comment by user1823** [comment] 2022-12-22 06:10
Even I am unable to reproduce the issue now.

I think it may be possible that the issue occurs when media is to be synced from AnkiWeb to AnkiDroid.

I will try this when I get to my computer and update here.

**Comment by user1823** [comment] 2022-12-24 16:51
I tried to reproduce the issue, but I couldn't. But I am sure that I saw the issue occurring not once but thrice after I installed the latest alpha. Maybe some special conditions cause the issue to occur. I will update when I see the issue occurring again.

**Comment by mikehardy** [comment] 2022-12-24 17:39
I'm going to close this as "not reproducible" but we collaborate frequently @user1823 and I appreciate the testing - obviously we'll reopen and check if there is something going on. At a meta level: the "collection" actually is a distinct sync from the media sync (in my mental model they are two fully separate processes, where collection sync is blocking but media sync is non-blocking even...) so the message behavior you see - even if reproduced - *may* be correct from my perspective 🤔

**Closed** 2022-12-24 17:39 UTC
