### ISSUE TITLE
[Bug] Dark mode: horizontal lines are not visible in MathJax fractions or roots

### ISSUE THREAD

**Issue by choralbari** [ankidroid/Anki-Android#10119] opened 2022-01-08 18:00 UTC
###### Reproduction Steps

1. View a MathJax card in light mode. Notice the horizontal lines in fractions and roots are displayed correctly.
2. Switch to dark mode.
3. Horizontal lines have vanished

Note that I have set my text size to XXS in system preferences. I'm unsure whether this is relevant.

###### Expected Result

Horizontal lines are still visible in dark mode.

###### Actual Result

Horizontal lines vanish in dark mode

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Xiaomi

Model = M2012K11AG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; M2012K11AG Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36

ACRA UUID = a7de9d6d-3d8e-49a9-a72d-f2cdfd48285d

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by AkechiShiro** [comment] 2022-01-08 20:11
Could you please provide a screenshot of the issue, I have tried to reproduce it under the version 2.16alpha34, I have the same phone as you I believe, mine is a Xiaomi Poco F3 and under the dark theme, or light theme fraction bar appear correctly.

**Comment by choralbari** [comment] 2022-01-08 20:48
This is a new phone and I wasn't aware MIUI was "forcing" dark mode. I disabled the forced dark mode for AnkiDroid, turned on dark mode in AnkiDroid manually, and fractions display correctly now.

**Comment by AkechiShiro** [comment] 2022-01-09 00:04
@choralbari Could you please close this issue then I guess, I couldn't reproduce the issue as well even by using the forced dark mode on MIUI.

**Comment by david-allison-1** [comment] 2022-01-09 01:48
Fixed in #9802. Thanks for the report!

**Closed by david-allison-1** 2022-01-09 01:48 UTC
