### ISSUE TITLE
How to inset two or more picture

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#3668] opened 2015-09-25 13:00 UTC
When I "Add image" to add another picture to note,the next picture will replace the last picture.So how to inset two or more picture in my android-anki?

**Comment by flerda** [comment] 2015-09-25 13:18
Duplicate of #3669

**Closed by flerda** 2015-09-25 13:18 UTC

**Comment by Juddd** [comment] 2015-09-25 13:26
I'm sorry,the network is not good in China,When I post the first succussing I don't recieve any response.So I post anothor poster.
