### ISSUE TITLE
stop html code from showing up in AnkiDroid when you edit card

### ISSUE THREAD

**Issue by student2374** [ankidroid/Anki-Android#5390] opened 2019-07-22 09:21 UTC
When I make a card on my computer and then try to edit it on ankidroid it shows html content which gets confusing and hard to edit card content

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2019-07-23 02:19
This is a duplicate of a long-standing request - lots of people want this but no one has stepped up to implement it yet #1377

**Closed by mikehardy** 2019-07-23 02:19 UTC
