### ISSUE TITLE
Make deck title optional, or always show it on "edit" menu when "fullscreen mode" is enabled

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#14962] opened 2023-12-12 20:39 UTC
The deck title was recently removed (#14931) in a way that has resulted in a usability regression for me. I have "Fullscreen Mode - Hide the system bars" enabled, which hides the title bar while reviewing, but makes the deck title and the edit menu buttons visible when using the "back" gesture. This was a helpful trick to be able to "reveal" the deck name when needed, which was especially helpful to get context if I needed to edit the note while reviewing. I don't think the same result can be achieved using CSS, as proposed in #14918.

**Comment by mikehardy** [comment] 2023-12-12 22:02
🤔 but, when you edit a note, isn't the current deck for the note in the edit note screen?

Not disputing, trying to understand

**Comment by david-allison** [comment] 2023-12-12 22:58
This will be possible again after:

* https://github.com/ankidroid/Anki-Android/issues/14286

**Comment by BrayanDSO** [comment] 2023-12-12 23:04
![image](https://github.com/ankidroid/Anki-Android/assets/69634269/e2990b31-d3fd-459c-a97a-fa3de4a255ba)

**Comment by doozan** [comment] 2023-12-13 00:25
It's not just for editing, but sometimes to get a clue about the source/region of a card, and often for making the decision of whether or not I should dismiss an obscure card or make edits to improve an ambiguous card.

In my case, I'm often reviewing a mix of Spanish vocabulary that either comes from a corpus of "most common words" plus specific vocabulary from books that I've read. While the corpus contains mostly "general Spanish," the decks make from books include words that may be particular one region (Mexico, Spain, Cuba, Argentina, etc) or even just dated or obscure words.

During a review session I'll sometimes encounter an English definition that could apply to multiple synonyms (usually a sign that I need to edit the clue) and after I've thought of all of the words that it could be, I like to check the deck name in case it helps me remember "oh yeah, this is the obsolete word for embers that Garcia Marquez is obsessed with" or "this is from the book that takes place in Argentina, so it's probably the regional variation" or "oh, this was that word for mud that I've only ever encountered in that one book of poetry, and I probably don't need to keep learning that because nobody will understand it." Without being able to check the deck name before answering, I'll probably get the answer wrong, then have to open the editor to see the deck name and make the appropriate changes to the card. It's not a huge deal, but it is still an annoying enough regression that I switched back to alpha9.

**Comment by david-allison** [comment] 2023-12-13 01:26
@doozan 

I'd hate to lose you, would any of the solutions listed in my above comment be useful? (especially if we can implement gesture actions and it would fix this issue):

* https://github.com/ankidroid/Anki-Android/issues/14962#issuecomment-1852944386

**Comment by doozan** [comment] 2023-12-13 12:15
Unless it adds additional gestures, I don't think #14286 is viable because I've already got up/down/left/right assigned to other actions, plus it will require some coding and editing note types that likely goes beyond what the average user can be expected to do. `{{hint:Deck}}` is any easy, ugly workaround, but still not workable for users who aren't comfortable editing note types. If I'm the only person (ab)using this feature, then it's fine to remove it and I won't complain further. I reported it here more for early awareness of something that could negatively affect other users.

**Comment by Alphyn-gunner** [comment] 2023-12-24 07:20
I think it was a horrible idea to promptly remove the deck title without an option to turn it back on. In fact I came here to report the missing deck title as a bug. This indeed seems to be a feature regression. 

As the previous user said, editing the card template is an ugly workaround for a missing feature. I expected the option to turn the deck tile on to be in the appearance settings.

The PR that removed the Deck title sounds like someone went and hardcoded a personal preference.

The oversimplified use case:
Front: DOG
2 possible decks - vocabulary or kanji. 
Or Spanish and French.
Or Greek and Major mnemonic system.

**Comment by dae** [comment] 2023-12-30 00:14
I was not involved in the decision, but my 2c: I don't think it's about personal preferences. It's about the fact that there are limited developer resources, and every extra feature in the app increases the maintenance burden and complexity of the settings for users. Given than {{Deck}} already exists as a more flexible solution (arbitrary positioning, conditional revealing, etc), and it works across all the Anki clients without add-ons, a separate option to display it in the top bar is hard to justify.

**Comment by david-allison** [comment] 2024-01-03 14:37
To be fixed in:

* #15147

**Closed by david-allison** 2024-01-03 14:37 UTC
