### ISSUE TITLE
Previewing different card wouldn't show properly type

### ISSUE THREAD

**Issue by someone120** [ankidroid/Anki-Android#16234] opened 2024-04-21 08:50 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Edit card types
2. Click "Preview" button 
3. Change card on "Preview" view

### Expected behaviour

Show different card.

### Actual behaviour

Show same card.

### Debug info

```text
AnkiDroid Version = 2.18alpha8 (6fc26947fd31743bc83e68f17ae7fec64bfa8e62)

Backend Version = provider(?) (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = Xiaomi

Model = 23116PN5BC

Hardware = qcom

Webview User Agent = null

ACRA UUID = 14c9007a-1dec-462b-bf52-ff5d63f0aeb1

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Image reproduce step:
1.![IMG_20240421_164745](https://github.com/ankidroid/Anki-Android/assets/47704813/d41d0835-8ad6-4012-a6d7-e71c9741dffe)

2.![IMG_20240421_164757](https://github.com/ankidroid/Anki-Android/assets/47704813/3196518c-d6f2-47a0-ba48-121255d47d24)

3.
![IMG_20240421_164914](https://github.com/ankidroid/Anki-Android/assets/47704813/85ffbf5f-4316-4220-ba10-1ee66547f817)

Get：
![Screenshot_2024-04-21-16-49-56-081_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/47704813/dfac662f-805e-480b-978b-207d46d00279)

卡片1 should show:
![Screenshot_2024-04-21-16-45-56-695_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/47704813/a2c95d1a-01df-4eeb-84f8-aefa65722add)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2024-04-21 09:49
Duplicate of #16155 and fixed in 2.18beta9. Next time, when posting an alpha bug, please check the latest one.

**Closed** 2024-04-21 09:49 UTC
Labels: Bug, Needs Triage
