### ISSUE TITLE
Crash when trying to reset progress

### ISSUE THREAD

**Issue by ByteHamster** [ankidroid/Anki-Android#4589] opened 2017-02-21 20:36 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open card editor 
2. Open 3 dot menu
3. Click "reset progress" (hope that's the correct translation)

###### Expected Result
Progress is reset

###### Actual Result
AnkiDroid crashes

###### Debug info
```
02-21 21:31:25.735 20409 20409 I AnkiDroid: NoteEditor:: Reset progress button pressed
02-21 21:31:25.750 20409 20409 D AndroidRuntime: Shutting down VM
02-21 21:31:25.765 20409 20409 E ACRA    : ACRA caught a IllegalStateException for com.ichi2.anki
02-21 21:31:25.765 20409 20409 E ACRA    : java.lang.IllegalStateException: Fragment null must be a public static class to be  properly recreated from instance state.
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:384)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v4.app.BackStackRecord.add(BackStackRecord.java:363)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v4.app.DialogFragment.show(DialogFragment.java:158)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:348)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at com.ichi2.anki.NoteEditor.onOptionsItemSelected(NoteEditor.java:864)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.app.Activity.onMenuItemSelected(Activity.java:2914)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:198)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v7.view.menu.h.dispatchMenuItemSelected(MenuBuilder.java:822)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v7.view.menu.k.a(MenuItemImpl.java:156)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v7.view.menu.h.performItemAction(MenuBuilder.java:969)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.support.v7.view.menu.n.onItemClick(MenuPopup.java:127)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.widget.AbsListView$3.run(AbsListView.java:3903)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:739)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.os.Looper.loop(Looper.java:148)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:5461)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-21 21:31:25.765 20409 20409 E ACRA    : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

**Comment by timrae** [comment] 2017-02-25 02:47
Duplicate of #4571

**Closed by timrae** 2017-02-25 02:47 UTC
