### ISSUE TITLE
[Bug] Some devices with Chinese Traditional will be fallback to Chinese Simplified

### ISSUE THREAD

**Issue by TragicLifeHu** [ankidroid/Anki-Android#10096] opened 2022-01-05 15:18 UTC
###### Reproduction Steps

1. Change device (basically Android 10 and up) into Traditional Chinese
2. Fresh launch AnkiDroid or use "System Language"
3. Shows Simplified Chinese

###### Expected Result
Devices with Chinese Traditional (zh-TW/zh-HK/zh-MO) to use Traditional Chinese strings/translation, not Simplified Chinese (zh-CN)

###### Actual Result
Devices with Chinese Traditional may be fallback to Chinese Simplified.

I have researched and found some system related issues.

For some newer version of Android (I tested AOSP Android 11, but MIUI and other ROMs may have different behaviors):
(java.util.locale) `Locale.getDefault().getLanguage()` only return string `zh` for both Chinese Traditional and Chinese Simplified;
and use `Locale.getDefault().toLanguageTag()` will return string `zh-Hant-TW`, `zh-Hant-HK` or `zh-Hans-CN`. `Hant` refers to Traditional, `Hans` refers to Simplified, and `TW`, `HK`, `CN` is region code;
if use `Locale.getDefault().getScript()`, then system will directly return string `Hant` or `Hans`.

But for some older version of Android (I tested MIUI Android 9), things are different:
`Locale.getDefault().getLanguage()` also returns string `zh`;
but for `Locale.getDefault().toLanguageTag()` the system returns `zh-TW`, `zh-HK` or `zh-CN`;
and `Locale.getDefault().getScript()` returns blank.

So as I could see, Language utilities used by AnkiDroid couldn't handle this situation. There needs some workarounds for Chinese language initialization.

###### Debug info
There won't be debug logs

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment] 2022-01-05 16:07
Thanks for the report!

Duplicate of #7173. Pull requests are highly encouraged for this one, it's been a bother for a long time. 

I'd ask that unit tests were included in this, as it's one that's tricky to get right, I'm happy to help if you're inclined.

**Closed by david-allison-1** 2022-01-05 16:07 UTC

**Comment by mikehardy** [comment] 2022-01-05 18:02
I thought the extra detail here was great and carried to the main issue, thanks!
