### ISSUE TITLE
Deck options settings not syncing properly across android mobile and tablet

### ISSUE THREAD

**Issue by ashrafbelim** [ankidroid/Anki-Android#9169] opened 2021-06-30 04:15 UTC
Whenever I change deck option graduating interval in mobile to 7 days and then sync it, the change is not reflected in tablet, when I tried manually to change graduating interval in tablet to 7 days and then sync it The graduating interval of mobile again changed to 1 day. same happens when I change the graduating interval in mobile to 7 days and sync tablet, interval in tablet changes to 1 day.

**Comment by mikehardy** [comment] 2021-06-30 12:36
Hi there! You have deleted the part of the issue template where we ask you for information necessary to help you.

In addition for your specific problem we need the version of Anki Desktop you are using

https://github.com/ankidroid/Anki-Android/blob/master/.github/ISSUE_TEMPLATE/issue_template.md

---
name: Bug report
about: Bug report
title: "[Bug]"
labels: bug
assignees: ''

---

###### Reproduction Steps

1. 
2. 
3. 


###### Expected Result



###### Actual Result



###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2021-06-30 14:00
I think this is a duplicate of #8889 - if I'm right, please close and we can focus there

**Comment by ashrafbelim** [comment] 2021-07-01 04:39
Ok

**Closed** 2021-07-01 04:39 UTC
