### ISSUE TITLE
max-height and max-width ignored

### ISSUE THREAD

**Issue by gregreen** [ankidroid/Anki-Android#3612] opened 2015-08-16 18:46 UTC
In cards with large images, the CSS `max-height` and `max-width` property are effectively overridden by the way AnkiDroid handles large images (see [here](https://github.com/ankidroid/Anki-Android/blob/c23cbff141e7ad9e5e5115a7b8a62169ee4ca05c/AnkiDroid/src/main/assets/card_template.html)). For example, if the card template specifies

```
img {
  max-height: 120px;
}
```

for a very large image, AnkiDroid's automatic image rescaling overrides `max-height`, setting the image width/height to whatever AnkiDroid's built-in maximum size is, rather than what the user specified. This happens even if 120px is _less_ than the maximum height, potentially causing the final image to be taller than 120px.

**Comment by hssm** [comment] 2015-08-16 22:18
What version of Android? How does it behave on the Desktop client?

**Comment by gregreen** [comment] 2015-08-17 15:50
I'm using AnkiDroid 2.4.3 on Android 5.0.1 (running on a Samsung Galaxy S4).

On the Desktop client (Anki 2.0.32, Qt 4.8.6 PyQt 4.10.4, running on Ubuntu 14.04), `max-height` works as expected. On AnkiDroid, however, `max-height` seems to have no effect at all for large images.

**Comment by gregreen** [comment] 2015-08-18 18:14
It seems like the problem right now is that Ankidroid handles large images with a JS script, which can potentially override what the user puts in the CSS. Isn't it possible to handle large images purely through CSS styling? That would make it more straightforward for users to modify image size in the cards, through the normal CSS override rules. Is there some reason this isn't a possible/easy fix?

**Comment by timrae** [comment] 2015-08-19 00:17
Because we implement pinch to zoom on Android. It's quite complicated to
get everything working in practice

**Comment by hssm** [comment] 2015-08-19 01:07
>Isn't it possible to handle large images purely through CSS styling?

That's what the JavaScript does for the platforms where doing this actually works.

>Is there some reason this isn't a possible/easy fix?

The file you linked to has a lot of comments explaining why we're doing it this way.

Unfortunately we can't cover every possible use case when dealing with many versions of the WebView (each with its own set of problems). We do cover the most common cases, and if you're writing your own template you should be able to make it work without too much extra effort.

In your case you can avoid the style rule being overridden by using a more specific selector instead of just `img` to restrict your image size.

**Comment by gregreen** [comment] 2015-08-19 01:33
I've tried increasing the specificity of my CSS selector, but I've had no luck. Here's my CSS:

    div.limit-img-size div#id-of-img img {
      max-height: 15%;
    }

Here's my HTML:

    <div class="limit-img-size">
      <div id="id-of-img">
        {{img-field}}
      </div>
    </div>

That *should* be more specific than the selector used [here](https://github.com/ankidroid/Anki-Android/blob/c23cbff141e7ad9e5e5115a7b8a62169ee4ca05c/AnkiDroid/src/main/assets/flashcard.css), but this still only works on the Desktop client.

**Comment by hssm** [comment] 2015-08-19 02:09
Oh, percentage-based max-height is a different story. According to [the spec](http://www.w3.org/TR/CSS21/visudet.html#min-max-heights):
>If the height of the containing block is not specified explicitly...the percentage value is treated as...'none' (for 'max-height').

Modern browser engines are more compliant with the spec. It may have worked on older browsers like the one that ships with the desktop client, and pre-lollipop Android (before they replaced the WebView with the new Chrome backend), but it was never really the "correct" way to do it.

I will change our base template to include a height, so it will fix the base use case (single image field on front or back) but more complex templates will have to account for this behaviour themselves.

**Comment by gregreen** [comment] 2015-08-19 02:45
Okay, switching to a pixel value for `max-height` worked, in combination with increasing the specificity of the CSS selector. Maybe [the Anki Manual](http://ankisrs.net/docs/manual.html#card-styling) should be updated to reflect this. That's what I was following to make my card template, and as written, it doesn't work.

My final CSS was:

    div#id-of-img img {
      max-height: 150px;
    }

And my HTML was:

    <div id="id-of-img">
      {{img-field}}
    </div>

**Comment by timrae** [comment] 2015-09-08 11:58
It looks like this can be closed then?
The Anki manual is [open source](https://github.com/dae/ankidocs/blob/master/manual.txt), you can submit a PR to Damien :)

**Comment by hssm** [comment] 2015-09-08 12:05
I'm reopening it since there is still something that could be done to improve the default behaviour. Even the built-in 90% max-height doesn't work on later devices, and anyone with large images will be affected by it.

I just haven't found the right combination of html to make it work without breaking some other layout behaviour. I'll look into it more one day.

**Comment by timrae** [comment] 2015-09-08 12:06
:+1:

**Comment by llakssz** [comment] 2016-03-08 09:23
I also have this problem, an image should be limited to 150px, it works fine on desktop but not on my phone;
`img {
  width: 200%;
  height: 200%;
  max-width: 150px;
  max-height: 150px;
}`
The image is simply {{Image}}, no containing div.

Is there any progress? And from above, if I contain it in a div it should be ok?

**Comment by hssm** [comment] 2016-03-08 09:44
Sorry no progress on this. Yes, you can override the default by enclosing it in a `div` and re-defining the `max-height` and `max-width`. Another way that should work is if you keep what you have but append `!important` to the rules you want to force. I.e..:

```img { width: 200%; height: 200%; max-width: 150px !important; max-height: 150px !important; }```

**Comment by llakssz** [comment] 2016-03-08 10:18
Thanks for the tip about '!important'.
Now that I saw the little fix above about putting the image in a div and specifying the div, it's not really a big issue - that worked perfectly.
I'm sure there are things to fix more that are more !important than this... :)
Thanks for the help!

**Comment by gajewsk2** [comment] 2017-08-11 19:24
Seeing something like this on 2.9alpha4 but it's not working with the !important div fix. Here's a deck to reproduce

**Comment by timrae** [comment] 2017-08-11 23:11
And alpha6?

**Comment by gajewsk2** [comment] 2017-08-13 04:14
checked alpha7 and its back to working

**Comment by mikehardy** [comment] 2018-10-08 03:40
I'm going to close this because it appears to be more of a documentation issue at this point, but reopen with details if I'm wrong

**Closed by mikehardy** 2018-10-08 03:40 UTC
