### ISSUE TITLE
[BUG]: Card browser's due date sort not matching new and review order

### ISSUE THREAD

**Issue by Nefcanto** [ankidroid/Anki-Android#15883] opened 2024-03-14 02:36 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Update to the 2.17.5

Go to card browser

Change display order

Select due time (ascending or descending)

Create only one deck

Deck options

Set these orders:

![Screenshot_2024-03-14-06-01-57-492_com ichi2 anki-edit](https://github.com/ankidroid/Anki-Android/assets/12782347/77d11ba5-0712-4232-b60a-2444b202a27a)

Now compare the top row with what comes for new or review

They are completly different

### Expected behaviour

New cards order and review order if set to random and due date should match card browser's sort by due date

### Actual behaviour

They are not related

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = Xiaomi

Model = 2201116PG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 2201116PG Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

ACRA UUID = aab36e08-79bc-43c3-bc87-1b50b478d918

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-03-14 07:06
Card Browser's going through a rewrite currently, this will be handled when the rewrite is completed:

Closing this as a duplicate of the below, as it'll be consistent with Anki Desktop after it's fixed

* https://github.com/ankidroid/Anki-Android/issues/11889

**Closed by david-allison** 2024-03-14 07:06 UTC
Labels: Card Browser
