### ISSUE TITLE
Rendering of the response card breaking the content (2.17.4)

### ISSUE THREAD

**Issue by JhonnySalles** [ankidroid/Anki-Android#15796] opened 2024-03-06 15:41 UTC
###### Reproduction Steps

1. show answer card
2. 
3. 

Recently, only one device I use shows the update, on which I updated to the latest version from the Google store. After the update I noticed that some of my cards were experiencing display problems, which in the previous version worked correctly.
Apparently something related to the update is breaking the page and its contents.

My layout was not changed at any time, I don't know how to get the page log, since unlike some Ankidroid API errors that showed an error message, but the card just appears to be lag loading but does not display error information.

It may have occurred in one of the recent updates, as version 2.16 on the device that is not receiving the update still works (Android 14).

![Screenshot_20240306_120302_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/43912638/8683c805-c463-494d-bb66-9c809366c3aa)
Error version: 2.17.4

###### Expected Result

When displaying the response card, the content is presented without fail, in which the css has loaded and the layout is correct.

![Screenshot_2024-03-06-11-48-32-049_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/43912638/bdfdb7a8-40bd-479f-b1bb-2dd2d0a2fcb5)
Front

![Screenshot_2024-03-06-11-48-38-113_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/43912638/b18bc143-f966-4b93-b69a-28f5094033a7)
Back

![Screenshot_2024-03-06-11-48-42-786_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/43912638/ba4073af-6793-472c-8e62-fb8d760d8249)
Back

###### Actual Result

When displayed the response card is breaking the css

![Screenshot_20240306_114858_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/43912638/097b3a23-85f7-4fde-8322-551bb513fc5a)
Front

![Screenshot_20240306_114915_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/43912638/a4f429b5-3bb9-44e2-a6f1-02f084fd9206)
Back

![Screenshot_20240306_114911_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/43912638/ff046d28-0f9d-4e56-bee7-f4dee7b2d9cb)
Back

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-03-06 15:55
Thanks for the report! I believe this is already fixed in `main` and will be fixed in 2.17.5

Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/15773
* https://github.com/ankidroid/Anki-Android/issues/15773

**Closed by david-allison** 2024-03-06 15:55 UTC
