### ISSUE TITLE
[Bug] Crash: InsertFieldDialog - Don't Keep Activities

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#9811] opened 2021-11-07 21:07 UTC
###### Reproduction Steps

1. Android Developer Settings - Enable "Don't keep Activities"
2. Deck Picker - Manage Note Types - Long Press a type - Cards
3. Long press - Insert Field
4. Minimise app
5. Maximise app

###### Expected Result

No Crash

###### Actual Result

```
2021-11-07 21:03:26.381 16777-16777/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 16777
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardTemplateEditor}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.ichi2.anki.dialogs.InsertFieldDialog: could not find Fragment constructor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.ichi2.anki.dialogs.InsertFieldDialog: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
        at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:320)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
        at com.ichi2.anki.AnkiActivity.onCreate(AnkiActivity.java:97)
        at com.ichi2.anki.CardTemplateEditor.onCreate(CardTemplateEditor.java:136)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.NoSuchMethodException: com.ichi2.anki.dialogs.InsertFieldDialog.<init> []
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getConstructor(Class.java:1728)
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483) 
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728) 
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198) 
        at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149) 
        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99) 
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:320) 
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273) 
        at com.ichi2.anki.AnkiActivity.onCreate(AnkiActivity.java:97) 
        at com.ichi2.anki.CardTemplateEditor.onCreate(CardTemplateEditor.java:136) 
        at android.app.Activity.performCreate(Activity.java:7994) 
        at android.app.Activity.performCreate(Activity.java:7978) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

###### Debug info
Latest alpha - e00531ed75169932f4eec5f047f626aaf42ae791 - branched off, but with no relevant changes

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment] 2021-11-07 21:07
I expect this is just an issue with the `FragmentFactory` that we use to instantiate the class

**Comment by mikehardy** [comment] 2021-11-17 16:35
go for it! Welcome :-)

**Comment by pun33t19** [comment] 2021-11-18 06:03
Hi i had a look through the app and couldnt find the exact place of issue....could you brief a little

**Comment by pun33t19** [comment] 2021-11-18 06:37
Hi @david-allison-1 i had a look through the app and couldnt find the exact place of issue....could you brief a little

**Comment by david-allison-1** [comment] 2021-11-18 13:10
https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialog.kt

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/InsertFieldDialogFactory.kt

Presumably `InsertFieldDialogFactory` is being used incorrectly. Take a look at how our other dialog factories are used, and where they're registered.

**Comment by Aman1131145** [comment] 2021-11-21 10:26
hey @david-allison-1 can I make this my first contribution if no one else is working on it.

**Comment by mikehardy** [comment] 2021-11-21 15:18
Sounds great! Glad you saw something else interesting, cheers

**Comment by SanjaySargam** [comment] 2022-02-04 16:33
Hey @david-allison-1  Can I contribute on this ??

**Comment by david-allison-1** [comment] 2022-02-04 16:39
> Hey @david-allison-1  Can I contribute on this ??
> 

Sure!

**Comment by xidsyed** [comment] 2022-02-04 18:35
I'd like a crack at it too... are issues allotted to people, or is it rude to work on someone else's issue 😶

**Comment by xidsyed** [comment] 2022-03-08 04:42
### Clearer Steps to replicate the problem 

1. Android Developer Settings - Enable "Don't keep Activities"
2. Open Deck Picker > Options Menu > Manage Note Types > Long Press any type > Edit Cards
3. Long press > Insert Field (Leave the modal open)
4. Minimise app
5. Maximise app

Try following these steps if you can't replicate the problem

**Comment by mikehardy** [comment] 2022-03-08 14:20
The general rule of one person per issue, and requesting / waiting for confirmation is just to make sure people have a reasonable chance to do the work, without anyone wasting their time doing duplicate work

There has been no progress on this in a month @SanjaySargam and communication / progress is an important part of the whole process here, so I will have to assume it's open again, @xidsyed if you would like to work on this please feel free

**Comment by mikehardy** [comment] 2022-03-08 14:37
This area of the code base is only barely understandable! I chose CardTemplateEditor as my first real attempt at doing Open Source and definitely my first attempt working on AnkiDroid and it was....kind of hell but also I learned so much :sweat_smile: :laughing: - so if you want to fix this my advice is: don't worry about feeling like you don't understand this area, I'm not sure anyone does, but also that should scare you (in a good way?) into making sure it is all thoroughly tested and works.

With all that said, if you've got something that you think works, go ahead and post it up as a pull request. It can never hurt to post a pull request, worst case, it gets closed right? No harm. Best case, it gets review and is either working or close to working, and with a little polish :boom: merged and a bug fixed,

**Comment by mikehardy** [comment] 2022-03-08 14:39
I thought your comment with the examples and everything was great by the way, it's not too much to read. Open Source work is asynchronous, technical, and involves lots of details. The *best* way of doing it is posting your known facts (with code snippets), your thought process for diagnosis of root cause, any questions outlined, and a rough sketch of a solution (which can be in a PR). This fits that structure perfectly, all that's missing is tossing up the PR in a way to say "what do you think?"

**Comment by xidsyed** [comment] 2022-03-08 19:57
Thanks for all the feedback Mike!

I definitely think there are ways to make this work. the constructor initialisation problem was easy, all that's left is making sure the arguments don't get in the way of the Factory getting reinitalised.

I Guess if worse comes to worse we could just... not restore the modal... its not like the user makes any progress in it that gets lost. atleast the activity wouldn't crash (Where the user could lose progress) ! 

About the **Making a PR** recommendation. Pull requests involve code changes with the intention of getting merged right? So how would a digram and an explanation suffice... I am confused 🤔

**Comment by mikehardy** [comment] 2022-03-08 21:30
> About the Making a PR recommendation. Pull requests involve code changes with the intention of getting merged right? So how would a digram and an explanation suffice... I am confused thinking

Oh! If you want to discuss a design first then sure, just post it up in here. I have actually just scribbled something on a piece of paper (as a diagram) and uploaded the pic before, fast and easy! Whatever works for you

**Comment by xidsyed** [comment] 2022-03-09 13:50
Great!

> The best way of doing it is posting your known facts (with code snippets), your thought process for diagnosis of root cause, any questions outlined, and a rough sketch of a solution (which can be in a PR).

I mean it was your idea.

**Closed** 2022-06-11 18:23 UTC
Labels: Bug, Good First Issue!, Keep Open, Card Template Editor, 2.16
