### ISSUE TITLE
[BUG]:When I click on the tag box on the word editing page, the program jumps directly.

### ISSUE THREAD

**Issue by riaranka** [ankidroid/Anki-Android#16494] opened 2024-05-28 04:24 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

When I click on the tag box on the word editing page, the program jumps directly.

### Expected behaviour

Usually a page should open allowing me to choose which tag to use for this word.

### Actual behaviour

The whole program jumps back to the mobile phone desktop. It seems that the app itself has been forced to stop.

### Debug info

```text
AnkiDroid Version = 2.18.1 (5d13819ba811c6baea34dc747fce0568c755f31a)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 12 (SDK 31)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A217F

Hardware = exynos850

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A217F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36

ACRA UUID = 30f27951-b643-4a2f-811d-1914bbf7bc40

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-05-29 00:09
2.18.2
* #16476
* #16482

2.18.3:
* #16490
* #16491

Thanks for the report. Closing as a duplicate of the above

**Closed** 2024-05-29 00:09 UTC
Labels: Duplicate
