### ISSUE TITLE
[Bug] Soft crashes on Android 11 / Moto G60S

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#10104] opened 2022-01-08 12:16 UTC
Since I got a new phone (Moto G60S, Android 11) AnkiDroid "crashes" dozens of times every day. Using the app itself is stable, but while not using the app I can see the message:
"AnkiDroid encountered a problem. A report is being sent to the developers..." all the time.

Do you have any idea what causes those problems?

AnkiDroid Version = 2.16alpha29

Android Version = 11

Manufacturer = motorola

Model = moto g(60)s

Hardware = mt6785

Webview User Agent = Mozilla/5.0 (Linux; Android 11; moto g(60)s Build/RRLS31.Q2X-70-24-2-5; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.70 Mobile Safari/537.36

ACRA UUID = 751875a7-f00b-41fe-90b1-2bcc6af0617f

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by david-allison-1** [comment] 2022-01-08 13:09
Thanks for the report.

This is either:

https://github.com/ankidroid/Anki-Android/issues/10108

or 

https://github.com/ankidroid/Anki-Android/issues/10107

Presumably: https://github.com/ankidroid/Anki-Android/issues/10108

I'll close this issue as it's been disambiguated. I feel that this is going to be caused by https://github.com/ankidroid/Anki-Android/issues/10108, and I'll fix it. Please let me know if this doesn't work. I expect it to go into alpha36

**Closed** 2022-01-08 13:09 UTC

**Comment by david-allison-1** [comment] 2022-01-11 21:10
@Anthropos888 Please let me know if this is reproducible in 2.1.36 or later. It should be resolved.

**Comment by Anthropos888** [comment] 2022-01-11 22:20
@david-allison-1 I'd like to check ot out but somehow the latest version of Ankidroid that I can see in PlayStore is 2.16.29alpha

Do I need to install the github release?

**Comment by david-allison-1** [comment] 2022-01-11 22:34
We can't upgrade the alphas on Google Play until we handle scoped storage and a risky data migration

GitHub parallel releases/source builds are currently the only option for testing

**Comment by Anthropos888** [comment] 2022-01-12 21:43
I updated to 2.16.37alpha and didn't recognize any crashes so far. But my collection now doesn't use CSS styles and pictures any more. It's like Ankidroid just ignores the CSS file. Any idea what causes that bug in 37alpha?

**Comment by david-allison-1** [comment] 2022-01-12 21:45
> @david-allison-1 I updated to 2.16.37alpha and didn't recognize any crashes so far. But my collection now doesn't use CSS styles and pictures any more. It's like Ankidroid just ignores the CSS file. Any idea what causes that bug in 37alpha?

Thanks, I'll take a look
