### ISSUE TITLE
[BUG]: Whiteboard not working in 2.17a release

### ISSUE THREAD

**Issue by KipperBoi** [ankidroid/Anki-Android#15221] opened 2024-01-14 08:17 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Enable whiteboard and attempt to draw

### Expected behaviour

Whiteboard should draw a line following the pen's movement on the screen

### Actual behaviour

Nothing is drawn when screen is touched and moved. When pen is lifted, a single point is drawn at the origin of the pen movement.

### Debug info

```text
AnkiDroid Version = 2.17alpha15 (e5b25f3fef737140ae396d1b212a8d638551500f)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 9 (SDK 28)

ProductFlavor = full

Manufacturer = samsung

Model = SM-N960F

Hardware = samsungexynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-N960F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.115 Mobile Safari/537.36

ACRA UUID = 77cec3e5-5869-4f0b-a58a-d932dbb784ea

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-01-14 14:32
Thanks for the report! Duplicate of #15176, already fixed in `main`, awaiting alpha16

* #15176

**Closed by david-allison** 2024-01-14 14:32 UTC
Labels: Bug, Needs Triage
