### ISSUE TITLE
Amazon AppStore publish rejected for camera permission request

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8151] opened 2021-03-08 04:31 UTC
###### Reproduction Steps

1. Attempt to submit a build of AnkiDroid from release-2.14 branch to amazon app store
2. 
3. 

###### Expected Result

Submission successful!

###### Actual Result

```
Your app submission does not meet one or more of our acceptance criteria for some or all targeted devices. Failure reason(s) are listed below:

    To ensure the best user experience apps may not request permissions for capabilities not present within Amazon Fire tablet or Fire TV devices. Camera functionality is not currently supported on Fire TV devices. Therefore, please remove the camera permission request and resubmit your app. For additional details see the Test Criteria for Amazon Appstore Apps section of the Appstore Developer Console.

You can view our guidelines on the Appstore Developer Portal. 
```

https://developer.amazon.com/docs/app-submission/faq-submission.html#device-targeting

:shrug: 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by kartikeysaran** [comment] 2021-03-10 09:19
Can I work on this issue !?

**Comment by mikehardy** [comment] 2021-03-14 21:30
You can but fair warning: even with a fair bit of experience in this area I am not sure on the best way to resolve it. I do the build/release script maintenance and automation here and my best guess is that we need to have another build flavor for amazon builds, with a different manifest that removes the camera permission and we need to alter the amazon APK upload script to use that flavor etc.

If you are familiar with gradle files, android flavors, AndroidManifest files etc this could be easy, if not ...it could be a lot of cool stuff to learn :-)

**Comment by imaryandokania** [comment] 2021-03-15 00:16
I can work on this, as i already have published my app on amazon app store, so i am familiar with all the process.

**Comment by mikehardy** [comment] 2021-03-15 04:50
I'm not sure exactly what you mean

Do you mean: we can remove the "uses-hardware" entry for camera in AndroidManifest.xml and that is sufficient?

Honestly it might be, I have no idea as I haven't tried. The problem is that you don't have permissions to submit our app to the Amazon store and I don't have the ability to delegate it, it's a privileged access and my abilities are limited.

So I'm not sure you can work on it directly, but if you have any information that would result in a build I could submit, I could certainly try it.

If so, base your work off the release-2.14 branch, as it is the 2.14.6 stable build I would like to get released there

**Comment by imaryandokania** [comment] 2021-03-15 08:27
I mean to say that we can go on for release of app on all non-fire devices in amazon App Store. 
Here is a pic from amazon developer portal and it says that :

<img width="701" alt="Screenshot 2021-03-15 at 2 08 19 PM" src="https://user-images.githubusercontent.com/61244704/111123956-0a581500-8598-11eb-89a3-c3eaa0a94d16.png">

I am still looking into this, maybe we can disable all camera related features and remove permission request from AndroidManifest.xml for only fire devices.

**Comment by kartikeysaran** [comment] 2021-03-15 08:30
> You can but fair warning: even with a fair bit of experience in this area I am not sure on the best way to resolve it. I do the build/release script maintenance and automation here and my best guess is that we need to have another build flavor for amazon builds, with a different manifest that removes the camera permission and we need to alter the amazon APK upload script to use that flavor etc.
> 
> If you are familiar with gradle files, android flavors, AndroidManifest files etc this could be easy, if not ...it could be a lot of cool stuff to learn :-)

Will try my best to resolve this !)

**Comment by kartikeysaran** [comment] 2021-03-15 08:31
If @imaryandokania wants to do it he can and still if the issue is unresolved i would love to work on this ;)

**Comment by kartikeysaran** [comment] 2021-03-15 08:44
> I am still looking into this, maybe we can disable all camera related features and remove permission request from AndroidManifest.xml for only fire devices.

I think the issue is because the declared permission in Manifest requires camera permission , this can be resolved by requesting a run-time permission for camera wherever it is needed inside the application what say :)

**Comment by imaryandokania** [comment] 2021-03-15 08:54
> > I am still looking into this, maybe we can disable all camera related features and remove permission request from AndroidManifest.xml for only fire devices.
> 
> I think the issue is because the declared permission in Manifest requires camera permission , this can be resolved by requesting a run-time permission for camera wherever it is needed inside the application what say :)

Yes, working on the same. Thanks !

**Comment by imaryandokania** [comment] 2021-03-15 09:11
> I'm not sure exactly what you mean
> 
> Do you mean: we can remove the "uses-hardware" entry for camera in AndroidManifest.xml and that is sufficient?
> 
> Honestly it might be, I have no idea as I haven't tried. The problem is that you don't have permissions to submit our app to the Amazon store and I don't have the ability to delegate it, it's a privileged access and my abilities are limited.
> 
> So I'm not sure you can work on it directly, but if you have any information that would result in a build I could submit, I could certainly try it.
> 
> If so, base your work off the release-2.14 branch, as it is the 2.14.6 stable build I would like to get released there

Shall I create a link for debug app, and then can you verify if it is getting accepted or not. 
Or 
Should I commit it?

**Comment by imaryandokania** [comment] 2021-03-15 13:53
can you please try this out! Since I was not able to test as I don't have permissions to test on amazon App Store @mikehardy

**Comment by mikehardy** [comment] 2021-03-15 19:01
Please create a real PR, but based on the release-2.14 branch, that way we can see the source changes, and I can run the official release script on it locally, where I have the official release signing keys for the APK and upload keys for Amazon

**Comment by imaryandokania** [comment] 2021-03-16 01:47
> Please create a real PR, but based on the release-2.14 branch, that way we can see the source changes, and I can run the official release script on it locally, where I have the official release signing keys for the APK and upload keys for Amazon

Yes would have created pr instantly but , my old pr is yet pending for second approval,there may be conflict if i create a pr of this commit.

**Comment by mikehardy** [comment] 2021-03-16 14:18
Handling conflicts between multiple PRs in flight, and being able to rebase one PR (solving conflicts) after another has merged is a core developer skill. You should not fear multiple PRs in flight at once, please propose a real PR so we can see it, I will make no attempt to publish an APK that was not built from source I can see

**Comment by david-allison-1** [comment] 2021-03-19 08:42
> @david-allison-1 I think we need to contact Amazon app store. Because I found a similar issue on amazon's [developer forum](https://forums.developer.amazon.com/questions/135455/app-available-on-web-and-amazon-app-store-but-not.html).

_Originally posted by @mrudultora in https://github.com/ankidroid/Anki-Android/issues/8269#issuecomment-802648118_

**Comment by mikehardy** [comment] 2021-03-19 17:14
@mrudultora I don't think that developer forum link is related to this issue at all, after reading it.

**Comment by imaryandokania** [comment] 2021-03-19 17:17
> @mrudultora I don't think that developer forum link is related to this issue at all, after reading it.

https://developer.amazon.com/docs/app-testing/test-criteria.html 
Here it clearly states about camera permission . Only possible can be is not making anki droid app available for fire devices!

**Comment by mrudultora** [comment] 2021-03-19 17:18
That user was exactly not having the same problem, but Camera permissions are not allowed in FireTv. Particularly, contacting the support is better because this issue is not mentioned on their pages.

**Comment by mikehardy** [comment] 2021-03-19 17:19
> Only possible can be is not making anki droid app available for fire devices

@imaryandokania I disagree completely.

As I state above:

> my best guess is that we need to have another build flavor for amazon builds, with a different manifest that removes the camera permission and we need to alter the amazon APK upload script to use that flavor etc.

However to be qualified to do this work: 

> If you are familiar with gradle files, android flavors, AndroidManifest files etc this could be easy, if not ...it could be a lot of cool stuff to learn :-)

If you do are not familiar with gradle files, Android flavors and AndroidManifest workings - and I mean *REALLY* familiar, you will not be qualified to work on this.

**Comment by imaryandokania** [comment] 2021-03-19 17:24
> > Only possible can be is not making anki droid app available for fire devices
> 
> 
> 
> @imaryandokania I disagree completely.
> 
> 
> 
> As I state above:
> 
> 
> 
> > my best guess is that we need to have another build flavor for amazon builds, with a different manifest that removes the camera permission and we need to alter the amazon APK upload script to use that flavor etc.
> 
> 
> 
> However to be qualified to do this work: 
> 
> 
> 
> > If you are familiar with gradle files, android flavors, AndroidManifest files etc this could be easy, if not ...it could be a lot of cool stuff to learn :-)
> 
> 
> 
> If you do are not familiar with gradle files, Android flavors and AndroidManifest workings - and I mean *REALLY* familiar, you will not be qualified to work on this.

Anyhow I try to solve this , as I tried my runtime permission, i have to ask for camera permission in manifest , this is the key this which is not as per amazon developer criteria written in website

**Comment by mrudultora** [comment] 2021-03-19 17:24
@imaryandokania If you are not taking this up, I am interested. Making a different flavor for Amazon app store.

**Comment by imaryandokania** [comment] 2021-03-19 17:25
> @imaryandokania If you are not taking this up, I am interested. Making a different flavor for Amazon app store.

Cool you can take over!

**Closed** 2021-04-20 03:39 UTC
Labels: Dev, Needs Triage, Release process
