### ISSUE TITLE
[Bug] UI bugs

### ISSUE THREAD

**Issue by user655362020** [ankidroid/Anki-Android#9312] opened 2021-07-25 19:22 UTC
###### Reproduction Steps

1.Open Ankidroid in landscape orientation. 

Screen size : 8 inch
Resolution : 1024x768

###### Actual Result
These screenshots show 2 different UI bugs

![Screenshot_20210726-003806](https://user-images.githubusercontent.com/66375825/126910851-ddcb7796-1a0c-4d76-b205-e60949b1ac6e.jpg)
![Screenshot_20210726-003804](https://user-images.githubusercontent.com/66375825/126910855-5c18d629-762e-4259-9ea6-e1de443d9ffa.jpg)

###### Debug info
```
AnkiDroid Version = 2.15.6

Android Version = 7.1.1

Manufacturer = samsung

Model = SM-T355Y

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 7.1.1; SM-T355Y Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.101 Safari/537.36

ACRA UUID = a865a727-96e0-47e8-909b-d3ff3697711c

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment] 2021-07-25 19:43
Thanks for the report.

Duplicate of https://github.com/ankidroid/Anki-Android/issues/9279

Fixes in our alpha: https://github.com/ankidroid/Anki-Android/pull/9285

**Closed by david-allison-1** 2021-07-25 19:43 UTC
