### ISSUE TITLE
[BUG]: S-Pen side button not working on OneUI 6.0

### ISSUE THREAD

**Issue by MaryMajesty** [ankidroid/Anki-Android#14767] opened 2023-11-18 12:33 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Do a review and enable whiteboard. Draw a line with the S-Pen. Then hold down the side button and try to erase the line with the S-Pen.

### Expected behaviour

As with previous OneUI versions, the line should get erased.

### Actual behaviour

After updating to OneUI 6.0, the line does not get erased anymore when holding down the side button and it simply draws a new line.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 14

ProductFlavor = play

Manufacturer = samsung

Model = SM-S918B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S918B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.163 Mobile Safari/537.36

ACRA UUID = d99a0b30-704f-40f7-af18-230697714582

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

I restarted my phone, cleared the cache partition, reinstalled AnkiDroid, and cleared all app data. The side button works as expected in other apps.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2023-11-18 20:37
believe it or not, I have a samsung tablet with an s-pen now! Not sure if it's oneui 6 or not though - was that a recent update for you? Also not sure I'll have time to look into it but if this sits for a while I can try to give it a check - maybe the generated keycode changed somehow

**Comment by MaryMajesty** [comment] 2023-11-19 14:53
Yes, updates to OneUI 6.0 have been rolling out recently and I got it a few days ago. I was running some version of OneUI 5 previously and the side button worked perfectly fine in AnkiDroid until the update to 6.

**Comment by mikehardy** [comment] 2023-11-21 18:11
Unfortunately, it appears my Samsung (a Galaxy Tab S6 Lite) is not eligible for the update to OneUI 6, and I will be stuck on OneUI 5 where I've just confirmed I can still erase with the side  button

ref https://www.androidauthority.com/one-ui-6-eligible-devices-3362453/

This is the line where things are implemented, the motion events are hard-coded since we cannot depend on the Samsung S-Pen Remote SDK as it has a proprietary license

https://github.com/ankidroid/Anki-Android/blob/c6fa3517c0e55e010fb8e373d572cdab9598c604/AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt#L150

Perhaps the motion events have changed in OneUI 6?

@MaryMajesty can you triple check that OneUI 6 hasn't installed some sort of software / configuration setting that is simply consuming these S-Pen events prior to our app getting them?

@BrayanDSO it appears you have an S-Pen enabled device. Is it eligible for OneUI6? If so you might be able to alter that switch statement to print out what the event was and see if we need to update the case

Otherwise perhaps I can do a debug build apk that pops up an alert or something so someone else with OneUI6 can try it and see what events are going through

**Comment by mikehardy** [comment] 2023-11-21 18:18
Note that the original PR that did this stated clearly that MotionEvent.TOOL_TYPE_ERASER was not implemented due to lack of test devices. I then looked, and that was implemented recently (but only released for the first time as 2.17alpha2):

https://github.com/ankidroid/Anki-Android/pull/14315

It may be that the S-Pen with button pressed sends that motion event, resulting in correct behavior. I see you are on 2.16.5, @MaryMajesty would you try a parallel build of the latest 2.17alpha to see if it works for you? https://github.com/ankidroid/Anki-Android/releases - it would be neat if that worked

**Comment by BrayanDSO** [comment] 2023-11-29 23:47
> Is it eligible for OneUI6? If so you might be able to alter that switch statement to print out what the event was and see if we need to update the case

Nope. Max update was to OneUI 4

**Comment by david-allison** [comment] 2023-12-19 05:33
> Here's two screenshots (first - when S pen is hovering and the pen button is clicked; this looks identical to when the S pen is actually touching the screen ... second - when S pen is only hovering). https://imgur.com/gallery/HiGvkDd
> 
> I hope this makes sense - for the first img, the AXIS_DISTANCE changes if I move from the spot I first clicked the button at (so if I click and hold the S pen button and move from the spot, it increases in value and returns to 0 when I go back to the spot I initially clicked the button). I also sometimes get values other than 0 when I touch the screen with the pen (1 [in green] seems to be the most common, though there have been other, higher values).
> 
> Pen position - first image, to the right of AXIS_DISTANCE. Second image, right around "AXIS" in AXIS_DISTANCE
> 
> The axis only change as long as I stay within the window. The top-left is 0,0 and bottom-right 1000+,1000+
> 
> I wrote this in a hurry late at night, so if anything doesn't make sense/the images aren't helpful, I can definitely retake/rewrite.

<details>

<summary>Screenshots</summary>

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/2fc8bdcd-f2ca-4b92-94fc-c7b4e25d3ec8)

**When pen button is hovering + clicked (same thing when pen is touching the screen)**

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/ddab0fcf-f090-4f30-b2dc-92797cefc1c1)

</details>

https://www.reddit.com/r/Anki/comments/18ldwdb/comment/kdzyp8w/?context=3

**Comment by mikehardy** [comment] 2023-12-19 17:34
Interesting, so if I understand this correctly, the S-Pen is now sending more standard/generic AXIS_X/AXIS_Y/AXIS_ORIENTATION events (at all times within window?) and when clicked also sends AXIS_DISTANCE?

If I understand correctly then adding conditionals to the current S-pen logic that ORs these events in to be handled like the pre-OneUI6 events might be the fix ?

**Comment by david-allison** [comment] 2023-12-19 17:41
Let me follow up, it's not ideal

**Comment by mmarlo-hassio** [comment] 2024-01-31 15:46
Has there been any developments with regards to this bug since the last post? Missing the erase function since the One UI update has been a big deal for me. Is there any action I can take towards solving it?

**Comment by mikehardy** [comment] 2024-01-31 16:01
@mmarlo-hassio it is open source, all updates will be in the open, visible here. No updates === nothing to report yet. Not sure what the next steps are but maybe @david-allison had some ideas

**Comment by david-allison** [comment] 2024-01-31 16:16
Preface:  I don't have an S-Pen enabled device

Ensure that nothing in `Settings - Controls` allows detection of the eraser button.

Otherwise, see the discussion on

* https://github.com/ankidroid/Anki-Android/issues/9670

We need an open source SDK to be able to legally use the library.

This would very likely require [clean room reverse engineering](https://en.wikipedia.org/wiki/Clean_room_design) of Samsung's SDK

This wouldn't be difficult, but it requires two dedicated people for an unspecified amount of time. It's one of those things which feels like a 'do it 100%, or don't do it at all'

Unless Samsung relicense, or unless people dedicate resources to this, I don't see a path forward with the dev capacity that we have

I'm open to suggestions on how to continue

**Comment by david-allison** [comment] 2024-02-02 19:53
I'm going to go back on my previous comment:
I've reverse engineered the SDK, and it's /probably/ not the answer:

* It supports handling button presses, and air actions, BUT it appears that we don't need to include the SDK to do this via an XML-based system:

https://developer.samsung.com/galaxy-spen-remote/air-actions.html

----

Secondly:

We need someone to let us know what the changes in the following method are with a OneUI 6.0 S Pen enabled device:

https://github.com/ankidroid/Anki-Android/blob/240d9d8f5587e685f6a9f61607aed180a639a68d/AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt#L110-L158

**Comment by mmarlo-hassio** [comment] 2024-02-02 21:17
That sounds great! I have an s-pen, but not the programming know-how. Is there a way I can test this method and share the result?

**Comment by david-allison** [comment] 2024-02-04 12:45
Hmm...

Somewhat complex, but you seem capable and motivated, let's give this a shot:

* Download Android Studio
* File -> New Project From Version Control: `https://github.com/ankidroid/Anki-Android.git`
* Enable USB Debugging on your phone and connect via USB
* Click "Run" and get AnkiDroid building and running on your phone
* Click "Debug", which runs AnkiDroid under the debugger
* Double press "shift" to bring up the search
* find `Whiteboard.kt`

Find the following lines

https://github.com/ankidroid/Anki-Android/blob/240d9d8f5587e685f6a9f61607aed180a639a68d/AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.kt#L110-L158

Set a breakpoint:

<img width="703" alt="Screenshot 2024-02-04 at 12 39 37" src="https://github.com/ankidroid/Anki-Android/assets/62114487/2b22d672-8711-42e2-98e0-63e05774e6b5">

* Open the whiteboard

When the breakpoint is hit, you'll information in the 'Debug -> watch' window, post it here

**Comment by mmarlo-hassio** [comment] 2024-02-04 13:46
Is this the information you're looking for? 

`MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=254.15527, y[0]=907.47363, toolType[0]=TOOL_TYPE_STYLUS, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=64801432, downTime=64801432, deviceId=3, source=0x5002, displayId=0, eventId=338920165 }`

**Comment by david-allison** [comment] 2024-02-04 13:54
That's exactly it! What does it produce when the button is pressed and you make a MotionEvent?

I'm hoping there's something we can use to differentiate the two

**Comment by mmarlo-hassio** [comment] 2024-02-04 13:58
Tha's great! thank you for the step-by-step instruction, that was easy to follow. 
Making the MotionEvent while the button is pressed results in this: 

`MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=317.27344, y[0]=1167.125, toolType[0]=TOOL_TYPE_STYLUS, buttonState=BUTTON_STYLUS_PRIMARY, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=65399286, downTime=65399286, deviceId=3, source=0x5002, displayId=0, eventId=258809400 }`

**Comment by TrustKibou** [comment] 2024-02-04 20:31
@david-allison @mmarlo-hassio I'm also willing to assist if either of you need! Not a professional, but studying to be a software dev :c

**Comment by david-allison** [comment] 2024-02-04 21:21
@mmarlo-hassio 

Could you change the block in 

```
MotionEvent.ACTION_DOWN -> {
    ...
    true
}
```

to

```kotlin
            MotionEvent.ACTION_DOWN -> {
                if (event.buttonState == MotionEvent.BUTTON_STYLUS_PRIMARY) {
                    stylusErase(event)
                } else {
                    drawStart(x, y)
                    invalidate()    
                }
                true
            }
```

And see if:

* the eraser works
* the erasing behaviour is as you expect?
   * especially when pressing the button while during a line

**Comment by mmarlo-hassio** [comment] 2024-02-04 21:58
@david-allison I've found the block, replaced the code and ran it. The whiteboard eraser works again!
I've replaced the action down code only, and i notice i can only erase if i touch the screen with the button pressed. It doesn't work if i was already writing (or the stylus was in close proximity) and i then click the button. (if i compare this with how Ankidroid behaved before, i didn't have to lift my hand every time i wanted to erase something, i guess that's because i didn't change the code of the action_move event?)

But this is absolutely great :D thankyou so much for guiding me through this!

**Comment by david-allison** [comment] 2024-02-04 22:03
Take 2: unsure on this one?

```kotlin
            MotionEvent.ACTION_DOWN -> {
                if (event.buttonState == MotionEvent.BUTTON_STYLUS_PRIMARY) {
                    stylusErase(event)
                } else {
                    drawStart(x, y)
                    invalidate()
                }
                true
            }
            MotionEvent.ACTION_MOVE -> {
                if (event.buttonState == MotionEvent.BUTTON_STYLUS_PRIMARY) {
                    stylusErase(event)
                    return true
                } 
                if (isCurrentlyDrawing) {
                    for (i in 0 until event.historySize) {
                        drawAlong(event.getHistoricalX(i), event.getHistoricalY(i))
                    }
                    drawAlong(x, y)
                    invalidate()
                    return true
                }
                false
            }
```

**Comment by mmarlo-hassio** [comment] 2024-02-05 09:06
@david-allison I've tested this code, and it works exactly how it did before. :D:D Also i haven't found any strange behaviour in using it.

I do care a lot about this, because i use anki for up-keep retention of various math and engineering topics (after reading "A Mind for Numbers" i though i'd give it a try, and it really does work. My longest interval is sitting at about 5 years now). It's basically solving equations and drawing diagrams, which is virtually impossible without an erase function. :P

**Comment by mikehardy** [comment] 2024-02-05 17:29
Wow. @mmarlo-hassio + @david-allison 

![image](https://github.com/ankidroid/Anki-Android/assets/782704/be5af6fc-cba7-4bcc-8bf2-8f11f59c3461)

**Closed** 2024-02-05 17:45 UTC
Labels: Bug, Needs Triage

**Comment by david-allison** [comment] 2024-02-05 21:22
@mmarlo-hassio Released in beta2, thanks so much again!

**Comment by mmarlo-hassio** [comment] 2024-02-05 21:27
@david-allison I've already used it for today's flashcards. =D I've been positively surprised with the zeal you guys maintain and improve anki. Thankyou for solving this issue, I'll make good use of it ;)
