### ISSUE TITLE
[Question] What are the actual blockers for the 2.15 release?

### ISSUE THREAD

**Issue by puelp** [ankidroid/Anki-Android#8298] opened 2021-03-21 03:11 UTC
I'm looking at issues under the 2.15 milestone (https://github.com/ankidroid/Anki-Android/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.15+release%22)

But a lot of these issues seem to be feature-requests/enhancements that are more 'would be nice to have in time for 2.15' rather than 'MUST have for 2.15'.

Is there another way to sort only for the critical issues that are blocking/must be solved before the 2.15 release?

**Comment by david-allison-1** [comment] 2021-03-21 04:10
Definitely:

https://github.com/ankidroid/Anki-Android/issues/8264 - 10 minute fix, not a worry
https://github.com/ankidroid/Anki-Android/issues/8178 - database migration regression on phones with low memory
https://github.com/ankidroid/Anki-Android/issues/8075 - rare, but will cause people to take drastic action on an error
https://github.com/ankidroid/Anki-Android/issues/8072 - likely fixed in 2.14.6, but needs confirmation

**Comment by mikehardy** [comment] 2021-03-21 04:28
Yeah - I manage the milestone but I don't really use it for planning formally in the way you might in a real software shop, sorry for that :-), but I'm also the main consumer of the information since I make the changelog from it and no one else has every paid attention!

The vast bulk of them will just be lifted and shifted to a 2.16 once the ones David mentions above are handled, and we'll keep rolling forward. If you or others start paying more attention to the milestones I'll manage them more like actual planning buckets

**Comment by voidplayer** [comment] 2021-03-21 20:26
I usually read the Milestones. They are fun to read :)

**Comment by mikehardy** [comment] 2021-03-23 16:30
@voidplayer I actually quite enjoy it as well - as mentioned I build the changelogs off them and it's amazing to see what gets done. But as a *forward* looking tool they are not useful the way I have been managing them, I've only really been managing with the changelog in mind and not other use cases

**Comment by puelp** [comment] 2021-04-11 06:19
Is there another way then to get a rough sense of the timetable for the 2.15 stable release?

**Comment by mikehardy** [comment] 2021-04-14 19:36
@puelp No. This is an open source project. I could throw a guess out there but it is much healthier for all involved (since it's all volunteer) to simply say there are no ETAs in open source projects, ever.

I'm not trying to be annoying or mean or anything I promise - just that we may discover something (anything!) important to fix before release, and it may be large, and it may take time, and it is better to not set expectations when none of us can be expected to work 80 hours a week to fix unexpected things like if we had huge salaries.

I hope it's soon personally, like a week or two, but who knows?

For that reason, we provide easy access to the alpha releases at all times, and with our automated test coverage they are never really "broken", and you can always use 2.14 in the meantime.

**Comment by mikehardy** [comment] 2021-04-14 19:38
it is worth noting that the release-2.15 milestone is pretty well curated at the moment. I am currently using it to track whether we have anything left or not, so watching it is no longer like looking at a catch-all bucket, it is now a list of things we really should complete

**Comment by puelp** [comment] 2021-05-12 08:57
I see now that the 2.15 milestone is 100% complete!

I imagine now it's time for beta, then RC? Is a very-rough estimate possible now, or are things still fluid at the moment?

**Comment by mikehardy** [comment] 2021-05-12 18:51
Trying to do the beta today, just need to do the changelog. Unfortunately I also maintain react-native-firebase (a Google product) as a day job and Google I/O is coming in a day or so meaning they are absolutely *raining* breaking changes on us and it's nutty

Patience please :pray: 

2.15 should be worth it, it was already a monumental effort and big release *before* google summer of code, then it basically doubled

**Comment by mikehardy** [comment] 2021-05-12 20:18
2.15.0beta1 is uploading to alpha channel now, It has sat with our nearly 10,000 alpha users for a few days though with only one issue (since fixed #8807 and picked onto the release branch) so I'm going to push it to the beta channel as soon as it's done. That's pretty general distribution and the full release will likely be within the week. In general I make a new version generally available about 2 days after the last beta that has no serious regressions. I can't predict how many betas that will be but it is usually not many, sometimes only 1 or so.

I'm going to close this as it's inevitable at this point - please test the beta and open separate issues for anything you find that's not already tracked.

Happy Reviewing :muscle: :nerd_face:

**Closed by mikehardy** 2021-05-12 20:18 UTC
Labels: Question
