### ISSUE TITLE
[Bug] new backend: Check your internet connection

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13773] opened 2023-04-30 14:25 UTC
https://ankidroid.org/acra/app/1/bug/37661/report/5bb64ad1-90f1-45db-b909-c4b91b2ff83a

The two japanese sentences are: "check your internet connection" and "error details"

> 
> net.ankiweb.rsdroid.exceptions.BackendNetworkException: インターネット接続を確認してください。
> 
> エラー詳細：⁨error sending request for url (): error trying to connect: dns error: failed to lookup address information: No address associated with hostname⁩
> 	at net.ankiweb.rsdroid.BackendException$Companion.fromError(BackendException.kt:93)
> 	at net.ankiweb.rsdroid.BackendKt.unpackResult(Backend.kt:38)
> 	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(Backend.kt:1)
> 	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:2)
> 	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(Backend.kt:1)
> 	at net.ankiweb.rsdroid.Backend.withBackend(Backend.kt:13)
> 	at net.ankiweb.rsdroid.Backend.runMethodRaw(Backend.kt:16)
> 	at anki.backend.GeneratedBackend.syncStatusRaw(GeneratedBackend.kt:7)
> 	at anki.backend.GeneratedBackend.syncStatus(GeneratedBackend.kt:15)
> 	at com.ichi2.utils.SyncStatus$Companion.getSyncStatus(SyncStatus.kt:50)
> 	at com.ichi2.anki.DeckPicker.fetchSyncStatus(DeckPicker.kt:7)
> 	at com.ichi2.anki.DeckPicker.access$fetchSyncStatus(DeckPicker.kt:1)
> 	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(DeckPicker.kt:4)
> 	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(DeckPicker.kt:1)
> 	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(CollectionManager.kt:3)
> 	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(CollectionManager.kt:1)
> 	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(CollectionManager.kt:15)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
> 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
> 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
> Attachments
>

**Comment by user1823** [comment] 2023-04-30 15:28
Seems to be duplicate of https://github.com/ankidroid/Anki-Android/issues/12821

**Comment by david-allison** [comment] 2023-04-30 15:46
Closing as duplicate

**Closed by david-allison** 2023-04-30 15:46 UTC
Labels: Duplicate, Backend Related
