### ISSUE TITLE
[BUG]: Enabling 2-button mode causes reviewer app bar buttons to disappear - 2.19alpha

### ISSUE THREAD

**Issue by parish-d** [ankidroid/Anki-Android#16918] opened 2024-08-21 00:42 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Enable 2-button mode in 2.19alpha developer options.

### Expected behaviour

App bar/buttons would continue to be visible in the reviewer in 2-button mode.

### Actual behaviour

App bar and buttons disappear in in the reviewer in 2-button mode.

### Debug info

```text
AnkiDroid Version = 2.19alpha11 (1e1e46d7e2ff7d9d2b51e720874ae0c891b46262)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-S901U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S901U Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = bd85dadb-68ae-4510-b361-9019967ff82d

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2024-08-21 15:14
Can't reproduce. Could you send a video showing the issue?

**Comment by BrayanDSO** [comment] 2024-08-21 16:48
I saw the forums [post](https://forums.ankiweb.net/t/enabling-2-button-mode-causes-reviewer-app-bar-buttons-to-disappear-2-19alpha/48454) that you made and you are assuming that the common settings like `Keep screen on` apply to the new reviewer.

Besides the ones in `New reviewer options` and some random other settings, they don't work yet. 

The new reviewer is a work in progress and not suited for general users, which is why it's a `Developer option`, so any reports about things "missing" are already known issues and don't help the team.

I still thank you for trying to help with the report, but I'm going to close it.

**Closed by BrayanDSO** 2024-08-21 16:48 UTC
Labels: Needs Author Reply, Can't reproduce

**Comment by parish-d** [comment] 2024-08-21 16:59
My mistake.  

Irrevelevant now, but just for the record, here's your video ...

https://github.com/user-attachments/assets/ad6fdb63-7eb4-4a70-a8d4-8b44a4c09aec

**Comment by BrayanDSO** [comment] 2024-08-21 17:07
As I expected, the toolbar appears. You just can't set which items appear on it yet, which is a known pending task.
