### ISSUE TITLE
[Bug] Sync and more options buttons disappear after syncing

### ISSUE THREAD

**Issue by ThoreBor** [ankidroid/Anki-Android#8934] opened 2021-05-25 15:38 UTC
After syncing, the sync and more options buttons on the top right disappear.

###### Reproduction Steps

1. Do some reviews (so that there are changes to sync, syncing when there are no changes works)
2. Sync
3. Doing anything afterwards makes the buttons reappear (e.g. opening hamburger menu, closing the app and reopening it etc.)

###### Expected Result
Buttons are still there

###### Actual Result
Buttons aren't there

###### Debug info
AnkiDroid Version = 2.15.0
Android Version = 10
Manufacturer = Xiaomi
Model = Redmi Note 8 Pro
Hardware = mt6785
Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi Note 8 Pro Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36
ACRA UUID = c4ca6b15-4969-4da2-ad9a-19b06686e1e9
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2021-06-08 13:43
@prateek-singh-3212 sure - going to resolve this as a duplicate of #9081 even though this was first, simply because I believe that one has more reproduction information. But I've seen this curious behavior myself and if you'd like to fix it that would be great!

**Closed by mikehardy** 2021-06-08 13:43 UTC
Labels: Help Wanted, Needs Triage
