### ISSUE TITLE
[Bug] LaTeX \! rendering incorrectly

### ISSUE THREAD

**Issue by andmis** [ankidroid/Anki-Android#10326] opened 2022-02-10 12:44 UTC
###### Reproduction Steps

Make a card containing `\[\perp\!\!\!\perp\]` (used for [conditional independence in probability](https://en.wikipedia.org/wiki/Conditional_independence#Conditional_independence_of_random_variables) in case you're wondering).

This is on 2.15.6.

###### Expected Result

<img width="78" alt="image" src="https://user-images.githubusercontent.com/5308024/153410670-9c13b29e-2475-456f-9122-94663eee002d.png">

###### Actual Result

<img width="106" alt="image" src="https://user-images.githubusercontent.com/5308024/153410777-1ba690f5-ac84-432e-a6ec-b789addc600a.png">

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2022-02-10 13:55
Hi there - this will perhaps not be the most welcome answer, however LaTeX support in the Anki ecosystem is supported for legacy reasons at the moment, but not well (for instance, I believe that image above is actually pre-rendered on Desktop then the image is simply displayed on AnkiDroid?) Mathjax is the future. It appears LaTeX perp is supported in Mathjax https://math.chapman.edu/~jipsen/mathquill/test/MathQuillsymbolsMathJax.html (search in page for perp) - have you tried using Mathjax? You may have more consistent results.

If this is actually a mathjax formula and it's displaying incorrectly, please include the contents of the card so we may inspect more...

**Comment by david-allison-1** [comment] 2022-02-10 15:44
This is a duplicate of #9002

@mikehardy That's MathJax. There's a problem with the MathJax's HTML renderer when run inside a WebView. 

This can be reproduced with an Android WebView and loading the MathJax site on Android.

We can fix this with an option to use the MathJax `svg` renderer instead (I've had pushback on making this the default), or spending time fixing the upstream HTML rendering code in MathJax.

**Comment by mikehardy** [comment] 2022-02-10 16:03
Ah - good work @david-allison-1 - yes, I will close this as a duplicate, here's the referenced pushback on making it default: https://github.com/ankidroid/Anki-Android/issues/7915

Adding an option to render SVG vs CHTML at least lets people choose where they want to land in the tension between "better formatting" (using SVG) vs "maybe doesn't load extensions" (so you need CHTML render).

It appears the "real" resolution would be to dig in to #7915 and resolve it without revert to CHTML, ideally by using the upstream Anki desktop Mathjax bundling somehow

**Closed by mikehardy** 2022-02-10 16:03 UTC

**Comment by david-allison-1** [comment] 2022-02-10 16:20
I believe we're using the same bundling, but it's broken inside an Android WebView, so somewhat more complex to fix
