### ISSUE TITLE
make keyboard shortcut customizable

### ISSUE THREAD

**Issue by ji-zh** [ankidroid/Anki-Android#7955] opened 2020-12-25 23:11 UTC
Please make keyboard shortcut customizable.  There should be a customization interface to specify per action a short cut key.

**Comment by david-allison-1** [comment] 2020-12-26 02:55
Agreed! I'd done some work on this - should be with you at some point in 2021

Duplicate of #6052

**Closed by david-allison-1** 2020-12-26 02:55 UTC
