### ISSUE TITLE
Show code when edit cards

### ISSUE THREAD

**Issue by mtbox9x** [ankidroid/Anki-Android#8798] opened 2021-05-09 09:50 UTC
<img src="https://user-images.githubusercontent.com/82198256/117567225-6eeda700-b0e5-11eb-850d-2353bfed0f68.png" height=500></img>

I am using 2.15alpha49. this deck i downloaded from internet. It's difficult to edit cards because of code. But on ankimobile, this issue is not exist, so i think the reason is not because of the deck. Thank you. I'm sorry for my english 😂

**Comment by Akshay0701** [comment] 2021-05-09 14:34
> I'm sorry for my english 

No problem @mtbox9x, as far I understand your main problem is "you want to view the whole card in note editor while editing"
am I right ?, if yes then we are working on a visual editor project that includes this feature to preview card from note editor 
you can see work on it here #7962

**Comment by mtbox9x** [comment] 2021-05-10 00:54
> > I'm sorry for my English
> 
> No problem @mtbox9x, as far I understood "you want to view the whole card in note editor while editing",
> 
> am I right? if yes then we are working on a visual editor project, we will be including a feature to preview card in the note editor,
> 
> you can see work on it here #7962,
> 
> Thank you.

![B98773F1-D0A6-4096-B422-B907E14C9CBD](https://user-images.githubusercontent.com/82198256/117592980-d26ae980-b164-11eb-9fbe-c9ad824e8a6d.png)I want the note editor to show up like this

**Comment by infinyte7** [comment] 2021-05-10 02:06
In Anki Desktop the html is not shown. When click on edit html then it shows.
<img src="https://user-images.githubusercontent.com/12841290/117596958-1e268e80-b177-11eb-856a-d5cd882d1bba.png" height=500></img>

**Comment by infinyte7** [comment] 2021-05-10 02:19
It may be duplicate of #1377

**Comment by AXiSource** [comment] 2021-05-10 13:30
I don't think @mtbox9x is asking for WYSIWYG but simply for the ability to hide html tags in fields.

Example: 

- Field with html tag : <b>one</b>

- WYSIWYG : **one**

- Field with html tags hidden : one

**Comment by mikehardy** [comment] 2021-05-10 14:08
I don't believe it is valid to just hide semantically important (for the card render) html code.
Either we can interpret it and let you edit it while interpreted (WYSIWYG) or you see the code.
The alternative is hiding it then users blow up their formatting during edit on AnkiDroid and we get errors related to that.

This is a duplicate of #1377

**Closed by mikehardy** 2021-05-10 14:08 UTC
Labels: Anki Ecosystem Compatibility, Help Wanted, Note Editor
