### ISSUE TITLE
[Bug] Notification service crash the app if it runs during sync

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8264] opened 2021-03-18 04:13 UTC
###### Reproduction Steps

0. Turn on notification
1. Reinstall AnkiDroid
2. Start ankidroid
3. Sync

###### Expected Result

Syncing.
A notification.

Not crashing

###### Actual Result

Crash with the stacktrace:

> 2021-03-18 04:53:05.640 22370-22370/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 22370
    java.lang.RuntimeException: Unable to start receiver com.ichi2.anki.services.ReminderService: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.queryScalar(java.lang.String, java.lang.Object[])' on a null object reference
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4207)
        at android.app.ActivityThread.access$1600(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2107)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8107)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.ichi2.libanki.DB.queryScalar(java.lang.String, java.lang.Object[])' on a null object reference
        at com.ichi2.libanki.sched.SchedV2._lrnForDeck(SchedV2.java:1478)
        at com.ichi2.libanki.sched.SchedV2.deckDueList(SchedV2.java:552)
        at com.ichi2.libanki.sched.SchedV2.deckDueTree(SchedV2.java:592)
        at com.ichi2.libanki.sched.SchedV2.deckDueTree(SchedV2.java:587)
        at com.ichi2.anki.services.ReminderService.getDeckOptionDue(ReminderService.java:172)
        at com.ichi2.anki.services.ReminderService.onReceive(ReminderService.java:110)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4198)
        at android.app.ActivityThread.access$1600(ActivityThread.java:273) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2107) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8107) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 

My understanding is that the notification service started running. However, sync closed the database, which means that notification suddenly can't access the database anymore

One way to deal with it would be to try/catch the NullPointerException here and state that notification is not so important that it should crash the program. Or that sync interact with notification, to pause notification until database is reoladed

**Comment by imaryandokania** [comment] 2021-03-18 04:35
I have gone through some blogs , the receiver class need to be static https://stackoverflow.com/questions/4391974/is-it-possible-to-define-a-broadcast-receiver-as-an-inner-class-in-manifest-file/4392499#4392499

**Comment by VamsiKrishnaCommits** [comment] 2021-03-18 04:37
> I have gone through some blogs , the receiver class need to be static https://stackoverflow.com/questions/4391974/is-it-possible-to-define-a-broadcast-receiver-as-an-inner-class-in-manifest-file/4392499#4392499 
> 
> 

Don't you think it is a different use case in the blog ?

**Comment by imaryandokania** [comment] 2021-03-18 04:40
> > I have gone through some blogs , the receiver class need to be static https://stackoverflow.com/questions/4391974/is-it-possible-to-define-a-broadcast-receiver-as-an-inner-class-in-manifest-file/4392499#4392499 
> > 
> > 
> 
> Don't you think it is a different use case in the blog ?

If it is not static then it would surely give null exception when the initial sync starts. Rest I am trying some alt options.

**Comment by IAmJaishree** [comment] 2021-03-18 04:44
Based on the logs this getDb() function is returning null object

![image](https://user-images.githubusercontent.com/58835654/111574576-bedd7b00-87d2-11eb-83af-dc0e6343ca61.png)

**Comment by imaryandokania** [comment] 2021-03-18 04:47
> Based on the logs this getDb() function is returning null object
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/58835654/111574576-bedd7b00-87d2-11eb-83af-dc0e6343ca61.png)
> 
> 

But its already in try/catch🤔

**Comment by IAmJaishree** [comment] 2021-03-18 04:49
@imaryandokania it is in try catch but it is only catching SQLException and not NullPointerException which is the actual cause of this issue

**Comment by imaryandokania** [comment] 2021-03-18 04:50
> @imaryandokania it is in try catch but it is only catching SQLException and not NullPointerException which is the actual cause of this issue

Could you keep Exception e instead of SqlException and try

**Comment by VamsiKrishnaCommits** [comment] 2021-03-18 04:51
We should ask the maintainers the reason behind using sqlite exception before proceeding. I am sure there is some reason.

**Comment by IAmJaishree** [comment] 2021-03-18 04:52
that will certainly fix the error but we do need to find why this is happening and is adding the try catch is the only option or we can come up with the better approach.

**Comment by IAmJaishree** [comment] 2021-03-18 04:52
> > @imaryandokania it is in try catch but it is only catching SQLException and not NullPointerException which is the actual cause of this issue
> 
> Could you keep Exception e instead of SqlException and try .. Since it is super class will contain all

that will certainly fix the error but we do need to find why this is happening and is adding the try catch is the only option or we can come up with the better approach.

**Comment by imaryandokania** [comment] 2021-03-18 04:54
> > > @imaryandokania it is in try catch but it is only catching SQLException and not NullPointerException which is the actual cause of this issue
> 
> > 
> 
> > Could you keep Exception e instead of SqlException and try .. Since it is super class will contain all
> 
> 
> 
> that will certainly fix the error but we do need to find why this is happening and is adding the try catch is the only option or we can come up with the better approach.

I think the reason is that when sync starts the notification service is getting called even before server is providing data .  Could be possible one!

**Comment by VamsiKrishnaCommits** [comment] 2021-03-18 04:55
> that will certainly fix the error but we do need to find why this is happening and is adding the try catch is the only option or we can come up with the better approach.

Also it will only make the error disappear but what we need to is to make sure the function is running so that the sync can be performed.

**Comment by imaryandokania** [comment] 2021-03-18 04:56
> > > @imaryandokania it is in try catch but it is only catching SQLException and not NullPointerException which is the actual cause of this issue
> 
> > 
> 
> > Could you keep Exception e instead of SqlException and try .. Since it is super class will contain all
> 
> 
> 
> that will certainly fix the error but we do need to find why this is happening and is adding the try catch is the only option or we can come up with the better approach.

We can analyze by using printStackTrace()

**Comment by kartikeysaran** [comment] 2021-03-18 06:15
Would love to work on this issue if no one is working on this !

**Comment by VamsiKrishnaCommits** [comment] 2021-03-18 06:18
Already working : )

**Comment by kartikeysaran** [comment] 2021-03-18 06:23
> Already working : ) guess even you can work on it since its not assigned to anyone

It will be a waste of time only one person should work on one issue if you dont want to work on this then ill start working on this

**Comment by VamsiKrishnaCommits** [comment] 2021-03-18 06:24
I am working on it

**Comment by Arthur-Milchior** [comment] 2021-03-18 06:41
> We should ask the maintainers the reason behind using sqlite exception before proceeding. I am sure there is some reason.

Honestly, no idea. Using git blame will probably give all information you can get. Mike arrived in 2019 and David and I in 2020, we inherited most of the code and certainly don't know all logic behind it.

In any case, ti's catching, but it's also sending a RuntimeException, so that's probably not ideal either. 

> I think the reason is that when sync starts the notification service is getting called even before db is providing data . Could be possible one!

Notification call is independent of most ankidroid. It's like an alarm clock. We register that a function should be called each day at a specific hours. This function starts ankidroid in order to get the database and check whether there are review to be done today. The problem is that sync closes the database, and the notification do not check for it. 

If https://github.com/ankidroid/Anki-Android/pull/6045 eventually gets merged, then the database can be kept open (As it is now the case on computer...), but until then, this bug will occur.

**Comment by mrudultora** [comment] 2021-03-18 11:55
> > @imaryandokania it is in try catch but it is only catching SQLException and not NullPointerException which is the actual cause of this issue
> 
> Could you keep Exception e instead of SqlException and try .. Since it is super class will contain all

Generally, Exception class must not be used directly. Using separate catch blocks is preferred over the first one.

**Comment by david-allison-1** [comment] 2021-03-18 12:02
2.15 regression. 

Introduced in 5128cc2c756ce1434367eb58807650581f26c661 . Ref: #7612

https://github.com/ankidroid/Anki-Android/commit/5128cc2c756ce1434367eb58807650581f26c661#diff-eab9b1b76312c13e47b4f32c7297da450ce522c4f6d15c79e55a8a8a5c51364fR172

Pending work:

- [ ] `col.getSched().deckDueTree()` was moved outside the `try...catch`
- [ ] We should audit this change to see if any other similar bugs have been introduced.

**Comment by 2tanayk** [comment] 2021-03-18 12:52
> > @imaryandokania it is in try catch but it is only catching SQLException and not NullPointerException which is the actual cause of this issue
> 
> Could you keep Exception e instead of SqlException and try .. Since it is super class will contain all

No thats not the way, instead one must go from the specific to general,hence I think we should add catch blocks for whatever the code is susceptible to and then finally Exception e

**Comment by mikehardy** [comment] 2021-03-18 14:44
I think David nailed it with the regression, this did not used to be a problem.

Unrelated: for a real "make the feature work" fix, which I would define as "notification service does not crash and if sync starts before or during notification activity, they interact correctly", it would look something like:

- there is the ability (via an API like SomeSyncObject.isSyncInProgress()) to know if a sync is in progress, as that can change data completely and thus make any notifications based on old data obsolete
- notification service while working can periodically check that status and stop working, additionally if it hits any exception cases related to database being closed it can check that and log a message while stopping work gracefully, maybe saving a pref indicating that it was interrupted
- sync when it is done, can send an event to the notification service that says essentially "a sync was completed, notifications based on old data should be rebuilt"
- notification service, if was interrupted can generate new notifications, or if not interrupted but there are existing notifications it may update them.


None of that is related to the crash though it is more related to #4944 (I will paste this over there) - the crash is related to the exact commit David posted and should be the subject of a *very focused* fix related just to that regression

**Comment by IAmJaishree** [comment] 2021-03-20 06:56
Can I take this bug and work on it?

**Comment by david-allison-1** [comment] 2021-03-20 07:36
Sure, do note: https://github.com/ankidroid/Anki-Android/issues/8264#issuecomment-801871816

**Comment by david-allison-1** [comment] 2021-04-04 14:40
@IAmJaishree are you working on this?

**Closed** 2021-04-08 04:28 UTC
Labels: 2.15, Bug, Priority-High
