### ISSUE TITLE
ankidroid beta #12  keyboard spell corrections are conflicting with spelling note type

### ISSUE THREAD

**Issue by zecoder** [ankidroid/Anki-Android#3846] opened 2015-11-18 02:04 UTC
Hi,

I have been using  v.2.4.3 from F-Droid. Last night, however, I installed 2.5 beta 12 to see how it was all coming along. I attempted to do some studying, but immediately ran into an issue. 

The beta is showing me spelling corrections. This wholly conflicts with my "Misspelling" note type, where a TTS mp3 speaks a commonly misspelled word, to which I must type an answer and have that checked on the back. Obviously since I'm being shown the answer while typing the answer this defeats the purpose. Please revert AnkiDroid back to 2.4.3 behavior of not displaying spelling corrections while typing an answer while studying. I'm sure many others use Anki this way as well. 

Thank you.

Attached: 

![ankidroid 2 5 beta 12](https://cloud.githubusercontent.com/assets/15900066/11230618/0546cf2a-8d55-11e5-8000-a64f916548c1.png)

**Comment by ospalh** [comment] 2015-11-18 13:22
Hmm.
We do [tell the keyboards](https://github.com/ankidroid/Anki-Android/blob/develop/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L766) to not show those hints.
Some obey this hint, some don’t. For example SwiftKey is always showing corrections like that, but the plain Android keyboard doesn’t.
![screenshot_2015-11-18-11-15-10](https://cloud.githubusercontent.com/assets/1690429/11242003/5b62350c-8dff-11e5-8405-6594e7492935.png)

**Comment by zecoder** [comment] 2015-11-19 23:43
In 2.4.3 there are no spell corrections, but in the beta there is.  

Also, the keyboard I'm using is "English (US) - Android Keyboard (AOSP)", which I believe to be default. Is that not correct?

**Comment by hssm** [comment] 2015-11-19 23:55
What version of Android are you on?

**Comment by zecoder** [comment] 2015-11-20 01:21
5.0

**Comment by zecoder** [comment] 2015-11-22 02:26
A screen of 2.4.3 and the same keyboard:
![screenshot_2015-11-21-17-27-24](https://cloud.githubusercontent.com/assets/15900066/11321666/489e342c-907d-11e5-9b20-fe6294145af9.png)

**Comment by hssm** [comment] 2015-11-24 02:49
I can reproduce it on an emulator running 5.0. However, the OS version should be independent of the browser engine being used since it updates separately. Did you by any chance disable or uninstall updates to the `Android System Webview` application?

**Comment by hssm** [comment] 2015-11-24 02:50
Actually, it could be a problem with the keyboard application instead. I will try updating the webview on that same emulator and see what happens.

**Comment by zecoder** [comment] 2015-11-24 02:53
Android System Webview is not disabled and is present under the "All" tab in Apps

**Comment by zecoder** [comment] 2015-11-24 03:01
I did disable Play Store though

**Comment by hssm** [comment] 2015-11-24 03:04
If doing so stops that component (or the keyboard, since it's also a separate application) from updating then it very well could be the problem.

**Comment by zecoder** [comment] 2015-11-24 03:14
Eh, I'll see if there are any other keyboards on FDroid

**Comment by timrae** [comment] 2015-11-24 03:16
For the record could you tell us the respective version number of your AOSP keyboard and Webview first please?

**Comment by zecoder** [comment] 2015-11-24 03:18
AOSP is 5.0
Android System WebView is 37 (1602158-arm)

**Comment by hssm** [comment] 2015-11-24 03:18
It's a [Chrome bug](https://code.google.com/p/chromium/issues/detail?id=303883) and not a keyboard bug.

**Comment by timrae** [comment] 2015-11-24 03:21
Please try upgrading to the latest webview 46

**Comment by zecoder** [comment] 2015-11-24 03:30
Is there a way to do this without a Google account?

**Comment by timrae** [comment] 2015-11-24 03:32
It's open source so it must be possible but I'm not sure how or how much
work it is sorry. Please do some research and let us know

**Comment by timrae** [comment] 2015-11-24 03:34
In the worst case I guess you could just upgrade to the latest CWM, though
we don't support custom roms

**Comment by hssm** [comment] 2015-11-24 03:36
You might be able to grab the apk from [somewhere](http://www.apkmirror.com/apk/google-inc/android-system-webview/) but I have no idea if that would work.

Since this is not an AnkiDroid bug I'm closing the issue.

**Closed by hssm** 2015-11-24 03:36 UTC

**Comment by zecoder** [comment] 2015-11-24 05:09
So, I installed a newer version, and it seems to be working alright. (47.0.2526.61). Thank you for helping me resolve that. 

Some feedback:

In Anki 2.43, the input box was at the bottom of the screen, near the Answer button. One could easily just hit it with a thumb and pop open the keyboard.

Now, in beta18 I have to reach all the way up to the top of my phone to invoke the keyboard. This seems a step backward. I feel sorry for anyone using a tablet lol. Its anti-ergonomic and I felt frustrated with having to perform the much longer reach after only a few questions. I liked the way it was before.

**Comment by eginhard** [comment] 2015-11-24 09:07
You can now yourself control the position of the input field, it appears at
the position you specified in the card.

Eginhard
