### ISSUE TITLE
AnkiDroid Error 1546

### ISSUE THREAD

**Issue by aitanaa0** [ankidroid/Anki-Android#13676] opened 2023-04-23 11:23 UTC
Hello!
When I synchronize my AnkiDroid, I get the following message:
**"Collection synchronized. Error syncing media data. disk I/O error (code 1546 SQLITE_IOERR_TRUNCATE"**

This is a problem for two reasons:  
1) I **cannot add any kind of media** (no images or audio clips). If I try to, when I click add images and select one, anki shuts down and when I go back in there is no new card.
However, any cards that had images added to them previously (before the error) do work and do show the images. 
2) I tried exporting a deck to then import it into my anki again and I got this message "This isn't a valid Anki package file. File name ... **doesn't have .apkg or .colkg extension**" So my decks do not have this .apkg or .colkg extension.

I have no coding experience and although I have been using AnkiDroid for years, I have not encountered this problem before. I do not understand what the messages mean, what the .apkg and .colkg extensions are and I do not know how to fix this problem. 
I would like to be able to add images to my cards and I would like to export my decks and be able to import them back if necessary.
I am not sure if these things are linked, but I think they are because they all started at the same time. I have no other problems, everything else seems to work just fine.

**Does anyone know how I can fix this? 
Or what I have to do with this error?** 
Thank you

**Comment by david-allison** [comment] 2023-04-23 11:48
Hi, could you please post debug information, as requested from the bug template?

**Comment by aitanaa0** [comment] 2023-04-23 12:18
Hello, I do not know what you mean, it is my first time using this website.

**Comment by david-allison** [comment] 2023-04-23 12:56
When you reported the issue, you likely cleared the following line from the template:

> ###### Debug info
> Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

Could you follow the steps and provide debug info as a comment

**Comment by doozan** [comment] 2023-04-23 13:16
> When you reported the issue, you likely cleared the following line from the template:

I think this is actually an issue with Github itself: If you're not signed into an account (or, presumably, if you're a new user creating an account for the first time), clicking "New Issue" will prompt you to log-in and then take you to a completely blank new issue submission form, bypassing the issue templates. Since there's no trace of any of the template in the header or the body of this issue, I'd guess that's what's happened here.

**Comment by aitanaa0** [comment] 2023-04-23 15:27
Okay, I will make a new issue with the correct template, thank you! :)

**Comment by david-allison** [comment] 2023-04-23 15:43
Thanks! 

- Closing as duplicate of #13681

**Closed** 2023-04-23 15:43 UTC
Labels: Needs Author Reply
