### ISSUE TITLE
Interface is partially in English, partially in German

### ISSUE THREAD

**Issue by Zwergkrug** [ankidroid/Anki-Android#6219] opened 2020-05-19 11:58 UTC
###### Reproduction Steps

1. System language on smartphone: German
2. In Anki:  General settings -> Language -> choose English

###### Expected Result

Anki should only display English

###### Actual Result

Part of Anki is now displayed in English, most in German.
Preferences are now in English. Everything else is in German (menu, start page, "again/good"-options)

###### Debug info
AnkiDroid Version = 2.10.2

Android Version = 6.0

ACRA UUID = 6fd4355b-f66a-432f-9b47-3306d9b67311

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Thank you for reading!

**Comment by david-allison-1** [comment] 2020-05-19 13:42
Hi @Zwergkrug, 

Thanks for the report.

This should be fixed in #6138.

Closing this as a duplicate of #4729

You can follow the linked issues for progress updates.

Please feel free to reopen this if the above links aren't fully relevant.

Thanks for using AnkiDroid,

David

**Closed by david-allison-1** 2020-05-19 13:42 UTC

**Comment by Zwergkrug** [comment] 2020-05-19 13:51
Hi @david-allison-1 

thank you for your quick reply and thanks for linking to the earlier reports, I couldn't find them by myself.

I followed the recommendation to change my language settings on my phone to English and it's fine now.
