### ISSUE TITLE
[Feature] Add stop button for audio notes

### ISSUE THREAD

**Issue by Abanoub-Asaad** [ankidroid/Anki-Android#8771] opened 2021-05-04 17:14 UTC
**Is your feature request related to a problem? Please describe.**
When I add audio to notes, I can't stop the audio.

**Describe the solution you'd like**
I suggest creating a stop icon for solving this.

**Additional context**
If you approved the feature, I would like to work on it.

**Comment by david-allison-1** [comment] 2021-05-04 18:01
What does Anki Desktop do?

**Comment by Abanoub-Asaad** [comment] 2021-05-04 18:38
Also, there's no stop button on Anki Desktop.

**Comment by Abanoub-Asaad** [comment] 2021-05-04 18:49
On both the desktop and android app, the audio never stops unless I show the answer.

**Comment by mikehardy** [comment] 2021-05-04 20:03
A slightly more useful comparison here is AnkiMobile - it has a play/pause button for audio - this specific item is actually duplicate of #6774 - which isn't a bad thing - taking that one up would be great

**Closed by mikehardy** 2021-05-04 20:03 UTC
