### ISSUE TITLE
Keyboard should pop up for type-answer fields

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3482] opened 2015-07-28 11:02 UTC
Originally reported on Google Code with ID 2586

```
What steps will reproduce the problem?
1. I open a deck with cloze texts
2. When I come to a new card there's text field where I can insert the missing texts.
The cursor is in this text field automatically.
3. I tap on the text field and the keyboard pops up.
4. I enter the missing word.

What is the expected output? What do you see instead?
The step 4 isn't necessary and annoying because I have to tap into the text field on
every single card you want to learn. This makes me loosing time. The keyboard should
pop up right away when a new card with cloze text is shown.

Does it happen again every time you repeat the steps above? Or did it
happen only one time?
It happens every time.

I saw this problem in other Android apps before, mainly dictionaries. Over the time
all the dictionaries I used have fixed this problem. When the search field is shown
the keyboard pops up automatically. There is no need anymore to tap into the text field.
I would like Ankidroid to behave this way too. 

I don't know whether there are Ankiusers who have very long cloze texts that would
be partly hidden by the keyboard. If this is the case I would be nice to have an option
in the settings where they can change the behavior of the keyboard to the old way so
that the keyboard doesn't pop up automatically. But the automatic pop up of the keyboard
should be the default behaviour.
```

Reported by `edbe.android` on 2015-04-19 17:32:37

**Comment by david-allison-1** [comment] 2020-06-03 16:41
Good first issue, let's keep it open

**Comment by adamwolf** [comment] 2020-10-30 13:31
Would we want to only auto-open the soft keyboard with type-answer if there isn't a physical keyboard attached?

**Comment by mikehardy** [comment] 2020-10-30 13:40
Hey @adamwolf ! :-)
Seems reasonable to open the keyboard yes, it would be the first thing people want in absence of physical keyboard
I trust your judgement though (in case there is a technical barrier or you try it and it is no good for some reason)

**Comment by cjbell630** [comment] 2020-11-21 01:24
If I may also suggest something: maybe add something for when the whiteboard is enabled (ie. the user is writing on the screen), the keyboard is not automatically toggled. Or maybe an icon towards the top that appears next to the ink icon to toggle pulling up the automatic keyboard. The best way would probably just something so that this can be controlled on a per-session basis :)

(Personally, I switch between writing and typing depending on where I'm studying, so that's why I thought it might be worth mentioning)

**Comment by musiqualGeek** [comment] 2021-03-15 16:15
Is this issue still open? I would like to work on it.

**Comment by tanmayChakrawarty** [comment] 2021-03-15 16:20
Hello Sir @david-allison-1 can I work on this issue?

**Comment by mikehardy** [comment] 2021-03-15 19:41
It appears to have no activity since November so I believe it is fine to work on. @musiqualGeek asked first, so if they are still interested, they should have priority, else @tanmayChakrawarty sure

**Comment by shankarpriyank** [comment] 2021-09-07 15:14
I would like to work on this issue

**Comment by mikehardy** [comment] 2021-09-07 15:23
Same as previous statement from me - doesn't appear to be active by anyone at the moment, so have a go @shankarpriyank ! Thanks

**Comment by david-allison-1** [comment] 2021-09-08 13:20
We have a "focus type in answer" setting in the advanced preferences. Is this issue still active given this?

**Comment by shankarpriyank** [comment] 2021-09-08 14:14
Hey actually I am new to open source world so I am having a hard time figuring out the problem and the solution of this issue
But I noticed something which can be enhanced by in the app
Whenever we click on creating new deck option a small dialog box appears which tells us to type in the name of the deck and has two options cancel and ok
But even when then name field is blank the ok button works and just closes the dialog box, I think we should add a check to it and if the name field is empty the ok button should be kind of disabled..


And I picked this issue #3482 because it had a tag good first issue and I in excitement just commented here, but I have still not figured out where the issue is in the app

**Comment by mikehardy** [comment] 2021-09-08 14:22
Hey @shankarpriyank sounds like you could open a new issue with the item you reported ("Ok button on create deck dialog is functional even if deck name is empty") and that would be a separate good first issue :-). As for this one, open settings --> advanced and experiment with the toggle David mentioned to see if it already has the desired functionality working - if so we can just close this

**Comment by codingtosh** [comment] 2021-10-31 10:09
Hey @david-allison-1 , @mikehardy , I would like to take this up. 
So just to confirm, we just need to enable Focus type in answer by default right?

**Comment by david-allison-1** [comment] 2021-10-31 10:10
> Hey @david-allison-1 , @mikehardy , I would like to take this up. 
> So just to confirm, we just need to enable Focus type in answer by default right?

Yep, should be another one line fix

**Closed** 2021-10-31 16:18 UTC
Labels: Enhancement, Priority-Low, Accepted, Help Wanted, Good First Issue!, Keep Open, Reviewer
