### ISSUE TITLE
[Bug] Migrate stuck on "Migrating 5 media files"

### ISSUE THREAD

**Issue by Gravity2106** [ankidroid/Anki-Android#13212] opened 2023-02-06 21:51 UTC
###### Reproduction Steps

1. Update to 2.16alpha93
2. Tap on migrate
3. 

###### Expected Result
The migration ends and synchronization works again

###### Actual Result
Stuck on migrating media files
I have restarted the phone, closed the app. given permissions...

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16alpha93

Android Version = 10

Manufacturer = Xiaomi

Model = MI 8

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; MI 8 Build/QKQ1.190828.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.117 Mobile Safari/537.36

ACRA UUID = ca9f38bd-b679-4a6b-b2e7-1d10fdff2fe1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2023-02-07 00:35
I have also seen this and reported it in our Discord channel as this is our main area of focus+development right now and there is a lot of real-time communication on our Discord - I'm surprised it is in 2.16alpha93 though! I saw this when I was testing #13152 and didn't realize it might happen without the PR

Thanks for logging it - and @david-allison this sounds like exactly what I saw. Perhaps the collection I shared with you isn't important to reproduce, may be widespread

**Comment by criticalAY** [comment] 2023-02-07 04:28
@mikehardy This will be solved once David's PR gets merged and I pull the updates in, push the code for STOR-04 and STOR-05 as they include this part.

**Comment by homocomputeris** [comment] 2023-02-07 09:46
I have the same issuu:
```
AnkiDroid Version = 2.16alpha93

Android Version = 13

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; ONEPLUS A6003 Build/TQ1A.230105.001.A2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = d955bcd1-fd00-4663-a668-76961b1f8863

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by criticalAY** [comment] 2023-02-07 09:57
Don't worry it will be resolved very soon, it's already in progress

**Comment by mikehardy** [comment] 2023-02-07 12:55
Ah okay - then I guess accelerating that stuff is perhaps better vs delay, as this appears to happen in alpha93 already, even without David's PR (implying David's PR is likely fine, "let's go"...) will see about getting that merged shortly, thanks

**Comment by doozan** [comment] 2023-02-07 21:59
I'm seeing this too. @criticalAY since you seem to understand what's going on here can you clarify what's happening? Is the migration complete? Is it still in progress? Is it safe to reviewing cards in this state, or is the collection now broken in some way? Assuming those PRs land quickly and alpha94 comes out soon, what happens to collections with unsynced reviews?

For now I'm going to install one of the parallel builds and pull a fresh collection from ankiweb so I can continue studying without worrying I'm going to lose data but I'm happy to keep this installation around to do any testing that might be needed.

**Comment by Juddd** [comment] 2023-02-08 02:43
I've been suffering from this problem all day

**Comment by criticalAY** [comment] 2023-02-08 03:27
If you are a new user then you are already redirected to scoped storage but if you were a existing one then you haven't been migrated as the PR that contains the migration code was merged yesterday to address the issue and it's not a unknown bug as things are being executed in a particular sequence considering the time we have as we all are volunteers here but don't worry you will get these things fixed in alpha94

**Comment by Juddd** [comment] 2023-02-08 04:20
After I migrate the all files from `Internal shared storage/AnkiDroid` into `Internal shared storage/Android/data/com.ichi2.anki/files/AnkiDroid1` by USB method, I get this error information:
![4d0c33ab37b06e03ca050aad5f3f671](https://user-images.githubusercontent.com/10048069/217432610-62a08aea-4821-4e28-abde-843ef79086ce.jpg)

If I don't want to wait for alpha94. What should I do to fix this problem?

**Comment by david-allison** [comment] 2023-02-15 20:29
I've had a couple of attempts at reproducing this and have been unable to, as of yet.

If anyone has a logcat of the issue, it would be greatly appreciated.

**Comment by doozan** [comment] 2023-02-15 21:28
I used advanced setting to change the data directory from the "new" destination (/storage/emulated/0/Android/data/com.ichi2.anki.b/files/AnkiDroid1) to the original path (/storage/emulated/0/Android/data/com.ichi2.anki.b/col). Then I killed the app and moved renamed /storage/emulated/0/Android/data/com.ichi2.anki.b/files to /storage/emulated/0/Android/data/com.ichi2.anki.b/files.old hoping it would prompt me to re-do the migration when I restarted anki, but it didn't show the icon on the sync button or otherwise prompt me to migrate. If I try to sync, even with the "old" path, I still get the same "Migrating 5 media files" warning. Is there an "already_migrated" flag someplace that I can reset to try running the migration again to capture a logcat?

**Comment by david-allison** [comment] 2023-02-15 22:16
Copy files back to `storage/emulated/0/AnkiDroid`, change the deck path here and the migration should be prompted

**Comment by doozan** [comment] 2023-02-15 22:32
Pointing it back to `/storage/emulated/0/AnkiDroid` shows the old collection but does not prompt me to migrate. Clicking sync still gives the message "Sync is disabled until the migration is done. 5 media files left to migrate"

**Comment by snowtimeglass** [comment] 2023-03-01 10:03
I saw the message of `5 media files left to migrate.` constantly when I pressed the sync icon during the migration. In my case, the migration itself didn't stuck. It was completed.

<img src="https://user-images.githubusercontent.com/10436072/222084814-4ff63c3a-fce3-459d-a046-8d04b6b3b5a6.png" width="320px">


```
AnkiDroid Version = 2.16alpha94

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = 1a83f190-7132-4cb5-ad86-adf382a79e4c

New schema = true

Scheduler = std2 *

Crash Reports Enabled = true

DatabaseV2 Enabled = true *

```
\* Sorry, these two items are uncertain because I may have tinkered with these settings after the migration and before getting this debug info.

**Comment by criticalAY** [comment] 2023-03-01 10:07
@snowtimeglass you are on alpha94 so it is fixed but this issue was raised when we were on alpha93. @mikehardy This is resolved now as we have merged the code for migration (needs to be worked upon though) so this issue can be marked as resolved and can be closed now.

**Comment by criticalAY** [comment] 2023-03-01 10:09
Well still see this dialog but with the amount of data to transfer and the progress dialog is blocked by state flow replacement in migration. Hopefully we will see a proper dialog in alpha95

**Comment by snowtimeglass** [comment] 2023-03-01 10:50
@criticalAY thank you for the prompt advice. I understand.

**Comment by BrayanDSO** [comment] 2023-04-19 11:13
String got unused with one of the last PRs

**Closed by BrayanDSO** 2023-04-19 11:13 UTC
Labels: Priority-High, Scoped storage
