### ISSUE TITLE
Text not appearing

### ISSUE THREAD

**Issue by terrywallwork** [ankidroid/Anki-Android#8153] opened 2021-03-09 06:49 UTC
Debug info:

AnkiDroid Version = 2.14.5

Android Version = 8.0.0

ACRA UUID = 8c4ae41a-d8ac-41bd-ba77-8ac55aec197c

Scheduler = std

Crash Reports Enabled = true

I open ankidroid, and go to a deck to review.  When it's displayed there is no text, just the show answer button and on the answer side just the buttons.

Note: Deck worked perfectly before most recent upgrade. Activating Safe Display mode made no difference.  Downgrading to 2.14.3 resolved issue.

Screenshots:
![Screenshot_20210309-063954](https://user-images.githubusercontent.com/19387982/110429780-54765d80-80a3-11eb-9ef7-4e98d89978c8.png)
![Screenshot_20210309-064007](https://user-images.githubusercontent.com/19387982/110429782-550ef400-80a3-11eb-8ce4-14ab54555d24.png)

**Comment by terrywallwork** [comment] 2021-03-09 10:30
Here is my collection for you to test, the Kanji Deck or JLPT decks all have the issue, See JLPT 5 deck.

[collection-20210309070102.zip](https://github.com/ankidroid/Anki-Android/files/6107806/collection-20210309070102.zip)

**Comment by mikehardy** [comment] 2021-03-09 14:50
Hi there!
Most recent upgrade from what to what?
I wonder if your font is referenced somehow over a non-HTTPS network connection vs being embedded correctly per https://docs.ankidroid.org/#customFonts ?

**Comment by mikehardy** [comment] 2021-03-09 14:50
also, note you may always revert while waiting for attention - all the primary contributors are pretty busy right now so there is no guarantee of response, apologies: https://github.com/ankidroid/Anki-Android/wiki/FAQ#i-dont-like-the-last-update-of-ankidroid-how-can-i-return-to-a-previous-version

**Comment by terrywallwork** [comment] 2021-03-09 19:47
The previous version that worked was 2,14.3 from.2.14.5 Anki droid.

I did revert to 2.14.3 in the meantime until this gets fixed got the apk from apk pure.

**Comment by terrywallwork** [comment] 2021-03-09 19:49
> Hi there!
> Most recent upgrade from what to what?
> I wonder if your font is referenced somehow over a non-HTTPS network connection vs being embedded correctly per https://docs.ankidroid.org/#customFonts ?

Font im using is local android system font.  Adding a custom font to the anki font directory made no difference.

**Comment by mikehardy** [comment] 2021-03-09 20:11
Okay - you are on Android 8, and this is a reviewer rendering problem - I think it is triggered by my attempts to fix #7369 in #8144 (which did not work)

I'm going to resolve this as a duplicate of that one but please subscribe to that issue as I'm about to post another "test fix" parallel/side-by-side build that might fix this issue.

My hunch at this point is that something changed with the hardware rendering of WebViews on Android 8/8.1 only and it's causing an incompatibility here. I know for certain a) we changed nothing in the area and b) it does not show up on android emulators so I can't reproduce it unfortunately but that gives me the hardware render hunch.

Head over to #7369 and hopefully the test build in a few minutes will have a positive result :crossed_fingers:

**Closed by mikehardy** 2021-03-09 20:11 UTC
Labels: Help Wanted, Needs Triage

**Comment by dotancohen** [comment] 2021-03-09 21:02
I can confirm this issue on Android 10 on a Xiaomi Redmi Note 9. We have tried both night and day mode, and we've tried burying cards but the next card displays the same issue. Video displaying the issue: https://imgur.com/GcYcOX5

Tomorrow I'll have her try the workaround suggested in #7369.

**Comment by Paddel06** [comment] 2021-03-09 21:27
> 
> 
> @dotancohen I have a test build with I think a fix available already, can install a parallel build side-by-side for quick test: https://github.com/mikehardy/Anki-Android/releases/tag/v2.14.5-issue7369-2
> 
> It seems to have fixed the original Android 8 problem with one confirmation and I'm polishing it for a release of 2.14.6 right now but would love feedback

Just tested parallel B and the issue seems to be gone now.
I am on Oneplus 5T with Android 10.

**Comment by mikehardy** [comment] 2021-03-09 21:38
@Paddel06 fantastic - really sorry for the bother. I'll be releasing a 2.14.6 that fixes this regression for everyone and I think (finally!?) has a fix for the poor Android 8 souls who have had a broken reviewer for a couple months now.

**Comment by badchute** [comment] 2021-06-04 11:54
I'm on android 10 and i have this issue. it started this morning, i tried installing this https://github.com/mikehardy/Anki-Android/releases/tag/v2.14.5-issue7369-2 but it doesn't work.

**Comment by mikehardy** [comment] 2021-06-04 13:17
@badchute seems like you may have something unrelated and/or new. In the 2.15.x series there is a way to toggle hardware render off or on in the settings --> advanced area. You may attempt to toggle it off then report back?

**Comment by badchute** [comment] 2021-06-04 13:21
i tried toggling it on and off and it still doesn't work

**Comment by mikehardy** [comment] 2021-06-04 14:29
Interesting @badchute - sorry to hear that. If you also try 2.14.5 and neither it nor the hardware/software render toggle work my next hypothesis is that you probably have a content problem in your cards. I would try to download some super simple shared deck from ankiweb to see if it works, as it should have known-good card templates / card content. Or you could also try opening your collection / the deck you have problems with on ankiweb and anki desktop to see if they have similar problems. This does not seem related to the hardware/software render issue we were having though, so if this continues for you and definitely works on other platforms and/or with known-good decks please open a new issue so we may focus on it

**Comment by badchute** [comment] 2021-06-04 14:36
i also notice that the statistics overview is blank
