### ISSUE TITLE
Bug: The reminders in the deck options don't work on time 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4525] opened 2017-01-04 12:51 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Set a reminder at "Reminders" in the deck options.

###### Expected Result

The notification is displayed on time

###### Actual Result

The notification is displayed several minutes (7 or more minutes) late.
![image](https://cloud.githubusercontent.com/assets/10436072/21642624/eafcc4b8-d2c6-11e6-8981-8c128c5e2aee.png)

###### 

ver: 2.8alpha5

**Comment by madhead** [comment] 2017-01-18 13:31
Not sure why this happens, maybe because `setInexactRepeating()` is used for notifications. As it is guessable from its name, it does not guarantee exact time to save the battery.

**Comment by timrae** [comment] 2017-01-26 04:27
According to the API documentation for `setInexactRepeating()`:

> long: time in milliseconds that the alarm should first go off, using the appropriate clock (depending on the alarm type). This is inexact: the alarm will not fire before this time, but there may be a delay of almost an entire alarm interval before the first invocation of the alarm.

**Comment by timrae** [comment] 2017-01-26 04:47
In this case, the interval is one day, so we basically can't expect the time to be obeyed at all.

Let's add a string to the checkbox summary field saying something like: `Notification time is inexact to save battery`

**Comment by snowtimeglass** [comment] 2017-01-26 14:33
Isn't there really a more suitable measure for reminder notifications, instead of the `setInexactRepeating()`?
On my device, the reminder notifications of all other apps work punctually as a matter of course.
Why does AnkiDroid have to be left behind  all alone?

**Comment by timrae** [comment] 2017-01-26 14:44
Which apps?

**Comment by snowtimeglass** [comment] 2017-01-26 15:56
For example, 

[GoalTracker](https://play.google.com/store/apps/details?id=com.galaxy.app.goaltracker)
![image](https://cloud.githubusercontent.com/assets/10436072/22338266/4fcab0a2-e42a-11e6-8a33-eabbbcbfe9b6.png)

[HabitHub](https://play.google.com/store/apps/details?id=com.rstudioz.habits)
![image](https://cloud.githubusercontent.com/assets/10436072/22338054/c56ffdae-e429-11e6-81a6-0d0e3c48ff44.png)

[Evernote](https://play.google.com/store/apps/details?id=com.evernote)
![image](https://cloud.githubusercontent.com/assets/10436072/22338127/eca391c4-e429-11e6-9500-54c40dbe3a6b.png)

**Comment by timrae** [comment] 2017-01-28 04:11
@snowtimeglass 
Thank you for that.

I checked the API documentation, and it looks like we can customize the amount of error we're willing to accept on Android 4.4+, so maybe we could use this function with an error window of 30s:

https://developer.android.com/reference/android/app/AlarmManager.html#setWindow(int, long, long, android.app.PendingIntent)

The documentation also says:

>  If your application needs precise delivery times then it must use one-time exact alarms, rescheduling each time

We can add a `setWindow()` function to the compat classes which falls back on `set()` on older Android versions.

**Comment by timrae** [comment] 2017-01-28 04:21
I think we have two choices here... We can either pull the feature from the release to allow more time for beta testing, or we can clearly label it as being an "experimental" feature.

@madhead 
Which do you prefer, and when do you think you could find time to implement a fix for this issue and #4546?

**Comment by madhead** [comment] 2017-01-28 21:07
Let's mark it as experimental?

**Comment by timrae** [comment] 2017-01-29 22:10
@madhead
When would you expect to address the issues I mentioned though?

**Comment by madhead** [comment] 2017-01-30 22:21
Not sure, pretty busy now.

**Comment by timrae** [comment] 2017-01-31 01:11
Hmmm OK in this case I think it's better for us to pull the feature from the current release, as I also don't have time to maintain it and I don't want to keep it "experimental" for an extended period of time.

**Comment by timrae** [comment] 2017-09-12 18:35
Why did you close it? Please provide explanation when closing issues.

**Comment by snowtimeglass** [comment] 2017-09-13 12:28
I read [this comment](https://github.com/ankidroid/Anki-Android/pull/4697#issuecomment-328711942), and thought the developers regard this as a excessive demand, a nuisance.

**Comment by timrae** [comment] 2017-09-13 13:48
The comment wasn't directed at you... Reporting problems during alpha/beta period is actually very useful and important. The problem is the flood of people who start complaining after we go live with a new version, so I feel it's better to fix it now to prevent that.

**Comment by snowtimeglass** [comment] 2017-09-15 13:29
Thanks. I hope so too.

**Comment by mikehardy** [comment] 2018-02-22 20:59
If I'm reading this correctly, the proposed change is to stop using setInexactRepeating (which handles recurrence automatically), and instead use setWindow (with a window of, say 30s) then any time the notification fires and we chain through NotificationReceiver to NotificationService, we should add logic to implement the recurrence by having NotificationService use BootService to call setWindow fresh for the next day?

As a simplifying proposal - why not let the OS handle the battery optimization and use the middle-ground API that handles recurrence, "set()"? (vs setExact() - a no-no unless you are an alarm clock - and setInexact() which isn't accurate enough and generated this issue). 

Support for the idea: The documentation indicates that set() will allow Android system to be a little inexact and optimize battery for alarms automatically after API 19 (4.4 KitKat / API 19), while remaining exact for devices <19. While we will support 4.0 Ice Cream / API 15 with the next release, that's a cost of 6.7% of the user base (c.f. Android Developer Dashboard) that may see degraded battery usage with a once-daily wakeup, with the benefit of not having to handle recurrence internally. Seems like an easy win to me?

**Comment by timrae** [comment] 2018-02-23 01:09
Sounds good to me

**Comment by mikehardy** [comment] 2018-03-09 17:02
@timrae I haven't noticed any problems with this since the commit, this likely may be closed?

**Closed** 2018-03-10 15:09 UTC
Labels: Priority-Medium, accepted, advanced-reminders
