### ISSUE TITLE
[Bug]: Background Images' Toggle Button Doesn't Work

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#15357] opened 2024-01-28 13:18 UTC
###### Reproduction Steps

1. Go to Settings > Appearances > Background Image.
2. Press toggle button.

###### Expected Result
The media files should be shown 

###### Actual Result
It shows the media files for selection only when you press on the left side i.e, on the text saying "Background Image" itself. Otherwise not.

###### Debug info

AnkiDroid Version = 2.17alpha17 (866369337a2ee1838b2075a401029c11b0fc33e9)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.230 Mobile Safari/537.36

ACRA UUID = dce906d5-19f7-4514-a0e4-0071f4f7b489

Crash Reports Enabled = true

###### Research

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment] 2024-01-28 14:30
Duplicate of #15036

**Closed** 2024-01-28 14:37 UTC
