### ISSUE TITLE
One suggested feature: When in the "Preview" interface, add a button in the top right corner，can directly Edit this Note and jump to the “edit note” page for this card

### ISSUE THREAD

**Issue by freemedom** [ankidroid/Anki-Android#6664] opened 2020-07-12 06:09 UTC
![111](https://user-images.githubusercontent.com/57294686/87240111-350e2e80-c449-11ea-8936-a001f8880587.jpg)

**Comment by freemedom** [comment] 2020-07-19 12:47
With this feature, many images for the content of the card can be more convenient changed，when in the "Preview" interface.

Because android app doesn't have two columns,upper and lower columns in the card Browser like the computer .

**Comment by freemedom** [comment] 2020-07-22 15:11
When preview several cards in sequence in the card browser, I always can't find which card corresponds to the previewing image.When I found a problem with this card when preview, I can't edit it directly

**Comment by freemedom** [comment] 2020-07-22 16:31
https://github.com/ankidroid/Anki-Android/issues/6148 
seems similar

**Comment by david-allison-1** [comment] 2020-09-15 16:59
Duplicate of (and fixed in) #7026

**Closed by david-allison-1** 2020-09-15 16:59 UTC
Labels: Enhancement, Previewer
