### ISSUE TITLE
Backup options need updating

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#14366] opened 2023-09-01 06:17 UTC
Currently when visiting the preferences>advanced screen, you can only choose a single number for backups, which is not how the backend code works. There are separate settings for weeks/months, which appear to have already been implemented in BackupsLimitPresenter(), and need to be hooked up.

**Comment by pratyaksh1610** [comment] 2023-09-01 07:16
Can i work on it ?

**Comment by dae** [comment] 2023-09-01 07:20
As a general rule, you can work on anything without permission if someone else has not already said they're working on it.

**Comment by pratyaksh1610** [comment] 2023-09-01 07:21
In this we need to remove max backups and add the weekly/monthly/daily backups .

**Comment by pavreh** [comment] 2023-09-01 20:36
Duplicate of #13121

**Comment by lukstbit** [comment] 2023-09-25 04:57
@pratyaksh1610 Are you still working on this?

**Closed** 2023-10-20 12:56 UTC
Labels: 2.17-alpha
