### ISSUE TITLE
Settings: Delete individual search history

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#14988] opened 2023-12-15 07:34 UTC
**Is your feature request related to a problem? Please describe.**
Currently, we can delete all search history at once. There is no option to delete a particular search history individually

**Describe the solution you'd like**
Show a dialog box on clicking on a particular search history where user can delete it individually

**Comment by SanjaySargam** [comment] 2023-12-15 07:35
Working on it

**Comment by david-allison** [comment] 2023-12-15 07:37
Regression in 2.17, this worked by pressing the "-" in 2.16

**Comment by david-allison** [comment] 2023-12-15 07:42
Relevant code

https://github.com/ankidroid/Anki-Android/blob/49dc7bdfac924756a1e31421ed297888a2612c66/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt#L307-L315

**Comment by SanjaySargam** [comment] 2023-12-15 07:58
@david-allison I'm talking about search history in Setting Screen

**Comment by SanjaySargam** [comment] 2023-12-15 08:02
I understand the above one is also a valid issue

Should I create a new issue for search history in setting screen

**Comment by david-allison** [comment] 2023-12-15 08:04
Ah! You caught a bug anyway, well done!

Best to run this by @BrayanDSO before implementation, since they set the current direction of `Settings` and likely have plans for where it should go in the future

**Comment by SanjaySargam** [comment] 2023-12-15 11:56
@BrayanDSO 
https://github.com/ByteHamster/SearchPreference
You mean I have to make PR in this repo right?

**Comment by BrayanDSO** [comment] 2023-12-15 22:29
Right

**Comment by ByteHamster** [comment] 2023-12-17 11:14
Is this really something users would need? What would be use-cases of this? I can totally see how deleting individual history items makes sense for a web browser, but for searching settings...?

To me, this feels like adding features just for the sake of adding them. More like a programming exercise than an actual useful feature that people need. While the additional code complexity isn't too much, it's still additional complexity (translations, testing, etc). The increase in apk size is probably kind of small as well (mainly just translations), but these things add up.

I'm not yet really convinced yet why this is actually something users need. But I'm open to be convinced otherwise.

**Comment by BrayanDSO** [comment] 2023-12-17 13:11
Good point. Agreed. I'm gonna close this issue to focus on more relevant things.

Thanks for the reply, @ByteHamster

**Closed by BrayanDSO** 2023-12-17 13:11 UTC
Labels: Enhancement, Accepted
