### ISSUE TITLE
Crash when clicking on deck options

### ISSUE THREAD

**Issue by benstox** [ankidroid/Anki-Android#6089] opened 2020-04-29 08:29 UTC
###### Reproduction Steps

1. Press and hold on a deck.
2. Click on "Options"

###### Expected Result

Should go to the options menu for that deck. I have a couple of decks that do not exhibit this behaviour and they are in the same options group.

###### Actual Result

The program crashes.

###### Debug info

AnkiDroid Version = 2.9.6
Android Version = 6.0.1
ACRA UUID = 2715152f-1201-4c3b-882e-8b2535d4be30

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment] 2020-04-29 08:36
Hi @benstox,

Thanks for the report!

There aren't any crashes under that UUID. Ref: https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser/user/2715152f-1201-4c3b-882e-8b2535d4be30

If you could turn crash reporting on, then we'd have a better idea about what's going wrong (`Settings - AnkiDroid - Error Reporting Mode`).

----

It'd be ideal for you to share your collection (without media or scheduling information) so we can quickly get to the bottom of this. It's totally optional in case you have any data that you consider confidential, but would be useful.

If you're comfortable with this, could you export your collection and either:

* Send it privately via email to gmail: davidallisongithub
* Upload it to a shared file service (Dropbox/Google Drive etc..) and post a link to it in the issue.

Thanks again for the report, it really helps to make AnkiDroid better for everyone.

**Comment by david-allison-1** [comment] 2020-04-29 09:57
Got collection via email. Crashes on 2.10alpha71. Similar to, if not duplicate of #6068.
```
2020-04-29 10:27:09.082 16752-16752/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 16752
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckOptions}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.ListPreference.setEntries(java.lang.CharSequence[])' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.ListPreference.setEntries(java.lang.CharSequence[])' on a null object reference
        at com.ichi2.anki.DeckOptions.buildLists(DeckOptions.java:789)
        at com.ichi2.anki.DeckOptions$DeckPreferenceHack$Editor.commit(DeckOptions.java:443)
        at com.ichi2.anki.DeckOptions$DeckPreferenceHack$Editor.apply(DeckOptions.java:499)
        at android.preference.PreferenceManager.setNoCommit(PreferenceManager.java:706)
        at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:328)
        at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1549)
        at com.ichi2.anki.DeckOptions.onCreate(DeckOptions.java:648)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
```

----

Cause:

This line returns `null`

https://github.com/ankidroid/Anki-Android/blob/d6c9f9415b4fc5c7d2ea73b17001e27e1ea8e8c7/AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java#L779
Cause:

Swallowed exception: 

https://github.com/ankidroid/Anki-Android/blob/d6c9f9415b4fc5c7d2ea73b17001e27e1ea8e8c7/AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java#L154-L156

`finish()` does not stop `onCreate()`

Exception:

```
com.ichi2.utils.JSONException: org.json.JSONException: Value false at timer of type java.lang.Boolean cannot be converted to int
```

JSON Config:
```
{"id":1568615369480,"mod":1588149381,"name":"Train 1 new","usn":4659,"maxTaken":60,"autoplay":true,"timer":false,"replayq":true,"new":{"bury":true,"delays":[1.0,10.0],"initialFactor":2500,"ints":[1,4,7],"order":1,"perDay":1,"separate":true},"rev":{"bury":true,"ease4":1.3,"ivlFct":1.0,"maxIvl":36500,"perDay":100,"hardFactor":1.2,"fuzz":0.05,"minSpace":1},"lapse":{"delays":[10.0],"leechAction":0,"leechFails":8,"minInt":1,"mult":0.0},"dyn":false}
```

This looks like an upstream config regression, confounded by a bug in our code.

**Comment by david-allison-1** [comment] 2020-04-29 09:57
@benstox which version of Anki Desktop are you using?

**Comment by benstox** [comment] 2020-04-29 09:59
> @benstox which version of Anki Desktop are you using?

Version 2.1.24 (359b9f5c)
Python 3.8.0 Qt 5.13.1 PyQt 5.14.1

Thanks

**Comment by david-allison-1** [comment] 2020-04-29 10:15
@dae

Confirmed. Regression in Anki 2.1.24. 

Schema change on dconf:

* `timer`: `int` -> `bool`

I think delays have also been modified from int -> double, but I don't see any crashes from this.

**Comment by mikehardy** [comment] 2020-04-29 14:46
I think you should obsolete #6068 with this one since you're working in the area anyway, stacks will change and otherwise #6068 will just sit in the list stale

How did AnkiDesktop handle the conversion, or does Python just make it transparent via coercion? If Python makes it transparent, perhaps the real fix is to tolerate either a true/false or 1/0 value in there and not worry about conversion/fixIntegrity at all?

**Comment by david-allison-1** [comment] 2020-04-29 15:05
> I think you should obsolete #6068 with this one since you're working in the area anyway, stacks will change and otherwise #6068 will just sit in the list stale 

Agreed.

> How did AnkiDesktop handle the conversion, or does Python just make it transparent via coercion? If Python makes it transparent, perhaps the real fix is to tolerate either a true/false or 1/0 value in there and not worry about conversion/fixIntegrity at all?

I presume the next step will be to ensure the schemas are consistent (so users of AnkiDroid who can't upgrade will be able to edit options).

If we do that, then it makes more sense to me to treat an invalid value as an error case, rather than working around it in normal operation. (I'm not a fan of the robustness principle in this instance, as it eeks towards allowing a client to break backwards compatibility).

We're in the design phase, and I'd be interested in knowing your thoughts and how it was handled in the past. None of the above is set in stone, and it's possible to handle the case fairly easily.

**Comment by mikehardy** [comment] 2020-04-29 15:21
> > How did AnkiDesktop handle the conversion, or does Python just make it transparent via coercion? 

I don't feel like this was answered?

> I presume the next step will be to ensure the schemas are consistent (so users of AnkiDroid who can't upgrade will be able to edit options).

Definitely - if the schema's moving we need to move

> If we do that, then it makes more sense to me to treat an invalid value as an error case, rather than working around it in normal operation. (I'm not a fan of the robustness principle in this instance, as it eeks towards allowing a client to break backwards compatibility).
> 
> We're in the design phase, and I'd be interested in knowing your thoughts and how it was handled in the past. None of the above is set in stone, and it's possible to handle the case fairly easily.

I want to know more about the first two points first - but I can say I'm not sure how/if we have had to handle this before...

**Comment by david-allison-1** [comment] 2020-04-29 15:23
> I don't feel like this was answered?

Whoops - 

```rust
    #[serde(deserialize_with = "deserialize_bool_from_anything")]
    timer: bool,
```

https://github.com/ankitects/anki/blob/913c26870529174b50f4207397ede7444a48dc6e/rslib/src/deckconf.rs#L32

**Comment by mikehardy** [comment] 2020-04-29 15:45
Hmm. So, I'm guessing in Rust, deserialize_bool_from_anything coerces the types auto-magically and but when it persists it is true/false every time? If so I think we should be robust as we'll be seeing pre-rust 1/0 and post-rust true/false for some time I'm sure. If not, then I would assume they have some sort of fixIntegrity analog that did the conversion and we should follow style with the associated fixIntegrity PR here

**Comment by dae** [comment] 2020-04-29 21:22
Sorry, I'll revert the code to writing an int in a bugfix update. Both Anki and AnkiMobile coerce the int into a bool, so I thought this was safe when I prototyped this a few months ago, and I didn't connect the recent dyn issue with this one.

**Comment by mikehardy** [comment] 2020-04-30 13:55
@dae @david-allison-1 it is a steady influx of commentary on our Play Store reviews about options-related crashes. It's coming in it at a rate that my experience tells me makes this basically my highest priority as a user-facing issue.

What's the plan here for resolution so I can track this into a 2.9.7 update of AnkiDroid and we can get something out?

My take on it is that we have collections out there with 1/0 & true/false already, there's no stopping that now. It's easier to reason about things when there's one style that *should* be in the database but I think everyone in the ecosystem now needs to recognize both as valid, and that's the immediate fix.

If that's a valid stance, then the "fix" (for AnkiDroid) is to alter our options processing to fetch all booleans in a way that recognizes both.

Thoughts?

**Comment by mikehardy** [comment] 2020-04-30 15:38
w.r.t. input "be liberal in what you accept" is rarely the wrong strategy, thank you for this! 🏆

**Closed** 2020-04-30 19:44 UTC
Labels: Bug, Reproduced, upstream-issue
