### ISSUE TITLE
Add a TTS tag or attribute on CARD to play via a specific section of text via Text-To-speak

### ISSUE THREAD

**Issue by madnik7** [ankidroid/Anki-Android#3784] opened 2015-10-28 12:53 UTC
Hi

For the last year I have created a big and rich collection of cloze deletion English card and I have studied them on my Android phone. I generally use **IVONA** as my TTS engine, but the only problem I have is that I need to install a **clipboard monitoring** software and select the part of the text by my finger on each card that contains sentences I want to hear and press copy to hear them. It is a time consuming and boring, but I need to do it always.

The current “Text to Speech” option of AnkiDroid is inadequate and useless for me, I don’t need to read all of the card because it contains **Title**, **Phonetic**, **Cloze deletion**, some **extra notes** such as sources, **part of speech** and so on, which I don’t want to be read out.

So, I would be grateful if you add a feature such as a **tag** or **custom attribute** on CARD's html so only that specific section of card would be played via Text-To-Speech engine such as < div tts-read=”true”  >.

**Comment by timrae** [comment] 2015-10-28 12:55
Duplicate of #1463

**Closed by timrae** 2015-10-28 12:55 UTC
Labels: duplicate

**Comment by timrae** [comment] 2015-10-28 12:58
BTW, an alternative solution instead of waiting for someone to implement this feature is for you to just do a bulk generation of media files via TTS on Anki Desktop
