### ISSUE TITLE
[Bug] UnsatisfiedLinkError: rsdroid1801181558290891185.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by Arnold2381** [ankidroid/Anki-Android#8482] opened 2021-04-05 14:16 UTC
###### Reproduction Steps

1.  Running test extending Roboelectric test
Reference 
https://github.com/david-allison-1/Anki-Android-Backend/issues/46
2. I have the dll file in my temp folder.
###### Expected Result
Test must pass

###### Actual Result
java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Piyush Goel\AppData\Local\Temp\rsdroid1801181558290891185.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1946)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1828)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.Runtime.load(Runtime.java:798)
	at net.ankiweb.rsdroid.testing.RustBackendLoader.loadPath(RustBackendLoader.java:100)
	at net.ankiweb.rsdroid.testing.RustBackendLoader.load(RustBackendLoader.java:95)
	at net.ankiweb.rsdroid.testing.RustBackendLoader.init(RustBackendLoader.java:49)
	at com.ichi2.anki.RobolectricTest.setUp(RobolectricTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	... 6 more

Process finished with exit code -1

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by mrudultora** [comment] 2021-04-05 14:18
This might help [http://robolectric.org/blog/2019/06/04/paused-looper/](http://robolectric.org/blog/2019/06/04/paused-looper/)

**Comment by david-allison-1** [comment] 2021-04-05 14:31
This is due to a `dll` failing to load

@Arnold2381 Could you post the full exception log, the `cause` is the most important part

Somewhere before the crash, could you set: `RustBackendLoader.PRINT_DEBUG = true;`, this should list your OS in the test output.

: `loading rsdroid-testing for: [os]`

This will likely need some diagnosis on your side, I'm not sure what's going on here

This comment may be useful in diagnosing which DLLs are missing: https://github.com/david-allison-1/Anki-Android-Backend/issues/46#issuecomment-808697017

* My first suggestion would be for you to install the [Microsoft C++ Build Tools](https://docs.microsoft.com/en-us/windows/dev-environment/rust/setup. I'm doubtful that this will help, but it clears out a possibility.

**Comment by david-allison-1** [comment] 2021-04-05 14:38
@Arnold2381 

Actually... first stage:

Could you save the following as a file: `checkrsdroid.ps1`, open up a PowerShell prompt in the folder and run `.\checkrsdroid.ps1`

```
(get-command ole32.dll).Path
(get-command SHELL32.dll).Path
(get-command ADVAPI32.dll).Path
(get-command libgcc_s_seh-1.dll).Path
(get-command KERNEL32.dll).Path
(get-command msvcrt.dll).Path
(get-command USERENV.dll).Path
(get-command WS2_32.dll).Path
```

**Comment by Arnold2381** [comment] 2021-04-05 15:05
My first suggestion would be for you to install the [Microsoft C++ Build Tools](https://docs.microsoft.com/en-us/windows/dev-environment/rust/setup. I'm doubtful that this will help, but it clears out a possibility.
@david-allison-1 I tried this didn't work. 
Will try next the suggestion

**Comment by david-allison-1** [comment] 2021-04-05 23:35
I've had a shot at fixing this and failed. 

@mikehardy

**Comment by mikehardy** [comment] 2021-04-06 00:36
Mmm I'll give it a shot I have some time tomorrow morning. Installing gcc isn't the worst as it's such an old (that is well understood and distributed) and package management even on windows is so much better with chocolatey etc. But there's usually a workaround or maybe just one dll or something.

Is this all platforms or just windows?

**Comment by mrudultora** [comment] 2021-04-06 02:24
I have gcc already installed but still getting the error. Using windows 10 rn.

**Comment by PANG-hans** [comment] 2021-04-24 12:18
I met this error, too. But in the path it mentioned i can find required `.dll` file. The same project run on another PC pass all test cases.

**Comment by david-allison-1** [comment] 2021-04-24 13:00
Does moving this dll to somewhere on the PATH fix it? [libgcc_s_seh-1.zip](https://github.com/ankidroid/Anki-Android/files/6369628/libgcc_s_seh-1.zip)

**Comment by PANG-hans** [comment] 2021-04-24 13:24
> Does moving this dll to somewhere on the PATH fix it? [libgcc_s_seh-1.zip](https://github.com/ankidroid/Anki-Android/files/6369628/libgcc_s_seh-1.zip) (sorry about this, I hate distributing unknown binaries)

Thanks, it works for some unit test file, but some still not works... 😢

**Comment by david-allison-1** [comment] 2021-04-24 13:45
> > Does moving this dll to somewhere on the PATH fix it? [libgcc_s_seh-1.zip](https://github.com/ankidroid/Anki-Android/files/6369628/libgcc_s_seh-1.zip) (sorry about this, I hate distributing unknown binaries)
> 
> Thanks, it works for some unit test file, but some still not works... 😢

That's strange, it should be all or nothing, which files fail and what's the error?

**Comment by Starkly** [comment] 2021-06-26 16:55
Just to note, libgcc_s_seh-1.dll has a dependency on libwinpthread-1.dll

if both are in your PATH, then the library will load and the tests should run ok, without installing all of gcc

**Comment by NinoDLC** [comment] 2021-07-14 12:33
I'm curious (and facing the same problem... currently downloading 6 Go with Visual Studio Installer only to get a .dll...), why do we need some .dll to run Android Tests ?

**Comment by NinoDLC** [comment] 2021-07-14 13:01
After putting `libgcc_s_seh-1.dll` (76Ko) and `libwinpthread-1.dll` (65Ko) in a folder inside my PATH, rebooting computer, and launching `./gradlew jacocoTestReport`, it still doesn't work. 

Error is : 
`java.lang.UnsatisfiedLinkError: C:\Users\Nino\AppData\Local\Temp\rsdroid3735626077991595567.dll: is not a valid win32 application`

Some Espresso tests ran correctly. But as usual, Robolectric is having a lot of issues.

**Comment by david-allison-1** [comment] 2021-07-14 13:18
> `C:\Users\Nino\AppData\Local\Temp\rsdroid3735626077991595567.dll: is not a valid win32 application`

Haven't seen this one. I have to confirm: are you running on 64 bit Windows?

**Comment by NinoDLC** [comment] 2021-07-14 15:37
Yes, 64 bit Win 10

**Comment by Starkly** [comment] 2021-07-14 16:46
I believe Git Bash is based on Ming64, which when installed includes both libgcc_s_seh-1.dll and libwinpthread-1.dll in it's default path (/mingw64/bin). Note that PATH is when running a git bash shell; it's not added to the windows PATH by default. That might  be an easier way to get the libraries, and you could try running gradlew from the git bash.

Also can post the result from java -version from whatever shell you are using?

**Comment by infinyte7** [comment] 2021-07-14 18:22
@Starkly Thanks I have using WSL for testing.

Git Bash is working properly in windows.

![image](https://user-images.githubusercontent.com/12841290/125672810-88a7ef73-1993-4d19-95b5-ff731d1879ca.png)

**Comment by infinyte7** [comment] 2021-07-14 18:28
@Starkly Thanks, it helps. I was using WSL. 
But Git Bash is more helpful.

![image](https://user-images.githubusercontent.com/12841290/125673551-64f8e8b0-9cfa-473d-a090-4d9b7695f621.png)

**Comment by NinoDLC** [comment] 2021-07-14 18:28
Agreed, same conclusions here, it works with basic git bash. 

I use PowerShell for Git and other CLI, `./gradlew jacocoTestReport` doesn't work with PowerShell, even with the "dll in PATH" trick. The command to open PowerShell with a "Git Touch" is `%SystemRoot%\System32\rundll32.exe "%SystemRoot%\System32\dfshim.dll",ShOpenVerbShortcut %LOCALAPPDATA%\GitHub\GitHub.appref-ms|--open-shell`

Before trying to run with another shell, I tried running on PowerShell with Java 8 and 13 (I installed 13 since Robolectric had a warning that API 29+ need Java 9+), without result.

**Comment by infinyte7** [comment] 2021-07-14 19:01
I have run the following command in Git Bash and the it build successfully.  From android studio there were `java.lang.UnsatisfiedLinkError`.

```
./gradlew jacocoUnitTestReport
```

![image](https://user-images.githubusercontent.com/12841290/125677666-99092e4a-b4fe-4e07-a23d-9ba29f627965.png)

**Comment by Starkly** [comment] 2021-07-14 19:07
So assuming that your Git Bash environment is using the same java as your PowerShell, this implies the root cause may be one of the other .dll's that  libgcc_s_seh-1.dll and libwinpthread-1.dll depend on 

you can use the utilities 'Dependencies', 'Dependency Walker', or 'dumpbin /dependents' on each .dll, to find out what they depend on and make sure all of those are in the right PATH

**Comment by NinoDLC** [comment] 2021-07-14 19:50
Other than what you stated before : 
> libgcc_s_seh-1.dll has a dependency on libwinpthread-1.dll

There's no other dependencies found, everything else is in system32\ folder. I have no idea why it doesn't work on PowerShell

![image](https://user-images.githubusercontent.com/11870220/125683833-387291e4-5d18-459c-b263-88ff08336faa.png)

**Comment by Arnold2381** [comment] 2021-11-02 04:33
@david-allison-1 

when i am running the tests at first I am getting this error 
```
C:\Users\Piyush Goel\AppData\Local\Temp\rsdroid943591543385363075.dll: Can't find dependent libraries
java.lang.UnsatisfiedLinkError: C:\Users\Piyush Goel\AppData\Local\Temp\rsdroid943591543385363075.dll: Can't find dependent libraries
```
then i ran checkrsdroid file and found that `libgcc_s_seh-1.dll` is missing, so i downloaded the file shared by you and placed that at the required path.
And now i am getting this error
```
C:\Users\Piyush Goel\AppData\Local\Temp\rsdroid8895325364430761062.dll: %1 is not a valid Win32 application
java.lang.UnsatisfiedLinkError: C:\Users\Piyush Goel\AppData\Local\Temp\rsdroid8895325364430761062.dll: %1 is not a valid Win32 application
```

**Comment by BrayanDSO** [comment] 2022-02-11 14:39
> when i am running the tests at first I am getting this error
> 
> ```
> C:\Users\Piyush Goel\AppData\Local\Temp\rsdroid943591543385363075.dll: Can't find dependent libraries
> java.lang.UnsatisfiedLinkError: C:\Users\Piyush Goel\AppData\Local\Temp\rsdroid943591543385363075.dll: Can't find dependent libraries
> ```
> 
> then i ran checkrsdroid file and found that `libgcc_s_seh-1.dll` is missing, so i downloaded the file shared by you and placed that at the required path. And now i am getting this error
> 
> ```
> C:\Users\Piyush Goel\AppData\Local\Temp\rsdroid8895325364430761062.dll: %1 is not a valid Win32 application
> java.lang.UnsatisfiedLinkError: C:\Users\Piyush Goel\AppData\Local\Temp\rsdroid8895325364430761062.dll: %1 is not a valid Win32 application
> ```

I had the exact same errors after doing the same procedures. OS: Windows 10 x64

**Comment by mikehardy** [comment] 2022-04-17 17:59
Still looking at solving this for real, but here's how I just did it
---

Everyone should use a package manager, and on windows I use chocolatey, install it like so https://chocolatey.org/install#install-step2

Then:

choco install mingw

And now the DLLs should be on PATH after a shell restart, you can investigate in a new powershell with this:

($env:Path).split(';')

...and you should see this:

C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin

Still want to investigate bundling those dlls somehow or doing the static link flag referenced above

**Closed** 2022-12-19 14:26 UTC
Labels: Bug, Keep Open, Backend Related

**Comment by dae** [comment] 2022-12-20 02:29
Please note I didn't make any changes to the Windows building in the .55 update aside from updating the Rust version, so this issue of missing gcc dlls may still exist.

**Comment by mikehardy** [comment] 2022-12-20 18:34
Yeah, but now it is documented more thoroughly I think in the README? I seem to remember doing that - that you need to either install mingw or similar, such that the DLLs will be there (basically `choco install mingw`)

If this bites someone else I'll ask them to update whatever doc they were using to install+run this stuff

**Comment by BrayanDSO** [comment] 2023-01-11 22:46
> 

> ## Still looking at solving this for real, but here's how I just did it
> Everyone should use a package manager, and on windows I use chocolatey, install it like so https://chocolatey.org/install#install-step2
> 
> Then:
> 
> choco install mingw
> 
> And now the DLLs should be on PATH after a shell restart, you can investigate in a new powershell with this:
> 
> ($env:Path).split(';')
> 
> ...and you should see this:
> 
> C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin
> 
> Still want to investigate bundling those dlls somehow or doing the static link flag referenced above

If you have installed git with chocolatey (or perhaps even without it), you can find a mingw64 installation inside the git installation folder and add it into your PATH (here the DLLs are at ``C:\Program Files\Git\mingw64\bin`)
