### ISSUE TITLE
[Bug] mathjax 'boldsymbol' function problem

### ISSUE THREAD

**Issue by Relevartt** [ankidroid/Anki-Android#13220] opened 2023-02-07 20:21 UTC
###### Reproduction Steps

1. Add a card with a mathjax on the front that contains '\boldsymbol F' or something like that.
2. Preview or get that card in your deck.
3. Possible workaround: add a second space between '\boledymbol' and 'F'.
![Screenshot_20230203-171526](https://user-images.githubusercontent.com/97558206/217356384-16a87928-a4a0-4a95-94aa-4b2c4a64bdb2.jpg)

###### Expected Result

![Screenshot_20230203-171533](https://user-images.githubusercontent.com/97558206/217355234-27e018e7-c448-4146-9710-4c431bd11140.jpg)

###### Actual Result

![Screenshot_20230203-171444](https://user-images.githubusercontent.com/97558206/217355648-1d984d2e-7e20-4248-9889-96396deca52d.jpg)

![Screenshot_20230203-171516](https://user-images.githubusercontent.com/97558206/217355256-5a886b35-b4c9-48c6-8ed4-69a9671dae03.jpg)

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = OnePlus

Model = GM1913

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; GM1913 Build/RKQ1.201022.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.117 Mobile Safari/537.36

ACRA UUID = 4dfad7f4-9d3a-44f2-b2c2-29a43469eea6

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2023-02-07 23:03
Can you please retest against our latest alphas? https://github.com/ankidroid/Anki-Android/releases

They include a huge pile of mathjax changes and every mathjax issue logged in recent memory against 2.15.6 is immediately close-able as fixed-already-in-alpha

Thanks!

**Comment by SanjaySargam** [comment] 2023-03-19 13:08
The issue is not reproducible on latest alphas 
@mikehardy You can feel free to close this issue

**Closed** 2023-03-20 02:45 UTC
