### ISSUE TITLE
Night Mode image inversion for Android 4.1.2 

### ISSUE THREAD

**Issue by scuen** [ankidroid/Anki-Android#4632] opened 2017-05-08 20:13 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

Hi everyone,

I have the following question, is it possible to invert the colors of an image (specifically a gif) when Night Mode is activated in an Android 4.1.2?

I've seen the Advanced Formatting but it clearly states that works for versions 4.4+...is there a workaround for my version?

Thank you all in advance and best regards.

Saul Cuen

**Comment by eginhard** [comment] 2017-05-08 22:42
Duplicate of #4625

**Closed by eginhard** 2017-05-08 22:42 UTC
