### ISSUE TITLE
[BUG]: Can't see the cards in deck, but appears in card browser

### ISSUE THREAD

**Issue by zapdos6244** [ankidroid/Anki-Android#15791] opened 2024-03-06 06:31 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Whole subdeck suddenly disappeared and made itself a new deck, with only around 2.5% of cards. When looking at the original location of subdeck, it pops up "Error deck not found in limits map". But if I go to Card Browser to view the original deck, all the cards appear.

### Expected behaviour

Subdeck B should have appeared under Deck A

### Actual behaviour

Subdeck B made a new Deck B with little of the original cards. When clicking Deck A, pops up "Error deck not found in limits map". But looking at Card Browser of Deck A, I could see the entire contents of subdeck B there

### Debug info

```text
AnkiDroid Version = 2.17.3 (ca4cb3c2802bcb17e73b051e7e42308993513717)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 9 (SDK 28)

ProductFlavor = play

Manufacturer = asus

Model = ASUS_X00TDB

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; ASUS_X00TDB Build/PKQ1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.91 Mobile Safari/537.36

ACRA UUID = 1f7364b2-d373-4aea-b31f-1a8b40efca1b

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment] 2024-03-06 07:50
The Check Database action will likely fix the error.

**Comment by zapdos6244** [comment] 2024-03-06 08:17
Thank you very much! What may have caused this to happen? I'm worried it might happen again in the future

**Comment by david-allison** [comment] 2024-03-10 11:48
Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/15195

* https://github.com/ankidroid/Anki-Android/issues/15195

**Closed by david-allison** 2024-03-10 11:48 UTC
Labels: Bug, Needs Triage
