### ISSUE TITLE
[Bug] 2.15 - Reported Synchronisation Taking Much Longer (cards and media)

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#8925] opened 2021-05-25 11:03 UTC
> Thing I noticed after today's update: synchronization takes much longer.
>
> My use-case: I have little over 100'000 cards. Sometimes on desktop I run add-on that adjusts ease factor for all cards.
>
> After that synchronization is quite big. But it become definitely longer after today's update.

/u/szalejot (reddit)

**Comment by david-allison-1** [comment] 2021-05-26 17:43
Note: This is not media-related, just card data

**Comment by mikehardy** [comment] 2021-06-01 21:31
Strangely - this is media related for me. I'm experiencing this right now, it is *horrific* on media sync. The collection was pretty slow as well. When I first saw this reported I blithely said "I don't know, it seems to saturate my 25Mbit pipe?" but at least for a real device (Pixel 4a) at the moment - hooboy this thing is crawling through sand mixed with cold molasses slow

**Comment by david-allison-1** [comment] 2021-06-01 21:57
> Strangely - this is media related for me. I'm experiencing this right now, it is _horrific_ on media sync. The collection was pretty slow as well. When I first saw this reported I blithely said "I don't know, it seems to saturate my 25Mbit pipe?" but at least for a real device (Pixel 4a) at the moment - hooboy this thing is crawling through sand mixed with cold molasses slow

The media sucks, and has done for a long time. One of the best parts of the Rust conversion will be moving it to the background like in Anki Desktop.

From memory, you don't sync media much. Is this a regression, or is it also slow for 2.1X as well?

**Comment by mikehardy** [comment] 2021-06-01 22:56
regression for me, it used to be a bit stop/starty because of the 25-files-at-once thing but it still saturated my downlink. Now it's crawlin'. I haven't attempted to go back to 2.14, I was just setting up a new phone as one of the things that happens when your mom visits you in your country where there is no postal system or economical package delivery from the US is that she brings all the goodies. Going through 1st time setup on a bunch of new / replacement device :)

**Comment by mikehardy** [comment] 2021-09-04 14:38
This is definitely an issue

**Comment by albsch** [comment] 2021-09-05 16:11
I am affected, too. Normal usage (desktop + android app) is becoming annoying with a big deck with media, because continuing on the android app after desktop use introduces a long (up to 10 minutes) sync.

**Comment by mikehardy** [comment] 2021-09-05 16:25
we definitely understand, I pinned this to make sure it never stales out - as mentioned by David

> The media sucks, and has done for a long time (imagine 3GB of AnKing). One of the best parts of the Rust conversion will be moving it to the background like in Anki Desktop.

And all I can do is say this is an area of serious hard work, it is happening: 

https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+rust+author%3Adavid-allison-1

It's just a massive massive effort, and critical to get right (it's your card collection access method after all...) so takes time. We appreciate the patience

**Comment by GypsyAcidQueen** [comment] 2021-09-19 15:23
Just chiming in to say that this is affecting me too, and to keep the thread alive!

**Comment by mikehardy** [comment] 2021-09-19 15:53
Yep - part of the conversion is handling the new V16 schema, and 2 more of those massive pull requests just went in yesterday, with another pending https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+author%3Adavid-allison-1+sort%3Aupdated-desc+

It's not easy to do all this stuff right but David's chewing through it at quite a rate

**Comment by david-allison-1** [comment] 2021-11-23 09:40
Fixed in #9249, it's writing to a "publicly visible" directory that's taking time. 

Significantly faster if the directory is changed to `/storage/emulated/0/android/data.com.ichi2.anki/testCol`

**Comment by mikehardy** [comment] 2021-11-23 13:26
what!? is there some documentation on that ? Is it because of MediaScanner ?

**Comment by mikehardy** [comment] 2021-11-23 13:28
(I ask because there are ways to disable it like dropping a .nomedia file in there?)

**Comment by mikehardy** [comment] 2021-11-23 15:51
Fascinating.

**Comment by Hxppdv** [comment] 2022-02-04 16:52
> My belief is that there's a massive IO performance penalty due to the security associated with enforcing scoped storage (saw a Reddit thread with 6x storage slowdown on Android 11 which tipped me off).
I tried disabling fuse on a rooted phone to bring back support for the old sdcardfs, and so far it seems to be working, and syncing is much faster. It seems that, at least in my case, the slow sync problem is related to fuse aka [Scoped Storage](https://source.android.com/devices/storage/scoped).

**Closed** 2023-01-06 22:12 UTC
Labels: Keep Open
