### ISSUE TITLE
Feature Request: Lower image size from camera capture

### ISSUE THREAD

**Issue by chrisrollins65** [ankidroid/Anki-Android#5629] opened 2019-11-15 10:40 UTC
When attaching images to cards from the camera, they appear to be saved at full size. This results in images that are 3mb each on my phone, and if I did this for every card, I'd have decks that are gigabytes in size when in reality I only need images that are maybe 50kb to view on my phone.

Is there any possibility to add the feature to downsize images before adding them to cards and maybe an option in the settings allowing us to choose whether we want images downsized or not?

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2019-11-15 15:14
Hi there - This is a duplicate of #2554 but there is hope - can you test #5301 ?

There is a PR there that may or may not work (it has not received great testing yet) and it's on a path to integrate eventually when the libanki forward-porting and 2.9 stabilization work settles down

**Closed by mikehardy** 2019-11-15 15:14 UTC
