### ISSUE TITLE
ForegroundServiceStartNotAllowedException on start

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13868] opened 2023-05-16 03:03 UTC
https://ankidroid.org/acra/app/1/bug/49980/report/fd9bac98-8c65-474f-96d2-a8e3811b5606

Seems to appear as start. Becaume logcat is very short
```

--------- beginning of main
05-15 08:13:54.251 I/AnkiDroid( 6305): AnkiActivity::onStart - DeckPicker
05-15 08:13:54.266 I/AnkiDroid( 6305): AnkiActivity::onResume - DeckPicker
05-15 08:13:54.463 E/AnkiDroid( 6305): CollectionManager/ blocked main thread for 177ms:
05-15 08:13:54.463 E/AnkiDroid( 6305): com.ichi2.anki.DeckPicker.refreshState(DeckPicker.kt:72)
05-15 08:13:54.576 I/AnkiDroid( 6305): Updating deck list UI
```

```
ndroid.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.ichi2.anki/.services.MigrationService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4816)
	at android.os.Parcel.readParcelable(Parcel.java:4778)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3006)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5302)
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1894)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at androidx.core.content.g.a(R8$$SyntheticClass:1)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:7)
	at com.ichi2.anki.DeckPicker.startMigrateUserDataService(DeckPicker.kt:18)
	at com.ichi2.anki.DeckPicker.startingStorageMigrationInterruptsStartup(DeckPicker.kt:41)
	at com.ichi2.anki.DeckPicker.handleStartup(DeckPicker.kt:45)
	at com.ichi2.anki.DeckPicker$migrate$1$elapsedMillisDuringEssentialFilesMigration$1$1$1.invokeSuspend(DeckPicker.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1)
```

**Comment by lukstbit** [comment] 2023-05-27 10:27
It's reasonable to expect that the code in DeckPicker.migrate() can throw this exception as it attempts to start the migration service after doing work related to migration essential files. If the user calls this method and then sends the DeckPicker to the background and the migration of essential files takes several seconds starting the service will fail.

**Comment by oakkitten** [comment] 2023-05-27 16:06
This is a tough issue to solve properly. I thought about using a worker as an alternative, but the work it can do is normally limited to 10 minutes, and if you go for [a long-running worker](https://developer.android.com/guide/background/persistent/how-to/long-running), you seem to be [getting the same restrictions as with foreground services](https://developer.android.com/reference/kotlin/androidx/work/CoroutineWorker#setForeground(androidx.work.ForegroundInfo):~:text=Calling%20setForeground%20will%20throw%20an%20IllegalStateException%20if%20the%20process%20is%20subject%20to%20foreground%20service%20restrictions.) as those are used under the hood.

I think we can run into the issue in two ways:
* If the user minimizes the app during the “essential file migration” phase (the service is launched *after* that and only moves media files)
* If the user needs to sync before migration and also minimizes the app

Perhaps this could be solved in the following way:
* Launch the service in the very beginning of the migration. For simplicity, we can skip doing actual work in the service's `onStartCommand` and keep it where it is now, only using the service to show the notification. We'd need to add a new progress state to `com.ichi2.anki.services.MigrationService.Progress` such as `TransferringEssentialFiles` (and rename the others) and we can perhaps show intermediate progress in the notification with a suitable message. (Although not a fan of this being followed with another indeterminate progress for calculating the size of media files to transfer.)
* Do not automatically start migration after sync. For simplicity, I suggest simply offering the user to sync and then doing nothing, making the user tap on the migrate button after a successful sync. As a user, I would actually prefer this.

**Comment by oakkitten** [comment] 2023-06-09 13:34
I can't reproduce the issue on Android 11. Can anyone reproduce it on 12/13? I don't think you have to be on 12 to trigger it but maybe the docs are wrong a bit? I tested by minimizing the app right after starting migration. Threw in `Thread.sleep(60_000)` before the call to `startMigrateUserDataService()` for good measure.

**Comment by BrayanDSO** [comment] 2023-06-09 15:24
I can see the lifecycle and withProgress problem. I'll split it into another issue

**Comment by oakkitten** [comment] 2023-06-23 17:25
I think that maybe a part of the issue originates in [348edd43](https://github.com/ankidroid/Anki-Android/commit/348edd43e1646b7f8ba5b3915f2d4292569f1a66#diff-bc9854cf8afc1ab02dad530aa214fdd7d2d9b3e35352bc63d2eb822861912f6dR936-R946). Here `mActivityPaused` was, I assume, by mistake moved into `refreshState` from `onResume`. And here we don't proceed with migration if that variable is set:

https://github.com/ankidroid/Anki-Android/blob/37f4d67d9380e393d9fb96295d6e4b19ff300e0e/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L2521-L2532

So it I think sometimes it's possible that this check fails, given how `refreshState` is often called by sync handling coroutines. I'll attempt to fix this bit as a part of my attempt to handle #13970 by moving essential file migration into the service. But I can't be sure that it is a comprehensive solution as I wasn't able to reproduce the crash. It seems that my Android allows services to start from background?

**Closed** 2023-07-02 12:56 UTC
Labels: Priority-High, Bug, Scoped storage
