### ISSUE TITLE
Crash on delete note type

### ISSUE THREAD

**Issue by st603** [ankidroid/Anki-Android#4593] opened 2017-02-25 15:00 UTC
:(

**Comment by Ana06** [comment] 2017-02-25 16:06
I also get the same error. 

AnkiDroid version: 2.8.1

Android version: 7.1.1

**Comment by Ana06** [comment] 2017-02-25 16:07
It also fails when adding a new field in a note and try to save it :confused:

**Comment by eginhard** [comment] 2017-02-26 01:02
Duplicate of #4594

**Closed by eginhard** 2017-02-26 01:02 UTC

**Comment by Ana06** [comment] 2017-02-26 09:06
@eginhard

> Duplicate of #459

Not really, #459 is about editing a note type and this is about editing/deleting a note template. So, I think they are unrelated and we should merge this two issues

**Comment by eginhard** [comment] 2017-02-26 10:53
I had updated that issue to reflect that. Anyway, it was the same underlying issue in both cases and should now be fixed in the latest beta: https://ankidroid.org/docs/manual.html#betaTesting
