### ISSUE TITLE
[Bug] can`t receive words/entries from takoboto(japanese dictionary)

### ISSUE THREAD

**Issue by ionx711** [ankidroid/Anki-Android#8963] opened 2021-05-26 14:08 UTC
###### Expected Result
used to receive new entries from takoboto. but since it updated to v2.15.00 it can`t.

###### Actual Result
Error

System.NullReferenceException: Object reference not set to an instance of an object
at com.ichi2.anki.AnkiDroidHelper.removeDuplicates(System.Collections.Generic.List`1[T] fields, System.Collections.Generic.List`1[T] tags, System.Int64 modelid, System.Nullable`1[T] deckId, System.Collections.Generic.List`1[T]noteidFieldsAndTagsToUpdate) [0x0005b] in <a7c69e18baf7427ba6d2c38cf2874dbf>:0 at aj.a (Android.App.Activity A_0, com.ichi2.anki.AnkiDroidHelperA_1,c1[] A_2, System.String[][] A_3, System.String A_4, System.Boolean A_5, System.Boolean A_6, System.Boolean A_7) [0x0042a] in <a7c69e18baf7427ba6d2c38cf2874dbf>:0 at aj+d.h () [0x00015] in <a7c69e18baf7427ba6d2c38cf2874dbf>:0 at b4.RunInBackground (System.Int32[] useless) [0x00000] in <a7c69e18baf7427ba6d2c38cf2874bdf>:0

###### Debug info
AnkiDroid Version = 2.15.0

Android Version = 9

Manufacturer = Google

Model = kukui

Hardware = cheets

Webview User Agent = Mozilla/5.0 (Linux; Android 9; kukui Build/R90-13816.82.0; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.77 Safari/537.36

ACRA UUID = e05f72e4-daa4-473a-a12f-23025ee2a0be

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2021-05-26 14:25
Hi there! Duplicate of #8928 - fixed in 2.15.1 - please update! sorry for the hassle!

**Closed by mikehardy** 2021-05-26 14:25 UTC
