### ISSUE TITLE
Ankidroid crashes inside the settings

### ISSUE THREAD

**Issue by readych** [ankidroid/Anki-Android#4681] opened 2017-08-07 15:15 UTC
Specs:
- App: AnkiDroid - 2.8.2
- Android: 7.0
- Device: Galaxy Tab S3
- Model: SM-T820

This problem only appears on the Galaxy Tab S3. If I test it on an other Android devices, the app works without any problems.

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Start app
2. Open the settings.
3. Click on the section "Advanced"

###### Expected Result

Showing the "Advanced" settings content.

###### Actual Result

Ankidroid crashes immediately with the message "AnkiDroid encountered a problem; a report is being sent to the developers".

**Comment by Ruckamongus** [comment] 2017-08-08 23:13
I reported the same crash a while ago: https://github.com/ankidroid/Anki-Android/issues/4422

To update I still get the crash on 2.9 alpha 4 on Pixel C with LineageOS. However it works fine on numerous other devices running various versions of Android including LineageOS. Seems to be an odd issue possibly outside of the hands of the developers here.

**Comment by iaai232** [comment] 2017-08-25 16:10
This is happening to me too. I tried reinstalling the app and now I can't access the Reviewing settings either - because it crashes whenever I try.

I am running Ankidroid 7.1.1 on a Nexus 9.

Is there really nothing that can be done?

**Comment by timrae** [comment] 2017-08-31 00:38
If someone with root can give us the output of their logcat after the crash occurred we could look at the stacktrace and see if there's anything we could do to workaround it.

**Comment by nicolas-raoul** [comment] 2017-09-05 07:12
Duplicate of #4422 I believe?
If not feel free to reopen :-)

**Closed by nicolas-raoul** 2017-09-05 07:12 UTC
