### ISSUE TITLE
[BUG]: Using the Bluetooth controller's page up and down functionality may cause the screen to dim

### ISSUE THREAD

**Issue by Jeffreyyao25** [ankidroid/Anki-Android#15164] opened 2024-01-05 11:43 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Connect the Bluetooth controller, bind the page up and page down functions on the control page, return to the deck page. 

When the text on the deck page is relatively long, you will need to use the page up and page down functions. 

After implementing this feature, the screen will simultaneously dim.

### Expected behaviour

 Performing only page up and down scrolling without any additional effects.

### Actual behaviour

 In addition to scrolling up and down, there is also an accompanying screen dimming effect.

### Debug info

```text
AnkiDroid Version = 2.17alpha14 (0717daab11cd9669997aea6a421ec94689120cb6)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Lenovo

Model = TB320FC

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; TB320FC Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.144 Safari/537.36

ACRA UUID = 9c44f3de-8649-4281-be04-c350f95bf1a4

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

 Most of my cards have images, so I'm not sure if this issue would occur with cards that are purely text-based.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-03-05 21:10
Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/15164

* https://github.com/ankidroid/Anki-Android/issues/15164

**Closed by david-allison** 2024-03-05 21:10 UTC
Labels: Bug, Needs Triage
