### ISSUE TITLE
InvocationTargetException/UnsatisfiedLinkError armeabi-v7a/libmonochrome.so is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7738] opened 2020-11-21 17:28 UTC
This has been seen on 2.13.5 (https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/8c7a19c5-fe48-4cbd-b8d0-0488e49ff781), but is much more prominent in 2.14.0 - might be our issue.

prop | value
-- | --
SUPPORTED_32_BIT_ABIS | [armeabi-v7a, armeabi]
SUPPORTED_64_BIT_ABIS | [arm64-v8a]
SUPPORTED_ABIS | [arm64-v8a, armeabi-v7a, armeabi] [+]

```
android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:204)
at android.webkit.CookieManager.getInstance(CookieManager.java:39)
at android.webkit.CookieManager.setAcceptFileSchemeCookies(CookieManager.java:264)
at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:24)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
at android.app.ActivityThread.-wrap3(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:198)
... 13 more
Caused by: VJ1: errorCode=2
at OJ1.g(chromium-Monochrome.aab-stable-428006620:21)
at OJ1.i(chromium-Monochrome.aab-stable-428006620:5)
at org.chromium.android_webview.AwBrowserProcess.h(chromium-Monochrome.aab-stable-428006620:9)
at com.android.webview.chromium.WebViewChromiumFactoryProvider.f(chromium-Monochrome.aab-stable-428006620:78)
at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(chromium-Monochrome.aab-stable-428006620:12)
... 16 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.android.chrome-1/base.apk!/lib/armeabi-v7a/libmonochrome.so" is 32-bit instead of 64-bit
at java.lang.Runtime.loadLibrary0(Runtime.java:977)
at java.lang.System.loadLibrary(System.java:1567)
at OJ1.g(chromium-Monochrome.aab-stable-428006620:13)
... 20 more
```

**Comment by david-allison-1** [comment] 2020-11-21 17:37
Maybe: https://bugs.chromium.org/p/chromium/issues/detail?id=547842#c29

**Comment by mikehardy** [comment] 2020-11-22 22:48
The comment mentioning that it is a busted update from 3rd party market seems plausible.
Best/easiest course would be just to search the exception chain for a message like "Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.android.webview-1/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit", pop a toast with this guess and just die I think. I'm not going to do a 32bit ndk filter, that's silly IMHO

**Comment by david-allison-1** [comment] 2020-11-22 22:52
We already handle this: 
![image](https://user-images.githubusercontent.com/62114487/99919422-47f90f80-2d15-11eb-880d-e4aa8de962a7.png)

Awaiting #7739 to fix the error message

**Comment by david-allison-1** [comment] 2020-11-22 22:53
Presuming this isn't actionable aside from the above, would you be happy with closing?

**Comment by mikehardy** [comment] 2020-11-22 23:07
Yeah good point and I just merged (and am about to pick+push) the chained exception reporting

**Closed by mikehardy** 2020-11-22 23:07 UTC
Labels: Bug
