### ISSUE TITLE
Stats lost when importing from AnkiDroid to desktop Anki

### ISSUE THREAD

**Issue by cohalex** [ankidroid/Anki-Android#7303] opened 2020-09-28 20:33 UTC
###### Configuration

Anki desktop version 2.1.33 on Ubuntu 20.04
AnkiDroid version 2.13.3

###### Scenario

Studying on the desktop, exporting the collection at the end of the day, importing to AnkiDroid, studying on the phone the next day, exporting from AnkiDroid at the end of the day, importing the collection to Anki desktop.

###### Reproduction steps:

Anki desktop:

1. File > Export
2. Export format: Anki Collection Package (*.colpkg)
3. Check "Include media"
4. Copy the colpkg file to the mobile device

AnkiDroid - the next day:

1. Import the colpkg file
2. Study
3. Export collection > Check "Include scheduling" + "Include media"
4. Save to file
5. Copy the colpkg file to the computer

Anki desktop:

1. Import colpkg file
2. Confirm the warning "This will delete your existing collection and replace it with the data in the file you're importing. Are you sure?"
3. Click "Stats"

###### Expected Result

Desktop stats should display combined data from desktop and phone study days.

###### Actual Result

In my case the desktop stats screen is missing desktop study days and only displays phone study days in the heatmap. Actual progress and card scheduling seem correct.

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment] 2020-09-28 21:22
Hi @cohalex, thanks for the report!

At which stage in the reproduction steps is the statistics tab wiped?

**Comment by cohalex** [comment] 2020-09-29 06:01
The stats heatmap in Anki desktop changes after the import, at the end of the scenario I described.

If I import the original colpkg I exported the day before from Anki desktop (in the very first step), back to Anki desktop, the heatmap shows the desktop study days, so I assume the problem is with AnkiDroid, exporting only the mobile study days or somehow corrupting the desktop data.

**Comment by mikehardy** [comment] 2020-09-29 13:31
Interesting. I wonder if that heatmap data - rather than being constructed on the fly from review data - is stored in the collection config spaces. There was a long-standing but unfixed issue about various sync scenarios not syncing, specifically the collection conf. That's my hypothesis on this one

**Comment by dae** [comment] 2020-09-30 02:31
@cohalex you did not export your scheduling when transferring from computer to phone, so it was lost at that point. Collection packages are akin to overwriting files, and no merging happens.

**Comment by cohalex** [comment] 2020-09-30 05:39
@dae When exporting from Anki desktop I don't see an option to include or not include scheduling. Are you saying the data simply cannot be exported via the colpkg?

Also, it seems that shcheduling is correct when importing back from AnkiDroid, as reflected in my counters for study. It's the stats that are missing data and the first place I see it is the heatmap.

On a personal note, Anki is a great tool, thank you so much.

**Comment by dae** [comment] 2020-09-30 05:47
Sorry, I saw you omitted "include scheduling" in your first step, and forgot that was not possible with colpkg selected - it's always included in the computer version.

The heatmap only uses data in the revlog table, and if you're exporting a colpkg in both directions, it should be included verbatim in both instances. If the computer studies are visible in AnkiDroid but not when importing the colpkg back into the computer version, that does sound odd. What happens if you import that colpkg back into AnkiDroid?

**Comment by cohalex** [comment] 2020-10-02 09:55
If I import the colpkg I exported from AnkiDroid back into AnkiDroid nothing changes. Same counter for due cards and the same data in the statistics page.

**Comment by cohalex** [comment] 2020-10-03 14:35
I started from scratch and was able to reproduce the issue. Testing the steps below takes about 5 minutes so I hope more people can try and verify. Hopefully I'm not the only one with this problem as it is quite frustrating.

##### Desktop:
Version 2.1.35, this time on Windows instead of Linux

##### AnkiDroid:
Version 2.13.4

#### On the Desktop:

1. Create a new empty profile.
2. Download a randomly selected deck from AnkiWeb. I picked [this one](https://ankiweb.net/shared/info/1994936100).
4. Study 5 cards.
5. Verify the stats page shows you studied 5 cards today.
6. Export colpkg and copy it to the mobile device.

#### In AnkiDroid:

1. Import colpkg.
2. Go to the Statistics page, it should say 5 cards were studied today.
3. Study a few more cards.
4. Go to the Statistics page again, verify the number of cards studied today has increased.
5. Export colpkg and copy the file to the computer. 

#### Back on the Desktop:

1. Import the colpkg.
2. Open the stats page.
3. For me at this point it says "**No cards have been studied today**" which is clearly wrong.
4. The heatmap diaplays "**NO DATA**" as if there were no study days, which is clearly wrong.
5. Now study at least one more card.
6. Open the stats page again.
7. Now the Today section shows the correct combined number of cards studied on the desktop and on the mobile device. The heatmap shows the current day as a blue rectangle, the tooltip above that day shows the correct number of cards studied as well.

##### Note:
Clocks are synced and timezone settings are identical across all devices used.

**Comment by dae** [comment] 2020-10-04 01:14
I tested using the latest AnkiDroid development code, and was not able to reproduce this - the daily counts and previous history successfully round-tripped back into the computer version, and were visible immediately after import - I did not need to study any cards to make the stats appear. Do you use any add-ons?

**Comment by cohalex** [comment] 2020-10-04 20:32
I think I've figured it out. It's not a data issue and not even an AnkiDroid issue but simply a UI issue in Anki Desktop or at least a problem with my understanding of the UI.

When opening the Statistics window in Anki Desktop, the default selected radio button is "deck" (the other option is "collection") and the textbox next to it says "deck:current".

What happens next depends on how many decks I have in the collection.

- When my collection contains several decks, after importing a colpkg there is no indication which deck is the "current" deck (no background shade in the deck list) but there is a current deck set somewhere in memory because the Statistics windows shows its data. That's what confused me and made me think some of my stats were lost, when in fact I was simply looking at (or more precisely - I was shown) a heatmap of a different deck. Adding the current deck's name on the Statistics windows could be helpful.

- When my test collection contains only one deck it gets weird. After importing the colpkg there is no indication of a selected deck (as is the case with multiple decks) but now when I open the Statistics windows all sections show "NO DATA". Selecting the "collection" option shows the data correctly. This behavior is quite confusing, if there is only one deck I would expect it to be the current deck by default.

In any case, this issue can be closed as it is not related to AnkiDroid. I'm happy to know I can go back and forth between desktop and mobile without losing data. Thank you for your patience and for trying to help.

**Comment by mikehardy** [comment] 2020-10-04 20:38
Happy to know we're not losing data :sweat_smile: - cheers

**Closed by mikehardy** 2020-10-04 20:38 UTC
Labels: Needs Triage, Waiting For Feedback
