### ISSUE TITLE
[2.9 ACRA] Using WebView from more than one process at once with the same data directory is not supported

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5502] opened 2019-10-15 13:17 UTC
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/6ba3eddd-911e-4b40-bef3-262118a3f189

```
java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
at org.chromium.android_webview.AwBrowserProcess.a(PG:40)
at vo.c(PG:88)
at vo.b(PG:152)
at vo.a(PG:133)
at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(PG:239)
at com.android.webview.chromium.WebViewChromium.init(PG:44)
at android.webkit.WebView.<init>(WebView.java:678)
at android.webkit.WebView.<init>(WebView.java:604)
at android.webkit.WebView.<init>(WebView.java:587)
at android.webkit.WebView.<init>(WebView.java:574)
at android.webkit.WebView.<init>(WebView.java:564)
at com.ichi2.anki.AbstractFlashcardViewer$MyWebView.<init>(AbstractFlashcardViewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.createWebView(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.setInterface(AbstractFlashcardViewer.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:3)
at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:11)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
at com.ichi2.async.DeckTask$TaskListener.onProgressUpdate(DeckTask.java:1)
at com.ichi2.async.DeckTask.onProgressUpdate(DeckTask.java:3)
at com.ichi2.async.DeckTask.onProgressUpdate(DeckTask.java:1)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:715)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7050)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by david-allison-1** [comment] 2020-06-02 23:23
I believe this is fixed in #6275, please reopen if this reappears.

**Comment by david-allison-1** [comment] 2020-07-08 14:46
Specifically blames the `acra` process here

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardTemplatePreviewer}: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Lock owner com.ichi2.anki:acra (pid 18647)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3555)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8016)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Lock owner com.ichi2.anki:acra (pid 18647)
at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle.apk-stable-410410683:26)
at ka.i(chromium-TrichromeWebViewGoogle.apk-stable-410410683:37)
at ka.b(chromium-TrichromeWebViewGoogle.apk-stable-410410683:15)
at ka.k(chromium-TrichromeWebViewGoogle.apk-stable-410410683:2)
at com.android.webview.chromium.WebViewChromiumFactoryProvider.h(chromium-TrichromeWebViewGoogle.apk-stable-410410683:2)
at com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle.apk-stable-410410683:14)
at android.webkit.WebView.<init>(WebView.java:429)
at android.webkit.WebView.<init>(WebView.java:353)
at android.webkit.WebView.<init>(WebView.java:336)
at android.webkit.WebView.<init>(WebView.java:323)
at android.webkit.WebView.<init>(WebView.java:313)
at com.ichi2.anki.AbstractFlashcardViewer$MyWebView.<init>(AbstractFlashcardViewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.createWebView(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.recreateWebView(AbstractFlashcardViewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.setInterface(AbstractFlashcardViewer.java:2)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:4)
at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.CardTemplatePreviewer.displayCardQuestion(CardTemplatePreviewer.java:1)
at com.ichi2.anki.CardTemplatePreviewer.onCollectionLoaded(CardTemplatePreviewer.java:12)
at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:4)
at com.ichi2.anki.CardTemplatePreviewer.onCreate(CardTemplatePreviewer.java:19)
at android.app.Activity.performCreate(Activity.java:7957)
at android.app.Activity.performCreate(Activity.java:7946)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3530)
... 11 more
```

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/a6ecb7ec-4c4d-4af3-8baf-d6b1818aef38

**Comment by mikehardy** [comment] 2020-07-08 15:12
bizarre - how would the acra process be starting CardTemplatePreviewer? 🤔

**Comment by david-allison-1** [comment] 2020-07-08 15:36
> bizarre - how would the acra process be starting CardTemplatePreviewer?

I hink that's the Previewer not being able to start due to ACRA starting a WebView /somewhere/. I don't think it's ACRA using the previewer (although I'm open to being mistaken).

**Comment by david-allison-1** [comment] 2020-07-13 16:52
I can reproduce this on 2.13alpha2, as long as error reporting is enabled - would have been high priority, as it blocks reviewing after a crash occurs. Now... we rarely crash, so it's less of an issue.

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/4c809001-b1b3-44af-9f70-49f26137c55c
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/23c86c4d-eed0-4f68-9c9d-e4903a2aaba9

**Comment by david-allison-1** [comment] 2020-07-14 23:06
I don't quite understand how the `:acra` process works (it seems to have all the logcat of the main app), but it's not killed once the exception report is successfully sent.

**Comment by david-allison-1** [comment] 2020-07-14 23:27
Maybe not:

>                     //Killing a process with a debugger attached would kill the whole application including our service, so we can't do that.

**Comment by mikehardy** [comment] 2020-07-15 00:11
I wonder
https://github.com/ankidroid/Anki-Android/blob/ea3e590e2a7a33deca495944ebfc8c183e740dca/AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java#L122

should maybe be:

API>=21 https://developer.android.com/reference/android/app/Activity#finishAndRemoveTask()

API<21 https://github.com/ACRA/acra/blob/23435c947d2b87202064f11b5b1e3b36df73711a/acra-core/src/main/java/org/acra/util/ProcessFinisher.java#L106-L109

or one of these https://stackoverflow.com/a/40231289/9910298

**Comment by david-allison-1** [comment] 2020-07-15 10:47
I had a skim and things look reasonable in the above class, we're inheriting from `CrashDialog` which uses `finish()` in the method we override: https://github.com/ankidroid/Anki-Android/blob/ea3e590e2a7a33deca495944ebfc8c183e740dca/AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.java#L122

After a little more testing (no debugger):

* Clear Data - Send Report - `:acra` process is still running
* After Rate Limiter  - `:acra` process is no longer running

**Comment by mikehardy** [comment] 2020-07-15 15:08
So perhaps it's the sender that needs cleaner exit? I had considered killing it pre-send and relying on send-on-restart to do it but if it's a crash loop yeah that may not work. Limiter should stop the dialog (and thus process) from being spawned at all) so it makes sense it is not there?

**Comment by mikehardy** [comment] 2020-07-15 15:09
still seems odd the webview is initialized at all for process ':acra'

**Comment by david-allison-1** [comment] 2020-07-15 15:52
Had a binary search, it's `UsageAnalytics.initialize(this);` which initializes the WebView.

`WebView.setDataDirectorySuffix` was used to test (as it crashes when run after a WebView is inisialized) - I expect it'll fix the problem, but it's API 28+, we need a better solution

**Comment by david-allison-1** [comment] 2020-07-15 15:57
Specifically: 

https://github.com/ankidroid/Anki-Android/blob/254944f96552873d993ba7565fc5e741ad908622/AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java#L321-322

**Comment by mikehardy** [comment] 2020-07-15 18:09
Oh dang! That's the exact thing that makes our analytics much more useful. Seems fair to say - in that method

1. If ACRA process then... (ACRA provides a util method I think?)
1.  if we are API<28, use the fallback user agent
1.  if we are are API>=28 set some temp data directory?

**Comment by mikehardy** [comment] 2020-07-15 18:10
Sucks that you fixed this (with the "abort init if ACRA" shunt) and then it came back like a :zombie: sorry

**Comment by david-allison-1** [comment] 2020-07-15 18:11
Any issue with blocking analytics initialization if in the `:acra` process? Do we get analytics value from the sender process?

**Comment by david-allison-1** [comment] 2020-07-15 18:11
Another ideal would be to disable/ kill the WebView afterwards, if that's possible

**Comment by mikehardy** [comment] 2020-07-15 18:57
The only thing we'll miss is that for ACRA analytics hits, we won't have auto-fingerprinted device recognition because we won't have the official WebView User-Agent string, we will have inited with the fallback. A small price to pay IMHO

**Comment by david-allison-1** [comment] 2020-07-15 19:06
I'll get on it later tonight. Will need a instrumented test. My unit test passed when it shouldn't when I used Robolectric

**Comment by mikehardy** [comment] 2020-07-15 20:12
Yep - robolectric may not be trusted for multi-thread, much less multi-process...

**Closed** 2020-07-16 19:18 UTC
Labels: 2.13.x, 2.9.x, Bug, Reproduced
