### ISSUE TITLE
How to add a custom plugin? Or how to build AnkiDroid with my plugin inside?

### ISSUE THREAD

**Issue by OnkelTem** [ankidroid/Anki-Android#4902] opened 2018-07-17 10:09 UTC
Hi all.

I'm a new AnkiDroid user and I have a couple of python scripts for AnkiDesktop which I want to use in AnkiDroid. 

(The reason is simple: Anki doesn't use any sensible/scientific proven strategy of reviewing cards, and that - after 133 years of [Ebbinghaus’s researches](https://en.wikipedia.org/wiki/Forgetting_curve).
[There is an attempt](https://eshapard.github.io/anki/thoughts-on-a-new-algorithm-for-anki.html) however to implement this strategy and I don't want to spend a minute with the old reviewing approach honestly)

So is there a way either to:
1) get a plugin working with AnkiDroid?
OR
2) build AnkiDroid with some specific plugin?

**Comment by mikehardy** [comment] 2018-07-25 14:54
Plugins for Android applications are apparently hard - they've been looked at before in an AnkiDroid context and no sensible way has been found yet. However, there is an API available that lets you do whatever you need with regard to the note database.

There are a few other issues that would be helped with a plugin architecture (#675 for instance - load balancing - good comments on that one)

I just had an idea though - if you could combine a Python execution environment with a separate app that used the AnkiDroid API, you could perhaps have cross-compatible Python scripts that loaded in your app, executed against the AnkiDroid database (to set scheduling information or similar) and handled your use case

That sounds amazing to me, but if that also all seems like a lot of effort, you can see where there are no PRs yet.

As for building something custom, you could easily fork, make a topic branch, and alter the scheduler. It's in Java for AnkiDroid but if my read of it is correct the port from Python is mathematical enough that it appears similar in both languages. 

In fact there's a new scheduler in Anki 2.1 apparently (#4905 we don't support it yet) so if you implemented a modular scheduling capability, with your desired scheduling as a second option that might get us some way to supporting 2.1's built-in scheduler also, as we'd have some infrastructure for multiple schedulers and preferences to select them.

**Comment by timrae** [comment] 2018-07-26 00:56
Yeah we don't currently have support for plugins in the traditional Anki desktop sense. As Mike suggested, your best bet is to create your own scheduler which implements the same interface as the current scheduler, and run a custom version of ankidroid with that. If there's a strong usage case for it then we could potentially merge it into master as an alternative scheduler. In any case I'm closing this issue as it's not a bug report or feature request.

**Closed by timrae** 2018-07-26 00:56 UTC
