### ISSUE TITLE
Automatic display answer funcion. How change default behaviour?

### ISSUE THREAD

**Issue by dzida16** [ankidroid/Anki-Android#4787] opened 2018-02-12 07:26 UTC
Hi. I'm verry glad to use an automatic display answer function but I have a problem with it :( 
After showing the answer without choose any option like"AGAIN" or "HARD" or "GOOD" or "EASY" the AnkiMobile always choose AGAIN as a default choose. 
It is useless for me due to save my time I have to learn during my housework. If or Where can I change default behaviour for automatic display answering without touching a mobilephone screen ? For instance I want to change default behaviour after displayed the answer from AGAIN to "GOOD" during my dishwashing :) or car maintenance . I often got wet or dirty fingers  and I will break my phone by  choosing a GOOD as a answer. 
Regards 

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by mikehardy** [comment] 2018-03-09 16:59
Hello! I can see how this would be useful. Anki Desktop doesn't support an option like this, and since AnkiDroid has the goal of mirroring Anki Desktop functionality I would propose this to the @dae from the Anki Desktop team. If they are interested and implement it, we can mirror it here.

I will mention that as a workaround several people seem to enjoy success using a wired headset with volume buttons remapped to different answer buttons. This may sound silly, but with some saran warp on the buttons themselves, you can protect them and your phone by using the buttons in this manner and learn things even with dirty hands. The process was documented here and appears to work with the free/demo version of the app mentioned: https://github.com/ankidroid/Anki-Android/issues/3021#issuecomment-160243369

@timrae as a feature request for a feature that isn't implemented in Anki Desktop this can likely be closed?

**Comment by timrae** [comment] 2018-05-14 06:48
Closing as duplicate of #2609

**Closed by timrae** 2018-05-14 06:48 UTC
Labels: duplicate
