### ISSUE TITLE
The "add note" button in card browser disappears after searching for a card

### ISSUE THREAD

**Issue by aemethyst** [ankidroid/Anki-Android#4611] opened 2017-03-21 04:57 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. I clicked on card browser and searched for a card under all decks 
2. Pressed the back button 
3. The little plus sign disappears. But it re-appears if I open and close the left hand side menu.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.2

Android Version = 6.0.1

ACRA UUID = da2d2c67-42f6-46c4-b11d-669231a6ff7b

**Comment by timrae** [comment] 2017-03-21 06:13
Duplicate of #4579 and already fixed in the latest alpha
https://github.com/ankidroid/Anki-Android/releases

**Closed by timrae** 2017-03-21 06:13 UTC
