### ISSUE TITLE
Browser Layout. Edit preview.

### ISSUE THREAD

**Issue by wondrousweeb** [ankidroid/Anki-Android#8749] opened 2021-05-01 16:18 UTC
It's a bit difficult to navigate around the Browse section. I'd suggest implementing a swipe navigating feature, in which you swipe left to open the decks, and then after selecting them, you have the cards from that Deck. (Reference can be taken from Android's Discord swipe navigation.
More than that is the editing. When I'm editing, I want to see how I'm going to see it, without needing to preview it. 
e.g, 
![image](https://user-images.githubusercontent.com/70597482/116788344-7ba94400-aac2-11eb-8c79-06841b9ed5bc.png)
I don't want to see all of that HTML stuff, I want to see this:
![image](https://user-images.githubusercontent.com/70597482/116788357-88c63300-aac2-11eb-9579-3191414afe14.png)
 
I hope you get my point. These are not major turnoffs, but they make me flag the card, and edit it on my laptop later. 

Other than that, awesome work on this app.

**Comment by mikehardy** [comment] 2021-06-30 14:17
Duplicate of enhancement request for WYSIWYG editor which is in progress #9048

**Closed by mikehardy** 2021-06-30 14:17 UTC
