### ISSUE TITLE
[Bug] Review not working with keyboard

### ISSUE THREAD

**Issue by MarkusJLechner** [ankidroid/Anki-Android#8636] opened 2021-04-17 08:40 UTC
###### Reproduction Steps

~~1. Press shift + v~~
2. Press Space / 1 / 2 / 3 / 4

~~Must not be in active record/play state. It's enough that the record options are visible~~

Edit: Review with keyboard is not working independent to the recording

###### Expected Result
Corresponding review action 

###### Actual Result
No recognition of review buttons

I'm using the 2.15 alpha 43

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

AnkiDroid Version = 2.15alpha43

Android Version = 11

Manufacturer = OnePlus

Model = IN2023

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; IN2023 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.66 Mobile Safari/537.36

ACRA UUID = ed0ca8ca-f925-4399-a89a-409ede3efc4c

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by dorrin-sot** [comment] 2021-04-18 06:57
Can I work on this? if so do you know what was the latest version this feature worked on?

**Comment by david-allison-1** [comment] 2021-04-18 15:01
Duplicate of #8572, to be fixed in #8527

**Closed by david-allison-1** 2021-04-18 15:01 UTC

**Comment by dorrin-sot** [comment] 2021-04-18 15:11
@david-allison-1 but isn't this about keyboard shortcuts as in pressing 1 passes in `EASE_1`, 2 passes `EASE_2` and so on?

**Comment by david-allison-1** [comment] 2021-04-18 15:20
> @david-allison-1 but isn't this about keyboard shortcuts not working? as in pressing 1 passes in `EASE_1`, 2 passes `EASE_2` and so on.

The issue is with executeCommand which both gestures and keyboard shortcuts use
