### ISSUE TITLE
Automatically Play Videos

### ISSUE THREAD

**Issue by SandyBubbles23** [ankidroid/Anki-Android#15830] opened 2024-03-10 03:25 UTC
Love the new update. Very nice look. However, in the past, videos would automatically play when a card was displayed. Now I have to push play, which slows me down and breaks my rythym. I've looked in all the settings and can't find a way to return it to automatically play videos. It would be nice to give users the option to control whether or not they want videos to play automatically. Thanks!

**Comment by josephShokry** [comment] 2024-03-10 07:57
I would like to try solving this issue, please assign it to me.

**Comment by david-allison** [comment] 2024-03-10 11:16
Thanks for the report!

Closing this as a duplicate of https://github.com/ankidroid/Anki-Android/issues/14693

* https://github.com/ankidroid/Anki-Android/issues/14693

**Closed by david-allison** 2024-03-10 11:16 UTC
