### ISSUE TITLE
After 2.17.1 (i.e. in the 2.17.3 and 2.17.4 versions) the One by one cloze cards are malfunctioning..

### ISSUE THREAD

**Issue by QuietBasil** [ankidroid/Anki-Android#15795] opened 2024-03-06 15:08 UTC
###### Reproduction Steps
Since v2.17.3
1. Using the anking note types 
2. Using the one by one cloze deletion type cards
3. The answer side shows the answer without hiding the answers in one by one manner.

###### Debug info

I did not install back to 2.17.3 because it's not working so
The debug info for the 2.17.1 version is:

AnkiDroid Version = 2.17.1 (dd2f3762fb214f9dd51162b215974b23cc809713)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = samsung

Model = SM-F926B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-F926B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Safari/537.36

ACRA UUID = 115b9fc8-1271-4f1d-a42b-2830540eb9d9

Crash Reports Enabled = true
 
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-03-06 15:35
Thanks for the report! Already fixed in `main` and will be fixed in 2.17.5

Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/15773
* https://github.com/ankidroid/Anki-Android/issues/15773

**Closed** 2024-03-06 15:35 UTC
Labels: Duplicate
