### ISSUE TITLE
New Congratulations Screen Increases Number of Clicks Unnecessarily

### ISSUE THREAD

**Issue by Rahey94** [ankidroid/Anki-Android#15846] opened 2024-03-10 22:40 UTC
Hi all,

I'm loving the new updates and the great work the team is doing on Ankidroid. The syncing is way faster and I haven't experienced any bugs. All in all, I'm loving it.

But there is one minor change I'm not a fan of that I wanted to share: Before, when you finished studying it would return you to the main screen with your deck list. Now, when you finish studying it presents you with a congratulations screen. I've attached a picture below.

This is somewhat annoying - for me the first thing I like to do after finishing studying is sync the decks, but since there is no sync button on this page it requires an extra click to get back to the home screen and sync.

I found the old behavior much better and smoother. If a congratulations message with info about custom studying needs to be shown, I think it would be better served as a disappearing popup (if my memory serves, this is how it was before). Or, having a sync button on the congratulations screen would work as well. The latter solution would be how it works in Anki desktop.

This is by no means a huge deal - even if the congratulations screen stays the way it is Ankidroid is a great app that I will continue using. Still, I thought I'd share my feedback.

Thanks!

![image](https://github.com/ankidroid/Anki-Android/assets/54212141/f9fefdc3-88ef-4f1d-96e4-6b2affa2a866)

**Comment by david-allison** [comment] 2024-03-10 22:49
Hi, thanks for the report!

Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/15349. I've already proposed a fix

* https://github.com/ankidroid/Anki-Android/issues/15349
* Fixed in https://github.com/ankidroid/Anki-Android/pull/15818

**Closed by david-allison** 2024-03-10 22:49 UTC

**Comment by Rahey94** [comment] 2024-03-10 22:58
Hey, great to hear this is already being worked on! My apologies for the duplicate post
