### ISSUE TITLE
feature request: 

### ISSUE THREAD

**Issue by lenkazbr** [ankidroid/Anki-Android#5111] opened 2018-11-09 09:37 UTC
Hello, 

I am a normal user of Anki without any knowledge of the code, so let me describe the feature that I miss with my own words. If you think that it is inappropriate, I can delete my request, but would appreciate if you tell me what I am supposed to do instead. 

I love Anki. In my opinion, it is the best flash cards app ever! However, I found two apps, that have something that I miss in Anki. 

Check these two apps:
https://play.google.com/store/apps/details?id=net.wordbit.deen
https://play.google.com/store/apps/details?id=co.unlockyourbrain&hl=gsw

The feature that I miss: showing the cards always on the LOCKED SCREEN. By this way, you are pushed to learn and you are exhibited to the vocabulary (in my case) that you are learning during the whole day, always when you unlock the mobile phone.

Do you think it is feasible to add this feature to Anki? I would really appreciate it a lot!

Lenka

**Comment by lenkazbr** [comment] 2018-11-09 09:40
By the way, now I see that I forgot to add the title, but I cannot edit it anymore... the edit function doesn't work somehow :/.

**Comment by mikehardy** [comment] 2018-11-09 13:33
Hi @lenkazbr - glad you love AnkiDroid so you much you want to see it more often :-)

This is a duplicate of #4709 though - read through the discussion there and you can see why we probably won't implement something *exactly* like this, but if someone wanted to create an interactive "notification" it could actually work almost exactly like the feature you requested, but without all the baggage required to replace an Android lock screen

**Closed by mikehardy** 2018-11-09 13:33 UTC

**Comment by lenkazbr** [comment] 2018-11-10 13:08
Hi @mikehardy, wow, I am impressed about all the ideas. I really appreciate that there is a community of people who are interested in this app so much. I recommend it to all of my friends as almost noone knows it! I only met one person in my life who had known the app before and he was also very surprised that he found another person using it.

Thanks for the reference to the other discussion thread. I am sorry for repeating the issue. I had tried to find the topic in the previous issues, but I didn't.

The notifications that you suggest are a good solution. I'd be happy to test it if you implement it!

**Comment by mikehardy** [comment] 2018-11-10 13:48
No worries about the duplicate, I'd rather have more feedback than less :-). I am also surprised it isn't more popular since the reviews are solid and it is like a superhero power for memory but I assume SRS just doesn't work the way some people like to work. That said, one of the best ways to contribute is word-of-mouth publicity like a comment on facebook or a blog post or something. That's how other people end up finding out about. And maybe we'll get a "lock screen learning" type solution implemented one of these days...
