### ISSUE TITLE
[Bug] V3 Scheduler: "Invalid input: card was modified" while answering card 

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#12946] opened 2022-12-10 03:36 UTC
###### Reproduction Steps
1. Start reviewing cards.
2. Click the show answer button.
3. Rate the card as good.

###### Expected Result
The next card is shown.

###### Actual Result
Sometimes, the following error is shown instead.

![IMG_20221210_085645](https://user-images.githubusercontent.com/92206575/206827159-90c069d2-087a-48ef-a5ed-5eb01e4112a0.jpg)

Note that this error occurs very rarely, maybe about once a week.

###### Debug info
AnkiDroid Version = 2.16alpha91

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment] 2022-12-10 06:10
The issue mostly occurs when I click "show answer", then edit the card and then rate the card. 
However, doing this doesn't cause the issue in most cases but only sometimes.

But today, I suppose that I didn't perform any action via the menus before answering the card.

**Comment by user1823** [comment] 2022-12-10 06:16
I think this can be confirmed from the error report generated by AnkiDroid.

**Comment by dae** [comment] 2022-12-10 06:29
The logs don't make this clear. Please keep an eye out for any actions you're taking around the time the problem occurs, as that will help to narrow it down.

To devs: I believe this happens because AnkiDroid is performing some operation on the database. The top of the review queue can then change (eg because a learning card has become due), but the reviewer still thinks the previous card is the current one. This will happen when an operation uses raw SQL, or was not invoked with undoableOp.

**Comment by user1823** [comment] 2022-12-11 11:18
This happened again.

I rated the card but nothing happened. Then, I rated the card again and I was shown the same error. When I dismissed the error, the next due card was shown.

And this time, I am sure that I didn't do anything via the menu.

**Comment by dae** [comment] 2022-12-12 04:48
If you see the same thing again, it may be worth looking up the card info of the card where nothing happened - I suspect it will show that the card was actually reviewed, and that the UI has failed to indicate it for some reason. Getting to the bottom of this may require adding some extra logging or digging through this part of the code. As some changes to this area will need to be made #12620, this may need to wait until someone has the time to pick that up.

**Comment by user1823** [comment] 2023-05-01 00:58
I have not seen this error message since a while. But, because this message used to appear on rare occasions, I can't be sure about whether this issue has been resolved or not.

**Comment by david-allison** [comment] 2023-05-01 09:29
It's not fixed. To be fixed in 2.17

**Comment by homocomputeris** [comment] 2023-06-11 21:23
I get this error but I don't see any logic behind, seems completely random:
![Screenshot_20230611-232107_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/7422433/538ffe95-9999-44cd-9413-c5501de2aabd)

**Comment by dae** [comment] 2023-09-01 06:24
We'll need reproduction steps to track this down. If it still occurs after a 2.17 alpha release, please let us know the steps we should take to trigger this.

**Comment by someone120** [comment] 2023-09-02 09:48
Sometimes I click the rate button and then the UI surface gets stuck. Then I click the rate button again, and I get this error.

**Comment by mikehardy** [comment] 2023-12-09 17:08
I'm going to move this off the 2.17 release milestone - not because we don't believe it is happening - but because it was already happening in 2.16 and I don't think it is a regression so it should not *block* a new public release

We'll try to fix it as soon as we have solid reproduction steps but we want to make sure all the other fixes we have queued up are released as quickly as possible so we don't want to block the release

**Comment by matejdro** [comment] 2023-12-09 17:11
For what it's worth, I've been experiencing those pretty frequently a couple of releases back, but since 2.16 (I think) and 2.17 alpha, I've not experiencing it anymore. So at least some cases were fixed.

**Comment by mikehardy** [comment] 2023-12-11 01:03
@david-allison indicates:

> Reproduced using the deck listed in: https://github.com/ankidroid/Anki-Android/issues/14920

https://github.com/ankidroid/Anki-Android/issues/14813#issuecomment-1848782337

I think that one is a duplicate so I'm closing it to focus here

**Comment by mikehardy** [comment] 2023-12-11 01:06
We're getting closer to a repro here I think - user `khonkhortisan` on discord posts this:

> 2.17alpha8+fsrs+gestures: I can tap on both sides of the screen to answer again-good or good-again and it says card was modified. I can do this reliably, if I wait half a second. Again-0.5s-good-cardwasmodified. or good-0.5s-again-cardwasmodified. but then I just tried it on another deck and got not at top of queue instead.

**Comment by homocomputeris** [comment] 2023-12-13 19:24
I noticed this usually happens when a card is being reviewed when today is cut off (e.g. at the midnight) during review. Then this carried over card casts the error.

**Comment by david-allison** [comment] 2023-12-13 23:59
Code ref for the above

https://github.com/ankitects/anki/blob/edd38ca06730d7fc16804f52ce10f6bc54c3d145/qt/aqt/main.py#L508-L528

**Comment by david-allison** [comment] 2023-12-23 11:44
There are at least 2 causes:

1. rollover
2. answering too quickly

* I'm going to make the following focus on rollover: #14090

Focusing on answering too quickly, this can be replicating by duplicating the line: `answerCardInner(ease)`

https://github.com/ankidroid/Anki-Android/blob/5425cc688f70b30e291a5f5b60fefd48ed09cd1a/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt#L915-L934

@BrayanDSO is fixing this likely going to get in the way of your refactors in the area?

**Comment by BrayanDSO** [comment] 2023-12-23 12:01
> @BrayanDSO is fixing this likely going to get in the way of your refactors in the area?

Nope. I don't care much to what happens to the AbstractFlashcardViewer/Reviewer/Previewer/CardTemplatePreviewer since I'm doing a re-write to implement #14302

**Comment by andreas1974** [comment] 2024-01-16 07:18
Ver. 2.17 alpha 15.
(anki 23.12.1 / 1a1d4d54)

Answering the first card this morning I got the error message that is described here. I was not answering this card quickly. I don't understand the "start of next day"/rollover" issue that people mention and link to above. 

Perhaps it is of no help, since you already know about it, but I thought I'd report this error.
![image](https://github.com/ankidroid/Anki-Android/assets/998258/86864067-ac0f-440b-ba2f-0e8bcababa91)

(Off topic: I installed the alpha version yesterday, and since then I've had no "check you internet" popups, which I'm very thankful for, since I'm often offline when using Anki!)

**Closed** 2024-01-26 05:54 UTC
Labels: Bug, Backend Related

**Comment by andreas1974** [comment] 2024-03-14 07:57
I installed AnkiDroid 2.17.5 and I still get this "card modified" error when leaving a card open overnight (unrated) and rate it in the morning.
The issue is marked as closed, but I still get the same error. 
It was also marked as "moved to Done in 2.17 - [Rust Backend Migration on Jan 26](https://github.com/orgs/ankidroid/projects/2)"
So I'm not sure I'm writing on the correct issue now.

_Version data copied from the about page:_
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)
Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)
Android Version = 9 (SDK 28)
ProductFlavor = full
Manufacturer = LGE
Model = LG-H930
Hardware = joan
Webview User Agent = Mozilla/5.0 (Linux; Android 9; LG-H930 Build/PKQ1.190414.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.210 Mobile Safari/537.36
Crash Reports Enabled = true

![Screenshot_20240314-082100](https://github.com/ankidroid/Anki-Android/assets/998258/db43b239-8e98-46f5-9cb2-0e0a99371a92)
