### ISSUE TITLE
View cards in deck from Decks popup screen

### ISSUE THREAD

**Issue by winstoncooke** [ankidroid/Anki-Android#10682] opened 2022-04-02 15:14 UTC
**Is your feature request related to a problem? Please describe.**
I've found when I'm making a lot of cards for decks at once, I often want to go back and modify a card I've just created. Intuitively, I long press on the deck name and expect to see a "View cards in deck" option in the popup screen that would take me to the Card browser for that deck. Instead, I have to back out of the popup, open the side menu, select 'Card browser', and then switch to the deck that I want at the top of the screen.

**Describe the solution you'd like**
Long pressing on a deck name in the decks screen brings up an option to jump straight to the Card browser for that deck.
Optionally, there could also be a similar button in the 3 dots menu in the top right when studying a deck.

**Describe alternatives you've considered**
Nothing I can think of.

**Additional context**
![Screenshot_20220402-095350_AnkiDroid](https://user-images.githubusercontent.com/71997294/161389639-f3209ed4-01cd-4a9e-b5e1-c2653fc58550.jpg)

**Comment by david-allison** [comment] 2022-04-02 15:30
Thanks for the report!!

Duplicate of https://github.com/ankidroid/Anki-Android/issues/8187. Already implemented in 2.16.

**Closed by david-allison** 2022-04-02 15:30 UTC
