### ISSUE TITLE
Custom study: Don't show "increase new card limit" when no new cards

### ISSUE THREAD

**Issue by rillig** [ankidroid/Anki-Android#4759] opened 2017-12-17 23:05 UTC
###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. On the main screen, long-press a deck and select "User-defined learning"

###### Expected Result

If there are 0 "new cards", the menu item "Increase limit for new cards" is not shown.

###### Actual Result

The menu item "Increase limit for new cards" is shown even when it doesn't make sense.

**Comment by mikehardy** [comment] 2017-12-19 04:20
Just a guess but looks to implement this, need to get the Deck being worked on ([similar to this](https://github.com/ankidroid/Anki-Android/blob/e6eb737a400a34ce8e9d2268e0b1566d7a2119d9/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java#L439), but looking for new cards or not, not the name)

And then use that information to filter the options you populate the dialog with here:
https://github.com/ankidroid/Anki-Android/blob/e6eb737a400a34ce8e9d2268e0b1566d7a2119d9/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CustomStudyDialog.java#L342-L371

**Comment by david-allison-1** [comment] 2020-06-03 07:49
Let's keep this for another few months. Would be good to get to grips with the project

**Comment by 4D17Y4** [comment] 2021-03-24 18:35
Hey, I'd like to work on this one. 
I have gone through the issue and noticed that the mentioned settings in the issue is migrated to `custom study -> modify today's new card limit.`
I can work on this as my first issue if this still needs help.

**Comment by david-allison-1** [comment] 2021-03-24 18:38
Sounds great, thanks!!

**Comment by mikehardy** [comment] 2021-04-01 22:28
Fixed after only ... 3 years hahah :-), will be in the next alpha :rocket:

**Closed** 2021-04-01 22:27 UTC
Labels: Accepted, Anki Ecosystem Compatibility, Enhancement, Good First Issue!, Help Wanted, Keep Open, Priority-Low
