### ISSUE TITLE
[Bug] All toasts are unreadable in night mode

### ISSUE THREAD

**Issue by elliotcathcart** [ankidroid/Anki-Android#13051] opened 2023-01-02 01:03 UTC
###### Reproduction Steps

1.  Enable night mode
2.  Perform any action that triggers a toast e.g. settings -> advanced -> about -> copy debug info

###### Actual Result
Unreadable toasts. It looks like the text color is almost identical to the toast background color. 

<img src="https://user-images.githubusercontent.com/55717501/210188898-b082d6f5-b1ba-47db-b3c3-1971461dc980.png" width="280">

<img src="https://user-images.githubusercontent.com/55717501/210188910-cc754c85-5d2e-40cd-98fe-353fe9fb55c4.png" width="280">

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 13

Manufacturer = Google

Model = Pixel 6

Hardware = oriole

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6 Build/TQ1A.221205.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = 0b366c7c-3869-4b7e-9141-34b90a1b5145

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Edit: I see some other apps reporting this same issue. 
I have repeated this bug on another Pixel 6 device. 
When I run Ankidroid on the emulator the toasts have a dark background.

**Comment by Jack8861** [comment] 2023-01-02 13:57
Can I look into it? This looks like a good first issue.

**Comment by Jack8861** [comment] 2023-01-02 14:45
I am not able to replicate the issue using the repo, it seems the "night mode" option is only available on the app available on playstore but even then the toasts where working fine. I'm gonna try with the pixel 6 itself and see....

**Comment by Aayush2111** [comment] 2023-01-02 15:35
Works fine for me aswell!
_device: redmi note 9 pro
android version: 11
ankidroid 2.16alpha92 _

**Comment by elliotcathcart** [comment] 2023-01-02 15:39
I forked the repo. I ran the Alpha version on both the emulated Pixel 6 and on a physical Pixel 6.  

On both devices the toast for "copy debug info" now has a dark background and the text is readable. This one is fixed. 

<img src="https://user-images.githubusercontent.com/55717501/210252806-dba7de2b-30aa-4d56-ab13-1cb149ce6e80.png" width="280">

However other toasts still have the light background. E.g. when creating a new deck. 

Physical device:
<img src="https://user-images.githubusercontent.com/55717501/210252578-e8cfd02a-c3d7-46a9-90dd-0476d32aeef1.png" width="280">
If you zoom in you can see the text is there, so it's a color issue. 

Emulated device:
<img src="https://user-images.githubusercontent.com/55717501/210252452-2f02a4d6-eb51-4c3d-8894-56a4a16c342e.png" width="280">

**Comment by elliotcathcart** [comment] 2023-01-02 15:41
> it seems the "night mode" option is only available on the app available on playstore

you should be able to set it via settings -> appearance -> theme -> black

**Comment by Jack8861** [comment] 2023-01-02 23:46
@elliotcathcart , Can you specify which API level you have used for the AVD? I tried to use 31 and 33 (highest), but ran into some incompatibility issue which terminated it during lunching the AVD. 

**android studio log:**
2023-01-03 05:11:06,770 [132636258]   INFO -       Emulator: Pixel 6 API 31 - C:\Users\jackn\AppData\Local\Android\Sdk\emulator\emulator.exe -netdelay none -netspeed full -avd Pixel_6_API_31 -qt-hide-window -grpc-use-token -idle-grpc-timeout 300 
2023-01-03 05:11:06,893 [132636381]   INFO -       Emulator: Pixel 6 API 31 - Android emulator version 31.3.14.0 (build_id 9322596) (CL:N/A) 
2023-01-03 05:11:06,893 [132636381]   INFO -       Emulator: Pixel 6 API 31 - emulator: INFO: Found systemPath C:\Users\jackn\AppData\Local\Android\Sdk\system-images\android-33\google_apis\arm64-v8a\ 
2023-01-03 05:11:06,908 [132636396]   INFO -       Emulator: Pixel 6 API 31 - PANIC: Avd's CPU Architecture 'arm64' is not supported by the QEMU2 emulator on x86_64 host. 
2023-01-03 05:11:06,912 [132636400]   INFO -       Emulator: Pixel 6 API 31 - Process finished with exit code 1

**Comment by elliotcathcart** [comment] 2023-01-03 00:03
Yeah it's API level 33 as I'm running android 13. 

This seems like an incompatibility with your hardware, but I'm not sure. I have no issues running this version on my machine.

I don't see much info about this error except this  https://stackoverflow.com/questions/74760054/panic-avds-cpu-architecture-arm64-is-not-supported-by-the-qemu2-emulator-on

**Comment by elliotcathcart** [comment] 2023-01-03 02:04
Confirming that the bug is _not_ specific to Pixel 6. Replicated using Alpha build on an emulated Pixel 5 (Android 13 / API level 33).

**Comment by tommik60fps** [comment] 2023-01-08 21:46
Hi, I can confirm that this issue is related to upgrading from Android 12 to 13. Since I upgraded yesterday no more readable pop-up messages, just those white bubbles. I am on Zenfone 9.

**Comment by BrayanDSO** [comment] 2023-01-09 10:11
Can't reproduce on my phone (Samsung, Android 13, One UI 5)

**Comment by rahul-gill** [comment] 2023-01-09 13:59
This is probably [issue only with stock android 13](https://issuetracker.google.com/issues/245108402). Toasts look fine on my phone(Samsung, Android 13, One UI 5) and api 30 emulator but are white on white on api 33 emulator

**Comment by BrayanDSO** [comment] 2023-01-11 18:06
> This is probably [issue only with stock android 13](https://issuetracker.google.com/issues/245108402). Toasts look fine on my phone(Samsung, Android 13, One UI 5) and api 30 emulator but are white on white on api 33 emulator

Nice. Thanks! Seems an Android issue then

**Comment by elliotcathcart** [comment] 2023-01-11 18:09
That wouldn't explain why the copy debug info toast has been fixed in the alpha build though

**Comment by BrayanDSO** [comment] 2023-01-11 18:10
> That wouldn't explain why the copy debug info toast has been fixed in the alpha build though

Now it is a snackbar, not a toast

**Comment by elliotcathcart** [comment] 2023-01-11 18:12
Ah yes, so it is. 

So why is the toast issue only occuring on certain apps? In other apps dark toasts work fine

**Comment by rahul-gill** [comment] 2023-01-11 18:27
[this is why](https://issuetracker.google.com/issues/245108402#comment6) probably

**Comment by elliotcathcart** [comment] 2023-01-11 18:28
> [this is why](https://issuetracker.google.com/issues/245108402#comment6) probably

The person who reported that issue also found a fix for it though

https://github.com/billthefarmer/gurgle/commit/e8be1a03d8489904f431898454b0eb381ddf11c0

**Comment by OneSidedPrism** [comment] 2023-03-03 14:49
Chiming in here to echo that I'm also having the same issue on my Pixel 6 Pro running Android 13 and the latest stable build from the play store. I didn't test all the toasts/snackbars but noticed it specifically on "Card marked as leech”

**Comment by david-allison** [comment] 2023-03-03 15:13
Thanks for the report!

According to the issue in the Google issue tracker, this will be fixed in #13261 when we bump `targetSdkVersion` to 30.

I can't reproduce this on my S21

**Closed** 2023-03-20 17:45 UTC
