### ISSUE TITLE
Feature request: ignore card by tag

### ISSUE THREAD

**Issue by p4nix** [ankidroid/Anki-Android#6354] opened 2020-06-04 09:47 UTC
In combination with the feature request for reviewing with the screen turned off (#6353 ), the idea came to me that tags could also be used to exclude cards from the reviewing queue using AnkiDroid normally.

This behaviour can currently be done via filtered decks, but not everyone likes setting them up and cluttering the home screen with them, also they have to be enabled and disabled all the time.

With a tag to exclude certain cards (or flags) from being reviewed (because they have unwanted sound, require pen&paper which is not possible on the go, whatever) filtered decks could be circumvented.

I'm not sure what should happen to those cards once you finished the queue and if they should be included in the numbers to review (maybe there is a space for a new number signalling the amount of non-mobile cards on the deck overview?).

Just a small idea, open for discussion or being turned down :)

**Comment by david-allison-1** [comment] 2020-06-04 09:56
I'd like to see it. Duplicate of #1151

**Closed by david-allison-1** 2020-06-04 09:56 UTC
