### ISSUE TITLE
[BUG]: Very slow stylus recognition when writing Chinese characters

### ISSUE THREAD

**Issue by MarkoSchuetz** [ankidroid/Anki-Android#16720] opened 2024-07-11 12:17 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Open Ankidroid on Android
Open e.g. xiehanzi's HSK1 deck
Write the strokes on the back of the card quickly

### Expected behaviour

All strokes are recognized, no strokes are lost.

### Actual behaviour

Sometimes a stroke seems to get stuck, i.e. it shows partially, but does not recognize. At other times the stroke does not show at all.

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 12 (SDK 31)

ProductFlavor = play

Manufacturer = HUAWEI

Model = MRX-W09

Hardware = kirin990

Webview User Agent = Mozilla/5.0 (Linux; Android 12; MRX-W09 Build/HUAWEIMRX-W09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Safari/537.36

ACRA UUID = db1a9ee1-19b1-431c-b9f2-9b663c2ab591

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2024-07-12 18:51
Are you using the `Whiteboard` feature of the reviewer, or is this a feature of the notetype of your cards?

**Comment by BrayanDSO** [comment] 2024-09-01 11:45
I'll close this as `Can't reproduce`

**Closed by BrayanDSO** 2024-09-01 11:45 UTC
Labels: Bug, Needs Triage

**Comment by MarkoSchuetz** [comment] 2024-09-01 14:10
it's not in the whiteboard: the whiteboard is actually very responsive which looks to me like this should not be very difficult to fix. I don't know whether this has to do with the note-type of the card, honestly  I'm just now reading about Anki note-types. So, thanks for that hint.

**Comment by BrayanDSO** [comment] 2024-09-01 17:16
Some chinese/japanese notetypes have a feature like that for checking the stroke order, so I suspect that the problem should be there
