### ISSUE TITLE
[BUG]: Card zooms in sometimes when viewing another app, going to the window manager, then back to Ankidroid.

### ISSUE THREAD

**Issue by johncaiwa** [ankidroid/Anki-Android#15978] opened 2024-03-23 12:31 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Review cards on Anki.

Go to another app.

In the window manager, go back to AnkiDroid.

(Doesn't always happen. More often than not it works normally.)

### Expected behaviour

See the card, resume studying.

### Actual behaviour

The card will appear all white. However, if you pinch to zoom in, then scroll up, you can kind of see it. It won't let you go to the very top of the card, though.

Has been an issue since at least 2.16.

![Screenshot_20240323-144217_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/141907143/c143f6b3-389d-40ca-886c-2b96dfb1d877)
![Screenshot_20240323-144235_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/141907143/9b571b07-df12-4f70-aaaa-3f5b34045973)

Screenshot 1 is how it appears when I go back to AnkiDroid.

Screenshot 2 is after pinching to zoom in, then scrolling up as far as I can.

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 9 (SDK 28)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G950U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-G950U1 Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = da9640d8-ffbd-45dd-9936-35e01980164d

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2024-05-11 10:03
Closing as can't reproduce

**Closed by BrayanDSO** 2024-05-11 10:03 UTC
Labels: Bug, Can't reproduce, Needs Triage
