### ISSUE TITLE
Typed answer comparison ignores combining characters

### ISSUE THREAD

**Issue by bkhl** [ankidroid/Anki-Android#4695] opened 2017-09-04 08:27 UTC
###### Research

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Create a card with a typed answer, where the correct answer contains some combining marks, in my case a Thai syllable such as เบียร์ ("beer")
2a. Type in an answer with missing combining marks
2b. Type in an answer with additional combining marks
3. Press button to show answer

###### Expected Result

1. Character position to be marked as failed if combining character is missing.
2. Character position to be marked as failed if there are extraneous combining characters.

###### Actual Result

1. Character position is marked as correct as long as "main" character is correct:

![image](https://user-images.githubusercontent.com/34634/30017543-ddb97c5c-9183-11e7-80b4-e17b5e4a6ca3.png)

2. Character position is marked as failed even if there are extra combining marks:

![image](https://user-images.githubusercontent.com/34634/30017727-7b57acc2-9184-11e7-8366-c39fd12ae337.png)

(The latter page also shows a rendering error, but that may be due to my styling having insufficient line height. Not part of this issue.)

Note: Not expecting the individual combining marks to be highlighted, doubt that's possible with CSS.

###### Debug info

AnkiDroid Version = 2.8.2

Android Version = 7.1.1

ACRA UUID = ee4c1a7d-71f7-4262-b2af-abc09b8336c7

**Comment by mikehardy** [comment] 2018-10-07 06:28
Marking this as a duplicate of #4821 because it's the same issue and I've put more information there.

**Closed by mikehardy** 2018-10-07 06:28 UTC
Labels: Priority-Medium, bug

**Comment by bkhl** [comment] 2018-10-07 07:35
This is similar to #4821 which focuses on Russian, which as I understand it uses diacritics in a way similar to Latin alphabets.

Here I'm talking about Thai (and other similar Indic scripts), where the ideal behaviour would be somewhat different. The modifying characters are effectively separate graphemes.

If it's difficult to highlight only the incorrect diacritic/vowel mark/tone mark/&c. maybe a different colour (orange?) could be used to indicate the main character in the box is correct, but the modifying character wrong?
