### ISSUE TITLE
[BUG]: Toggle Cards/Notes

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#16130] opened 2024-04-08 04:12 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Go to CardBrowser
2. From menu select options
3. Click on notes ( radio button )

### Anki
![WhatsApp Image 2024-04-08 at 7 53 52 AM](https://github.com/ankidroid/Anki-Android/assets/65113071/d94c2907-8c09-498f-a395-5045abc3d418)

### Actual behaviour

Toggle Cards/Notes not working

https://github.com/ankidroid/Anki-Android/assets/65113071/4819b192-b50f-4c84-8b57-023c987b5187

### Debug info

```text
AnkiDroid Version = 2.18alpha8-debug (814e9f58a0d27e2ec1d70abf0426468987f34aa1)

Backend Version = 0.1.36-anki24.04 (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.40 Mobile Safari/537.36

ACRA UUID = 460992b3-5f47-4ddc-9022-06285543c5f4

FSRS Enabled = false

Crash Reports Enabled = false
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-04-08 13:12
Don't they all have one card?

**Comment by SanjaySargam** [comment] 2024-04-08 13:36
![IMG_20240408_190621.jpg](https://github.com/ankidroid/Anki-Android/assets/65113071/93ce6f59-a1bd-436e-b849-f95e5d4e8e1d)

**Comment by david-allison** [comment] 2024-04-13 02:29
@SanjaySargam Could you provide a zipped export?

**Comment by david-allison** [comment] 2024-04-13 15:58
@SanjaySargam what's the issue?

![Screenshot 2024-04-13 at 16 58 11](https://github.com/ankidroid/Anki-Android/assets/62114487/28b80aeb-16a7-41b7-beed-8bf5ca5dfa32)

![Screenshot 2024-04-13 at 16 58 04](https://github.com/ankidroid/Anki-Android/assets/62114487/b9f30852-fd9a-4db5-a63d-76c6bb081612)

**Comment by SanjaySargam** [comment] 2024-04-13 16:00
Check this behaviour in AnkiDroid

**Comment by david-allison** [comment] 2024-04-13 16:07
![Screenshot 2024-04-13 at 17 05 47](https://github.com/ankidroid/Anki-Android/assets/62114487/c087db5b-83f2-4cf4-9c14-81df3b8418aa)

![Screenshot 2024-04-13 at 17 05 36](https://github.com/ankidroid/Anki-Android/assets/62114487/b55ab8a7-3f10-49d2-84ea-0049148a3b92)

![Screenshot 2024-04-13 at 17 06 53](https://github.com/ankidroid/Anki-Android/assets/62114487/1d3888cf-dacd-43b9-8374-db49a0ad8de0)

Seems fine, just a different representation of the data

**Comment by david-allison** [comment] 2024-04-13 16:08
Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/11889 - we're nearly around to redoing this functionality

* https://github.com/ankidroid/Anki-Android/issues/11889

**Closed by david-allison** 2024-04-13 16:08 UTC
Labels: Bug, Card Browser
