### ISSUE TITLE
[BUG] Cursor has too little contrast

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15395] opened 2024-02-03 12:49 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Enable Black theme
- Long press a deck and select `Rename deck`.

### Expected behaviour

The cursor has a reasonable level of contrast like that in the following images:
<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/e90c2f82-39b2-44ca-b926-f3e2741128d8">
<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/92b8a95d-a6f4-4515-a35b-e8648cb80fe8">
(Ignore the absence of the cursor in the lower box of the second screenshot. It was not captured because it is blinking.)

### Actual behaviour

The contrast is almost non-existent.
<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/2d02dc8e-80db-486c-b4a3-4b59eed487f6">

### Debug info

```text
2.17beta1
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment] 2024-02-04 04:01
Working on it

**Comment by SanjaySargam** [comment] 2024-02-06 16:31
This was introduced due to #15333

**Comment by mikehardy** [comment] 2024-02-28 16:31
@SanjaySargam I don't see a PR attached to this and it has been approximately a month, but this is currently tagged for 2.17 fix releases which have a cadence of one every couple days. Are you still working on this? If not we need to unassign and re-label as help wanted. Thanks

**Comment by SanjaySargam** [comment] 2024-02-28 19:23
Hey @mikehardy, this is not reproducible in latest alpha 2.18alpha2
The cursor color is visible as expected

**Comment by user1823** [comment] 2024-02-29 02:40
Yes, the cursor is visible now.

However, there is a new minor issue. There is a halo around the cursor pointer (I don't know if it has a better name) that doesn't look good.

<img width=200 src="https://github.com/ankidroid/Anki-Android/assets/92206575/0cb4156f-e432-4188-b681-cf13a70dbb93">

**Comment by mikehardy** [comment] 2024-02-29 03:25
If there were no "halo" ("area of occlusion" ?? Not sure what you'd call that) then it would be possible to complain that you can't see the cursor indicator well because it blends in with the text bounding box. I'm going to say that for me at least, this does actually look good, at the very least "good enough"

**Comment by user1823** [comment] 2024-02-29 03:37
The probable reason it doesn't look good to me is that no other app shows such halo around the cursor indicator.

For example, see the following screenshots:

WhatsApp:
<img width=200 src="https://github.com/ankidroid/Anki-Android/assets/92206575/690db96c-dd53-48b2-95e2-ceed90c6acac">
Browser:
<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/e90c2f82-39b2-44ca-b926-f3e2741128d8">

> it would be possible to complain that you can't see the cursor indicator well because it blends in with the text bounding box

I don't think that because the cursor pointer is much larger than the border thickness.

**Comment by SanjaySargam** [comment] 2024-02-29 04:21
I agree with mikehardy.

**Comment by david-allison** [comment] 2024-02-29 06:30
How did it look previously [2.16.5], and can we revert to that?

**Comment by user1823** [comment] 2024-02-29 06:37
2.16.5:
<img width=250 src="https://github.com/ankidroid/Anki-Android/assets/92206575/6d90f503-033f-4ecb-8e3e-498fe793e058">

**Comment by david-allison** [comment] 2024-02-29 06:40
That looks good to me. We'll close the issue once it looks as it used to.

**Comment by snowtimeglass** [comment] 2024-02-29 11:03
The "area of occlusion" ("halo") doesn't occur on "Edit note" screen, so it seems an issue from a consistency viewpoint, too.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/ef840991-5ff7-44a0-81b9-3a8ccc44ecd4)

Also, the whole shape of the area seems not so much "good-enough looking halo" as "bare block".


![image](https://github.com/ankidroid/Anki-Android/assets/10436072/44c78b82-cddf-4df2-8829-051ed4d54654)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/f05beaef-1a75-4171-8979-9f6adc84dd5d)

**Comment by david-allison** [comment] 2024-02-29 11:30
I suspect either:
* transparent background is not being set
* An override is put in place

This is probably the same cause as: 0d238508f5b81dc72a5dd089a6577bcad3e5138a

**Comment by david-allison** [comment] 2024-02-29 15:26
This may be fixed by https://github.com/ankidroid/Anki-Android/pull/15719

**Closed** 2024-03-07 04:30 UTC
Labels: Bug, UI
