### ISSUE TITLE
[Bug] Floating action button goes up after tapping "Create deck"

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#11019] opened 2022-04-22 09:10 UTC
###### Reproduction Steps

1. Tap the floating action button
2. Tap create deck

<details><summary>Demo video</summary>

https://user-images.githubusercontent.com/69634269/164675025-0362e7cb-e18a-4261-a0e9-9f4de2e2f63a.mp4

</details>

###### Expected Result

The FAB stays on its place

###### Actual Result

The FAB goes up

###### Debug info
```
AnkiDroid Version = 2.16alpha61

Android Version = 12

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-N770F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.88 Mobile Safari/537.36

ACRA UUID = 6f89106f-1072-4e27-981d-9966c4a55c5f

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

![image](https://user-images.githubusercontent.com/69634269/164675300-0e9341d8-eb93-4209-9a4a-8630c69e2aa7.png)

**Comment by mikehardy** [comment] 2022-04-22 12:36
What, you don't like our custom FAB bounce animation?

**Comment by BrayanDSO** [comment] 2022-04-22 13:29
See the position of the FAB on the screenshot attached, it shouldn't go that high

**Comment by mikehardy** [comment] 2022-04-22 14:38
Hahaha I was totally joking - it does look ridiculous, good find

**Comment by BrayanDSO** [comment] 2022-04-22 15:57
lol, I just thought:

![my reaction](https://media.giphy.com/media/S4AVBFpmuV16pbpwb9/giphy.gif)

"Maybe he haven't seen the screenshot?". That's part of the whole async, online, text communication. You got me this time

**Comment by HuWeiyy** [comment] 2022-04-24 16:19
I think this bug is interesting.May I assign this?

**Comment by HuWeiyy** [comment] 2022-04-24 17:57
![4TOVDIT1B4H3G2O_PGGMMP1](https://user-images.githubusercontent.com/92869272/164989875-4a951995-b524-4092-8b83-1fac50fe21d9.png)
![2U~((RMGWW )0FEM7MOMFZY](https://user-images.githubusercontent.com/92869272/164989877-49f0b9c6-6b21-446f-99f0-1c5ffcb3d75d.png)

**Comment by winstoncooke** [comment] 2022-04-26 19:29
This looks similar to #10854. I think a similar solution would be in order.

**Comment by BrayanDSO** [comment] 2022-05-01 14:34
I noticed I can't reproduce this anymore in 2.16alpha63. Maybe one of the recent changes on the FAB solved it somehow

**Comment by mikehardy** [comment] 2022-05-01 14:50
Strange - if you are the initial reporter and cannot reproduce please close though, keep things tidy :-)

**Closed** 2022-05-01 15:03 UTC
