### ISSUE TITLE
Show based on notes error

### ISSUE THREAD

**Issue by BEST8OY** [ankidroid/Anki-Android#14668] opened 2023-11-05 09:37 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Import this .apkg
[Cards-20231105125348.zip](https://github.com/ankidroid/Anki-Android/files/13259166/Cards-20231105125348.zip)
2. Go to card browser
3. Tap on 3 dots and choose Options
4. Choose Notes and then tap OK
5. You'll face an error

### Expected behaviour

Should not happen.

### Actual behaviour

Well this happens.
![image](https://github.com/ankidroid/Anki-Android/assets/70865987/34f84ea0-871f-4cd1-94c7-57592958348e)

### Debug info

```text
AnkiDroid Version = 2.17alpha3 (42a8c8c55c200f372b0bd0b462e4b58554b72fe5)

Android Version = 13

ProductFlavor = full

Manufacturer = Xiaomi

Model = Mi 9 Lite

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Mi 9 Lite Build/TQ3A.230901.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.123 Mobile Safari/537.36

ACRA UUID = 2d4473c6-c308-41cf-a884-64d4323e9ba6

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment] 2023-11-05 17:07
Duplicate of #14623 
This will be fixed starting with 2.17.alpha4.

**Closed by lukstbit** 2023-11-05 17:07 UTC
Labels: Bug, Needs Triage
