### ISSUE TITLE
Card template editor: reposition a card type

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#16787] opened 2024-07-28 00:31 UTC
In Anki, in the card template editor, you can move a card type to another position. It would be nice to have the same feature in ankidroid.
You can imitate the anki implementation, with the same dialog requesting a number between 1 and the number of card.
Or, if another maintainer agree, you can try to have something more beautiful such as showing the list of name of card types, as we do with the list of field.
But honestly, just imitating Anki implementation would be a good quick first solution

**Comment by david-allison** [comment] 2024-07-28 01:00
Duplicate of https://github.com/ankidroid/Anki-Android/issues/6017

**Closed by david-allison** 2024-07-28 01:00 UTC
