### ISSUE TITLE
Error syncing media data java.io.IOException: ~.mp3: No such file or directory

### ISSUE THREAD

**Issue by vrublack** [ankidroid/Anki-Android#4782] opened 2018-02-05 16:02 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

(Using Nexus 5x)

1. Press sync

###### Expected Result

Synced collection without errors

###### Actual Result

The following error dialog:

Collection synchronized
Error syncing media data
java.io.IOException: ~.mp3: No such file or directory

The error doesn't occur for that specific .mp3-file anymore if sync is done again but it often occurs for a differen .mp3-file. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.3

Android Version = 8.1.0

ACRA UUID = 3cdabe8c-2b39-47fb-a660-54e5edfa1183

**Comment by SvenskNavi** [comment] 2018-05-31 18:06
@mikehardy I installed alpha22, and it worked much better. I did still managed to get 3 errors during the sync, one still being the same "No such file or directory". Other one was an ssl connection exception, and didn't catch the third one, closed it too soon. Still, was better than an error every 100 media files.

**Comment by mikehardy** [comment] 2018-05-31 18:23
@SvenskNavi  - very interesting! Thanks for trying that out. What I understand then is that with AnkiDroid simply re-trying up to 5 times for each file, you have greater success. Obviously we could tune that, so maybe one more time would make it work better for you, but the root cause here seems to be that your network connection is just really unstable. 

Can you tell me a couple more things? 

1- If you sync a couple times with alpha 22 (which contains the 5-retry patch), are you eventually able to sync fully and verify that all your media files are downloaded?
2- are you aware of any problems with the network your phone is using? (other applications misbehaving, etc)

**Comment by SvenskNavi** [comment] 2018-06-02 23:49
1. I did try it again on another device (my phone actually died the day I was going to try a second time on it ), and it synced fully with zero issues.
2. I was on work Wi-Fi which can be a little spotty, so a connection issue is definitely possible. I will say that 2.8.3 was tried at home with strong connection, so definitely no connection issues there.

**Comment by dangercrow** [comment] 2018-06-03 20:05
Had previously encountered this issue (also 5X) and gave up and swapped device. Now my other device is bust I'm back to my 5X and still seeing this issue!

No network issues on WiFi, about to try installing the new alpha to provide more data.

**Comment by mikehardy** [comment] 2018-06-03 21:07
Fascinating, this seems to be a 5X phenomenon, but the code is harmless to be in mainline in my opinion.

@dangercrow  thanks for the testing and glad it worked
@SvenskNavi  thanks for the additional feedback

On a cursory search it appears Nexus 5X wifi is problematic. The data charges might or might not be important, but I would wager that with wifi disabled these syncs would work over a mobile network.

Either way, it appears the patch is working as intended and allowing people to muddle through at least.

https://issuetracker.google.com/issues/37117629

**Closed** 2018-06-08 23:51 UTC
