### ISSUE TITLE
[Bug][2.16alpha52] Crash on opening "Deck options"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10592] opened 2022-03-21 08:37 UTC
Thank you always, developers.

###### Reproduction Steps

1. Update AnkiDroid to version 2.16alpha52 (the latest version).
2. Open AnkiDroid.
3. Long tap a deck on `Decks` screen.
4. Tap `Deck options` on the deck's menu.

###### Expected Result

`Deck options` screen is displayed, as in 2.16alpha51 and the earlier versions.

###### Actual Result

AnkiDroid crashes.

###### Debug info
```
AnkiDroid Version = 2.16alpha52

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.58 Mobile Safari/537.36

ACRA UUID = 57691f25-90e7-4c99-a358-c33c2f723019

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2022-03-21 10:54
Duplicate of #10584. Already fixed

**Closed** 2022-03-21 11:04 UTC
Labels: Duplicate

**Comment by snowtimeglass** [comment] 2022-03-21 11:18
I'm sorry. Mistakenly, I only checked open issues. @BrayanDSO, thanks for letting me know.
