### ISSUE TITLE
in-progress edits to search string in card browser are lost if navigation drawer opens

### ISSUE THREAD

**Issue by Andrej-Adamenko** [ankidroid/Anki-Android#9010] opened 2021-05-30 02:45 UTC
I cannot finish editing a search string, because every time I try a window or menu would open, reverting my editions.

[This screenshot video demonstrates the problem](https://youtu.be/j2KWTnxDC2w) 

The problem started recently, I noticed it only today. 

AnkiDroid Version = 2.15.2

Android Version = 10

Manufacturer = samsung

Model = SM-A920F

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-A920F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.77 Mobile Safari/537.36

ACRA UUID = 1b392f85-2b0c-4491-b153-fdb7fb7b8d34

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment] 2021-05-30 03:31
Hi @Andrej-Adamenko thank you for the video that was a clear demonstration of the issue, it really helped.

I see two problems really:

1) the search string should not revert just because the navigation drawer opened, that's odd? I want to keep this specific issue focused "why do the edits on a search string revert when the navigation drawer opens?"

Because no matter when the navigation drawer opens the search string edits in progress should stay in progress.

But, the navigation drawer open behavior itself did change from 2.14 to 2.15 release series. We added the feature that the drawer would open from a drag anywhere on the screen, not just the border. Why? People with small hands on today's larger phones were not able to access the drawer. It is a need, however, we have received a lot of negative feedback and we're tracking an issue here were the plan is to make it possible but *optional* and default it to off. #8936 is one you may wish to track for that

If this is really bothersome you may install a "parallel" release of 2.14.6 side by side with the main release you have, and as long as only one is running at a time you may think of it as a temporary workaround while we solve the navigation drawer issues https://github.com/ankidroid/Anki-Android/releases/tag/v2.14.6

Hope this helps

**Comment by Andrej-Adamenko** [comment] 2021-05-30 03:59
@mikehardy may be it reverted, because I used the "back" button, to hide the navigation drawer? If yes, how could I hide it without reverting?

**Comment by Andrej-Adamenko** [comment] 2021-05-30 04:11
There was another problem that repeated a few times. The note editor unexpectedly opened, while i was typing a search string in Card Browser

**Comment by david-allison-1** [comment] 2021-05-30 12:14
Opening the drawer calls `onCreateOptionsMenu()`, which resets the value:

Caused by a fix to #6500:

https://github.com/ankidroid/Anki-Android/blob/6d96bbebd62346f049666e2d4c12af3fdf58def3/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L991-L995

**Comment by david-allison-1** [comment] 2021-05-30 12:49
Thanks so much for the reports by the way.

Additional related code:

https://github.com/ankidroid/Anki-Android/blob/d14eea94579aef17ba77b5046f0400f3dad61386/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.java#L130-L134

**Comment by david-allison-1** [comment] 2021-05-30 14:05
Just to note for future:

* supportInvalidateOptionsMenu => MenuBuilder.clear() 
* MenuBuilder.clear() => collapseItemActionView(mExpandedItem);
* => onActionViewCollapsed
* =>  setQuery("", false);

**Comment by mikehardy** [comment] 2021-05-30 15:26
@Andrej-Adamenko we will be defaulting the navigation drawer full screen swipe to off with a new setting in 2.15.3 and @david-allison-1 just posted a pull request to save/restore the search string (that may have in progress edits) if the navigation drawer opens) so both those issues should be fixed in 2.15.3

I'm unaware of the note editor opening as an issue, this issue will be closed by those two fixes

If you can open a new issue and post a video of the note editor also opening after 2.15.3 releases we can investigate that but I *think* and hope that your user experience will be all fixed up with 2.15.3

**Comment by david-allison-1** [comment] 2021-05-30 15:27
This was a bug in 2.14.6 as well

**Comment by mikehardy** [comment] 2021-06-01 18:10
minor update: making navigation drawer full-screen-gesture-to-open optional will go in 2.15.3, but maintaining search string edits while the drawer opens won't go in until 2.16.0

**Closed** 2021-06-02 03:54 UTC
Labels: Good First Issue!, Help Wanted, Needs Triage, UI
