### ISSUE TITLE
Language not changing properly

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4888] opened 2018-06-26 00:20 UTC
###### Reproduction Steps

1. Settings->AnkiDroid->Language
2. Change to French
3. Restart the app and open navigation drawer

###### Expected Result
Navigation drawer items should be translated, since they have translation strings for French

###### Actual Result
None of the drawer is translated. Only a very few selected strings around the app are translated, like the "you studied XXX card today" part at the bottom

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

Reproduced on a motog running Android 8.0.0 and on the pixel simulator for 8.1.0. Haven't tried any other OS versions.

**Comment by mikehardy** [comment] 2018-06-26 00:50
Yeah there are a couple translation issues extent right now and they are pretty serious! I have duplicated with varying effects in different API emulators but have no root cause analysis

**Comment by timrae** [comment] 2018-06-26 00:55
Are you able to reproduce with 2.8.x on Android 8? If not then maybe it's coming in through the build tools update

**Comment by mikehardy** [comment] 2018-06-26 01:01
It was before then if I remember, can compare that commit with my repro test record on one of the bugs (I forgot which and am only on a phone right now sorry)

**Comment by timrae** [comment] 2018-06-26 01:11
Mmm yeah I just tried 2.6.1 on my MotoG and it's not working there either,
so most likely an OS update that broke it

**Comment by mikehardy** [comment] 2018-06-26 02:21
Back on the laptop, here's the full cross-reference - I think this might best be closed as a duplicate as the full info is on Issue #4729 - below is a copy/paste of my test summary; it is broken all the way back to API 18 which was 2012 according to The Internet. So either an API upgrade broke it or I think this will actually be what I usually call a "multi-bug" because it has different problems in different APIs, hinting that there are probably a few things going wrong under the covers...an implementation issue originally (should just change in API18? why the restart), an API upgrade/change layered on (API>=24 plain busted), etc

---


Old Android (API 18): Mostly works though doesn't apply immediately or fully - works perfectly after force-stopping the app and restarting though
Marshmallow (API 23)): Works but doesn't apply immediately (after Slovak selection, takes you to settings page still in system language). Works perfectly across force-stop app restarts
Newer Android (API >= 24): barely works, in the same instance or across restarts

**Closed** 2018-06-27 01:18 UTC
