### ISSUE TITLE
[BUG]: Unresovled:Screen Highlights/Darkens with Bluetooth Controller

### ISSUE THREAD

**Issue by Jeffreyyao25** [ankidroid/Anki-Android#14411] opened 2023-09-08 13:49 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Using an (Xbox) Bluetooth Controller

Connect an (Xbox) Bluetooth controller.
Assign a key to a joystick with show hint .
Press the assigned keys.

### Expected behaviour

The screen's brightness/contrast should not change.

### Actual behaviour

Instead, when I trigger the show hint function using a Bluetooth Controller, the brightness of the next card will be lowered, which is very uncomfortable.. This state persists through the cards, and the only ways to fix it are to either exit to the deck overview or close the app altogether.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = full

Manufacturer = vivo

Model = V2243A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; V2243A Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36

ACRA UUID = 706b5b86-807d-4cc5-804c-a7f55d877958

New schema = true

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2023-09-09 08:15
Duplicate of #14262

**Closed** 2023-09-09 08:15 UTC
Labels: Bug, Needs Triage
