### ISSUE TITLE
Anki doesn't show color's name

### ISSUE THREAD

**Issue by Akshittuli** [ankidroid/Anki-Android#5648] opened 2019-12-05 06:42 UTC
###### Reproduction Steps

1. Enter "color: yellow red" in front or back fields
2. Preview the flashcard
3. 

###### Expected Result
The card should read "color: yellow orange"

###### Actual Result
The card reads color: #0000ff green
The same happens with any pair of colors.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by Anthropos888** [comment] 2019-12-07 16:54
Which version are you using? I can't reproduce it.

![Screenshot_20191207-175254](https://user-images.githubusercontent.com/45192213/70377923-8639cb00-191a-11ea-9eff-d992e64738ff.png)

**Comment by Akshittuli** [comment] 2019-12-07 17:14
Interesting, It happens only with night mode turned on
Btw, I'm using version 2.9.2beta4

**Comment by Anthropos888** [comment] 2019-12-07 18:48
Interested indeed. I can confirm that:

![Screenshot_20191207-194746](https://user-images.githubusercontent.com/45192213/70379244-95c11000-192a-11ea-8197-c589377f286c.png)

**Comment by mikehardy** [comment] 2019-12-07 21:40
Night has a specific color inversion system that this must be tripping into. Something about it's regex needs a change. If you search the code case-insensitive for "invert" or just "inver" (to catch invert or inversion) you should be able to find it and might be able to use an online regex tool to propose a quick fix?

**Comment by pablode** [comment] 2019-12-23 22:30
The fundamental problem is that the current color inversion system tries to [match a regex to the whole card content](https://github.com/ankidroid/Anki-Android/blob/ac527462170071626673b517d131e5c7f08a49a5/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L2169) - not only to html or css styling. The regex searches for css attributes like `color: ...` and `background: ...`. Because of the expected form `color: yellow;`, only the first two words in this example are being replaced. 

A clean way to fix this issue is to extract and invert styling properties.

Also, the regex [`fHtmlColorPattern`](https://github.com/ankidroid/Anki-Android/blob/ac527462170071626673b517d131e5c7f08a49a5/AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.java#L11) can be extended by the `background-color` css attribute.

**Comment by david-allison-1** [comment] 2020-08-08 08:25
Proposed fix:

* Notify users that the night-mode inversion is happening (maybe once per session, maybe once overall, maybe just on the note editor)
   * This can be turned off via `.night_mode {}` in the CSS
* Provide them with an ability to allow it, turn it off, or edit the card template manually.

**Comment by Georgezxh** [comment] 2021-04-24 08:40
Hi,I found that there exists a call to connect the contents in front or back fields and the regex of fhtmlColorPattern when it is nightmode, but not exist in lightmode. And that's why the bug only appears in the nightmode......
I would like to work on this issue.

**Comment by david-allison** [comment] 2024-02-17 05:15
Closed by https://github.com/ankidroid/Anki-Android/pull/14894

**Closed by david-allison** 2024-02-17 05:15 UTC
Labels: Bug, Rendering, Keep Open
