### ISSUE TITLE
A list for missed media

### ISSUE THREAD

**Issue by lahootian313** [ankidroid/Anki-Android#4412] opened 2016-08-26 16:18 UTC
Sir
When we check media sometimes it says for example 10 media used by cards but aren't in media folder or says 10 media are in media folder that aren't used by any cards
In these two cases it's highly needed for a creator of a deck to see which is which
I mean if I have 900 cards and 10 media aren't in media folder and 20 media aren't used by any cards if I could be able to see which media aren't used and which cards are using missed media it wouldn't be needed to check all these 900 cards to find which card can't play audio 
Sometimes audio's incorrect name or card's incorrect content caused these two problems
If u add a list of these media or these cards that don't have media You simply have removed a burden  

I just thought u can add this feature in card browsing by adding a tag like other tags or make it visible in another color

**Comment by eginhard** [comment] 2016-08-31 10:52
Duplicate of #4396

**Closed by eginhard** 2016-08-31 10:52 UTC
