### ISSUE TITLE
Undo: NoSuchElementException - LinkedBlockingDeque.removeLast

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#7776] opened 2020-11-26 22:31 UTC
Related: #7723 #7728

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/29cf12d8-b484-45a5-87bc-5a5b18de4c0d

```
java.util.NoSuchElementException
at java.util.concurrent.LinkedBlockingDeque.removeLast(LinkedBlockingDeque.java:462)
at com.ichi2.libanki.Collection.undo(Collection.java:1)
at com.ichi2.async.CollectionTask.nonTaskUndo(CollectionTask.java:2)
at com.ichi2.async.CollectionTask.e(CollectionTask.java:1)
at com.ichi2.async.c.run(Unknown Source:4)
at com.ichi2.libanki.DB.executeInTransaction(DB.java:2)
at com.ichi2.async.CollectionTask.doInBackgroundUndo(CollectionTask.java:3)
at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:47)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by david-allison-1** [comment] 2020-11-26 22:52
@Arthur-Milchior This isn't a crash, but will cause a "corrupt collection" message to appear if obtained from the reviewer.

What is the intended behaviour if an undo can't be performed?

**Comment by david-allison-1** [comment] 2020-11-26 22:53
This needs to be handled in two ways:

* Ensure that undo can't be double-tapped when there is 1 undo left
* If this does occur - reconsider and specify the action which should occur:
   * Recommendation: Exception report, and show a "something went wrong" toast.

**Comment by Arthur-Milchior** [comment] 2020-11-27 00:24
If undo can't be performed, I don't believe there is anything we can do. Just toast as you wrote.
Normally, buttons are deactivated after actions is done in the reviewer, so it should not be possible to double click. I'd be interested in knowing how this occured if you had any idea.
Undo is also available in the deck picker. I don't know whether buttons are deactivated here. I guess not, but when you undo, it should open the reviewer to show the card again.

**Comment by david-allison-1** [comment] 2020-11-29 13:26
> I'd be interested in knowing how this occured if you had any idea.

Clicking a button queues up actions which aren't executed immediately - we haven't yet implemented a good debouncing mechanism

**Comment by farjadilyas** [comment] 2021-03-30 18:19
I believe this is a consequence of #4312. I was able to reproduce this bug using the following steps:
1. Open a deck, in the reviewer, bury a single card
2. Go back to DeckPicker
3. Click on 'Undo Bury Card' twice

**Comment by farjadilyas** [comment] 2021-03-30 18:46
If the desired behavior while undoing anything from DeckPicker is to open the Reviewer, then multiple clicks shouldn't be possible once #4312 is resolved. In addition, ```Collection```'s ```undo()``` method can be altered to check for available undos and return null instead of throwing an exception at ```removeLast()```. The ```undo()``` method has only one calling method, ```CollectionTask()```'s ```nonTaskUndo()``` which seems to ignore the undo if null is returned. All other methods that call ```undo()``` are tests. Can anyone confirm these observations?

**Comment by mikehardy** [comment] 2021-04-01 21:58
@farjadilyas good digging!

1- if "undo review card" returns to the reviewer, it does seem that "undo ... card" (the general case of a single card action that sends you to the deck picker) should also return to the reviewer, on that card
2- I think marking Collection.undo() as `@Nullable` return, and returning null when there are no undos, plus cleaning up any new lint from callers that are not null checking is also a good idea as it will make the rest of the app safe from this class of issue

**Comment by mikehardy** [comment] 2021-06-30 14:35
This is still happening

**Comment by BrayanDSO** [comment] 2023-01-06 22:23
> Open a deck, in the reviewer, bury a single card
Go back to DeckPicker
Click on 'Undo Bury Card' twice

Still reproducible on 2.16alpha91

**Comment by zaghdaneh** [comment] 2023-06-25 15:50
From my understanding the problem is that the undo button isn't hidden when the list of undo actions is empty.
Adding `context.invalidateOptionsMenu()` in the DeckPicker.kt undoListener after the undo is successful fixes the problem (you can only undo once). Should I open a pull request with this fix or is invalidating the menu bad in this case?

**Comment by dae** [comment] 2023-08-31 08:15
Should be fixed by new backend.

**Closed by dae** 2023-08-31 08:15 UTC
Labels: Priority-High, Bug, Keep Open
