### ISSUE TITLE
Bug: Tapping "Reset progress" occurs a crash

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4590] opened 2017-02-24 11:06 UTC
At least 3 users have commented about this bug on Google Play or Google Group.

###### Reproduction Steps

1. Display a card 
2. [Edit note]
3. [Reset progress]

###### Expected Result
 The progress is reset.

###### Actual Result
A crash occurs.

###### Debug info
AnkiDroid Version = 2.8.2beta2
Android Version = 4.3
ACRA UUID = 4481e477-c396-48c9-9a20-5d6b34e717f1

**Comment by snowtimeglass** [comment] 2017-02-24 12:35
5 users have done.

**Comment by timrae** [comment] 2017-02-25 02:44
Duplicate of #4589 
Please try to check the list of open issues before opening a new one.

**Closed by timrae** 2017-02-25 02:44 UTC
Labels: duplicate

**Comment by snowtimeglass** [comment] 2017-02-25 04:03
I'm sorry for bothering you. It was careless of me. I'll be more careful in future.
