### ISSUE TITLE
[Bug] Finishing a deck no longer goes to overview

### ISSUE THREAD

**Issue by j-steinbach** [ankidroid/Anki-Android#15694] opened 2024-02-27 11:13 UTC
###### Reproduction Steps

1. Finish a deck

###### Expected Result

Finishing a deck should move me to the deck overview, where I can select the next deck to review.

###### Actual Result

Finishing a deck does not return me to the deck summary anymore, but instead some other screen.

###### Debug info

2.17.1
26 Feb 2024
anki 23.12.1 / 1a1d4d54

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pavreh** [comment] 2024-02-27 17:22
duplicate of #15349

**Closed** 2024-02-27 18:29 UTC
