### ISSUE TITLE
Stats page appears wierd while loading

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16085] opened 2024-04-03 12:03 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Open Stats page

### Expected behaviour

The page doesn't appear wierd while loading

### Actual behaviour

The page appears wierd when loading.

IIRC, this issue was not present in alpha 7.

<img width=280 src="https://github.com/ankidroid/Anki-Android/assets/92206575/92fdc962-6852-4e7d-966a-53d16bb035ff">

Fully loaded page (for comparison)
<img width=280 src="https://github.com/ankidroid/Anki-Android/assets/92206575/25d3557e-70d5-4792-b32e-efb6104f64ad">

### Debug info

```text
AnkiDroid Version = 2.18alpha8 (6fc26947fd31743bc83e68f17ae7fec64bfa8e62)

Backend Version = provider(?) (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = null

ACRA UUID = 70fd8e4a-1bcf-4f20-8bac-43ba9946410f

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2024-04-03 14:40
likely upstream, the big difference between 2.18alpha7 and 2.18alpha8 was moving from internally including anki 23.10.1 to anki 24.04 and that's a *lot* of change, including to the statistics page (which comes from upstream)

It would be interesting to see what the statistics page looks like if anki desktop is run in a very very small screen like it does in AnkiDroid...

**Comment by david-allison** [comment] 2024-04-03 14:49
Smallest I can do:

![Screenshot 2024-04-03 at 15 49 41](https://github.com/ankidroid/Anki-Android/assets/62114487/521173e5-fc9a-465a-a869-a78c4bd56af6)

**Comment by david-allison** [comment] 2024-04-03 15:00
@neeldoshii Could you have a quick check to see whether https://github.com/ankidroid/Anki-Android/commit/7a4dfd093db8cc794b6f8b5f63e9f0a846b58985 is relevant (I suspect it's our Anki backend change which is the cause), this is the other reasonable possibility

* https://github.com/ankidroid/Anki-Android/pull/16027

**Comment by neeldoshii** [comment] 2024-04-03 15:02
sure, will check and get back to it in few hour.

**Comment by neeldoshii** [comment] 2024-04-03 19:20
The issue is not reproduced in https://github.com/ankidroid/Anki-Android/commit/7a4dfd093db8cc794b6f8b5f63e9f0a846b58985.


https://github.com/ankidroid/Anki-Android/assets/60827173/de39c09d-9efb-41bc-a940-2757301fcaf7

**Comment by snowtimeglass** [comment] 2024-04-04 03:11
Some parts of the phenomenon seem to occur in neeldoshii's video, too.

The vertical-scroll-bar-like objects is shown momently, and also, the resizing (fitting the objects to the screen) occurs in it.

On 2.18alpha8 in my device, the resizing is relatively conspicuous, since the objects overflow from the screen at first. On the other hand, the scroll-bar-like objects don't seem to be shown.

On loading | After loading
---|---
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/01920aec-ddce-4787-ade3-38699785490d" width="320px">|<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/251c6e09-7f44-46a0-b9be-1d79267b1a24" width="320px">



**2.18alpha8**

https://github.com/ankidroid/Anki-Android/assets/10436072/dae6645b-3fee-46b7-9321-71b4bfd42309

---

The resizing doesn't seem to occur in 2.18alpha7 on my device, which is consistent with user1823's comment. 

**2.18alpha7**

https://github.com/ankidroid/Anki-Android/assets/10436072/992d62c9-cfbe-49fa-a1d7-28d7ed52fb1a

**Comment by david-allison** [comment] 2024-04-09 13:48
Can we `git bisect` https://github.com/ankidroid/Anki-Android/compare/v2.18alpha7...v2.18alpha8 to find the relevant commit?

**Comment by user1823** [comment] 2024-08-11 17:32
Still looking for a solution...

**Comment by deysak** [comment] 2024-10-21 14:40
This issue was fixed by https://github.com/ankidroid/Anki-Android/pull/17250

**Tested** on Device (Physical): Pixel 6a, Android 14, SDK 34

### Video:

<details><summary>Before Fix 🐞 @ <code><a href="https://github.com/ankidroid/Anki-Android/commit/461984282b381f41e48f2e7933851935ae9a586d">4619842</href></code></summary>
<p>

https://github.com/user-attachments/assets/a1409539-dd53-4436-925d-2aed0c9c40e8

</p>
</details> 

<details><summary>After Fix ✨ @ <code><a href="https://github.com/ankidroid/Anki-Android/commit/5645e2817977110bfad555318ff6edc927dc4453">5645e28</href></code></summary>
<p>

https://github.com/user-attachments/assets/2231dbd4-c861-4a82-b91a-cab281f01e81

</p>
</details> 

<details><summary>Current <code>main</code> ✨ @ <code><a href="https://github.com/ankidroid/Anki-Android/commit/0fdbb6dfa568409ab00d2033c184fb0410bb8dea">0fdbb6d</href></code></summary>
<p>

https://github.com/user-attachments/assets/ce312b04-3595-4928-824d-5a452b598f19

</p>
</details>

**Closed** 2024-10-21 18:22 UTC
Labels: Bug, UI, Needs Triage, 2.18
