### ISSUE TITLE
[Bug] Previewing a note breaks TTS

### ISSUE THREAD

**Issue by jparta** [ankidroid/Anki-Android#8085] opened 2021-02-04 12:17 UTC
###### Reproduction Steps

1. Enable TTS
2. Go to Study
2. Preview a note, either from Card browser or from dots menu > Edit menu in Study
3. Return to review view in Study without re-initialization (use back button to come back from Card browser)

###### Expected Result
'Replay audio' causes TTS to read card.
Presentation of next card causes TTS to read card.

###### Actual Result
No audio or visual feedback with either action.

###### Debug info
AnkiDroid Version = 2.14.3

Android Version = 10

ACRA UUID = f939c8ba-2220-489e-abb1-d041f0afd05a

Scheduler = std2

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Similar and possibly related to #8084. Unlike #8084, here there is no visual feedback. Re-initialization by opening Study again all the way fixes this one as well.

**Comment by iCarlosCode** [comment] 2021-02-06 17:10
Hi! This bug was anoying me so much hahahaha. I was about to open an issue about it. Thanks for opening it.

**Comment by jparta** [comment] 2021-04-10 19:05
@JG916 @mikehardy
Could this issue have a cause similar to #8084?

**Comment by JG916** [comment] 2021-04-10 22:20
It looks similar. I did a quick check and it looks like the issue stems from the study activity not re-initializing TTS/ReadText again. When the preview activity opens, it overwrites everything on ReadText that belonged to the other activity. The other issue occurred because one activity was trying to release it and the other was trying to initialize it, but here, it's only being released.

I managed to get it 'working' again by moving `ReadText.initializeTts` from onCollectionLoaded to onResume (inside AbstractFlashCardView). I doubt it's as simple as this, but at least it's a start...

Also, take note of #8179. Possibly this will be fixed with whatever comes out of that?

**Comment by dae** [comment] 2023-08-31 08:25
Related: #14358

**Comment by sudomain** [comment] 2024-01-22 15:24
A note for those affected:
I can't reproduce this in 2.17alpha16, though I only tested with the new multi-field TTS syntax, which I don't think existed when this issue was opened:
```
[anki:tts lang=en]
This is {{Field 1}}
[/anki:tts]
```

I did not test the `{{tts}}` syntax or AnkiDroid's TTS option under `Advanced` and it's not clear which one was described in the reproduction steps. Adding the new syntax to your templates is a workaround

**Comment by david-allison** [comment] 2024-01-22 15:37
`{{tts}}` is recent. 

I believe the syntax was `<tts service="android">`, but this was added well before my time

----

We're going to deprecate `ReadText`, so I suspect this will be removed before it gets fixed

**Comment by david-allison** [comment] 2024-02-11 22:00
https://github.com/ankidroid/Anki-Android/labels/Won%27t-fix

**Closed by david-allison** 2024-02-11 22:00 UTC
Labels: Bug, Audio, Help Wanted, Won't-fix, Keep Open, Reviewer
