### ISSUE TITLE
User report: check media not working

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15434] opened 2024-02-07 00:08 UTC
> I can't use "check media" on the latest beta. Is it a problem others have encountered?

> I have tried **restarting the device, clearing my catch. have checked database/empty cards.** It works fine. 
The check media option doesn't work still. What I mean by that is after the check completes **the popup disappears**, and at this point it needs to show me the unused media, but instead the ** app freezes for a few secs and the app closes**
> I think it maybe related my large collection?
> The collection.media folder on my phone has around 30437 items and the total size is 1.82GB
> The last thing I was doing was importing a Hanzi deck and it probably had like 5K media files. I stopped importing once, decided to reimport but again stopped because it was taking too much time. I don't know if it's related somehow to my large collection of unused media that the app freezes.
But this is the only explanation I have.

Subset of ACRA: no relevant reports found

```
AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

ACRA UUID = dce906d5-19f7-4514-a0e4-0071f4f7b489

Crash Reports Enabled = true
```

Discord: brishtibheja

**Comment by brishtibheja** [comment] 2024-02-07 17:29
Posting a comment so people can reach me. If anyone needs additional info, I am willing to share.

**Comment by david-allison** [comment] 2024-02-07 18:16
@brishtibheja Thanks!

Could you:
* ensure crash reporting is enabled in the settings
* re-send a troubleshooting exception:
  * Help -> Get help -> Send troubleshooting report 
* cause the crash again

**Comment by brishtibheja** [comment] 2024-02-13 16:17
Completely missed the notification somehow. I came because I saw "needs author reply" tag. Sorry for my delayed response.

1. crash reporting enabled.
2. sent. I think it went through this time.
3. done. I bought a new phone so had to reinstall anki in my old phone to cause the crash again. New phone is perfectly fine and check media doesn't cause any issues for the same collection.
4.  Here:

AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)
Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)
Android Version = 11 (SDK 30)
ProductFlavor = full
Manufacturer = realme
Model = RMX2193
Hardware = mt6768
Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.143 Mobile Safari/537.36
ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac
Crash Reports Enabled = true

**Comment by david-allison** [comment] 2024-02-13 23:57
Crash hasn't come through. It's still occurring?

You may need to install `adb` and use `logcat` to obtain a crash log

Instructions: https://github.com/ankidroid/Anki-Android/issues/14708#issuecomment-1862972315

**Comment by brishtibheja** [comment] 2024-02-14 00:02
I wish I could do that but I have no idea how do these things work. And if my understanding is correct you need to have a PC right? Sadly I can't access that. Brown Parents 🥲 They can't even use an email.

**Comment by david-allison** [comment] 2024-02-14 06:43
No worries! Might get left for a while until we can find a way to reproduce this

**Comment by BrayanDSO** [comment] 2024-10-12 09:42
Closing as can't reproduce

**Closed by BrayanDSO** 2024-10-12 09:42 UTC
Labels: Bug, Can't reproduce, 2.17
