### ISSUE TITLE
[BUG]: New cards are added to wrong deck

### ISSUE THREAD

**Issue by Sharkara98** [ankidroid/Anki-Android#15879] opened 2024-03-13 22:51 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

I add a new card and they are added to the wrong deck, one in particular.

### Expected behaviour

New cards should go to the deck I have selected.

### Actual behaviour

New cards do not go to the deck I have selected.

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 10 (SDK 29)

ProductFlavor = play

Manufacturer = HMD Global

Model = Nokia 7 plus

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Nokia 7 plus Build/QKQ1.190828.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.105 Mobile Safari/537.36

ACRA UUID = 255f475e-2863-4db2-a65b-d1f085f3c4ca

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

I believe this is an issue that has occurred in the past.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-03-13 23:08
Edit a note of the note type. Tap `Cards:`, then tap the menu

It should say `Deck override: off`

**Comment by Sharkara98** [comment] 2024-03-13 23:11
It is on. How do I turn it off?
________________________________

**Comment by david-allison** [comment] 2024-03-13 23:57
Tap it and select "Restore default"

**Comment by david-allison** [comment] 2024-03-13 23:58
Closed this as it's not a bug

**Closed** 2024-03-13 23:57 UTC
Labels: Question
