### ISSUE TITLE
Can't open database with many decks after update

### ISSUE THREAD

**Issue by mtrevix** [ankidroid/Anki-Android#5603] opened 2019-11-04 04:25 UTC
###### Reproduction Steps

1. Open AnkiDroid
2. Error message appears (see screenshot in Italian, giving only two options: "close" and "options")
3. Even after trying to check the database (the most reasonable option), I can't open my collection. But the same collection works fine with Anki desktop and previous AnkiDroid versions

![Screenshot_2019-11-04-04-04-25](https://user-images.githubusercontent.com/5268991/68099476-b83eb400-feba-11e9-947f-dd7b40bf2528.png)

###### Expected Result

Open decks and use normally.

###### Actual Result

Can't open collection, need to close.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

I cannot copy the debug info, because the app doesn't allow to do anything. However, I know from google play it in version 2.9.2beta4

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2019-11-04 05:33
Hello @mtrevix - that's a serious error indeed. I think it may be related to a recent change made in libanki code with editing, can confirm whether or not you were editing cards just prior to this happening? Or just reviewing? Either way, *if* it the issue I'm thinking then it is fixed either by increasing your daring and going to the alpha program, or leaving the beta and using 2.9.1 

- alpha option explained here - https://docs.ankidroid.org/manual.html#betaTesting
- that link also shows how to leave the beta program (so you'd get 2.9.1)

Issue I'm thinking of https://github.com/ankidroid/Anki-Android/issues/5576 (discussion there focused on 2.10alpha10, but I believe 2.9beta4 had the same change included)

If you can confirm any of the suggestions here work, I'd appreciate it, as that would mean we need a 2.9beta5 quickly with the fix from #5579

**Comment by mtrevix** [comment] 2019-11-04 14:56
Hi @mikehardy. Actually, this error reminds me a lot what happened back in 2015, when v2.5 was released; I sent then my collection to @timrae, and it was fixed in the next version:
https://github.com/ankidroid/Anki-Android/issues/3905

I don't know if this issue is related to that, and I don't understand the details of what was wrong back then. My collection is large and I organise it making a heavy use of nesting, but it works fine both in version 2.9.1 (which I have installed now to be able to work with my cards) and with the last desktop version (v2.1.15). I use Anki on a daily basis, but I didn't change or study any decks after syncing, the only difference was that the new AnkiDroid beta version was installed (2.9.2beta4).

Thanks for checking this.

**Comment by timrae** [comment] 2019-11-04 15:04
Please test with the latest alpha version. You do NOT need to permanently join the alpha program, you can manually install the apk from github, and then uninstall --> reinstall AnkiDroid from Google Play.

**Comment by timrae** [comment] 2019-11-04 15:05
Also, if you can post a Google Drive link to your collection, that might help someone to reproduce the error if required.

**Comment by mtrevix** [comment] 2019-11-04 22:46
I have just tested 2.10alpha16, but unfortunately doesn't work, same issue. About sharing my collection, it contains some personal information, so I prefer to keep it private.

**Comment by timrae** [comment] 2019-11-04 22:53
Can you please tell us the first version of 2.9.2 beta series where the bug is introduced? Exporting a small example deck that demonstrates the problem might be useful, without sharing your whole collection.

**Comment by mtrevix** [comment] 2019-11-05 05:32
I can confirm that 2.9.2beta3 works perfectly, so the bug is between than and 2.9.2beta4.

**Comment by mtrevix** [comment] 2019-11-05 12:28
I have isolated the bug! It had to do with the fact that some of my subdecks had a name starting with colon (":"). To reproduce the bug follow these steps using 2.9.2beta4:

1) select a subdeck, for example "anydeck::subdeck" (appears as "anydeck > subdeck" in the collection)
2) rename it as "anydeck:::subdeck" (notice the three colons instead of two)

behaviour in versions 2.9.2beta3 (AnkiDroid), and 2.1.15 (desktop, using Ubuntu, Windows and Mac) and previous: new deck appears as "anydeck > :subdeck"
behaviour in versions 2.9.3beta4 and posterior: whole collection crashes and error message appears.

I used the "colon trick" to "move" some of the decks to the bottom, sort of tricking the alphabetical order.

Hope this helps!

**Comment by mikehardy** [comment] 2019-11-05 14:17
Excellent diagnostics! I'm glad you are working again and thank you so much for digging in and sharing details

@Arthur-Milchior does it seem like any of your changes might have affected this? I think the work on [removing recursion in the deck list scan](https://github.com/ankidroid/Anki-Android/commit/e9d5dc2ce0a9a733930bab445ba1db72871be936) is exactly in this area. You can see what commits went in to the betas looking here https://github.com/ankidroid/Anki-Android/commits/hotfix-2.9.2

**Comment by Arthur-Milchior** [comment] 2019-11-05 16:08
Thanks for mentioning me. I'm indeed the one to blame here.
Corrected.
I never thought about what would happen when : starts or ends a deck name. (Actually this last one seems quite fun to deal with. I'll try giving a child to a deck "foo:" in anki and see what occurs.)

**Comment by mtrevix** [comment] 2019-11-05 20:54
Narrowing down to the key problem has been a lot of work, but I'm glad I helped, this is the whole point of being a beta tester!

**Comment by Arthur-Milchior** [comment] 2019-11-05 21:22
I hope that my remark will not offend you. I certainly am sorry for creating an error, and hope it'll be corrected soon. But in this case, I do believe that you may have saved yourself some work. 
For what I get, I assume you're not used to read the technical error messages that are sent when the program crashes. 
If you did share the collection which creates the trouble, then one of the dev' could have read the error message, and then could probably have found the cause of the problem quite quickly. 
I do understand that you may choose not to share your collection, and prefer to narrow down yourself. In which case, I suggest you should try to learn how to read and copy/paste the message written by the program.

**Comment by mikehardy** [comment] 2019-11-05 21:32
@Arthur-Milchior - by technical error do you mean accessing logcat via adb while a device is plugged in? That's what I'd do but I while it is an insanely powerful tool for devs - and probably would have showed this immediately - it is maybe even more time-consuming setting it up the first time (getting Android Dev Tools set up, enabling developer menu on your phone, enabling adb, getting that working on your machine etc). I'm not sure there's another way though - if you meant something different then this could just be off-base

**Comment by Arthur-Milchior** [comment] 2019-11-05 21:33
@mikehardy that's what I means. That is why I suggested sharing the collection instead of trying to debug oneself. And that my last suggestion was given ONLY if @mtrevix didn't want to share the collection for some reason.
I mean, it's indeed a lot of work to set-up. I'm not entirely sure that it's more work than what @mtrevix did have to do to narrow done the problem

**Comment by mikehardy** [comment] 2019-11-05 21:40
Well, for anyone in the future that is interested I just read a bit and vetted this article, I think if you followed the instructions here: https://android.gadgethacks.com/how-to/android-basics-install-adb-fastboot-mac-linux-windows-0164225/ - when it was done and your phone was plugged in you could type "adb logcat" (or redirect it or something like "adb logcat > logcat.txt") and it wouldn't be too hard to do. Maybe 10-15minutes for something unfamiliar. In case it pops up in the future @mtrevix  :-). 

Or if you are just curious what an android system log looks like (guessing from your physicist/bioinformatics you've seen unix logs plenty, a unix phone log is kind of interesting first time you see it)

Either way this one has  PR in the works already thanks to speedy work from @Arthur-Milchior and it should be fixed before it can bite anyone else.

**Comment by mikehardy** [comment] 2019-11-06 17:32
The fix was merged this morning as #5607 and is out in latest alpha

**Closed by mikehardy** 2019-11-06 17:32 UTC
Labels: 2.9.x, bug

**Comment by mtrevix** [comment] 2019-11-07 09:38
Hi @mikehardy and @Arthur-Milchior, it's as you said, I preferred not to share my whole collection. I know as a programmer that checking the error would have been a much cleaner way to narrow down the problem, but I didn't want to install the Android Dev Tools, so I was just removing different sets of decks to see if one was faulty, going back and forth between version 2.9.2beta3 and 2.9.2beta4.

However, whenever I find time, I will try the ADB and other tools. I like a lot programming, I just didn't find the "headspace" to commit more seriously to an Android project, but actually I find very attractive the idea of diving into Android development by contributing to the AnkiDroid project. So thank you for your recommendations, I will take them into account!
