### ISSUE TITLE
AnkiDroid randomly crashes when learning, and progress gets reset

### ISSUE THREAD

**Issue by yhrcyt** [ankidroid/Anki-Android#5656] opened 2019-12-11 16:19 UTC
###### Reproduction Steps

1. Learn using the shared deck Japanese Core 200 deck shared on the Anki website.
2. It randomly occurs. I have no idea why.

###### Expected Result

AnkiDroid doesn't crash.

###### Actual Result

The screen goes white, and after a short while it returns to the main menu of the app.

AND... My new cards progress resets. Review card progress doesn't reset, thankfully.

###### Debug info

AnkiDroid Version = 2.9.1

Android Version = 9

ACRA UUID = 5517b928-c346-4b3a-a32d-df0d9d788046

###### Research

*Enter an [ x ] character to confirm the points below:*
[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[   ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2019-12-11 17:48
Are you certain you are using the newest possible Chrome / Android System Webview? This sounds like it could be a font problem crashing the webview #4856 , which is out of our control though we could do a better job of handling the crash https://github.com/ankidroid/Anki-Android/issues/4967#issuecomment-559098034

**Comment by yhrcyt** [comment] 2019-12-12 02:02
Hi,

Thank you for your reply. My Chrome is on Version 78.0.3904.108, and my Android System Webview is automatically disabled (cannot enable).

**Comment by mikehardy** [comment] 2019-12-12 02:11
From that font problem issue, there are recommendations I believe for lightweight fonts that are easier on the webview. Have you tried them?

**Comment by yhrcyt** [comment] 2019-12-12 02:28
I changed my font. But since this is not an issue I encounter every day, I am unable to reproduce it right away. I'll update this page when I encounter it again.

Thank you!

**Comment by Delgathar** [comment] 2020-01-11 15:08
I have this problem too.  It is suddenly occurring after years of no problem.   Anki pauses when I  go to the rate screen and seems to lock up so the page doesn't fully populate.  Then without giving me a chance to rate my last entry, it goes back to the main screen with my new cards reset.  I can see losing the last card, but I don't see why the whole thing resets.  If it simply crashed so I had 1 new card left, then I could at least figure out what card is causing the problem.

**Comment by mikehardy** [comment] 2020-01-11 19:58
So I tried looking for a crash report from ACRA UUID 5517b928-c346-4b3a-a32d-df0d9d788046 and I was unable to find one. So what we need is a stack trace from the crash which implies turning on crash reporting in preferences, and posting the UUID for your install per the instructions here about copying debug info: https://docs.ankidroid.org/help.html

with the crash report sent and the UUID to locate it we might be able to figure out what's happening?

**Comment by Delgathar** [comment] 2020-01-11 20:28
Crash reporting is in it is not working. "Ask me" is set for crash reports so I know if they are working and I was never notified that a crash report had been generated. I was just giving a  response to verify the problem is still happening.  But if there is anything I can add to help will do so gladly. Here is debug info from help.


AnkiDroid Version = 2.9.1

Android Version = 9

ACRA UUID = 1f13f567-d57a-4067-bfc2-2fb8f6ec0873

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mikehardy** [comment] 2020-01-11 21:19
Very strange - thanks for providing the ACRA UUID, I did search for it just in case but as you mention - it does not seem this is a full crash as no crash reports were there for that UUID

All I can think of now is to see if this is still happening with the latest code in the 2.10alpha series: https://docs.ankidroid.org/manual.html#betaTesting - follow the instructions there to sign up for test releases in google play, and to join the alpha group on google groups to get the latest releases

**Comment by david-allison-1** [comment] 2020-03-15 05:36
**Cause:** A hard crash of the application (should be fixed in #5820) means that `col.decks.[new/lrn/rev/time]Today` is not synchronised with state changes to the `cards` table.

**Other issues found:** Probable race conditions during normal operation causing partial writes of JSONObject to the database (tearing). This would cause hard-to-quantify data corruption issues.

<details>
<summary><b>Relevant code</b></summary>

See: [Database Structure](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure#decks-jsonobjects).

https://github.com/ankidroid/Anki-Android/blob/0904169051eae3969402ba3f67dba9629748b515/AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java#L181-L197
</details>

<details><summary><b>Walking through the code</b></summary>

1. We update an in-memory copy of `col.decks`

https://github.com/ankidroid/Anki-Android/blob/0904169051eae3969402ba3f67dba9629748b515/AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java#L181

2. We update a database copy of `cards`

https://github.com/ankidroid/Anki-Android/blob/0904169051eae3969402ba3f67dba9629748b515/AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java#L197

</details>

As seen above, we have an in-memory copy of `col.decks`, whereas `cards` is persisted.

On crash, this becomes permanent

<details><summary><b>Why does this work in the happy path?</b></summary>

`Reviewer` performs a `save` `onStop()`: 

https://github.com/ankidroid/Anki-Android/blob/0904169051eae3969402ba3f67dba9629748b515/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java#L566-L573

</details>

<details><summary><b>What are the problems?</b></summary>

* `col` needs to be consistent, for example: `col.mod` `col.models` `col.dconf` depend on data in `col.decks`.
* `col` does not support delta-based updates due to all fields being JSON, (you can't just update `newToday`
* `col` can be large (mine is >300KB of text). Desktop addons use it to store arbitrary data, and it contains all the HTML templates.
* Our use of AsyncTask means that updates to the JSONObjects are nonatomic. We can, and most likely already do experience bugs due to JSON tearing

</details>

<details><summary><b>How does Anki deal with it?</b></summary>

Anki takes out a long-running transaction over the database, It loses reviews, but stays consistent if the application is killed.

</details>

<details><summary><b>What can we do?</b></summary>

Assuming "don't crash the application, so we don't need to deal with this" isn't an acceptable answer and that we shouldn't allow for JSON tearing.

**1.**

* Convert all operations over `col` to be atomic. 
* We can now save `col` at an arbitrary time without bugs.
* Determine a strategy to synchronise the saving of `col` and `cards` which won't kill performance.

**2.**

Investigate whether we can do the same as Anki and implement `DB.commit()`.

I don't know why we don't. Perhaps: 

* Didn't want the risk of the Android lifecycle losing work `onDestroy()` 
* Multithreading issues
* The API didn't support it at the time. 
* We never got around to it

@nobnago appears to have made the commits, and hasn't been active for a long time.

https://github.com/ankidroid/Anki-Android/commit/dc75d1b44b01d80ac4657d87605dc99cec48b11f#diff-ccc5a0b819c0b77e6993c497931a9c6bR82

</details>

----

I imagine it's going to be complex and time-intensive to solve this. It'd be useful to know the historic context behind `DB.commit()` not being implemented.

**Comment by mikehardy** [comment] 2020-03-15 13:50
@timrae this is the perfect place for some wisdom - I think we're really close to solving some deep reviewer crash issues but a real fix involves understanding history / previous experience - maybe you've got some insight into db transaction use / collection save performance issues etc? Details above

**Comment by mikehardy** [comment] 2020-03-19 13:49
This is released in 2.9.6beta1 now, positive user feedback - other related issues (@david-allison-1 seems like you had some ideas...) should be logged separately

**Closed by mikehardy** 2020-03-19 13:49 UTC
