### ISSUE TITLE
[Bug] Fresh install app persist AnkiDroid logo in background till refresh or restart of app

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#8227] opened 2021-03-15 07:03 UTC
###### Reproduction Steps
I have used latest alpha build also previous one 2.14.3
1. Install AnkiDroid
2. Give storage permission
3. There are logo in background

###### Expected Result
<img src="https://user-images.githubusercontent.com/12841290/111115095-1a272780-859f-11eb-9dd4-773a784e1444.PNG"  height=400></img>

###### Actual Result
<img src="https://user-images.githubusercontent.com/12841290/111115089-185d6400-859f-11eb-9a8d-4410576bc25c.png" height=400></img>

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.15alpha30

Android Version = 11

ACRA UUID = 69a1fe19-f17a-4356-9dbf-af1c29f299fe

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by gargVader** [comment] 2021-03-15 10:55
I am unable to reproduce it

**Comment by leoshrey** [comment] 2021-03-15 16:53
Same, unable to reproduce it in build 2.14.6

**Comment by infinyte7** [comment] 2021-03-15 17:35
I think it is device specific. Also, I am not using dark theme but at first time app open welcome message in dark theme.

This is on Samsung.
v2.14.6
<img src="https://user-images.githubusercontent.com/12841290/111195644-6ef68c80-85f7-11eb-869c-10832f7bd608.gif" height=450></img>

v2.15alpha30
<img src="https://user-images.githubusercontent.com/12841290/111195643-6ef68c80-85f7-11eb-8737-1635e7d449e0.gif" height=450></img>

**Comment by mikehardy** [comment] 2021-03-15 18:08
Please never omit the "Debug info" from the bug report, it would help reproduce this.
It occurs to me that we should probably add Vendor and Model (the device info) to the Debug Info in the app that people copy/paste here, it would be useful

**Comment by david-allison-1** [comment] 2021-03-15 21:10
I'm fairly sure I've seen this on the Samsung test lab: https://developer.samsung.com/remotetestlab/rtlDeviceList.action

I presumed it was due to bad emulation software.

**Comment by mikehardy** [comment] 2021-04-14 13:18
just merged a fix should be clean and looking good in the next alpha - will release today

**Closed** 2021-04-14 13:18 UTC
Labels: UI
