### ISSUE TITLE
check media second time causes crash

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#13597] opened 2023-04-12 20:15 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Install 2.16.alpha97 play build
2. Check media (ok)
3. Check media again

### Expected behaviour

Check media is done without troubles

### Actual behaviour

Crash

### Debug info

```text
AnkiDroid Version = 2.16alpha97

Android Version = 13

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36

ACRA UUID = 0f75984c-f461-4a77-8831-85940f55f223

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2023-04-12 22:37
Thank you so much for these reports!!!!

This is a duplicate of #13527. Pending alpha 98

**Closed by david-allison** 2023-04-12 22:37 UTC
Labels: Bug, Needs Triage
