### ISSUE TITLE
Weird Backspace behavior in Card Browser Search

### ISSUE THREAD

**Issue by Ecpii** [ankidroid/Anki-Android#17040] opened 2024-09-08 18:22 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Go to card browser, search for the term "early", and get some results (~30)
2. Refocus search window, switch language to Japanese, and add Japanese characters to end of query (no results)
3. Try to delete previous input using backspace - the input resets back to the previous failed search after every backspace

### Expected behaviour

Should be able to delete previous input using backspace, but in this case the input does not change after trying.

### Debug info

```text
AnkiDroid Version = 2.19beta1 (6630ff411d643bf03206e106c4d940dc7076e738)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 8

Hardware = shiba

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 8 Build/AP2A.240805.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = d0ea4af1-1a40-4867-bed1-73eb860ba836

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

[here is a video of it happening, my description is probably not very clear](https://media.discordapp.net/attachments/790362734742601728/1282404513570885702/screen-20240908-141012.mp4?ex=66df3bc5&is=66ddea45&hm=36ec60b9ec96a2fc8dfb1758f6a6c670413bfcb3165f4cf3fca754c27b769a3f&)

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-09-08 18:24
Thanks so much for beta testing feedback!!!!!!


* Duplicate of https://github.com/ankidroid/Anki-Android/issues/16983
* Fixed in https://github.com/ankidroid/Anki-Android/pull/16999

**Closed by david-allison** 2024-09-08 18:24 UTC
Labels: Duplicate

**Comment by Ecpii** [comment] 2024-09-08 19:02
My bad for posting a duplicate! I forgot the issue search only searches through open issues, glad to see you guys already got this! Thanks 👍
