### ISSUE TITLE
[BUG]: Japanese text gets cut off on phone with rounded screen corners.

### ISSUE THREAD

**Issue by johncaiwa** [ankidroid/Anki-Android#15947] opened 2024-03-20 17:41 UTC
![Screenshot_20240321-025132_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/141907143/4624aaa9-d62b-4d6f-bdf8-9358a79dc001)
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

View the AnkiDroid home screen.
At the bottom, in Japanese, it says:
今日は332枚のカードを2.09時間後で学習しています。

### Expected behaviour

The 今 kanji should not be half cut off.

### Actual behaviour

The 今 kanji is half cut off. I don't see a period, either. I don't know if there is one or not, since where it would be is also cut off.

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 9 (SDK 28)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G950U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-G950U1 Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = da9640d8-ffbd-45dd-9936-35e01980164d

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

I think I might buy a pizza next week.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

EDIT

I just opened the screen again. It is even more cut off now. Now the first bit of text I see is the top half of the number 3, then 2枚のカード...
However, for some reason I can now see further to the right. There is no period, but it does say: (22.6 then the top half of 4

The screenshot I posted does not have rounded corners, but still the text is cut off.

**Comment by david-allison** [comment] 2024-03-20 18:17
Thanks for the report!

Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/14641

* https://github.com/ankidroid/Anki-Android/labels/Duplicate https://github.com/ankidroid/Anki-Android/issues/14641

Please give the above issue a 👍 reaction

**Closed by david-allison** 2024-03-20 18:17 UTC
Labels: Duplicate, Bug, Home Screen

**Comment by johncaiwa** [comment] 2024-03-20 19:36
"Please give the above issue a 👍 reaction"

Got it

"You should!"

Sure thing
