### ISSUE TITLE
Reviewer / Previewer don't store/restore state on restart (switch to night view while using them to see)

### ISSUE THREAD

**Issue by timo-a** [ankidroid/Anki-Android#4035] opened 2016-01-03 21:58 UTC
1) go to Browser
select preview on a card
pull side bar in, switch to night mode
->crash

2) review card A
pull side bar in, switch to night mode
-> another card B is on top, card A has disappeared back into the deck

**Comment by jeffreyj100** [comment] 2016-03-24 01:56
Is it right to allow the user the option of swiping the nav menu and toggling night mode while on preview view, as edit note view does not have this option?

**Comment by hssm** [comment] 2016-03-29 09:53
The way we restart activities when toggling night mode doesn't really work for the previewer (hierarchy and state are both lost). So unless we come up with a better way to do that in the future, I think the quick and easy solution to avoiding the crash is indeed to disable the nav drawer.

As for point 2 in the original issue, that is not what usually happens, so I don't know what is going on with that.

**Comment by ospalh** [comment] 2016-03-29 09:59
@hssm: # 2: I see this from time to time. One way i think this can happen is when a learning card (card B) becomes due while you (re]view card A.

**Comment by peervalhoegen** [comment] 2016-07-01 18:20
@hssm I found a new way to produce the behaviour in point 2!
You don't need new or red-because-wrong-answer cards.
open deck
get first card correct
on second card switch to night mode

**Comment by ukanuk** [comment] 2020-02-06 03:43
Just wanted to mention I'm still getting the behavior in point # 2. Generally I leave night mode on, but one of my cards has a stroke order diagram with black lines on a transparent background, which is practically invisible in night mode. Therefore I pull out the navigation drawer, turn off night mode --- and then am presented with different cards. So I end up having night mode disabled for a significant part of the review session, until that offending card reappears in the reviews. 

Not a big deal at the end of the day, but it does take a little bit to get back in rhythm of review.

**Comment by mikehardy** [comment] 2020-02-06 18:08
Switching to or from night mode causes a full app restart if I recall, yes. So pretty much any ephemeral state (like, current state of the reviewer activity) will be blown away. Not sure how I'd handle that but if there was a way to stuff info in a bundle for the activity and reload it, and someone followed through the control chain on night-mode switches, might be possible.

**Comment by mikehardy** [comment] 2020-03-06 16:35
@ukanuk this should be fixed I think along with #5688 via #5693 ? But maybe reviewer needs a change too? Can you check the latest alphas to see if you reproduce

**Comment by ukanuk** [comment] 2020-03-07 02:34
@mikehardy The issue is still present when toggling night mode, although I can swap between portrait/landscape on both reviewer and previewer without losing the current card.

This is with version 2.10alpha43, which I got from following directions at https://docs.ankidroid.org/manual.html#betaTesting to join the Google Play beta and also the ankidroidalphatesters google group.

**Comment by mikehardy** [comment] 2020-03-07 16:29
@ukanuk sorry it is still happening but thanks a lot for checking that out and letting us know

**Comment by mikehardy** [comment] 2021-03-14 18:19
This is a special case of #3654 - please refer to that issue for easier reproduction than night mode toggles (specifically: "don't keep activities" developer setting in phone preferences

**Comment by dae** [comment] 2021-10-20 03:35
That should not be necessary; getQueuedCards() is designed to be idempotent under most circumstances.

**Comment by BrayanDSO** [comment] 2024-02-28 21:13
Removed the `Keep Open` because the new previewer handles that and it should be the default one before this goes stale

**Closed** 2024-03-08 11:11 UTC
Labels: Bug, Priority-Medium, Reproduced, Keep Open, Backend Related
