### ISSUE TITLE
[BUG]: crash on emulator after recording local audio

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#16333] opened 2024-05-02 18:24 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- current main (commit hash in debug info)
- `./gradlew installPlayDebug`
- open AnkiDroid
- create a note
- add audio recording
- begin a recording
- stop the recording (seems to be working through this...)
- tap the ✔️  to save the recording

### Expected behaviour

it records audio and puts it in the note field

### Actual behaviour

Something new to me as a crash:

> 05-02 13:17:59.421 31267 31267 W chi2.anki.debug: Attempt to remove non-JNI local reference

was after the stack, the stack was

```
05-02 13:17:59.404 31267 31267 E AndroidRuntime: Caused by: java.lang.IllegalStateException
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at android.media.MediaRecorder.stop(Native Method)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at com.ichi2.anki.multimediacard.AudioRecorder.stopRecording(AudioRecorder.kt:78)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at com.ichi2.audio.AudioRecordingController.clearRecording(AudioRecordingController.kt:598)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at com.ichi2.audio.AudioRecordingController.onViewFocusChanged(AudioRecordingController.kt:282)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at com.ichi2.audio.AudioRecordingController$createUI$8$1.onActivityPaused(AudioRecordingController.kt:246)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at android.app.Application.dispatchActivityPaused(Application.java:461)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at android.app.Activity.dispatchActivityPaused(Activity.java:1519)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at android.app.Activity.onPause(Activity.java:2468)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:282)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:8790)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1657)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5252)
05-02 13:17:59.404 31267 31267 E AndroidRuntime: 	... 14 more
05-02 13:17:59.407 31267 31267 D UsageAnalytics: sendAnalyticsException() description/fatal: java.lang.IllegalStateException/true

```

### Debug info

```text
AnkiDroid Version = 2.18beta1-debug (8e29b5a50b3fb161137af0831639395c5bfaf78c)

Backend Version = 0.1.38-anki24.04.1 (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 14; sdk_gphone64_arm64 Build/UE1A.230829.036.A2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.136 Mobile Safari/537.36

ACRA UUID = b188f1a2-8daa-4843-a1ea-925ef41232e4

FSRS Enabled = false

Crash Reports Enabled = false
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-05-02 18:48
Duplicate of https://github.com/ankidroid/Anki-Android/issues/16321

**Closed by david-allison** 2024-05-02 18:48 UTC
Labels: Bug, Needs Triage

**Comment by mikehardy** [comment] 2024-05-02 18:52
sorry for the duplicate
