### ISSUE TITLE
Option to not display audio cards when the device media loudness is set to silent

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2867] opened 2015-07-28 10:14 UTC
Originally reported on Google Code with ID 1965

```
There are cases where a user sets his phone to silent because he's in an enviroment
in which he would disturb other people through audio.

In that case AnkiDroid currently still gives the user cards that contain audio information
but doesn't play that information.

I therefore suggest that when the device media loudness is that to zero, Anki simply
skips all cards that contain audio information.
```

Reported by `christian.kleineidam` on 2014-01-14 15:21:13

**Comment by eginhard** [comment] 2017-05-10 21:44
Duplicate of #4601

**Closed by eginhard** 2017-05-10 21:44 UTC
Labels: enhancement, Priority-Low
