### ISSUE TITLE
android.preference.Preference is deprecated

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8349] opened 2021-03-26 17:41 UTC
We are using `android.preference.Preference` which is marked as deprecated since API 29. It would be nice to consider moving to `androidx.preference.Preference` as suggested. Or if we don't do it, document why we prefer to keep a deprecated class

**Comment by david-allison-1** [comment] 2021-03-26 21:25
Duplicate of #5019

**Closed by david-allison-1** 2021-03-26 21:25 UTC
