### ISSUE TITLE
[Bug] Some dialogs remain in original language after a language change

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12448] opened 2022-09-19 14:18 UTC
###### Reproduction Steps
1. Have AnkiDroid in system language
2. Change language to a different one (in this case English)

###### Expected Result
Language of the whole app is changed.

###### Actual Result
Language is changed for the most of the app but some dialogs remain in the original language. 
Affected dialogs:
1. Check database
2. Check media
3. Restore from backup
4. Interval in Card Browser
![Screenshot_20220919-122956_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/191038638-d4f1348c-a536-413b-bbfe-ab1fc499b15a.png)
![Screenshot_20220919-123248_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/191038672-deeea38c-db64-48ef-bd0e-7cd37197754e.png)

###### Debug info
AnkiDroid Version = 2.16alpha85

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.79 Mobile Safari/537.36

ACRA UUID = bd3df842-8d38-48ea-8cb8-9ef2d08fbca2

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment] 2022-09-19 14:30
Hey nice one!

```
Scheduler = std3
Crash Reports Enabled = true
DatabaseV2 Enabled = true
```

Those dialogs you mention are starting to come from the Anki Desktop code and it's translation services, for you, since you are using the new backend. 

(did you realize that also implied using a whole new set of translations and different tranlation service? it does - it is such a big change...but that's not something users really care about)

@dae - So it seems this bug may have to do with the language selector code not informing the new schema / backend code that we need to switch languages. Is there an API for this, or is there a cache to expire, or is this just missing us-over-here calling something that already exists? You may know off the top of your head

Thanks for reporting this

**Comment by pavreh** [comment] 2022-09-19 15:58
@mikehardy I realised a lot of translations are from Pontoon and I have been wondering if these translations will be updated for every (alpha) release as Crowdin translations are. Moreover,  if you tap Support AnkiDroid - Translate in AnkiDroid, it leads to Crowdin only. There could be links to both, Crowdin and Pontoon. But it is a topic for a new issue. :-) I am glad to help.

**Comment by mikehardy** [comment] 2022-09-19 16:39
Indeed - 

1) we need to start messaging the changes for translators in AnkiDroid (contributing, support etc) that Pontoon is a place to help with translations as well as Crowdin,

2)  *and* we need to work on frequency/freshness of the Pontoon translations which are at this point pretty static (we have not ingested changes from that system in months, and...have no plan to do so right now which is not good, I want a plan we just don't have one). I'm not sure if we can ingest just translations easily or if we must necessarily update the whole backend or not, the question bears investigating

I will peel this to two new issues yes - obvious-and-good idea

**Comment by dae** [comment] 2022-09-20 01:07
The question shown before checking a database is an Android string; the message shown after finishing is a backend one. I tested switching languages in the general settings, and the former did not change, but the latter did, so it seems the backend is performing correctly here, and the issue lies elsewhere.

**Comment by mikehardy** [comment] 2022-09-20 12:49
Well... :hankey: - re-labeling. Thanks for checking

**Comment by homocomputeris** [comment] 2022-09-21 00:07
This string is missing both at Crowdin and Pontoon:

![photo_2022-09-21_03-05-29](https://user-images.githubusercontent.com/7422433/191385943-fb8a7be7-9b03-4081-be38-e2379192c859.jpg)
```
AnkiDroid Version = 2.16alpha85

Android Version = 12

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; ONEPLUS A6003 Build/SQ3A.220705.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.68 Mobile Safari/537.36

ACRA UUID = 1467ed99-aea0-4803-9715-30e236817dbb

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by dae** [comment] 2022-09-21 03:29
I've logged the background one on https://github.com/ankidroid/Anki-Android/issues/12468

**Comment by dae** [comment] 2022-09-21 07:35
Issue with Check Database appears to exist in the stable release as well, so this doesn't look like a (recent) regression.

**Comment by homocomputeris** [comment] 2022-11-20 10:32
Still an issue

**Comment by david-allison** [comment] 2023-05-05 22:49
A fix for this issue should also include a test for https://github.com/ankidroid/Anki-Android/issues/13795

**Comment by pavreh** [comment] 2024-08-12 19:39
2.19alpha10 works perfectly. I cannot reproduce the bug anymore.

**Comment by david-allison** [comment] 2024-08-12 19:57
FANTASTIC!! Thanks for the feedback

**Closed** 2024-08-12 19:57 UTC
Labels: Bug, Priority-Low, Help Wanted, Needs Triage
