### ISSUE TITLE
[Bug] "Browse Cards" shows incorrect deck

### ISSUE THREAD

**Issue by xjqm-tao** [ankidroid/Anki-Android#15191] opened 2024-01-09 10:15 UTC
###### Reproduction Steps

1. Long press the deck.
2. click"Browse cards"

###### Expected Result
Show the contents of the long-pressed deck

###### Actual Result
Show the contents of other decks.

###### Debug info
AnkiDroid Version = 2.17alpha15 (e5b25f3fef737140ae396d1b212a8d638551500f)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = 22041216C

Hardware = mt6895

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 22041216C Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 13b991d9-a0fd-4ffc-8f8b-0b5c080f71cf

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment] 2024-01-10 22:52
Probably the cause is the same of #15072

**Comment by david-allison** [comment] 2024-01-11 15:23
Thanks, I'll aim to take this one on tonight

**Comment by xjqm-tao** [comment] 2024-01-27 00:34
> Thanks, I'll aim to take this one on tonight

There are some new discoveries on 2.17alpha16 and 2.17alpha17.It is correct to press a deck for the first time and enter the card browser.It is not correct to press another deck for the second time to enter the card browser, but it is still the deck that was pressed last time.

**Comment by david-allison** [comment] 2024-01-27 02:05
This should have been fixed in the latest alpha. Could you send a video of the issue?

**Comment by xjqm-tao** [comment] 2024-01-27 08:37
> This should have been fixed in the latest alpha. Could you send a video of the issue?



> This should have been fixed in the latest alpha. Could you send a video of the issue?
[https://filetransfer.io/data-package/xCjt7T5E#link](url)

**Comment by lukstbit** [comment] 2024-02-10 06:26
Fixed in #15389?
@xjqm-tao Can you please verify if the issues is fixed in the last beta version?

**Closed** 2024-02-11 12:12 UTC
Labels: Bug, Needs Author Reply, Home Screen
