### ISSUE TITLE
Default TTS Language

### ISSUE THREAD

**Issue by Jeylucifer** [ankidroid/Anki-Android#14409] opened 2023-09-07 11:39 UTC
I just wish there was a section to set the **default TTS language for all decks**

Because the language selection page that is shown every time and for each deck is very annoying for me.

I appreciate all the developers of this app ✨♥️

**Comment by BrayanDSO** [comment] 2023-09-09 08:16
Duplicate of #8140

**Closed by BrayanDSO** 2023-09-09 08:16 UTC
