### ISSUE TITLE
[Bug] "Card was modified" error with the V3 scheduler

### ISSUE THREAD

**Issue by matejdro** [ankidroid/Anki-Android#13167] opened 2023-01-30 16:27 UTC
###### Reproduction Steps

1. Review a backlog of cards, mostly using "Good" button
2. After a while, you will be unable to proceed, pressing Good would just produce an error

###### Expected Result

Review should proceed normally

###### Actual Result

![image](https://user-images.githubusercontent.com/507922/215534393-2caebe5a-2f15-47a5-91a2-8afd9d81875e.png)

This error seems pretty vague, is there anything else I can provide you to help you resolve this issue? I can try reproducing it again.

###### Debug info

```
AnkiDroid Version = 2.16alpha92

Android Version = 13

Manufacturer = Google

Model = Pixel 7 Pro

Hardware = cheetah

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro Build/TQ1A.221205.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.85 Mobile Safari/537.36

ACRA UUID = 85314e7b-0d43-4b96-a861-e60e9dd7f848

New schema = true

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment] 2023-01-30 18:22
This is a duplicate of https://github.com/ankidroid/Anki-Android/issues/12946

**Comment by david-allison** [comment] 2023-01-30 23:31
Closing as duplicate of #12946

**Closed by david-allison** 2023-01-30 23:31 UTC
