### ISSUE TITLE
Deprecate MaterialDialog and use AlertDialog instead

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13315] opened 2023-02-20 12:02 UTC
# PRs only will be accepted with a screenshot/video showing the dialog in the PR description 

Historically, the [MaterialDialog](https://github.com/afollestad/material-dialogs) dependency has caused some issues, e.g. #12669, and hasn't been dev-friendly, like disabling issues on their repository and forcing to upgrade to Kotlin in order to use it. Here's some pros and cons I thought about keeping it:

Reasons to remove it:
- It isn't very extensible
- Haven't got new releases for 3 years
- Their repo's issues is disabled
- They make dialogs inconsistent between the platform libraries that use AlertDialog by default (e.g. `Preference`) and where we use MaterialDialog
- It is harder to customize the style of the material dialogs
- One less dependency

Reasons to keep it:
- Avoid having the work of replacing it

So I'm in favor of replacing its usages with the platform `AlertDialog`. This can be done one by one, or a bunch of dialogs at a time (e.g. #12682), showing a video that the functionaly is kept after the change.

# Recommendations

1. One dialog per commit -> so it's easier to review and drop the changes if necessary, although probably the commits are going to be squashed
2. Check for linked open PRs to avoid duplicating work
3. Don't ask to assign the issue to you. You can start working on it immediately by warning here which class(es) you are working on
4. Add a screenshot of the dialog after the change. If you can add a video tapping the dialog's buttons, even better

**Comment by lukstbit** [comment] 2023-02-20 13:22
I'm on favor of this, could be a good first issue like the IDE lint errors one.

**Comment by rishujam** [comment] 2023-02-20 17:14
So do this need to be done class by class? If so I am working AbstractFlashcardViewer

**Comment by narendraanjana09** [comment] 2023-02-21 11:17
hey @BrayanDSO, I saw the code and looked for the MaterialDialog, I found that it's used for 81 times. How can I start working on it or is there anything else I need to know? Like right now are you taking opinions for it?

**Comment by BrayanDSO** [comment] 2023-02-21 15:52
@narendraanjana09, this became accepted, so the issue is open for pull requests. I've updated the issue's text with some recommendations. Feel free to ask anything you want

**Comment by david-allison** [comment] 2023-02-21 20:31
In https://github.com/ankidroid/Anki-Android/pull/13316/commits ([Add: Facade for AlertDialog.Builder](https://github.com/ankidroid/Anki-Android/pull/13316/commits/3167a20577608979ea364a4226203eb02f3bbd6f)), I introduce `AlertDialogFacade.kt`

This handles many of the standard `MaterialDialog` methods, and means we do not need to change the API

We need at the very least a replacement for the following:

```
checkBoxPrompt() { 
}
```

**Comment by david-allison** [comment] 2023-02-21 21:28
From a chat on Discord:

I want to [use a facade] to avoid code churn/bugs when converting to the new API (as appeared in 12682 with the missing `.show()`

Once the dependency is gone, we can quickly + safely inline the methods that we want to go via the IDE

**Don't care**:
I do feel that `.foo()` is cleaner than `.setFoo()`, but one way to do things is better (if we care, we'd abstract away `AlertDialog` with a wrapper)

**Minor push**
I'd like to consider keeping:
* `DialogListener` changes because `{ ... }` is cleaner than `{ _, _ -> ... }`
* `.show { ... }`
* More complex methods. I had a 5 second scan, but handling checkboxes seemed more difficult in `AlertDialog`
* `.attrRes` - custom method I added on MaterialDialog

**Comment by narendraanjana09** [comment] 2023-02-22 10:24
@BrayanDSO thanks for adding details, I'm working on **AbstractFlashcardViewer** class

**Comment by narendraanjana09** [comment] 2023-02-22 17:59
Hey @BrayanDSO, I have replaced two instances of MaterialDialog with AlertDialog in AbstractFlashcardViewer class. The first one was inside the showDeleteNoteDialog() method and another was inside NextCardHandler inner class, I have made these changes in two separate commits. Could you let me know what the next steps are for this issue? Should I continue to make more changes, or should I go ahead and create a pull request to merge these changes into the main branch of the project?

https://user-images.githubusercontent.com/60137237/220712234-d26aed53-6b39-4aae-ada7-0e03b92eba41.mp4

![Screenshot_20230222-230815_AnkiDroid](https://user-images.githubusercontent.com/60137237/220713545-01b5edc7-0e95-4da1-8f4a-e0653d3ab3a5.jpg)

**Comment by BrayanDSO** [comment] 2023-02-22 20:19
Particularly, I don't mind reviewing a bunch of dialogs at a single PR, so I'd say to put as much as you want on a PR. Whatever it's best for you it's best for me. If I were to do it myself, I'd suggest doing one class per PR so you can get quicker merges and avoid conflicts and rebases.

**Comment by david-allison** [comment] 2023-02-22 20:45
Something like https://github.com/ankidroid/Anki-Android/pull/13326 is so clean it doesn't feel worthwhile having two reviewers

**Comment by narendraanjana09** [comment] 2023-02-23 08:54
okay, I'm creating PR for AbstractFlashcardViewer class.

**Comment by Prince-kushwaha** [comment] 2023-02-24 03:04
I am working on OnRenderProcessGoneDelegate.kt and BasicImageFieldController.kt materialDialog

**Comment by narendraanjana09** [comment] 2023-02-24 07:58
I'm working on DatabaseErrorDialog.kt

**Comment by narendraanjana09** [comment] 2023-02-27 15:48
in DatabaseErrorDialog.kt, need assistance in handling parameter "waitForPositiveButton" in listItemsSingleChoice and  listItems 
and for the function "setActionButtonEnabled" in the dialog.

**Comment by niteshmandall** [comment] 2023-03-06 07:20
I want to work on this issue as previously, I have solved this issue in another app on which I am working.

![Screenshot 2023-03-06 124855](https://user-images.githubusercontent.com/108911562/223043814-fdea11a9-c0ae-4daa-aab2-2c06c8171f27.png)

**Comment by niteshmandall** [comment] 2023-03-06 20:26
I wanted to work on this issue.

**Comment by mikehardy** [comment] 2023-03-13 21:44
@niteshmandall please read the description ☝️ item 3

> Don't ask to assign the issue to you. You can start working on it immediately by warning here which class(es) you are working on

**Comment by SanjaySargam** [comment] 2023-03-15 10:54
I am working on DeckPicker.kt

**Comment by gajwani** [comment] 2023-03-30 19:55
I have worked on modifying `CardTemplateEditor` and because it is interconnected, I also modified `DiscardChangesDialog`. See #13525 .

**Comment by adityabarodiya** [comment] 2023-07-06 16:51
Can I work on this?

**Comment by lukstbit** [comment] 2023-07-07 03:25
@adityabarodiya There's no need to ask for permission, just choose a dialog that isn't migrated yet and it wasn't mentioned by someone here as being worked on.

**Comment by Viraj76** [comment] 2023-08-20 22:10
I also want to work on this can I ?

**Comment by david-allison** [comment] 2023-08-21 01:45
> Don't ask to assign the issue to you. You can start working on it immediately by warning here which class(es) you are working on

Feel very welcome to start!

**Comment by lukstbit** [comment] 2023-08-21 07:38
I wonder if it wouldn't be better to put a pause for work on this issue. We have Damien's PR that is going to delete a lot of classes some that still contain MaterialDialog usages(for example ModelBrowser). Changing those now seems like useless work both for  contributors and reviewers.

**Comment by david-allison** [comment] 2023-08-21 10:24
If it's causing conflicts, absolutely pause it

----

I suspect we can get Damien's PRs in by the end of the week. I've approved the backend change and I feel it'll go smoothly. 

I'll be looking to push through the PR in this repo shortly after

**Comment by BrayanDSO** [comment] 2023-08-21 14:14
Given the fact that the dialog migration PRs are pretty rare now, I assume that only the "hard" dialogs PRs are left, I mean the dialogs which need implementing some API.

So maybe it's time to discuss the API before progressing in this. I haven't thought on anything yet, but I'd like consider  `MaterialAlertDialogBuilder` and bottom sheet dialogs in the middle of it

**Comment by ritikrawat2447** [comment] 2023-12-22 08:18
I want to contribute to this issue, I have changed the MaterialDialog to AlertDialog in SharedDecksDownloadFragment.kt now I want to test this, so can anyone tell me what sharedDecksDownloadFagmet is used for and where it is used in the entire project so that I can test it .

**Comment by david-allison** [comment] 2023-12-22 09:29
> I want to contribute to this issue, I have changed the MaterialDialog to AlertDialog in SharedDecksDownloadFragment.kt now I want to test this, so can anyone tell me what sharedDecksDownloadFagmet is used for and where it is used in the entire project so that I can test it .

Typically, "Find Usages" in the IDE helps. If you're struggling, once you figure it out, add a KDoc comment explaining the use of the class, and put in a Pull Request

For this one:

Deck Picker - FAB - Get Shared Decks - Search - Download Deck

**Comment by neeldoshii** [comment] 2024-01-25 02:38
I am working on BackupPromptDialog conversion to AlertDialog.

**Comment by neeldoshii** [comment] 2024-01-26 10:40
I am taking up Tags Dialog and working on it for conversion from Material Dialog to AlertDialog

**Comment by neeldoshii** [comment] 2024-02-03 13:48
I am taking up DatabaseErrorDialog

**Comment by david-allison** [comment] 2024-02-10 20:38
Before closing, we should consider maintaining the background color change: 

See:
* https://github.com/ankidroid/Anki-Android/pull/15474

**Comment by neeldoshii** [comment] 2024-02-14 18:53
> Before closing, we should consider maintaining the background color change:
> 
> See:
> 
> * [ManageNoteTypes uses AlertDialog #15474](https://github.com/ankidroid/Anki-Android/pull/15474)

I'll fix it.

**Comment by david-allison** [comment] 2024-03-18 15:34
@Somesh-nayek What dialog are you trying, and what issues are you encounering?

**Comment by xYoussefMahmoudx** [comment] 2024-03-24 21:16
Hi, I was working on this issue as my first task. 
To replace the usage of the material Dialog in MaterialBuilderUtil.kt, I created a contentNullable extension method for AlertDialog.Builder class and defined it in AlertDialogFacade.kt class. I also created a setActionButtonEnabled extension method for AlertDialog instead of the built-in setActionButtonEnabled of Material Dialog. Additionally, in DatabaseErrorDialog.kt, I replaced the Material Dialog of the (DIALOG_DB_ERROR) with an AlertDialog. 
I'm willing to replace the other Material Dialogs in this class, but for now, the problem is I can't get screenshots of these dialogs in the app to make the PR. As mentioned above, to get it accepted, can you provide me with a sequence to produce this error so I can see the dialogs directly and take screenshots? Or is passing the test class of this class (DatabaseErrorDialogTest.kt) enough? (Sorry for any inconvenience, but I am still new.)

**Comment by david-allison** [comment] 2024-03-24 21:43
You're best to send a `patch`, rather than a textual explanation if you want to explain what's been done. You seem like you've got something working, so send in a Pull Request if tests pass, and you've produced a visual comparison of the changes

Initial thought (nitpick): `contentNullable` isn't required, `setMessage()` should work with a nullable value

**Comment by neeldoshii** [comment] 2024-03-25 05:15
@xYoussefMahmoudx Thank you for your interest in refactoring material dialog 
> I created a contentNullable extension method for AlertDialog.Builder class and defined it in AlertDialogFacade.kt class.

There is no need for creating an extension of `contentNullable`  you can access it using `message`. You can refer [this PR](https://github.com/ankidroid/Anki-Android/pull/15396/files).

> But for now, the problem is I can't get screenshots of these dialogs in the app to make the PR. 

You can try a workaround to test the dialog is either create a button and test on it or replace the Database_Error_Dialog with dialog you are able to access it  and test the dialog you have created.

For example you can access this by more --> check --> check database.  Replace the dialog with the one you refactor currently to test your changes (Note just use it for testing don't replace existing dialog)

```
 DIALOG_CONFIRM_DATABASE_CHECK -> {
                // Confirmation dialog for database check
                alertDialog.show {
                    title(R.string.check_db_title)
                    message(text = message)
                    positiveButton(R.string.dialog_ok) {
                        (activity as DeckPicker).integrityCheck()
                        dismissAllDialogFragments()
                    }
                    negativeButton(R.string.dialog_cancel)
                }
            }
```

**Comment by neeldoshii** [comment] 2024-05-20 15:59
Following is the Dialog's left now to migrate

1. `DeckSelectionDialog` needs triage causing bug when migrated to alertDialog.
2. `MaterialDialogUtil` almost done removing it and adding alertdialog.
3. `DeckPickerTest` will start it in 2-3 days if someone is gonna take just ping it and start it ;)

Wew only 3 more to officially completely migrate it.

**Closed** 2024-05-21 13:18 UTC
Labels: Accepted, Good First Issue!, Keep Open
