### ISSUE TITLE
[Bug] dialogue/notification not shown in corner case (locking screen while AnkiDroid is active)

### ISSUE THREAD

**Issue by tbm** [ankidroid/Anki-Android#7952] opened 2020-12-24 01:40 UTC
When showing updates (e.g. when importing a deck or doing a sync), there are two different modes:

* If you're in the app, you get a dialogue box
* If you're not in the app, you get a notification

But there is a third case and this doesn't work well: if you stay in the AnkiDroid app, but lock your screen - in this case, a notification is sent, but when you unlock the screen the notification automatically goes away because you're using the app. That clears the notification and you never have a chance to read it.

###### Reproduction Steps

1. Open app
2. Import deck or do a sync
3. While the dialogue box is shown, lock your screen
4. Wait a few seconds for operation to send
5. Unlock
6. You see there's a notification but it goes away before you can read it

###### Debug info

2.14.2 from Google Play

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment] 2020-12-24 08:18
Thank you very much for the report. 

May I ask whether it creates any problem in your use of the app? Are you reporting it because it's a trouble in your usage and you want to see it fixed, or only because it's a bug and reporting it is the right thing to do?

I personally don't expect to take the time to fix it, unless I hear that it's actually making the app harder to use for some people. Given that the messages state that import/sync is done and the goal is mostly to give feedback to a recent action/let the user know they can start reviewing again, I expect that missing the message have little importance.

To be honest, the problem is also that, as far as I know, the app only know whether the app is displayed or not, and not the reason why we can't display. I would expect privacy reason would ensure that we don't have right to know it.
You're entirely right that this is not expected.
I would state however that, if you use another app, don't pay attention to the notification, and open AnkiDroid, then it'll have disappeared without you being able to read it either. So this occurs even more frequently than that.

**Comment by mikehardy** [comment] 2020-12-24 13:17
Yeah this would involve actually changing the notification style after deciding which one to use - the app was live so we went with a more live notification style and *then* because the user goes away (lock screen) we would need to change style, I don't see that as a really high priority either personally as it would likely be a semi-large change to decouple notification presentation from data, add some application state listeners and make it so the presentation could be swapped  as state changes. Lots of work for not a bunch of gain vs other priorities at the moment.

But I'll grant its real at least

**Comment by tbm** [comment] 2021-01-04 10:43
> Are you reporting it because it's a trouble in your usage and you want to see it fixed, or only because it's a bug and reporting it is the right thing to do?

I mostly reported it because it's a bug, but it's certainly a fairly minor issue.  I just wanted to make you aware in case it's easy to fix, but if you want to close the issue that's fine with me.

> I expect that missing the message have little importance

Well, I guess missing the sync update doesn't matter much, but seeing the import updates is quite useful.  But yes, it's not the end of the world if you miss it.

> To be honest, the problem is also that, as far as I know, the app only know whether the app is displayed or not

I don't know anything about Android development. So there's no way to tell that the app is open but the screen is locked (vs the app not being open at all).

**Comment by tbm** [comment] 2021-01-04 10:47
> Yeah this would involve actually changing the notification style after deciding which one to use - the app was live so we went with a more live notification style and then because the user goes away (lock screen) we would need to change style

I don't think that's correct.

There are two prompts:

* First there's the "Importing" prompt
* If the app stays open, you get a popup "AnkiDroid: updated X of Y ...  OK" and you have to press ok
* If the app is not open, you get the same message but as a notification

I lock the screen when I see the "Importing" prompt.  So the screen is locked *before* you send out the second notification.  So I don't think it's true that you'd need to change the notification style afterwards.  You'd just need to change the logic that determines which one is shown (popup vs notification)

Right now the logic seems to be: app not open or app open bug screen locked

What I was suggesting is to change that and do:

* App not open: send notification
* App open but screen locked: show popup (that will be shown when I unlock my screen).

@Arthur-Milchior   suggests that might have access to the app state on Android, in which case what I suggest isn't possible.  But if you have access to the state, I don't think the change would be hard.

But again, it's a minor issue and I don't mind you closing it.

**Comment by tbm** [comment] 2021-01-04 10:55
Although I guess in a way sending the notification is the right thing to do when the screen is locked because that way you see that AnkiDroid is done.

**Comment by tbm** [comment] 2021-01-04 11:08
Ok, I've been playing around with this some more and noticed something interesting.

So far I only tested sync and import.

But this time I did "check media".

When I do "check media" and it eventually locks my screen because it takes a long time, two things happen:

* I get a notification saying "Media checked" and "AnkiDroid"
* When I then unlock I have a pop-up saying: "Media checked \n Media database rebuilt... \n OK"

And the pop-up goes away when I press "OK".

So this is exactly the behaviour I'd like to see for import and sync, too.

But what happens there is that I *only* get the notification, but not the pop-up.

So I guess the question is why there are two different behaviours (is that intentional?) and whether this could be unified.

**Comment by mikehardy** [comment] 2021-01-04 16:42
Interesting, I definitely would not have expected a difference between the two

**Comment by tbm** [comment] 2021-03-05 23:28
I think we established in the end that because of the inconsistency between the two cases that this is a bug, so this should stay open.

**Comment by Arthur-Milchior** [comment] 2021-03-13 00:15
I do not know whether it should be kept open. It may be a case where we won't fix, due to the difficulty relative to how much it would improve UX. But at the very least, it should be kept open until a human decide to close it

**Comment by dae** [comment] 2023-08-31 08:20
Given the amount of time that has elapsed and the lack of AnkiDroid developer resources, I'm going to close this now, and suggest you open a PR if you still consider it to be a problem.

**Closed by dae** 2023-08-31 08:20 UTC
Labels: Bug, Priority-Low, Needs Triage, Keep Open
