### ISSUE TITLE
[Bug] Using "OR" in search when filtered to one deck gives unexpected results

### ISSUE THREAD

**Issue by barthisius** [ankidroid/Anki-Android#8027] opened 2021-01-19 07:25 UTC
###### Reproduction Steps

1. Go to the Card browser
2. Select a deck from the drop down (example: `deck:Default`)
3. Press search, and enter a search containing the "or" operand (example: `card:1 OR card:2`)

###### Expected Result

All search results are from the chosen deck, including results matching either case.
Example: Functioning like a search on desktop Anki of `deck:Default (card:1 OR card:2)`

###### Actual Result

Results from the left-hand side of the OR are from the selected deck, but the right-hand side is searching **all** decks.
Example: Functioning like a search on desktop Anki of `deck:Default card:1 OR card:2`

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by iCarlosCode** [comment] 2021-01-23 19:48
OMG it works! I choosed one deck, and when I use the "OR" it searched through all decks for what was the right-hand side of the "OR" .

**Comment by barthisius** [comment] 2021-01-23 20:39
A workaround in the meantime is just to enclose your entire search in parentheses, but that shouldn't be necessary.
The problem looks like it's in `AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java` where `CardBrowser`'s `searchCards()` method concatenates a string specifying the deck with your search string. I'd suggest having it wrap the user's search in parentheses in order to avoid this, but I've never developed for Android before so it might take me a while to I figure out how to set up a testing environment before making a PR.

**Comment by barthisius** [comment] 2021-01-31 09:33
Okay I had tried putting together PR #8046 but it's failing the unit tests. Should be fixable but I might not have the chance to dig into it for a little while, so if someone else wants to take a shot at it in the meantime, feel free.

**Comment by ritvij14** [comment] 2021-03-26 07:27
@david-allison-1 can I work on this? I am currently not assigned to any issue. From what I read on discord and the explanation on this issue, all I have to do is modify the string being sent to search for (by adding parenthesis), and adding a unit test for this. The unit test would check for the string that gets sent and whether it always has that parenthesis or not.

Did I get that right? Please correct me if I went wrong somewhere.

**Comment by david-allison-1** [comment] 2021-03-26 07:31
Sure - it should just be a simple addition of parenthesis to the search (and adding a unit test to ensure against regressions), but do check the linked PR, it may be slightly more complex.

**Comment by ritvij14** [comment] 2021-03-31 11:49
Sorry about the late updates, but yea I am still working on this one and I wanted to ask a doubt:
https://github.com/ankidroid/Anki-Android/blob/c19389d77cd231b58fc44022601906e269585d74/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L1491-L1523

This function is the one that's handling the main searching tasks in `CardBrowser.java`. Now the issue is that when I am adding brackets to this line:
https://github.com/ankidroid/Anki-Android/blob/c19389d77cd231b58fc44022601906e269585d74/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L1505

and then running my code, Card Browser becomes empty when I open it. And this is what logcat says:-
```
2021-03-31 17:07:41.718 10900-11230/com.ichi2.anki D/CollectionTask$SearchCards: doInBackgroundSearchCards
2021-03-31 17:07:41.720 10900-11230/com.ichi2.anki V/Finder: Search query 'deck:"my_deck" ()' is compiled as 'select c.id from cards c, notes n where c.nid=n.id and ((c.did in (1615373780198) or c.odid in (1615373780198)) and ())  ORDER BY n.sfld COLLATE NOCASE, c.ord'.
```
This clearly tells that `searchCards()` is being called on the first startup of CardBrowser as well, but how should we tackle this?

**Closed** 2021-04-03 13:29 UTC
Labels: Good First Issue!
