### ISSUE TITLE
Unable to import: This isn't a valid apkg file.

### ISSUE THREAD

**Issue by Gloria-Li** [ankidroid/Anki-Android#4401] opened 2016-08-07 11:02 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Download the apkg file
2. Place it in directory "AnkiDroid"
3. Press import in AnkiDroid

###### Expected Result

The deck be imported.

###### Actual Result

This isn't a valid apkg file.
What's more, when I first imported a deck, it succeeded and when I tried to update it by importing one with a few cards added in it, the problem occured. I tried to solve it by deleting the deck in the app, but it turned out that the new deck still can't be imported. Then I tried to import the old again, and the poblem still exists. And the result is I can't import any card to my AnkiDroid right now...
![515706087579792874](https://cloud.githubusercontent.com/assets/20829896/17462031/71c40702-5cd1-11e6-84a6-18a591c29716.jpg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by hssm** [comment] 2016-08-12 23:14
The bug will be fixed in the next version. When this bug happens, only the first deck will correctly import.

So as a workaround for now, what you can do is open the recent applications menu and swipe off AnkiDroid which forces it to close. The next time you open it the first deck will import. You can keep doing this until you have all your decks imported.

**Closed by hssm** 2016-08-12 23:14 UTC

**Comment by ccfontes** [comment] 2016-11-06 21:43
In which version is this fixed?

**Comment by hssm** [comment] 2016-11-06 21:52
2.7

**Comment by ccfontes** [comment] 2016-11-06 23:41
Still same issue here with versions 2.7 and 2. 8alpha1

**Comment by hssm** [comment] 2016-11-07 00:18
You mean it only fails on the second import?

Or do you mean the error appears for a certain deck only? If so, attach that deck here.

**Comment by ccfontes** [comment] 2016-11-08 20:50
It fails on every import, including the first.

I created a new deck with just one card and still get the same error.

**Comment by timrae** [comment] 2016-11-28 01:27
Can you please attach the apkg file? We can't reproduce the error without it...

**Comment by ccfontes** [comment] 2016-12-03 00:37
Here it is. Thanks. 
[apkg.zip](https://github.com/ankidroid/Anki-Android/files/628589/apkg.zip)

**Comment by nolala** [comment] 2017-01-01 23:32
Having the same problem - import of the collection.apkg fails, unfortunately even on the first deck. What was the solution to the problem above, or are you still waiting for feedback?

**Comment by hssm** [comment] 2017-01-02 22:38
It is likely that the file is, in fact, not a valid file. The file that @ccfontes posted does not import in the desktop client either. The desktop gives a more informative error message, however:

>This file does not appear to be a valid .apkg file. If you're getting this error from a file downloaded from AnkiWeb, chances are that your download failed. Please try again, and if the problem persists, please try again with a different browser.

This is not an AnkiDroid problem, so I am leaving this closed.

**Comment by mikehardy** [comment] 2018-03-31 18:33
@farshad1880 also had a corrupt zip file - it wasn't an AnkiDroid problem. @timrae I don't think this is an actual bug anymore and may be closed? I can successfully import collections with multiple decks, and media, and they work fine (even collections that are actually corrupted-then-repaired zipfiles)

**Comment by DrewPlots** [comment] 2021-05-21 01:09
I've written up the fix on ankiforums, see here:
[](https://forums.ankiweb.net/t/created-colpkg-invalid-file-format-for-import/10148/3)

As @mikehardy mentioned (three years ago), a repaired ZIP file will allow opening "corrupt" **.colpkg**.
