### ISSUE TITLE
[Feature request] Export configuration 

### ISSUE THREAD

**Issue by hazel-bunny** [ankidroid/Anki-Android#16142] opened 2024-04-09 08:47 UTC
**Is your feature request related to a problem? Please describe.**

I had been using the 2.17alpha series for a long time. The github apks were installed using an app called obtainium. My phone, however, had goolag play store and goolag play services preinstalled.

When the 2.17 stable releases came out, goolag automatically replaced the github version of the app with the play store version. When I removed the play version and installed the github version, I was able to regain access to my database & media, but lost my ankidroid configuration including gestures and controls.

I have a very complex gestures and controls setup with options for a gamepad, keyboard, mouse and screen gestures. It takes hours to replicate. 

**Describe the solution you'd like**

Allow exporting ankidroid configuration to storage using SAF. If it was possible to export the ankidroid configuration, it would be possible to set this up once, make a backup and restore as necessary. Many other open source apps like keepassdx, fairemail and antennapod allow exporting their configuration, so I believe that this feature is a must have. It will also help custom ROM users who might need to migrate their settings to newer ROMs.

**Describe alternatives you've considered**

Neo backup app, which requires root.

**Additional context**

Please don't blame me for not disabling auto updates on play store, I disable it quite often and it comes back.

**Comment by david-allison** [comment] 2024-04-09 09:26
Thanks for the report! Is this a duplicate of: 

* https://github.com/ankidroid/Anki-Android/issues/9762

**Closed as not planned** 2024-04-09 09:44 UTC
Labels: Duplicate

**Comment by david-allison** [comment] 2024-04-09 12:35
Cheers! For GitHub linkage:

Duplicate of https://github.com/ankidroid/Anki-Android/issues/9762
