### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by hanpingchinese** [ankidroid/Anki-Android#4786] opened 2018-02-09 02:02 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Install 2.9alpha18 on Android 8.1 and launch app
2. Restart device

###### Expected Result
No crash

###### Actual Result
AnkiDroid crashes as part of startup procedure - i.e. does not need to be launched

###### Debug info
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.ichi2.anki, PID: 5265
java.lang.RuntimeException: Unable to create application com.ichi2.anki.AnkiDroidApp: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.ichi2.anki/.services.BootService }: app is in background uid UidRecord{c5888c8 u0a286 RCVR idle change:uncached procs:1 seq(0,0,0)}
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
    at android.app.ActivityThread.-wrap1(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by timrae** [comment] 2018-02-09 02:05
:(

**Comment by mikehardy** [comment] 2018-02-09 03:20
what version of Android is this? I tried to reproduce it with my test configuration on the Android Studio emulator which I currently have running as Nexus 5 / Android 6.0 / API 23, with AnkiDroid 2.9alpha18. Of course, when I read the logcat I see zero anki messages until I start the app so knowing your notification / configuration details may help as well. If I could reproduce this I'd take a look

**Comment by hanpingchinese** [comment] 2018-02-09 03:26
Thanks Mike - the only Android version I have tried is 8.1 on the Nexus 6P (please see "reproduction steps" in my report).

**Comment by mikehardy** [comment] 2018-02-09 03:39
Guess it's time to upgrade my emulator! I'll see what I can do. I will certainly report what I find. Just for information: I know there are notifications issues (they switched to "notification channels" with >= 8 if I remember correctly?) causing a separate bug where notifications don't show, it wouldn't surprise me if rules around background processes changed also as I know they are working towards better power management etc.

**Comment by hanpingchinese** [comment] 2018-02-09 04:31
Brand new emulator version was just released by Google, so definitely a good time to do those bug downloads.

https://developer.android.com/about/versions/oreo/android-8.0-changes.html#back-all

**Comment by mikehardy** [comment] 2018-02-09 05:21
Okay - I can reproduce it after creating a new emulator based on the Nexus 6P and Android 8.1 / API 27. I see the exact same log messages. 

I googled a bit, and it looks like we need to migrate from IntentService to JobIntentService from the compat library - https://developer.android.com/reference/android/support/v4/app/JobIntentService.html
(background reading here: https://developer.android.com/about/versions/oreo/background.html#services)

It is not quite as easy as simply altering BootService to extend JobIntentService and changing the work method signature there - a second-level issue in AnkiDroidApp.java:204 is seen after this where the instantiation takes place. I can't keep digging just this moment but altering AnkiDroid to be compatible with Android O is going to follow the same pattern lots of other apps have taken - it is hopefully a pretty focused change. I'll look at it more in the next couple days unless someone else generates a pull request before me

**Comment by hanpingchinese** [comment] 2018-02-09 06:08
Maybe a related issue: It looks like you're starting the BootService from your Application.onCreate(). You already start it from BootReceiver so that should be enough?  If you also need to start the BootService when the user launches the app, then maybe start it from the Activity.onCreate() which is guaranteed to be a foreground process. Also, in that case, maybe better to rename it to something like LaunchService to avoid confusion.

**Comment by mikehardy** [comment] 2018-02-11 19:52
As a new mobile developer I'm still researching the basic concepts of Intents, Services, Jobs etc to make sure anything I propose is coherent, but a quick note to mention that I researched just changing all of the notification/reminder stuff to a Job and it's not possible because we have a minSDK of 14 and JobService isn't until 21 - so we're definitely constrained to using the compat JobIntentService which will do the right underlying implementation for us. As for the previous comment if I get something to work here I'm most likely to do a straight conversion than attempt to untangle possible multiple invocations / logical paths, just to keep the patch smaller. Finally, it's worth noting that while AnkiDroid crashes on boot it does work on Android 8 for review, it's just notifications and reminders won't be enqueued on boot, they'll only happen when people use the app and it's in foreground (assuming I'm understanding these things correctly). At that point they'll fail for the semi-related separate logged issue that we haven't converted to notification channels either...

**Comment by mikehardy** [comment] 2018-03-08 13:15
If using current builds from source, this now has a workaround in place, and the app should not crash on startup.

**Comment by mikehardy** [comment] 2018-06-08 17:09
@timrae - current builds of the app are definitely not crashing on boot after the merge of #4795 - I think we should either close this bug and open an enhancement to support targetSdkVersion >= 26, likely by migrating from IntentService to JobIntentService, or alter this bug to be an enhancement and change the title...

**Comment by timrae** [comment] 2018-06-08 23:46
@mikehardy

Would you be able to create a new issue summarizing the road blocks to upgrading the target sdk?

**Comment by mikehardy** [comment] 2018-06-08 23:58
Yes - without actually having a go at implementing it (yet) it'll be in general terms but from what I can tell it's our services usage and notifcations usage and that's it (up to API 26 at least). I'll log one later this weekend - about out of open source hacking time for now

**Comment by mikehardy** [comment] 2018-06-18 00:36
I created #4883  which can be a clean enhancement to do the needful - this is not an active bug at the moment at least

**Comment by mikehardy** [comment] 2018-09-14 03:58
This should be merged and fixed. I no longer crash on boot on API>=26, even with targetSdk of 27. it's out with the alphas now, will be in 2.9

**Closed by mikehardy** 2018-09-14 03:58 UTC
Labels: accepted, bug
