### ISSUE TITLE
[BUG]: Deck options menu "Discard input" dialog is unintuitive

### ISSUE THREAD

**Issue by camoz** [ankidroid/Anki-Android#15782] opened 2024-03-05 16:13 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Open deck options, then (without changing anything) go back.

### Expected behaviour

Go back to previous screen.

### Actual behaviour

I get asked "Discard current input?"

### Debug info

```text
AnkiDroid 2.17.0 (anki 23.12.1 / 1a1d4d54)
```

### (Optional) Anything else you want to share?

This issue is about skipping the "discard changes" dialog when no changes were made to the deck options (and perhaps other menus, I don't know).

However I would also propose to change the wording to "Discard changes?" in case changes were made, since any user actions in the deck options are rather "changes" and not "input". Should I open an extra issue for that?

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-03-05 16:18
* Thanks! Agreed. Duplicate of https://github.com/ankidroid/Anki-Android/issues/14438

**Closed by david-allison** 2024-03-05 16:18 UTC
Labels: Bug, Needs Triage

**Comment by camoz** [comment] 2024-03-05 17:16
Not sure how I missed this, I searched existing issues... sorry.

What about changing "Discard current input?" to "Discard changes?" or similar (cf. last paragraph I wrote)?

**Comment by david-allison** [comment] 2024-03-05 17:22
No worries! Better to have people reporting issues than not now what's going on. Please give the linked issue a 👍 react.

The string we used is obtained from Anki Desktop, we're aiming for compatibility as we're building out the final pieces of functionality to hit feature parity.

Once this is completed, we can determine where to make changes

**Comment by camoz** [comment] 2024-03-06 05:27
Done, thank you!
