### ISSUE TITLE
[Bug] Login error after installing AnkiDroid for the first time on Android 12

### ISSUE THREAD

**Issue by gugutu** [ankidroid/Anki-Android#14964] opened 2023-12-13 16:46 UTC
###### Reproduction Steps

1. Install AnkiDroid. (Not installed before, or installed again after completely uninstalling)

2. Click `Sync from AnkiWeb`

![IMG_20231212_155104.jpg](https://github.com/ankidroid/Anki-Android/assets/59798823/fc05028d-d279-48e0-af18-e122fad3531f)

3. Enter email and password and log in

###### Expected Result

Log in normally

###### Actual Result

![Screenshot_2023-12-12-15-46-20-180_com.ichi2.anki.jpg](https://github.com/ankidroid/Anki-Android/assets/59798823/fb25238c-abd6-4074-8c32-f72e74cb8669)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.17alpha10 (50fa39cd561d83662cd5ef1f708b14a9a15c74ac)

Backend Version = 0.1.31-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 12 (SDK 31)

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2006J10C

Hardware = mt6889

Webview User Agent = Mozilla/5.0 (Linux; Android 12; M2006J10C Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 26e3157c-37a1-460b-b909-853b67e75fde

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by gugutu** [comment] 2023-12-13 16:58
Clicking `Get Started` will pop up the page requesting storage permission, but when clicking `Sync from AnkiWeb`, there is no request permission, which may be the cause of the problem.

![Screenshot_2023-12-12-15-47-08-667_com.ichi2.anki.jpg](https://github.com/ankidroid/Anki-Android/assets/59798823/d801781c-88d5-4cfa-898e-4fcbb01fccb9)

**Comment by david-allison** [comment] 2023-12-13 17:39
Thanks for the detailed report!

Duplicate of https://github.com/ankidroid/Anki-Android/issues/14650

We'll get it fixed before general release

**Closed as not planned** 2023-12-13 17:40 UTC
Labels: Duplicate
