### ISSUE TITLE
implementing access for android talkback to read text from flashcards  

### ISSUE THREAD

**Issue by vudeey** [ankidroid/Anki-Android#12883] opened 2022-11-25 00:36 UTC
the latest Anki version just works fine, but the text content of flashcards cannot be readout loud by Android's Talk Back feature. That's why I'd like to request this feature.

**Comment by criticalAY** [comment] 2022-11-25 09:10
refer [this](https://github.com/ankidroid/Anki-Android/wiki/Absence-of-voice-control-feature)

**Comment by eginhard** [comment] 2022-11-26 12:16
Duplicate of #6369 (also see #7913). Any help or feedback on these would be really appreciated, but I think currently it just doesn't work unfortunately.

@criticalAY TalkBack isn't related to voice control. It's a screen reader and it would be great if it worked well with AnkiDroid, but it's a tricky problem.

**Closed by eginhard** 2022-11-26 12:16 UTC
