### ISSUE TITLE
Feature request: Add mp3 files directly from the phone

### ISSUE THREAD

**Issue by barghest** [ankidroid/Anki-Android#4573] opened 2017-02-11 18:58 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[X  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

Hi,

Thank you for the nice app. I would be really happy if it was possible to import mp3 files directly from the phone just like you can already do with pictures.

Currently I can only record something by my own but I'd like to use other peoples recordings.

Thanks

**Comment by eginhard** [comment] 2017-02-11 21:47
Duplicate of #3107

**Closed by eginhard** 2017-02-11 21:47 UTC
