### ISSUE TITLE
Error -1 wal during synchronization

### ISSUE THREAD

**Issue by stouf** [ankidroid/Anki-Android#4213] opened 2016-04-12 23:41 UTC
Hi there !

I'm trying to synchronize my local decks with Ankiweb but I always get a synchronization error code -1, message "wal".
I had a look on the Internet but could not find anything so far :( Does anyone have an idea ?

My phone is a OnePlus 2, running Oxygen OS 2.2.1 (Android 5.1.1.), and I'm using AnkiDroid v2.5.4

**Comment by timrae** [comment] 2016-04-12 23:42
Can you post your debug info please?

https://ankidroid.org/docs/help.html

**Comment by stouf** [comment] 2016-04-13 04:52
Ah, sorry, I missed that. Here is

```
AnkiDroid Version = 2.5.4

Android Version = 5.1.1

ACRA UUID = 1f01e89f-0453-49d5-a308-acd85964e2d5
```

Is this enough ?

**Comment by stouf** [comment] 2016-04-19 23:46
No need for more information ?

**Comment by timrae** [comment] 2016-04-19 23:50
Sorry I haven't been able to access our bug reports database, there seems
to be a problem there and I've been really busy.

Are other developers able to access? Maybe we need to restart the server.

**Comment by hssm** [comment] 2016-04-20 01:07
It works for me but it takes a while to start responding (leave tab open for a few minutes).

There is no error report with that ID. I believe that is an error message from the server saying that we are sending a DB in the wrong mode.

You are trying to do a full sync, correct? Has sync ever worked on that device before? Do you use other Anki clients? Can you try restarting your device?

**Comment by stouf** [comment] 2016-04-20 01:38
Hi guys !

Thanks for responding :)

@timrae 

> Sorry I haven't been able to access our bug reports database, there seems to be a problem there and I've been really busy.

No problem at all. On the contrary, thanks a lot for your time, I truly appreciate.

@hssm 

> You are trying to do a full sync, correct?

Yes.

> Has sync ever worked on that device before?

I've never tried with this device no.

> Do you use other Anki clients?

Not right now. I was planning on using a Mac OS client, but I wanted to first sync the collection I have on my phone.

> Can you try restarting your device?

I did, but the same issue remains :(

Thanks for trying to help, I appreciate :)

**Comment by hssm** [comment] 2016-04-20 01:50
Can you navigate to the AnkiDroid directory on your device and tell me the name of every file that begins with `collection.anki2`?

**Comment by stouf** [comment] 2016-04-20 02:25
Sure ! Here is the list:

- "collection.anki2" (8.45MB)
- "collection.ankin2-shm" (32KB)
- "collection.anki2-wal" (414KB)

That's all.

**Comment by hssm** [comment] 2016-04-20 02:49
This tells us that it's definitely running in WAL mode which is a problem because AnkiWeb won't accept it. Your ROM seems to be forcing this feature which is undesirable in our case. 

This should only really affect full sync uploads. If you export your collection and import it on the desktop, then sync from the desktop the rest should work normally.

As for "fixing" the problem, we used to explicitly un-set WAL mode when closing the collection. There might be some value in putting that back in for cases like this.

**Comment by stouf** [comment] 2016-04-20 04:15
> Your ROM seems to be forcing this feature which is undesirable in our case.

I see... Is there anything I can do to help you guys with this ?

> This should only really affect full sync uploads. If you export your collection and import it on the desktop, then sync from the desktop the rest should work normally.

Confirmed, it now works and I can sync from both, a desktop and a smartphone :) Thank you !!

**Comment by hssm** [comment] 2016-04-20 11:58
I will let you know when we release an alpha or beta build that includes a workaround for the problem. It would be great if you could test it for us then.

**Comment by stouf** [comment] 2016-04-21 00:30
It would be my pleasure. Don't hesitate to poke me ;-)

**Comment by hssm** [comment] 2016-04-23 04:41
There is [an alpha build up](https://github.com/ankidroid/Anki-Android/releases/tag/v2.6alpha24) with a fix. Please let me know if this resolves the problem.

You can force a full sync upload to help you test:
1 - Settings -> Advanced -> Force full sync
2 - Go back and sync and choose to *upload*

Try it first with the version you have now to make sure it's still reproducible. Then install the alpha build from above and try the sync again. Of course, make sure you have backups before trying this.

**Comment by stouf** [comment] 2016-04-25 04:38
> Try it first with the version you have now to make sure it's still reproducible.

I tried and it occurred again.

> Then install the alpha build from above and try the sync again.

I got the error :( (I checked the version of AnkiDroid to make sure I was using the alpha build you gave the link to)

Here are the debug info:

```
AnkiDroid Version = 2.6alpha24

Android Version = 5.1.1

ACRA UUID = 1f01e89f-0453-49d5-a308-acd85964e2d5
```

**Comment by hssm** [comment] 2016-04-25 05:10
Sorry I got a little lazy and didn't test it well enough. This time I reproduced it and put in a proper fix. I'll let you know when the next alpha is out.

**Comment by timrae** [comment] 2016-04-25 05:13
I just pushed a new alpha for you

**Comment by stouf** [comment] 2016-04-25 05:22
Same error with the version 2.6alpha26 :(

```
AnkiDroid Version = 2.6alpha26

Android Version = 5.1.1

ACRA UUID = cac0696f-98bf-4f00-9266-20dfc065ebb4
```

**Comment by hssm** [comment] 2016-04-25 05:28
Well it looks like your OS is ignoring the setting completely and doing its own thing. I don't think there is anything more we can do in that case. You should file a bug report with Oxygen OS.

**Closed by hssm** 2016-04-25 05:28 UTC
Labels: bug, Priority-Low
