### ISSUE TITLE
Failed to load online content in 2.10beta2

### ISSUE THREAD

**Issue by C-Y-Liu** [ankidroid/Anki-Android#6109] opened 2020-05-05 13:57 UTC
After updating to the newest version I found the online pictures in my cards failed to load. At first I thought it was because of the poor internet connection, but the synchronizing function works well. And when I copied the content to 2.9.6, it showed successfully. I think there's something wrong here.   
![IMG_20200505_214641.jpg](https://i.loli.net/2020/05/05/1YPSJnqxWj2fGLD.jpg)

**Comment by david-allison-1** [comment] 2020-05-05 14:02
Hi @C-Y-Liu,

Thanks for the report. Could you provide the HTML of the field which is causing issues?

Thanks,
David

**Comment by C-Y-Liu** [comment] 2020-05-05 14:07
> Hi @C-Y-Liu,
> 
> Thanks for the report. Could you provide the HTML of the field which is causing issues?
> 
> Thanks,
> David

Front
```
<!-- Google图标 -->
<div class="google">
<img src='_Google_logo.svg' class="logo">
</div>
<!-- 搜索框 -->
<div class="head"><span class="bar">{{#《》}}Search:{{《》}}{{/《》}}{{^《》}}Site:{{Deck}}{{/《》}}</span><img class="mic" src="_Google_mic.svg"><img src="_Google_icon.svg" class="icon"></div>

<!-- 正面区块 -->
<div class="section">
<div id="front" class="items">{{Text}}</div>
</div>

<!-- 谷歌Gooo... -->
<div class="foot"><img src="_Google_foot.svg" style="width:80%"></div>
```

Styling
```
.card {
  font-family : serif;
  font-size : 18px;  
  text-align : left;  
  color : #222;    
  background-color : #fafafa; 
}
.icon{
float:right;
height:1.2em;
padding-left:5px;
}
.mic{
height:1.2em;
float:right;
padding-left:5px;
}
.head{
  /*border-radius : 2px;  *//*方形框*/
  border-radius : 1.2em;  /*半圆框*/
  box-shadow : 0 1px 3px 1px rgba(0, 0, 0, 0.16),0 0px 0px 1px rgba(0, 0, 0, 0.06);
  padding : 8px 12px 8px; 
  display:flex;
}
.bar{
width:100%;
white-space: nowrap;
overflow:auto;
}
.google{
  padding : 5px 0 10px; 
  text-align : center;  
}
.logo{ 
width:50%;
}
.foot{
  padding : 10px 0 10px; 
  text-align : center;  
}
/**** 卡片样式，阴影等 ****/
.section {
  background-color : #fff;  
  box-shadow  : 0 1px 2px 0px rgba(0, 0, 0, 0.16),0 0px 0px 1px rgba(0, 0, 0, 0.02);                       
  border-radius  : 2px;  
  margin : 8px 0 8px 0; 
}

.night_mode .section{
box-shadow:0 0 1px 1px rgba(255, 255, 255, 0.3);
background-color:black;
}
.night_mode .head{
box-shadow:0 0 1px 2px rgba(255, 255, 255, 0.3);
background-color:black;
}

/*正反卡片共同样式*/
.items{
  font-size  : 20px;            
  margin     : 0 12px;            
  padding    : 10px 8px;      
  line-height : 1.5em; 
}

hr{
  border     : 0;                   /*分割线宽*/
  margin     : 6px 12px;                   /*区块间隔*/
  border-top : 1px solid #e5e5e5;  
}


/*正面字段样式*/
#front{
  color      : #222;       /*字体颜色-黑色*/
  text-align : justify;       /*文本对齐-居左*/
  font-family: serif;
  padding:1.2em inherit;
}

/*背面字段样式*/
#back{
  color      : #222;       /*字体颜色-蓝色*/
  text-align : center;       /*文本对齐-居左*/
  font-family:cursive;
}

.night_mode #front{
color:white;
}
.night_mode #back{
color:white;
}
@font-face {font-family:C;src: url('Fonts/楷体.ttf');}

u { text-decoration: none; background-color: #ffff75; border-bottom: 2px solid #ec6c4f; }
uu { border-bottom: 1px solid #ec6c4f; }
.night_mode u { color: #a0a0a0; background-color: #505050; border-bottom: 2px solid #5f5f5f; }
blockquote{ border-left:3px solid red;padding-left:10px;margin:10px;}
```

back
```
<!-- Google图标 -->
<div class="google">
<img src='_Google_logo.svg' class="logo">
</div>
<!-- 搜索框 -->
<div class="head"><span class="bar">{{#《》}}Search:{{《》}}{{/《》}}{{^《》}}Site:{{Deck}}{{/《》}}</span><img class="mic" src="_Google_mic.svg"><img src="_Google_icon.svg" class="icon"></div>

<!-- 正面区块 -->
<div class="section">
<div id="front" class="items">{{Text}}</div>
</div>
<!-- 背面 -->
<div class="section">
<div id="back" class="items">When Would You Like to See This Again?</div>
</div>


<!-- 谷歌Gooo... -->
<div class="foot"><img src="_Google_foot.svg" style="width:80%"></div>
```

Contents in `Text` field
```
<details><summary>如何读书</summary><img src="https://s2.ax1x.com/2019/04/05/ARtr9g.png" border="0" /></details>
```

contents in `《》` field
```
Read
```

**Comment by mikehardy** [comment] 2020-05-05 14:40
@C-Y-Liu sorry you're continuing to experience problems, and looks like David is investigating but I just wanted to thank you again for testing and reporting. You can see we're trying and so far you're the only reports we've got :-). Good clear reports are quite valuable, thanks

**Comment by C-Y-Liu** [comment] 2020-05-05 14:48
> @C-Y-Liu sorry you're continuing to experience problems, and looks like David is investigating but I just wanted to thank you again for testing and reporting. You can see we're trying and so far you're the only reports we've got :-). Good clear reports are quite valuable, thanks

I should also thank you all for developing such a great app. I'm glad that I could help. 🙌

**Comment by david-allison-1** [comment] 2020-05-05 15:09
Thanks!

`<details><summary>如何读书</summary><img src="https://s2.ax1x.com/2019/04/05/ARtr9g.png" border="0" /></details>` works fine in 2.10alpha73

I've tested on 2.10beta2 with the full data you provided, I get the opposite: the image loads fine, and the images which are contained in the colleciton fail to load (expected, as they weren't provided)

![image](https://user-images.githubusercontent.com/62114487/81082097-b47ffe80-8eea-11ea-926e-b320e25f0f95.png)

@C-Y-Liu, can you confirm that: https://s2.ax1x.com/2019/04/05/ARtr9g.png loads on your device?

Thanks,

**Comment by C-Y-Liu** [comment] 2020-05-05 15:26
> Thanks!
> 
> `<details><summary>如何读书</summary><img src="https://s2.ax1x.com/2019/04/05/ARtr9g.png" border="0" /></details>` works fine in 2.10alpha73
> 
> I've tested on 2.10beta2 with the full data you provided, I get the opposite: the image loads fine, and the images which are contained in the colleciton fail to load (expected, as they weren't provided)
> 
> ![image](https://user-images.githubusercontent.com/62114487/81082097-b47ffe80-8eea-11ea-926e-b320e25f0f95.png)
> 
> @C-Y-Liu, can you confirm that: https://s2.ax1x.com/2019/04/05/ARtr9g.png loads on your device, and could you try loading it in the beta again?
> 
> Thanks,

Sorry, it still fails on my phone in the beta version.

**Comment by C-Y-Liu** [comment] 2020-05-05 15:44
@david-allison-1 I have tried several alpha versions. The problem starts to occur in 2.10 alpha64. Before that everything works fine.

**Comment by david-allison-1** [comment] 2020-05-05 15:56
@C-Y-Liu That's fantastic! Thank you.

If you have the time, could you try javascript debugging and see if you can capture the error generated: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

It's going to be tough to debug if it works fine for me. Sorry to put the effort back on you, thank you so much for the help, if you can throw anything back to me to look at, please do!

In the meantime, I'll see if anything looks fishy:

https://github.com/ankidroid/Anki-Android/compare/v2.10alpha63...v2.10alpha64

**Comment by mikehardy** [comment] 2020-05-05 15:59
Yeah, I just looked at the same diff link, unfortunately that was a really big diff. It's not just what we changed, it's that I pulled in the new appcompat dependency. If I were bisecting, I'd work a hunch and just change that one appcompat dependency back.

But we will be very constrained in helping until we can reproduce this.

The other thing I can think of is the device, perhaps this is somehow hitting the device adapter we shimmed in for the constrained / no external browser learning use case? 🤔

**Comment by david-allison-1** [comment] 2020-05-05 16:00
@C-Y-Liu Could you go to the Deck Picker and click "Get Shared Decks". Does it open in a web browser, or show a message?

**Comment by C-Y-Liu** [comment] 2020-05-05 16:06
> @C-Y-Liu Could you go to the Deck Picker and click "Get Shared Decks". Does it open in a web browser, or show a message?

@david-allison-1 It shows
```
AnkiDroid: No browser found,please visit web page by pc or mobile:https://ankiweb.net/shared
```

**Comment by david-allison-1** [comment] 2020-05-05 16:09
> > @C-Y-Liu Could you go to the Deck Picker and click "Get Shared Decks". Does it open in a web browser, or show a message?
> 
> @david-allison-1 It shows
> 
> ```
> AnkiDroid: No browser found,please visit web page by pc or mobile:https://ankiweb.net/shared
> ```

Found it!! Thanks so much 🙏 

<img height="200px" src="https://previews.123rf.com/images/sudowoodo/sudowoodo1905/sudowoodo190500004/122634988-winner-winner-chicken-dinner-funny-saying-vector-clip-art-illustration-cartoon-style-text-and-drawin.jpg"/>

---

@mikehardy Introduced in #5913

**Comment by mikehardy** [comment] 2020-05-05 16:15
Yep, no good deed unpunished on that one 😅 

@C-Y-Liu what is the browser configuration on your device? Do you have a WebView installed, but no actual browser, or a restricted browser? The more detail you can give us on your device (brand, model, operating system version, browser setup) the easier we can resolve this without affecting the intended goal of #5913

**Comment by C-Y-Liu** [comment] 2020-05-05 16:24
> Yep, no good deed unpunished on that one 😅 
> 
> @C-Y-Liu what is the browser configuration on your device? Do you have a WebView installed, but no actual browser, or a restricted browser? The more detail you can give us on your device (brand, model, operating system version, browser setup) the easier we can resolve this without affecting the intended goal of #5913 

I'm using MI8 Lite. 
I have installed webview as well as actual browsers. 
This is the information about my browser and webview test in a website
[https://www.whatsmybrowser.org/b/LVPYQ3K](https://www.whatsmybrowser.org/b/LVPYQ3K)
[https://www.whatsmybrowser.org/b/8AY7X](https://www.whatsmybrowser.org/b/8AY7X)
 
And the operating system is MIUI11.0.1 based on Android 10.

Hope this could help you.

**Comment by mikehardy** [comment] 2020-05-06 16:40
@C-Y-Liu 2.10beta3 will have a fix for this, it's in review now

**Closed** 2020-05-06 17:02 UTC

**Comment by mikehardy** [comment] 2020-05-06 17:07
ok 2.10beta3 is going to alpha first and as soon as google is done chewing on it I will promote to beta. Takes a couple hours but be on the lookout for an update, should fix this. Thanks again for reporting, happy reviewing!

**Comment by mikehardy** [comment] 2020-05-07 01:26
Took forever but 2.10beta3 is available now, hopefully it fixes this up

**Comment by C-Y-Liu** [comment] 2020-05-07 13:16
> Took forever but 2.10beta3 is available now, hopefully it fixes this up

Yes, it works! Thanks!
