### ISSUE TITLE
Forced full upload of media after media check

### ISSUE THREAD

**Issue by rogerwilco86** [ankidroid/Anki-Android#4195] opened 2016-04-04 09:51 UTC
Hi! 
I have been using ankiDroid for a long time.
Today I did a "check media," which took a long time, and then afterwords when I pressed the sync button, I was surprised to see it doing a _full_ upload.  I canceled the sync, I believe that I synced from my computer first, and then I went to SETTINGS -> ADVANCED -> FORCE FULL SYNC so that it would download rather than upload the full sync.

It started doing the full sync, as far as I could tell, so I put the phone in my pocket to let it work.  A few minutes later I looked and found it doing a full _upload_ instead of download.

So I let it complete its work and hoped that no damage was done.  (I will back up my data after this).

It didn't seem like it should be uploading when I specified that it should be downloading.

Sorry I have not attempted to recreate this behavior, as the data is valuable to me.

---
AnkiDroid Version = 2.5.4

Android Version = 4.4.4

ACRA UUID = 8726d1f4-6ab0-4eb5-bc6d-4a19d860f231

**Comment by timrae** [comment] 2016-04-04 14:04
> I went to SETTINGS -> ADVANCED -> FORCE FULL SYNC so that it would download rather than upload the full sync.

IIRC this option has no effect on media sync, only the main database.

**Comment by hssm** [comment] 2016-04-05 00:23
Yep, forcing full sync has no effect on the media database. The media changes being synced are a result of you using the *Check media* option. You did not mention what the result of the check was or whether you chose to remove unused files it told you about, but this is the cause of the behaviour you are seeing.

There will be a file named `collection.log` in your AnkiDroid folder that should explain what is going on and which files are being marked as added for upload. You might recognize these files from something like a deck you deleted previously. The other possibility is that those files are in fact not yet synced to AnkiWeb and uploading them was the correct thing to do.

In any case, I don't think there is anything abnormal going on. You should use the *check media* option on the desktop client and see if there are any used files (the desktop client shows you the list of files while AnkiDroid doesn't). If so, you can tell it to delete them and sync again and both clients will be in sync.

**Closed** 2016-06-29 14:45 UTC
Labels: waitingforfeedback
