### ISSUE TITLE
Cards not displaying

### ISSUE THREAD

**Issue by josemlucero** [ankidroid/Anki-Android#8157] opened 2021-03-10 03:42 UTC
When I enter a deck I see no card text only showd answer button,  if I press the button the screen only shows the three button, but not the card answer. 
If I choose edit card I see the field are apparently still store correctly. 

AnkiDroid Version = 2.14.5

Android Version = 11

ACRA UUID = 33c655ad-66eb-4e58-b677-2fd7ed929f80

Scheduler = std

Crash Reports Enabled = true

**Comment by david-allison-1** [comment] 2021-03-10 03:59
Hi, @mikehardy should have fixed this in 2.14.6. Could you try upgrading on the Play Store?

Marking as duplicate of https://github.com/ankidroid/Anki-Android/issues/7369#issuecomment-794497874. Could you direct any issues to the linked issue.

Thanks! 

David

**Closed by david-allison-1** 2021-03-10 03:59 UTC
