### ISSUE TITLE
TTS speeches Cyrillic symbols even if English language is set.  

### ISSUE THREAD

**Issue by Wiha77** [ankidroid/Anki-Android#6105] opened 2020-05-04 17:07 UTC
###### Reproduction Steps

1. Add the russian-english card
2. set TTS language as English
3. it will speak both side. Russian side sounds as Martian.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.9.7

Android Version = 7.0

ACRA UUID = 6d1b069d-dd70-4fea-81b3-5de16de4b06d

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment] 2020-05-04 17:31
Hi there! Yes, there is no support at current for the feature that would fix this https://docs.ankiweb.net/#/templates/fields?id=text-to-speech - it is available in Anki Desktop but no one has implemented it here yet, as a solution for the duplicate #5793 

I'm going to resolve this is a duplicate of that issue - you should follow along there and if you wanted to contribute a pull request implementing the feature that would be great!

**Closed by mikehardy** 2020-05-04 17:31 UTC
