### ISSUE TITLE
[Bug] Buttons in Reviewer does not change when card browser is open on top of reviewer

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13947] opened 2023-06-04 10:44 UTC
###### Reproduction Steps

1.  open the reviewer
2. open the card browser
3. open settings > display > buttons in the top bar (I'm using ankidroid in French, maybe not the exact translation)
4. Edit the buttons available
5. close the settings
6. close the card browser
7. observe the top app bar

###### Expected Result
The new buttons are added/removed to the top of the reviewer

###### Actual Result
No change between step 1 and 7

###### Debug info
Executed on current main

**Comment by BrayanDSO** [comment] 2023-06-04 11:58
Duplicate of #11046

**Closed by BrayanDSO** 2023-06-04 11:58 UTC
Labels: Priority-Low
