### ISSUE TITLE
[Bug] Cursor in card browser is not visible

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13502] opened 2023-03-26 13:31 UTC
###### Reproduction Steps

1. Go to card browser
2. search for cards

###### Expected Result
The cursor is shown and is not transparent so that it is easy to move between words and edit them

###### Actual Result
The cursor is transparent

###### Debug info
AnkiDroid Version = 2.16alpha94-debug

Android Version = 12

Manufacturer = OnePlus

Model = EB2101

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; EB2101 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.118 Mobile Safari/537.36

ACRA UUID = 4ffa3fea-6003-44a0-b914-0919027ac81d

New schema = true

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment] 2023-03-26 13:33
I would like to work on this

**Comment by criticalAY** [comment] 2023-03-26 13:34
> I would like to work on this

Umm I have already fixed it

**Comment by SanjaySargam** [comment] 2023-03-26 13:39
> > I would like to work on this
> 
> Umm I have already fixed it, Thankyou though

Ok no worries

**Comment by SanjaySargam** [comment] 2023-03-26 13:39
> > I would like to work on this
> 
> Umm I have already fixed it, Thankyou though

Ok no worries

**Comment by BrayanDSO** [comment] 2023-03-26 21:14
Duplicate of #12337

**Closed** 2023-06-07 01:13 UTC
