### ISSUE TITLE
AnkiDroid-folder unavailable

### ISSUE THREAD

**Issue by LovolaAnki** [ankidroid/Anki-Android#16275] opened 2024-04-26 17:32 UTC
Hey everyone!

When I try to open Anki (using android) it says "AnkiDroid-folder unavailable" and then I arrive on a page for advanced settings.

It seems as it has to do with the /storage/emulated/0/Ankidroid folder.

The only folders that I can find is the following:

![Screenshot_20240426_152853_Gallery](https://github.com/ankidroid/Anki-Android/assets/168220154/1d14a289-d6d5-4d53-a13f-982edf3e7356)

Haven't reinstalled or updated it. This just occured out of nowhere.

Is there any way to solve this? I have a folder with backup files. I have a folder with all the media (collection.media). So the data is there. 

//worried user.

**Comment by david-allison** [comment] 2024-04-26 17:48
Google's revoked your phone's access to `/AnkiDroid`, see: https://github.com/ankidroid/Anki-Android/wiki/Full%20Storage%20Access

**Comment by LovolaAnki** [comment] 2024-04-28 08:29
Thanks! Do you know why they have decided to revoke that access?

**Comment by david-allison** [comment] 2024-04-28 08:47
The goal of scoped storage is to protect the privacy of app and user data. This includes protecting user information (such as photo metadata), preventing apps from modifying or deleting user files without explicit permission, and protecting sensitive user documents downloaded to Download or other folders.

Apps using scoped storage can have the following levels of access (actual access is implementation specific).

* Read and write access to their own files with no permissions
* Read access to other apps' media files with READ_EXTERNAL_STORAGE permission
* Write access to other apps' media files is allowed only with direct user consent (exceptions granted to System Gallery and apps that are eligible for All Files access)
* No read or write access to other apps' external app data directories

https://source.android.com/docs/core/storage/scoped#app-access-restrictions

----

In addition: it means that Android wipes app data when apps are uninstalled

**Comment by david-allison** [comment] 2024-04-28 08:53
Closing this as a duplicate of #14423 (as there's no work to be done here)

* #14423

Feel free to continue the discussion, just moving this out of our active work queue, as I believe we've improved this for 2.18

**Closed** 2024-04-28 08:53 UTC
