### ISSUE TITLE
[BUG]: Statistics at the bottom of the deck page is out of screen.

### ISSUE THREAD

**Issue by xjqm-tao** [ankidroid/Anki-Android#14804] opened 2023-11-24 11:14 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

When the language is Chinese, the text at the bottom of the deck page exceeds the screen.
![IMG_20231124_190219](https://github.com/ankidroid/Anki-Android/assets/126331411/1dfd48d5-18f0-4e0e-a3ba-6c18f961e10a)

### Expected behaviour

Can see the complete text

### Actual behaviour

Incomplete text

### Debug info

```text
AnkiDroid Version = 2.17alpha6 (393f61b229a26ec97eb13c83f0d1f09652f776c2)

Android Version = 13

ProductFlavor = full

Manufacturer = Xiaomi

Model = 22041216C

Hardware = mt6895

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 22041216C Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 13b991d9-a0fd-4ffc-8f8b-0b5c080f71cf

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by snowtimeglass** [comment] 2023-11-24 11:29
Seems to be a duplicate of https://github.com/ankidroid/Anki-Android/issues/14641

**Comment by xjqm-tao** [comment] 2023-11-24 13:05
> Seems to be a duplicate of #14641
Sorry, My English is poor,I didn't see it.But it's still a little different. I use the latest version.I found that it can be displayed completely when switching to English language.But it is incomplete when it is in Chinese language.The picture is not rounded.

**Comment by david-allison** [comment] 2023-11-24 14:13
Thanks for the report! Duplicate of:

* https://github.com/ankidroid/Anki-Android/issues/14641

Once the linked issue is fixed, this will also be fixed

**Closed by david-allison** 2023-11-24 14:13 UTC
Labels: Duplicate
