### ISSUE TITLE
[BUG]: [2.19alpha1] template editing: missing save button / card type switch animation glitch / front replaced with css

### ISSUE THREAD

**Issue by khonkhortisan** [ankidroid/Anki-Android#16467] opened 2024-05-23 22:54 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

review→Ultimate Geography [Extended] note type→✏️ edit→Cards
scroll the card type list to make the last one visible: Map - Country
tap the last one
optionally experience behavior 1 buttons temporarily disappearing
optionally experience behavior 2 card type tab animation glitch
switch to css, add some text
open other apps to use up the memory?
switch back to Anki, wait for the center logo to go away, behavior 3: now it's on the front side which is replaced with the edited css text

### Expected behaviour

✔️ 👁️ ≡ ⋮ buttons stay there, card type tab text and underbar animation is smooth, card template texts stay where they are

### Actual behaviour

1. when switching card type tabs, the top-right ✔️ 👁️ ≡ ⋮ buttons do one of:
- 🟢 stay there
- 🟡 disappear during the animation then come back
- 🔴 are missing by the time I want to save.
Copying to clipboard, re-opening the template editor, pasting would allow saving changes.
![Screenshot_20240523-125422](https://github.com/ankidroid/Anki-Android/assets/1996449/8c22d81e-2b8d-43fa-9241-724d71ea1c7e)

2. when switching card type tabs, it:
- 🟢 animates scrolling them to center the selected one. or
- 🟡 does the same, then jumps backward a small amount in the animation, then continues again. This applies to both the text and the underbar.
It seems more likely to glitch if I scroll all the way from the end tabs then from adjacent tabs.
independent: It can glitch the tab scroll while the buttons are visible, and it can glitch the tab scroll while temporarily hiding the buttons.
https://github.com/ankidroid/Anki-Android/assets/1996449/9ccf0881-9b43-4d4c-adde-d991f90926f8

3. reloading the template editor when switching back to Anki keeps the edited css text but switches to the Front side, so instead of front/back/css, it has css/back/css.
  a. switch to last card type tab, switch to css, type something in `html {background-image: url(_background_geography.jpg); background-size: cover;}`
  b. open other apps to use up the memory
  c. come back to Anki, it's on the front side, 🔴 with the entire front side replaced by the css including my edit.
Saving at this point would cause front template loss.
![Screenshot_20240523-125633](https://github.com/ankidroid/Anki-Android/assets/1996449/e69a6412-f74f-4184-89b8-d648ab24954f)

### Debug info

```text
AnkiDroid Version = 2.19alpha1 (a15da1f476a438b5fb3eee87905b10b2e3d94b6c)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = FIH

Model = EC1002

Hardware = mt6761

Webview User Agent = Mozilla/5.0 (Linux; Android 11; EC1002 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.124 Safari/537.36

ACRA UUID = c8fe5a3e-6bce-4976-867c-42a883891f6b

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-06-10 21:21
@BrayanDSO I believe we saw this a while back with a reproduction case, do you recall where?

**Comment by BrayanDSO** [comment] 2024-06-10 22:04
#14086

**Comment by david-allison** [comment] 2024-08-03 18:00
Closing as duplicate of https://github.com/ankidroid/Anki-Android/issues/14086

**Closed by david-allison** 2024-08-03 18:00 UTC
Labels: Priority-High, Bug, Needs Triage, Card Template Editor
