### ISSUE TITLE
importing suddenly stopped working correctly

### ISSUE THREAD

**Issue by ihajat** [ankidroid/Anki-Android#4389] opened 2016-07-29 15:09 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. import apkg
2. import several more

###### Expected Result

all apkg imports showing the correct cards

###### Actual Result

last set of cards imported from apkg file, shows the cards of the previous imported apkg file???

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by hssm** [comment] 2016-07-30 03:48
I'm afraid I can't reproduce this behavior. I have imported 5 apkg files in a row without any issue.

You will need to provide more details or a reproducible test case if you want us to look into it any further. If you are using a version of AnkiDroid earlier than **2.6.1** then this issue is invalid.

**Comment by ihajat** [comment] 2016-08-01 10:06
ok, a few extra information:
1. normal decks are ok, only decks using media ( jpgs ) affected.
2. I have two folders, I guess, only one is required, where I have jpg files and a txt file, the txt file looks like:
"<img src=""Image001.jpg"">"	"<img src=""Image002.jpg"">"
"<img src=""Image003.jpg"">"	"<img src=""Image004.jpg"">"

I have this in both the collection.media folder under anki and User 1/collection.media folder also.
This generates a deck, on the desktop app It looks ok. I then export the apkg file, which I import into the android version. This deck (politics), when I use it, on the android, has the same cards as the previous deck ( idioms )

any ideas, where its getting contaminated?

**Comment by hssm** [comment] 2016-08-01 11:09
What happens if you create a new, empty profile on the desktop client, and try importing those apkg files into that one?

**Comment by ihajat** [comment] 2016-08-01 14:14
If you export deck, then reimport it, back into the desktop client, then , it is ok, it works correctly.
There is another way to do this, but, I don't know how? Instead of importing the txt file, that points to the jpgs, I can create an empty deck, goto tools -> media import, point to the folder. But, I don't know how to point to image001.jpg for card #1 front and image002.jpg for card #1 back, image003.jpg for card #2 front and image004.jpg for card #2 back, etc????

**Comment by hssm** [comment] 2016-08-03 06:52
To be honest, I don't understand what you are doing. Your description is really confusing.

Maybe the problem is fixed by [this change](https://github.com/ankidroid/Anki-Android/pull/4391). I will let you know when the next beta is out so you can test it.

**Comment by ihajat** [comment] 2016-08-03 09:32
I managed to get it to work, by creating a new profile and importing the txt file that points to the jpgs. So, either the profile is corrupt or has too many decks?

However, out of curiosity, how would you create cards, from images. The front and back of the card pointing to an image ( obviously, not the same image )???

**Comment by hssm** [comment] 2016-08-03 10:19
I still don't understand what part of the process involving AnkiDroid is breaking down. AnkiDroid is not capable of importing txt files. It will only import apkg files that you export from the desktop client. You are not being clear about what you are doing.

Regarding image import, if you have pairs of front/back side images, you should create a spreadsheet document with two columns where each column contains the file name of each side. Then you can import that file as a csv and map each column to each field. The media import add-on only works for 1 image at a time so it will not work in your use-case.

**Comment by ihajat** [comment] 2016-08-03 14:43
Hi,


It's very simple. I want to import images for both the front and back. Is this possible? I tried the media import, but, although, it allows the same image for both the front and back ( which is obviously pointless ) I can't see how you can import both the image question and image answer for the front and back?


regards

________________________________

**Comment by hssm** [comment] 2016-08-04 06:37
I am going to close this issue since you are unable to demonstrate a **bug in AnkiDroid**.

I have already given you one possible approach to achieve what you want. You are better off asking (or searching, first, since this has come up before) for help on the [official Anki support forums](https://anki.tenderapp.com/discussions).

**Closed by hssm** 2016-08-04 06:37 UTC
