### ISSUE TITLE
[BUG]: Cannot paste email and password on login screen

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#14379] opened 2023-09-02 22:24 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Download AnkiDroid parallel A
2. Install
3. It asks to enter email and password
4. Copy-paste email and password from password manager

### Expected behaviour

Paste email and password.

### Actual behaviour

Pasting both email and password impossible: no menu, no Gboard clipboard button.

### Debug info

```text
AnkiDroid Version = 2.17alpha1 (e817d891c70a05b86aa10690f5a5d5e2b1c7ad2d)

Android Version = 13

ProductFlavor = full

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; ONEPLUS A6003 Build/TQ2A.230505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.58 Mobile Safari/537.36

ACRA UUID = 134abe2c-e359-4a4e-9ad5-bea9e7c5531c

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by savitore** [comment] 2023-09-05 13:34
can i work in this?

**Comment by david-allison** [comment] 2023-12-08 20:02
Moving to 2.18 unless we can get reproduction steps

**Comment by BrayanDSO** [comment] 2024-02-20 23:02
Closing as can't reproduce

**Closed by BrayanDSO** 2024-02-20 23:02 UTC
Labels: Bug, Can't reproduce, Needs Triage, 2.17-alpha
