### ISSUE TITLE
"Automatic display answer" - Add option to Bury card when next question is shown automatically

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3869] opened 2015-11-24 17:28 UTC
The "Automatic display answer" feature (which should probably be renamed "Automatically display answer") sounds great in theory, but I don't like that it automatically selects Again if I don't answer in time. It would be better if users could select the action that AnkiDroid takes if the time runs out before he/she rates the card. Personally, I would love to set it to Bury the card, so that I don't upset the SRS algorithm by being inattentive at the wrong moment.

The current "Again" behavior can lead to a case like this: I'm chugging along, answering cards, when suddenly I'm distracted by someone walking into the room. A Mature card comes up on my phone, the time runs out, and it gets rated Again and sent back to relearn, breaking the SRS algorithm. This could happen several times in a row before I realize and put a stop to it. 

While it's true that in this case I could hit Undo over and over until I get back to my last truly answered card, it could be difficult to remember where I last left off. Also, if Anki goes idle for some time, or I clumsily navigate to the deck screen to stop the onslaught of cards, or I relaunch Anki from the notification bar, I think I'd lose the Undo capability. 

On the other hand, if I had it set to Bury the card if it went unanswered for X seconds, I could always unbury that card later. Worst case scenario, I see the card the next day. This is much less disruptive to the SRS algorithm, while still having all the benefits of keeping me focused.

**Comment by eginhard** [comment] 2015-12-01 19:03
Duplicate of #2609

**Closed by eginhard** 2015-12-01 19:03 UTC
