### ISSUE TITLE
[Bug] MIUI: Latex fraction bar is not shown in Android 10 dark mode

### ISSUE THREAD

**Issue by tilmanrpk** [ankidroid/Anki-Android#8119] opened 2021-02-19 16:36 UTC
###### Reproduction Steps

1. Turn dark mode on
2. Enter \(\frac{1}{2} \) 
3. Tap the preview button

###### Expected Result
Fraction (with bar) is shown

###### Actual Result
Fraction without bar (like \substack) is shown

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by irenenserrano** [comment] 2021-03-26 22:10
Is this issue still available for solving?

**Comment by david-allison-1** [comment] 2021-03-26 22:15
Sure! Make sure you can reproduce it first. We've updated MathJax for 2.15 already.

I don't know how complex this one will be to solve.

**Comment by irenenserrano** [comment] 2021-03-28 18:17
@david-allison-1 I actually am having trouble replicating the problem, but not just in dark mode. I have the following card made up, but I can't get the fraction to display properly.
![image](https://user-images.githubusercontent.com/60762137/112762925-28217300-8fb7-11eb-8fda-faa8400de9d2.png)
![image](https://user-images.githubusercontent.com/60762137/112762935-34a5cb80-8fb7-11eb-86ce-405630e77cd0.png)

**Comment by david-allison-1** [comment] 2021-03-28 18:20
From memory: `\(\frac{1}{2}\)`

**Comment by irenenserrano** [comment] 2021-03-28 19:17
@david-allison-1 Thank you for the speedy response! I've made sure to check on 3 different devices, but I cannot replicate the bug. I guess this issue can be closed then.

**Comment by david-allison-1** [comment] 2021-03-28 19:57
Can you replicate it on 2.14.x? https://github.com/ankidroid/Anki-Android/releases/download/v2.14.6/AnkiDroid-2.14.6.parallel.A.apk

**Comment by irenenserrano** [comment] 2021-03-28 22:23
@david-allison-1 I still cannot replicate the bug.

**Comment by david-allison-1** [comment] 2021-05-27 23:11
@tilmanrpk  is this still an issue?

**Comment by tilmanrpk** [comment] 2021-05-27 23:19
Oh completely forgot about it. If it's not easily to replicate I think its an issue with miui then. The fraction bar is also not invisible it is just a very dark grey so almost invisible. Some other apps like snapchat have similar problems with the miui dark mode. If I had to guess it may have something to do with the specific color or theme used so that miui treats it like background? I don't know.

**Comment by david-allison-1** [comment] 2021-05-27 23:42
> Oh completely forgot about it. If it's not easy to replicate I think its an issue with miui then. The fraction bar is also not invisible it is just a very dark grey so almost invisible. Some other apps like snapchat have similar problems with the miui dark mode. If I had to guess it may have something to do with the specific color or theme used so that miui treats it like background? I don't know.

Does this fix your issue: https://github.com/ankidroid/Anki-Android/issues/8150#issuecomment-795071385

**Comment by tilmanrpk** [comment] 2021-05-28 15:46
Of course but then thr app is not in dark mode

**Comment by david-allison-1** [comment] 2021-05-28 15:53
OK, I'm going to close this as a duplicate of #8150, glad we (eventually) figured out the problem

Please don't treat this as 'closed forever', if there's more, please let us know

**Closed** 2021-05-28 15:53 UTC
Labels: Duplicate
