### ISSUE TITLE
NullPointerException while saving note.

### ISSUE THREAD

**Issue by gayatriii0803** [ankidroid/Anki-Android#16668] opened 2024-06-28 06:33 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1.Go to Reviewer
2.Click on edit note
3.Click on copy note
4.Save the copy note
5.Save edit note.

### Expected behaviour

The edit note should be saved without any error.

### Actual behaviour

Getting error while saving edit note.

https://github.com/ankidroid/Anki-Android/assets/119813120/0b5d1f97-fa6b-4656-8fae-63a467c0ede3

### Debug info

```text
AnkiDroid Version = 2.19alpha4-debug (7a48b84ffb93d69fe4d64307cd84d57ac0be624b)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 6.0.1 (SDK 23)

ProductFlavor = amazon

Manufacturer = OPPO

Model = CPH1701

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0.1; CPH1701 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = fc11ca4a-c1c1-4186-a201-d21b0e7aae16

FSRS Enabled = false

Crash Reports Enabled = false
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by gayatriii0803** [comment] 2024-06-28 06:38
I would like to work on this issue.

**Comment by criticalAY** [comment] 2024-06-28 16:10
Duplicate of #16569 hence closing it

**Closed by criticalAY** 2024-06-28 16:10 UTC
Labels: Bug, Needs Triage
