### ISSUE TITLE
Adding an image to a field of a new card will replace any other content from the field.

### ISSUE THREAD

**Issue by AgarwalPragy** [ankidroid/Anki-Android#3958] opened 2015-12-05 16:46 UTC
Steps to reproduce:

- In Ankidroid, on the home screen, click the blue + button, and choose to "Add note".
- Type in something in the Front field, or add images or other content.
- In the front field, click the attach icon. Choose add image. Choose camera.
- Take a pic, and select the tick mark.

Result: A new image tag is seen in the front field, and all previous content in the front field has been overwritten.

Expected: The new image tag should be appended at the cursor location, and shouldn't overwrite the previous contents.

**Comment by eginhard** [comment] 2015-12-05 17:24
Duplicate of #3669

**Closed by eginhard** 2015-12-05 17:24 UTC
