### ISSUE TITLE
Simple drawings within AnkiDroid

### ISSUE THREAD

**Issue by Olifair** [ankidroid/Anki-Android#4620] opened 2017-04-16 10:14 UTC
Feature Request:

It would be great if simple drawings could be added to a card in extended mode directly from within Anki. There is code in Anki that allows drawing during testing. This might perhaps be reused also to create cards ?
This would really simplify the usage of drawings for learning. 
Thanks for considering this.
Olifair

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment] 2017-04-16 11:25
Duplicate of #1633

**Closed by eginhard** 2017-04-16 11:25 UTC
