### ISSUE TITLE
2 options mode (again/easy) instead of 4 (again/hard/good/easy)

### ISSUE THREAD

**Issue by dhysuiej** [ankidroid/Anki-Android#12859] opened 2022-11-20 14:41 UTC
**Is your feature request related to a problem? Please describe.**

Pretty much all other flashcard apps I've used so far have only two options available for the users to mark whether they remembered the card or not, and the time for the next time when the card will be shown again is not shown.

**Describe the solution you'd like**

A way to activate a mode where only the 2 options Again/Easy are shown on each card without showing when will be the next time for the card to appear again.

**Additional context**

When I started using Anki, having 4 options indicating the difficulty for each card with the time was kind of overwhelming, since it basically implied to me that I would need to make some decisions that other flashcard apps did automatically, so what's the point of using Anki anyway.

Regardless, I started using the app and selecting the option Again if I didn't remember the card or the option Easy if I did, that way the card would be either be presented again during the same session, or put on schedule to show again a few days later, which is how I would expect a flashcard app to work. I'm assuming the time that a card is put on schedule to be presented again depends somehow on how often I forgot the card.

**Comment by mikehardy** [comment] 2022-11-20 15:16
Hi there!
This is not supported upstream in Anki, and we must maintain compatibility with them, thus it will not be implemented.

This is roughly a duplicate of #10961 and would require a UI interface workaround to collapse responses to the 4 supported

**Closed by mikehardy** 2022-11-20 15:16 UTC

**Comment by 825i** [comment] 2025-01-05 13:47
I don't see how adding a toggle to remove 2 buttons in the UI would "break" anything. There is literally a massive "advanced" section of the settings which allows all sorts that totally "breaks Anki".

This on the other hand would actually be useful for you know. The hundreds of thousands of people who would actively use it... Just a simple toggle to remove the "Easy" and "Hard" buttons. Is that really so much to ask?

**Comment by mikehardy** [comment] 2025-01-05 20:03
@825i we welcome PRs, but careful with adversarial tone

**Comment by david-allison** [comment] 2025-01-05 20:13
1. Already exists for the new reviewer
2. We should make **strong** attempts to avoid deviating from upstream, and when we do, we should do so in a way which doesn't provide leverage for people to pressure upstream. ESPECIALLY when it gives people justification to request using a similar tone to the message above. 

We've put in a lot of thought into (1) to make this possible. AnkiDroid still has a fair number of ducks to put in order with regards to ecosystem compatibility, and wherever possible, we should be **positively** contributing upstream, so changes can flow downstream, rather than applying pressure by breaking compatibility.

**Comment by domonnss** [comment] 2025-06-24 08:35
> 1. Already exists for the new reviewer
> 
>     2. We should make **strong** attempts to avoid deviating from upstream, and when we do, we should do so in a way which doesn't provide leverage for people to pressure upstream. ESPECIALLY when it gives people justification to request changes using a similar tone to the message above.
> 
> 
> We've put in a lot of thought into (1) to make this possible. AnkiDroid still has a fair number of ducks to put in order with regards to ecosystem compatibility, and wherever possible, we should be **positively** contributing upstream, so changes can flow downstream, rather than applying pressure by breaking compatibility.


I'm very happy to see this feature in the new reviewer.
However, if using the new reviewer, gestures are no longer supported.

**Comment by domonnss** [comment] 2025-06-24 08:36
> 1. Already exists for the new reviewer
> 
> 2. We should make **strong** attempts to avoid deviating from upstream, and when we do, we should do so in a way which doesn't provide leverage for people to pressure upstream. ESPECIALLY when it gives people justification to request changes using a similar tone to the message above.
> 
> 
> We've put in a lot of thought into (1) to make this possible. AnkiDroid still has a fair number of ducks to put in order with regards to ecosystem compatibility, and wherever possible, we should be **positively** contributing upstream, so changes can flow downstream, rather than applying pressure by breaking compatibility.


I'm very happy to see this feature in the new reviewer.
However, if using the new reviewer, gestures are no longer supported.
I hope you can fix it.

OK, I found that guys are working on it https://github.com/ankidroid/Anki-Android/issues/18559
