### ISSUE TITLE
[Bug] {{}} tags not handled the same way in Anki Desktop and Ankidroid

### ISSUE THREAD

**Issue by iCarlosCode** [ankidroid/Anki-Android#8010] opened 2021-01-11 18:32 UTC
Anki Desktop do not display {{tts en_US:Front}} or any other tts tag.
Ankidroid is displaying {{tts en_US:Front}} as if it was a {{Front}} tag, which is not the case. 
{{tts en_US:Front}} and other tts tags should not be displayed on Ankidroid when you review or preview a card.

###### Reproduction Steps

1. Open the navigation drawer by tapping the button on the top left of the screen
2. Tap "card browser"
3. Tap on a note to edit it
4. Tap "Cards:" at the bottom
<img src="https://user-images.githubusercontent.com/69172891/104220082-bdcc4e00-541d-11eb-8633-47eedd2a7646.png" width="30%" height="30%"></img>
5. Type "{{tts en_US:Front}}" below "{{Front}}" to have Anki read the Front field in a US English voice on Windows.
<img src="https://user-images.githubusercontent.com/69172891/104220104-c6248900-541d-11eb-8c3d-538d51740d13.png" width="30%" height="30%"></img>

###### Expected Result
**EXPECTED RESULT ON WINDOWS:**
![TTSONWINDOWS](https://user-images.githubusercontent.com/69172891/104220256-ff5cf900-541d-11eb-8317-e574fd42186c.png)

**EXPECTED RESULT ON ANDROID:**
<img src="https://user-images.githubusercontent.com/69172891/104220310-13085f80-541e-11eb-8acc-68ed4e2627e3.png" width="30%" height="30%"></img>

###### Actual Result
**ACTUAL RESULT ON WINDOWS:**
![TTSONWINDOWS](https://user-images.githubusercontent.com/69172891/104220272-0552da00-541e-11eb-99ec-39123fd0323d.png)

**ACTUAL RESULT ON ANDROID:**
<img src="https://user-images.githubusercontent.com/69172891/104222777-86f83700-5421-11eb-80ca-eb0794966922.png" width="30%" height="30%"></img>

###### Debug info
AnkiDroid Version = 2.14.3
Android Version = 8.1.0
ACRA UUID = 0aad9384-47fc-4d67-aa52-6ee69790144f
Scheduler = std
Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ X] I have searched for similar existing issues here and on the user forum
- [ X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by iCarlosCode** [comment] 2021-01-11 18:51
I think the solution should be to detect all tags related to Text to Speech and hide them.
All tags: [https://docs.ankiweb.net/#/templates/fields?id=text-to-speech](url)

**Comment by Ekagra** [comment] 2021-03-11 12:13
I want to work on this issue, can someone kindly assign me ?

**Comment by mrudultora** [comment] 2021-03-15 10:04
@iCarlosCode Yes, the link you mentioned states that clearly,

> AnkiDroid does not currently support this method.

**Comment by david-allison-1** [comment] 2021-03-15 10:14
I believe this is a duplicate of #5793. Likely to be fixed in AnkiDroid 2.16.

**Closed by david-allison-1** 2021-03-15 10:14 UTC
Labels: Anki Ecosystem Compatibility, Help Wanted

**Comment by iCarlosCode** [comment] 2021-03-24 17:26
Yeah, it's a duplicate. I should have searched more. Sorry.😅

**Comment by david-allison-1** [comment] 2021-03-24 17:31
No worries! Thanks for reporting
