### ISSUE TITLE
Show remaining setting

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#14374] opened 2023-09-02 08:36 UTC
Show remaining in Settings - Appearance should be greyed/inactive when Show top bar is off.
Remaining card count is not shown when the top bar is disabled.
![Screenshot_20230902_102654_AnkiDroidA.png](https://github.com/ankidroid/Anki-Android/assets/10192661/3f289b5c-9a64-43e9-a892-a5e576a940c9)

**Comment by user1823** [comment] 2023-09-02 09:59
Duplicate of https://github.com/ankidroid/Anki-Android/issues/13919

**Closed** 2023-09-04 00:00 UTC
