### ISSUE TITLE
Notification only shown when app is opened

### ISSUE THREAD

**Issue by loewexy** [ankidroid/Anki-Android#4615] opened 2017-04-04 19:19 UTC
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Enable notifications on more than 10 due cards.
2. Enter some Cards
3. Wait until more than 10 cards are due. 

###### Expected Result
A notification should be shown without opening the app.

###### Actual Result
I have to open the app, then a notification is shown. But this does not make sense as I can see the due cards in the allready opened app.

###### Debug info
AnkiDroid Version = 2.8.2
Android Version = 6.0.1
ACRA UUID = 78549792-7916-4041-a6b2-b58d85214139

**Comment by timrae** [comment] 2017-04-05 00:22
![screenshot from 2017-04-05 09-21-19](https://cloud.githubusercontent.com/assets/2818274/24684501/69cb1bbc-19e1-11e7-8b33-72e98be63799.png)

**Comment by timrae** [comment] 2017-04-05 00:28
Although we can probably remove this limitation without much work thanks to #4450

**Comment by loewexy** [comment] 2017-04-05 12:44
Ok yes this fixes the problem, it would be nice if it was possible without the widget. But in the meantime I just replaced the shortcut with the widget.

**Comment by Nutomic** [comment] 2017-04-20 02:49
@timrae How would you implement this? It seems like BootService already has some code for this, calling ReminderService every day. I guess the easiest solution would be a permanent background service, that checks the number of due cards every hour or so. All the existing services could be merged into this single service.

**Comment by timrae** [comment] 2017-04-20 04:20
@Nutomic 
I haven't really been through @madhead's code in a lot of detail so I'm not sure how I would implement it. Is BootService already running permanently, or does it only run when it needs to? We have to be careful not to inadvertently reduce battery life of users that have not opted into reminders.

**Comment by madhead** [comment] 2017-04-20 08:56
`BootService` is not running permanently. It is a one-shot service that runs just after device restart. It's purpose is to enable alarms for every deck that is configured for notifications. Also, you don't need to run service permanently to notify the user, I think alarms can do that, but they are reset after restarts, that's why you need a `BootReceiver` and `BootService`

**Comment by moshpirit** [comment] 2017-04-29 14:15
I'm using KISS launcher, which doesn't allow to use widgets (to keep it simple). How long do you think it would take to implement this feature?

Thanks a lot for this great app!!

**Comment by damccull** [comment] 2017-08-12 01:36
I would like to suggest not running a service permanently. Android offers something called an alarm. You can set an alarm when you first run the app that will be maintained by the system itself. When the alarm is up, it can call an intent to start the service, which should then check the cards due, notify if required an then set another alarm and shut itself down. You can also set the service to auto start on system boot, I believe, to accomplish this the first time after a boot.

This approach gives you the same effect you want without leaving the application running constantly in the background as a service. It saves battery, cpu, and ram, and will keep the app from being killed by those ridiculous memory manager apps everyone's always downloading.

Please tag me reply if you need any further info from me.

**Comment by damccull** [comment] 2017-08-12 01:37
Yeah @madhead already seems to have set that up...so can we get notified without the widget please? 😁

**Comment by timrae** [comment] 2017-08-12 01:38
A pull request would be appreciated... Nobody is working on this AFAIK

On 12/08/2017 10:37, "damccull" <notifications@github.com> wrote:

Yeah @madhead <https://github.com/madhead> already seems to have set that
up...so can we get notified without the widget please? 😁

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/4615#issuecomment-321949260>,
or mute the thread

**Comment by madhead** [comment] 2017-08-12 02:19
I remember that we pulled out the code for this feature out of master because of some non-reproducible bugs on some devices.

**Comment by timrae** [comment] 2017-08-12 02:21
I didn't pull it from master, just from the release version. The hope was
that someone would fix all the issues for v2.9 ;)

**Comment by damccull** [comment] 2017-08-12 03:30
I will download the code and look at it. No promises. Which pr or branch?

**Comment by damccull** [comment] 2017-08-12 03:32
Also do you know what bugs and devices? Is there an issue to reference?

**Comment by timrae** [comment] 2017-08-12 03:38
@madhead's code is in master, refer to the PR for the code and unresolved issues:
https://github.com/ankidroid/Anki-Android/pull/4450

That PR doesn't address the specific issue in this thread though, as those notifications are separate from the notifications based on how many cards are due that are currently tied to the widget.

**Comment by damccull** [comment] 2017-08-12 03:40
Understood, but if I can find a way to fix that pr in the process of doing
this (assuming I can) i might as well. Thanks. No promises.

**Comment by timrae** [comment] 2017-08-12 03:41
Thanks, I'm sure a lot of people would appreciate it if you do end up getting the time to do that!

**Closed** 2017-09-13 04:41 UTC
Labels: advanced-reminders, enhancement, Priority-Low, Widget
