### ISSUE TITLE
[Bug] cannot find my card and wrong number of cards is shown in the card browser

### ISSUE THREAD

**Issue by Andrej-Adamenko** [ankidroid/Anki-Android#9012] opened 2021-05-30 05:44 UTC
###### Reproduction Steps
1. Switch from `Decks` to `Card browser` 
2. Type a specific query 
3. The card is not found in `Default` deck, which is correct
4. Try "search all decks" at the bottom
5. The card is still not found, though it should be. The total number of the cards at the top bar is incorrect.
6. Repeat the search. Still not found.
7. As a workaround, switch to `All decks` at the top of the browser.
8. Now the total number of the cards in the collection is correct
9. Repeat the search. Now the card is found. 

See this screenshot video:
https://youtu.be/iMPYh0ygCmE

###### Debug info
AnkiDroid Version = 2.15.2

Android Version = 10

Manufacturer = samsung

Model = SM-A920F

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-A920F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.77 Mobile Safari/537.36

ACRA UUID = 1b392f85-2b0c-4491-b153-fdb7fb7b8d34

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by prateek-singh-3212** [comment] 2021-05-30 06:00
Thanks @Andrej-Adamenko for reporting this issue. I think this is duplicate #8975 and we have fixed this issue with #8998. Fix will be public in 2.15.3 release.

**Comment by Andrej-Adamenko** [comment] 2021-05-30 06:02
#9013 might be related

**Comment by prateek-singh-3212** [comment] 2021-05-30 10:32
We already solved this issue. I think it will be out  in 2.16 release. I appreciate your effort to find the bug in Ankidroid.

**Comment by david-allison-1** [comment] 2021-05-30 15:11
Not related. This is new, and exists in both `master` and `2.15.2`

**Comment by ShridharGoel** [comment] 2021-05-31 18:52
@david-allison-1 This is a duplicate of #8975 and already fixed in #8998 as mentioned by @prateek-singh-3212.

**Comment by ShridharGoel** [comment] 2021-05-31 18:54
@david-allison-1 As already mentioned by @prateek-singh-3212, this is a duplicate of #8975 and has been already fixed in #8998.

**Closed** 2021-05-31 18:58 UTC
Labels: Bug, Priority-High
