### ISSUE TITLE
[BUG]: In the tags, letters like "š, č, ć, ž..." do not appear.

### ISSUE THREAD

**Issue by Milann977** [ankidroid/Anki-Android#16496] opened 2024-05-28 17:47 UTC
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

...

### Expected behaviour

...

### Actual behaviour

 Hello! After the latest update of Anki, the following error occurred: namely, the letters like "š, č, ć, ž..." are not appearing in the tags. For example, I had a tag "brašno" (Serbian word for "flour"), and now it shows "braano" instead. Is there a way to revert to the old version of Anki, or do I have to wait for a new update where this will be fixed? Thank you and all the best!

### Debug info

```text
...
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment] 2024-05-29 08:08
2.18.2
* #16476
* #16482

2.18.3:
* #16490
* #16491

Thanks for the report. Closing as a duplicate of the above

**Closed by david-allison** 2024-05-29 08:08 UTC
Labels: Bug, Needs Triage
