### ISSUE TITLE
Different scheduling dates between Ankidroid and Anki [Bug]

### ISSUE THREAD

**Issue by kodovanie** [ankidroid/Anki-Android#9127] opened 2021-06-20 02:43 UTC
Dear all,

I reviewed my Ankidroid cards late at night (19/06/2021) - somewhere at 10pm. The next day (20/06/2021) (4 and a half hours after midnight), Ankidroid does not show any cards - start of next day is set at 0.

On the other hand, if I synchronize the devices, I already have scheduled cards for today (20/06/2021) on Anki, but no scheduled cards in Ankidroid.

I randomly chose one of the cards that are to be reviewed today (20/06/2021) on Anki desktop and it has due date 20/06/2021. The very same card has due date 21/06/2021 when checked in Ankidroid. What is going on?

The same applies for cards scheduled for 21/06/2021 - in Anki desktop they are scheduled for 21/06/2021, in Ankidroid they are scheduled for 22/06/2021. Seems like due dates are shifted in Ankidroid by 1 day.

There is correct date on mobile phone.

**Comment by kodovanie** [comment] 2021-06-20 04:10
Update:

It is now past 6am, and cards scheduled for 21/06/2021 are also visible in Ankidroid (so that they are not scheduled for 21/06/2021 as before, but they are scheduled for 20/06/201 - the same as it is on anki desktop). Still confused why this happened with the setting "start of the next day at 0".

**Comment by mikehardy** [comment] 2021-06-20 16:03
Hi there! We ask for certain information in our new issue template, because we really need that in order to diagnose problems. Specifically the scheduler information would help

You  have deleted that template and not provided the information. Could you provide it please?

https://github.com/ankidroid/Anki-Android/blob/master/.github/ISSUE_TEMPLATE/issue_template.md

**Comment by kodovanie** [comment] 2021-06-20 19:03
Hi there! Sorry about that.

###### Reproduction Steps

1. Reviewed my Ankidroid cards late last night (19/06/2021) - somewhere at 10pm.
2. The next day (20/06/2021) (4 and a half hours after midnight), Ankidroid does not show any cards due for today (20/06/2021) - even though the start of next day is set at 0.
3. I synchronized the devices (Ankidroid with Anki desktop), I already had scheduled cards for today (20/06/2021) shown on Anki, but no due cards shown in Ankidroid.
4. I randomly chose one of the cards that was to be reviewed today (20/06/2021) on Anki desktop and it had due date 20/06/2021. The very same card had due date 21/06/2021 when checked in Ankidroid. Both PC and mobile use the same time and date and the "Ankis" were synchronized.
5. Checking Ankidroid "later" that day (actually it was still morning, right after 6 am), there were suddenly the cards in Ankidroid scheduled for today (20/06/2021) and had correct due dates. Still not sure why there was a shift of 1 day in due date when browsing the same notes in Ankidroid that was already synchronized win Anki.


###### Expected Result
I expected that the notes would be showing correct due dates right after midnight and would be available for learning on the day they are scheduled. It seemed like it was not the case for couple of hours after midnight.


###### Actual Result
 I mean it is working now, it only got me confused why this phenomenom happened for probably six hours (shifting todays cards for tomorrow (when in Ankidroid) and then bringing them back for today).


###### Debug info
AnkiDroid Version = 2.14.6
Android Version = 4.1.2

ACRA UUID = e920e920-d917-4b52-9f53-e465ff8cefa2

Scheduler = std2

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment] 2021-06-22 04:51
Hi, this should be fixed in AnkiDroid 2.15.

Please upgrade, and then enable 'new timezeone code' in Anki Desktop's preferences.

Thanks

**Comment by mikehardy** [comment] 2021-06-30 13:49
can reopen if still reproducible but closing as should be fixed

**Closed by mikehardy** 2021-06-30 13:49 UTC
Labels: Waiting For Feedback

**Comment by Yourself1011** [comment] 2023-02-03 05:22
I'm having this issue again on Anki 2.1.57 and AnkiDroid 2.16alpha92. I have the `new timezone handling` setting enabled on AnkiDroid, and the `Legacy timezone handling` option disabled. I've tried other combinations of these settings to no avail. Checking on AnkiWeb, it seems to agree with AnkiDroid, but I'm somewhat sure this issue started happening after I went to AnkiDroid 2.16.
